import FX1PolyAudit.DependencyAudit
import FX1Poly.Core.Metatheory.Reducibility.Core.DataReducibilityCoverage
import FX1Poly.Core.Metatheory.Reducibility.Candidates.DataTaitCandidate
import FX1Poly.Core.Metatheory.Reducibility.Candidates.FlatCodeTaitCandidate
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FlatCodeCanonicalForms
import FX1PolyAudit.Corpus.MilestoneASpineValueLayer
import FX1PolyAudit.Corpus.MilestoneAEliminatorLayerSpine
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimComputingCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicityTyped
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchGeneralBranchCanonicity
import FX1PolyAudit.Ledger.MetatheoryParityLedger
import FX1Poly.Typed.Engine.Classifier.TypingContext
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeShape
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeConversion
import FX1Poly.Typed.Engine.Formation.SigmaCodeShape
import FX1Poly.Typed.Engine.Formation.ListCodeShape
import FX1Poly.Typed.Engine.Formation.ListFormationSmoke
import FX1Poly.Typed.Engine.Formation.OptionCodeShape
import FX1Poly.Typed.Engine.Formation.OptionCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.OptionFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationOptionFromTelescope
import FX1Poly.Typed.Engine.Formation.OptionFormationSmoke
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDesc
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescDecidable
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElim
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescValidity
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescClosedForms
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFormerTelescopeInversion
import FX1Poly.Typed.Engine.Formation.DataFormerInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescUniqueness
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPi
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaCoherence
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionGrown
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionComputes
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiWeakening
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiSubstitution
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiValidity
import FX1Poly.Typed.Metatheory.Universe.ConvCodeInjectivity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ConvBoolCodeRigidity
import FX1Poly.Typed.Engine.Formation.ConvFormationFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvCrossTableFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatCodeInjectivity
import FX1Poly.Typed.Engine.Formation.ConvDataCodeInjectivity
import FX1Poly.Typed.Metatheory.Universe.EmptyTypeCodeConvRigidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.EmptyTypeValueInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FormationCanonicalForms
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.PiTypeFunctionInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalForms
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafety
import FX1Poly.Typed.Engine.Formation.FormationTypeSafety
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsNonVacuity
import FX1Poly.Typed.Corpus.Smoke.GrownBetaRedexInAction
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgress
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownOpenCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafetyUnconditional
import FX1Poly.Typed.Engine.Formation.FormerStepInversionGeneric
import FX1Poly.Typed.Metatheory.SubjectReduction.SubjectReductionAtFormerGeneric
import FX1Poly.Typed.Engine.WfContext.WfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescValidity
import FX1Poly.Typed.Engine.WfContext.WfContextDescUniqueness
import FX1Poly.Typed.Engine.WfContext.WfContextDescPi
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiFromWfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiClassifierValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiFunctionComponentValidity
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionDescPi
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionMutual
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnv
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAt
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvTypeVariable
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprFT
import FX1Poly.Typed.Metatheory.Reducibility.Pi.AbstractionNonDependentUnderSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprReducibleLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermFundamentalLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInversionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprClosureLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermRenameLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1Poly.Typed.Metatheory.SimplyTyped.MilestoneA0SimplyTypedFloor
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1Poly.Tier0.Context.Instances.Renaming.FxRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecIsomorphism
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecPreimage
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTryTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecRMC
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecGlobalSections
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecSconingPreservation
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstVec
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstCategory
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWeakening
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstComprehension
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstSingleton
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstGlobalSections
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWitnessScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstConcreteScone
import FX1Poly.Tier0.Context.IsomorphismCategorical
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeRMC
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeGlobalSections
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1Poly.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1Poly.Core.Rewriting.Reduction.Head.RootStepDispatch
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnce
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1Poly.Core.Rewriting.Normalize.Normalize
import FX1Poly.Core.Rewriting.Normalize.NormalizeSteps
import FX1Poly.Core.Rewriting.Conversion.ConvDecisionSteps
import FX1Poly.Core.Rewriting.Normalize.NormalizeMeta
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsWeakHeadExpansion
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.BoolElimCanonicalComputation
import FX1Poly.Core.Eliminators.Bool.BoolElimClosedMembership
import FX1Poly.Core.Eliminators.Core.DataEliminatorMembershipSmoke
import FX1Poly.Core.Metatheory.Canonicity.SigmaProjectionCanonicalComputation
import FX1Poly.Core.Metatheory.Canonicity.IdentityEliminatorCanonicalComputation
import FX1Poly.Core.Eliminators.Identity.IdEliminatorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.OptionEitherMatchCanonicalComputation
import FX1Poly.Core.Eliminators.Match.MatchClosedMembership
import FX1Poly.Core.Eliminators.Sigma.SigmaProjectionClosedMembership
import FX1Poly.Core.Eliminators.Recursor.RecursorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.RecursiveEliminatorBaseComputation
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.DataCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.ModalCanonicityViaSconing
import FX1Poly.Core.Metatheory.Sconing.DataMetatheoryViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1Poly.Core.Metatheory.Sconing.ConsistencyViaSconing
import FX1Poly.Core.Eliminators.Core.DataEliminatorProgressViaSconing
import FX1Poly.Core.Eliminators.Recursor.RecursiveEliminatorProgressViaSconing
import FX1Poly.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.UnitCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EmptyCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingSubst
import FX1Poly.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1Poly.Core.Metatheory.Normalization.Core.WeakNormalization
import FX1Poly.Core.Rewriting.Normalize.NormalFormUnique
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevels
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllFormerChildren
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPiIntro
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Pi.NeutralFuelStability
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiTypeSaturationReassembly
import FX1Poly.Typed.Metatheory.Reducibility.Pi.StrongNormalizingAllLevelPiComponents
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescopePositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllCanonicalCandidate
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllVectorPremises
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllNonDependentBinders
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtUniformVectorPremises
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFundamentalVectorFromFormation
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFundamentalAtAllFromGenFormation
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClosedLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.TypeFundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LeveledContext
import FX1Poly.Typed.Corpus.Smoke.ClosedSNSmoke
import FX1Poly.Typed.Corpus.Smoke.UntypedOmegaNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.StepNonDeterministic
import FX1Poly.Typed.Metatheory.Normalizer.ConvValueDiscrimination
import FX1Poly.Typed.Corpus.Smoke.TypedLambdaDerivations
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleans
import FX1Poly.Typed.Corpus.Church.Core.TypedChurchNegation
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumerals
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIteration
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralDiscrimination
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralThree
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralTyping
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralInhabitants
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralComputeGeneral
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralAddition
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralMultiplication
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralSemiringLaws
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIsZero
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleanOperations
import FX1Poly.Typed.Corpus.Smoke.TypedFragmentAcyclicity
import FX1Poly.Typed.Corpus.Smoke.UnboundedGrowthNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointDivergence
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointCombinator
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryLogic
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryCompleteness
import FX1Poly.Typed.Corpus.Church.Combinators.SymbolicSCombinatorRule
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairs
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairsInjective
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSums
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsDisjoint
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsGeneral
import FX1Poly.Typed.Corpus.Church.Lists.ChurchLists
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListIsEmpty
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAny
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAll
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBooleanComplementLaws
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBoolXor
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListFirstOr
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSucc
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSuccApplies
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListLength
import FX1Poly.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1Poly.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1Poly.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseNoTop
import FX1Poly.Typed.Metatheory.Universe.TypedUniversePredicative
import FX1Poly.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1Poly.Typed.Corpus.Progress.ClosedNormalForm
import FX1Poly.Typed.Metatheory.Normalizer.ClosedNonConvertibility
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTyping
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiStronglyNormalizingFromFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVecTypeVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConsistency
import FX1Poly.Typed.Engine.Formation.HasTypeFormationNoLambdaApplication
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleSemanticRules
import FX1Poly.Typed.Engine.Formation.ListCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.ListFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberFormation
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeInversion
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeReach
import FX1Poly.Typed.Engine.RuleTables.FlatDescTelescope
import FX1Poly.Typed.Metatheory.Canonicity.Core.StandaloneEngineCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.CombinedBoolCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedBoolCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicitySyntacticRoute
import FX1Poly.Typed.Metatheory.Canonicity.Core.GrownRigidityCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedNatCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimValueCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.NatElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulArithmetic
import FX1Poly.Typed.Metatheory.Reducibility.Core.ClosedNumeralSubstInvariant
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulMul
import FX1Poly.Typed.Corpus.Faithfulness.ValueElimHostFold
import FX1Poly.Typed.Corpus.Faithfulness.RecursorHostFold
import FX1Poly.Typed.Metatheory.Canonicity.Core.ListElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.ListElimFaithfulLength
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicity
import FX1Poly.Typed.Corpus.Progress.GrownClosedNormalClassifierShape
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ClosedNormalEmptyConsistency
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ProductEitherCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.OptionCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ListCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.IdCanonicalForms
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiFormerMembership
import FX1Poly.Typed.Engine.Formation.FormerChildrenReducible
import FX1Poly.Typed.Metatheory.Reducibility.Telescope.TelescopeReducible
import FX1Poly.Typed.Metatheory.Universe.UniverseDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsInduction
import FX1Poly.Typed.Metatheory.Reducibility.Pi.ReducibleTypeAtAllLevelsPiNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsWhnfDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsPiDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsPiMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsHeadExpand
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsConv
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Strengthening.RouteAObstruction
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelDiagnosis
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelMeasure
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibility
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibilitySmoke
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPi
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedLevelIrrelevance
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseFormationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCanonicalMemberCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationFromExistence
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGeneralDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSingleLevelPi
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiAboveThreshold
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormerAtLevel
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleTypeLevelLift
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiArmDischarge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedApplicationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedConvMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberForwardClosed
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMemberBetaExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberWeakHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiElim
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalConv
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAmbientLevelBridge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrow
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedClosedMember
import FX1Poly.Typed.Metatheory.Denote.Telescope.DenoteKeyedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedUniformReducible
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMembershipIntro
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFormation
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFromChildMembers
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationSigmaArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedCumulativityObstruction
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibility
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedConvArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiElimArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiIntroArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedFormerEngine
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiDischarge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedAssemblyBridge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeProjection
import FX1Poly.Typed.Engine.Formation.FormerOutputLevelBounds
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedCodomainOpenSN
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDomainInhabitant
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationPiFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationSigmaFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationListFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedTelescopeConsSucc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGrownDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDesc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPi
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPiDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedGrownFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ClosedBoundedReducibleMember
import FX1Poly.Typed.Corpus.Smoke.ClosedStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedNeutralMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseInversion
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBindingTypeReducible
import FX1Poly.Typed.Engine.WfContext.ReducibleEnvOfWfContext
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizingUnconditional
import FX1Poly.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1Poly.Typed.Corpus.Smoke.OpenSNSmoke
import FX1Poly.Typed.Corpus.Progress.ContextValidityFails
import FX1Poly.Typed.Equality.UnitEta.UnitEtaJudgmentalEquality
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruenceGap
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruentEquality
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapse
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseIncompleteness
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeep
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseNeutralBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitNeutralSpineDetection
import FX1Poly.Typed.Equality.UnitEta.UnitSpineDetectionBoundary
import FX1Poly.Typed.Equality.UnitEta.TypeDirectedUnitReadback
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackArgumentBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackFormerChildBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackDeepSpineBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackAnnotationBoundary
import FX1Poly.Typed.Engine.Formation.FormationClassifierRigidity
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Pi.LiftedChildNormalizationFromClosure
import FX1Poly.Typed.Engine.RuleTables.TelescopeSubstitutedChildrenNormalization
import FX1PolyAudit.Ledger.CascadeFreedomLedger
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyTargetSignature
import FX1PolyAudit.Corpus.CandidateBridgeEditViability
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicityTargetSignature
import FX1Poly.Typed.Metatheory.Universe.NullaryFormerFormation
import FX1Poly.Typed.Metatheory.Universe.GrownUniverseFormationStrictness
import FX1Poly.Typed.Engine.Formation.GrownFormerFormationStrictness
import FX1Poly.Typed.Engine.Classifier.GrownTypingNotUnique
import FX1Poly.Typed.Engine.Classifier.GrownEngineHonesty
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.GrownUniverseConsistency
import FX1Poly.Typed.Engine.Classifier.GrownVariableHonesty
import FX1Poly.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiLamInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiAppInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVarInversion
import FX1Poly.Typed.Metatheory.ContextConversion.VarHeadedAppContextConversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiBetaSR
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiCongruence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerCongruence
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionConditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimReduction
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionValidityReduction
import FX1Poly.Typed.Corpus.Progress.GrownMutualMetatheoryFromPiValidity
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimEquivalence
import FX1Poly.Typed.Engine.HasTypeDescPi.ContextConversion.HasTypeDescPiContextStepConversion
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionUnconditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionFlexibleUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormationFragment
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormerStep
import FX1Poly.Typed.Metatheory.ContextConversion.GenFormerValidityContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPiValidityModelNeutral
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveled
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransport
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransportUnderWf
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledCompleteness
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValid
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRename
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValidLookup
import FX1Poly.Typed.Metatheory.ContextConversion.PiElimClassifierConvResidual
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiFormerInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiDataHeadUntyped
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiRootGeneric
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedUniverseBoundedCumulativity
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedClosedTypeCodeSN
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiMemberSN
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrowMemberSN
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCodomainMemberWiring
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelSpike
import FX1PolyAudit.Ledger.SNStrategy
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.LogRelSpec
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LevelingBridge
import FX1Poly.Typed.Metatheory.Canonicity.Core.ConsistentStratification
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingLevelFlexible
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingRefinedMotive
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingConvArm
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingPiArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingFormerArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingVariableLevelPinned
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalReduction
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalAssembly
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.SimplyTyped.HigherOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiOverNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiNeutralCodomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentlyTypedNeutralDomainFragment
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedSubsumption
import FX1Poly.Typed.Metatheory.Universe.UniverseCumulativity
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermReducibility
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiTypingNonUnique
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckOfInferred
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVariableInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiUniverseCodeInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplicationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationCodomainReTyping
import FX1Poly.Typed.Engine.RuleTables.IntroRuleDesc
import FX1Poly.Typed.Engine.RuleTables.ElimRuleDesc
import FX1Poly.Typed.Engine.RuleTables.GenElimIotaComputation
import FX1Poly.Typed.Engine.Classifier.TypingRoleClassifier
import FX1Poly.Typed.Engine.Classifier.TypingRoleEngineBridge
import FX1Poly.Typed.Engine.Classifier.TypingRoleCoverage
import FX1Poly.Typed.Engine.Classifier.UntypableHeadDecision
import FX1Poly.Typed.Engine.Classifier.TypingHeadKindClassifier
import FX1Poly.Typed.Engine.Classifier.TypedBySomeEngine
import FX1Poly.Typed.Engine.Classifier.GeneratorSemanticTier
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyOverview
import FX1Poly.Typed.Engine.Classifier.StaticTypingSoundness
import FX1Poly.Typed.Engine.Classifier.SemanticTierSoundness
import FX1Poly.Typed.Engine.Classifier.ClassifierRefinement
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyLedger
import FX1Poly.Typed.Metatheory.Normalizer.CertifiedWordReductionTermination
import FX1Poly.Typed.Metatheory.Normalizer.CertifiedWordReductionConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerStepDomainFormationCodomain
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionFormerArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionInlineArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionConvOfFormationArms
import FX1Poly.Typed.Metatheory.SubjectReduction.ConsistencyConditionalOnSubjectReduction
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencySyntactic
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyOfPiElimArm
import FX1Poly.Typed.Metatheory.ContextConversion.PiElimUpToClassifierConv
import FX1Poly.Typed.Engine.Classifier.ClassifierRespectsConvRefuted
import FX1Poly.Typed.Dimensions.AxisObligation.TypedCertificationStackingRefuted
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencyUnconditional
import FX1Poly.Typed.Engine.Formation.FormationNormalSmoke
import FX1Poly.Typed.Engine.Formation.BoolTypeCodeSubstrate
import FX1Poly.Typed.Engine.Formation.NatTypeCodeSubstrate
import FX1Poly.Typed.Corpus.Progress.GrownNoTypeInType
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescRigidity
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidable
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1PolyAudit.Corpus.KnownUnsoundnessCorpus
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationAcyclic
import FX1Poly.Dimensions.Security.SecurityNoninterferenceGeneral
import FX1Poly.Dimensions.Graded.GradedApplicationFlow
import FX1PolyAudit.Corpus.MetatheoryFuzz
import FX1PolyAudit.Corpus.FuzzCorpusConvertibility
import FX1PolyAudit.Corpus.FuzzCorpusNormalizes
import FX1PolyAudit.Corpus.LambdaValueFuzzFamily
import FX1PolyAudit.Corpus.MechanizedProofCrossReference
import FX1PolyAudit.Corpus.FormalReviewGate
import FX1PolyAudit.Corpus.SelfVerifiedMetatheory
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengthening
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheck
import FX1Poly.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1Poly.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiImageComponents
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiRenameImage
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionContext
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiIntro
import FX1Poly.Typed.Engine.Formation.FormationPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.GrownPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimCore
import FX1Poly.Typed.Corpus.Smoke.GrownWfOpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimDispatcher
import FX1Poly.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1Poly.Typed.Metatheory.Strengthening.GuardedPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PlateauPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.NeutralReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionLamClassifierResidual
import FX1Poly.Typed.Metatheory.Strengthening.FlagCoherentReflectionCondition
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.NeutralClassifierUnique
import FX1Poly.Typed.Metatheory.Universe.NormalAppNeutral
import FX1Poly.Typed.Engine.RuleTables.TelescopeUniverseDeterminism
import FX1Poly.Typed.Engine.RuleTables.GenericFormerTelescopeInversion
import FX1Poly.Typed.Metatheory.Universe.NormalUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.ConvUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Strengthening.RenameAlongFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.PinSelectsCallerPair
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.LamReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherentMaster

/-! # FX1PolyAudit.Typed.Shards.ConvRigidity.Part03 — zero-axiom gate shard (part 3/5 of AuditTypedConvRigidity)

Chunk-split slice of the former monolithic `AuditTypedConvRigidity` semantic shard so each audit file
stays under the per-file eval ceiling and elaborates in parallel.  Import block and eval
lines are preserved byte-for-byte; the old flat module re-exports every part. -/

#assert_no_axioms FX1Poly.Typed.Conv.boolTypeCell_not_sigmaTyCode
#assert_no_axioms FX1Poly.Typed.Conv.boolTypeCell_not_universeCode
#assert_no_axioms FX1Poly.Typed.Conv.formationFormersNotConvOfDistinct
#assert_no_axioms FX1Poly.Typed.Conv.listCode_not_conv_optionCode
#assert_no_axioms FX1Poly.Typed.Conv.flatFormationFormersNotConvOfDistinct
#assert_no_axioms FX1Poly.Typed.Conv.productCode_not_conv_sumCode
-- CROSS-TABLE discrimination (ConvCrossTableFormerRigidity.lean): completes the cross-former no-confusion —
-- a typingRuleDescOf-former (Π/Σ/list/option) is never Conv to a flatTypingRuleDescOf-former
-- (product/sum/either/arrow/equiv). NO disjointness helper needed: the LEFT uses formationFormerHeadStable
-- General, the RIGHT uses flatFormationFormerHeadStableGeneral, then per-instance g1 != g2 (Generator.no
-- Confusion). THIS is the load-bearing SN-049 rule-out: a closed normal t:productCode has head in
-- {lam,piTyCode,...} (all typingRuleDescOf-classified), and piTyCode_not_conv_productCode etc. refute each.
#assert_no_axioms FX1Poly.Typed.Conv.crossTableFormersNotConvOfDistinct
#assert_no_axioms FX1Poly.Typed.Conv.piTyCode_not_conv_productCode
#assert_no_axioms FX1Poly.Typed.Conv.sigmaTyCode_not_conv_eitherCode
-- GrownCtxConv-5 REDUCTION (PiElimUpToClassifierConv, VAL-1 #1039): the grown context-conversion piElim arm — the
-- entangled crux #842 — closes given EXACTLY ONE property, classifierRespectsConv (type-Conv-closure: IsTypeDescPi
-- respects Conv). piElimUpToClassifierConv rebuilds appCell fn arg from the mutual-IH re-typings (fn at a type
-- Conv to piTyCodeCell D C, arg at a type Conv to D) using ONLY shipped pieces: classifierIsTypeDescPi (validity,
-- unconditional) + classifierRespectsConv (the lone residual hypothesis) + two conv-rule re-ascriptions
-- (universe witnesses from the Pi-code's IsType + inversionPiCodeComponents) + piElim, landing at subst0 C arg
-- on the nose. So GrownCtxConv-5 = one lemma; the reflect (reducible-type -> typed) is the VAL-2 residual (the universe
-- candidate IS IsReducibleType, Conv-invariant via #537). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.piElimUpToClassifierConv
-- GrownCtxConv-5-REFUTE (#1058, ClassifierRespectsConvRefuted): ★ classifierRespectsConv_isFalse — the VAL-1 GrownCtxConv-5
-- reduction target (classifierRespectsConv : IsType A → Conv A B → IsType B) is PROVABLY FALSE.
-- Counterexample: A = Type@0 (a type), B = (λ_.Type@0) Ω. B β-reduces to A (classifierConvCounterexampleRedex_
-- stepsToType: the body Type@0 discards Ω), so Conv A B; A isType (classifierConvCounterexampleType_isType, via
-- universe-formation); but B is NOT a type (classifierConvCounterexampleRedex_notType: invertApp would type the
-- discarded argument Ω, contradicting omegaCombinator_notClosedWellTyped #958). So VAL-2 as planned is impossible.
-- DEEP FINDING: grown typing requires EVERY subterm typed (even a discarded argument), so IsTypeDescPi is NOT
-- Conv-invariant. REDIRECT: the real piElim arm keeps the SOURCE fn:piTyCode D C derivation (D,C genuinely typed
-- by validity) and context-converts that formation (GrownCtxConv-4), NOT the lossy Conv-to-piTyCode. Zero-axiom: Step.beta
-- + invertApp + omega-untypable + universeFormation + Conv.fromStepStar.
#assert_no_axioms FX1Poly.Typed.classifierConvCounterexampleRedex_stepsToType
#assert_no_axioms FX1Poly.Typed.classifierConvCounterexampleType_isType
#assert_no_axioms FX1Poly.Typed.classifierConvCounterexampleRedex_notType
#assert_no_axioms FX1Poly.Typed.classifierRespectsConv_isFalse
-- Conv VALUE NON-DEGENERACY (ConvValueDiscrimination): the contrapositive of Conv.eq_of_noStep — distinct closed
-- normal-form values are NOT convertible. normalLeavesNotConvertibleOfDistinctRoot: two no-step terms with
-- distinct head generators ⟹ ¬Conv (Conv.eq_of_noStep collapses Conv→Eq, congrArg rootGenerator refutes).
-- boolTrue ≢ boolFalse + boolTrue ≢ unit concretely; convIsNonDegenerate (★ ∃ a b, ¬Conv a b) is the value-
-- discrimination sanity property canonicity rests on (if Conv collapsed values, every type would be inhabited
-- and the theory inconsistent). Distinct from Conv-INJECTIVITY (#947/948, same-head decomposition).
#assert_no_axioms FX1Poly.Typed.normalLeavesNotConvertibleOfDistinctRoot
#assert_no_axioms FX1Poly.Typed.boolTrueValue_notConvertible_boolFalseValue
#assert_no_axioms FX1Poly.Typed.convIsNonDegenerate
#assert_no_axioms FX1Poly.Typed.betaRedexConvertsToReduct
#assert_no_axioms FX1Poly.Typed.closedUniverseCode_not_conv_identity
#assert_no_axioms FX1Poly.Typed.closedUniverseCode_not_conv_piCode
#assert_no_axioms FX1Poly.Typed.closedIdentity_not_conv_piCode
-- LEG-2 RECURSOR (ValidTyping.lean): the level-annotated typing (Abel validity-derivation-indexed relation),
-- now spanning var/universeFormation/conv/piIntro/piElim/piFormation/sigmaFormation — the leaf+conv core, the
-- COMPUTATIONAL core (λ-introduction + application, where β-redexes live), AND the Π/Σ TYPE-former core. var/conv
-- level coordination resolved BY CONSTRUCTION (var at contextLevels index; conv's reclassifier at subjectLevel+1;
-- piIntro's body under levelCons at predLevel+1, codes at predLevel+1+1; piElim shares subjectLevel; the formers
-- carry ∀-level-quantified domain children — a type code's universe membership is fuel-polymorphic — which the
-- recursor lifts to ∀-quantified IHs feeding fundamentalPiFormationLevelIndexed/…Sigma…). So ValidTyping.fundamental
-- is a CLEAN single induction (ValidTyping.rec) threading the seven shipped level-indexed arms.
-- closedStronglyNormalizing = SN-for-well-typed (core, closed) via the recursor; validTyping_identity… shows the
-- closed identity λx.x lands SN through piIntro; validTyping_{pi,sigma}BetweenUniverses… show closed Π/Σ codes land
-- SN through the former arms. REMAINING for full SN: the GENERIC genFormation arm (table-driven former over an
-- arbitrary telescope, of which Π/Σ are instances) + the HasTypeDescPi→ValidTyping leveling bridge.
-- SN-007 VERIFIED 2026-06-02 (no rebuild): ValidTyping IS the per-binder-leveled validity context — its index is
-- the ABSTRACT (Fin scope → Nat) contextLevels + Nat subjectLevel (depth/fuel levels, NOT denote(LevelExpr)); all
-- seven claimed arms (var/universeFormation/conv/piIntro/piElim/piFormation/sigmaFormation) are present; the var arm
-- produces subjectLevel := contextLevels index by construction (the off-by-one dodge, SN-024); fundamental is PROVED
-- (clean ValidTyping.rec induction) + gated below; it is the consumer the SN-022 bridge composes with. No
-- classifier-universe-level (denote-keyed) variant is built: SN-004 is GO but the fuel-level bridge (SN-022) is not
-- yet shown insufficient, so a variant would be premature duplication (task discipline: do NOT duplicate ValidTyping).
-- SN-021 LANDED 2026-06-02: ValidTyping now also carries the GENERIC table-driven `genFormationPi` ctor (over
-- typingRuleDescOf — Π/Σ as instances), so the leveled relation has cascade-free former coverage matching
-- HasTypeDescPi. The ctor is NON-recursive in ValidTyping (carries DescTelescopePi + the telescopeFundamental
-- reducibility premise — faithful for an Abel VALIDITY relation), so it needed no mutual refactor; the fundamental
-- arm is a one-liner to fundamentalGenFormationFormerLevelIndexed (real former-membership work). Both gates below
-- now cover the extended inductive + theorem zero-axiom (the genFormationPi arm's axiom-cleanliness is checked
-- transitively by the .fundamental gate).
#assert_no_axioms FX1Poly.Typed.ValidTyping
#assert_no_axioms FX1Poly.Typed.validTypingBridgeConv
-- SN-023 (LevelingBridge.lean): the binder + former bridge arms — each mirrors the matching ValidTyping ctor's
-- level discipline (piIntro: codes at predLevel+1+1, body at predLevel+1 under levelCons; piElim: shared level;
-- piFormation/sigmaFormation: the ∀-aboveLevel domain premise SN-025 produces; genFormationPi: the SN-021 ctor).
-- Per-arm TARGET SHAPES given coordinated inputs; the cross-IH coordination + ∀-aboveLevel production is the
-- inductive assembly SN-027 (ValidTyping is NOT level-weakenable — var pins its level — so coordination is the
-- deferred crux, not arm-local).
#assert_no_axioms FX1Poly.Typed.validTypingBridgePiIntro
#assert_no_axioms FX1Poly.Typed.validTypingBridgePiElim
-- SN-027 (refined-motive coordination): validTypingBridgeConvFromAllLevelReclassifier discharges the conv arm's
-- LEVEL alignment — the existential ∃-shape can't force aligned levels, but a REFINED MOTIVE giving type-code
-- subjects an ∀-level conclusion does: conv needs the reclassifier at subjectLevel+1, which is just the
-- subjectLevel-instance of the all-level reclassifier IH. Supersedes the pre-aligned validTypingBridgeConv
-- (SN-022). Type variables (var-pinned) are the sole non-level-flexible type code → reducibility route (SN-025).
#assert_no_axioms FX1Poly.Typed.validTypingBridgeConvFromAllLevelReclassifier
#assert_no_axioms FX1Poly.Typed.ValidTyping.convWithLevelFlexibleReclassifier
-- SN-027 the TOTAL-BRIDGE MOTIVE (#655, ValidTypingRefinedMotive.lean): TotalBridgeConclusion = single-level
-- validity ∧ (NON-VARIABLE subject whose classifier is CONVERTIBLE to a universe code ⟹ level-flexible). The
-- IH-strengthening induction motive that forces the conv/piElim level coordination the bare ∃-shape can't. Two
-- design points: the non-variable guard (∀ index, subject ≠ variableCell index) — a type variable is pinned by
-- ValidTyping.var, cannot be flexible; and the CONVERTIBILITY guard (Conv classifier (Type@e f), not syntactic =)
-- so conjunct-2 propagates through conv by Conv.trans. var arm: conjunct-2 vacuous (subject IS a variable).
-- universeFormation arm: flexibility via universeFormation_isLevelFlexible, convertibility guard met by
-- universeCodeCell_inj_of_conv. RawTerm.isVariableOrNot routes the conv arm onto the guard.
#assert_no_axioms FX1Poly.Typed.TotalBridgeConclusion.var
-- the CONV arm (non-variable reclassifier) of the revised motive. The convertibility guard (Conv classifier
-- (Type@e f), not syntactic =) lets conjunct-2 propagate through conv by Conv.trans; conjunct-1 reclassifies
-- via convWithLevelFlexibleReclassifier (the non-variable reclassifier is level-flexible from its own conjunct-2
-- at Conv.refl). The variable-reclassifier case routes to validTypingBridgeConvPinnedReclassifier (the leveling
-- eq) via RawTerm.isVariableOrNot.
#assert_no_axioms FX1Poly.Typed.TotalBridgeConclusion.convNonVariableReclassifier
-- the conv arm VARIABLE-reclassifier twin (ValidTypingConvArm.lean): conjunct-1 via validTypingBridgeConvPinnedReclassifier
-- (consuming the leveling eq contextLevels index = subjectLevel + 1, the one residual the assembly's leveling
-- discipline supplies); conjunct-2 vacuous (a variable reclassifier is not conv to a universe code). Routed by
-- isVariableOrNot. This COMPLETES the conv arm modulo the leveling equation.
#assert_no_axioms FX1Poly.Typed.TotalBridgeConclusion.convVariableReclassifier
-- the BASE CASE of the level synthesis (ValidTypingConvArm.lean): the conv-variable arm for a FRESHLY-BOUND type
-- variable ⟨0,_⟩ under a binder (contextLevels = levelCons (predLevel+1) tailLevels). The leveling eq
-- contextLevels ⟨0,_⟩ = subjectLevel+1 is discharged BY rfl (levelCons's ⟨0,_⟩ branch = predLevel+1, subject at
-- predLevel) — NO hypothesis. A binder pins its variable's level, so the coordination is automatic; this is where
-- the assembly's level synthesis bottoms out (deeper variables thread the eq through the levelCons tail).
#assert_no_axioms FX1Poly.Typed.TotalBridgeConclusion.convBoundVariableReclassifier
-- the DEEPER tower step (#662): a subject var termIndex whose looked-up type IS the reclassifier type-variable
-- (lookup termIndex = variableCell index, the x:A:Type tower). The leveling eq contextLevels index =
-- contextLevels termIndex + 1 is discharged by the ConsistentStratification invariant at that looked-up edge —
-- this is where the assembly's synthesized level vector pays off (no per-derivation hypothesis).
#assert_no_axioms FX1Poly.Typed.TotalBridgeConclusion.convVariableReclassifierOfStratified

/-! ### FormationClassifierRigidity — ★ brick 8, POSITIVE: literal classifier matching is complete

The post-brick-7 completeness re-analysis closed the suspected 10th-boundary family EMPTY, as
theorems: formation subjects are step-free (`subjectAdmitsNoStep` — the formation engine has no
`piIntro`/`piElim` arms, so formation-typed terms are app-free, redex-free trees), hence
`Conv`-RIGID (`formationSubjects_convRigid` via `Conv.eq_of_noStep`).  Consequently a
formation-typed classifier `Conv` to a Π code literally IS a Π code with `Conv`-related
components (`piCodeDetection_completeOnFormationClassifiers` via `Conv.reducesToPiTyCode` +
chain collapse), `asPiCode?` fires on it (`asPiCode?_firesOnFormationClassifiers`), wf lookups
inherit the completeness (`WfContextDesc.piCodeDetection_completeOnLookups` via
`lookupIsTypeDesc`), and the unit arm's literal test is complete
(`unitDetection_completeOnFormationClassifiers`).  Within the soundness presupposition the
readback's literal dispatch loses NOTHING — `Conv`-disguised type codes are not
formation-typable; the 9th boundary's phenomenon cannot recur at classifier or lookup
positions.  The standing honest-boundary note (2) is RETIRED.  Zero-axiom. -/

#assert_no_axioms FX1Poly.Typed.HasTypeDesc.formationSubjects_convRigid
#assert_no_axioms FX1Poly.Typed.standaloneDataIntroAndBaseTypeSubjectsDisjoint
#assert_no_axioms FX1Poly.Typed.Conv.natTypeCell_not_piTyCode
#assert_no_axioms FX1Poly.Typed.Conv.natTypeCell_not_sigmaTyCode
#assert_no_axioms FX1Poly.Typed.Conv.natTypeCell_not_universeCode
-- Σ/COPRODUCT CANONICAL FORMS (ProductEitherCanonicalForms, the DI-2 payoff): NON-VACUOUS closed-normal
-- canonicity for product/either types, unconditional (no GrownCtxConv-5/§5). NEW rigidity Conv.product/eitherCode_not_
-- universeCode (flat-former twin of boolTypeCell_not_universeCode, via shapeStable + universe leaf + noConfusion)
-- + Conv.piTyCode_not_conv_eitherCode (cross-table). noClosedNormalTermAtProduct/EitherType = CANON-1c rule-out
-- instances (grown engine inhabits no product/either type — Σ/coproduct formation but no introduction). ★ closed
-- NormalProduct/EitherCanonicalForms = a closed-normal term at product/either by the intro engine OR grown is a
-- pairCell / eitherInl-or-Inr cell. The non-vacuous Σ/coproduct canonicity (values exist via DI-2a/b + every
-- closed-normal inhabitant is one). Full canonicity (all closed terms) still needs the master SR / #842.
#assert_no_axioms FX1Poly.Typed.Conv.productCode_not_universeCode
#assert_no_axioms FX1Poly.Typed.Conv.eitherCode_not_universeCode
#assert_no_axioms FX1Poly.Typed.Conv.piTyCode_not_conv_eitherCode
