import LeanFX2.Tools.AuditGen
import LeanFX2.Smoke.AuditConvCumulHomo
import LeanFX2.Smoke.AuditCoverageGap
import LeanFX2.Smoke.AuditCumul21
import LeanFX2.Smoke.AuditCumul24
import LeanFX2.Smoke.AuditCumul26
import LeanFX2.Smoke.AuditCumul33
import LeanFX2.Smoke.AuditCumulMeta
import LeanFX2.Smoke.AuditCumulSubstCompat
import LeanFX2.Smoke.AuditFunextFull
import LeanFX2.Smoke.AuditMegaZ1A
import LeanFX2.Smoke.AuditMegaZ1B
import LeanFX2.Smoke.AuditMegaZ25
import LeanFX2.Smoke.AuditMegaZ26
import LeanFX2.Smoke.AuditMegaZ2A
import LeanFX2.Smoke.AuditMegaZ2A1
import LeanFX2.Smoke.AuditMegaZ2B
import LeanFX2.Smoke.AuditMegaZ3
import LeanFX2.Smoke.AuditMegaZ4A
import LeanFX2.Smoke.AuditMegaZ5A
import LeanFX2.Smoke.AuditMegaZ5A1
import LeanFX2.Smoke.AuditPattern23Bridge
import LeanFX2.Smoke.AuditPhase10ASchema
import LeanFX2.Smoke.AuditPhase10ASchemaAudit
import LeanFX2.Smoke.AuditPhase10BBridge
import LeanFX2.Smoke.AuditPhase10BBridgeCorrespondence
import LeanFX2.Smoke.AuditPhase10BBridgeReduction
import LeanFX2.Smoke.AuditPhase12A0Cofib
import LeanFX2.Smoke.AuditPhase12A0Interval
import LeanFX2.Smoke.AuditPhase12A1Day1
import LeanFX2.Smoke.AuditPhase12A1Mode
import LeanFX2.Smoke.AuditPhase12A1NewTyCtors
import LeanFX2.Smoke.AuditPhase12A1UniverseConstraint
import LeanFX2.Smoke.AuditPhase12A2ConvCongIsClosedTy
import LeanFX2.Smoke.AuditPhase12A2Cumul
import LeanFX2.Smoke.AuditPhase12A2Day2
import LeanFX2.Smoke.AuditPhase12A2HoTTIdentityCong
import LeanFX2.Smoke.AuditPhase12A2IsClosedTy
import LeanFX2.Smoke.AuditPhase12A2IsClosedTyGeneral
import LeanFX2.Smoke.AuditPhase12A2RefactorPerTypeSR
import LeanFX2.Smoke.AuditPhase12A3Day3
import LeanFX2.Smoke.AuditPhase12A3GradedAtkeyAttack
import LeanFX2.Smoke.AuditPhase12A3HeadStepExtended
import LeanFX2.Smoke.AuditPhase12A3HeadStepPayloadSound
import LeanFX2.Smoke.AuditPhase12A3HoTTEquivalence
import LeanFX2.Smoke.AuditPhase12A3HoTTNTypes
import LeanFX2.Smoke.AuditPhase12A3HoTTPath
import LeanFX2.Smoke.AuditPhase12A3InferExtensions
import LeanFX2.Smoke.AuditPhase12A3M08Composition
import LeanFX2.Smoke.AuditPhase12A3NatSuccDestruct
import LeanFX2.Smoke.AuditPhase12A3Sessions
import LeanFX2.Smoke.AuditPhase12A4Day4
import LeanFX2.Smoke.AuditPhase12A4Dimensions21
import LeanFX2.Smoke.AuditPhase12A4GradedTwoElement
import LeanFX2.Smoke.AuditPhase12A5GradeVector
import LeanFX2.Smoke.AuditPhase12A5GradedCtx
import LeanFX2.Smoke.AuditPhase12A5HoTTTransport
import LeanFX2.Smoke.AuditPhase12A5ModalFoundation
import LeanFX2.Smoke.AuditPhase12A5RefineDecidable
import LeanFX2.Smoke.AuditPhase12A5RefineTy
import LeanFX2.Smoke.AuditPhase12A6CodataFoundation
import LeanFX2.Smoke.AuditPhase12A6EffectsFoundation
import LeanFX2.Smoke.AuditPhase12A6GradedRules
import LeanFX2.Smoke.AuditPhase12AB12LiftLevel
import LeanFX2.Smoke.AuditPhase12AB12SubstHet
import LeanFX2.Smoke.AuditPhase12AB13TermSubstHet
import LeanFX2.Smoke.AuditPhase12AB14CumulUpScope
import LeanFX2.Smoke.AuditPhase12AB15ConvBridge
import LeanFX2.Smoke.AuditPhase12AB16UniverseSR
import LeanFX2.Smoke.AuditPhase12AB17CumulReduction
import LeanFX2.Smoke.AuditPhase12AB18CumulConfluence
import LeanFX2.Smoke.AuditPhase12AB8
import LeanFX2.Smoke.AuditPhase12AB85
import LeanFX2.Smoke.AuditPhase12AB85b
import LeanFX2.Smoke.AuditPhase12AB86
import LeanFX2.Smoke.AuditPhase12AB87
import LeanFX2.Smoke.AuditPhase12AB88
import LeanFX2.Smoke.AuditPhase12AB89
import LeanFX2.Smoke.AuditPhase12AB8Cascade
import LeanFX2.Smoke.AuditPhase1E_Raw
import LeanFX2.Smoke.AuditPhase1E_Ty
import LeanFX2.Smoke.AuditPhase1F
import LeanFX2.Smoke.AuditPhase1FUniverse
import LeanFX2.Smoke.AuditPhase1G2
import LeanFX2.Smoke.AuditPhase1G3
import LeanFX2.Smoke.AuditPhase1G_Foundation
import LeanFX2.Smoke.AuditPhase1HRenameId
import LeanFX2.Smoke.AuditPhase2Bridge
import LeanFX2.Smoke.AuditPhase2HEqCongr
import LeanFX2.Smoke.AuditPhase2ProofIrrel
import LeanFX2.Smoke.AuditPhase3A
import LeanFX2.Smoke.AuditPhase3B
import LeanFX2.Smoke.AuditPhase3C
import LeanFX2.Smoke.AuditPhase3D
import LeanFX2.Smoke.AuditPhase3E
import LeanFX2.Smoke.AuditPhase3F1
import LeanFX2.Smoke.AuditPhase4ConfluenceTyped
import LeanFX2.Smoke.AuditPhase4Token
import LeanFX2.Smoke.AuditPhase4WHNF
import LeanFX2.Smoke.AuditPhase5Bridge
import LeanFX2.Smoke.AuditPhase6ARawCd
import LeanFX2.Smoke.AuditPhase6BCdDominates
import LeanFX2.Smoke.AuditPhase6BCdLemma
import LeanFX2.Smoke.AuditPhase6BCompatible
import LeanFX2.Smoke.AuditPhase6BInversion
import LeanFX2.Smoke.AuditPhase6BRename
import LeanFX2.Smoke.AuditPhase6CDiamond
import LeanFX2.Smoke.AuditPhase6DTypedConfluence
import LeanFX2.Smoke.AuditPhase6EStepStarToPar
import LeanFX2.Smoke.AuditPhase6FConvBridge
import LeanFX2.Smoke.AuditPhase79EndToEnd
import LeanFX2.Smoke.AuditPhase7ATypeInversions
import LeanFX2.Smoke.AuditPhase7BConvCanonical
import LeanFX2.Smoke.AuditPhase7CSubjectReduction
import LeanFX2.Smoke.AuditPhase8Semiring
import LeanFX2.Smoke.AuditPhase8Usage
import LeanFX2.Smoke.AuditPhase9ARawWHNF
import LeanFX2.Smoke.AuditPhase9ARawWHNFInversions
import LeanFX2.Smoke.AuditPhase9CDecConv
import LeanFX2.Smoke.AuditPhase9CDecConvTyped
import LeanFX2.Smoke.AuditPhase9DCheck
import LeanFX2.Smoke.AuditPhase9DInfer
import LeanFX2.Smoke.AuditPhase9DSynth
import LeanFX2.Smoke.AuditPhase9EEval
import LeanFX2.Smoke.AuditPhase9FCheckEval
import LeanFX2.Smoke.AuditPhase9GSoundness
import LeanFX2.Smoke.AuditUnivalenceFull
import LeanFX2.Smoke.AuditUnivalenceTransport
import LeanFX2.Smoke.Bridge
import LeanFX2.Smoke.Confluence
import LeanFX2.Smoke.Foundation
import LeanFX2.Smoke.Graded
import LeanFX2.Smoke.HoTT
import LeanFX2.Smoke.Modal
import LeanFX2.Smoke.Reduction
import LeanFX2.Smoke.Term

/-! # Smoke/AuditNamespace — fail-fast audit for loaded smoke declarations.

Most legacy smoke files still use `#print axioms`, which only logs.
This module imports the smoke suite and runs the build-failing namespace
audit over `LeanFX2.Smoke` declarations.  Production kernel declarations
are already covered by `LeanFX2.Tools.AuditAll`; keeping this sweep
smoke-scoped prevents documented surface boundary shims from weakening
the kernel gate.
-/

namespace LeanFX2.Tools

#audit_namespace_including_smoke LeanFX2.Smoke

end LeanFX2.Tools
