import LeanFX2.Foundation._deprecated_polygraph.GeneratorOutputType
import LeanFX2.Tools.DependencyAudit

/-! # AuditGeneratorOutputType — zero-axiom audit for the P2.2 Π/Σ + recursor + HOTT families.

Smoke gates for accelerate-P2.2 (#2123) — per-Generator outputType
extractors, currently covering 19 of the 74 ctors (Π/Σ + closed-type
recursors + HOTT identity / observational / strict identity / equiv-app).

## Coverage

Twelve extractors + twelve matching `rfl` theorems across two families:

**Π/Σ family** (6 ctors at `LeanFX2/Term.lean:104-146`):

* `Generator.outputTypeApp` — non-dep function application.
* `Generator.outputTypeLam` — non-dep function intro.
* `Generator.outputTypeLamPi` — dependent Π intro.
* `Generator.outputTypePair` — Σ pair intro.
* `Generator.outputTypeFst` — Σ first projection.
* `Generator.outputTypeSnd` — dependent Σ second projection.

**Closed-type recursor family** (6 ctors at `LeanFX2/Term.lean:152-234`):

* `Generator.outputTypeBoolElim` — dependent bool eliminator (output is
  `motiveType.subst0 Ty.bool scrutineeRaw`).
* `Generator.outputTypeNatElim` — non-dep nat eliminator.
* `Generator.outputTypeNatRec` — non-dep nat recursor.
* `Generator.outputTypeListElim` — non-dep list eliminator.
* `Generator.outputTypeOptionMatch` — non-dep option matcher.
* `Generator.outputTypeEitherMatch` — non-dep either matcher.

**HoTT identity + observational + strict-identity + equivApp family**
(7 ctors at `LeanFX2/Term.lean:236-294, 791-797`):

* `Generator.outputTypeRefl` — HoTT identity-type reflexivity:
  `Ty.id carrier rawWitness rawWitness`.
* `Generator.outputTypeIdJ` — non-dep HoTT J eliminator.
* `Generator.outputTypeOeqRefl` — observational reflexivity:
  `Ty.oeq carrier rawWitness rawWitness`.
* `Generator.outputTypeOeqJ` — non-dep observational J eliminator.
* `Generator.outputTypeIdStrictRefl` — strict-identity reflexivity
  (carries `mode = Mode.strict` hypothesis):
  `Ty.idStrict carrier rawWitness rawWitness`.
* `Generator.outputTypeIdStrictRec` — non-dep strict-identity
  recursor (carries `mode = Mode.strict` hypothesis).
* `Generator.outputTypeEquivApp` — equivalence application:
  `Ty.equiv carrierA carrierB → carrierA → carrierB`.

Plus the P2.0-shipped `Generator.outputTypeAppPi` (in `Generator.lean`)
for dependent function application — 20 of 74 outputType ctors covered.

All clean = P2.2 Π/Σ + recursor + HOTT extractor PASS.  The remaining
54 extractors (cubical / modal / type-code / record / codata /
session / effect / P-S vocabulary / transpFill) land in subsequent
P2.2 batches.
-/

namespace LeanFX2.SmokeGeneratorOutputType

#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeApp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeApp_matches_Term_app
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLam
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLam_matches_Term_lam
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLamPi
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLamPi_matches_Term_lamPi
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePair
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePair_matches_Term_pair
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeFst
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeFst_matches_Term_fst
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSnd
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSnd_matches_Term_snd
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolElim_matches_Term_boolElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatElim_matches_Term_natElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatRec
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatRec_matches_Term_natRec
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListElim_matches_Term_listElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionMatch
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionMatch_matches_Term_optionMatch
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherMatch
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherMatch_matches_Term_eitherMatch
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefl_matches_Term_refl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdJ
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdJ_matches_Term_idJ
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqRefl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqRefl_matches_Term_oeqRefl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqJ
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqJ_matches_Term_oeqJ
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRefl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRefl_matches_Term_idStrictRefl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRec
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRec_matches_Term_idStrictRec
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApp_matches_Term_equivApp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModIntro_matches_Term_modIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModElim_matches_Term_modElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSubsume
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSubsume_matches_Term_subsume
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval0
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval0_matches_Term_interval0
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval1
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval1_matches_Term_interval1
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalOpp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalOpp_matches_Term_intervalOpp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalMeet
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalMeet_matches_Term_intervalMeet
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalJoin
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalJoin_matches_Term_intervalJoin
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordIntro_matches_Term_recordIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordProj
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordProj_matches_Term_recordProj
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineIntro_matches_Term_refineIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineElim_matches_Term_refineElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataUnfold
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataUnfold_matches_Term_codataUnfold
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataDest
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataDest_matches_Term_codataDest
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionSend
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionSend_matches_Term_sessionSend
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionRecv
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionRecv_matches_Term_sessionRecv
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEffectPerform
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEffectPerform_matches_Term_effectPerform
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeVar
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeVar_matches_Term_var
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUnit
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUnit_matches_Term_unit
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolTrue
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolTrue_matches_Term_boolTrue
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolFalse
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolFalse_matches_Term_boolFalse
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatZero
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatZero_matches_Term_natZero
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatSucc
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatSucc_matches_Term_natSucc
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListNil
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListNil_matches_Term_listNil
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCons
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCons_matches_Term_listCons
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionNone
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionNone_matches_Term_optionNone
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionSome
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionSome_matches_Term_optionSome
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInl_matches_Term_eitherInl
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInr
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInr_matches_Term_eitherInr
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUniverseCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUniverseCode_matches_Term_universeCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeArrowCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeArrowCode_matches_Term_arrowCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePiTyCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePiTyCode_matches_Term_piTyCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSigmaTyCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSigmaTyCode_matches_Term_sigmaTyCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeProductCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeProductCode_matches_Term_productCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSumCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSumCode_matches_Term_sumCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCode_matches_Term_listCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionCode_matches_Term_optionCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherCode_matches_Term_eitherCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdCode_matches_Term_idCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivCode_matches_Term_equivCode
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathLam
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathLam_matches_Term_pathLam
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathApp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathApp_matches_Term_pathApp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueIntro_matches_Term_glueIntro
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueElim_matches_Term_glueElim
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeTransp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeTransp_matches_Term_transp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeHcomp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeHcomp_matches_Term_hcomp
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUaToEquiv
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUaToEquiv_matches_Term_uaToEquiv
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApply
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApply_matches_Term_equivApply
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqFunext
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqFunext_matches_Term_oeqFunext
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivIntroHet
#assert_no_axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivIntroHet_matches_Term_equivIntroHet

#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeApp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeApp_matches_Term_app
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLam
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLam_matches_Term_lam
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLamPi
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeLamPi_matches_Term_lamPi
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePair
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePair_matches_Term_pair
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeFst
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeFst_matches_Term_fst
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSnd
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSnd_matches_Term_snd
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolElim_matches_Term_boolElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatElim_matches_Term_natElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatRec
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatRec_matches_Term_natRec
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListElim_matches_Term_listElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionMatch
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionMatch_matches_Term_optionMatch
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherMatch
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherMatch_matches_Term_eitherMatch
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefl_matches_Term_refl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdJ
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdJ_matches_Term_idJ
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqRefl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqRefl_matches_Term_oeqRefl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqJ
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqJ_matches_Term_oeqJ
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRefl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRefl_matches_Term_idStrictRefl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRec
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdStrictRec_matches_Term_idStrictRec
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApp_matches_Term_equivApp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModIntro_matches_Term_modIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeModElim_matches_Term_modElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSubsume
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSubsume_matches_Term_subsume
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval0
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval0_matches_Term_interval0
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval1
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeInterval1_matches_Term_interval1
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalOpp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalOpp_matches_Term_intervalOpp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalMeet
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalMeet_matches_Term_intervalMeet
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalJoin
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIntervalJoin_matches_Term_intervalJoin
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordIntro_matches_Term_recordIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordProj
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRecordProj_matches_Term_recordProj
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineIntro_matches_Term_refineIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeRefineElim_matches_Term_refineElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataUnfold
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataUnfold_matches_Term_codataUnfold
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataDest
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeCodataDest_matches_Term_codataDest
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionSend
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionSend_matches_Term_sessionSend
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionRecv
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSessionRecv_matches_Term_sessionRecv
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEffectPerform
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEffectPerform_matches_Term_effectPerform
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeVar
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeVar_matches_Term_var
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUnit
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUnit_matches_Term_unit
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolTrue
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolTrue_matches_Term_boolTrue
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolFalse
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeBoolFalse_matches_Term_boolFalse
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatZero
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatZero_matches_Term_natZero
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatSucc
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeNatSucc_matches_Term_natSucc
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListNil
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListNil_matches_Term_listNil
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCons
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCons_matches_Term_listCons
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionNone
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionNone_matches_Term_optionNone
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionSome
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionSome_matches_Term_optionSome
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInl_matches_Term_eitherInl
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInr
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherInr_matches_Term_eitherInr
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUniverseCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUniverseCode_matches_Term_universeCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeArrowCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeArrowCode_matches_Term_arrowCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePiTyCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePiTyCode_matches_Term_piTyCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSigmaTyCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSigmaTyCode_matches_Term_sigmaTyCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeProductCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeProductCode_matches_Term_productCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSumCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeSumCode_matches_Term_sumCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeListCode_matches_Term_listCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOptionCode_matches_Term_optionCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEitherCode_matches_Term_eitherCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeIdCode_matches_Term_idCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivCode_matches_Term_equivCode
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathLam
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathLam_matches_Term_pathLam
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathApp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypePathApp_matches_Term_pathApp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueIntro_matches_Term_glueIntro
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeGlueElim_matches_Term_glueElim
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeTransp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeTransp_matches_Term_transp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeHcomp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeHcomp_matches_Term_hcomp
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUaToEquiv
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeUaToEquiv_matches_Term_uaToEquiv
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApply
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivApply_matches_Term_equivApply
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqFunext
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeOeqFunext_matches_Term_oeqFunext
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivIntroHet
#print axioms LeanFX2.Foundation._deprecated_polygraph.Generator.outputTypeEquivIntroHet_matches_Term_equivIntroHet

end LeanFX2.SmokeGeneratorOutputType
