import LeanFX2.Reduction.ConvCongIsClosedTy

#print axioms LeanFX2.StepStar.lift_at_isClosedTy
#print axioms LeanFX2.Conv.cong_at_isClosedTy
#print axioms LeanFX2.Conv.optionSome_cong
#print axioms LeanFX2.Conv.eitherInl_cong
#print axioms LeanFX2.Conv.eitherInr_cong
#print axioms LeanFX2.Conv.listCons_head_cong_isClosedTy
#print axioms LeanFX2.Conv.listCons_tail_cong_isClosedTy
#print axioms LeanFX2.Conv.listCons_cong
#print axioms LeanFX2.Conv.recordIntro_cong
#print axioms LeanFX2.Conv.codataUnfold_cong
#print axioms LeanFX2.Conv.listElim_scrutinee_cong_isClosedTy
#print axioms LeanFX2.Conv.optionMatch_scrutinee_cong_isClosedTy
#print axioms LeanFX2.Conv.eitherMatch_scrutinee_cong_isClosedTy
#print axioms LeanFX2.Conv.listElim_nil_cong_isClosedTy
#print axioms LeanFX2.Conv.listElim_cons_cong_isClosedTy
#print axioms LeanFX2.Conv.optionMatch_none_cong_isClosedTy
#print axioms LeanFX2.Conv.optionMatch_some_cong_isClosedTy
#print axioms LeanFX2.Conv.eitherMatch_left_cong_isClosedTy
#print axioms LeanFX2.Conv.eitherMatch_right_cong_isClosedTy
#print axioms LeanFX2.Conv.appLeft_cong_isClosedTy
#print axioms LeanFX2.Conv.appRight_cong_isClosedTy
#print axioms LeanFX2.Conv.app_cong
#print axioms LeanFX2.Conv.natElimSucc_cong_isClosedTy
#print axioms LeanFX2.Conv.natRecSucc_cong_isClosedTy
#print axioms LeanFX2.Conv.modIntro_cong
#print axioms LeanFX2.Conv.modElim_cong
#print axioms LeanFX2.Conv.subsume_cong
#print axioms LeanFX2.Conv.refineIntro_cong
#print axioms LeanFX2.Conv.recordProj_cong
#print axioms LeanFX2.Conv.codataDest_cong
#print axioms LeanFX2.Conv.cong3_at_isClosedTy
#print axioms LeanFX2.Conv.listElim_cong
#print axioms LeanFX2.Conv.optionMatch_cong
#print axioms LeanFX2.Conv.eitherMatch_cong
#print axioms LeanFX2.Conv.natElim_cong
#print axioms LeanFX2.Conv.natRec_cong
