import LeanFX2.Term.RenameInjective

/-! # Smoke: Term/RenameInjective zero-axiom audit -/

#print axioms LeanFX2.Term.rename_injective_atVar
#print axioms LeanFX2.Term.rename_injective_lam_ctor
#print axioms LeanFX2.Term.rename_injective_app_ctor
#print axioms LeanFX2.Term.rename_injective_lamPi_ctor
#print axioms LeanFX2.Term.rename_injective_appPi_ctor
#print axioms LeanFX2.Term.rename_injective_pathLam_ctor
#print axioms LeanFX2.Term.rename_injective_atUnit
#print axioms LeanFX2.Term.rename_injective_atBoolTrue
#print axioms LeanFX2.Term.rename_injective_atBoolFalse
#print axioms LeanFX2.Term.rename_injective_atNatZero
#print axioms LeanFX2.Term.rename_injective_atNatSucc_of_inner
#print axioms LeanFX2.Term.rename_injective_atNatElim_of_inner
#print axioms LeanFX2.Term.rename_injective_atNatRec_of_inner
#print axioms LeanFX2.Term.rename_injective_atListNil
#print axioms LeanFX2.Term.rename_injective_atListCons_of_inner
#print axioms LeanFX2.Term.rename_injective_atPair_of_inner
#print axioms LeanFX2.Term.rename_injective_atFst_of_inner
#print axioms LeanFX2.Term.rename_injective_snd_ctor
#print axioms LeanFX2.Term.rename_injective_atGlueIntro_of_inner
#print axioms LeanFX2.Term.rename_injective_atGlueElim_of_inner
#print axioms LeanFX2.Term.rename_injective_atTransp_of_inner
#print axioms LeanFX2.Term.rename_injective_atHcompFamily_of_inner
#print axioms LeanFX2.Term.rename_injective_atListElim_of_inner
#print axioms LeanFX2.Term.rename_injective_atOptionNone
#print axioms LeanFX2.Term.rename_injective_atOptionSome_of_inner
#print axioms LeanFX2.Term.rename_injective_atOptionMatch_of_inner
#print axioms LeanFX2.Term.rename_injective_atEitherInl_of_inner
#print axioms LeanFX2.Term.rename_injective_atEitherInr_of_inner
#print axioms LeanFX2.Term.rename_injective_atEitherMatch_of_inner
#print axioms LeanFX2.Term.rename_injective_boolElim_ctor
#print axioms LeanFX2.Term.rename_injective_atIdJ_of_inner
#print axioms LeanFX2.Term.rename_injective_atOEqJ_of_inner
#print axioms LeanFX2.Term.rename_injective_atOEqFunext_of_inner
#print axioms LeanFX2.Term.rename_injective_atIdStrictRec_of_inner
#print axioms LeanFX2.Term.rename_injective_atRefl
#print axioms LeanFX2.Term.rename_injective_atOEqRefl
#print axioms LeanFX2.Term.rename_injective_atIdStrictRefl
#print axioms LeanFX2.Term.rename_injective_atInterval0
#print axioms LeanFX2.Term.rename_injective_atInterval1
#print axioms LeanFX2.Term.rename_injective_atIntervalOpp_of_inner
#print axioms LeanFX2.Term.rename_injective_atIntervalMeet_of_inner
#print axioms LeanFX2.Term.rename_injective_atIntervalJoin_of_inner
#print axioms LeanFX2.Term.rename_injective_atPathApp_of_inner
#print axioms LeanFX2.Term.rename_injective_atModIntro_of_inner
#print axioms LeanFX2.Term.rename_injective_atModElim_of_inner
#print axioms LeanFX2.Term.rename_injective_atSubsume_of_inner
#print axioms LeanFX2.Term.rename_injective_atRecordIntro_of_inner
#print axioms LeanFX2.Term.rename_injective_atRecordProj_of_inner
#print axioms LeanFX2.Term.rename_injective_atRefineIntro_of_inner
#print axioms LeanFX2.Term.rename_injective_atRefineElim_of_inner
#print axioms LeanFX2.Term.rename_injective_atCodataUnfold_of_inner
#print axioms LeanFX2.Term.rename_injective_atCodataDest_of_inner
#print axioms LeanFX2.Term.rename_injective_atSessionSend_of_inner
#print axioms LeanFX2.Term.rename_injective_atSessionRecv_of_inner
#print axioms LeanFX2.Term.rename_injective_atArrowCode
#print axioms LeanFX2.Term.rename_injective_atPiTyCode
#print axioms LeanFX2.Term.rename_injective_atSigmaTyCode
#print axioms LeanFX2.Term.rename_injective_atProductCode
#print axioms LeanFX2.Term.rename_injective_atSumCode
#print axioms LeanFX2.Term.rename_injective_atListCode
#print axioms LeanFX2.Term.rename_injective_atOptionCode
#print axioms LeanFX2.Term.rename_injective_atEitherCode
#print axioms LeanFX2.Term.rename_injective_atIdCode
#print axioms LeanFX2.Term.rename_injective_atEquivCode
#print axioms LeanFX2.Term.rename_injective_atCumulUp_of_inner
#print axioms LeanFX2.Term.rename_injective_atUaToEquiv_of_inner
#print axioms LeanFX2.Term.rename_injective_atEquivApply_of_inner
#print axioms LeanFX2.Term.rename_injective_atEquivApp_of_inner
