import FX1PolyAudit.DependencyAudit
import FX1Poly.ComputerAlgebra.Number.IntExactDivision

/-! # Zero-axiom gate for `IntExactDivision`

Per-declaration zero-axiom gate for the sign-aware exact-division kit: the magnitude
remainder/quotient pair over the counting divider, the exactness theorem a vanishing
remainder yields, the nonnegative `toNat` round-trip, and the directed rounding quotients.
Every declaration must be free of `propext`, `Quot.sound`, `Classical.choice`, `sorry`,
`native_decide`, and `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeRemainder
#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeDivisionExact
#assert_no_axioms FX1Poly.ComputerAlgebra.intOfNatToNatOfNonNeg
#assert_no_axioms FX1Poly.ComputerAlgebra.intNegOfNatNatAbs
#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeRemainderAsCounting
#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeQuotientNatAbs
#assert_no_axioms FX1Poly.ComputerAlgebra.intEqZeroOfNatAbsEqZero
#assert_no_axioms FX1Poly.ComputerAlgebra.intNatAbsMulOfNatSucc
#assert_no_axioms FX1Poly.ComputerAlgebra.intToNatAtLeastTwoOfOneLessThan
#assert_no_axioms FX1Poly.ComputerAlgebra.intToNatPosOfPos
#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeQuotientByOne
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeOfIntOfNatLe
#assert_no_axioms FX1Poly.ComputerAlgebra.intFalseOfOfNatLeNegSucc
#assert_no_axioms FX1Poly.ComputerAlgebra.intNegOfNatLeOfNat
#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeQuotientIsMonotone
#assert_no_axioms FX1Poly.ComputerAlgebra.intMagnitudeQuotientScales
#assert_no_axioms FX1Poly.ComputerAlgebra.intFloorQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.intFloorQuotientMulIsBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.intFloorQuotientNextMultipleIsAbove
#assert_no_axioms FX1Poly.ComputerAlgebra.intCeilQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.intCeilQuotientMulIsAbove
#assert_no_axioms FX1Poly.ComputerAlgebra.intCeilQuotientPreviousMultipleIsBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.intSuccNeverLeSelf
#assert_no_axioms FX1Poly.ComputerAlgebra.intMulLeMantissaOfLeFloorQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.intLeFloorQuotientOfMulLe
#assert_no_axioms FX1Poly.ComputerAlgebra.intMantissaLeMulOfCeilQuotientLe
#assert_no_axioms FX1Poly.ComputerAlgebra.intCeilQuotientLeOfMantissaLeMul
#assert_no_axioms FX1Poly.ComputerAlgebra.intAwayQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.intAwayQuotientMulIsAboveOfNonNegativeMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.intAwayQuotientPreviousMultipleIsBelowOfNonNegativeMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.intAwayQuotientMulIsBelowOfNegativeMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.intAwayQuotientNextMultipleIsAboveOfNegativeMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.intMulTwiceNegFolds
#assert_no_axioms FX1Poly.ComputerAlgebra.intNegAddShiftCollapses
#assert_no_axioms FX1Poly.ComputerAlgebra.intNearestEvenQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.intNearestEvenQuotientMulTwiceIsBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.intNearestEvenQuotientMulTwiceIsAbove
#assert_no_axioms FX1Poly.ComputerAlgebra.intFloorQuotientAtNegSuccOfPositiveRemainder
#assert_no_axioms FX1Poly.ComputerAlgebra.intCeilQuotientAtOfNatOfPositiveRemainder
#assert_no_axioms FX1Poly.ComputerAlgebra.intNearestEvenQuotientIsFloorOrCeil

end FX1PolyAudit
