import FX1PolyAudit.DependencyAudit
import FX1Poly.ComputerAlgebra.Number.NatEuclideanDivision

/-! # Zero-axiom gate for `NatEuclideanDivision`

Per-declaration zero-axiom gate for the structural counting divider: the step function,
the counter, the strictness upgrade, the reconstruction / remainder-bound / existence
certificates, and the round-nearest-ties-even corrector. Every declaration must be free
of `propext`, `Quot.sound`, `Classical.choice`, `sorry`, `native_decide`, and `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModStep
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModCounting
#assert_no_axioms FX1Poly.ComputerAlgebra.natLtOfLeOfNe
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModStepReconstructs
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModStepRemainderIsBounded
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModCountingReconstructs
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModCountingRemainderIsBounded
#assert_no_axioms FX1Poly.ComputerAlgebra.natEuclideanDivisionExists
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModCountingByOne
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeTrans
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeOfSuccLeSucc
#assert_no_axioms FX1Poly.ComputerAlgebra.natEqZeroOfLeZero
#assert_no_axioms FX1Poly.ComputerAlgebra.natExactQuotientSuccBound
#assert_no_axioms FX1Poly.ComputerAlgebra.natExactQuotientWithinFuel
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModStepQuotientGrows
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModCountingQuotientIsMonotone
#assert_no_axioms FX1Poly.ComputerAlgebra.natZeroLe
#assert_no_axioms FX1Poly.ComputerAlgebra.natSuccLeSuccOfLe
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeTotal
#assert_no_axioms FX1Poly.ComputerAlgebra.natAddRightCancel
#assert_no_axioms FX1Poly.ComputerAlgebra.natAddLeftCancel
#assert_no_axioms FX1Poly.ComputerAlgebra.natSuccNeverLeSelf
#assert_no_axioms FX1Poly.ComputerAlgebra.natRightDistrib
#assert_no_axioms FX1Poly.ComputerAlgebra.natMulLtMulRight
#assert_no_axioms FX1Poly.ComputerAlgebra.natMulPosOfPos
#assert_no_axioms FX1Poly.ComputerAlgebra.natEuclideanQuotientEqOfLe
#assert_no_axioms FX1Poly.ComputerAlgebra.natEuclideanQuotientUnique
#assert_no_axioms FX1Poly.ComputerAlgebra.natDivModCountingQuotientScales
#assert_no_axioms FX1Poly.ComputerAlgebra.natBleEqTrueOfLe
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeOfBltEqFalse
#assert_no_axioms FX1Poly.ComputerAlgebra.natIsEven
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientIsKeptOrBumped
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestEvenQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeOfLt
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeOfEqLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.natLeOfEqRight
#assert_no_axioms FX1Poly.ComputerAlgebra.natAddLeAddLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.natAddLeAddRight
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientAtBump
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientAtKeep
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientAtTieEven
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientAtTieOdd
#assert_no_axioms FX1Poly.ComputerAlgebra.natKeptQuotientMulTwiceIsBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.natBumpedQuotientMulTwiceIsBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.natKeptQuotientMulTwiceIsAbove
#assert_no_axioms FX1Poly.ComputerAlgebra.natBumpedQuotientMulTwiceIsAbove
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientMulTwiceIsBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientMulTwiceIsAbove
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestEvenQuotientMulTwiceIsBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestEvenQuotientMulTwiceIsAbove
#assert_no_axioms FX1Poly.ComputerAlgebra.natBeqZeroEqFalseOfPos
#assert_no_axioms FX1Poly.ComputerAlgebra.natPosOfDoublePos
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestCorrectedQuotientIsKeptOrBumpedWithMidpointCertificate
#assert_no_axioms FX1Poly.ComputerAlgebra.natNearestEvenQuotientIsKeptOrBumpedWithMidpointCertificate
#assert_no_axioms FX1Poly.ComputerAlgebra.natSuccPredOfPositive

end FX1PolyAudit
