import FX1PolyAudit.DependencyAudit
import FX1Poly.ComputerAlgebra.Number.RationalPair

/-! # FX1PolyAudit/ComputerAlgebra/Number/RationalPair — zero-axiom gate
    (NUM-Q-1)

Per-declaration zero-axiom gate for the ℚ carrier: the successor-shaped pair, the
positive denominator read-back, and the decidable cross-multiplication setoid with
its reflexivity/symmetry/transitivity laws.

Every declaration must be free of `propext`, `Quot.sound`, `Classical.choice`, `sorry`,
`native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mk
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denominatorInt
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denominatorIntIsPositive
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.DenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.decideDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denotesSameAsRefl
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denotesSameAsSymm
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denotesSameAsTrans
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExact
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactNumerator
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactDenominatorInt
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExact
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactNumerator
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactDenominatorInt
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.negExact
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactCongrLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactCongrRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactRespectsDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactCongrLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactCongrRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactRespectsDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.negExactRespectsDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.LessEqualAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.decideLessEqualAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.LessThanAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.decideLessThanAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessEqualAsOfLessThan
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessEqualAsRefl
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessEqualAsTotal
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessEqualAsOfDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denotesSameAsOfLessEqualBoth
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessEqualAsTrans
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessEqualAsCongrLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessEqualAsCongrRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.lessThanAsTrichotomy
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.zeroRational
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.IsNonNegative
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.numeratorNonNegativeOfIsNonNegative
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.isNonNegativeOfNumeratorNonNegative
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactMonotoneLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactMonotoneRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactMonotone
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactIsNonNegative
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.magnitudeRemainderVanishesOfDividesNatAbs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.normalize
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.normalizeDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.normalizeIsCoprime
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.IsReduced
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.decideIsReduced
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.eqOfReducedOfDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.normalizeEqOfDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denotesSameAsOfNormalizeEq
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.denotesSameAsIffNormalizeEq
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.normalizeOfReducedIsSelf
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.normalizeIsIdempotent
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.oneRational
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactComm
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactZeroRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactZeroLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactNegRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.addExactAssoc
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactComm
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactOneRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactOneLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactAssoc
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactLeftDistrib
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactRightDistrib
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.IsApartFromZero
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.decideIsApartFromZero
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.invExact
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactInvRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RationalPair.mulExactInvLeft

end FX1PolyAudit
