import FX1Poly.Polygraph.TwoCategory.WalkingKZ.KZMonadDecision
import FX1Poly.Polygraph.TwoCategory.WalkingMonad.MonadWordProblem
import FX1Poly.Polygraph.TwoCategory.WalkingMonad.MonadHcompMult

/-! # WalkingKZ/KZOrderCompleteness — the LOCAL covering move of the KZ order (`kzGen` in merge context)

`KZMonadDecision` closed the KZ 2-cell EQUALITY word problem outright (`decideKZEq`, the antisymmetric core =
the walking monad) and left ONE open leg of the FULL order decision: `KZOrderCompleteness.leOfMapLE` —
`mapLE (fold a) (fold b) → KZTwoCellLE a b` — the reconstruction of a directed KZ 2-cell from pointwise
dominance of Δ₊ fibre-count vectors.  The route (recon, Street; recognition criterion arXiv:2512.05631): the
dominance order on the count vectors is GENERATED by COVERING MOVES, each covering move — increment one
fibre-count position, decrement the adjacent one — realized by ONE whiskered `kzGen` composed with
monad-convertibility reshuffling; a dominance `mapLE` decomposes into a finite chain of such moves, chained by
`KZTwoCellLE.trans`.

## What this file ships — the COVERING MOVE, mechanized zero-axiom (the genuine `kzGen` order content)

The sole GENUINE order content of the completeness leg is the single covering move; everything else is
monad-equality reshuffling (free, via the shipped EQUALITY completeness `monadConvOfMapEq_ofNormalize`) and
dominance combinatorics.  This file mechanizes the covering move in full:

  * ★★ **`kzAtomicCovering`** — the ATOMIC covering `word [a,1,0,b] ⇒ word [a,0,1,b]`: a single strand moves
    one fibre rightward past an `eta`-inserted target, with the `a`-merge and `b`-merge carried as horizontal
    context.  This is the whiskered `kzGen` composed with `wordMul_hcomp` reshuffling — the recon's "one
    whiskered `kzGen` application in the appropriate boundary context".  Its sole order step is `kzGen` (through
    `kzBaseCovering`); the context is threaded by the shipped `wordMul_hcomp` (word splitting) plus the KZ
    congruence closures.
  * ★★ **`kzLocalCovering`** — the LOCAL 2-block covering `flat [a+1,b] ⇒ flat [a,b+1]` at a fixed flat
    boundary `(t^n, t^2)`: the general covering move `(a+1,b) ↦ (a,b+1)` on MERGED fibre-count vectors.  It is
    the `kzAtomicCovering` between the UNMERGED 4-block words `[a,1,0,b] ⇒ [a,0,1,b]`, post-composed with the
    fixed merge `word [2,2]` (fold `[0,0,1,1]`); the merge collapse is the pure `List Nat` identities
    `mergeCollapse_srcCounts` / `mergeCollapse_tgtCounts`, and the endpoints bridge to the merged words by
    EQUALITY completeness (`kzLE_ofMapEq`).  This is the recon's `kzLocalCovering` — the covering-word brick.

Plus the covering-carrier infrastructure: the KZ boundary-cast congruence (`KZTwoCellLE.castBoundaryCongr`), the
KZ horizontal-composite congruences (`KZTwoCellLE.hcompCongrLeft` / `_Right`), the fold-invisibility of casts
(`monadMonotoneMapOf_castBoundary`), and the flat covering carrier `kzFlatWord` (a canonical Eilenberg–Zilber
word cast to the FLAT boundary `t^(listSum) ⇒ t^length`, so covering-chain waypoints of a fixed `(n,m)` are
all mutually PARALLEL and bridge cast-free by fold equality).

## The residual (honest fail-forward — NO wall, the move IS realizable)

What remains toward inhabiting `KZOrderCompleteness` is PURELY the covering-CHAIN assembly: a structural-fuel
recursion (fuel = the dominance measure `Σ_i (map b − map a)_i`) that (i) at each step selects the covering
position from `mapLE` (the leftmost fibre-count position where `a` exceeds `b`, provably `> 0` by prefix-sum
dominance), (ii) applies `kzLocalCovering` there via `wordMul_hcomp` context lifting, and (iii) recurses on the
one-step-closer count vector.  This is genuine dominance-lattice combinatorics but it is NOT a wall: the covering
move `kzLocalCovering` — the only place `kzGen`'s single direction had to align with the reconstructed order — is
CLOSED here, confirming the dominance order is generated by whiskered-`kzGen` covering moves with no rigid
coordinate.  So NO covering-gap marker is flipped (there is no gap), and `fxKZ_hasWalkingKZOrderCompleteness`
stays honestly `false` (in `KZMonadDecision`, untouched) pending the chain-assembly round.

Raw Lean 4 + Init; the covering move is an inductive-`Prop` derivation spliced with `wordMul_hcomp`; the merge
collapse is cons-only `List Nat` structural recursion; the flat carrier is a boundary `castBoundary`; every
declaration is `propext`/`Quot.sound`/`Classical`/`sorry`/`native_decide`/`omega`-free (each key theorem verified
`does not depend on any axioms`).  Per-declaration `#assert_no_axioms` gated in the audit twin. -/

namespace FX1Poly.Polygraph

/-! ## KZ boundary-cast congruence + fold-invisibility of casts -/

/-- The KZ 2-cell order transports along a boundary cast on BOTH sides — `KZTwoCellLE a b` gives
`KZTwoCellLE (cast a) (cast b)`.  The order analog of `MonadSaturatedTwoCellConv.castBoundaryCongr`; the cast is
a double `Eq.rec`, so `cases` on the two boundary equalities collapses it to the identity. -/
theorem KZTwoCellLE.castBoundaryCongr
    {sourcePath sourcePath' targetPath targetPath' : ModalityPath monadGraph MonadMode.point MonadMode.point}
    (hsource : sourcePath = sourcePath') (htarget : targetPath = targetPath')
    {cellAlpha cellBeta : RawTwoCellExpr monadModeSignature sourcePath targetPath}
    (le : KZTwoCellLE cellAlpha cellBeta) :
    KZTwoCellLE (RawTwoCellExpr.castBoundary hsource htarget cellAlpha)
      (RawTwoCellExpr.castBoundary hsource htarget cellBeta) := by
  cases hsource; cases htarget; exact le

/-- **Casting a cell is fold-invisible**: `monadMonotoneMapOf (castBoundary hs ht cell) = monadMonotoneMapOf
cell`.  The Δ₊ fold reads only the spine (which the boundary paths do not enter), so `cases` on the two boundary
equalities collapses the cast.  The order-decision analog of `RawTwoCellExpr.castBoundary_spine`. -/
theorem monadMonotoneMapOf_castBoundary
    {sourcePath sourcePath' targetPath targetPath' : ModalityPath monadGraph MonadMode.point MonadMode.point}
    (hsource : sourcePath = sourcePath') (htarget : targetPath = targetPath')
    (cell : RawTwoCellExpr monadModeSignature sourcePath targetPath) :
    monadMonotoneMapOf (RawTwoCellExpr.castBoundary hsource htarget cell) = monadMonotoneMapOf cell := by
  cases hsource; cases htarget; rfl

/-! ## KZ horizontal-composite congruences (completing the KZ congruence closure for `hcomp`) -/

/-- Congruence in the RIGHT factor of a KZ horizontal composite: `hcomp α = whiskerRight … then whiskerLeft …`,
so replacing the right factor by a KZ-larger one enlarges the composite (`whiskerLeftCongr` under a `vcompCongr`).
The order analog of `MonadSaturatedTwoCellConv.hcompCongrRight`. -/
theorem KZTwoCellLE.hcompCongrRight {sourceMode middleMode targetMode : MonadMode}
    {oneCellFDom oneCellFCod : ModalityPath monadModeSignature.graph sourceMode middleMode}
    {oneCellGDom oneCellGCod : ModalityPath monadModeSignature.graph middleMode targetMode}
    (cellAlpha : RawTwoCellExpr monadModeSignature oneCellFDom oneCellFCod)
    {cellBeta cellBeta' : RawTwoCellExpr monadModeSignature oneCellGDom oneCellGCod}
    (le : KZTwoCellLE cellBeta cellBeta') :
    KZTwoCellLE (RawTwoCellExpr.hcomp cellAlpha cellBeta) (RawTwoCellExpr.hcomp cellAlpha cellBeta') :=
  KZTwoCellLE.vcompCongrRight _ (KZTwoCellLE.whiskerLeftCongr oneCellFCod le)

/-- Congruence in the LEFT factor of a KZ horizontal composite (the dual of `hcompCongrRight`, via
`whiskerRightCongr` under a `vcompCongr`). -/
theorem KZTwoCellLE.hcompCongrLeft {sourceMode middleMode targetMode : MonadMode}
    {oneCellFDom oneCellFCod : ModalityPath monadModeSignature.graph sourceMode middleMode}
    {oneCellGDom oneCellGCod : ModalityPath monadModeSignature.graph middleMode targetMode}
    {cellAlpha cellAlpha' : RawTwoCellExpr monadModeSignature oneCellFDom oneCellFCod}
    (cellBeta : RawTwoCellExpr monadModeSignature oneCellGDom oneCellGCod)
    (le : KZTwoCellLE cellAlpha cellAlpha') :
    KZTwoCellLE (RawTwoCellExpr.hcomp cellAlpha cellBeta) (RawTwoCellExpr.hcomp cellAlpha' cellBeta) :=
  KZTwoCellLE.vcompCongrLeft _ (KZTwoCellLE.whiskerRightCongr oneCellGDom le)

/-! ## The merge-collapse `List Nat` identities (the fold of the covering witness) -/

/-- `composeMap` over a `consReplicate` block: a run of `count` copies of `value` maps to a run of `count` copies
of `second`'s value at `value`.  Cons-only structural recursion on `count`. -/
theorem composeMap_consReplicate (value count : Nat) (tail second : List Nat) :
    composeMap (consReplicate value count tail) second
      = consReplicate (monotoneMapGet second value) count (composeMap tail second) := by
  induction count with
  | zero => rfl
  | succ n ih =>
      show monotoneMapGet second value :: composeMap (consReplicate value n tail) second
        = monotoneMapGet second value
          :: consReplicate (monotoneMapGet second value) n (composeMap tail second)
      rw [ih]

/-- Two adjacent `consReplicate` runs of the SAME value fuse: `consReplicate v a (consReplicate v c tail) =
consReplicate v (a+c) tail`.  Cons-only structural recursion on `a`. -/
theorem consReplicate_add (value countA countC : Nat) (tail : List Nat) :
    consReplicate value countA (consReplicate value countC tail) = consReplicate value (countA + countC) tail := by
  induction countA with
  | zero =>
      show consReplicate value countC tail = consReplicate value (0 + countC) tail
      rw [Nat.zero_add]
  | succ n ih =>
      show value :: consReplicate value n (consReplicate value countC tail)
        = consReplicate value (Nat.succ n + countC) tail
      rw [Nat.succ_add]
      show value :: consReplicate value n (consReplicate value countC tail)
        = value :: consReplicate value (n + countC) tail
      rw [ih]

/-- ★ **The SOURCE merge collapse.**  Post-composing the unmerged 4-block reconstruction `reconstructFrom 0
[a,1,0,b]` (`= [0×a, 1, 3×b]`) with the fixed merge map `reconstructFrom 0 [2,2]` (`= [0,0,1,1]`, i.e. fuse
targets `{0,1}` and `{2,3}`) collapses to the MERGED 2-block reconstruction `reconstructFrom 0 [a+1,b]` (`=
[0×(a+1), 1×b]`).  This is the covering witness's source fold: the moving strand (target `1`) and the `a`-merge
(target `0`) fuse to target `0`.  Cons-only `composeMap`/`consReplicate` algebra. -/
theorem mergeCollapse_srcCounts (widthLeft widthRight : Nat) :
    composeMap (reconstructFrom 0 [widthLeft, 1, 0, widthRight]) (reconstructFrom 0 [2, 2])
      = reconstructFrom 0 [widthLeft + 1, widthRight] := by
  show composeMap (consReplicate 0 widthLeft (1 :: consReplicate 3 widthRight [])) [0, 0, 1, 1]
    = reconstructFrom 0 [widthLeft + 1, widthRight]
  rw [composeMap_consReplicate]
  show consReplicate 0 widthLeft (0 :: composeMap (consReplicate 3 widthRight []) [0, 0, 1, 1])
    = reconstructFrom 0 [widthLeft + 1, widthRight]
  rw [composeMap_consReplicate]
  show consReplicate 0 widthLeft (consReplicate 0 1 (consReplicate 1 widthRight []))
    = reconstructFrom 0 [widthLeft + 1, widthRight]
  rw [consReplicate_add]
  rfl

/-- ★ **The TARGET merge collapse.**  Post-composing the moved unmerged reconstruction `reconstructFrom 0
[a,0,1,b]` (`= [0×a, 2, 3×b]`) with the same merge `[0,0,1,1]` collapses to `reconstructFrom 0 [a,b+1]` (`=
[0×a, 1×(b+1)]`): the moving strand (now target `2`) and the `b`-merge (target `3`) fuse to target `1`.  Cons-only
algebra (the dual of `mergeCollapse_srcCounts`). -/
theorem mergeCollapse_tgtCounts (widthLeft widthRight : Nat) :
    composeMap (reconstructFrom 0 [widthLeft, 0, 1, widthRight]) (reconstructFrom 0 [2, 2])
      = reconstructFrom 0 [widthLeft, widthRight + 1] := by
  show composeMap (consReplicate 0 widthLeft (consReplicate 2 1 (consReplicate 3 widthRight []))) [0, 0, 1, 1]
    = reconstructFrom 0 [widthLeft, widthRight + 1]
  rw [composeMap_consReplicate, composeMap_consReplicate, composeMap_consReplicate]
  show consReplicate 0 widthLeft (consReplicate 1 1 (consReplicate 1 widthRight []))
    = reconstructFrom 0 [widthLeft, widthRight + 1]
  rw [consReplicate_add, Nat.add_comm 1 widthRight]
  rfl

/-! ## The atomic covering move — one whiskered `kzGen` in merge context -/

/-- ★ **The BASE covering** `word [1,0] ⇒ word [0,1]` — the bare `kzGen`, no context.  `word [1,0]` folds `[0]`
(one strand at target `0`, an `eta`-inserted target `1`) and is PARALLEL to `kzTEtaCell` (both `t ⇒ t·t`);
`word [0,1]` folds `[1]` and is parallel to `kzEtaTCell`.  So the base covering is `kzGen` bridged by two EQUALITY
convertibilities (`kzLE_ofMapEq`, fold `[0] = [0]` and `[1] = [1]`) — cast-free, the single `kzGen` order step. -/
theorem kzBaseCovering : KZTwoCellLE (wordFromCounts [1, 0]) (wordFromCounts [0, 1]) :=
  KZTwoCellLE.trans
    (kzLE_ofMapEq (show monadMonotoneMapOf (wordFromCounts [1, 0]) = monadMonotoneMapOf kzTEtaCell by
      rw [monadMonotoneMapOf_wordFromCounts]; rfl))
    (KZTwoCellLE.trans KZTwoCellLE.kzGen
      (kzLE_ofMapEq (show monadMonotoneMapOf kzEtaTCell = monadMonotoneMapOf (wordFromCounts [0, 1]) by
        rw [monadMonotoneMapOf_wordFromCounts]; rfl)))

/-- The base covering under a RIGHT context `t^b`-merge: `word [1,0,b] ⇒ word [0,1,b]`.  Split the merge tail off
by `wordMul_hcomp` (`word [1,0,b] ≈ cast (word [1,0] ⊠ word [b])`), fire `kzBaseCovering` on the `[1,0]` factor
through `hcompCongrLeft`, and reassemble (`wordMul_hcomp` symmetrised).  The `wordMul` equalities lift to the KZ
order by `KZTwoCellLE.ofMonad`; the boundary casts thread through `castBoundaryCongr`. -/
theorem kzCoveringRightContext (widthRight : Nat) :
    KZTwoCellLE (wordFromCounts (consAppend [1, 0] [widthRight]))
      (wordFromCounts (consAppend [0, 1] [widthRight])) := by
  refine KZTwoCellLE.trans (KZTwoCellLE.ofMonad (wordMul_hcomp [1, 0] [widthRight])) ?_
  refine KZTwoCellLE.trans (KZTwoCellLE.castBoundaryCongr _ _
    (KZTwoCellLE.hcompCongrLeft (wordFromCounts [widthRight]) kzBaseCovering)) ?_
  exact KZTwoCellLE.ofMonad (MonadSaturatedTwoCellConv.symm (wordMul_hcomp [0, 1] [widthRight]))

/-- ★★ **The ATOMIC covering move** `word [a,1,0,b] ⇒ word [a,0,1,b]`: one strand moves one fibre rightward past
the `eta`-inserted target, with the `a`-merge on the LEFT and the `b`-merge on the RIGHT carried as horizontal
context.  Split the left `a`-merge off (`wordMul_hcomp [a] …`), fire `kzCoveringRightContext` on the `[1,0,b]`
factor through `hcompCongrRight`, and reassemble.  This is the recon's covering move — ONE whiskered `kzGen`
(inside `kzCoveringRightContext` / `kzBaseCovering`) composed with `wordMul_hcomp` monad-conv reshuffling — the
sole GENUINE order content of the completeness leg, mechanized zero-axiom. -/
theorem kzAtomicCovering (widthLeft widthRight : Nat) :
    KZTwoCellLE (wordFromCounts (consAppend [widthLeft] (consAppend [1, 0] [widthRight])))
      (wordFromCounts (consAppend [widthLeft] (consAppend [0, 1] [widthRight]))) := by
  refine KZTwoCellLE.trans (KZTwoCellLE.ofMonad (wordMul_hcomp [widthLeft] (consAppend [1, 0] [widthRight]))) ?_
  refine KZTwoCellLE.trans (KZTwoCellLE.castBoundaryCongr _ _
    (KZTwoCellLE.hcompCongrRight (wordFromCounts [widthLeft]) (kzCoveringRightContext widthRight))) ?_
  exact KZTwoCellLE.ofMonad
    (MonadSaturatedTwoCellConv.symm (wordMul_hcomp [widthLeft] (consAppend [0, 1] [widthRight])))

/-- The atomic covering restated on the literal 4-count lists (`consAppend [a] (consAppend [1,0] [b]) = [a,1,0,b]`
definitionally). -/
theorem kzAtomicCoveringLiteral (widthLeft widthRight : Nat) :
    KZTwoCellLE (wordFromCounts [widthLeft, 1, 0, widthRight]) (wordFromCounts [widthLeft, 0, 1, widthRight]) :=
  kzAtomicCovering widthLeft widthRight

/-! ## The atomic covering carrying an arbitrary count-list SUFFIX -/

/-- ★ **The atomic covering with an arbitrary count-list SUFFIX** `word ([a,1,0,b] ++ suf) ⇒ word ([a,0,1,b] ++
suf)`: the single-strand move `[a,1,0,b] ⇒ [a,0,1,b]` with the `a`-merge and `b`-merge on the active block and an
ARBITRARY count-list `suf` riding as right horizontal context (generalizing `kzAtomicCovering`'s single
`[widthRight]` block to any `suf`).  The four-block active pattern `[a,1,0,b]` is a LITERAL that computes through
`consAppend`, so the `[1,0]↔[0,1]` swap stays definitionally parallel; the `suf` tail splits off by
`wordMul_hcomp`, `kzAtomicCoveringLiteral` fires on the active factor through `hcompCongrLeft`, and the boundary
casts thread through `castBoundaryCongr`.  Works for any `suf` because `wordMul_hcomp` is polymorphic in its second
argument. -/
theorem kzAtomicCoveringSuffix (widthLeft widthRight : Nat) (suf : List Nat) :
    KZTwoCellLE (wordFromCounts (consAppend [widthLeft, 1, 0, widthRight] suf))
      (wordFromCounts (consAppend [widthLeft, 0, 1, widthRight] suf)) := by
  refine KZTwoCellLE.trans (KZTwoCellLE.ofMonad (wordMul_hcomp [widthLeft, 1, 0, widthRight] suf)) ?_
  refine KZTwoCellLE.trans (KZTwoCellLE.castBoundaryCongr _ _
    (KZTwoCellLE.hcompCongrLeft (wordFromCounts suf) (kzAtomicCoveringLiteral widthLeft widthRight))) ?_
  exact KZTwoCellLE.ofMonad
    (MonadSaturatedTwoCellConv.symm (wordMul_hcomp [widthLeft, 0, 1, widthRight] suf))

/-! ## The flat covering carrier: canonical words cast to `t^(listSum) ⇒ t^length` -/

/-- ★ The **flat Eilenberg–Zilber word** of a count vector `cs` at the FLAT boundary `t^(listSum cs) ⇒ t^m`
(here `n = listSum cs`, `m = cs.length`): `wordFromCounts cs` transported from its native domain
`countsDomainPath cs` onto the flat `t`-power `monadTPower n` (they are equal by
`countsDomainPath_eq_monadTPower_listSum`) and its codomain onto `monadTPower m`.  Casting to the flat boundary is
what makes ALL words of a fixed `(n,m)` mutually PARALLEL, so covering-chain waypoints bridge cast-free by fold
equality (`kzLE_ofMapEq`). -/
def kzFlatWord (widthTotal widthCod : Nat) (counts : List Nat)
    (hsum : listSum counts = widthTotal) (hlen : counts.length = widthCod) :
    RawTwoCellExpr monadModeSignature (monadTPower widthTotal) (monadTPower widthCod) :=
  RawTwoCellExpr.castBoundary
    (by rw [countsDomainPath_eq_monadTPower_listSum, hsum])
    (by rw [hlen]) (wordFromCounts counts)

/-- The flat word folds to its count vector's reconstruction — `monadMonotoneMapOf (kzFlatWord n m cs …) =
reconstructFrom 0 cs` — since the boundary cast is fold-invisible and `wordFromCounts` round-trips. -/
theorem kzFlatWord_map (widthTotal widthCod : Nat) (counts : List Nat)
    (hsum : listSum counts = widthTotal) (hlen : counts.length = widthCod) :
    monadMonotoneMapOf (kzFlatWord widthTotal widthCod counts hsum hlen) = reconstructFrom 0 counts := by
  rw [kzFlatWord, monadMonotoneMapOf_castBoundary, monadMonotoneMapOf_wordFromCounts]

/-- Two flat words of the SAME `(n,m)` whose count vectors reconstruct to the SAME map are KZ-`≤` (both ways) —
the EQUALITY-completeness bridge at the flat boundary, cast-free (they are parallel). -/
theorem kzLE_ofFlatMapEq (widthTotal widthCod : Nat) {counts counts' : List Nat}
    (hsum : listSum counts = widthTotal) (hlen : counts.length = widthCod)
    (hsum' : listSum counts' = widthTotal) (hlen' : counts'.length = widthCod)
    (hmap : reconstructFrom 0 counts = reconstructFrom 0 counts') :
    KZTwoCellLE (kzFlatWord widthTotal widthCod counts hsum hlen)
      (kzFlatWord widthTotal widthCod counts' hsum' hlen') :=
  kzLE_ofMapEq (by rw [kzFlatWord_map, kzFlatWord_map, hmap])

/-! ## ★★ The LOCAL covering move on merged fibre-count vectors -/

/-- ★★ **The LOCAL 2-block covering** `flat [a+1,b] ⇒ flat [a,b+1]` at the flat boundary `(t^n, t^2)` — the
general covering move `(a+1, b) ↦ (a, b+1)` that moves ONE fibre unit rightward between two adjacent MERGED
target blocks.  Realized as the atomic move between the UNMERGED 4-block words `[a,1,0,b] ⇒ [a,0,1,b]`
(`kzAtomicCovering`, the whiskered `kzGen`), post-composed with the fixed merge `word [2,2]` (fold `[0,0,1,1]`):
the source endpoint folds `composeMap (reconstruct [a,1,0,b]) [0,0,1,1] = reconstruct [a+1,b]`
(`mergeCollapse_srcCounts`) and the target `= reconstruct [a,b+1]` (`mergeCollapse_tgtCounts`), so both endpoints
bridge to the merged flat words by EQUALITY completeness.  The whole chain lives at `(t^n, t^2)`, so every step is
cast-free `vcompCongrLeft` / `kzLE_ofMapEq`.  This is the covering-word brick the completeness chain iterates. -/
theorem kzLocalCovering (widthLeft widthRight widthTotal : Nat)
    (hsumSrc : listSum [widthLeft + 1, widthRight] = widthTotal)
    (hsumTgt : listSum [widthLeft, widthRight + 1] = widthTotal) :
    KZTwoCellLE (kzFlatWord widthTotal 2 [widthLeft + 1, widthRight] hsumSrc rfl)
      (kzFlatWord widthTotal 2 [widthLeft, widthRight + 1] hsumTgt rfl) := by
  -- The two unmerged 4-block words also have block sum `widthTotal`.
  have hsum4Src : listSum [widthLeft, 1, 0, widthRight] = widthTotal := by
    have hstep : listSum [widthLeft, 1, 0, widthRight] = listSum [widthLeft + 1, widthRight] := by
      show widthLeft + (1 + (0 + (widthRight + 0))) = (widthLeft + 1) + (widthRight + 0)
      rw [Nat.zero_add, Nat.add_zero, Nat.add_zero, ← Nat.add_assoc]
    rw [hstep, hsumSrc]
  have hsum4Tgt : listSum [widthLeft, 0, 1, widthRight] = widthTotal := by
    have hstep : listSum [widthLeft, 0, 1, widthRight] = listSum [widthLeft, widthRight + 1] := by
      show widthLeft + (0 + (1 + (widthRight + 0))) = widthLeft + ((widthRight + 1) + 0)
      rw [Nat.zero_add, Nat.add_zero, Nat.add_zero, Nat.add_comm 1 widthRight]
    rw [hstep, hsumTgt]
  have hsumMerge : listSum [2, 2] = 4 := rfl
  -- The atomic move, lifted to the flat 4-block boundary.
  have hAtomicFlat : KZTwoCellLE (kzFlatWord widthTotal 4 [widthLeft, 1, 0, widthRight] hsum4Src rfl)
      (kzFlatWord widthTotal 4 [widthLeft, 0, 1, widthRight] hsum4Tgt rfl) := by
    rw [kzFlatWord, kzFlatWord]
    exact KZTwoCellLE.castBoundaryCongr _ _ (kzAtomicCoveringLiteral widthLeft widthRight)
  -- The source merged word ≈ (flat 4-block src ⊟ merge), by the source merge collapse.
  refine KZTwoCellLE.trans
    (kzLE_ofMapEq (show monadMonotoneMapOf (kzFlatWord widthTotal 2 [widthLeft + 1, widthRight] hsumSrc rfl)
      = monadMonotoneMapOf (RawTwoCellExpr.vcomp (kzFlatWord widthTotal 4 [widthLeft, 1, 0, widthRight] hsum4Src rfl)
          (kzFlatWord 4 2 [2, 2] hsumMerge rfl)) from ?_)) ?_
  · rw [kzFlatWord_map, monadMonotoneMapOf_vcomp, kzFlatWord_map, kzFlatWord_map, mergeCollapse_srcCounts]
  -- The order step: (flat 4 src ⊟ merge) ⇒ (flat 4 tgt ⊟ merge) by the atomic move.
  refine KZTwoCellLE.trans (KZTwoCellLE.vcompCongrLeft (kzFlatWord 4 2 [2, 2] hsumMerge rfl) hAtomicFlat) ?_
  -- (flat 4 tgt ⊟ merge) ≈ target merged word, by the target merge collapse.
  refine kzLE_ofMapEq
    (show monadMonotoneMapOf (RawTwoCellExpr.vcomp (kzFlatWord widthTotal 4 [widthLeft, 0, 1, widthRight] hsum4Tgt rfl)
        (kzFlatWord 4 2 [2, 2] hsumMerge rfl))
      = monadMonotoneMapOf (kzFlatWord widthTotal 2 [widthLeft, widthRight + 1] hsumTgt rfl) from ?_)
  rw [monadMonotoneMapOf_vcomp, kzFlatWord_map, kzFlatWord_map, kzFlatWord_map, mergeCollapse_tgtCounts]

/-! ## ★★ The FRONT covering with an arbitrary suffix — the covering brick with context

`kzLocalCovering` moves one unit between the ONLY two blocks (`m = 2`).  The completeness chain needs the same move
in front of an arbitrary tail: `flat ((a+1)::b::suf) ⇒ flat (a::(b+1)::suf)`.  This section ships that via the SAME
merge-collapse route as `kzLocalCovering` but with the suffix `suf` riding through the merge word.  The new
combinatorial content is the two merge-collapse identities with a suffix (`mergeCollapseSuffix_src`/`_tgt`), built
from `composeMap_reconstructFrom_relabel` (post-composition relabels a reconstruction) and the ones-block value law
`reconstructFrom_ones_get`. -/

/-- The reconstruction of a run of `1`s (a `consReplicate 1 kount []` count-vector) is the ascending block: its
value at an in-range position is `base + position`.  Structural recursion on the count. -/
theorem reconstructFrom_ones_get : ∀ (base kount position : Nat), position < kount →
    monotoneMapGet (reconstructFrom base (consReplicate 1 kount [])) position = base + position
  | _, 0, _, hlt => absurd hlt (Nat.not_lt_zero _)
  | base, kount + 1, 0, _ => by
      show monotoneMapGet (reconstructFrom base (1 :: consReplicate 1 kount [])) 0 = base + 0
      show base = base + 0
      rw [Nat.add_zero]
  | base, kount + 1, position + 1, hlt => by
      show monotoneMapGet (reconstructFrom base (1 :: consReplicate 1 kount [])) (position + 1)
        = base + (position + 1)
      show monotoneMapGet (reconstructFrom (base + 1) (consReplicate 1 kount [])) position
        = base + (position + 1)
      rw [reconstructFrom_ones_get (base + 1) kount position (Nat.lt_of_succ_lt_succ hlt),
          Nat.add_assoc, Nat.add_comm 1 position]

/-- **Post-composition relabels a reconstruction.**  If a map `postMap` sends every value `srcBase + index` (for
`index` in range) to `tgtBase + index`, then post-composing the reconstruction `reconstructFrom srcBase counts`
with `postMap` is the reconstruction `reconstructFrom tgtBase counts` — the block structure is preserved, only the
target labels shift.  Structural recursion on `counts`, peeling `consReplicate` blocks. -/
theorem composeMap_reconstructFrom_relabel : ∀ (counts : List Nat) (srcBase tgtBase : Nat) (postMap : List Nat),
    (∀ index, index < counts.length → monotoneMapGet postMap (srcBase + index) = tgtBase + index) →
    composeMap (reconstructFrom srcBase counts) postMap = reconstructFrom tgtBase counts
  | [], _, _, _, _ => rfl
  | count :: counts', srcBase, tgtBase, postMap, hrelabel => by
      show composeMap (consReplicate srcBase count (reconstructFrom (srcBase + 1) counts')) postMap
        = consReplicate tgtBase count (reconstructFrom (tgtBase + 1) counts')
      rw [composeMap_consReplicate]
      have hhead : monotoneMapGet postMap srcBase = tgtBase := by
        have hget := hrelabel 0 (Nat.succ_pos _)
        rw [Nat.add_zero, Nat.add_zero] at hget
        exact hget
      rw [hhead,
          composeMap_reconstructFrom_relabel counts' (srcBase + 1) (tgtBase + 1) postMap
            (fun index hindex => by
              rw [Nat.add_right_comm srcBase 1 index, Nat.add_right_comm tgtBase 1 index]
              exact hrelabel (index + 1) (Nat.succ_lt_succ hindex))]

/-- `listSum` of a run of `1`s is the count.  Structural recursion on the count. -/
theorem listSum_consReplicate_ones : ∀ (kount : Nat), listSum (consReplicate 1 kount []) = kount
  | 0 => rfl
  | kount + 1 => by
      show 1 + listSum (consReplicate 1 kount []) = kount + 1
      rw [listSum_consReplicate_ones kount, Nat.add_comm]

/-- **The suffix merge word counts**: fuse the first two target blocks (`[2, 2]`, the `kzLocalCovering` merge) and
pass the remaining `kount` targets through the identity (`consReplicate 1 kount []`, a run of `1`s).  Its fold is
`[0,0,1,1,2,3,…,kount+1]` — merge `{0,1}→0`, `{2,3}→1`, identity above. -/
def kzMergeSuffix (kount : Nat) : List Nat := consAppend [2, 2] (consReplicate 1 kount [])

/-- The suffix merge word has block sum `4 + kount` (two 2-blocks plus `kount` ones). -/
theorem kzMergeSuffix_listSum (kount : Nat) : listSum (kzMergeSuffix kount) = 4 + kount := by
  show 2 + (2 + listSum (consReplicate 1 kount [])) = 4 + kount
  rw [listSum_consReplicate_ones]
  exact (Nat.add_assoc 2 2 kount).symm

/-- The suffix merge word has `2 + kount` blocks (two merged targets plus the `kount` pass-through targets). -/
theorem kzMergeSuffix_length (kount : Nat) : (kzMergeSuffix kount).length = 2 + kount := by
  show (consAppend [2, 2] (consReplicate 1 kount [])).length = 2 + kount
  rw [consAppend_length, consReplicate_length]
  show (2 : Nat) + (0 + kount) = 2 + kount
  rw [Nat.zero_add]

/-- The suffix merge word's fold at a position `≥ 4` reads the identity pass-through: `map (4 + index) = 2 + index`
(the `index`-th target above the two merged blocks). -/
theorem mergemapSuffix_get_ge (kount : Nat) : ∀ (index : Nat), index < kount →
    monotoneMapGet (reconstructFrom 0 (kzMergeSuffix kount)) (4 + index) = 2 + index := by
  intro index hindex
  show monotoneMapGet
      (consReplicate 0 2 (consReplicate 1 2 (reconstructFrom 2 (consReplicate 1 kount [])))) (4 + index)
    = 2 + index
  rw [show (4 : Nat) + index = 2 + (2 + index) from Nat.add_assoc 2 2 index,
      monotoneMapGet_consReplicate_ge 0 2 (2 + index)
        (consReplicate 1 2 (reconstructFrom 2 (consReplicate 1 kount []))),
      monotoneMapGet_consReplicate_ge 1 2 index (reconstructFrom 2 (consReplicate 1 kount []))]
  exact reconstructFrom_ones_get 2 kount index hindex

/-- ★ **The SOURCE merge collapse with a suffix.**  Post-composing the unmerged `[a,1,0,b] ++ suf` reconstruction
with the suffix merge word collapses to the merged `[a+1,b] ++ suf` reconstruction — the moving strand fuses into
the `a`-block; the suffix relabels down by two.  Cons-only `composeMap`/`consReplicate` algebra plus the relabel of
the suffix tail. -/
theorem mergeCollapseSuffix_src (widthLeft widthRight : Nat) (suf : List Nat) :
    composeMap (reconstructFrom 0 (consAppend [widthLeft, 1, 0, widthRight] suf))
      (reconstructFrom 0 (kzMergeSuffix suf.length))
      = reconstructFrom 0 (consAppend [widthLeft + 1, widthRight] suf) := by
  show composeMap (consReplicate 0 widthLeft (1 :: consReplicate 3 widthRight (reconstructFrom 4 suf)))
      (reconstructFrom 0 (kzMergeSuffix suf.length))
    = consReplicate 0 (widthLeft + 1) (consReplicate 1 widthRight (reconstructFrom 2 suf))
  rw [composeMap_consReplicate]
  show consReplicate 0 widthLeft
      (composeMap (1 :: consReplicate 3 widthRight (reconstructFrom 4 suf))
        (reconstructFrom 0 (kzMergeSuffix suf.length)))
    = consReplicate 0 (widthLeft + 1) (consReplicate 1 widthRight (reconstructFrom 2 suf))
  show consReplicate 0 widthLeft
      (0 :: composeMap (consReplicate 3 widthRight (reconstructFrom 4 suf))
        (reconstructFrom 0 (kzMergeSuffix suf.length)))
    = consReplicate 0 (widthLeft + 1) (consReplicate 1 widthRight (reconstructFrom 2 suf))
  rw [composeMap_consReplicate]
  show consReplicate 0 widthLeft
      (0 :: consReplicate 1 widthRight
        (composeMap (reconstructFrom 4 suf) (reconstructFrom 0 (kzMergeSuffix suf.length))))
    = consReplicate 0 (widthLeft + 1) (consReplicate 1 widthRight (reconstructFrom 2 suf))
  rw [composeMap_reconstructFrom_relabel suf 4 2 (reconstructFrom 0 (kzMergeSuffix suf.length))
        (fun index hindex => mergemapSuffix_get_ge suf.length index hindex)]
  show consReplicate 0 widthLeft (consReplicate 0 1 (consReplicate 1 widthRight (reconstructFrom 2 suf)))
    = consReplicate 0 (widthLeft + 1) (consReplicate 1 widthRight (reconstructFrom 2 suf))
  rw [consReplicate_add]

/-- ★ **The TARGET merge collapse with a suffix** (the dual): post-composing the moved `[a,0,1,b] ++ suf`
reconstruction with the suffix merge word collapses to `[a,b+1] ++ suf` — the moved strand fuses into the
`b`-block. -/
theorem mergeCollapseSuffix_tgt (widthLeft widthRight : Nat) (suf : List Nat) :
    composeMap (reconstructFrom 0 (consAppend [widthLeft, 0, 1, widthRight] suf))
      (reconstructFrom 0 (kzMergeSuffix suf.length))
      = reconstructFrom 0 (consAppend [widthLeft, widthRight + 1] suf) := by
  show composeMap
      (consReplicate 0 widthLeft (consReplicate 2 1 (consReplicate 3 widthRight (reconstructFrom 4 suf))))
      (reconstructFrom 0 (kzMergeSuffix suf.length))
    = consReplicate 0 widthLeft (consReplicate 1 (widthRight + 1) (reconstructFrom 2 suf))
  rw [composeMap_consReplicate, composeMap_consReplicate, composeMap_consReplicate]
  show consReplicate 0 widthLeft (consReplicate 1 1 (consReplicate 1 widthRight
        (composeMap (reconstructFrom 4 suf) (reconstructFrom 0 (kzMergeSuffix suf.length)))))
    = consReplicate 0 widthLeft (consReplicate 1 (widthRight + 1) (reconstructFrom 2 suf))
  rw [composeMap_reconstructFrom_relabel suf 4 2 (reconstructFrom 0 (kzMergeSuffix suf.length))
        (fun index hindex => mergemapSuffix_get_ge suf.length index hindex),
      consReplicate_add, Nat.add_comm 1 widthRight]

/-- ★★ **The FRONT covering with an arbitrary suffix** `flat ((a+1)::b::suf) ⇒ flat (a::(b+1)::suf)` at the flat
boundary `(t^n, t^(2+|suf|))` — the general covering move `(a+1,b) ↦ (a,b+1)` on the FIRST two merged blocks with
an arbitrary count-list `suf` following.  Realized exactly as `kzLocalCovering` but with the suffix merge word:
`kzAtomicCoveringSuffix` supplies the whiskered `kzGen` between the unmerged `[a,1,0,b]++suf` and `[a,0,1,b]++suf`
words, post-composed with `kzMergeSuffix`, the endpoints bridged by the suffix merge-collapse identities through
EQUALITY completeness at the flat carrier.  The covering brick the completeness chain iterates. -/
theorem kzFrontCovering (widthLeft widthRight widthTotal : Nat) (suf : List Nat)
    (hsumSrc : listSum (consAppend [widthLeft + 1, widthRight] suf) = widthTotal)
    (hsumTgt : listSum (consAppend [widthLeft, widthRight + 1] suf) = widthTotal)
    (hlenSrc : (consAppend [widthLeft + 1, widthRight] suf).length = 2 + suf.length)
    (hlenTgt : (consAppend [widthLeft, widthRight + 1] suf).length = 2 + suf.length) :
    KZTwoCellLE
      (kzFlatWord widthTotal (2 + suf.length) (consAppend [widthLeft + 1, widthRight] suf) hsumSrc hlenSrc)
      (kzFlatWord widthTotal (2 + suf.length) (consAppend [widthLeft, widthRight + 1] suf) hsumTgt hlenTgt) := by
  have hsum4Src : listSum (consAppend [widthLeft, 1, 0, widthRight] suf) = widthTotal := by
    rw [listSum_consAppend]
    rw [listSum_consAppend] at hsumSrc
    have hstep : listSum [widthLeft, 1, 0, widthRight] = listSum [widthLeft + 1, widthRight] := by
      show widthLeft + (1 + (0 + (widthRight + 0))) = (widthLeft + 1) + (widthRight + 0)
      rw [Nat.zero_add, Nat.add_zero, Nat.add_zero, ← Nat.add_assoc]
    rw [hstep]; exact hsumSrc
  have hsum4Tgt : listSum (consAppend [widthLeft, 0, 1, widthRight] suf) = widthTotal := by
    rw [listSum_consAppend]
    rw [listSum_consAppend] at hsumTgt
    have hstep : listSum [widthLeft, 0, 1, widthRight] = listSum [widthLeft, widthRight + 1] := by
      show widthLeft + (0 + (1 + (widthRight + 0))) = widthLeft + ((widthRight + 1) + 0)
      rw [Nat.zero_add, Nat.add_zero, Nat.add_zero, Nat.add_comm 1 widthRight]
    rw [hstep]; exact hsumTgt
  have hlen4Src : (consAppend [widthLeft, 1, 0, widthRight] suf).length = 4 + suf.length :=
    consAppend_length [widthLeft, 1, 0, widthRight] suf
  have hlen4Tgt : (consAppend [widthLeft, 0, 1, widthRight] suf).length = 4 + suf.length :=
    consAppend_length [widthLeft, 0, 1, widthRight] suf
  have hAtomicFlat :
      KZTwoCellLE
        (kzFlatWord widthTotal (4 + suf.length) (consAppend [widthLeft, 1, 0, widthRight] suf) hsum4Src hlen4Src)
        (kzFlatWord widthTotal (4 + suf.length) (consAppend [widthLeft, 0, 1, widthRight] suf) hsum4Tgt hlen4Tgt) := by
    rw [kzFlatWord, kzFlatWord]
    exact KZTwoCellLE.castBoundaryCongr _ _ (kzAtomicCoveringSuffix widthLeft widthRight suf)
  refine KZTwoCellLE.trans
    (kzLE_ofMapEq (show monadMonotoneMapOf
        (kzFlatWord widthTotal (2 + suf.length) (consAppend [widthLeft + 1, widthRight] suf) hsumSrc hlenSrc)
      = monadMonotoneMapOf (RawTwoCellExpr.vcomp
          (kzFlatWord widthTotal (4 + suf.length) (consAppend [widthLeft, 1, 0, widthRight] suf) hsum4Src hlen4Src)
          (kzFlatWord (4 + suf.length) (2 + suf.length) (kzMergeSuffix suf.length)
            (kzMergeSuffix_listSum suf.length) (kzMergeSuffix_length suf.length))) from ?_)) ?_
  · rw [kzFlatWord_map, monadMonotoneMapOf_vcomp, kzFlatWord_map, kzFlatWord_map, mergeCollapseSuffix_src]
  refine KZTwoCellLE.trans
    (KZTwoCellLE.vcompCongrLeft
      (kzFlatWord (4 + suf.length) (2 + suf.length) (kzMergeSuffix suf.length)
        (kzMergeSuffix_listSum suf.length) (kzMergeSuffix_length suf.length)) hAtomicFlat) ?_
  refine kzLE_ofMapEq
    (show monadMonotoneMapOf (RawTwoCellExpr.vcomp
        (kzFlatWord widthTotal (4 + suf.length) (consAppend [widthLeft, 0, 1, widthRight] suf) hsum4Tgt hlen4Tgt)
        (kzFlatWord (4 + suf.length) (2 + suf.length) (kzMergeSuffix suf.length)
          (kzMergeSuffix_listSum suf.length) (kzMergeSuffix_length suf.length)))
      = monadMonotoneMapOf
          (kzFlatWord widthTotal (2 + suf.length) (consAppend [widthLeft, widthRight + 1] suf) hsumTgt hlenTgt)
        from ?_)
  rw [monadMonotoneMapOf_vcomp, kzFlatWord_map, kzFlatWord_map, kzFlatWord_map, mergeCollapseSuffix_tgt]

/-! ## ★★ The front-strip: prepend a head block to a flat covering -/

/-- The flat word of `headBlock :: w` is a boundary cast of the head gadget horizontally composed with the flat
word of `w`: `flat (c::w) = cast (gadget c ⊠ flat w)`.  Definitionally `wordFromCounts (c::w) = gadget c ⊠
wordFromCounts w`; `hcomp_castBoundaryRight` pulls the inner flat cast out and `castBoundary_castBoundary` fuses the
two casts — the residual is proof-irrelevant (`rfl`). -/
theorem kzFlatWord_cons (headBlock widthTotal widthCod : Nat) (w : List Nat)
    (hsum : listSum w = widthTotal) (hlen : w.length = widthCod)
    (hsum' : listSum (headBlock :: w) = headBlock + widthTotal)
    (hlen' : (headBlock :: w).length = widthCod + 1) :
    kzFlatWord (headBlock + widthTotal) (widthCod + 1) (headBlock :: w) hsum' hlen'
      = RawTwoCellExpr.castBoundary (monadTPower_add headBlock widthTotal).symm rfl
          (RawTwoCellExpr.hcomp (monadGadget headBlock) (kzFlatWord widthTotal widthCod w hsum hlen)) := by
  dsimp only [kzFlatWord]
  rw [RawTwoCellExpr.hcomp_castBoundaryRight, RawTwoCellExpr.castBoundary_castBoundary]
  rfl

/-- ★★ **The front-strip congruence** — prepend a head block to both sides of a flat covering: from a covering
`flat w_src ⇒ flat w_tgt` build `flat (c::w_src) ⇒ flat (c::w_tgt)`.  The head gadget `c` rides as free
horizontal context: `hcompCongrRight (gadget c)` lifts the covering, `kzFlatWord_cons` re-anchors both endpoints to
the flat `(t^(c+n), t^(m+1))` boundary, and `castBoundaryCongr` transports the order across the `t^(c+n) =
t^c · t^n` associator.  This is the length-INCREASING move the head-peel chain recursion needs (the covering itself
is length-preserving; the strip prepends a settled head). -/
theorem kzPrefixAdd (headBlock widthTotal widthCod : Nat) {w_src w_tgt : List Nat}
    (hsum_src : listSum w_src = widthTotal) (hlen_src : w_src.length = widthCod)
    (hsum_tgt : listSum w_tgt = widthTotal) (hlen_tgt : w_tgt.length = widthCod)
    (hsum_src' : listSum (headBlock :: w_src) = headBlock + widthTotal)
    (hlen_src' : (headBlock :: w_src).length = widthCod + 1)
    (hsum_tgt' : listSum (headBlock :: w_tgt) = headBlock + widthTotal)
    (hlen_tgt' : (headBlock :: w_tgt).length = widthCod + 1)
    (le : KZTwoCellLE (kzFlatWord widthTotal widthCod w_src hsum_src hlen_src)
      (kzFlatWord widthTotal widthCod w_tgt hsum_tgt hlen_tgt)) :
    KZTwoCellLE (kzFlatWord (headBlock + widthTotal) (widthCod + 1) (headBlock :: w_src) hsum_src' hlen_src')
      (kzFlatWord (headBlock + widthTotal) (widthCod + 1) (headBlock :: w_tgt) hsum_tgt' hlen_tgt') := by
  rw [kzFlatWord_cons headBlock widthTotal widthCod w_src hsum_src hlen_src hsum_src' hlen_src',
      kzFlatWord_cons headBlock widthTotal widthCod w_tgt hsum_tgt hlen_tgt hsum_tgt' hlen_tgt']
  exact KZTwoCellLE.castBoundaryCongr (monadTPower_add headBlock widthTotal).symm rfl
    (KZTwoCellLE.hcompCongrRight (monadGadget headBlock) le)

/-! ## Non-vacuity: the covering move is genuine and strictly directional -/

/-- ★ **Non-vacuity — the base covering IS the strict KZ pair.**  At `widthLeft = widthRight = 0` the local
covering is `word [1,0] ⇒ word [0,1]`, folds `[0] ≤ [1]` — the strict directional generator `t◁eta ≤ eta▷t`
whose reverse is REFUTED (`kz_strict`).  So the covering move is non-vacuous and carries the genuine
lax-idempotency direction, not an equality. -/
theorem kzBaseCovering_isStrict :
    KZTwoCellLE (wordFromCounts [1, 0]) (wordFromCounts [0, 1])
      ∧ ¬ KZTwoCellLE (wordFromCounts [0, 1]) (wordFromCounts [1, 0]) := by
  refine ⟨kzBaseCovering, ?_⟩
  intro le
  have hsound := kzLE_sound le
  have hMapUpper : monadMonotoneMapOf (wordFromCounts [0, 1]) = [1] := by
    rw [monadMonotoneMapOf_wordFromCounts]; rfl
  have hMapLower : monadMonotoneMapOf (wordFromCounts [1, 0]) = [0] := by
    rw [monadMonotoneMapOf_wordFromCounts]; rfl
  have hStrict : mapLE [1] [0] := by rw [← hMapUpper, ← hMapLower]; exact hsound
  exact not_mapLE10 hStrict

/-- ★ Non-vacuity — a genuinely MERGED covering move fires: `flat [2,1] ⇒ flat [1,2]` (folds `[0,0,1] ≤ [0,1,1]`,
the middle strand moves rightward out of the width-2 merge).  `kzLocalCovering 1 1 3` instantiated. -/
theorem kzLocalCovering_merged_smoke :
    KZTwoCellLE (kzFlatWord 3 2 [2, 1] rfl rfl) (kzFlatWord 3 2 [1, 2] rfl rfl) :=
  kzLocalCovering 1 1 3 rfl rfl

/-- ★ Non-vacuity — the FRONT covering fires WITH a real suffix: `flat [2,1,5] ⇒ flat [1,2,5]` (a covering at the
first two blocks with a width-`5` block riding as context).  `kzFrontCovering 1 1 8 [5]` instantiated — the covering
brick works past a nonempty tail. -/
theorem kzFrontCovering_suffix_smoke :
    KZTwoCellLE (kzFlatWord 8 (2 + [5].length) (consAppend [2, 1] [5]) rfl rfl)
      (kzFlatWord 8 (2 + [5].length) (consAppend [1, 2] [5]) rfl rfl) :=
  kzFrontCovering 1 1 8 [5] rfl rfl rfl rfl

/-- ★ Non-vacuity — the front-strip prepends a settled head: from the merged covering `flat [2,1] ⇒ flat [1,2]`
build `flat [3,2,1] ⇒ flat [3,1,2]` (head block `3` prepended).  `kzPrefixAdd 3 3 2` applied to
`kzLocalCovering_merged_smoke` — the length-increasing move the chain recursion needs. -/
theorem kzPrefixAdd_smoke :
    KZTwoCellLE (kzFlatWord 6 3 [3, 2, 1] rfl rfl) (kzFlatWord 6 3 [3, 1, 2] rfl rfl) :=
  kzPrefixAdd 3 3 2 rfl rfl rfl rfl rfl rfl rfl rfl kzLocalCovering_merged_smoke

/-! ## Honesty markers -/

/-- **ESTABLISHED — the KZ covering MOVE is mechanized zero-axiom (the genuine `kzGen` order content).**  The
LOCAL 2-block covering `kzLocalCovering : flat [a+1,b] ⇒ flat [a,b+1]` — the general dominance covering move on
MERGED Δ₊ fibre-count vectors — is proven: it is the atomic whiskered-`kzGen` move `kzAtomicCovering :
word [a,1,0,b] ⇒ word [a,0,1,b]` (one strand past an `eta`-insert, `a`/`b`-merges as `wordMul_hcomp` context,
sole order step `kzGen` via `kzBaseCovering`), post-composed with the fixed merge `word [2,2]` and bridged to the
merged words by the merge-collapse identities (`mergeCollapse_srcCounts` / `_tgtCounts`) through EQUALITY
completeness at the flat carrier `kzFlatWord`.  Non-vacuous and strictly directional (`kzBaseCovering_isStrict`,
`kzLocalCovering_merged_smoke`).  This CONFIRMS the dominance order is generated by whiskered-`kzGen` covering
moves with NO rigid coordinate — there is no covering gap, no wall.  `= true`. -/
def fxKZ_hasWalkingKZLocalCovering : Bool := true

/-- **ESTABLISHED — the CONTEXTUAL covering + the front-strip are mechanized zero-axiom (GAP-1 closed).**  Beyond
the bare 2-block move, the chain-assembly bricks are shipped: (i) `kzFrontCovering : flat ((a+1)::b::suf) ⇒
flat (a::(b+1)::suf)` — the covering move at the FIRST two blocks with an ARBITRARY count-list `suf` riding through
the suffix merge word `kzMergeSuffix` (new combinatorics: `mergeCollapseSuffix_src`/`_tgt` via the reconstruction
relabel `composeMap_reconstructFrom_relabel`), the whiskered `kzGen` supplied by `kzAtomicCoveringSuffix`; (ii)
`kzPrefixAdd : (flat w_src ⇒ flat w_tgt) → (flat (c::w_src) ⇒ flat (c::w_tgt))` — the front-strip that prepends a
settled head block (`hcompCongrRight (gadget c)` + the boundary re-anchor `kzFlatWord_cons` + `castBoundaryCongr`
across the `t^(c+n) = t^c · t^n` associator).  Non-vacuous (`kzFrontCovering_suffix_smoke`, `kzPrefixAdd_smoke`).
Together they are exactly the length-preserving covering-in-context and the length-increasing head-peel the
head-recursion completeness chain iterates — the covering side of the residual is now fully closed.  `= true`. -/
def fxKZ_hasWalkingKZContextualCoveringAndStrip : Bool := true

/-- **Honesty marker — the RESIDUAL toward `KZOrderCompleteness`.**  The FULL order-completeness leg
`leOfMapLE : mapLE (fold a) (fold b) → KZTwoCellLE a b` needs, beyond the now-mechanized covering MOVE
(`kzLocalCovering`), only the covering-CHAIN assembly: a structural-fuel recursion (fuel = the dominance measure
`Σ_i (fold b − fold a)_i`) that at each step selects the covering position from `mapLE` (the leftmost fibre-count
position where `a`'s partial sums exceed `b`'s, provably a valid rightward move by prefix-sum dominance), lifts
`kzLocalCovering` to that position via `wordMul_hcomp` context splitting, and recurses on the one-step-closer count
vector — plus the top connection of `canon a` / `canon b` (already the shipped Eilenberg–Zilber canonical words)
to the flat carrier.  This is dominance-lattice combinatorics, NOT a mathematical wall: the covering move
`kzLocalCovering` is CLOSED, so `kzGen`'s single direction DOES climb the whole order (no rigid coordinate, no
covering gap).  Accordingly no covering-gap marker is flipped, and `fxKZ_hasWalkingKZOrderCompleteness`
(`KZMonadDecision`, untouched) stays honestly `false` pending the chain-assembly round.  `= false`. -/
def fxKZ_hasWalkingKZOrderCompletenessChain : Bool := false

end FX1Poly.Polygraph
