import FX1Poly.Polygraph.Omega.CongruenceWithId
import FX1Poly.Polygraph.Omega.StrictAxioms

/-! # Polygraph/Omega/CyclicThreeDemonstrator — the walking cyclic-3 involution as a two-critical-pair
Squier demonstrator (OMEGA-4 continued, WP-SQUIER r2 — the family round)

★ **The fourth walker re-encoded as an `OmegaComputad` Squier demonstrator — the walking cyclic-3
`<s | s.s.s => id>` at TWO critical pairs, the first NEW-SHAPE walker (rule-count 1 < critical-pair-count
2).**  After the involution `<s | s.s => id>` (1 rule / 1 CP), the walking monad `<t | eta, mu>` (2 / 5)
and the idempotent semigroup `<e | e.e => e>` (1 / 1), this file ships cyclic-3: one object, one
endo-1-generator `s`, one 2-generator `R : s.s.s => id` (the cyclic-3 law oriented left-to-right,
`id = s^0`), and its TWO Squier critical pairs `ssss` / `sssss` exhibited as generating 3-cells.

## Why NEW-SHAPE (the count observation this walker introduces)

The involution's rule source `ss` has one self-overlap (`sss`), giving ONE critical pair.  Cyclic-3's rule
source `sss` (length 3) has TWO self-overlaps — overlap length 2 (total word `ssss`, residual `s`) and
overlap length 1 (total word `sssss`, residual `ss`) — giving TWO critical pairs from ONE rule.  This is
the first walker where the critical-pair count strictly exceeds the rule count
(`cyclicThreeOmegaGeneratingRuleCount = 1 < 2 = allCyclicThreeOmegaCriticalPairs.length`), which is why
the COUNT certificate becomes load-bearing for completeness (obligation 3 of the full-homotopy-basis
design note below): the basis must contain BOTH width classes, or the branching `sssss` / `ssss` has an
unfilled 2-sphere.

## The presentation as a 2-polygraph (Squier reading)

  * 0-cells: one object `cyclicThreeOmegaPoint`.
  * 1-cells: freely generated by `cyclicThreeOmegaSGen : point => point`; words are `s^n`.
  * 2-cells (the rewrite rule): ONE generator `cyclicThreeOmegaRhoGen : s.s.s => id` (the cyclic-3 law).
  * 3-cells: the critical-pair fillers (this file), TWO of them.

## The two critical pairs, enumerated by hand (recon JOB 2)

The rule's source pattern is `sss` (length 3, left-associated `(ss)s`).  Overlaps of `sss` with itself:

  * **Length-2 overlap `ssss` (whisker by `s`).**  Reduce the FRONT `sss` (`cyclicThreeOmegaSsssLeftLeg =
    R |> s : ((ss)s)s => (id)s`, residual `s` on the RIGHT) or the BACK `sss`
    (`cyclicThreeOmegaSsssRightLeg = s <| R : s((ss)s) => s(id)`, residual `s` on the LEFT).  Both land on
    `s` after the strict units.  Peak `((ss)s)s ~ s((ss)s)` (a 3-STEP associativity chain — the genuinely
    new proof content), valley `(id)s ~ s ~ s(id)`.
  * **Length-1 overlap `sssss` (whisker by `ss`).**  Reduce the front (`cyclicThreeOmegaSssssLeftLeg =
    R |> ss : ((ss)s)(ss) => (id)(ss)`) or the back (`cyclicThreeOmegaSssssRightLeg = ss <| R :
    (ss)((ss)s) => (ss)(id)`).  Both land on `ss`.  Peak `((ss)s)(ss) ~ (ss)((ss)s)` (a 2-step
    associativity chain), valley `(id)(ss) ~ ss ~ (ss)(id)`.
  * Length-3 overlap (`sss = sss`): the SAME redex — not a genuine critical pair.
  * Length-0 overlap (`ssssss`): a DISJOINT-redex diamond, resolved by orthogonality — not a critical pair.

So there are exactly TWO critical pairs, and TWO generating 3-cells filling them.  The correspondence to
the Homology lane's `CyclicThreeChainComplex` (`cyclicThreeCriticalPairCountIsTwo`, `ssss→s`,
`sssss @ ss`, `H1 = ZZ/3`) is NAMED here, not imported (the r1 read-only discipline).

## The genuine new proof content (recon's one subtlety)

Cyclic-3's peaks are MULTI-STEP associativity chains — unlike the involution / monad, whose peaks are a
SINGLE `vcompAssoc` row.  Verified by hand: no single `vcompAssoc` relates `((ss)s)s` to `s((ss)s)`.  The
`ssss` peak is a 3-step `trans` chain (`vcompAssoc (ss) s s`, then `vcompAssoc s s (ss)`, then the reverse
of a right-congruence over `vcompAssoc s s s`); the `sssss` peak is a 2-step chain.  These are the only
proof terms in this file the monad's single-`vcompAssoc` peak join does NOT transplant.

## The honest coherence scope (mirroring the involution, refined to two pairs)

Both critical pairs are parallel only MODULO the strict congruence (peak sources structurally distinct,
`cyclicThreeOmega*Legs_notLiterallyParallel` compute `false`; valleys reach `s` / `ss` modulo the strict
units).  The POSITIVE content shipped here: the two generating 3-cells, the two peak joins (the
associativity chains), the two valley joins (units), the assembled per-pair resolutions, the bundled
coherent presentation, and the least-congruence universal property
(`cyclicThreeOmegaCriticalPairsIdentifiedInEveryModel`).  Neither pair is literally parallel (peaks differ
by association), so — like the involution — neither ships a genuine `CriticalPairRow`.

## The 2-path normalizer wall — the full homotopy basis (design note, no code this round)

The FULL homotopy basis (every parallel 2-path pair `s^n => s^k` 3-cell-homotopic) is WALLED identically
to the involution and the monad and stays the OMEGA-5 handoff.  The exact obligations the full basis needs
(the named design deliverable):

  1. **`TwoPath` NF-directed syntax** — a subset of `SaturatedConvOverWithId` derivations oriented as
     reduction sequences with a canonical (leftmost-outermost) 2-path per parallel class.
  2. **A structural fuel measure** `twoPathSize : TwoPath → Nat` (constant-`Nat` motive, like `cellSize`)
     strictly decreasing under Squier peak-elimination — so the recursion is STRUCTURAL FUEL, not
     `WellFounded.fix` (whose `propext` / `Quot.sound` leak is the Init-only wall; the involution's
     rewriting is length-monotone, so this measure EXISTS).
  3. **Completeness of the generating 3-cells** — every 2-path critical branching is one of the shipped
     `*ThreeCell`s.  ★ HERE the COUNT certificate is load-bearing: for cyclic-3 the basis must contain
     BOTH `ssss` and `sssss`, or the branching has an unfilled 2-sphere
     (`cyclicThreeOmegaCriticalPairCountIsTwo` is the confluence-data count).
  4. **The orthogonality 3-cells** (UNSHIPPED) — the disjoint-redex commutation squares (`ssssss` width-0
     diamond) needed for the closure — the concrete missing datum.
  5. **Newman-at-dim-3** (local confluence + termination ⇒ confluence through the normal form) — feasible
     ONLY if obligation 2 gives a structural-fuel decoder rather than `WellFounded.fix` (the Wall A/B of
     `SquierAscentLedger` / `InvolutionSquierBasis`).

Blocking node: a `conv_toParityNF`-analogue at the 2-path level (a normalizer on reduction sequences one
dimension up) plus general Squier coherence needing OMEGA-2 Steiner arithmetic at n=3 AND termination of
3-cell rewriting, where Forest-Mimram (arXiv:2109.05369) stayed pen-and-paper (cite Guiraud-Malbos).

Raw Lean 4 + Init.  Per-declaration `#assert_no_axioms` gated in the audit twin. -/

namespace FX1Poly.Polygraph.Omega

/-! ## The walking-cyclic-3 2-polygraph as an `OmegaComputad` -/

/-- The **walking-cyclic-3 omega-computad**: one object (`Unit`), one generator label at every dimension
(`Unit`).  A single 2-generator `R`, so a constant `Unit` label family suffices (like the involution's and
the idempotent's, unlike the monad's `Bool`) — no `Nat`-match in `genLabel`, so propext-clean. -/
def cyclicThreeOmegaComputad : OmegaComputad where
  modeCarrier := Unit
  genLabel := fun _ => Unit

/-- The trivial mode comparator (one object). -/
def cyclicThreeOmegaModeBeq :
    cyclicThreeOmegaComputad.modeCarrier → cyclicThreeOmegaComputad.modeCarrier → Bool :=
  fun _ _ => true

/-- The trivial heterogeneous generator comparator — the leg-distinctness probes are STRUCTURAL (whisker
orders differ), so the comparator need not separate labels. -/
def cyclicThreeOmegaGenBeq :
    (dimA dimB : Nat) → cyclicThreeOmegaComputad.genLabel dimA →
      cyclicThreeOmegaComputad.genLabel dimB → Bool :=
  fun _ _ _ _ => true

/-- The single object `*`. -/
def cyclicThreeOmegaPoint : CellExpr cyclicThreeOmegaComputad 0 := CellExpr.ofMode ()

/-- The endo-1-generator `s : * => *`. -/
def cyclicThreeOmegaSGen : CellExpr cyclicThreeOmegaComputad 1 :=
  CellExpr.gen (dim := 0) () cyclicThreeOmegaPoint cyclicThreeOmegaPoint

/-- The 1-cell `s.s` (the residual of the length-1 overlap, and the inner block of the rule's LHS). -/
def cyclicThreeOmegaSsWord : CellExpr cyclicThreeOmegaComputad 1 :=
  CellExpr.vcomp cyclicThreeOmegaSGen cyclicThreeOmegaSGen

/-- The 1-cell `s.s.s` (the rule's left-hand side, left-associated `(ss)s`). -/
def cyclicThreeOmegaSssWord : CellExpr cyclicThreeOmegaComputad 1 :=
  CellExpr.vcomp cyclicThreeOmegaSsWord cyclicThreeOmegaSGen

/-- The identity 1-cell `id` (the rule's right-hand side, `s^0`). -/
def cyclicThreeOmegaIdOne : CellExpr cyclicThreeOmegaComputad 1 :=
  CellExpr.id cyclicThreeOmegaPoint

/-- ★ The **rewrite rule** `R : s.s.s => id` as the single 2-cell generator.  Globular: `(ss)s` and `id`
are both `* => *`.  The rule LHS association `(ss)s` (left-assoc, matching `cyclicThreeOmegaSssWord`) is
arbitrary — every association is related by `vcompAssoc` rows, so the joins close regardless. -/
def cyclicThreeOmegaRhoGen : CellExpr cyclicThreeOmegaComputad 2 :=
  CellExpr.gen (dim := 1) () cyclicThreeOmegaSssWord cyclicThreeOmegaIdOne

/-! ## The two legs of the length-2 overlap critical pair `ssss` (whisker by `s`) -/

/-- The **`ssss` left leg**: reduce the FRONT `sss` — `R` whiskered on the right by `s`
(`((ss)s)s => (id)s`, residual `s` on the RIGHT). -/
def cyclicThreeOmegaSsssLeftLeg : CellExpr cyclicThreeOmegaComputad 2 :=
  CellExpr.whiskerRight cyclicThreeOmegaRhoGen cyclicThreeOmegaSGen

/-- The **`ssss` right leg**: reduce the BACK `sss` — `R` whiskered on the left by `s`
(`s((ss)s) => s(id)`, residual `s` on the LEFT). -/
def cyclicThreeOmegaSsssRightLeg : CellExpr cyclicThreeOmegaComputad 2 :=
  CellExpr.whiskerLeft cyclicThreeOmegaSGen cyclicThreeOmegaRhoGen

/-- The `ssss` left leg's source 1-cell is the front-associated peak `((ss)s)s`. -/
theorem cyclicThreeOmegaSsssLeftLeg_boundarySource :
    boundarySource cyclicThreeOmegaSsssLeftLeg
      = CellExpr.vcomp cyclicThreeOmegaSssWord cyclicThreeOmegaSGen := rfl

/-- The `ssss` left leg's target 1-cell is `(id)s`. -/
theorem cyclicThreeOmegaSsssLeftLeg_boundaryTarget :
    boundaryTarget cyclicThreeOmegaSsssLeftLeg
      = CellExpr.vcomp cyclicThreeOmegaIdOne cyclicThreeOmegaSGen := rfl

/-- The `ssss` right leg's source 1-cell is the back-associated peak `s((ss)s)`. -/
theorem cyclicThreeOmegaSsssRightLeg_boundarySource :
    boundarySource cyclicThreeOmegaSsssRightLeg
      = CellExpr.vcomp cyclicThreeOmegaSGen cyclicThreeOmegaSssWord := rfl

/-- The `ssss` right leg's target 1-cell is `s(id)`. -/
theorem cyclicThreeOmegaSsssRightLeg_boundaryTarget :
    boundaryTarget cyclicThreeOmegaSsssRightLeg
      = CellExpr.vcomp cyclicThreeOmegaSGen cyclicThreeOmegaIdOne := rfl

/-! ## The two legs of the length-1 overlap critical pair `sssss` (whisker by `s.s`) -/

/-- The **`sssss` left leg**: reduce the front `sss` — `R` whiskered on the right by `ss`
(`((ss)s)(ss) => (id)(ss)`). -/
def cyclicThreeOmegaSssssLeftLeg : CellExpr cyclicThreeOmegaComputad 2 :=
  CellExpr.whiskerRight cyclicThreeOmegaRhoGen cyclicThreeOmegaSsWord

/-- The **`sssss` right leg**: reduce the back `sss` — `R` whiskered on the left by `ss`
(`(ss)((ss)s) => (ss)(id)`). -/
def cyclicThreeOmegaSssssRightLeg : CellExpr cyclicThreeOmegaComputad 2 :=
  CellExpr.whiskerLeft cyclicThreeOmegaSsWord cyclicThreeOmegaRhoGen

/-- The `sssss` left leg's source 1-cell is `((ss)s)(ss)`. -/
theorem cyclicThreeOmegaSssssLeftLeg_boundarySource :
    boundarySource cyclicThreeOmegaSssssLeftLeg
      = CellExpr.vcomp cyclicThreeOmegaSssWord cyclicThreeOmegaSsWord := rfl

/-- The `sssss` left leg's target 1-cell is `(id)(ss)`. -/
theorem cyclicThreeOmegaSssssLeftLeg_boundaryTarget :
    boundaryTarget cyclicThreeOmegaSssssLeftLeg
      = CellExpr.vcomp cyclicThreeOmegaIdOne cyclicThreeOmegaSsWord := rfl

/-- The `sssss` right leg's source 1-cell is `(ss)((ss)s)`. -/
theorem cyclicThreeOmegaSssssRightLeg_boundarySource :
    boundarySource cyclicThreeOmegaSssssRightLeg
      = CellExpr.vcomp cyclicThreeOmegaSsWord cyclicThreeOmegaSssWord := rfl

/-- The `sssss` right leg's target 1-cell is `(ss)(id)`. -/
theorem cyclicThreeOmegaSssssRightLeg_boundaryTarget :
    boundaryTarget cyclicThreeOmegaSssssRightLeg
      = CellExpr.vcomp cyclicThreeOmegaSsWord cyclicThreeOmegaIdOne := rfl

/-! ## The critical-pair row family and the base relation -/

/-- ★ The **two walking-cyclic-3 critical-pair rows** — a `CellRelOver` firing on each of the two
overlaps' two reduction legs.  The walking cyclic-3's homotopy basis at Squier's convergent scope: TWO
generating 3-cells from ONE rule (the new-shape observation). -/
inductive CyclicThreeCriticalRow :
    {d : Nat} → CellExpr cyclicThreeOmegaComputad d → CellExpr cyclicThreeOmegaComputad d → Prop where
  /-- (a) the length-2 overlap `ssss` — the two whisker orders of `R` by `s`. -/
  | ssss : CyclicThreeCriticalRow cyclicThreeOmegaSsssLeftLeg cyclicThreeOmegaSsssRightLeg
  /-- (b) the length-1 overlap `sssss` — the two whisker orders of `R` by `ss`. -/
  | sssss : CyclicThreeCriticalRow cyclicThreeOmegaSssssLeftLeg cyclicThreeOmegaSssssRightLeg

/-- The base relation the 3-cells resolve: the strict omega laws united with the two critical-pair rows. -/
def cyclicThreeOmegaBaseRel : CellRelOver cyclicThreeOmegaComputad :=
  unionCellRel cyclicThreeOmegaComputad
    (StrictAxiomRel cyclicThreeOmegaComputad) CyclicThreeCriticalRow

/-! ## The two generating 3-cells -/

/-- ★ **THE `ssss` GENERATING 3-CELL.**  The length-2 overlap critical pair fired through `ofRelation`. -/
def cyclicThreeOmegaSsssThreeCell :
    SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
      cyclicThreeOmegaSsssLeftLeg cyclicThreeOmegaSsssRightLeg :=
  SaturatedConvOverWithId.ofRelation (Or.inr CyclicThreeCriticalRow.ssss)

/-- ★ **THE `sssss` GENERATING 3-CELL.**  The length-1 overlap critical pair fired through `ofRelation`. -/
def cyclicThreeOmegaSssssThreeCell :
    SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
      cyclicThreeOmegaSssssLeftLeg cyclicThreeOmegaSssssRightLeg :=
  SaturatedConvOverWithId.ofRelation (Or.inr CyclicThreeCriticalRow.sssss)

/-! ## The peak joins — the associativity chains (the genuinely new proof content) -/

/-- ★ **THE `ssss` PEAK JOIN — a 3-STEP associativity chain.**  `((ss)s)s ~ s((ss)s)`, which NO single
`vcompAssoc` row relates.  Step 1 `vcompAssoc (ss) s s`: `((ss)s)s ~ (ss)(ss)`.  Step 2
`vcompAssoc s s (ss)`: `(ss)(ss) ~ s(s(ss))`.  Step 3 (the reverse of a right-congruence over
`vcompAssoc s s s`): `s(s(ss)) ~ s((ss)s)`.  Pure `trans` / `symm` / `vcompCongrRight` / `ofRelation`. -/
def cyclicThreeOmegaSsssPeakJoin :
    SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
      (boundarySource cyclicThreeOmegaSsssLeftLeg) (boundarySource cyclicThreeOmegaSsssRightLeg) :=
  SaturatedConvOverWithId.trans
    (SaturatedConvOverWithId.ofRelation
      (Or.inl (StrictAxiomRel.vcompAssoc cyclicThreeOmegaSsWord cyclicThreeOmegaSGen
        cyclicThreeOmegaSGen)))
    (SaturatedConvOverWithId.trans
      (SaturatedConvOverWithId.ofRelation
        (Or.inl (StrictAxiomRel.vcompAssoc cyclicThreeOmegaSGen cyclicThreeOmegaSGen
          cyclicThreeOmegaSsWord)))
      (SaturatedConvOverWithId.symm
        (SaturatedConvOverWithId.vcompCongrRight cyclicThreeOmegaSGen
          (SaturatedConvOverWithId.ofRelation
            (Or.inl (StrictAxiomRel.vcompAssoc cyclicThreeOmegaSGen cyclicThreeOmegaSGen
              cyclicThreeOmegaSGen))))))

/-- ★ **THE `sssss` PEAK JOIN — a 2-STEP associativity chain.**  `((ss)s)(ss) ~ (ss)((ss)s)`.  Step 1
`vcompAssoc (ss) s (ss)`: `((ss)s)(ss) ~ (ss)(s(ss))`.  Step 2 (the reverse of a right-congruence over
`vcompAssoc s s s`): `(ss)(s(ss)) ~ (ss)((ss)s)`. -/
def cyclicThreeOmegaSssssPeakJoin :
    SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
      (boundarySource cyclicThreeOmegaSssssLeftLeg) (boundarySource cyclicThreeOmegaSssssRightLeg) :=
  SaturatedConvOverWithId.trans
    (SaturatedConvOverWithId.ofRelation
      (Or.inl (StrictAxiomRel.vcompAssoc cyclicThreeOmegaSsWord cyclicThreeOmegaSGen
        cyclicThreeOmegaSsWord)))
    (SaturatedConvOverWithId.symm
      (SaturatedConvOverWithId.vcompCongrRight cyclicThreeOmegaSsWord
        (SaturatedConvOverWithId.ofRelation
          (Or.inl (StrictAxiomRel.vcompAssoc cyclicThreeOmegaSGen cyclicThreeOmegaSGen
            cyclicThreeOmegaSGen)))))

/-! ## The valley joins — the leg TARGETS join through the common valley modulo the strict units -/

/-- The `ssss` valley: the two leg TARGETS join through the common valley `s`: `(id)s ~ s ~ s(id)`
(both units).  Verbatim the involution's `involutionValleyJoin` idiom. -/
def cyclicThreeOmegaSsssValleyJoin :
    SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
      (boundaryTarget cyclicThreeOmegaSsssLeftLeg) (boundaryTarget cyclicThreeOmegaSsssRightLeg) :=
  SaturatedConvOverWithId.trans
    (SaturatedConvOverWithId.ofRelation (Or.inl (StrictAxiomRel.vcompUnitLeft cyclicThreeOmegaSGen)))
    (SaturatedConvOverWithId.symm
      (SaturatedConvOverWithId.ofRelation (Or.inl (StrictAxiomRel.vcompUnitRight cyclicThreeOmegaSGen))))

/-- The `sssss` valley: the two leg TARGETS join through the common valley `ss`: `(id)(ss) ~ ss ~ (ss)(id)`
(both units).  The monad's `rightUnitAssocPeakJoin` idiom with `ss` as the whiskering block. -/
def cyclicThreeOmegaSssssValleyJoin :
    SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
      (boundaryTarget cyclicThreeOmegaSssssLeftLeg) (boundaryTarget cyclicThreeOmegaSssssRightLeg) :=
  SaturatedConvOverWithId.trans
    (SaturatedConvOverWithId.ofRelation (Or.inl (StrictAxiomRel.vcompUnitLeft cyclicThreeOmegaSsWord)))
    (SaturatedConvOverWithId.symm
      (SaturatedConvOverWithId.ofRelation
        (Or.inl (StrictAxiomRel.vcompUnitRight cyclicThreeOmegaSsWord))))

/-! ## The assembled per-pair resolutions -/

/-- ★ A **coherent resolution** of one cyclic-3 critical pair, joinable MODULO the strict congruence: the
two leg SOURCES are convertible (the associativity peak chain), the two legs are convertible (the
generating 3-cell), and the two leg TARGETS are convertible (the units valley).  Parameterised by the two
legs (the monad's `MonadCriticalPairResolved` at two pairs). -/
structure CyclicThreeOmegaCriticalPairResolved {d : Nat}
    (leftLeg rightLeg : CellExpr cyclicThreeOmegaComputad (d + 1)) : Prop where
  /-- The two leg SOURCES are convertible (the peak chain). -/
  peakJoined : SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
    (boundarySource leftLeg) (boundarySource rightLeg)
  /-- The two legs are convertible (the generating 3-cell). -/
  legsConvertible : SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
    leftLeg rightLeg
  /-- The two leg TARGETS are convertible (the valley). -/
  valleyJoined : SaturatedConvOverWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel
    (boundaryTarget leftLeg) (boundaryTarget rightLeg)

/-- The `ssss` pair is coherently resolved (peak 3-step assoc chain, valley units). -/
theorem cyclicThreeOmegaSsssResolved :
    CyclicThreeOmegaCriticalPairResolved cyclicThreeOmegaSsssLeftLeg cyclicThreeOmegaSsssRightLeg :=
  ⟨cyclicThreeOmegaSsssPeakJoin, cyclicThreeOmegaSsssThreeCell, cyclicThreeOmegaSsssValleyJoin⟩

/-- The `sssss` pair is coherently resolved (peak 2-step assoc chain, valley units). -/
theorem cyclicThreeOmegaSssssResolved :
    CyclicThreeOmegaCriticalPairResolved cyclicThreeOmegaSssssLeftLeg cyclicThreeOmegaSssssRightLeg :=
  ⟨cyclicThreeOmegaSssssPeakJoin, cyclicThreeOmegaSssssThreeCell, cyclicThreeOmegaSssssValleyJoin⟩

/-! ## The least-congruence universal property (map-out) -/

/-- ★ **THE TWO 3-CELLS GENERATE THE IDENTIFICATION (least-congruence UP).**  For any relation `targetRel`
absorbing the cyclic-3 base relation (a congruence containing the strict laws and the two critical-pair
rows), the two legs of EVERY cyclic-3 critical row are `targetRel`-related — so the two generating 3-cells
are the datum whose fold through `SaturatedConvOverWithId.recInto` identifies each critical pair in EVERY
model.  Uniform in the row (one statement covering both, keyed on `CyclicThreeCriticalRow`). -/
theorem cyclicThreeOmegaCriticalPairsIdentifiedInEveryModel
    {targetRel : CellRelOver cyclicThreeOmegaComputad}
    (absorbs : IsSaturatedCongruenceWithId cyclicThreeOmegaComputad cyclicThreeOmegaBaseRel targetRel)
    {d : Nat} {leftLeg rightLeg : CellExpr cyclicThreeOmegaComputad d}
    (row : CyclicThreeCriticalRow leftLeg rightLeg) : targetRel leftLeg rightLeg :=
  SaturatedConvOverWithId.recInto absorbs (SaturatedConvOverWithId.ofRelation (Or.inr row))

/-! ## The native two-count and the cofork column (correspondence NAMED to the Homology lane) -/

/-- The two critical-pair labels, re-declared NATIVELY over this substrate (mirroring the Homology lane's
`CyclicThreeCriticalPairs`; the correspondence is named, not imported). -/
inductive CyclicThreeOmegaCriticalPairLabel
  /-- (a) the length-2 overlap `ssss`. -/
  | ssss
  /-- (b) the length-1 overlap `sssss`. -/
  | sssss

/-- The complete enumeration of the walking-cyclic-3 critical pairs over this substrate — TWO, listed. -/
def allCyclicThreeOmegaCriticalPairs : List CyclicThreeOmegaCriticalPairLabel := [.ssss, .sssss]

/-- ★ **The critical-pair count is exactly TWO** — kernel-checked (`rfl`), re-derived natively (it matches
the Homology lane's `cyclicThreeCriticalPairCountIsTwo`). -/
theorem cyclicThreeOmegaCriticalPairCountIsTwo : allCyclicThreeOmegaCriticalPairs.length = 2 := rfl

/-- ★ **The enumeration is EXHAUSTIVE** — every label appears (full case split). -/
theorem allCyclicThreeOmegaCriticalPairsExhaustive :
    ∀ pair : CyclicThreeOmegaCriticalPairLabel, pair ∈ allCyclicThreeOmegaCriticalPairs
  | .ssss => List.Mem.head _
  | .sssss => List.Mem.tail _ (List.Mem.head _)

/-- The **generating-rule count** — ONE (the single 2-generator `R`).  The new-shape datum: it is strictly
less than the critical-pair count TWO (`cyclicThreeOmegaCriticalPairCountIsTwo`). -/
def cyclicThreeOmegaGeneratingRuleCount : Nat := 1

/-- The abelianized cofork column of each critical pair — a single `Nat` (one 2-generator `R`, so the
column is the net `#R` count; both whisker legs of each pair fire `R` once, so the net cancels to `0`).
The correspondence to the Homology lane's `cyclicThreeCriticalPairBoundaryColumn` (`Int`-valued Smith
column, `H1 = ZZ/3`) is NAMED here, not proven across substrates. -/
def cyclicThreeOmegaCriticalPairCoforkColumn : CyclicThreeOmegaCriticalPairLabel → Nat
  | .ssss => 0
  | .sssss => 0

/-! ## The coherent-presentation statement (the honest-scope bundle) -/

/-- ★ **The walking-cyclic-3 coherent-presentation statement (honest scope).**  Both critical pairs are
coherently resolved modulo the strict congruence.  A `Prop` conjunction of the two per-pair resolutions. -/
def CyclicThreeWalkerCoherentPresentationStatement : Prop :=
  CyclicThreeOmegaCriticalPairResolved cyclicThreeOmegaSsssLeftLeg cyclicThreeOmegaSsssRightLeg ∧
  CyclicThreeOmegaCriticalPairResolved cyclicThreeOmegaSssssLeftLeg cyclicThreeOmegaSssssRightLeg

/-- ★★ **THE WALKING-CYCLIC-3 COHERENT PRESENTATION (two critical pairs, joinable modulo strict).**  The
two per-pair resolutions assembled into one datum: the walking cyclic-3 `<s | s.s.s => id>` re-encoded as
an `OmegaComputad` 2-polygraph has both Squier critical pairs exhibited as generating 3-cells, each
joinable-modulo-strict at peak (associativity chains) and valley (units) — the fourth walker (after the
involution, monad, idempotent) to reach this scope, and the first new-shape one (1 rule, 2 critical
pairs). -/
theorem cyclicThreeWalkerCoherentPresentation : CyclicThreeWalkerCoherentPresentationStatement :=
  ⟨cyclicThreeOmegaSsssResolved, cyclicThreeOmegaSssssResolved⟩

/-! ## Non-vacuity — the four legs are genuinely distinct, the peaks are modulo strict -/

/-- The `ssss` legs are structurally DISTINCT (whisker-right vs whisker-left). -/
theorem cyclicThreeOmegaSsssLegs_distinct :
    cellBeq cyclicThreeOmegaModeBeq cyclicThreeOmegaGenBeq
      cyclicThreeOmegaSsssLeftLeg cyclicThreeOmegaSsssRightLeg = false := rfl

/-- The `sssss` legs are structurally DISTINCT. -/
theorem cyclicThreeOmegaSssssLegs_distinct :
    cellBeq cyclicThreeOmegaModeBeq cyclicThreeOmegaGenBeq
      cyclicThreeOmegaSssssLeftLeg cyclicThreeOmegaSssssRightLeg = false := rfl

/-- The `ssss` peak spellings are structurally distinct (`((ss)s)s` vs `s((ss)s)`, spanning three
associations) — so parallelism holds only MODULO strict (the honest fragment boundary, exactly the
involution's `involutionLegs_notLiterallyParallel`). -/
theorem cyclicThreeOmegaSsssLegs_notLiterallyParallel :
    cellBeq cyclicThreeOmegaModeBeq cyclicThreeOmegaGenBeq
      (boundarySource cyclicThreeOmegaSsssLeftLeg)
      (boundarySource cyclicThreeOmegaSsssRightLeg) = false := rfl

/-- The `sssss` peak spellings are structurally distinct (`((ss)s)(ss)` vs `(ss)((ss)s)`). -/
theorem cyclicThreeOmegaSssssLegs_notLiterallyParallel :
    cellBeq cyclicThreeOmegaModeBeq cyclicThreeOmegaGenBeq
      (boundarySource cyclicThreeOmegaSssssLeftLeg)
      (boundarySource cyclicThreeOmegaSssssRightLeg) = false := rfl

/-! ## Non-vacuity probes -/

#eval cellBeq cyclicThreeOmegaModeBeq cyclicThreeOmegaGenBeq
  cyclicThreeOmegaSsssLeftLeg cyclicThreeOmegaSsssRightLeg
#eval cellBeq cyclicThreeOmegaModeBeq cyclicThreeOmegaGenBeq
  cyclicThreeOmegaSssssLeftLeg cyclicThreeOmegaSssssRightLeg
#eval cellBeq cyclicThreeOmegaModeBeq cyclicThreeOmegaGenBeq
  (boundarySource cyclicThreeOmegaSsssLeftLeg) (boundarySource cyclicThreeOmegaSsssRightLeg)
#eval allCyclicThreeOmegaCriticalPairs.length
#eval cyclicThreeOmegaGeneratingRuleCount

/-! ## The honesty markers -/

/-- ★ **ESTABLISHED (fragment scope).**  The walking cyclic-3 `<s | s.s.s => id>` re-encoded as an
`OmegaComputad` 2-polygraph has its TWO Squier critical pairs (`ssss` / `sssss`) exhibited as dim-3
content: the four reduction legs, the two generating 3-cells (`cyclicThreeOmega*ThreeCell`), the two peak
joins (associativity chains — 3-step / 2-step) and the two valley joins (units), assembled into
`cyclicThreeWalkerCoherentPresentation`.  Two-count kernel-checked natively
(`cyclicThreeOmegaCriticalPairCountIsTwo`), the correspondence to the Homology lane's two-count NAMED.
The scope is HONEST: both pairs are parallel only modulo strict
(`cyclicThreeOmega*Legs_notLiterallyParallel`).  `= true`. -/
def fxOmega4_cyclicThreeTwoCriticalPairsShipped : Bool := true

/-- ★ **THE FIRST NEW-SHAPE WALKER (rule-count 1 < critical-pair-count 2).**  `= true` records that
cyclic-3 is the first walker whose critical-pair count strictly exceeds its rule count: ONE rule `R`
(`cyclicThreeOmegaGeneratingRuleCount = 1`) generates TWO critical pairs
(`cyclicThreeOmegaCriticalPairCountIsTwo`), because the length-3 rule source `sss` has two self-overlaps.
This is why the COUNT certificate is load-bearing for the full-basis completeness obligation (obligation 3
in the file docstring). -/
def fxOmega4_cyclicThreeOneRuleTwoCriticalPairsNewShape : Bool := true

/-- ★ **WALL / OMEGA-5 HANDOFF (honest).**  `= false` records that the FULL homotopy basis for the walking
cyclic-3 — every parallel 2-path pair `s^n => s^k` 3-cell-homotopic, by a structural length-fuel 2-path
normalizer one dimension up — is NOT reached this round, exactly as the involution / monad / idempotent
deferred it.  Blocking node: a 2-path normalizer (`conv_toParityNF`-analogue at the 2-path level) over the
two-generator homotopy basis (obligations 1-5 named in the file docstring — obligation 3, completeness of
the two generating 3-cells, is where the two-count becomes confluence data); the shipped content is the
two generating 3-cells + their peak/valley joins, not the closure of every 2-sphere. -/
def fxOmega4_cyclicThreeFullHomotopyBasisReached : Bool := false

end FX1Poly.Polygraph.Omega
