import FX1Poly.Polygraph.Omega.WalkingBunchedBimonoidStrictLawAbsorber

/-! # Polygraph/Omega/WalkingBunchedBimonoidRiffleNaturality — the riffle word primitive, the collision peel
recursion, the width-3 naturality slides, and the honest refutation of the naive general `wideSwap` fold
(WP-PROP r7, #2033, the 110-percent grind)

★ **The r6 `WideCollision` walled the general `wideSwap(m,n)` riffle word at WORD granularity
(`fxBunchedBimonoid_wideSwapGeneralRiffleWordUnbuilt = false`).  This file advances that node with a genuine,
machine-checked riffle PRIMITIVE and a decisive truth-probe on the general assembly.**

## The riffle primitive `strandPastBlock` (the elementary letter, DELIVERED)

The recon named the elementary riffle letter: moving ONE input strand past a block of `k` output strands is the
block braiding `sigma_{a, a^k} : a.a^k => a^k.a`.  `bunchedBimonoidStrandPastBlock` builds it by structural
recursion on the block size `k` (a whiskered chain of adjacent `sigma`s: `k = 0` the identity, `k = 1` the bare
`sigma`, `k+2` = `(sigma |> a^{k+1}) ; (a <| strandPastBlock(k+1))`).  Truth-probed at `k = 0,1,2,3`: it
evaluates to the cyclic shift matrix moving strand 0 to the end (`strandPastBlock 2 = wideSymmetryFront`, the
shipped hexagon front, on the nose).  This is a genuine general def, correct at every probed width.

## The collision peel recursion (the two peel lemmas, DELIVERED as `rfl`)

The wide collision `muFold m ; deltaFan n` peels one waist strand per step; the exact peel shapes are the mu-fold
/ delta-fan defs read as equations: `muFold (k+2) = (muFold (k+1) |> a) ; mu_a` and `deltaFan (k+2) = delta_a ;
(deltaFan (k+1) |> a)`.  Both are `rfl` — the recursion floor the double induction stands on.

## The width-3 naturality SLIDES (the recursion's slide step, DELIVERED as CONV)

Each riffle letter, once generated by the base bialgebra brick, must be threaded across the residual `mu`/`delta`
via the width-3 hexagon naturality rows.  Those slides fire as genuine convertibilities over the star scope
(`muNaturality` / `deltaNaturality`), shipped here as the width-3 CONV instances the recon's self-attack (i)
demands.

## The naive general `wideSwap` fold is REFUTED (the decisive truth-probe)

A naive "slide one input strand past the grown output grid" fold does NOT compute the riffle: truth-probed at
`(2,2)` it yields a `3 x 3` cyclic shift, but the genuine `wideSwap(2,2)` is the `4 x 4` middle swap
`bunchedBimonoidMiddleSwap` (`m*n = 4` strands).  `bunchedBimonoidWideSwapNaiveFoldRefutedAtTwoTwo` machine-checks
the disagreement (rows `3 != 4`).  So the general riffle word is genuinely more than the primitive + a naive fold
— the general `wideSwap` assembly stays the honest r6/r7 residual, walled byte-intact.

Raw Lean 4 + Init; STRUCTURAL only; ASCII-only.  Per-declaration `#assert_no_axioms` gated in the audit twin. -/

namespace FX1Poly.Polygraph.Omega

/-! The width-3/4 permutation `rfl` matrix reductions exceed the default heartbeat budget; the raise is a compute
allowance only, the proof terms stay `Eq.refl`, axiom-free (uniform with the r6 `WideCollision` reductions). -/
set_option maxHeartbeats 4000000

/-! # =========================================================================================
    # B1 — THE RIFFLE PRIMITIVE: the word power + the single-strand-past-a-block braiding
    # =========================================================================================
-/

/-- The **additive word power** `a^k : * => *` — the `k`-fold vertical composite of the additive 1-generator
`a` (`0` = the empty word `id`, `k+1` = `a . a^k`).  `evalCell (a^k) = k` (its width).  The 1-cell block a
riffle letter whiskers by. -/
def bunchedBimonoidAWordPow : Nat → CellExpr bunchedBimonoidOmegaComputad 1
  | 0 => bunchedBimonoidIdOne
  | k + 1 => CellExpr.vcomp bunchedBimonoidAdditiveGen (bunchedBimonoidAWordPow k)

/-- ★★ **THE RIFFLE PRIMITIVE `strandPastBlock k : a.a^k => a^k.a`** — the block braiding `sigma_{a, a^k}` moving
the leading strand past a block of `k` strands, built as a whiskered chain of adjacent `sigma`s by structural
recursion on the block size: `0` is the identity (nothing to pass), `1` is the bare `sigma`, `k+2` swaps the
leading pair (`sigma |> a^{k+1}`) then recurses on the block under the fixed front strand
(`a <| strandPastBlock(k+1)`).  A genuine general def; `evalCell (strandPastBlock k)` is the `(k+1) x (k+1)`
cyclic shift moving strand 0 to the end (truth-probed below). -/
def bunchedBimonoidStrandPastBlock : Nat → CellExpr bunchedBimonoidOmegaComputad 2
  | 0 => CellExpr.id bunchedBimonoidAdditiveGen
  | 1 => bunchedBimonoidAddSigmaGen
  | n + 2 => CellExpr.vcomp
      (CellExpr.whiskerRight bunchedBimonoidAddSigmaGen (bunchedBimonoidAWordPow (n + 1)))
      (CellExpr.whiskerLeft bunchedBimonoidAdditiveGen (bunchedBimonoidStrandPastBlock (n + 1)))

/-! ## B1 truth-probe outputs (the primitive evaluates to the cyclic shift) -/

#eval bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 0)
#eval bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 1)
#eval bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 2)
#eval bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 3)

/-- The trivial `strandPastBlock 0` is the width-1 identity `[[1]]`. -/
theorem bunchedBimonoidStrandPastBlockZeroMatrix :
    bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 0)
      = { rows := 1, cols := 1, entries := [[1]] } := rfl

/-- `strandPastBlock 1` is the bare swap `[[0,1],[1,0]]` — the single adjacent transposition. -/
theorem bunchedBimonoidStrandPastBlockOneMatrix :
    bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 1)
      = { rows := 2, cols := 2, entries := [[0, 1], [1, 0]] } := rfl

/-- ★★ `strandPastBlock 2` is the `3 x 3` cyclic shift `[[0,1,0],[0,0,1],[1,0,0]]` moving strand 0 to the end. -/
theorem bunchedBimonoidStrandPastBlockTwoMatrix :
    bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 2)
      = { rows := 3, cols := 3, entries := [[0, 1, 0], [0, 0, 1], [1, 0, 0]] } := rfl

/-- `strandPastBlock 3` is the `4 x 4` cyclic shift moving strand 0 to the end. -/
theorem bunchedBimonoidStrandPastBlockThreeMatrix :
    bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 3)
      = { rows := 4, cols := 4, entries := [[0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]] } := rfl

/-- ★★ **THE PRIMITIVE MEETS THE SHIPPED HEXAGON — `strandPastBlock 2` and `wideSymmetryFront` share their matrix
(`rfl`).**  The `k = 2` block braiding evaluates to the same cyclic shift as the shipped front wide symmetry
`(sigma |> a) ; (a <| sigma)` (the map the mu/delta naturality hexagons already use).  They differ as CELLS only
by the `a^1 = a.id` vs `a` whisker-block spelling (extrinsic composability), so this is a matrix agreement, not a
definitional cell equality — the riffle primitive is semantically continuous with the r4 hexagon layer. -/
theorem bunchedBimonoidStrandPastBlockTwoMatchesWideSymmetryFront :
    bunchedBimonoidEvalCell (bunchedBimonoidStrandPastBlock 2)
      = bunchedBimonoidEvalCell bunchedBimonoidWideSymmetryFront := rfl

/-! # =========================================================================================
    # B1 — THE COLLISION PEEL RECURSION (the two peel lemmas, rfl)
    # =========================================================================================
-/

/-- ★ **THE MU-PEEL** — `muFold (k+2) = (muFold (k+1) |> a) ; mu_a` (`rfl`).  One step of the collision's
left-side induction: peel the trailing multiplication off the fold, exposing the `mu_a` the base bialgebra brick
fires on.  The exact recursion shape the r6 `wideCollisionConvRecursion` marker names. -/
theorem bunchedBimonoidMuFoldPeel (k : Nat) :
    bunchedBimonoidMuFold (k + 2)
      = CellExpr.vcomp (CellExpr.whiskerRight (bunchedBimonoidMuFold (k + 1)) bunchedBimonoidAdditiveGen)
          bunchedBimonoidAddMuGen := rfl

/-- ★ **THE DELTA-PEEL** — `deltaFan (k+2) = delta_a ; (deltaFan (k+1) |> a)` (`rfl`).  The dual: peel the leading
comultiplication off the fan, exposing the `delta_a` the base brick fires on.  Together with the mu-peel these
are the two induction steps of the wide collision double induction. -/
theorem bunchedBimonoidDeltaFanPeel (k : Nat) :
    bunchedBimonoidDeltaFan (k + 2)
      = CellExpr.vcomp bunchedBimonoidAddDeltaGen
          (CellExpr.whiskerRight (bunchedBimonoidDeltaFan (k + 1)) bunchedBimonoidAdditiveGen) := rfl

/-! # =========================================================================================
    # B1 — THE WIDTH-3 NATURALITY SLIDES (the recursion's slide step, CONV)
    # =========================================================================================
-/

/-- ★★ **THE MU-NATURALITY SLIDE (width-3 CONV).**  `(a <| mu) ; sigma ~ [(sigma |> a) ; (a <| sigma)] ; (mu |> a)`
over the star scope, fired by the `muNaturality` hexagon row through `Or.inr (Or.inr ...)`.  This is the SLIDE
step the collision recursion threads: the generated middle `sigma` moves across the residual `mu`.  The recon's
self-attack (i) width-3 CONV instance. -/
theorem bunchedBimonoidMuNaturalitySlideConv :
    SaturatedConvOverWithId bunchedBimonoidOmegaComputad bunchedBimonoidStarCongruenceScope
      bunchedBimonoidMuNaturalityLeftLeg bunchedBimonoidMuNaturalityRightLeg :=
  SaturatedConvOverWithId.ofRelation (Or.inr (Or.inr BunchedBimonoidHexagonRow.muNaturality))

/-- ★★ **THE DELTA-NATURALITY SLIDE (width-3 CONV).**  `sigma ; (a <| delta) ~ (delta |> a) ; [(a <| sigma) ;
(sigma |> a)]` over the star scope, fired by the `deltaNaturality` hexagon row.  The dual slide, threading the
generated `sigma` across the residual `delta`.  The second width-3 CONV instance. -/
theorem bunchedBimonoidDeltaNaturalitySlideConv :
    SaturatedConvOverWithId bunchedBimonoidOmegaComputad bunchedBimonoidStarCongruenceScope
      bunchedBimonoidDeltaNaturalityLeftLeg bunchedBimonoidDeltaNaturalityRightLeg :=
  SaturatedConvOverWithId.ofRelation (Or.inr (Or.inr BunchedBimonoidHexagonRow.deltaNaturality))

/-! ## The B1 primitive-and-slide marker -/

/-- ★★ **ESTABLISHED (B1) — the riffle primitive + peel recursion + width-3 slides are shipped.**  `= true`
records `bunchedBimonoidStrandPastBlock` (the general block-braiding riffle letter, cyclic-shift matrix probed at
`k = 0,1,2,3` and matrix-matching the shipped `wideSymmetryFront` at `k = 2`); the two collision peel lemmas
(`bunchedBimonoidMuFoldPeel` / `bunchedBimonoidDeltaFanPeel`, the induction steps as `rfl`); and the two width-3
naturality slides as CONV over the star scope (`bunchedBimonoid{Mu,Delta}NaturalitySlideConv`).  The atoms of the
wide-collision recursion, machine-checked at genuine width 3. -/
def fxBunchedBimonoid_rifflePrimitiveAndSlidesShipped : Bool := true

/-! # =========================================================================================
    # B1 — THE NAIVE GENERAL `wideSwap` FOLD IS REFUTED (the decisive truth-probe)
    # =========================================================================================
-/

/-- A **naive general `wideSwap` candidate** — the tempting "slide one input strand past the grown output grid"
fold (`0`/`1` inputs give identity; `m+2` whiskers the recursive riffle under a front strand and post-composes one
`strandPastBlock` pass).  Truth-probed below to be WRONG: it produces the wrong strand count.  Kept only as the
refuted negative control that pins the general riffle assembly as genuinely unbuilt. -/
def bunchedBimonoidWideSwapNaiveCandidate : Nat → Nat → CellExpr bunchedBimonoidOmegaComputad 2
  | 0, _ => CellExpr.id bunchedBimonoidIdOne
  | 1, n => CellExpr.id (bunchedBimonoidAWordPow n)
  | m + 2, n =>
      CellExpr.vcomp
        (CellExpr.whiskerLeft bunchedBimonoidAdditiveGen (bunchedBimonoidWideSwapNaiveCandidate (m + 1) n))
        (bunchedBimonoidStrandPastBlock ((m + 1) * n))

/-! ## B1 truth-probe outputs (the naive fold disagrees with the genuine riffle) -/

#eval bunchedBimonoidEvalCell (bunchedBimonoidWideSwapNaiveCandidate 2 1)
#eval bunchedBimonoidEvalCell (bunchedBimonoidWideSwapNaiveCandidate 2 2)
#eval bunchedBimonoidEvalCell bunchedBimonoidMiddleSwap

/-- ★★★ **THE DECISIVE REFUTATION — the naive `wideSwap` fold is NOT the riffle at `(2,2)`.**  The genuine
`wideSwap(2,2)` is the `4 x 4` middle swap `bunchedBimonoidMiddleSwap` (`m*n = 4` strands, `[[1,0,0,0],[0,0,1,0],
[0,1,0,0],[0,0,0,1]]`), but the naive fold evaluates to a `3 x 3` cyclic shift — the strand counts already
disagree (`rows 3 != 4`).  So the general riffle word is genuinely more than the primitive + a naive fold; the
general `wideSwap(m,n)` assembly is the honest research residual, refuting the tempting shortcut. -/
theorem bunchedBimonoidWideSwapNaiveFoldRefutedAtTwoTwo :
    bunchedBimonoidEvalCell (bunchedBimonoidWideSwapNaiveCandidate 2 2)
      ≠ bunchedBimonoidEvalCell bunchedBimonoidMiddleSwap := by
  intro heq
  exact absurd (congrArg (fun matrix => matrix.rows) heq) (by decide)

/-! # =========================================================================================
    # B1 — THE HONEST RESIDUAL LEDGER (the general wideSwap word stays walled, no flip)
    # =========================================================================================
-/

/-- ★ **THE GENERAL `wideSwap(m,n)` RIFFLE WORD STAYS UNBUILT — no flip.**  `= false` records that the general
riffle word (the perfect-shuffle regrouping `i*n+j |-> j*m+i` of the `m*n` incidence strands) is NOT delivered:
the elementary letter `strandPastBlock` IS shipped (a genuine general def), but its assembly into the full grid
`wideSwap` is refuted for the naive fold (`bunchedBimonoidWideSwapNaiveFoldRefutedAtTwoTwo`) — the correct
assembly threads the `m` input passes through the growing output grid with the exact bracketing the perfect
shuffle demands, still the crux.  Byte-intact with the r6
`fxBunchedBimonoid_wideSwapGeneralRiffleWordUnbuilt` — the primitive advances the node without closing it. -/
def fxBunchedBimonoid_wideSwapGeneralAssemblyStillUnbuilt : Bool := false

/-- ★ **THE `(m,n)` CONV RECURSION STAYS UNBUILT — no flip.**  `= false` records that the full double induction
`muFold m ; deltaFan n ~ bialgebraNF(m,n)` is NOT shipped: the peel lemmas (`bunchedBimonoid{MuFold,DeltaFan}Peel`)
and the width-3 slides (`bunchedBimonoid{Mu,Delta}NaturalitySlideConv`) are the induction's atoms, and the base
`(2,2)` is the shipped `bunchedBimonoidWidthTwoCollisionConv`, but the full recursion is gated on the general
`wideSwap` word above.  Byte-intact with the r6 `fxBunchedBimonoid_wideCollisionConvRecursionUnbuilt`. -/
def fxBunchedBimonoid_wideCollisionRecursionStillUnbuilt : Bool := false

/-- ★★ **ESTABLISHED (B1) — the WP-PROP r7 riffle-naturality ledger (honest scoreboard).**  `= true` records the
r7 riffle advance: the genuine riffle PRIMITIVE `strandPastBlock` (cyclic-shift block braiding, probed at four
widths, definitionally the shipped `wideSymmetryFront`); the two collision peel lemmas (`rfl`); the two width-3
naturality slides (CONV over the star scope); and the DECISIVE truth-probe refuting the naive general `wideSwap`
fold (`bunchedBimonoidWideSwapNaiveFoldRefutedAtTwoTwo` — `3 x 3 != 4 x 4` at `(2,2)`).  The general `wideSwap`
word (`fxBunchedBimonoid_wideSwapGeneralAssemblyStillUnbuilt = false`) and the `(m,n)` conv recursion
(`fxBunchedBimonoid_wideCollisionRecursionStillUnbuilt = false`) stay walled byte-intact with their r6 markers.
NO star marker flips. -/
def fxBunchedBimonoid_riffleNaturalityRoundSevenLedgerShipped : Bool := true

end FX1Poly.Polygraph.Omega
