import FX1PolyAudit.DependencyAudit
import FX1Poly.Core.Metatheory.Reducibility.Core.DataReducibilityCoverage
import FX1Poly.Core.Metatheory.Reducibility.Candidates.DataTaitCandidate
import FX1Poly.Core.Metatheory.Reducibility.Candidates.FlatCodeTaitCandidate
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FlatCodeCanonicalForms
import FX1PolyAudit.MilestoneASpineValueLayer
import FX1PolyAudit.MilestoneAEliminatorLayerSpine
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimComputingCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicityTyped
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchGeneralBranchCanonicity
import FX1PolyAudit.MetatheoryParityLedger
import FX1Poly.Typed.Engine.Classifier.TypingContext
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeShape
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeConversion
import FX1Poly.Typed.Engine.Formation.SigmaCodeShape
import FX1Poly.Typed.Engine.Formation.ListCodeShape
import FX1Poly.Typed.Engine.Formation.ListFormationSmoke
import FX1Poly.Typed.Engine.Formation.OptionCodeShape
import FX1Poly.Typed.Engine.Formation.OptionCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.OptionFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationOptionFromTelescope
import FX1Poly.Typed.Engine.Formation.OptionFormationSmoke
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDesc
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescDecidable
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElim
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescValidity
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescClosedForms
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFormerTelescopeInversion
import FX1Poly.Typed.Engine.Formation.DataFormerInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescUniqueness
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPi
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaCoherence
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionGrown
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionComputes
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiWeakening
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiSubstitution
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiValidity
import FX1Poly.Typed.Metatheory.Universe.ConvCodeInjectivity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ConvBoolCodeRigidity
import FX1Poly.Typed.Engine.Formation.ConvFormationFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvCrossTableFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatCodeInjectivity
import FX1Poly.Typed.Engine.Formation.ConvDataCodeInjectivity
import FX1Poly.Typed.Metatheory.Universe.EmptyTypeCodeConvRigidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.EmptyTypeValueInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FormationCanonicalForms
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.PiTypeFunctionInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalForms
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafety
import FX1Poly.Typed.Engine.Formation.FormationTypeSafety
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsNonVacuity
import FX1Poly.Typed.Corpus.Smoke.GrownBetaRedexInAction
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgress
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownOpenCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafetyUnconditional
import FX1Poly.Typed.Engine.Formation.FormerStepInversionGeneric
import FX1Poly.Typed.Metatheory.SubjectReduction.SubjectReductionAtFormerGeneric
import FX1Poly.Typed.Engine.WfContext.WfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescValidity
import FX1Poly.Typed.Engine.WfContext.WfContextDescUniqueness
import FX1Poly.Typed.Engine.WfContext.WfContextDescPi
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiFromWfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiClassifierValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiFunctionComponentValidity
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionDescPi
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionMutual
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnv
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAt
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvTypeVariable
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprFT
import FX1Poly.Typed.Metatheory.Reducibility.Pi.AbstractionNonDependentUnderSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprReducibleLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermFundamentalLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInversionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprClosureLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermRenameLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1Poly.Typed.Metatheory.SimplyTyped.MilestoneA0SimplyTypedFloor
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1Poly.Tier0.Context.Instances.Renaming.FxRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecIsomorphism
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecPreimage
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTryTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecRMC
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecGlobalSections
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecSconingPreservation
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstVec
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstCategory
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWeakening
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstComprehension
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstSingleton
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstGlobalSections
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWitnessScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstConcreteScone
import FX1Poly.Tier0.Context.IsomorphismCategorical
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeRMC
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeGlobalSections
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1Poly.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1Poly.Core.Rewriting.Reduction.Head.RootStepDispatch
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnce
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1Poly.Core.Rewriting.Normalize.Normalize
import FX1Poly.Core.Rewriting.Normalize.NormalizeSteps
import FX1Poly.Core.Rewriting.Conversion.ConvDecisionSteps
import FX1Poly.Core.Rewriting.Normalize.NormalizeMeta
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsWeakHeadExpansion
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.BoolElimCanonicalComputation
import FX1Poly.Core.Eliminators.Bool.BoolElimClosedMembership
import FX1Poly.Core.Eliminators.Core.DataEliminatorMembershipSmoke
import FX1Poly.Core.Metatheory.Canonicity.SigmaProjectionCanonicalComputation
import FX1Poly.Core.Metatheory.Canonicity.IdentityEliminatorCanonicalComputation
import FX1Poly.Core.Eliminators.Identity.IdEliminatorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.OptionEitherMatchCanonicalComputation
import FX1Poly.Core.Eliminators.Match.MatchClosedMembership
import FX1Poly.Core.Eliminators.Sigma.SigmaProjectionClosedMembership
import FX1Poly.Core.Eliminators.Recursor.RecursorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.RecursiveEliminatorBaseComputation
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.DataCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.ModalCanonicityViaSconing
import FX1Poly.Core.Metatheory.Sconing.DataMetatheoryViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1Poly.Core.Metatheory.Sconing.ConsistencyViaSconing
import FX1Poly.Core.Eliminators.Core.DataEliminatorProgressViaSconing
import FX1Poly.Core.Eliminators.Recursor.RecursiveEliminatorProgressViaSconing
import FX1Poly.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.UnitCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EmptyCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingSubst
import FX1Poly.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1Poly.Core.Metatheory.Normalization.Core.WeakNormalization
import FX1Poly.Core.Rewriting.Normalize.NormalFormUnique
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevels
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllFormerChildren
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPiIntro
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Pi.NeutralFuelStability
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiTypeSaturationReassembly
import FX1Poly.Typed.Metatheory.Reducibility.Pi.StrongNormalizingAllLevelPiComponents
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescopePositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllCanonicalCandidate
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllVectorPremises
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllNonDependentBinders
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtUniformVectorPremises
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFundamentalVectorFromFormation
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFundamentalAtAllFromGenFormation
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClosedLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.TypeFundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LeveledContext
import FX1Poly.Typed.Corpus.Smoke.ClosedSNSmoke
import FX1Poly.Typed.Corpus.Smoke.UntypedOmegaNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.StepNonDeterministic
import FX1Poly.Typed.Metatheory.Normalizer.ConvValueDiscrimination
import FX1Poly.Typed.Corpus.Smoke.TypedLambdaDerivations
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleans
import FX1Poly.Typed.Corpus.Church.Core.TypedChurchNegation
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumerals
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIteration
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralDiscrimination
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralThree
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralTyping
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralInhabitants
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralComputeGeneral
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralAddition
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralMultiplication
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralSemiringLaws
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIsZero
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleanOperations
import FX1Poly.Typed.Corpus.Smoke.TypedFragmentAcyclicity
import FX1Poly.Typed.Corpus.Smoke.UnboundedGrowthNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointDivergence
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointCombinator
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryLogic
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryCompleteness
import FX1Poly.Typed.Corpus.Church.Combinators.SymbolicSCombinatorRule
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairs
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairsInjective
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSums
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsDisjoint
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsGeneral
import FX1Poly.Typed.Corpus.Church.Lists.ChurchLists
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListIsEmpty
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAny
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAll
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBooleanComplementLaws
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBoolXor
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListFirstOr
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSucc
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSuccApplies
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListLength
import FX1Poly.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1Poly.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1Poly.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseNoTop
import FX1Poly.Typed.Metatheory.Universe.TypedUniversePredicative
import FX1Poly.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1Poly.Typed.Corpus.Progress.ClosedNormalForm
import FX1Poly.Typed.Metatheory.Normalizer.ClosedNonConvertibility
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTyping
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiStronglyNormalizingFromFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVecTypeVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConsistency
import FX1Poly.Typed.Engine.Formation.HasTypeFormationNoLambdaApplication
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleSemanticRules
import FX1Poly.Typed.Engine.Formation.ListCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.ListFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberFormation
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeInversion
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeReach
import FX1Poly.Typed.Engine.RuleTables.FlatDescTelescope
import FX1Poly.Typed.Metatheory.Canonicity.Core.StandaloneEngineCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.CombinedBoolCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedBoolCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicitySyntacticRoute
import FX1Poly.Typed.Metatheory.Canonicity.Core.GrownRigidityCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedNatCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimValueCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.NatElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulArithmetic
import FX1Poly.Typed.Metatheory.Reducibility.Core.ClosedNumeralSubstInvariant
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulMul
import FX1Poly.Typed.Corpus.Faithfulness.ValueElimHostFold
import FX1Poly.Typed.Corpus.Faithfulness.RecursorHostFold
import FX1Poly.Typed.Metatheory.Canonicity.Core.ListElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.ListElimFaithfulLength
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicity
import FX1Poly.Typed.Corpus.Progress.GrownClosedNormalClassifierShape
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ClosedNormalEmptyConsistency
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ProductEitherCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.OptionCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ListCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.IdCanonicalForms
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiFormerMembership
import FX1Poly.Typed.Engine.Formation.FormerChildrenReducible
import FX1Poly.Typed.Metatheory.Reducibility.Telescope.TelescopeReducible
import FX1Poly.Typed.Metatheory.Universe.UniverseDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsInduction
import FX1Poly.Typed.Metatheory.Reducibility.Pi.ReducibleTypeAtAllLevelsPiNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsWhnfDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsPiDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsPiMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsHeadExpand
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsConv
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Strengthening.RouteAObstruction
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelDiagnosis
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelMeasure
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibility
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibilitySmoke
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPi
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedLevelIrrelevance
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseFormationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCanonicalMemberCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationFromExistence
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGeneralDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSingleLevelPi
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiAboveThreshold
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormerAtLevel
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleTypeLevelLift
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiArmDischarge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedApplicationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedConvMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberForwardClosed
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMemberBetaExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberWeakHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiElim
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalConv
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAmbientLevelBridge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrow
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedClosedMember
import FX1Poly.Typed.Metatheory.Denote.Telescope.DenoteKeyedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedUniformReducible
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMembershipIntro
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFormation
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFromChildMembers
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationSigmaArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedCumulativityObstruction
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibility
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedConvArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiElimArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiIntroArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedFormerEngine
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiDischarge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedAssemblyBridge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeProjection
import FX1Poly.Typed.Engine.Formation.FormerOutputLevelBounds
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedCodomainOpenSN
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDomainInhabitant
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationPiFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationSigmaFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationListFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedTelescopeConsSucc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGrownDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDesc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPi
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPiDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedGrownFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ClosedBoundedReducibleMember
import FX1Poly.Typed.Corpus.Smoke.ClosedStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedNeutralMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseInversion
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBindingTypeReducible
import FX1Poly.Typed.Engine.WfContext.ReducibleEnvOfWfContext
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizingUnconditional
import FX1Poly.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1Poly.Typed.Corpus.Smoke.OpenSNSmoke
import FX1Poly.Typed.Corpus.Progress.ContextValidityFails
import FX1Poly.Typed.Equality.UnitEta.UnitEtaJudgmentalEquality
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruenceGap
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruentEquality
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapse
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseIncompleteness
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeep
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseNeutralBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitNeutralSpineDetection
import FX1Poly.Typed.Equality.UnitEta.UnitSpineDetectionBoundary
import FX1Poly.Typed.Equality.UnitEta.TypeDirectedUnitReadback
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackArgumentBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackFormerChildBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackDeepSpineBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackAnnotationBoundary
import FX1Poly.Typed.Engine.Formation.FormationClassifierRigidity
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Pi.LiftedChildNormalizationFromClosure
import FX1Poly.Typed.Engine.RuleTables.TelescopeSubstitutedChildrenNormalization
import FX1PolyAudit.CascadeFreedomLedger
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyTargetSignature
import FX1PolyAudit.CandidateBridgeEditViability
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicityTargetSignature
import FX1Poly.Typed.Metatheory.Universe.NullaryFormerFormation
import FX1Poly.Typed.Metatheory.Universe.GrownUniverseFormationStrictness
import FX1Poly.Typed.Engine.Formation.GrownFormerFormationStrictness
import FX1Poly.Typed.Engine.Classifier.GrownTypingNotUnique
import FX1Poly.Typed.Engine.Classifier.GrownEngineHonesty
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.GrownUniverseConsistency
import FX1Poly.Typed.Engine.Classifier.GrownVariableHonesty
import FX1Poly.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiLamInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiAppInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVarInversion
import FX1Poly.Typed.Metatheory.ContextConversion.VarHeadedAppContextConversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiBetaSR
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiCongruence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerCongruence
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionConditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimReduction
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionValidityReduction
import FX1Poly.Typed.Corpus.Progress.GrownMutualMetatheoryFromPiValidity
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimEquivalence
import FX1Poly.Typed.Engine.HasTypeDescPi.ContextConversion.HasTypeDescPiContextStepConversion
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionUnconditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionFlexibleUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormationFragment
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormerStep
import FX1Poly.Typed.Metatheory.ContextConversion.GenFormerValidityContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPiValidityModelNeutral
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveled
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransport
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransportUnderWf
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledCompleteness
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValid
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRename
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValidLookup
import FX1Poly.Typed.Metatheory.ContextConversion.PiElimClassifierConvResidual
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiFormerInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiDataHeadUntyped
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiRootGeneric
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedUniverseBoundedCumulativity
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedClosedTypeCodeSN
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiMemberSN
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrowMemberSN
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCodomainMemberWiring
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelSpike
import FX1PolyAudit.SNStrategy
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.LogRelSpec
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LevelingBridge
import FX1Poly.Typed.Metatheory.Canonicity.Core.ConsistentStratification
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingLevelFlexible
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingRefinedMotive
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingConvArm
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingPiArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingFormerArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingVariableLevelPinned
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalReduction
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalAssembly
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.SimplyTyped.HigherOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiOverNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiNeutralCodomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentlyTypedNeutralDomainFragment
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedSubsumption
import FX1Poly.Typed.Metatheory.Universe.UniverseCumulativity
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermReducibility
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiTypingNonUnique
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckOfInferred
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVariableInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiUniverseCodeInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckUniverseCode
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplicationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckFormation
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationCodomainReTyping
import FX1Poly.Typed.Engine.RuleTables.IntroRuleDesc
import FX1Poly.Typed.Engine.RuleTables.ElimRuleDesc
import FX1Poly.Typed.Engine.RuleTables.GenElimIotaComputation
import FX1Poly.Typed.Engine.Classifier.TypingRoleClassifier
import FX1Poly.Typed.Engine.Classifier.TypingRoleEngineBridge
import FX1Poly.Typed.Engine.Classifier.TypingRoleCoverage
import FX1Poly.Typed.Engine.Classifier.UntypableHeadDecision
import FX1Poly.Typed.Engine.Classifier.TypingHeadKindClassifier
import FX1Poly.Typed.Engine.Classifier.TypedBySomeEngine
import FX1Poly.Typed.Engine.Classifier.GeneratorSemanticTier
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyOverview
import FX1Poly.Typed.Engine.Classifier.StaticTypingSoundness
import FX1Poly.Typed.Engine.Classifier.SemanticTierSoundness
import FX1Poly.Typed.Engine.Classifier.ClassifierRefinement
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyLedger
import FX1Poly.Typed.Metatheory.Normalizer.CertifiedWordReductionTermination
import FX1Poly.Typed.Metatheory.Normalizer.CertifiedWordReductionConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerStepDomainFormationCodomain
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionFormerArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionInlineArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionConvOfFormationArms
import FX1Poly.Typed.Metatheory.SubjectReduction.ConsistencyConditionalOnSubjectReduction
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencySyntactic
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyOfPiElimArm
import FX1Poly.Typed.Metatheory.ContextConversion.PiElimUpToClassifierConv
import FX1Poly.Typed.Engine.Classifier.ClassifierRespectsConvRefuted
import FX1Poly.Typed.Dimensions.AxisObligation.TypedCertificationStackingRefuted
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencyUnconditional
import FX1Poly.Typed.Engine.Formation.FormationNormalSmoke
import FX1Poly.Typed.Engine.Formation.BoolTypeCodeSubstrate
import FX1Poly.Typed.Engine.Formation.NatTypeCodeSubstrate
import FX1Poly.Typed.Corpus.Progress.GrownNoTypeInType
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescRigidity
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidable
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1PolyAudit.KnownUnsoundnessCorpus
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationAcyclic
import FX1Poly.Dimensions.Security.SecurityNoninterferenceGeneral
import FX1Poly.Dimensions.Graded.GradedApplicationFlow
import FX1PolyAudit.MetatheoryFuzz
import FX1PolyAudit.FuzzCorpusConvertibility
import FX1PolyAudit.FuzzCorpusNormalizes
import FX1PolyAudit.LambdaValueFuzzFamily
import FX1PolyAudit.MechanizedProofCrossReference
import FX1PolyAudit.FormalReviewGate
import FX1PolyAudit.SelfVerifiedMetatheory
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengthening
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheck
import FX1Poly.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1Poly.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiImageComponents
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiRenameImage
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionContext
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiIntro
import FX1Poly.Typed.Engine.Formation.FormationPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.GrownPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimCore
import FX1Poly.Typed.Corpus.Smoke.GrownWfOpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimDispatcher
import FX1Poly.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1Poly.Typed.Metatheory.Strengthening.GuardedPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PlateauPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.NeutralReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionLamClassifierResidual
import FX1Poly.Typed.Metatheory.Strengthening.FlagCoherentReflectionCondition
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.NeutralClassifierUnique
import FX1Poly.Typed.Metatheory.Universe.NormalAppNeutral
import FX1Poly.Typed.Engine.RuleTables.TelescopeUniverseDeterminism
import FX1Poly.Typed.Engine.RuleTables.GenericFormerTelescopeInversion
import FX1Poly.Typed.Metatheory.Universe.NormalUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.ConvUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Strengthening.RenameAlongFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.PinSelectsCallerPair
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.LamReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherentMaster

/-! # FX1PolyAudit/AuditTypedCheckerInference — typed-layer zero-axiom gates: the typecheckers, deciders, NbE normalizers, and complexity witnesses
   (semantic shard of the typed audit; gates classified by declaration topic, appended
   clusters kept together; full import block retained for namespace-sweep coverage) -/

-- DECIDABILITY (P11 0-FN) of the description engine.  `decidableOfWellFormed` is a native
-- formation decision procedure.  `Conv.decidableOfHasTypeDesc` decides Conv by SN: each classifier
-- is SN by the native `HasTypeDesc.classifierStronglyNormalizing`, fed to the parameter-free
-- `Conv.decidableOfStronglyNormalizing`.
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.decidableOfWellFormed
#assert_no_axioms FX1Poly.Typed.Conv.decidableOfHasTypeDesc
-- CLOSED PROGRESS PER TYPE (GrownClosedProgressByClassifier.lean): the missing "closed + per-classifier +
-- progress" cell, read at the classifier. closedFunctionStepsOrIsLambda = a closed grown-typed term of Π type
-- STEPS or IS a λ (body extracted) — the operational form the function position of an application consumes, the
-- dependent analogue of the graded closedWellTypedProgress sharpened to the exact λ shape. closedTypeStepsOrIsFormer
-- = a closed grown-typed TYPE (universe classifier) STEPS or its head is a type FORMER (Π/Σ/universe/list/option
-- code), never a stuck λ. Both UNCONDITIONAL: the classifier is read only at the already-normal subject (via
-- closedNormalFunctionIsLambda / closedNormalTypeIsFormer), so no reduction step is typed — no SR, no GrownCtxConv-5 #842,
-- no §5; the non-normal case only asserts a step EXISTS. The per-classifier progress refinements of closedProgress.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedFunctionStepsOrIsLambda
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedTypeStepsOrIsFormer
-- EVALUATION DETERMINISM (GrownTypeSafety.lean): closedHasUniqueNormalForm = UNCONDITIONAL — a closed grown-typed
-- term has a UNIQUE normal form (OB-5 SN ⤳ exists_unique_normalForm_of_isStronglyNormalizing: existence by weak
-- normalization, uniqueness by raw confluence #420; NO SR), so evaluation is a well-defined single-valued total
-- function. closedTypeSafetyUniqueOfSubjectReductionStar = CONDITIONAL — that unique normal form is moreover a
-- canonical VALUE (closedNormalSubjectHead at the SR-typed normal form): the full "evaluates to THE canonical
-- value" statement, progress + preservation + confluence combined.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedHasUniqueNormalForm
-- OPEN PROGRESS PER TYPE (GrownOpenProgressByClassifier.lean): the eighth and last cell of the grown progress/
-- canonical-forms matrix {closed,open}×{general,per-classifier}×{canonical-forms,progress}. openFunctionStepsOrIsLambdaOrNeutral
-- = a grown-typed term of Π type in ANY WfContext STEPS or IS a λ or is Core.IsNeutral; openTypeStepsOrIsFormerOrNeutral
-- = a grown-typed TYPE (universe classifier) STEPS or has a type-former head or is Core.IsNeutral. The open
-- generalizations of the closed{Function,Type}Steps… twin (admitting the neutral leaf variables introduce). The
-- 3-way disjunction (steps ∨ canonical-at-classifier ∨ neutral) IS the type-directed η-long readback case split
-- (TY-CONV-quote / η-M15). UNCONDITIONAL: the classifier is read only at the already-normal subject (via the open
-- per-classifier canonical-forms lemmas), so no reduction step is typed — no SR, no GrownCtxConv-5 #842, no §5.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.openFunctionStepsOrIsLambdaOrNeutral
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.openTypeStepsOrIsFormerOrNeutral
-- OPEN TYPE SAFETY + DETERMINISM (GrownOpenTypeSafety.lean, five-layer-defense L4 §27.3): the open analogues of the
-- three GrownTypeSafety statements, resting on OB-5 open SN (stronglyNormalizingOfWfContext, any WfContext) + open
-- progress (openNormalSubjectCanonicalOrNeutral), with the neutral disjunct. openHasUniqueNormalForm = OPEN
-- EVALUATION DETERMINISM (unconditional — OB-5 SN any context ⤳ exists_unique_normalForm; NO SR, NO closedness):
-- evaluation of an open grown-typed term is a well-defined single-valued total function.
-- openTypeSafetyOfSubjectReductionStar / openTypeSafetyUniqueOfSubjectReductionStar = OPEN TYPE SAFETY (conditional
-- on SR-along-↝*): every open grown-typed term evaluates to a (unique) canonical-or-neutral normal form. Completes
-- the open metatheory triple (progress + canonical forms + safety). #672-independent (OB-5 is unconditional open SN).
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.openHasUniqueNormalForm
#assert_no_axioms FX1Poly.Typed.discardedBody_isNormalForm
#assert_no_axioms FX1Poly.Typed.discardingApplicationOnOmega_argumentSelfLoop
-- Conv on the NORMAL FRAGMENT is DECIDABLE and the decider EXECUTES (ConvValueDiscrimination, constructive
-- companion to the non-degeneracy facts): convDecidableOfBothNoStep packages the ConvNormalForm seed as an
-- actual Decidable (decidable_of_iff (left=right) ∘ Conv.iff_eq_of_noStep, over the propext-free DecidableEq
-- RawTerm — no normalizer). The convDecider_* equations are `@decide … = true/false` by rfl: the decider RUNS
-- and computes the right boolean (Conv boolTrue boolTrue → true; boolTrue/boolFalse, boolTrue/unit → false). No
-- native_decide; the evaluations reduce over the structural DecidableEq.
#assert_no_axioms FX1Poly.Typed.convDecidableOfBothNoStep
#assert_no_axioms FX1Poly.Typed.convDecider_boolTrueValue_self_isTrue
#assert_no_axioms FX1Poly.Typed.convDecider_boolTrueValue_boolFalseValue_isFalse
#assert_no_axioms FX1Poly.Typed.lamCell_isStepNormalForm
-- FIRST LANE CROSSING: the FT-derived SN results discharge the SN-fragment conversion decider
-- (Conv.decidableOfStronglyNormalizing — normalize each, compare NF), yielding UNCONDITIONAL decidable Conv
-- for concrete closed terms (β-redex vs reduct, β-redex vs identity). The general bridge is conditional on the
-- FT conclusion (becomes unconditional with the recursor). betaRedexConvertsToReduct is the non-vacuity witness
-- (the redex really converts to its reduct). Concrete realization of raw decidable Conv (#267 / #503).
#assert_no_axioms FX1Poly.Typed.closedConvDecidableFromLevelIndexed
#assert_no_axioms FX1Poly.Typed.decidableConvBetaRedexAndReduct
#assert_no_axioms FX1Poly.Typed.decidableConvBetaRedexAndIdentity
#assert_no_axioms FX1Poly.Typed.closedConv_iff_normalForm_eq
#assert_no_axioms FX1Poly.Typed.closedBetaRedexNormalForm_eq
#assert_no_axioms FX1Poly.Typed.closedIdentityNormalForm_eq
-- SN-046 typed Newman bridge + general typed decidable Conv, CONDITIONAL on the one typed-SN interface
-- (HasTypeDescPiConditionalConfluence.lean). HasTypeDescPiStronglyNormalizes = the named typed-SN hypothesis
-- (= SN-043, gate #672). subjectConfluenceOfStronglyNormalizes = Newman confined to the SN fragment
-- (StepStar.confluence_of_localJoin_and_accessible on the hypothesis-supplied SN witness; raw global confluence
-- false-by-Omega is never used). decidableOfHasTypeDescPiStronglyNormalizes = general typed Conv decidable via
-- the parameter-free SN-fragment decider (Conv.decidableOfStronglyNormalizing), subsuming decidableOfIsType
-- (TYPES-only) to ARBITRARY well-typed terms. All zero-axiom (Acc-recursion + instDecidableEqRawTerm). Once #672
-- lands and feeds HasTypeDescPi.subjectStronglyNormalizingFromFormation, the hypothesis discharges and these go
-- unconditional in one step.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiStronglyNormalizes
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.subjectConfluenceOfStronglyNormalizes
#assert_no_axioms FX1Poly.Typed.Conv.decidableOfHasTypeDescPiStronglyNormalizes
-- SN-046/NbE-soundness: Conv.iff_normalize_eq_of_hasTypeDescPiStronglyNormalizes = the SEMANTIC characterization
-- for the typed fragment (Conv ↔ normalize-equality), the Path-A NbE headline (Conv ↔ quote∘eval eq) modulo the
-- one typed-SN hypothesis. The decidability theorem above is decidable_of_iff over this. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.Conv.iff_normalize_eq_of_hasTypeDescPiStronglyNormalizes
-- WEAK NORMALIZATION leg of the conditional package: subjectWeaklyNormalizesOfStronglyNormalizes — typed-SN ⟹
-- every well-typed subject reaches a normal form (RawTerm.normalize on the hypothesis-supplied SN witness;
-- normalize_reducesTo + normalize_isStepNormalForm). Completes typed-SN ⟹ {confluence, decidable Conv,
-- Conv=normalize-eq, WN}. Zero-axiom (Acc-recursion).
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.subjectWeaklyNormalizesOfStronglyNormalizes
-- CANONICAL-FORMS HEADLINE (conditional on typed-SN): uniqueNormalFormOfStronglyNormalizes — every well-typed
-- subject has a UNIQUE normal form. Existence = weak normalization; uniqueness = confluence + normal-form
-- rigidity (two NFs reached from one subject join, and a NF reached by a chain IS the chain start, so the join
-- apex collapses both onto one term). The typed fragment is a normalizing rewriting system with a unique
-- canonical representative. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.uniqueNormalFormOfStronglyNormalizes
-- RELEASE-READINESS CONSOLIDATION (#664, Thrust-C de-risking): convergencePackageModuloStronglyNormalizes bundles
-- the THREE propositional normalization consequences of the single typed-SN hypothesis into one auditable
-- statement: (1) weak normalization, (2) per-subject confluence (typed Newman bridge SN-046), (3) unique normal
-- form. Termination (the hypothesis) + WN + confluence = convergence; conjunct 3 is the headline. NOT new
-- metatheory — each conjunct is the corresponding shipped conditional theorem applied to the one hypothesis; the
-- value is the single discharge point. Decidable Conv + Conv=normalize-eq are the companion gated results (their
-- conclusions thread the SN witness into normalize, so they stay standalone in HasTypeDescPiConditionalConfluence).
-- Unconditional in one step once #672 lands. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.convergencePackageModuloStronglyNormalizes

/-! ### PER-VARIABLE-LEVEL reducible environment (the Kripke refinement for the dependent fundamental
    theorem).  `ReducibleEnvAt`'s single global level cannot serve a context that mixes variables at
    different typing-tower rungs (each rung sits one fuel higher via `tarskiDecode`, and upward
    level-cumulativity is false).  `ReducibleEnvVec` indexes each variable by its OWN tower level via a
    `Fin scope → Nat` vector; `levelCons` is the propext-free fresh-level cons. -/
-- SN-008 VERIFIED 2026-06-02 (no rebuild): ReducibleEnvVec IS the per-variable-level reducible closing
-- environment — `def ReducibleEnvVec (levels : Fin scope → Nat) context substitution := ∀ index,
-- IsReducibleMemberAt (levels index) (subst substitution (context.lookup index)) (substitution index)` — its
-- per-variable level is the ABSTRACT (Fin scope → Nat) vector (fuel/depth, NOT denote(LevelExpr)); empty/cons/
-- lookupReducible are proved + gated below, and the all-levels Kripke variant ReducibleEnvAtAllLevels (+9 members)
-- is gated above (lines ~943-956). A denote-keyed env is the INSTANTIATION levels := fun i => denote(classifierOf i)
-- env — NO new relation (the SN-002 "instantiation, not rebuild" finding) — so NO variant is built: it would
-- duplicate the shipped env (task discipline forbids duplication).
#assert_no_axioms FX1Poly.Typed.levelCons
#assert_no_axioms FX1Poly.Typed.konstAppliedToVariableNormalForm
#assert_no_axioms FX1Poly.Typed.konstAppliedToVariable_normalizes
#assert_no_axioms FX1Poly.Typed.konstNormalForms_congruentlyEqual

/-! ### TypedNbeNormalizer — ★ #480: the typed NbE EVAL half + the eval∘quote composition

The typed normalizer assembled from its two halves.  EVAL (`evalNormalForm`, #480): β/ι
normalization of well-typed OPEN terms — `RawTerm.normalize` with the open-SN witness
(`stronglyNormalizingOfWfContextDesc`) as the termination certificate; total, fuel-free; the
output reduces from the input, is structurally normal, converts to the input, and — the
headline — is TYPED AT THE SAME CLASSIFIER (`evalNormalForm_typed` via the unconditional master
`subjectReductionStar`).  QUOTE: the #481 type-directed η-long readback.  The composition
`nbeNormalForm = quote ∘ eval` carries the composed soundness (`nbeNormalForm_congruent`:
`ofConvTable` over `ConvTableBetaEtaRoot.ofConv` along the normalization chain, then the readback
soundness on the typed eval output) and the #364-shaped semi-decision
(`DefEqUnitEtaCong.ofNbeEqual`).  EACH HALF IS
LOAD-BEARING: eval contracts the typed β-redex `(λx.x)(Type@e)` (the pair with its reduct is
decided — `identityApplicationPair_decidedByNbe`) while quote alone provably fixes the
unevaluated redex (`readbackAlone_keepsBetaRedex`); conversely the η/unit pairs of the #481
modules are β-normal and decided only by quote.  Zero-axiom. -/

#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.evalNormalForm
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.evalNormalForm_reducesTo
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.evalNormalForm_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.evalNormalForm_conv
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.evalNormalForm_typed
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.nbeNormalForm
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.nbeNormalForm_congruent
#assert_no_axioms FX1Poly.Typed.universeCode_evalNormalForm_eq
#assert_no_axioms FX1Poly.Typed.identityApplication_evalNormalForm_eq
#assert_no_axioms FX1Poly.Typed.identityApplicationPair_decidedByNbe

/-! ### TypedNbeConvDecision — ★ #364: the typed NbE conversion check, sound + complete-at-unit

The normalize-and-compare check over the composed typed NbE normalizer: `checkNbeEqual`
(executable `decide` over the kernel's `DecidableEq RawTerm`), SOUND unconditionally
(`checkNbeEqual_sound` — a passing check certifies the full typed judgmental equality
`DefEqUnitEtaCong`), and sound AND complete at the UNIT classifier: the readback is CONSTANT
at `unitTypeCell` on a SYMBOLIC subject (`readbackAtClassifier_constantAtUnit`, `rfl`), so
every unit-typed NbE form at positive fuel is `unitCell`
(`nbeNormalForm_constantAtUnit`, still `rfl` through eval), any two unit-typed subjects check
equal (`nbeComplete_atUnit`), and `checkNbeEqual = true ↔ DefEqUnitEtaCong` there
(`checkNbeEqual_iff_atUnit` — the first total 0/0 cell of the NbE decider;
`DefEqUnitEtaCong.decidableAtUnit` realizes the `Decidable`).  Honest ledger: β/ι completeness
is the shipped `conv_iff_normalForm_eq`; η/congruent completeness holds on the ten #481
boundary verdicts and is UNPROVEN jointly (O-NORM).  Zero-axiom. -/

#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.checkNbeEqual
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.checkNbeEqual_sound
-- FIRST CONCRETE DATA CANDIDATE — bool (SN-063 data core), unconditional + zero-axiom: boolIsValue := the
-- true/false constructor cells; boolIsValue values are structural normal forms (isStepNormalFormBool computes
-- to true); the candidate is isReducibilityCandidateOfValuesNormal at boolIsValue (CR1+CR2+CR3, neutral half
-- via IsNeutral.closedUnderStep); both canonical inhabitants are members (Acc.intro over no_step_from_bool*).
#assert_no_axioms FX1Poly.Core.boolIsValue_impliesStepNormalForm
-- RECURSIVE data candidate — Nat (SN-060/062): IsNatValue is the inductive numeral predicate; numerals are
-- structural normal forms by induction (a natSucc cell is normal iff its predecessor is); the candidate is
-- isReducibilityCandidateOfValuesNormal at IsNatValue; every numeral is a member (memberOfValue); a closed
-- member reduces to a numeral (closedReducesToValue). Unconditional + #672-free.
#assert_no_axioms FX1Poly.Core.isNatValue_impliesStepNormalForm
-- BINARY data candidate — Σ pairs (SN-057/059): isPairValue := a pairCell with both components normal; a
-- pair of normals is a structural normal form (the two-child spine recursion); the candidate is
-- isReducibilityCandidateOfValuesNormal at isPairValue; a normal pair is a member (memberOfValue); a closed
-- member reduces to a pair (closedReducesToValue). Unconditional + #672-free.
#assert_no_axioms FX1Poly.Core.isPairValue_impliesStepNormalForm
-- MODAL layer data candidate — modIntro (SN-073 data core): the modal box is a single unary constructor
-- (option-some shape); isModIntroValue := modIntro of a normal payload; value-normality is the one-child
-- spine; candidate via isReducibilityCandidateOfValuesNormal; a normal box is a member (memberOfValue); a
-- closed member reduces to a modIntro. Over β+ι Step (raw modal η is a separate relation). #672-free.
#assert_no_axioms FX1Poly.Core.isModIntroValue_impliesStepNormalForm
-- RICHEST data candidate — List (SN-064): IsListValue inductive combines nullary nil + binary-recursive cons
-- (head normal like pair, tail recursive like Nat); list values are normal forms by induction; the candidate
-- is isReducibilityCandidateOfValuesNormal at IsListValue; every list value is a member (memberOfValue); a
-- closed member reduces to a list constructor (closedReducesToValue). Unconditional + #672-free.
#assert_no_axioms FX1Poly.Core.isListValue_impliesStepNormalForm
-- OPTION data candidate (SN-065): isOptionValue := none | some payload (payload normal) — nullary + unary,
-- no recursion; option values are normal forms; the candidate is isReducibilityCandidateOfValuesNormal at
-- isOptionValue; every option value is a member (memberOfValue); a closed member reduces to none/some.
#assert_no_axioms FX1Poly.Core.isOptionValue_impliesStepNormalForm
-- EITHER (sum) data candidate (SN-066): isEitherValue := inl payload | inr payload (payload normal) — two
-- unary tagged arms; either values are normal forms; the candidate is isReducibilityCandidateOfValuesNormal
-- at isEitherValue; every either value is a member (memberOfValue); a closed member reduces to inl/inr.
-- Completes the tagged-union extraction family (option + either).
#assert_no_axioms FX1Poly.Core.isEitherValue_impliesStepNormalForm
-- IDENTITY refl data candidate (SN-067): isReflValue := refl witness (witness normal) — the single unary
-- introduction of the identity type; refl values are normal forms; the candidate is
-- isReducibilityCandidateOfValuesNormal at isReflValue; every refl value is a member (memberOfValue); a closed
-- member reduces to a refl. Completes the data-introduction extraction family.
#assert_no_axioms FX1Poly.Core.isReflValue_impliesStepNormalForm
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.normalFormUniqueUnderSubst
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.normalFormUniqueClosed

-- INHABITATION CORPUS for the simply-typed term FT (the fundamental theorem is non-vacuous): concrete
-- `SimplyTypedTermLF` derivations of the polymorphic identity at a universe base type and at an arrow type,
-- with their strong normalization as fundamental-theorem corollaries.  Simply-typed analogue of TY-honesty.
#assert_no_axioms FX1Poly.Typed.identityIsSimplyTyped
#assert_no_axioms FX1Poly.Core.RawTerm.reduceOnce_eq_none_iff_isStepNormalForm
#assert_no_axioms FX1Poly.Core.RawTerm.not_isStepNormalForm_imp_reduceOnce_isSome

-- THE NORMALIZER FUNCTION + its correctness, and the parameter-free SN-fragment decidable Conv it unlocks.
-- normalize iterates reduceOnce along Acc StepSuccessor (Acc.rec — the descent shrinks the accessibility
-- proof, not the term); normalize_reducesTo / normalize_isStepNormalForm are its soundness/normality.
-- Conv.decidableOfStronglyNormalizing: two SN terms → Decidable (Conv ..), no NF witnesses / Normalizer /
-- global confluence.  The culmination of the WN grind (#503) — raw redex detection to a real decider.
#assert_no_axioms FX1Poly.Core.RawTerm.normalize
#assert_no_axioms FX1Poly.Core.RawTerm.normalize_unfold
#assert_no_axioms FX1Poly.Core.RawTerm.normalize_reducesTo
#assert_no_axioms FX1Poly.Core.RawTerm.normalize_isStepNormalForm

-- NORMALIZER METATHEORY: fixed-point-at-NF, idempotence, term↔NF conversion, and the headline
-- normalize_eq_iff_conv (two terms convert iff their normal forms coincide — the normal form is a complete
-- conversion invariant on the SN fragment, the explicit biconditional behind decidableOfStronglyNormalizing).
#assert_no_axioms FX1Poly.Core.RawTerm.normalize_eq_self_of_isStepNormalForm
#assert_no_axioms FX1Poly.Core.RawTerm.normalize_idempotent
#assert_no_axioms FX1Poly.Core.RawTerm.conv_normalize
#assert_no_axioms FX1Poly.Core.RawTerm.normalize_eq_iff_conv

-- DECIDABLE CONV ON THE SIMPLY-TYPED FRAGMENT WITH SN DISCHARGED.  Composing the normalizer's
-- decidableOfStronglyNormalizing with the simply-typed fundamental theorem's stronglyNormalizing* — typing
-- alone decides convertibility (no SN hypothesis), joining the FT (#502) and WN-normalizer (#503) lines.
#assert_no_axioms FX1Poly.Typed.Conv.decidableOfSimplyTypedUnderSubst
#assert_no_axioms FX1Poly.Typed.Conv.decidableOfSimplyTypedClosed
#assert_no_axioms FX1Poly.Typed.Conv.decidableOfSimplyTypedBareClosed
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.normalForm
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.conv_normalForm
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.normalForm_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.normalForm_eq_self_of_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.conv_iff_normalForm_eq

-- REDUCER SMOKE CORPUS — the WN-grind reducer COMPUTES on concrete closed terms (each `by rfl`, no decide).
-- Demonstrates non-vacuity of reduceOnce / fireTableRedexOver / isStepNormalFormBool: β fires with the right
-- reduct (identity + binder-ignoring bodies), the reducer halts on normal forms, a two-step normalization
-- trace reaches `unit`, the detector agrees, and the table root engine fires directly at the legacy table.
-- The 8 theorem gates transitively certify the 5 fixture defs are axiom-free too.
#assert_no_axioms FX1Poly.Typed.reduceOnce_betaIdentity_fires
#assert_no_axioms FX1Poly.Typed.reduceOnce_betaConstant_fires
#assert_no_axioms FX1Poly.Typed.reduceOnce_identityLambda_halts
#assert_no_axioms FX1Poly.Typed.isStepNormalFormBool_betaRedex_false
#assert_no_axioms FX1Poly.Typed.isStepNormalFormBool_identityLambda_true
#assert_no_axioms FX1Poly.Typed.fireTableRedex_betaIdentity_fires
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.normalForm_typed

-- CANONICITY (PROGRESS) — the classic STLC capstone, completing the simply-typed metatheory.  Closed normal
-- forms are lambdas: a LnNeutral term (var-headed app spine) is impossible at scope 0, the canonicalSplit
-- inducts on typing (β-redex case killed by Step.beta + blocks_step, child-normality via cong), and
-- normalFormIsLambda composes it with type-preserving normalization — every closed simply-typed term
-- normalizes to a lambda.
#assert_no_axioms FX1Poly.Typed.lnNeutral_scopeZero_absurd
#assert_no_axioms FX1Poly.Typed.isStepNormalForm_appCell_function
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.normalFormIsLambda

-- INHABITATION / CONSISTENCY — the final theorem of the simply-typed metatheory.  Every closed simply-typed
-- term has an arrow type (canonicity says its NF is a lambda, type-preserving normalization keeps the type,
-- lambda inversion makes the type an arrow); hence universe codes are uninhabited by closed terms (arrow vs
-- universe-code head generators differ) — the fragment's consistency.
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.closedTermHasArrowType
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.noClosedTermAtUniverseCode
#assert_no_axioms FX1Poly.Typed.SimplyTypedClosedTerm.decidableConvertsTo

-- The PRODUCTIVE MIRROR of `isStepNormalForm_blocks_step`: a non-normal term genuinely reduces, with the
-- reduct exhibited.  Mutual term + child-spine halves.  Combines the root-redex dispatch (root conjunct) with
-- a structural recursion into the child spine (`Step.cong` / `StepChildren.here` / `StepChildren.there`).
-- The step-extraction the `Acc StepSuccessor` weak-normalization descent calls at every non-normal node.
#assert_no_axioms FX1Poly.Core.exists_step_of_not_isStepNormalForm
#assert_no_axioms FX1Poly.Core.exists_stepChildren_of_not_areStepNormalForms

-- NORMAL-FORM UNIQUENESS: confluence forces two normal reducts of one SN term to coincide, so the SN
-- fragment has a UNIQUE normal form (existence from WN + this uniqueness clause).  The "the normal form"
-- handle a normalizer function realizes and SN-fragment decidable Conv (#267) rests on.
#assert_no_axioms FX1Poly.Core.normalForm_unique
-- General-reducibility NORMALIZATION sconing extraction (SN-094 / SN-110 at the logical-predicate level,
-- ReducibilityNormalizationViaSconing.lean). reducibilityScone (SconingWitness) extracts strong normalization;
-- DataMetatheoryViaSconing (#696) bundles SN + reduces-to-value for the DATA axis. Neither delivers the genuine
-- WEAK-NORMALIZATION metatheorem (term reaches a structural normal form). This file adds it at the GENERAL
-- reducibility-candidate level (any IsReducibilityCandidate, any scope): the SECOND concrete sconing witness,
-- whose extraction composes CR1 (candidate => SN) with exists_normalForm_of_isStronglyNormalizing (SN => reaches
-- NF, WeakNormalization.lean). reachesStepNormalForm: the WN predicate. reducibilityNormalizationScone: the
-- normalization sconing witness. normalizationViaSconing: well-typed => reaches NF. ReducibilityMetatheory +
-- reducibilityMetatheoryViaSconing: ONE fundamental => BOTH strong + weak normalization, the general-reducibility
-- "sconing is enough" demonstration (SN-110), strictly beyond DataMetatheory's SN-only. Parametric in the
-- fundamental obligation (honest: gated on SN-043 for the full kernel, discharged on proven fragments); does NOT
-- flip the Tier-0 categorical NormalizationExtraction ledger flag. All zero-axiom.
#assert_no_axioms FX1Poly.Core.reachesStepNormalForm
-- Decidable conversion from a reducibility candidate + the full-metatheory capstone (the decidability FX wants
-- most, ReducibilityConversionViaSconing.lean). ReducibilityNormalizationViaSconing extracts SN + weak
-- normalization from a candidate; DECIDABLE CONVERSION (the Milestone-A core) is the next free extraction: CR1
-- makes both sides SN, and Conv.decidableOfStronglyNormalizing (Normalize.lean) decides Conv by normalizing each
-- side and comparing -- no global confluence. conversionDecidableViaSconing: the decidability extraction.
-- conversionIffNormalizeEqViaSconing: the semantic NbE characterization (Conv = normalize-equality).
-- ReducibilityFullMetatheory + reducibilityFullMetatheoryViaSconing: ONE fundamental => SN + weak normalization
-- + decidable conversion, the general-reducibility decidable-metatheory capstone (Type-valued: conversion is
-- decision DATA). Parametric in the fundamental (gated on SN-043 for the full kernel, discharged on fragments);
-- NOT the BKS parametricity leg (that needs a binary relation). All zero-axiom.
#assert_no_axioms FX1Poly.Core.conversionDecidableViaSconing
#assert_no_axioms FX1Poly.Core.conversionIffNormalizeEqViaSconing
#assert_no_axioms FX1Poly.Typed.simplyTypedReachesNormalForm
#assert_no_axioms FX1Poly.Typed.simplyTypedConversionDecidableViaSconing
-- First concrete RawCategory instance for FX (FxRenamingCategory.lean, toward SN-083/084 fxBaseRMC). The Tier-0
-- categorical interfaces (RawCategory / RepresentableMapCategory / GlobalSections / SconingObject) are
-- obligation-shape interfaces; fxRenamingCategory builds the first concrete FX inhabitant: the
-- renaming (thinning) category, objects = scopes (Nat), morphisms = positional renamings (RawRenaming = Fin
-- source -> Fin target). All three category laws hold definitionally (function-comp associativity + definitional
-- eta), so it is a genuine complete category, not a stub. HONEST SCOPE: this is the renaming/thinning base (the
-- variable-reindexing category NbE presheaf models live over), the underlying-category first piece of fxBaseRMC;
-- the full RepresentableMapCategory additionally needs term substitutions as morphisms + a representable-map
-- class with the 3 CwR axioms (pullback-universal-property in particular), deferred. fxRenamingCategory_identity
-- _eq / _compose_eq: the categorical identity/composition ARE the renaming identity/composition (defeq samples).
-- All zero-axiom (no funext -- renaming function-equality would pull Quot.sound).
#assert_no_axioms FX1Poly.Tier0.fxRenamingCategory
#assert_no_axioms FX1Poly.Tier0.fxRenamingCategory_identity_eq
#assert_no_axioms FX1Poly.Tier0.fxRenamingCategory_compose_eq

-- SN-051 / SN-046-uncond (WfContextDecidableConv.lean): the open-SN-043 harvest, routed through the
-- HasTypeDesc-defined WfContextDesc via the bridge-free stronglyNormalizingOfWfContextDesc. Two well-typed
-- subjects in a well-formed context have DECIDABLE Conv (no typed-SN hypothesis — each OB-5 SN witness feeds the
-- parameter-free decider Conv.decidableOfStronglyNormalizing), and global confluence holds (per-term Newman on
-- the OB-5 SN witness). The qualifier is "assume WfContextDesc" (a decidable presupposition; the unqualified
-- typed-SN interface is unprovable since the var rule types in any context).
#assert_no_axioms FX1Poly.Typed.Conv.decidableOfWellTypedInWfContextDesc
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.subjectWeaklyNormalizesOfWfContextDesc
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.uniqueNormalFormOfWfContextDesc
-- SN-052 COMPARE step: checking a subject against a KNOWN-TYPE target reduces to deciding Conv (SN-051) — the
-- load-bearing infer-mode step of the bidirectional checker. isTrue via the grown conv rule; isFalse via the
-- subject's per-term uniqueness (holds for every non-λ subject). Typing witnesses threaded explicitly (data),
-- since Decidable cannot large-eliminate the Prop-valued IsTypeDesc existential.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.decidableCheckOfInferredUniqueAtType
-- SN-052 first COMPLETE checker case: deciding a VARIABLE against a known-type target (CHECK mode, SR-free)
-- composes the COMPARE step + variable inversion + variable inference + context validity
-- (IsType.decideWithWitness for the lookup's typehood-as-data, WfContext.lookupIsType refuting the impossible
-- non-type branch). The template for the application infer-mode case.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.decidableCheckVariableAtType
-- SN-052 second COMPLETE checker case (closes the SR-free leaf fragment): deciding a UNIVERSE CODE against a
-- known-type target (CHECK mode, SR-free). Strictly simpler than the variable case — both the inference and
-- its classifier-typing are direct universeFormation constructors, so no IsType.decideWithWitness is needed.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.decidableCheckUniverseCodeAtType
-- SN-052 APPLICATION checker case, factored over the SR-gated function exposure: given the function's Π-typing
-- + type-uniqueness + the Π-components' universe-typings (threaded as input — the eventual recursive inference
-- delivers them once the SR exposure lands), the application check against a known-type target reduces to the
-- argument's check against the domain. isTrue: piElim + substituteUnderBinding + applicationTypeUniqueGivenFunction
-- + COMPARE step; isFalse: invertApp + Conv.piTyCode_inj + conv show the application cannot be typed at all.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.decidableCheckApplicationGivenFunction
-- SN-052 Π/Σ-FORMATION checker cases (closes the infer-mode SR-free combinator coverage): deciding a former
-- against a known-type target given its components' universe-typings + uniqueness (threaded as input — the
-- recursive component-inference delivers them). SR-free: a former needs no exposure (its components are already
-- type codes), so the whole decision is the COMPARE step. {pi,sigma}FormationViaGenArm infers, universeFormation
-- types the inferred universe, {pi,sigma}FormationTypeUniqueGivenComponents supplies uniqueAtSubject.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.decidableCheckPiFormationGivenComponents
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.decidableCheckSigmaFormationGivenComponents

-- Ω HAS NO NORMAL FORM — sharpening "not SN" into "never reaches a Step-normal term." selfApplicator is itself
-- normal (by decide); Ω's only one-step reduct is Ω (Step.from_app inversion, congruence shapes refuted by the
-- self-applicator being normal); its only StepStar-reduct is Ω (chain induction, both endpoints generalized);
-- hence no reachable term is normal. The exact obstruction a raw weak-normalization proof cannot clear — closed,
-- well-scoped, ill-typed, every reduction path diverges (the reason SN-043/WN need the typing restriction).
#assert_no_axioms FX1Poly.Typed.selfApplicator_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.divergentOmega_reductIsSelf
#assert_no_axioms FX1Poly.Typed.divergentOmega_starReductIsSelf
#assert_no_axioms FX1Poly.Typed.divergentOmega_noNormalForm
-- HasTypeDescDecidable = Decidable (HasTypeDesc Γ t T), CASCADE-FREE. inferWithWitness =
-- principal-type synthesis (non-recursive: var/universe leaves; EVERY other
-- head delegates to IsTypeDesc.decideTypeGeneric — its universe witness IS the head's principal type, its
-- refutation reconstructs the denied IsTypeDesc witness via subjectRootGeneratorGeneric + the generic former
-- inversion + genFormation, with NO Π/Σ enumeration and no typingRuleDescOf_isPiOrSigma else-branch).
-- decidableOfWellFormed (gated above) = the decision via the IsType-gate on the classifier (Conv principal classifier
-- decided by Conv.decidableOfStronglyNormalizing — principal SN by classifierStronglyNormalizing,
-- classifier SN by IsTypeDesc.isStronglyNormalizing via decidableOfWellFormedGeneric) + conv rule forward +
-- uniqueness refute.
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.inferWithWitness
-- IsTypeDescDecidableGeneric = the FULLY cascade-free IsTypeDesc decider (GTL-10/11 payoff): a 3-function
-- STRUCTURAL mutual recursion over RawTerm/RawTermChildren (no size measure, no termination_by) with no Π/Σ
-- enumeration and no typingRuleDescOf_isPiOrSigma else. decideTypeGeneric does the var/universe
-- leaves + a typingRuleDescOf dispatch (some → decideSynthGeneric → genFormation; none → not_of_rootGenerator);
-- decideSynthGeneric synthesises the shared flag (ASSEMBLE form, recurses on childTail); decideAtFlagGeneric is
-- the fixed-flag spine. subst eliminates currentDepth (not childHead's shift), keeping it structural. A future
-- formation row is absorbed zero-touch — the FRAME-2 extensibility property, realized for the decider.
#assert_no_axioms FX1Poly.Typed.IsTypeDesc.decideTypeGeneric
-- The cascade-free Decidable instance — the typeclass form of decideTypeGeneric (cascade-free twin of
-- decidableOfWellFormed), the canonical decidability for the formation type-hood judgment.
#assert_no_axioms FX1Poly.Typed.IsTypeDesc.decidableOfWellFormedGeneric
-- IsTypeDescGenericSmoke = non-vacuity + definitional-computation corpus for decideTypeGeneric: each fixture is
-- `by rfl` (the kernel REDUCES the whole structural mutual recursion to the right constructor), proving the
-- decider is a genuine computable function that returns .inl on Π/Σ/nested-Π/universe types and .inr on
-- unitCell (a value) + emptyTypeCell (the GTL-11-deferred row, which FLIPS to .inl zero-touch when it lands).
#assert_no_axioms FX1Poly.Typed.IsTypeDesc.decidesAsTypeBool
#assert_no_axioms FX1Poly.Typed.decideTypeGeneric_smoke_universeCode
#assert_no_axioms FX1Poly.Typed.decideTypeGeneric_smoke_pi
#assert_no_axioms FX1Poly.Typed.decideTypeGeneric_smoke_sigma
#assert_no_axioms FX1Poly.Typed.decideTypeGeneric_smoke_nestedPi
#assert_no_axioms FX1Poly.Typed.decideTypeGeneric_smoke_emptyCodeDeferred
#assert_no_axioms FX1Poly.Typed.crossRef_uniqueNormalForm
#assert_no_axioms FX1Poly.Typed.crossRef_decidableConversion
#assert_no_axioms FX1Poly.Typed.crossRef_newmanLemma
#assert_no_axioms FX1Poly.Typed.correctedLamReview_corpusCheck
#assert_no_axioms FX1Poly.Typed.correctedLamReviewGate
#assert_no_axioms FX1Poly.Typed.correctedLamReviewGate_passes
#assert_no_axioms FX1Poly.Typed.universeFormationReview_corpusCheck
-- SN-112 (TypedNormalizer): the term-layer normalizer keyed DIRECTLY on the grown HasTypeDescPi judgment —
-- SN-043 (closedStronglyNormalizing) supplies RawTerm.normalize's Acc witness, so typing IS the termination
-- certificate (no Acc passed by hand). Distinct from firing 67's level-indexed route, the SimplyTypedTermLF
-- normalForm_typed, and SN-051's formation-engine classifier-side Conv.decidableOfHasTypeDesc. normalForm (the
-- NF fn) + normalForm_reducesTo (StepStar) + normalForm_isStepNormalForm + normalForm_conv (Conv to NF) +
-- conv_iff_normalForm_eq (NF is a COMPLETE conversion invariant) + closedConvDecidable (grown-keyed closed-
-- subject Conv decider, UNCONDITIONAL — grown twin of decidableOfHasTypeDesc). identityApplicationNormalForm
-- _convReduct = non-vacuity: the normalizer takes the closed β-redex (λx.x)(Type@e) to a NF convertible to its
-- reduct Type@e (real reduction work on firing 64's piElim derivation). Closes SN-112 (#615).
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.normalForm
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.normalForm_reducesTo
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.normalForm_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.normalForm_conv
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.conv_iff_normalForm_eq
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedConvDecidable
#assert_no_axioms FX1Poly.Typed.identityApplicationNormalForm_convReduct
-- DETERMINISM CONNECTOR (TypedNormalizer, appended): identify the COMPUTED normalForm (SN-112) as THE unique
-- normal form. closedHasUniqueNormalForm (GrownTypeSafety) proves a closed grown-typed term has a unique NF
-- EXISTENTIALLY; reachedNormalForm_eq_normalForm pins it to the computed function — any reached NF = typing.
-- normalForm (both = the unique value, via closedHasUniqueNormalForm's ∀-uniqueness on normalForm_reducesTo +
-- normalForm_isStepNormalForm). normalForm_eq_self_of_isStepNormalForm: already-normal subjects are fixed
-- points (reflexive instance). identityNormalForm_eq: the identity λx.x normalizes to itself (by decide on
-- isStepNormalForm). The normalizer computes THE canonical NF, not an arbitrary one.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.reachedNormalForm_eq_normalForm
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.normalForm_eq_self_of_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.identityNormalForm_eq
-- IDENTITY TOWER (IdentityTowerFamily): a uniformly-typed INFINITE family idTower e flag n = (λx.x)^n (Type@e),
-- complementing the §27.3 L2 constant-function tower (metatheoryFuzzFamily) with an identity tower. idTower_has
-- TypeDescPi: every height types uniformly at Type@(e+1) — base universeFormation, step RECURSIVE piElim of the
-- identity at Type@(e+1) against the IH (the rule fires n times in the n-th derivation; piElim result subst0
-- Type@(e+1) (idTower n) is defeq Type@(e+1), constant codomain). idTower_stronglyNormalizing: SN for all heights
-- via SN-043 uniformly. idTower_reducesToValue: β-reduces to Type@e in exactly n identity contractions ((λx.x)t ↝
-- t via Step.beta subst0 (var 0) t = t, StepStar.trans chain). idTowerUniformlyTypedReducesToValue packages the
-- headline — the typing engine + SN-043 scale to an INFINITE uniformly-typed family, not just finite fixtures.
#assert_no_axioms FX1Poly.Typed.idTower_hasTypeDescPi
-- ID-TOWER COLLAPSE (IdentityTowerFamily, appended): the family collapses to one canonical value via conversion
-- + the SN-112 normalizer. universeCodeCell_isStepNormalForm: Type@e is a step-NF (rfl over the Bool normality
-- check, free level/flag — nullary leaf, payload-independent). idTower_convToValue: each member converts to Type@e
-- (Conv.fromStepStar of idTower_reducesToValue). idTower_allConvertible: all members mutually convertible (one
-- Conv-class joined through Type@e, trans+sym). idTower_normalForm_eq_value: the computed normalForm of every
-- member = Type@e (firing-72 reachedNormalForm_eq_normalForm on the reduction to the normal value).
-- idTowerCollapsesToCanonicalValue: ★ infinitely many syntactically-distinct well-typed terms, all definitionally
-- equal, all normalizing to the single canonical value — the conversion/normalization face of the typed family.
#assert_no_axioms FX1Poly.Typed.universeCodeCell_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.idTower_normalForm_eq_value

/- The syntax-directed grown checking RELATION (GrownCheck): one arm per subject head shape, recursive
premises only on strict subterms, Conv only at compare leaves, no typehood premises — the
grown-strengthening campaign's central object (completeness ∘ rename-reflection ∘ soundness). absorbConv is
the recursion-free conv-absorption (completeness's conv-arm discharge); the leaf soundness lemmas
reconstruct typing at a typed target; the smokes pin the identity-λ check and the STR-1 escaping
reclassifier's GrownCheck-reachability (why the reflection conclusion is the Conv-existential). -/

#assert_no_axioms FX1Poly.Typed.GrownCheck
#assert_no_axioms FX1Poly.Typed.GrownCheck.absorbConv
#assert_no_axioms FX1Poly.Typed.GrownCheck.variableSoundAtTypedTarget
#assert_no_axioms FX1Poly.Typed.GrownCheck.universeCodeSoundAtTypedTarget
#assert_no_axioms FX1Poly.Typed.grownCheckIdentityLambdaSmoke
#assert_no_axioms FX1Poly.Typed.grownCheckEscapingReclassifierSmoke
#assert_no_axioms FX1Poly.Typed.GrownCheck.convBinder
#assert_no_axioms FX1Poly.Typed.GrownCheck.lamSoundGivenBodyTyped
#assert_no_axioms FX1Poly.Typed.GrownCheck.appSoundGivenComponentsTyped

/- Raw-relation SOUNDNESS REFUTED (GrownCheckSoundnessRefutation): the Curry fix-point TYPE
X := curryOmega (λT. Π T. Type@0) — with X ~Conv~ Π X. Type@0 — threads the app arm's floating Π-code, so
Ω = (λx.xx)(λx.xx) CHECKS at the typed target Type@0 while being untypable (SN-043). The
completeness ∘ reflection ∘ soundness pipeline cannot run over the RAW relation; typehood must enter via an
annotated judgment (campaign log carries the surviving routes). -/

#assert_no_axioms FX1Poly.Typed.recursivePiType
#assert_no_axioms FX1Poly.Typed.selfApplicationBodyChecks
#assert_no_axioms FX1Poly.Typed.selfApplicationChecksAtPi
#assert_no_axioms FX1Poly.Typed.selfApplicationChecksAtRecursiveType
#assert_no_axioms FX1Poly.Typed.omegaChecksAtTypeZero
#assert_no_axioms FX1Poly.Typed.grownCheckRawSoundness_isFalse

/- ConvExistentialStrengtheningRefutation — RETIRED refutation (T2 flipped it; user-approved
deletion 2026-06-10).  `convExistentialStrengthening_isFalse` is gone: under T2 `piIntro` pins
the λ annotation, the pre-T2 floating-domain witness is untypeable, and the Conv-existential
strengthening is expected TRUE.  Survivors: the variable-domain Π and its normality, the
RESTATED typing witness (the var-0-ANNOTATED identity), and `notConvWeakenImage` — which now
documents WHY the annotation pin is load-bearing rather than refuting anything. -/

#assert_no_axioms FX1Poly.Typed.variableDomainPi
#assert_no_axioms FX1Poly.Typed.variableDomainPi_isStepNormalForm
#assert_no_axioms FX1Poly.Typed.RawTerm.isStepNormalForm_childrenNormal
#assert_no_axioms FX1Poly.Typed.RawTermChildren.areStepNormalFormsBool_head
#assert_no_axioms FX1Poly.Typed.RawTermChildren.areStepNormalFormsBool_tail

/-! ### NormalizeSteps + NormalizeStepsTower — the SN-normalizer STRICT-COMPLEXITY witness (SN-145)

The normalizer's EXACT cost instrumentation: `normalizeSteps` (the `Acc.rec` twin of
`RawTerm.normalize`), the counted-chain identity (`StepStarN (normalizeSteps t acc) t
(normalize t acc)`), zero-cost-iff-normal, and the identity-tower family realizing the counter
exactly (`= towerHeight`) — yielding the unboundedness boundary brick.  HONEST scope: exactness +
unboundedness are machine-checked; NO size-polynomial bound is claimed in either direction (the
non-elementary β-normalization lower bound, Statman 1979, is literature-cited, not mechanized);
the polynomial-shape `StrictNormalizer` contract is deliberately NOT instantiated for the term
normalizer. -/

#assert_no_axioms FX1Poly.Core.RawTerm.normalizeSteps
#assert_no_axioms FX1Poly.Core.RawTerm.normalizeSteps_unfold
#assert_no_axioms FX1Poly.Core.RawTerm.normalizeSteps_eq
#assert_no_axioms FX1Poly.Core.RawTerm.reduceOnce_eq_none_of_isStepNormalForm
#assert_no_axioms FX1Poly.Core.RawTerm.normalizeSteps_chainExact
#assert_no_axioms FX1Poly.Core.RawTerm.normalizeSteps_eq_zero_iff
#assert_no_axioms FX1Poly.Typed.normalizeSteps_idTower
#assert_no_axioms FX1Poly.Typed.normalizeSteps_unbounded
#assert_no_axioms FX1Poly.Typed.idTower_normalizeChainExact
#assert_no_axioms FX1Poly.Typed.convDecideSteps_idTower
#assert_no_axioms FX1Poly.Typed.convDecideSteps_unbounded
