import FX1PolyAudit.DependencyAudit
import FX1Poly.Core.Metatheory.Reducibility.Core.DataReducibilityCoverage
import FX1Poly.Core.Metatheory.Reducibility.Candidates.DataTaitCandidate
import FX1Poly.Core.Metatheory.Reducibility.Candidates.FlatCodeTaitCandidate
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FlatCodeCanonicalForms
import FX1Poly.Typed.Ledger.MilestoneASpineValueLayer
import FX1Poly.Typed.Ledger.MilestoneAEliminatorLayerSpine
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimComputingCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicityTyped
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchGeneralBranchCanonicity
import FX1Poly.Typed.Ledger.MetatheoryParityLedger
import FX1Poly.Typed.Engine.Classifier.TypingContext
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeShape
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeConversion
import FX1Poly.Typed.Engine.Formation.SigmaCodeShape
import FX1Poly.Typed.Engine.Formation.ListCodeShape
import FX1Poly.Typed.Engine.Formation.ListFormationSmoke
import FX1Poly.Typed.Engine.Formation.OptionCodeShape
import FX1Poly.Typed.Engine.Formation.OptionCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.OptionFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationOptionFromTelescope
import FX1Poly.Typed.Engine.Formation.OptionFormationSmoke
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDesc
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescDecidable
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElim
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescValidity
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescClosedForms
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFormerTelescopeInversion
import FX1Poly.Typed.Engine.Formation.DataFormerInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescUniqueness
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPi
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaCoherence
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionGrown
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionComputes
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiWeakening
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiSubstitution
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiValidity
import FX1Poly.Typed.Ledger.Misc.ConvCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvBoolCodeRigidity
import FX1Poly.Typed.Engine.Formation.ConvFormationFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvCrossTableFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvDataCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.EmptyTypeCodeConvRigidity
import FX1Poly.Typed.Ledger.Inversion.EmptyTypeValueInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FormationCanonicalForms
import FX1Poly.Typed.Ledger.Inversion.PiTypeFunctionInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalForms
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafety
import FX1Poly.Typed.Engine.Formation.FormationTypeSafety
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsNonVacuity
import FX1Poly.Typed.Corpus.Smoke.GrownBetaRedexInAction
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgress
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownOpenCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafetyUnconditional
import FX1Poly.Typed.Engine.Formation.FormerStepInversionGeneric
import FX1Poly.Typed.Metatheory.SubjectReduction.SubjectReductionAtFormerGeneric
import FX1Poly.Typed.Engine.WfContext.WfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescValidity
import FX1Poly.Typed.Engine.WfContext.WfContextDescUniqueness
import FX1Poly.Typed.Engine.WfContext.WfContextDescPi
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiFromWfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiClassifierValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiFunctionComponentValidity
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionDescPi
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionMutual
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnv
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAt
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvTypeVariable
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprFT
import FX1Poly.Typed.Metatheory.Reducibility.Pi.AbstractionNonDependentUnderSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprReducibleLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermFundamentalLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInversionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprClosureLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermRenameLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1Poly.Typed.Metatheory.SimplyTyped.MilestoneA0SimplyTypedFloor
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1Poly.Tier0.Context.Instances.Renaming.FxRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecIsomorphism
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecPreimage
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTryTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecRMC
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecGlobalSections
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecSconingPreservation
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstVec
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstCategory
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWeakening
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstComprehension
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstSingleton
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstGlobalSections
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWitnessScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstConcreteScone
import FX1Poly.Tier0.Context.IsomorphismCategorical
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeRMC
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeGlobalSections
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1Poly.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1Poly.Core.Rewriting.Reduction.Head.RootStepDispatch
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnce
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1Poly.Core.Rewriting.Normalize.Normalize
import FX1Poly.Core.Rewriting.Normalize.NormalizeSteps
import FX1Poly.Core.Rewriting.Conversion.ConvDecisionSteps
import FX1Poly.Core.Rewriting.Normalize.NormalizeMeta
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsWeakHeadExpansion
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.BoolElimCanonicalComputation
import FX1Poly.Core.Eliminators.Bool.BoolElimClosedMembership
import FX1Poly.Core.Eliminators.Core.DataEliminatorMembershipSmoke
import FX1Poly.Core.Metatheory.Canonicity.SigmaProjectionCanonicalComputation
import FX1Poly.Core.Metatheory.Canonicity.IdentityEliminatorCanonicalComputation
import FX1Poly.Core.Eliminators.Identity.IdEliminatorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.OptionEitherMatchCanonicalComputation
import FX1Poly.Core.Eliminators.Match.MatchClosedMembership
import FX1Poly.Core.Eliminators.Sigma.SigmaProjectionClosedMembership
import FX1Poly.Core.Eliminators.Recursor.RecursorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.RecursiveEliminatorBaseComputation
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.DataCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.ModalCanonicityViaSconing
import FX1Poly.Core.Metatheory.Sconing.DataMetatheoryViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1Poly.Core.Metatheory.Sconing.ConsistencyViaSconing
import FX1Poly.Core.Eliminators.Core.DataEliminatorProgressViaSconing
import FX1Poly.Core.Eliminators.Recursor.RecursiveEliminatorProgressViaSconing
import FX1Poly.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.UnitCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EmptyCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingSubst
import FX1Poly.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1Poly.Core.Metatheory.Normalization.Core.WeakNormalization
import FX1Poly.Core.Rewriting.Normalize.NormalFormUnique
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevels
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllFormerChildren
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPiIntro
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Pi.NeutralFuelStability
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiTypeSaturationReassembly
import FX1Poly.Typed.Metatheory.Reducibility.Pi.StrongNormalizingAllLevelPiComponents
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescopePositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllCanonicalCandidate
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllVectorPremises
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllNonDependentBinders
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtUniformVectorPremises
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFundamentalVectorFromFormation
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFundamentalAtAllFromGenFormation
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClosedLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.TypeFundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LeveledContext
import FX1Poly.Typed.Corpus.Smoke.ClosedSNSmoke
import FX1Poly.Typed.Corpus.Smoke.UntypedOmegaNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.StepNonDeterministic
import FX1Poly.Typed.Ledger.Misc.ConvValueDiscrimination
import FX1Poly.Typed.Corpus.Smoke.TypedLambdaDerivations
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleans
import FX1Poly.Typed.Corpus.Church.Core.TypedChurchNegation
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumerals
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIteration
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralDiscrimination
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralThree
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralTyping
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralInhabitants
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralComputeGeneral
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralAddition
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralMultiplication
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralSemiringLaws
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIsZero
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleanOperations
import FX1Poly.Typed.Corpus.Smoke.TypedFragmentAcyclicity
import FX1Poly.Typed.Corpus.Smoke.UnboundedGrowthNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointDivergence
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointCombinator
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryLogic
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryCompleteness
import FX1Poly.Typed.Corpus.Church.Combinators.SymbolicSCombinatorRule
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairs
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairsInjective
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSums
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsDisjoint
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsGeneral
import FX1Poly.Typed.Corpus.Church.Lists.ChurchLists
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListIsEmpty
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAny
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAll
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBooleanComplementLaws
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBoolXor
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListFirstOr
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSucc
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSuccApplies
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListLength
import FX1Poly.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1Poly.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1Poly.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseNoTop
import FX1Poly.Typed.Metatheory.Universe.TypedUniversePredicative
import FX1Poly.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1Poly.Typed.Corpus.Progress.ClosedNormalForm
import FX1Poly.Typed.Metatheory.Normalizer.ClosedNonConvertibility
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTyping
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiStronglyNormalizingFromFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVecTypeVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConsistency
import FX1Poly.Typed.Engine.Formation.HasTypeFormationNoLambdaApplication
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleSemanticRules
import FX1Poly.Typed.Engine.Formation.ListCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.ListFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberFormation
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeInversion
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeReach
import FX1Poly.Typed.Engine.RuleTables.FlatDescTelescope
import FX1Poly.Typed.Metatheory.Canonicity.Core.StandaloneEngineCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.CombinedBoolCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedBoolCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicitySyntacticRoute
import FX1Poly.Typed.Metatheory.Canonicity.Core.GrownRigidityCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedNatCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimValueCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.NatElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulArithmetic
import FX1Poly.Typed.Metatheory.Reducibility.Core.ClosedNumeralSubstInvariant
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulMul
import FX1Poly.Typed.Corpus.Faithfulness.ValueElimHostFold
import FX1Poly.Typed.Corpus.Faithfulness.RecursorHostFold
import FX1Poly.Typed.Metatheory.Canonicity.Core.ListElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.ListElimFaithfulLength
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicity
import FX1Poly.Typed.Corpus.Progress.GrownClosedNormalClassifierShape
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ClosedNormalEmptyConsistency
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ProductEitherCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.OptionCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ListCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.IdCanonicalForms
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiFormerMembership
import FX1Poly.Typed.Engine.Formation.FormerChildrenReducible
import FX1Poly.Typed.Metatheory.Reducibility.Telescope.TelescopeReducible
import FX1Poly.Typed.Metatheory.Universe.UniverseDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsInduction
import FX1Poly.Typed.Metatheory.Reducibility.Pi.ReducibleTypeAtAllLevelsPiNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsWhnfDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsPiDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsPiMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsHeadExpand
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsConv
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Strengthening.RouteAObstruction
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelDiagnosis
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelMeasure
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibility
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibilitySmoke
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPi
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedLevelIrrelevance
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseFormationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCanonicalMemberCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationFromExistence
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGeneralDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSingleLevelPi
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiAboveThreshold
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormerAtLevel
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleTypeLevelLift
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiArmDischarge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedApplicationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedConvMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberForwardClosed
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMemberBetaExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberWeakHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedAbstractionMember
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAbstractionUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiElim
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalConv
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAmbientLevelBridge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrow
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiIntro
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedClosedMember
import FX1Poly.Typed.Metatheory.Denote.Telescope.DenoteKeyedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedUniformReducible
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMembershipIntro
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFormation
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFromChildMembers
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationSigmaArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedCumulativityObstruction
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibility
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedConvArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiElimArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiIntroArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedFormerEngine
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiDischarge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedAssemblyBridge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeProjection
import FX1Poly.Typed.Engine.Formation.FormerOutputLevelBounds
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedCodomainOpenSN
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDomainInhabitant
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationPiFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationSigmaFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationListFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedTelescopeConsSucc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGrownDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDesc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPi
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPiDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedGrownFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ClosedBoundedReducibleMember
import FX1Poly.Typed.Corpus.Smoke.ClosedStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedNeutralMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseInversion
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBindingTypeReducible
import FX1Poly.Typed.Engine.WfContext.ReducibleEnvOfWfContext
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizingUnconditional
import FX1Poly.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1Poly.Typed.Corpus.Smoke.OpenSNSmoke
import FX1Poly.Typed.Corpus.Progress.ContextValidityFails
import FX1Poly.Typed.Equality.UnitEta.UnitEtaJudgmentalEquality
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruenceGap
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruentEquality
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapse
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseIncompleteness
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeep
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseNeutralBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitNeutralSpineDetection
import FX1Poly.Typed.Equality.UnitEta.UnitSpineDetectionBoundary
import FX1Poly.Typed.Equality.UnitEta.TypeDirectedUnitReadback
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackArgumentBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackFormerChildBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackDeepSpineBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackAnnotationBoundary
import FX1Poly.Typed.Engine.Formation.FormationClassifierRigidity
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeConvDecision
import FX1Poly.Typed.Ledger.Misc.LiftedChildNormalizationFromClosure
import FX1Poly.Typed.Engine.RuleTables.TelescopeSubstitutedChildrenNormalization
import FX1Poly.Typed.Ledger.CascadeFreedomLedger
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyTargetSignature
import FX1Poly.Typed.Ledger.Bridge.CandidateBridgeEditViability
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicityTargetSignature
import FX1Poly.Typed.Metatheory.Universe.NullaryFormerFormation
import FX1Poly.Typed.Metatheory.Universe.GrownUniverseFormationStrictness
import FX1Poly.Typed.Engine.Formation.GrownFormerFormationStrictness
import FX1Poly.Typed.Engine.Classifier.GrownTypingNotUnique
import FX1Poly.Typed.Engine.Classifier.GrownEngineHonesty
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.GrownUniverseConsistency
import FX1Poly.Typed.Engine.Classifier.GrownVariableHonesty
import FX1Poly.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiLamInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiAppInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVarInversion
import FX1Poly.Typed.Metatheory.ContextConversion.VarHeadedAppContextConversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiBetaSR
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiCongruence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerCongruence
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionConditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimReduction
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionValidityReduction
import FX1Poly.Typed.Corpus.Progress.GrownMutualMetatheoryFromPiValidity
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimEquivalence
import FX1Poly.Typed.Engine.HasTypeDescPi.ContextConversion.HasTypeDescPiContextStepConversion
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionUnconditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionFlexibleUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormationFragment
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormerStep
import FX1Poly.Typed.Metatheory.ContextConversion.GenFormerValidityContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPiValidityModelNeutral
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveled
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransport
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransportUnderWf
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledCompleteness
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValid
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRename
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValidLookup
import FX1Poly.Typed.Ledger.Misc.PiElimClassifierConvResidual
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiFormerInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiDataHeadUntyped
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiRootGeneric
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedUniverseBoundedCumulativity
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedClosedTypeCodeSN
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiMemberSN
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrowMemberSN
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCodomainMemberWiring
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelSpike
import FX1Poly.Typed.Ledger.SNStrategy
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.LogRelSpec
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LevelingBridge
import FX1Poly.Typed.Metatheory.Canonicity.Core.ConsistentStratification
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingLevelFlexible
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingRefinedMotive
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingConvArm
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingPiArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingFormerArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingVariableLevelPinned
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalReduction
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalAssembly
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.SimplyTyped.HigherOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiOverNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiNeutralCodomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentlyTypedNeutralDomainFragment
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedSubsumption
import FX1Poly.Typed.Metatheory.Universe.UniverseCumulativity
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermReducibility
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiTypingNonUnique
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckOfInferred
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVariableInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiUniverseCodeInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckUniverseCode
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplicationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckFormation
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationCodomainReTyping
import FX1Poly.Typed.Engine.RuleTables.IntroRuleDesc
import FX1Poly.Typed.Engine.RuleTables.ElimRuleDesc
import FX1Poly.Typed.Engine.RuleTables.GenElimIotaComputation
import FX1Poly.Typed.Engine.Classifier.TypingRoleClassifier
import FX1Poly.Typed.Engine.Classifier.TypingRoleEngineBridge
import FX1Poly.Typed.Engine.Classifier.TypingRoleCoverage
import FX1Poly.Typed.Engine.Classifier.UntypableHeadDecision
import FX1Poly.Typed.Engine.Classifier.TypingHeadKindClassifier
import FX1Poly.Typed.Engine.Classifier.TypedBySomeEngine
import FX1Poly.Typed.Engine.Classifier.GeneratorSemanticTier
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyOverview
import FX1Poly.Typed.Engine.Classifier.StaticTypingSoundness
import FX1Poly.Typed.Engine.Classifier.SemanticTierSoundness
import FX1Poly.Typed.Engine.Classifier.ClassifierRefinement
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyLedger
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionTermination
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerStepDomainFormationCodomain
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionFormerArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionInlineArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionConvOfFormationArms
import FX1Poly.Typed.Metatheory.SubjectReduction.ConsistencyConditionalOnSubjectReduction
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencySyntactic
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyOfPiElimArm
import FX1Poly.Typed.Ledger.Misc.PiElimUpToClassifierConv
import FX1Poly.Typed.Engine.Classifier.ClassifierRespectsConvRefuted
import FX1Poly.Typed.Dimensions.AxisObligation.TypedCertificationStackingRefuted
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencyUnconditional
import FX1Poly.Typed.Engine.Formation.FormationNormalSmoke
import FX1Poly.Typed.Engine.Formation.BoolTypeCodeSubstrate
import FX1Poly.Typed.Engine.Formation.NatTypeCodeSubstrate
import FX1Poly.Typed.Corpus.Progress.GrownNoTypeInType
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescRigidity
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidable
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1Poly.Typed.Ledger.KnownUnsoundnessCorpus
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationAcyclic
import FX1Poly.Modal.SecurityNoninterferenceGeneral
import FX1Poly.Modal.GradedApplicationFlow
import FX1Poly.Typed.Ledger.MetatheoryFuzz
import FX1Poly.Typed.Ledger.FuzzCorpusConvertibility
import FX1Poly.Typed.Ledger.FuzzCorpusNormalizes
import FX1Poly.Typed.Ledger.LambdaValueFuzzFamily
import FX1Poly.Typed.Ledger.MechanizedProofCrossReference
import FX1Poly.Typed.Ledger.FormalReviewGate
import FX1Poly.Typed.Ledger.SelfVerifiedMetatheory
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengthening
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheck
import FX1Poly.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1Poly.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiImageComponents
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiRenameImage
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionContext
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiIntro
import FX1Poly.Typed.Engine.Formation.FormationPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.GrownPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimCore
import FX1Poly.Typed.Corpus.Smoke.GrownWfOpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimDispatcher
import FX1Poly.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1Poly.Typed.Metatheory.Strengthening.GuardedPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PlateauPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.NeutralReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionLamClassifierResidual
import FX1Poly.Typed.Metatheory.Strengthening.FlagCoherentReflectionCondition
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationUnique
import FX1Poly.Typed.Ledger.Misc.NeutralClassifierUnique
import FX1Poly.Typed.Ledger.Misc.NormalAppNeutral
import FX1Poly.Typed.Engine.RuleTables.TelescopeUniverseDeterminism
import FX1Poly.Typed.Engine.RuleTables.GenericFormerTelescopeInversion
import FX1Poly.Typed.Metatheory.Universe.NormalUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.ConvUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Strengthening.RenameAlongFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.PinSelectsCallerPair
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.LamReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherentMaster

/-! # FX1PolyAudit/AuditTypedFundamentalDenote — typed-layer zero-axiom gates: the denote-keyed reducibility fundamental theorem
   (semantic shard of the typed audit; gates classified by declaration topic, appended
   clusters kept together; full import block retained for namespace-sweep coverage) -/


-- SN-003: the predicative well-founded MEASURE for classifier-level reducibility.  `denote_lt_lsucc` is the
-- strict decrease at the universe-decode step; the `lmax` bounds are the non-increasing former-component
-- descents; `variableCell_reducibleTypeAtZero` is the non-degenerate base (neutral types inhabit level 0,
-- unlike the SN-001 universe-code vacuity).
#assert_no_axioms FX1Poly.Typed.denote_lt_lsucc
#assert_no_axioms FX1Poly.Typed.denote_le_lmax_left
#assert_no_axioms FX1Poly.Typed.denote_le_lmax_right
-- The composed universe-domain-Pi measure step (#672 sub-step 3): a member of Type@e has level denote e
-- strictly below the dependent Pi's level lmax (lsucc e) levelC — the Adjedj recursion's well-founded
-- descent. Member level bound comes from ValidTyping's subjectLevel (the validity derivation), not bare
-- reducibility.
#assert_no_axioms FX1Poly.Typed.denote_lt_lmax_lsucc_left

-- DenoteKeyedReducibility (SN-006 foundation toward #672): the classifier-universe-level reducibility
-- relation. The universe arm decodes Type@e to the lower relation AT denote e (the fixed classifier level),
-- not ambient-fuel-minus-one — defeating SN-001's fuel-0 vacuity. The lower family is STRUCTURAL (not WF:
-- the WF .eq_def leaks Quot.sound), granting arbitrary-lower-level access at the structural predecessor.
-- universeMembership_levelIrrelevant is the headline: Type@e's candidate is the SAME decode-at-(denote e)
-- set at every ambient level > denote e — the level-irrelevance the fuel model could not deliver, true by
-- construction. universeCode_isReducibleAtDenote is the anti-vacuity (refutes RouteAObstruction's empty base).
#assert_no_axioms FX1Poly.Typed.universeDenotePredicate
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote
#assert_no_axioms FX1Poly.Typed.denoteBelowFamily
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtDenote
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtDenote
#assert_no_axioms FX1Poly.Typed.denoteBelowFamily_eq_reducible
#assert_no_axioms FX1Poly.Typed.universeCode_isReducibleAtDenote
#assert_no_axioms FX1Poly.Typed.universeMembership_levelIrrelevant

-- DenoteKeyedReducibility CR machinery (#672 sub-step 1): shape inversions + determinism, ported from
-- StratifiedReducibleType. The only structural difference: the denote-keyed universe candidate depends on
-- levelExpr, so candidateIffUniverse/deterministic align it via universeCodeCell_inj (where the fuel version
-- used bare Iff.rfl). piTypeInversion decomposes a reducible Pi(Type@e)C — the decomposition the
-- universe-domain piArm of typeLevelIrrelevance consumes; deterministic aligns the domain/codomain candidates.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.candidateAtWhnfReduct
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.candidateIffStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.candidatePiShape
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.candidateIffUniverse
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.candidateIffEmptyCandidate
-- The FLAT twin (CAN-6): root-keyed shape inversion — a reducible type whose root generator is a FLAT data
-- code came through the dedicated dataFlat arm; its candidate IS the pinned flat Tait candidate.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.candidateIffFlatCandidate
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.deterministic
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtDenote.deterministic
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtDenote.piTypeInversion

-- DenoteKeyedReducibility forward closure + conversion-invariance (#672 sub-step 2a): ported from
-- StratifiedReducibleTypeForwardClosure/ConvInvariance. The reduction helpers (commuteWithStep,
-- weakHeadNormalRootStableAlongStepStar, piTyCode_decompose, noStep_universeCode) are relation-agnostic and
-- reused verbatim; only the reducibility constructors change. convTransfer is the membership form the conv
-- typing arm and the dependent-arrow CR3 argument-reduction case consume — the prerequisite for the arrow CR.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.whnfExpandClosure
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.forwardStepStar
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtDenote.forwardStepStar
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.convInvariant
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.convTransfer
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtDenote.convTransfer

-- DenoteKeyedReducibility CR-soundness (#672 sub-step 2b): every denote-keyed candidate is a Girard
-- reducibility candidate (CR1/CR2/CR3). The arrow CR is a verbatim port (CR3 via convTransfer); the
-- parametric isReducibilityCandidate reuses the fuel universeCandidateIsReducibilityCandidate at the DECODED
-- level via the defeq universeDenotePredicate env lowerAt levelExpr = universeReducibilityPredicate
-- (lowerAt (denote levelExpr env)). Interface legs are per-level (∀ lvl); the unconditional level-indexed
-- discharge carries the predicative level-bound subtlety, deferred to the piArm step.
#assert_no_axioms FX1Poly.Typed.isDependentArrowReducibleStepDenote_isReducibilityCandidate
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.isReducibilityCandidate

-- DenoteKeyedReducibility interface-leg discharge for denoteBelowFamily (#672 sub-step 3 prerequisite):
-- the per-level legs the candidate machinery consumes. forwardStep is unconditional (below the level via
-- coherence, above it vacuous since the family is empty); neutralInclusion holds for lvl < level only
-- (at/above, the family is empty and neutral-inclusion FAILS — SN-001 degeneracy re-keyed to denote; the
-- piArm satisfies the bound via denote e < level / denote_lt_lsucc). backwardWeakHeadStep is the THIRD leg
-- and is UNCONDITIONAL: unlike neutral-inclusion (an existence obligation, false on the empty family), a
-- backward-step leg is an implication whose premise is False above the bound, hence vacuous there and
-- whnfExpand below it — the leg the member weak-head β-expansion (denote lambda-arm engine) needs at its
-- universe arm, making that case bound-free.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.forwardStep
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.reducibleOfNeutral
#assert_no_axioms FX1Poly.Typed.denoteBelowFamily_eq_empty_of_ge
-- the denote-keyed semantic member predicate (member analogue of IsReducibleTypeAtDenote)
#assert_no_axioms FX1Poly.Typed.IsReducibleMemberAtDenote
#assert_no_axioms FX1Poly.Typed.universeDomainPi_reducibleAtAllDenoteLevels
#assert_no_axioms FX1Poly.Typed.universeDomainPi_uniformCandidateAtAllDenoteLevels
#assert_no_axioms FX1Poly.Typed.universeDomainPi_memberStableAcrossDenoteLevels
-- universeLeafMemberStableAcrossDenoteLevels: the LEAF twin of the Π member-stability -- a reducible member of
-- Type@e at one level above denote e is a member at every level above it. The fixed decode-set candidate
-- (universeMembership_levelIrrelevant) is the same at both levels; determinism reconciles. Fills the gap left by
-- DenoteKeyedLevelIrrelevance (which has leaf member-stability only for neutral/uniform types, uniform across ALL
-- levels; the universe is uniform only ABOVE denote e). Choice-free (canonical candidate). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.universeLeafMemberStableAcrossDenoteLevels
-- totalises the universe-domain Π to ∀ level (the IsReducibleTypeAtAllDenoteLevels piArm shape): genuine
-- levels reuse reducibleAtAllDenoteLevels, low levels (≤ denote e env) vacuous via empty domain candidate.
#assert_no_axioms FX1Poly.Typed.universeDomainPi_reducibleAtEveryDenoteLevel

-- DenoteKeyedLevelIrrelevance (#672 toward the denote level-irrelevance induction): the denote analogue of the
-- fuel IsReducibleTypeAtAllLevels.ofReducibleTypeStep. IsReducibleTypeAtAllDenoteLevels = ∀ level,
-- IsReducibleTypeAtDenote env level typeCode. ofNeutral/ofUniverseCode/headExpand are the level-uniform leaves;
-- ofReducibleTypeStepDenote is the induction backbone discharging neutral/universe/whnfExpand/ofPointwiseIff and
-- isolating piType as the piArm hypothesis (whose impredicative universe-domain instance the fuel model could
-- not close but DenoteKeyedUniverseDomainPi does).
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtAllDenoteLevels
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtAllDenoteLevels.ofNeutral
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtAllDenoteLevels.ofUniverseCode
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtAllDenoteLevels.headExpand
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtAllDenoteLevels.ofReducibleTypeStepDenote
-- the NON-universe half of the piArm: uniformDomainPi handles any domain with a single candidate uniform at
-- ALL levels (neutral/data/non-universe-former domains); neutralDomainPi is the witnessing neutral instance
-- (candidate IsStronglyNormalizing). Complements A1 (universe domain, uniform above denote e env).
#assert_no_axioms FX1Poly.Typed.uniformDomainPi_reducibleAtEveryDenoteLevel
#assert_no_axioms FX1Poly.Typed.neutralDomainPi_reducibleAtEveryDenoteLevel
-- member-level complement (toward the denote #672 member-extension): a member of a type reducible with one
-- all-level uniform candidate is level-stable (via determinism); neutral-type instance witnesses it. The
-- non-universe analogue of universeDomainPi_memberStableAcrossDenoteLevels (which holds only above denote e).
#assert_no_axioms FX1Poly.Typed.uniformType_memberStableAcrossDenoteLevels
#assert_no_axioms FX1Poly.Typed.neutralType_memberStableAcrossDenoteLevels
-- Member-stability lifted from leaf types to the Π FORMER: a uniform-domain Π's own candidate
-- (fun f => forall arg, domCand arg -> codCand arg (app f arg)) is itself level-uniform, so
-- uniformType_memberStableAcrossDenoteLevels applies. uniformDomainPiType_ + the neutral-domain witnessing
-- instance neutralDomainPiType_ extend the member-stable #672 fragment to dependent arrows over member-stable
-- domains -- the non-universe-domain case the cumulativity obstruction does NOT block.
#assert_no_axioms FX1Poly.Typed.uniformDomainPiType_memberStableAcrossDenoteLevels
#assert_no_axioms FX1Poly.Typed.neutralDomainPiType_memberStableAcrossDenoteLevels

-- DenoteKeyedReducibleEnv (route C toward the denote fundamental theorem): the denote analogue of
-- ReducibleEnvAt, riding on IsReducibleMemberAtDenote. def + var-projection + empty + binder-cons; the cons
-- proof is character-identical to ReducibleEnvAt.cons (env/level ride along the lookup/weaken rewrites).
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtDenote
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtDenote.lookupReducible
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtDenote.empty
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtDenote.cons

-- DenoteKeyedCanonicalMemberCandidate (route D Π-formation engine, the denote analogue of #490): the canonical
-- member-predicate IsReducibleMemberAtDenote env level typeCode is itself the type's own candidate. The
-- choice-free codomain extraction the denote FT's Π-formation arm consumes — turns the codomain IH's mere
-- EXISTENCE of a candidate into the FIXED canonical predicate, no Classical.choice. ofPointwiseIff (pointwise,
-- no funext) + deterministic; uniform in level (no cases-level split the fuel original needed).
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtDenote.reducibleMemberCandidate
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtDenote.reducibleMemberCandidate

-- Member-transfer across weak-head reduction (the member-level analogues of SN-D1 head-expansion closure):
-- headExpand re-attaches the same candidate above a whnf step (whnfExpand ctor); weakHeadForward keeps the
-- candidate at the contractum (candidateAtWhnfReduct). whnfExpandDomainMemberStableToOuter is the whnfExpand
-- arm of the #752 dispatcher — member-stability transfers across a domain whnf step (forward to reduct, lift by
-- the contractum's stability, head-expand back), reducing the redex-domain case to the contractum's stability.
#assert_no_axioms FX1Poly.Typed.IsReducibleMemberAtDenote.headExpand
#assert_no_axioms FX1Poly.Typed.IsReducibleMemberAtDenote.weakHeadForward
#assert_no_axioms FX1Poly.Typed.whnfExpandDomainMemberStableToOuter

-- compositeDomainMemberStableToOuter (#752 — the RECURSIVE HEART, threshold-drift composite domains): Π dom cod
-- is member-stable to outerLevel from the components' all-levels both-directions member-stability (domainStable /
-- codomainStable, the recursion IHs). A function member at sourceLevel maps source-dom-members to
-- source-cod-members (piTypeInversion); an outer-dom argument is pulled back to source (domainStable
-- outer→source, candidate via deterministic), fed to the function's source property, and the codomain image
-- pushed forward to outerLevel (codomainStable source→outer, candidate via deterministic). The drift is absorbed
-- entirely into the components' member-stability — the Π former composes with NO extra threshold reasoning. The
-- recursion bottoms out at neutral/universe/whnf-redex leaves; only the universe leaves carry the threshold gate.
#assert_no_axioms FX1Poly.Typed.compositeDomainMemberStableToOuter

-- DenoteKeyedUniverseDomainPiArm (#752 — the universeCode arm of the ofReducibleTypeStepDenote piArm case-split):
-- the domain is a universe code Type@innerLevelExpr whose membership candidate DRIFTS (empty below the inner
-- decoded level, real above), so the neutral/uniform adapters cannot reach it. The two decode lemmas split the
-- lowerAt-keyed universe predicate universeDenotePredicate env (denoteBelowFamily env outerLevel) innerLevelExpr:
-- _aboveThreshold (inner < outer) decodes to "SN ∧ reducible-as-type at the inner level" via
-- denoteBelowFamily_eq_reducible; _empty (outer ≤ inner) refutes membership via denoteBelowFamily_eq_empty_of_ge.
-- universeDomainPiArmFromInductiveHypotheses then discharges the arm gated on the WELL-TYPED-guaranteed threshold
-- (denote innerLevelExpr env < outerLevel = the Π-formation level constraint Type@inner : Type@outer), assembling
-- IsReducibleTypeAtAllDenoteLevels PER OUTPUT LEVEL (so the codomain candidate may DRIFT — no member-stability):
-- above the inner level decode + transport to the backbone candidate + fire the codomain IH's canonical
-- member-predicate; at/below the inner level the domain is empty so the codomain obligation is vacuous. Remaining
-- #752 arms: composite/threshold-drift (piType) + the high-inner-universe case (unreachable for well-typed input).
#assert_no_axioms FX1Poly.Typed.universeDenotePredicate_belowFamily_aboveThreshold
#assert_no_axioms FX1Poly.Typed.universeDenotePredicate_belowFamily_empty
#assert_no_axioms FX1Poly.Typed.universeDomainPiArmFromInductiveHypotheses
-- universeDomainMemberStableToOuter: the universe-code instance of the unified piArm's memberStableToOuter,
-- gated on inner < outerLevel. A member at source forces inner < source (else empty), decodes to SN ∧
-- reducible-at-inner, the same predicate as the outerLevel candidate (also above inner) — so it transports.
#assert_no_axioms FX1Poly.Typed.universeDomainMemberStableToOuter

-- DenoteKeyedReducibilitySmoke (regression corpus, SN-149-flavored): the first CONCRETE denote-reducibility
-- witnesses — the two LEAF cases of the step functor. smoke_universeCode_isReducibleAtDenote: the universeCode
-- arm (a universe code reducible at EVERY level, the anti-vacuity refuting SN-001's empty fuel-0 base).
-- smoke_neutralVariable_isReducibleAtDenote: the neutral arm (a context variable, weak-head-normal non-Π
-- non-universe, reducible with the SN candidate; noWeakHeadStep from noStep_var via WeakHeadStep.toStep, the
-- root-generator inequalities via show-then-decide on the closed enum). The universe/neutral leaves of the
-- denote reducibility relation, guarding the load-bearing entry points against regression.
#assert_no_axioms FX1Poly.Typed.smoke_universeCode_isReducibleAtDenote
#assert_no_axioms FX1Poly.Typed.smoke_neutralVariable_isReducibleAtDenote
-- smoke_sigmaFormer: the neutral arm on a FORMER (not a leaf) — a Σ-type former is reducible-as-type
-- unconditionally (noWeakHeadStep via nomatch; no constraint on the children), concretely witnessing the EASY
-- half of the genFormationPi reducible-as-type ingredient (non-Π non-universe formers are reducible types; only
-- the Π case routes through the piType arm and constrains its children).
#assert_no_axioms FX1Poly.Typed.smoke_sigmaFormer_isReducibleAtDenote

-- SN-D5d (denote universe-member CR1 + Σ-from-child-members assembly): bridges the children's universe
-- MEMBERSHIPS (what the FT telescope IH supplies) to sigmaFormationMemberAtDenote's SN premises.
-- stronglyNormalizing_of_universeMemberAtDenote: a member of Type@e above threshold is SN (universe candidate
-- pinned via universeMembership_levelIrrelevant + ReducibleTypeAtDenote.deterministic — the threshold is the
-- fundamental #672 caveat). sigmaFormationFromChildMembersAtDenote: domain member + codomain member at var 0
-- ⟹ Σ universe membership (domain SN by CR1; codomain-under-binder SN by CR1 then openBodyOfConsSubst; the
-- denote analogue of the fuel sigmaFormerOfChildMembershipsAtRequiredLevel).
#assert_no_axioms FX1Poly.Typed.stronglyNormalizing_of_universeMemberAtDenote

-- SN-D5d (the genFormationPi Σ FT arm, premise-isolating like fundamentalPiIntroAtDenote): domain universe
-- membership (CR1-discharged to domain SN) + codomain under-binder SN, both ∀-substitution, ⟹ the Σ former's
-- FundamentalConclusionAtDenote at Type@levelExpr. The Σ case reduces to children SN (reducible-as-type is the
-- free neutral arm); the codomain SN is the deferred premise (its production needs var-0 mining at the weakened
-- scope = the Kripke-obstructed SN-040). The direct analogue of fundamentalPiIntroAtDenote for genFormationPi/Σ.
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationSigmaAtDenote

-- SN-D5d (the genFormationPi Π FT arm, premise-isolating — the Π twin of the Σ arm, completing the 2-case
-- split): domain universe membership (CR1 → domain SN) + codomain under-binder SN + the Π former's
-- reducible-as-type at the decoded output level (the #752 threshold residual, isolated as a premise) ⟹ the Π
-- former's FundamentalConclusionAtDenote. Routes through fundamentalTypeFormerAtDenote; Π former SN is
-- piTyCode_isStronglyNormalizing_of_domain_codomain. Both genFormationPi branches are now premise-complete, the
-- two #672-family walls cleanly isolated: codomain SN (denote SN-040, shared) + Π reducible-as-type (#752).
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationPiAtDenote

-- POSITIVE complement to the obstruction (DenoteKeyedUniverseBoundedCumulativity): in the BOUNDED regime
-- (denote levelExpr env < ambient), the universe candidate is level-STABLE -- universeDenotePredicate reaches
-- lowerAt only at the fixed index denote e, which the below-family coherence (denoteBelowFamily_eq_reducible)
-- rewrites to the bound-independent ReducibleTypeAtDenote env (denote e). universeDenoteCandidate_boundIndependent:
-- the candidate agrees pointwise at two ambient levels both exceeding denote e. universeReducible_withLowerCandidate
-- _atHigher: cumulativity below the bound (same-candidate transport up via ofPointwiseIff). Together with the
-- obstruction witness this pins the EXACT cumulativity boundary (holds iff universe < ambient); the gap regime
-- is the sole residual = exactly what the bound-carrying refactor (#753) excludes by construction. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.universeDenoteCandidate_boundIndependent

-- closedTypeCodeStronglyNormalizingFromFundamentalAtDenote (SN-D6 type-code fragment): a CLOSED subject
-- classified by Type@levelExpr (decoded level < ambient) satisfying the denote FT conclusion at the empty context
-- is strongly normalizing. Composes closedMemberAtDenote (FT conclusion → closed universe membership) with the
-- shipped denote universe-member CR1 stronglyNormalizing_of_universeMemberAtDenote (bound-packaged by levelAbove).
-- The early-win type-code fragment of SN-D6 — subjects that ARE types, where denote CR1 is threshold-free (the
-- general-classifier CR1 carries the denoteBelowFamily neutral-inclusion bound the cumulativity obstruction pins).
-- Conditional only on the (still-blocked) FT conclusion; de-risks SN-D5 without the non-uniform genFormationPi residual.
#assert_no_axioms FX1Poly.Typed.closedTypeCodeStronglyNormalizingFromFundamentalAtDenote

-- SN-D5d (the SN-040-FREE codomain-member wiring — CORRECTS the ticks #18/#19 SN-040 claim): the codomain's
-- universe membership at `cons headTerm σ` (var0 → a domain member, σ tail UN-RENAMED) comes from the codomain
-- IH via ReducibleEnvAtDenote.cons — NO renaming-closure (SN-040). The `cons` (prepend) vs `lift` (weaken-rename)
-- distinction is the whole point. Consequence: the genFormationPi residual UNIFIES to #752 alone (the domain
-- member var0 routes through the A2 bridge = #752; there is NO separate SN-040 Kripke wall).
#assert_no_axioms FX1Poly.Typed.codomainMemberFromIH

-- DenoteKeyedMemberForwardClosed (CR2 for the denote relation, UNCONDITIONAL — first piece of the bounded-CR
-- decomposition toward B1'): every denote-reducible type's candidate is forward-closed under Step on members.
-- Uses only the lowerForwardStep leg (unconditional), never the bounded neutralInclusion. Π arm reduces to the
-- codomain CR2 (no domain candidacy ⟹ no bound); universe arm uses lowerForwardStep. Isolates the level bound
-- to CR1's Π-arm + CR3.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.memberForwardClosed

-- DenoteKeyedMemberWeakHeadExpansion: the inductive BACKBONE of the denote member weak-head expansion (the
-- lambda-arm engine toward SN-043/#672). One induction over ReducibleTypeStepDenote in the GENERAL form
-- (WeakHeadStep source reduct + SN source — the β-specific form breaks at the Π arm), discharging FOUR arms
-- intrinsically (neutral = SN source; universe = the unconditional backward leg; whnf/ofPointwiseIff = IH) and
-- isolating the fifth (piType = the application-SN-spine arm) as an explicit piArm hypothesis — the
-- ofReducibleTypeStepDenote discipline. The lambda FT arm instantiates with source = app (lam body) arg + SN
-- via appLam_isStronglyNormalizing_of_contractum; a proof of piArm alone completes the full member WHE.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.memberWeakHeadExpansionModuloPi

-- DenoteKeyedHeadExpansion (SN-D1): the SPINE-GENERAL head-expansion closure ported from the fuel layer
-- (StratifiedReducibleTypeHeadExpansion.lean:98) onto the denote relation — the lower-risk lambda-arm vehicle
-- (Route Y; spine absorbs the extra app arg via applySpineApp_append, so NO application-SN spine / NO piArm).
-- The parametric form takes a per-level lowerHeadExpand leg; the unconditional ReducibleTypeAtDenote corollary
-- discharges it via denoteBelowFamily_backwardWeakHeadStep on WeakHeadStep.betaSpine — bound-free (vacuous
-- above the bound). Feeds SN-D2 (abstractionMemberAtDenote via the generic DependentArrowCandidate.abstraction).
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepDenote.headExpansionClosed
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtDenote.headExpansionClosed

-- DenoteKeyedAbstractionMember (SN-D2): the denote FT's Π-INTRODUCTION (λ) member arm, the introduction twin
-- of applicationMemberAtDenote. lam body is a denote-reducible MEMBER of Π domainCode codomainCode, assembled
-- in one anonymous constructor: the Π type is reducible with the dependent-arrow candidate via the piType ctor
-- (whose candidate is defeq to DependentArrowCandidate), and λ-membership is the generic
-- DependentArrowCandidate.abstraction fed SN-D1's ReducibleTypeAtDenote.headExpansionClosed for the codomain
-- head-expansion-closure premise. The domain CR1 (domainArgumentsSN) is an explicit premise, deferring the
-- bounded denote CR1 to BRICK 5; the FT supplies it at the ambient classifier level. Feeds SN-D3 (under-subst)
-- and the SN-D5 FT induction's Π-introduction case.
#assert_no_axioms FX1Poly.Typed.abstractionMemberAtDenote

-- DenoteKeyedAbstractionUnderSubst (SN-D3): the FT-shaped under-closing-substitution twin of SN-D2, the
-- introduction counterpart of applicationMemberUnderClosingSubstitution / piFormationUnderClosingSubstitution.
-- subst σ (Π A B) and subst σ (λ body) distribute definitionally (children crossing the binder get lift σ);
-- the codomain/body premises arrive in the FT IH shape (under cons argument σ) and bridge to
-- abstractionMemberAtDenote's subst0 … (lift σ) shape via RawTerm.subst_cons_eq_subst0_lift. The
-- codomainCandidate is pinned explicitly (existentially packaged in the conclusion). Feeds the SN-D5 FT
-- induction's Π-introduction case under the closing substitution.
#assert_no_axioms FX1Poly.Typed.abstractionMemberUnderClosingSubstitution

-- DenoteKeyedFundamentalMotive (SN-D4): the denote FT conclusion motive + the two LEAF member arms. The motive
-- FundamentalConclusionAtDenote uses a SINGLE uniform ambient level (not the per-variable contextLevels vector
-- the fuel route FundamentalConclusionLevelIndexed needed) — the denote relation's level-irrelevance lets one
-- ambient level carry the whole judgment, the binder cons threading the same level. fundamentalVarAtDenote =
-- ReducibleEnvAtDenote.lookupReducible (subst on a variable is the substitution lookup definitionally);
-- fundamentalUniverseFormationAtDenote = universeFormationMemberUnderClosingSubstitution (carries the levelAbove
-- side condition the FT discharges at a large-enough ambient level). The recursive arms (conv/piIntro/piElim/
-- genFormationPi) belong to the SN-D5 induction assembly.
#assert_no_axioms FX1Poly.Typed.fundamentalVarAtDenote
#assert_no_axioms FX1Poly.Typed.fundamentalUniverseFormationAtDenote

-- DenoteKeyedFundamentalPiElim (SN-D5b): the denote FT's Π-elimination (application) dispatcher arm — the first
-- RECURSIVE-arm dispatcher (leaves shipped in SN-D4). Lowest-risk recursive arm: a direct composition of
-- applicationMemberUnderClosingSubstitution with the function + argument sub-conclusions at the SAME closing
-- substitution / environment / uniform ambient level — NO level-bridge (unlike the conv arm, which must extract
-- the target type's reducibility at the ambient level from a universe membership at the decoded level). Feeds
-- the SN-D5 HasTypeDescPi induction's piElim case.
#assert_no_axioms FX1Poly.Typed.fundamentalPiElimAtDenote

-- DenoteKeyedFundamentalConv (SN-D5a): the denote FT's conversion dispatcher arm. The real content is
-- convMemberUnderClosingSubstitution (pushes Conv under σ, transports the member). SOLE RESIDUAL isolated as the
-- explicit reclassifierReducible premise = the target type's reducibility at the AMBIENT level — the single-level
-- motive's genuine obstruction: the reclassifier IH gives reducibility only at the DECODED level (universe
-- membership), and bridging to ambient is the general denote type-level level-irrelevance (A2). No conv-transport
-- produces it directly (reducibility candidates aren't backward-closed under arbitrary Step; convInvariant is
-- determinism-only at both layers). The wiring discharges the premise via the reclassifierTyped IH + the A2
-- universe-membership→ambient bridge (carrying denote levelExpr env < level). piIntro's domain hits the SAME
-- bridge; piElim sidesteps it.
#assert_no_axioms FX1Poly.Typed.fundamentalConvAtDenote

-- DenoteKeyedUniverseMembershipIntro (SN-D5d step (b)): the universe-membership INTRODUCTION — the converse of
-- the A2 decode bridge (#751). universeMembershipIntroAtDenote: a denote-reducible SN type AT its decoded level
-- is a denote-reducible MEMBER of its universe code Type@levelExpr at any higher ambient level. It IS the
-- headline universe candidate (universeMembership_levelIrrelevant, whose decode-set is SN ∧ reducible-at-decoded)
-- repackaged as an intro, no new induction; universeFormationMemberAtDenote is its closed-universe-code instance.
-- fundamentalTypeFormerAtDenote: the type-former FT arm (universeFormation/piFormation/genFormationPi) MODULO
-- route-A reducibility — the closed universe classifier is subst-fixed so the conclusion lands on the intro,
-- isolating the former's TYPE-reducibility (route A / the A2 composite-domain piArm #752) as the single premise,
-- the same isolation discipline fundamentalConvAtDenote uses.
#assert_no_axioms FX1Poly.Typed.universeMembershipIntroAtDenote
#assert_no_axioms FX1Poly.Typed.fundamentalTypeFormerAtDenote

-- DenoteKeyedNonDependentArrow (an unconditional slice of #752): the denote port of the fuel
-- nonDependentArrowOfAllLevelsDomain. A non-dependent arrow domainCode → codomainBase is reducible at ALL denote
-- levels from domain + base-codomain all-levels reducibility ALONE — NO domain-candidate uniformity, NO
-- member-extension, NO piArm. The weaken-cancellation subst0 (weaken codomainBase) arg = codomainBase collapses
-- the piType codomain obligation to the constant base fact, so the (possibly composite/drifting) domain candidate
-- is never consumed per-argument. universeDomainNonDependentArrow is the Type@e → codomainBase instance (reaches
-- past the universe-domain wall). The dependent composite-domain Π stays gated on #752.
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtAllDenoteLevels.nonDependentArrowOfAllLevelsDomain
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtAllDenoteLevels.universeDomainNonDependentArrow

-- DenoteKeyedFundamentalPiIntro (SN-D5c): the denote FT's Π-introduction (λ) dispatcher arm — THE binder crux
-- (the case the per-level route walled on). Canonical-candidate move: domain + codomain candidates are the
-- canonical member predicate IsReducibleMemberAtDenote env level (subst …), so (a) the env-cons arg-membership
-- is direct (candidate = membership predicate) and (b) bodyReducible is direct (codomain candidate = body IH
-- target, no deterministic). Assembled via abstractionMemberUnderClosingSubstitution (SN-D3) + reducibleMemberCandidate
-- + ReducibleEnvAtDenote.cons. UNCONDITIONAL given the three caller premises: domain/codomain reducible-at-level
-- (= A2-bridge-applied IHs) + domain CR1; the body IH is direct. Feeds the SN-D5 induction's piIntro case.
#assert_no_axioms FX1Poly.Typed.fundamentalPiIntroAtDenote

-- DenoteKeyedClosedMember (route-E / SN-D6 precursor): closed-term reducibility from the empty-context denote FT
-- conclusion. Instantiate the FundamentalConclusionAtDenote at the empty context at the IDENTITY substitution +
-- ReducibleEnvAtDenote.empty, then cancel subst identity = id (RawTerm.subst_identity_apply) — yielding the closed
-- subject as a denote-reducible member of its closed classifier. Composed with denote CR1, this is the
-- wire-to-SN step for the closed-term SN headline (SN-043). Fed the eventual unconditional denote FT (#744).
#assert_no_axioms FX1Poly.Typed.closedMemberAtDenote

-- DenoteKeyedTelescopeReducible (SN-D5d first brick): the denote-keyed telescope-reducibility relation, the
-- return type the genFormationPi premise's future fundamentalTelescope companion produces. Single-level denote
-- analogue of the fuel TelescopeReducible (simpler: one ambient level, no +1 scope). nil = vacuous base; twoChild
-- = the Π/Σ-former unfolder (binderShifts [0,1] = consecutiveShifts 0 2). Starts the genFormationPi arm
-- infrastructure (#750); the cons recursion + the genFormationPi connection remain.
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtDenote
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtDenote.nil
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtDenote.twoChild

-- DenoteKeyedTelescopeFundamental (SN-D5d step 1): the telescope FT companion arms that BUILD
-- TelescopeReducibleAtDenote from the typed DescTelescopePi + per-child fundamentals — the denote analogues of
-- the fuel fundamentalTelescopeNilAtAll/fundamentalTelescopeConsAtAll (FundamentalAtAllTelescope), single-level
-- (no ∀ level over the head member). nil = True.intro at count 0; cons = the relation's cons conjunction
-- (head member from headFundamental σ reducibleEnv, subst_universeCodeCell cancelling subst on the closed code;
-- tail passed through). These are the DescTelescopePi.nil/.cons minor-premise bodies the eventual mutual FT
-- recursor discharges; the genFormationPi arm reads the produced telescope for its children's reducibility.
#assert_no_axioms FX1Poly.Typed.fundamentalTelescopeNilAtDenote
#assert_no_axioms FX1Poly.Typed.fundamentalTelescopeConsAtDenote

-- DenoteKeyedUniformReducible (#752 foundation): the uniform-candidate-above-threshold motive
-- UniformlyReducibleAboveDenote — the STRENGTHENING that breaks the piType circularity in the level-irrelevance
-- proof (the all-levels motive's per-level candidate varies; this fixes a single candidate above a threshold, so
-- the piType arm's domain IH supplies a uniform domain candidate that transfers the codomain gate across levels).
-- Three easy backbone arms: ofNeutral (threshold 0, SN candidate, level-independent ctor), ofUniverseCode
-- (threshold denote e, level-independent decode-set via universeMembership_levelIrrelevant), headExpand (rewrap
-- the contractum's uniform candidate via whnfExpand). PLUS the backbone induction ofReducibleTypeStepDenote —
-- a verbatim mirror of the all-levels IsReducibleTypeAtAllDenoteLevels.ofReducibleTypeStepDenote (same 5-arm
-- dispatch, level-independent uniform motive, piType isolated as the piArm hypothesis). REMAINING for #752: the
-- piArm discharge itself — deeper than one motive-swap (the codomain threshold-swap needs a "reducibility bounds
-- a type code's universe level" lemma; see the module header), then the projection to IsReducibleTypeAtAllDenoteLevels.
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote.ofNeutral
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote.ofUniverseCode
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote.headExpand
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote.ofReducibleTypeStepDenote
-- Non-dependent arrow piArm (uniform motive): the UNCONDITIONAL slice of #752. The weaken-cancellation makes
-- the codomain constant in the argument, so the codomain threshold-swap vanishes (Π threshold = domThreshold +
-- codomainThreshold, NOT max — the Nat.le_max_* lemmas leak propext, so + with Nat.le_add_* is the clean route).
-- Correction recorded: the prior "reducibility bounds a type's universe level" idea is FALSE (Type@huge is a
-- reducible type at every level), so the DEPENDENT composite piArm needs a different technique, not a bound lemma.
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote.nonDependentArrow
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote.universeDomainNonDependentArrow
-- The consumable interface: uniform reducibility ⟹ is-a-reducible-type above the threshold (drops the candidate
-- to existence). The face the uniform backbone presents to a consumer (the A2 ambient-level bridge) once the
-- piArm lands. Weaker than IsReducibleTypeAtAllDenoteLevels (below-threshold reducibility is leaf-specific).
#assert_no_axioms FX1Poly.Typed.UniformlyReducibleAboveDenote.isReducibleTypeAboveThreshold
#assert_no_axioms FX1Poly.Typed.denote_domainLevel_le_lmaxAll_pair
#assert_no_axioms FX1Poly.Typed.denote_codomainLevel_le_lmaxAll_pair
