import FX1PolyAudit.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1PolyAudit.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1PolyAudit.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1PolyAudit.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1PolyAudit.Core.Rewriting.Normalize.NormalFormUnique
import FX1PolyAudit.Core.Rewriting.Normalize.Normalize
import FX1PolyAudit.Core.Rewriting.Normalize.NormalizeMeta
import FX1PolyAudit.Core.Rewriting.Normalize.NormalizeSteps
import FX1PolyAudit.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1PolyAudit.Tier0.Context.Instances.Renaming.FxRenamingCategory
import FX1PolyAudit.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1PolyAudit.Typed.Corpus.Progress.ClosedNormalForm
import FX1PolyAudit.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1PolyAudit.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1PolyAudit.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1PolyAudit.Typed.Corpus.Progress.GrownTypeSafety
import FX1PolyAudit.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1PolyAudit.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1PolyAudit.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1PolyAudit.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1PolyAudit.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckApplication
import FX1PolyAudit.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckFormation
import FX1PolyAudit.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckUniverseCode
import FX1PolyAudit.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckVariable
import FX1PolyAudit.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1PolyAudit.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1PolyAudit.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1PolyAudit.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1PolyAudit.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1PolyAudit.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1PolyAudit.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1PolyAudit.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1PolyAudit.Typed.Metatheory.Normalizer.ConvValueDiscrimination
import FX1PolyAudit.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1PolyAudit.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1PolyAudit.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1PolyAudit.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1PolyAudit.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1PolyAudit.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1PolyAudit.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1PolyAudit.Typed.Metatheory.Strengthening.GrownCheck
import FX1PolyAudit.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1PolyAudit.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1PolyAudit.Typed.RegionD.Contested.HasTypeDescDecidable
import FX1PolyAudit.Typed.RegionD.Contested.HasTypeDescPiCheckOfInferred
import FX1PolyAudit.Typed.RegionD.Contested.TypedNbeConvDecision
import FX1PolyAudit.Typed.RegionD.SelfVerification.FormalReviewGate
import FX1PolyAudit.Typed.RegionD.SelfVerification.MechanizedProofCrossReference

/-! # FX1PolyAudit/AuditTypedCheckerInference — region-D aggregator (restructured)

This file's per-declaration zero-axiom gates were redistributed into mirror
shards that literally mirror the `FX1Poly` source tree (one audit file per
source module, each well under 50 eval-commands, so the audit build parallelizes).
This thin aggregator re-imports those shards, conserving every gate and keeping
all existing importers (AuditTyped / AuditModal / AuditAll) resolving unchanged. -/

