import FX1PolyAudit.Dimensions.Collision.DimensionMultiplicationContrast
import FX1PolyAudit.Dimensions.Collision.DimensionRepetitionContrast
import FX1PolyAudit.Dimensions.Collision.FlagshipMultiDimensionSignature
import FX1PolyAudit.Dimensions.Collision.PrecisionOverflowCollision
import FX1PolyAudit.Dimensions.Collision.SoundnessCollisionCatalog
import FX1PolyAudit.Dimensions.Collision.SoundnessCollisionCatalogComplete
import FX1PolyAudit.Dimensions.Collision.SoundnessCollisionSchema
import FX1PolyAudit.Dimensions.Collision.ThreeWayCollisionClassifiedAsyncSession
import FX1PolyAudit.Dimensions.Graded.GradedEvaluation
import FX1PolyAudit.Dimensions.Graded.GradedLogicalConsistency
import FX1PolyAudit.Dimensions.Graded.GradedNormalizerValue
import FX1PolyAudit.Dimensions.Graded.GradedProgress
import FX1PolyAudit.Dimensions.Graded.SelfApplicationUntypable
import FX1PolyAudit.Dimensions.Lattice.LatticeDistributivityClassification
import FX1PolyAudit.Dimensions.Lattice.ProvenanceLatticeDimension
import FX1PolyAudit.Dimensions.Lattice.VersionCategoryDimension
import FX1PolyAudit.Dimensions.Session.SessionCommunication
import FX1PolyAudit.Dimensions.Session.SessionDualityDimension
import FX1PolyAudit.Dimensions.Graded.GradeVector
import FX1PolyAudit.Dimensions.Graded.GradeVectorGeneric
import FX1PolyAudit.Dimensions.Graded.GradedLambdaTerm
import FX1PolyAudit.Dimensions.Security.UsageDiscipline
import FX1PolyAudit.Dimensions.Semiring.GradeSemiringFunctorial
import FX1PolyAudit.Dimensions.Semiring.GradeSemiringMonoidal
import FX1PolyAudit.Dimensions.Semiring.GradeSemiringProduct
import FX1PolyAudit.Axis.Mode.GradeAlgebra.ResourceGraded
import FX1PolyAudit.Axis.Mode.GradeAlgebra.ResourceGradedMore
import FX1PolyAudit.Dimensions.Graded.GradeErasureGeneric
import FX1PolyAudit.Dimensions.Graded.GradedGradeExactness
import FX1PolyAudit.Dimensions.Graded.GradedSubstitutionGeneric
import FX1PolyAudit.Dimensions.Graded.GradedTypingGeneric
import FX1PolyAudit.Dimensions.Graded.GradedWeakeningGeneric
import FX1PolyAudit.Dimensions.Lattice.BoundedJoinSemilatticeProductOrder
import FX1PolyAudit.Dimensions.Lattice.BoundedJoinSemilatticeUniversal
import FX1PolyAudit.Dimensions.Lattice.OverflowLatticeDimension
import FX1PolyAudit.Dimensions.Semiring.ComplexitySemiring
import FX1PolyAudit.Dimensions.Semiring.UnifiedGradeMonoid
import FX1PolyAudit.Axis.Mode.GradeAlgebra.EffectLatticeClassification
import FX1PolyAudit.Dimensions.Graded.GradedBinaryParametricity
import FX1PolyAudit.Dimensions.Graded.GradedCompositionGeneric
import FX1PolyAudit.Dimensions.Graded.GradedFundamentalTheorem
import FX1PolyAudit.Dimensions.Graded.GradedNormalization
import FX1PolyAudit.Dimensions.Graded.GradedReductionConfluence
import FX1PolyAudit.Dimensions.Graded.GradedReductionSubstitution
import FX1PolyAudit.Dimensions.Graded.GradedRelationScaling
import FX1PolyAudit.Dimensions.Graded.GradedSubjectReductionGeneric
import FX1PolyAudit.Dimensions.Graded.GradedSubstitutionAlgebra
import FX1PolyAudit.Dimensions.Graded.SimpleStrongNormalization
import FX1PolyAudit.Dimensions.Graded.SimpleTyping
import FX1PolyAudit.Dimensions.Lattice.ClockDomainLatticeDimension
import FX1PolyAudit.Dimensions.Lattice.MutationChainLatticeDimension
import FX1PolyAudit.Dimensions.Lattice.PreorderDimension
import FX1PolyAudit.Dimensions.Security.FractionalPermission

/-! # FX1PolyAudit/AuditModal — aggregator over the granular audit shards

The former AuditModal gate monolith, now the modal/dimension layer: every gate lives in one of
the imported shard files, which elaborate IN PARALLEL (the monolith serialized them)
and re-elaborate individually on incremental gate edits.  Gate content and counts are
conserved exactly; each shard carries the full import block so namespace-sweep
coverage is unchanged. -/
