import FX1PolyAudit.DependencyAudit
import FX1Poly.Core.Metatheory.Reducibility.Core.DataReducibilityCoverage
import FX1Poly.Core.Metatheory.Reducibility.Candidates.DataTaitCandidate
import FX1Poly.Core.Metatheory.Reducibility.Candidates.FlatCodeTaitCandidate
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FlatCodeCanonicalForms
import FX1Poly.Typed.Ledger.MilestoneASpineValueLayer
import FX1Poly.Typed.Ledger.MilestoneAEliminatorLayerSpine
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimComputingCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicityTyped
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchGeneralBranchCanonicity
import FX1Poly.Typed.Ledger.MetatheoryParityLedger
import FX1Poly.Typed.Engine.Classifier.TypingContext
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeShape
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeConversion
import FX1Poly.Typed.Engine.Formation.SigmaCodeShape
import FX1Poly.Typed.Engine.Formation.ListCodeShape
import FX1Poly.Typed.Engine.Formation.ListFormationSmoke
import FX1Poly.Typed.Engine.Formation.OptionCodeShape
import FX1Poly.Typed.Engine.Formation.OptionCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.OptionFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationOptionFromTelescope
import FX1Poly.Typed.Engine.Formation.OptionFormationSmoke
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDesc
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescDecidable
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElim
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescValidity
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescClosedForms
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFormerTelescopeInversion
import FX1Poly.Typed.Engine.Formation.DataFormerInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescUniqueness
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPi
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaCoherence
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionGrown
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionComputes
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiWeakening
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiSubstitution
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiValidity
import FX1Poly.Typed.Ledger.Misc.ConvCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvBoolCodeRigidity
import FX1Poly.Typed.Engine.Formation.ConvFormationFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvCrossTableFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvDataCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.EmptyTypeCodeConvRigidity
import FX1Poly.Typed.Ledger.Inversion.EmptyTypeValueInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FormationCanonicalForms
import FX1Poly.Typed.Ledger.Inversion.PiTypeFunctionInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalForms
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafety
import FX1Poly.Typed.Engine.Formation.FormationTypeSafety
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsNonVacuity
import FX1Poly.Typed.Corpus.Smoke.GrownBetaRedexInAction
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgress
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownOpenCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafetyUnconditional
import FX1Poly.Typed.Engine.Formation.FormerStepInversionGeneric
import FX1Poly.Typed.Metatheory.SubjectReduction.SubjectReductionAtFormerGeneric
import FX1Poly.Typed.Engine.WfContext.WfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescValidity
import FX1Poly.Typed.Engine.WfContext.WfContextDescUniqueness
import FX1Poly.Typed.Engine.WfContext.WfContextDescPi
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiFromWfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiClassifierValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiFunctionComponentValidity
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionDescPi
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionMutual
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnv
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAt
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvTypeVariable
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprFT
import FX1Poly.Typed.Metatheory.Reducibility.Pi.AbstractionNonDependentUnderSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprReducibleLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermFundamentalLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInversionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprClosureLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermRenameLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1Poly.Typed.Metatheory.SimplyTyped.MilestoneA0SimplyTypedFloor
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1Poly.Tier0.Context.Instances.Renaming.FxRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecIsomorphism
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecPreimage
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTryTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecRMC
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecGlobalSections
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecSconingPreservation
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstVec
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstCategory
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWeakening
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstComprehension
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstSingleton
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstGlobalSections
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWitnessScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstConcreteScone
import FX1Poly.Tier0.Context.IsomorphismCategorical
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeRMC
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeGlobalSections
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1Poly.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1Poly.Core.Rewriting.Reduction.Head.RootStepDispatch
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnce
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1Poly.Core.Rewriting.Normalize.Normalize
import FX1Poly.Core.Rewriting.Normalize.NormalizeSteps
import FX1Poly.Core.Rewriting.Conversion.ConvDecisionSteps
import FX1Poly.Core.Rewriting.Normalize.NormalizeMeta
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsWeakHeadExpansion
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.BoolElimCanonicalComputation
import FX1Poly.Core.Eliminators.Bool.BoolElimClosedMembership
import FX1Poly.Core.Eliminators.Core.DataEliminatorMembershipSmoke
import FX1Poly.Core.Metatheory.Canonicity.SigmaProjectionCanonicalComputation
import FX1Poly.Core.Metatheory.Canonicity.IdentityEliminatorCanonicalComputation
import FX1Poly.Core.Eliminators.Identity.IdEliminatorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.OptionEitherMatchCanonicalComputation
import FX1Poly.Core.Eliminators.Match.MatchClosedMembership
import FX1Poly.Core.Eliminators.Sigma.SigmaProjectionClosedMembership
import FX1Poly.Core.Eliminators.Recursor.RecursorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.RecursiveEliminatorBaseComputation
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.DataCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.ModalCanonicityViaSconing
import FX1Poly.Core.Metatheory.Sconing.DataMetatheoryViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1Poly.Core.Metatheory.Sconing.ConsistencyViaSconing
import FX1Poly.Core.Eliminators.Core.DataEliminatorProgressViaSconing
import FX1Poly.Core.Eliminators.Recursor.RecursiveEliminatorProgressViaSconing
import FX1Poly.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.UnitCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EmptyCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingSubst
import FX1Poly.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1Poly.Core.Metatheory.Normalization.Core.WeakNormalization
import FX1Poly.Core.Rewriting.Normalize.NormalFormUnique
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevels
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllFormerChildren
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPiIntro
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Pi.NeutralFuelStability
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiTypeSaturationReassembly
import FX1Poly.Typed.Metatheory.Reducibility.Pi.StrongNormalizingAllLevelPiComponents
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescopePositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllCanonicalCandidate
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllVectorPremises
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllNonDependentBinders
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtUniformVectorPremises
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFundamentalVectorFromFormation
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFundamentalAtAllFromGenFormation
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClosedLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.TypeFundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LeveledContext
import FX1Poly.Typed.Corpus.Smoke.ClosedSNSmoke
import FX1Poly.Typed.Corpus.Smoke.UntypedOmegaNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.StepNonDeterministic
import FX1Poly.Typed.Ledger.Misc.ConvValueDiscrimination
import FX1Poly.Typed.Corpus.Smoke.TypedLambdaDerivations
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleans
import FX1Poly.Typed.Corpus.Church.Core.TypedChurchNegation
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumerals
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIteration
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralDiscrimination
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralThree
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralTyping
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralInhabitants
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralComputeGeneral
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralAddition
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralMultiplication
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralSemiringLaws
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIsZero
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleanOperations
import FX1Poly.Typed.Corpus.Smoke.TypedFragmentAcyclicity
import FX1Poly.Typed.Corpus.Smoke.UnboundedGrowthNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointDivergence
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointCombinator
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryLogic
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryCompleteness
import FX1Poly.Typed.Corpus.Church.Combinators.SymbolicSCombinatorRule
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairs
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairsInjective
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSums
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsDisjoint
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsGeneral
import FX1Poly.Typed.Corpus.Church.Lists.ChurchLists
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListIsEmpty
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAny
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAll
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBooleanComplementLaws
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBoolXor
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListFirstOr
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSucc
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSuccApplies
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListLength
import FX1Poly.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1Poly.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1Poly.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseNoTop
import FX1Poly.Typed.Metatheory.Universe.TypedUniversePredicative
import FX1Poly.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1Poly.Typed.Corpus.Progress.ClosedNormalForm
import FX1Poly.Typed.Metatheory.Normalizer.ClosedNonConvertibility
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTyping
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiStronglyNormalizingFromFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVecTypeVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConsistency
import FX1Poly.Typed.Engine.Formation.HasTypeFormationNoLambdaApplication
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleSemanticRules
import FX1Poly.Typed.Engine.Formation.ListCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.ListFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberFormation
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeInversion
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeReach
import FX1Poly.Typed.Engine.RuleTables.FlatDescTelescope
import FX1Poly.Typed.Metatheory.Canonicity.Core.StandaloneEngineCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.CombinedBoolCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedBoolCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicitySyntacticRoute
import FX1Poly.Typed.Metatheory.Canonicity.Core.GrownRigidityCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedNatCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimValueCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.NatElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulArithmetic
import FX1Poly.Typed.Metatheory.Reducibility.Core.ClosedNumeralSubstInvariant
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulMul
import FX1Poly.Typed.Corpus.Faithfulness.ValueElimHostFold
import FX1Poly.Typed.Corpus.Faithfulness.RecursorHostFold
import FX1Poly.Typed.Metatheory.Canonicity.Core.ListElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.ListElimFaithfulLength
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicity
import FX1Poly.Typed.Corpus.Progress.GrownClosedNormalClassifierShape
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ClosedNormalEmptyConsistency
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ProductEitherCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.OptionCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ListCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.IdCanonicalForms
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiFormerMembership
import FX1Poly.Typed.Engine.Formation.FormerChildrenReducible
import FX1Poly.Typed.Metatheory.Reducibility.Telescope.TelescopeReducible
import FX1Poly.Typed.Metatheory.Universe.UniverseDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsInduction
import FX1Poly.Typed.Metatheory.Reducibility.Pi.ReducibleTypeAtAllLevelsPiNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsWhnfDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsPiDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsPiMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsHeadExpand
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsConv
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Strengthening.RouteAObstruction
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelDiagnosis
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelMeasure
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibility
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibilitySmoke
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPi
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedLevelIrrelevance
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseFormationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCanonicalMemberCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationFromExistence
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGeneralDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSingleLevelPi
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiAboveThreshold
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormerAtLevel
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleTypeLevelLift
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiArmDischarge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedApplicationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedConvMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberForwardClosed
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMemberBetaExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberWeakHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedAbstractionMember
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAbstractionUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiElim
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalConv
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAmbientLevelBridge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrow
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiIntro
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedClosedMember
import FX1Poly.Typed.Metatheory.Denote.Telescope.DenoteKeyedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedUniformReducible
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMembershipIntro
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFormation
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFromChildMembers
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationSigmaArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedCumulativityObstruction
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibility
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedConvArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiElimArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiIntroArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedFormerEngine
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiDischarge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedAssemblyBridge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeProjection
import FX1Poly.Typed.Engine.Formation.FormerOutputLevelBounds
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedCodomainOpenSN
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDomainInhabitant
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationPiFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationSigmaFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationListFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedTelescopeConsSucc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGrownDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDesc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPi
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPiDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedGrownFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ClosedBoundedReducibleMember
import FX1Poly.Typed.Corpus.Smoke.ClosedStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedNeutralMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseInversion
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBindingTypeReducible
import FX1Poly.Typed.Engine.WfContext.ReducibleEnvOfWfContext
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizingUnconditional
import FX1Poly.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1Poly.Typed.Corpus.Smoke.OpenSNSmoke
import FX1Poly.Typed.Corpus.Progress.ContextValidityFails
import FX1Poly.Typed.Equality.UnitEta.UnitEtaJudgmentalEquality
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruenceGap
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruentEquality
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapse
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseIncompleteness
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeep
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseNeutralBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitNeutralSpineDetection
import FX1Poly.Typed.Equality.UnitEta.UnitSpineDetectionBoundary
import FX1Poly.Typed.Equality.UnitEta.TypeDirectedUnitReadback
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackArgumentBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackFormerChildBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackDeepSpineBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackAnnotationBoundary
import FX1Poly.Typed.Engine.Formation.FormationClassifierRigidity
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeConvDecision
import FX1Poly.Typed.Ledger.Misc.LiftedChildNormalizationFromClosure
import FX1Poly.Typed.Engine.RuleTables.TelescopeSubstitutedChildrenNormalization
import FX1Poly.Typed.Ledger.CascadeFreedomLedger
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyTargetSignature
import FX1Poly.Typed.Ledger.Bridge.CandidateBridgeEditViability
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicityTargetSignature
import FX1Poly.Typed.Metatheory.Universe.NullaryFormerFormation
import FX1Poly.Typed.Metatheory.Universe.GrownUniverseFormationStrictness
import FX1Poly.Typed.Engine.Formation.GrownFormerFormationStrictness
import FX1Poly.Typed.Engine.Classifier.GrownTypingNotUnique
import FX1Poly.Typed.Engine.Classifier.GrownEngineHonesty
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.GrownUniverseConsistency
import FX1Poly.Typed.Engine.Classifier.GrownVariableHonesty
import FX1Poly.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiLamInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiAppInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVarInversion
import FX1Poly.Typed.Metatheory.ContextConversion.VarHeadedAppContextConversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiBetaSR
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiCongruence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerCongruence
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionConditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimReduction
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionValidityReduction
import FX1Poly.Typed.Corpus.Progress.GrownMutualMetatheoryFromPiValidity
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimEquivalence
import FX1Poly.Typed.Engine.HasTypeDescPi.ContextConversion.HasTypeDescPiContextStepConversion
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionUnconditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionFlexibleUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormationFragment
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormerStep
import FX1Poly.Typed.Metatheory.ContextConversion.GenFormerValidityContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPiValidityModelNeutral
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveled
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransport
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransportUnderWf
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledCompleteness
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValid
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRename
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValidLookup
import FX1Poly.Typed.Ledger.Misc.PiElimClassifierConvResidual
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiFormerInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiDataHeadUntyped
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiRootGeneric
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedUniverseBoundedCumulativity
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedClosedTypeCodeSN
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiMemberSN
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrowMemberSN
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCodomainMemberWiring
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelSpike
import FX1Poly.Typed.Ledger.SNStrategy
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.LogRelSpec
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LevelingBridge
import FX1Poly.Typed.Metatheory.Canonicity.Core.ConsistentStratification
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingLevelFlexible
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingRefinedMotive
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingConvArm
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingPiArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingFormerArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingVariableLevelPinned
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalReduction
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalAssembly
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.SimplyTyped.HigherOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiOverNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiNeutralCodomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentlyTypedNeutralDomainFragment
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedSubsumption
import FX1Poly.Typed.Metatheory.Universe.UniverseCumulativity
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermReducibility
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiTypingNonUnique
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckOfInferred
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVariableInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiUniverseCodeInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckUniverseCode
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplicationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckFormation
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationCodomainReTyping
import FX1Poly.Typed.Engine.RuleTables.IntroRuleDesc
import FX1Poly.Typed.Engine.RuleTables.ElimRuleDesc
import FX1Poly.Typed.Engine.RuleTables.GenElimIotaComputation
import FX1Poly.Typed.Engine.Classifier.TypingRoleClassifier
import FX1Poly.Typed.Engine.Classifier.TypingRoleEngineBridge
import FX1Poly.Typed.Engine.Classifier.TypingRoleCoverage
import FX1Poly.Typed.Engine.Classifier.UntypableHeadDecision
import FX1Poly.Typed.Engine.Classifier.TypingHeadKindClassifier
import FX1Poly.Typed.Engine.Classifier.TypedBySomeEngine
import FX1Poly.Typed.Engine.Classifier.GeneratorSemanticTier
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyOverview
import FX1Poly.Typed.Engine.Classifier.StaticTypingSoundness
import FX1Poly.Typed.Engine.Classifier.SemanticTierSoundness
import FX1Poly.Typed.Engine.Classifier.ClassifierRefinement
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyLedger
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionTermination
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerStepDomainFormationCodomain
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionFormerArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionInlineArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionConvOfFormationArms
import FX1Poly.Typed.Metatheory.SubjectReduction.ConsistencyConditionalOnSubjectReduction
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencySyntactic
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyOfPiElimArm
import FX1Poly.Typed.Ledger.Misc.PiElimUpToClassifierConv
import FX1Poly.Typed.Engine.Classifier.ClassifierRespectsConvRefuted
import FX1Poly.Typed.Dimensions.AxisObligation.TypedCertificationStackingRefuted
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencyUnconditional
import FX1Poly.Typed.Engine.Formation.FormationNormalSmoke
import FX1Poly.Typed.Engine.Formation.BoolTypeCodeSubstrate
import FX1Poly.Typed.Engine.Formation.NatTypeCodeSubstrate
import FX1Poly.Typed.Corpus.Progress.GrownNoTypeInType
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescRigidity
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidable
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1Poly.Typed.Ledger.KnownUnsoundnessCorpus
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationAcyclic
import FX1Poly.Dimensions.Security.SecurityNoninterferenceGeneral
import FX1Poly.Dimensions.Graded.GradedApplicationFlow
import FX1Poly.Typed.Ledger.MetatheoryFuzz
import FX1Poly.Typed.Ledger.FuzzCorpusConvertibility
import FX1Poly.Typed.Ledger.FuzzCorpusNormalizes
import FX1Poly.Typed.Ledger.LambdaValueFuzzFamily
import FX1Poly.Typed.Ledger.MechanizedProofCrossReference
import FX1Poly.Typed.Ledger.FormalReviewGate
import FX1Poly.Typed.Ledger.SelfVerifiedMetatheory
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengthening
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheck
import FX1Poly.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1Poly.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiImageComponents
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiRenameImage
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionContext
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiIntro
import FX1Poly.Typed.Engine.Formation.FormationPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.GrownPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimCore
import FX1Poly.Typed.Corpus.Smoke.GrownWfOpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimDispatcher
import FX1Poly.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1Poly.Typed.Metatheory.Strengthening.GuardedPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PlateauPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.NeutralReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionLamClassifierResidual
import FX1Poly.Typed.Metatheory.Strengthening.FlagCoherentReflectionCondition
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationUnique
import FX1Poly.Typed.Ledger.Misc.NeutralClassifierUnique
import FX1Poly.Typed.Ledger.Misc.NormalAppNeutral
import FX1Poly.Typed.Engine.RuleTables.TelescopeUniverseDeterminism
import FX1Poly.Typed.Engine.RuleTables.GenericFormerTelescopeInversion
import FX1Poly.Typed.Metatheory.Universe.NormalUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.ConvUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Strengthening.RenameAlongFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.PinSelectsCallerPair
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.LamReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherentMaster
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedUnionFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.ClosedNativeStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BaseTypeFormationEmptyMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BaseTypeFormationNeutralMembers
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDataMemberExtraction
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.GenericDependentDataElimBridge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBoolElimFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BaseTypeFormationArm
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CumulativeBinderFormationMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseMemberCumulativity
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CumulativeFreeLevelsSupport
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CumulativeFormationRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CumulativeElementFormationRows
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedCarrierAwareArm
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CarrierAwareFlatFormationMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CarrierAwareFlatFormationRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ContentFreeFlatFormationRows
import FX1Poly.Typed.Engine.Formation.FlatFormerStrongNormalization
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ModalityFlatFormationRows
import FX1Poly.Typed.Engine.Formation.TermIndexedFormerStrongNormalization
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.TermIndexedFormationRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.FlatFormationFamilyArm
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CumulativeFormationFamilyArm
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.UnionFormationFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.NullaryIntroRows
import FX1Poly.Typed.Engine.Formation.IntroConstructorStrongNormalization
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.SNNeutralIntroRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.CarrierAwareIntroRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BinderIntroRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.UnionIntroFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.GeneralElimRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.DependentDataElimRows
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedMemberWeakHeadExpansion

/-! # FX1PolyAudit/AuditTypedFundamentalBounded — typed-layer zero-axiom gates: the bounded reducibility fundamental theorem (the canonical SN route)
   (semantic shard of the typed audit; gates classified by declaration topic, appended
   clusters kept together; full import block retained for namespace-sweep coverage) -/

#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationOptionFromTelescopeAtBoundedSucc

-- #753 / SN-D5e BOUND-CARRYING RELATION (DenoteKeyedBoundedReducibility) — the genuine resolution of the
-- obstruction above. ReducibleTypeStepBounded GATES the universeCode arm on denote levelExpr env < bound, so
-- high-universe codes are EXCLUDED from low bounds by construction (universe-label-AWARE, unlike the label-blind
-- ReducibleTypeStepDenote). denoteBelowFamilyBounded keeps the structural (non-WF) recursion ⟹ Quot.sound-free.
#assert_no_axioms FX1Poly.Typed.denoteBelowFamilyBounded_eq_reducible
-- THE PAYOFF: cumulativity is FREE in the gated relation (the property the label-blind model CANNOT prove). A
-- bounded-reducibility derivation lifts from bound to any higherBound ≥ bound with the SAME candidate — universeCode
-- arm re-fires (its gate denote e < higherBound guaranteed by denote e < bound ≤ higherBound) reconciled via
-- ofPointwiseIff (funext-free), every other arm by IH. The keystone the genFormationPi piArm needs.
#assert_no_axioms FX1Poly.Typed.stepBounded_cumulative
#assert_no_axioms FX1Poly.Typed.isReducibleBounded_cumulative
-- THE FORGET BRIDGE (bounded ⊆ denote): a bounded-reducibility derivation IS a denote derivation (drop the gate),
-- so ALL ReducibleTypeStepDenote metatheory (determinism, candidate-shapes, forward-closure, convTransfer, the
-- CR1/2/3 bundle) transfers to the bounded relation WITHOUT re-porting. The leverage lemma for the rest of #753.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.toReducibleTypeStepDenote
-- First fruits of the bridge: determinism transferred (the canonical-candidate reconciliation the bounded FT needs).
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.deterministic
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtBounded.deterministic
-- THE UNCONDITIONAL CR1/CR2/CR3 BUNDLE for the bounded relation. Forward-closure must PRODUCE a bounded
-- (gate-preserving) derivation, so it does NOT transfer through the forget bridge -- it is a direct port
-- (universeCode is a step normal form, gate carried vacuously). The reducibility-candidate bundle is also a
-- direct induction, but here the gate PAYS OFF: at the universeCode arm belowBound : denote e < bound supplies
-- the level bound neutral-inclusion needs, so the FAMILY-level ReducibleTypeAtBounded.isReducibilityCandidate is
-- UNCONDITIONAL -- no predicative caveat (the property the label-blind ReducibleTypeAtDenote could not get).
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.whnfExpandClosure
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.forwardStepStar
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.forwardStep
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.reducibleOfNeutral
#assert_no_axioms FX1Poly.Typed.denoteBelowFamilyBounded_eq_empty_of_ge
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.isReducibilityCandidate
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtBounded.isReducibilityCandidate
-- THE BOUNDED FT FOUNDATIONAL LAYER (DenoteKeyedBoundedReducibleEnv): the bound-carrying member predicate +
-- closing-substitution environment the bounded fundamental theorem consumes. Character-identical to the denote
-- env (DenoteKeyedReducibleEnv) with bound riding where level rode; cons is the Fin-position split + the
-- weakening cancellation. The env the bounded FT uses to discharge the non-uniform genFormationPi piReducibleAsType
-- that the denote relation leaves model-obstructed (DenoteKeyedCumulativityObstruction).
#assert_no_axioms FX1Poly.Typed.IsReducibleMemberAtBounded
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtBounded
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtBounded.lookupReducible
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtBounded.empty
#assert_no_axioms FX1Poly.Typed.ReducibleEnvAtBounded.cons
-- THE BOUNDED FT MOTIVE + LEAF ARMS (DenoteKeyedBoundedFundamentalMotive): the bound-carrying analogue of
-- FundamentalConclusionAtDenote + var/universeFormation, built over the label-AWARE ReducibleTypeAtBounded. The
-- universe-membership machinery (isReducibleAtBounded / membership level-irrelevance) threads the universeCode gate;
-- the universeFormation arm's new gate vs denote is denote e < denote (lsucc e) (denote_lt_lsucc). This is where the
-- bounded FT begins replacing the denote FT, whose non-uniform genFormationPi arm is model-obstructed.
#assert_no_axioms FX1Poly.Typed.universeCode_isReducibleAtBounded
#assert_no_axioms FX1Poly.Typed.universeMembershipBounded_levelIrrelevant
#assert_no_axioms FX1Poly.Typed.FundamentalConclusionAtBounded
#assert_no_axioms FX1Poly.Typed.fundamentalVarAtBounded
#assert_no_axioms FX1Poly.Typed.fundamentalUniverseFormationAtBounded
-- THE BOUNDED FT CONV ARM (DenoteKeyedBoundedConvArm): the bound-carrying analogue of the denote conv member arm +
-- FT arm. convTransfer is a ~3-line FORGET-BRIDGE transfer (bounded forgets to denote at the same lowerAt, and
-- ReducibleTypeStepDenote.convTransfer is lowerAt-parametric) — the canonical economy the forget bridge provides for
-- facts-about-candidates. The FT arm is premise-isolating (carries the A2 ambient-bound reducibility premise).
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtBounded.convTransfer
#assert_no_axioms FX1Poly.Typed.fundamentalConvAtBounded
-- THE BOUNDED FT PI-ELIM ARM (DenoteKeyedBoundedPiElimArm): the bound-carrying application member + FT arm. Unlike
-- the conv arm, the application member's OUTPUT carries a BOUNDED codomain derivation the forget bridge cannot
-- recover, so candidatePiShape is a DIRECT 5-arm induction port (the derivation-producing side of the dichotomy);
-- ReducibleTypeAtBounded.deterministic (bridge-transferred) supplies the argument-candidate alignment.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.candidatePiShape
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtBounded.piTypeInversion
#assert_no_axioms FX1Poly.Typed.applicationMemberAtBounded
#assert_no_axioms FX1Poly.Typed.applicationMemberUnderClosingSubstitutionBounded
#assert_no_axioms FX1Poly.Typed.fundamentalPiElimAtBounded
-- THE BOUNDED FT PI-INTRO ARM (DenoteKeyedBoundedPiIntroArm) — THE BINDER CRUX. The headline: headExpansionClosed
-- is a FORGET-BRIDGE transfer (HeadExpansionClosed candidate is a FACT; ReducibleTypeStepDenote.headExpansionClosed
-- is lowerAt-parametric) fed the bounded leg denoteBelowFamilyBounded_backwardWeakHeadStep (verbatim by-cases port).
-- reducibleMemberCandidate (the choice-free canonical predicate) makes the binder env-cons coordination direct;
-- abstractionMemberAtBounded via DependentArrowCandidate.abstraction; the arm threads ReducibleEnvAtBounded.cons.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtBounded.reducibleMemberCandidate
#assert_no_axioms FX1Poly.Typed.IsReducibleTypeAtBounded.reducibleMemberCandidate
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtBounded.headExpansionClosed
#assert_no_axioms FX1Poly.Typed.abstractionMemberAtBounded
#assert_no_axioms FX1Poly.Typed.abstractionMemberUnderClosingSubstitutionBounded
#assert_no_axioms FX1Poly.Typed.fundamentalPiIntroAtBounded
-- THE BOUNDED FORMER ENGINE (DenoteKeyedBoundedFormerEngine): the universe-membership INTRODUCTION + type-former
-- arm + universe-member SN projection that the bounded universeFormation / genFormationPi arms route through. All
-- three route through the SHIPPED universeMembershipBounded_levelIrrelevant; fundamentalTypeFormerAtBounded isolates
-- the former's type-reducibility (route A) as the single premise — the residual that, in the BOUNDED relation,
-- closes via free cumulativity (stepBounded_cumulative) where the denote relation is model-obstructed.
#assert_no_axioms FX1Poly.Typed.universeMembershipIntroAtBounded
#assert_no_axioms FX1Poly.Typed.fundamentalTypeFormerAtBounded
#assert_no_axioms FX1Poly.Typed.stronglyNormalizing_of_universeMemberAtBounded
-- THE BOUNDED GENFORMATIONPI ARM SKELETON (DenoteKeyedBoundedGenFormationPiArm): the single-level Π toolkit + the
-- premise-isolating arm. piReducibleAtLevelFromComponentsBounded (piType + canonical member-predicate codomain),
-- universeMemberReducibleAsTypeAtDecodedLevelBounded (.2-projection twin of the universe-member SN), the connector,
-- and fundamentalGenFormationPiAtBounded (routes through the former engine; Π-former SN relation-agnostic). The
-- non-uniform piReducibleAsType — model-obstructed in denote — closes via free cumulativity (the next brick).
#assert_no_axioms FX1Poly.Typed.piReducibleAtLevelFromComponentsBounded
#assert_no_axioms FX1Poly.Typed.universeMemberReducibleAsTypeAtDecodedLevelBounded
#assert_no_axioms FX1Poly.Typed.piReducibleAsTypeFromComponentReducibilityBounded
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationPiAtBounded

-- THE PAYOFF (DenoteKeyedBoundedGenFormationPiDischarge): the bound-carrying piReducibleAsType DISCHARGE variants.
-- piReducibleAsTypeFromNonUniformLevelMemberBounded closes the model-obstructed non-uniform case (a child classified
-- STRICTLY below the Π output universe) via isReducibleBounded_cumulative -- the free bounded cumulativity decode-
-- then-lift the denote relation cannot do (DenoteKeyedCumulativityObstruction). Uniform is its Nat.le_refl instance.
-- The universe-code variants discharge anti-vacuously via the GATED universeCode_isReducibleAtBounded (strict-below
-- hypotheses). fundamentalGenFormationPiUniverseUniverseAtBounded = the FIRST fully-discharged bounded genFormationPi
-- arm (Π (A : Type@a). Type@b), all three premises of fundamentalGenFormationPiAtBounded closed.
#assert_no_axioms FX1Poly.Typed.piReducibleAsTypeFromNonUniformLevelMemberBounded
#assert_no_axioms FX1Poly.Typed.piReducibleAsTypeFromUniformLevelMemberBounded
#assert_no_axioms FX1Poly.Typed.piReducibleAsTypeFromUniverseDomainCodomainReducibilityBounded
#assert_no_axioms FX1Poly.Typed.piReducibleAsTypeFromUniverseCodeComponentsBounded
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationPiUniverseUniverseAtBounded

-- THE A2 BRIDGE + WIRED CONV ARM (DenoteKeyedBoundedAssemblyBridge): toward the bounded grown-FT assembly. The
-- recursor arms extract a reducible-TYPE-at-bound from a universe-MEMBERSHIP IH -- now a clean cumulativity
-- composition (universeMemberReducibleAsTypeAtDecodedLevelBounded then isReducibleBounded_cumulative via Nat.le_of_lt).
-- reducibleTypeAtBoundUnderSubstFromMembershipBounded is the under-subst wrapper; fundamentalConvArmBounded wires the
-- conv recursor arm (fundamentalConvAtBounded composed with the bridge). The piIntro arm additionally needs member->SN
-- (CR1) at arbitrary scope, blocked by ReducibleTypeAtBounded.isReducibilityCandidate being at scope+1 -- the next residual.
#assert_no_axioms FX1Poly.Typed.reducibleTypeAtBoundFromUniverseMemberBounded
#assert_no_axioms FX1Poly.Typed.reducibleTypeAtBoundUnderSubstFromMembershipBounded
#assert_no_axioms FX1Poly.Typed.fundamentalConvArmBounded

-- Bounded CR1 in member form at the non-empty closing scope (scope+1) -- the piIntro arm's domainArgumentsSN discharge.
-- The bounded reducibility-candidate bundle is at scope+1 (arrow-CR1 var-0 inhabitant), exactly the scope the FT closes
-- into; arbitrary-scope member-SN is structurally blocked (the same var-0 wall in denote too -- denote escapes by keying
-- CR1 on a positive fuel LEVEL, scope-general). The wired piIntro arm consumes this once its motive closes into scope+1.
#assert_no_axioms FX1Poly.Typed.stronglyNormalizing_of_memberAtBoundedSucc

-- THE +1-CLOSING MOTIVE + the piIntro arm with domainArgumentsSN AUTO-DISCHARGED. The grown-FT assembly must close
-- into a non-empty scope targetScope+1 so the binder arm reads member->SN via the scope+1 bounded CR1. FundamentalConcl
-- usionAtBoundedSucc is that motive; .toSucc lifts the shipped arbitrary-scope arms (var/conv/universeFormation/piElim/
-- genFormationPi -- no binder) into it for free; fundamentalPiIntroAtBoundedSucc is the last binder-specific arm, its
-- domainArgumentsSN premise ELIMINATED (discharged internally by stronglyNormalizing_of_memberAtBoundedSucc at the +1 scope).
#assert_no_axioms FX1Poly.Typed.FundamentalConclusionAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.FundamentalConclusionAtBounded.toSucc
#assert_no_axioms FX1Poly.Typed.fundamentalPiIntroAtBoundedSucc

-- The +1-closing conv + piElim recursor arms (+ the +1 A2 bridge). Mechanical mirrors of the shipped arbitrary-scope
-- arms at the targetScope+1 substitution -- the member-level lemmas (convMember.../applicationMember...) are scope-
-- parametric. With fundamentalPiIntroAtBoundedSucc, the grown-FT arms conv/piIntro/piElim are now all +1-available;
-- only the genFormationPi +1-arm + the formation FT + the HasTypeDescPi.rec dispatch remain.
#assert_no_axioms FX1Poly.Typed.reducibleTypeAtBoundUnderSubstFromMembershipBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalConvArmBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalPiElimAtBoundedSucc

-- The +1-closing former engine + genFormationPi arm. Mirrors of fundamentalTypeFormerAtBounded / fundamentalGenForm
-- ationPiAtBounded over the +1 motive (universeMembershipIntroAtBounded + piTyCode SN are scope-parametric/relation-
-- agnostic). With these, ALL FIVE grown-FT arms (conv/piIntro/piElim/genFormationPi + ofFormation premise) are now
-- +1-available; only the HasTypeDescPi.rec dispatch (motive_2 telescope + bound-exceeds-levels threading) + the
-- formation FT remain before the SN-043 wire.
#assert_no_axioms FX1Poly.Typed.fundamentalTypeFormerAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationPiAtBoundedSucc

-- GATE EXTRACTION -- dissolves the bound-threading. The bounded universeCode arm carries belowBound (denote levelExpr
-- env < bound) as a gate; read backwards, a bound-reducible universe code FORCES that gate. So each grown-FT recursor
-- arm recovers its belowBound LOCALLY from a sub-derivation's reducibility (intro the closing substitution, apply the
-- universe-typing IH, extract) -- NO global "bound exceeds every level in subject" invariant needed. The spine is a
-- 5-arm induction (candidatePiShape style): universeCode carries it, whnfExpand/neutral/piType impossible, ofPointwiseIff recurses.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeStepBounded.belowBoundOfUniverseCodeShape
#assert_no_axioms FX1Poly.Typed.universeCodeReducibleAtBounded_belowBound

-- Bound-carrying telescope-reducibility relation (DenoteKeyedBoundedTelescopeReducible.lean) — the motive_2
-- shape for the grown-FT HasTypeDescPi.rec dispatch. The bound-carrying analogue of TelescopeReducibleAtDenote,
-- carrying TWO nat levels: `bound` (each child head a bound-reducible member of its universe code) and `argLevel`
-- (the tail's domain argument quantification level = the former's decoded output level, strictly below `bound` by
-- gate-extraction). twoChild is the Π/Σ-former unfolder (consecutiveShifts 0 2), the shape the bounded
-- genFormationPi arm reads domain/codomain reducibility off before lifting via free bounded cumulativity.
-- Structural-recursion def on `count` + nil (True.intro) + twoChild (anonymous conjunction constructor).
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtBounded
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtBounded.nil
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtBounded.twoChild

-- Bound-carrying telescope fundamental-theorem companion arms (DenoteKeyedBoundedTelescopeFundamental.lean) — the
-- nil/cons minor-premise bodies that PRODUCE TelescopeReducibleAtBounded, the bound-carrying analogue of
-- fundamentalTelescopeNil/ConsAtDenote. nil is True.intro; cons reads the head member off its
-- FundamentalConclusionAtBounded (head member at `bound` via subst_universeCodeCell) and threads the tail premise
-- (argument at `argLevel`). Non-recursive minor-premise bodies the eventual HasTypeDescPi/DescTelescopePi FT
-- recursor discharges; no induction, no funext.
#assert_no_axioms FX1Poly.Typed.fundamentalTelescopeNilAtBounded
#assert_no_axioms FX1Poly.Typed.fundamentalTelescopeConsAtBounded

-- Two-child bounded telescope projection (DenoteKeyedBoundedTelescopeProjection.lean) — reads the domain +
-- codomain bound-reducible universe-members off the depth-0/count-2 Π/Σ telescope in the EXACT shape
-- piReducibleAsTypeFromNonUniformLevelMemberBounded consumes; codomain reshaped subst(cons)→subst0(subst(lift))
-- via RawTerm.subst_cons_eq_subst0_lift. The telescope→discharge bridge for the genFormationPi recursor arm.
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtBounded.twoChildMembers
-- GTL-11 bounded substrate: the one-child [0] data-former analogue (listCode / optionCode) — a pure
-- telescope.1 projection (no codomain reshaping, the data former is non-dependent), feeding the bounded
-- genFormationPi data-former arm.
#assert_no_axioms FX1Poly.Typed.TelescopeReducibleAtBounded.oneChildMember

-- Π/Σ-former output-level bounds (FormerOutputLevelBounds.lean) — the genFormationPi belowOutput premises:
-- each child level ≤ the former's lmaxAll output level. lmaxAll [a,b] = lmax a b (definitional fold collapse);
-- denote_lmax → structural levelMax; levelMax_le_left/right re-derived (the ClassifierLevelMeasure ones are
-- file-private). Feeds piReducibleAsTypeFromNonUniformLevelMemberBounded's domainBelowOutput/codomainBelowOutput.
#assert_no_axioms FX1Poly.Typed.levelMax_le_left
#assert_no_axioms FX1Poly.Typed.levelMax_le_right

-- Open-codomain SN from a bounded FILLED codomain member (BoundedCodomainOpenSN.lean) — the genFormationPi
-- codomainSN premise. The bounded telescope gives the codomain filled at an argument (subst0 (subst (lift σ)
-- codomain) arg); bounded CR1 (stronglyNormalizing_of_memberAtBoundedSucc) → SN of the instance; the
-- relation-agnostic IsStronglyNormalizing.ofSubst0Body reflects it to the OPEN body subst (lift σ) codomain.
-- The hardest sub-piece of the genFormationPi recursor arm (BFT-4), via shipped primitives only.
#assert_no_axioms FX1Poly.Typed.codomainOpenStronglyNormalizing_ofBoundedFilledMember

-- Last two genFormationPi recursor-arm prerequisites (BoundedDomainInhabitant.lean): levelMax_lt (the output
-- belowBound — max of two below-bound child levels is below bound, via LevelExpr.levelMax_le); and
-- variableZeroMemberOfBoundedUniverseMember (the var-0 neutral inhabits the cumulatively-lifted domain candidate
-- at argLevel: decode universe member → reducible type at its level → isReducibleBounded_cumulative lift →
-- IsReducibilityCandidate.containsVariable). The argument the genFormationPi arm feeds the codomain telescope.
#assert_no_axioms FX1Poly.Typed.levelMax_lt
#assert_no_axioms FX1Poly.Typed.variableZeroMemberOfBoundedUniverseMember

-- The bounded genFormationPi recursor arm (BoundedGenFormationPiFromTelescope.lean) — a two-child Π/Σ former is a
-- +1-closing fundamental member of Type@(lmaxAll levels) from the telescope IH. Builds the universe member INSIDE
-- the ∀ (resolving the belowBound threading: every level bound extracted per-substitution, no canonical env),
-- lifting children to the output level by free bounded cumulativity (the non-uniform case). Composes ALL the BFT
-- pieces: twoChildMembers + gate-extraction + variableZeroMember + levelMax_lt + belowOutput + codomainOpenSN +
-- piReducibleAtLevelFromComponentsBounded + universeMembershipIntroAtBounded. The hardest dispatch arm.
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationPiFromTelescopeAtBoundedSucc

-- The +1-closing cons telescope companion (BoundedTelescopeConsSucc.lean) — the cons recursor-arm body for the
-- bounded grown-FT motive_2. Mirrors fundamentalTelescopeConsAtBounded but the head child's IH is the +1-closing
-- FundamentalConclusionAtBoundedSucc (the recursor's motive_1) and the closing substitution targets targetScope+1.
-- Reads the head member off the +1 conclusion (subst_universeCodeCell cancels the closed-code substitution) and
-- threads the tail premise — uniform in argLevel (the dispatch instantiates it to the former's decoded level).
#assert_no_axioms FX1Poly.Typed.fundamentalTelescopeConsAtBoundedSucc

-- Member cumulativity (bound-carrying) (DenoteKeyedBoundedReducibleEnv.lean) — a bound-reducible member at
-- lowerBound is one at any higherBound ≥ lowerBound, SAME candidate (the type relation lifts by
-- stepBounded_cumulative, which preserves the candidate; the membership witness carries over). The member analogue
-- of isReducibleBounded_cumulative; reconciles the bounded telescope's argument level (the former's decoded OUTPUT
-- level, used by twoChildMembers) with the uniform environment bound in the grown-FT consTelescope dispatch arm.
#assert_no_axioms FX1Poly.Typed.IsReducibleMemberAtBounded.cumulative

-- The Σ twin of BFT-4 (BoundedGenFormationSigmaFromTelescope.lean) — a two-child Σ former is a +1-closing
-- fundamental member of Type@(lmaxAll levels) from the SAME telescope IH. Σ is classified by the relation's
-- `neutral` arm (SN candidate; no sigmaType arm), so the former reducible-as-type needs only former SN, NOT the
-- per-component cumulative lifts the Π arm needs; domain/codomain SN + level bounds + var-0 instantiation are
-- identical to the Π arm. The Σ-branch body of the eventual HasTypeDescPi.rec dispatch (BFT-6) + formation FT.
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationSigmaFromTelescopeAtBoundedSucc
-- GTL-11 bounded reassembly: the 1-child listCode data-former twin (non-dependent; neutral SN-candidate path,
-- lmaxAll [elementLevel] = elementLevel collapses the level bookkeeping). The bounded analogue of
-- listCodeFormationUnderSubst; the last reassembly piece before the atomic landing.
#assert_no_axioms FX1Poly.Typed.fundamentalGenFormationListFromTelescopeAtBoundedSucc

-- The bounded grown-engine fundamental theorem BFT-6 (BoundedGrownDispatch.lean) — the HasTypeDescPi.rec dispatch
-- with motive_1 = FundamentalConclusionAtBoundedSucc, motive_2 = IsTelescopeReducibleAtBoundedSucc (the +1
-- telescope wrapper carrying the argLevel≤bound cumulativity gate), conditional on a bounded HasTypeDesc formation
-- premise. Pure assembly of shipped arms: ofFormation[premise]/conv[inline]/piIntro/piElim/genFormationPi
-- [BFT-4 Π + Σ-twin, double-applying premisesFundamental to gate-extract output<bound]/nil/consTelescope[cons
-- companion + member cumulativity]. The +1-closing analogue of the denote HasTypeDescPi.fundamentalVectorFromFormation.
#assert_no_axioms FX1Poly.Typed.IsTelescopeReducibleAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.fundamentalAtBoundedSuccFromFormation

-- The bounded formation leaf arms (BoundedFormationLeafArms.lean) — the +1-closing var (BFT-7) and
-- universeFormation (BFT-9) arms of the bounded FORMATION FT (HasTypeDesc.rec dispatch). Each is the
-- FundamentalConclusionAtBounded.toSucc lift of the shipped arbitrary-scope leaf arm (no binder); the
-- universeFormation arm threads belowBound : denote (lsucc levelExpr) env < bound (the per-term gate the dispatch
-- supplies). The conv arm (BFT-8) is already fundamentalConvArmBoundedSucc; genFormation (BFT-10) reuses BFT-4+Σ-twin.
#assert_no_axioms FX1Poly.Typed.fundamentalVarAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalUniverseFormationAtBoundedSucc

-- The per-derivation universe-level budget (BoundExceedsDesc.lean) — the BFT-11/12 fuel. An INDUCTIVE Prop family
-- indexed by the HasTypeDesc derivation (a budget FUNCTION over the Prop derivation would be large elimination,
-- forbidden), mutual with the telescope budget. `bound` exceeds the denoted lsucc-level of every universeFormation
-- leaf; conv/genFormation carry sub-budgets by construction (sidestepping a term-syntactic budget's inner-classifier
-- obstruction). Foundation for the bounded formation FT dispatch (BFT-11) + the ∃-bound discharge (BFT-12).
#assert_no_axioms FX1Poly.Typed.BoundExceeds

-- The bounded FORMATION-engine fundamental theorem (BoundedFormationDispatch.lean, BFT-10 + BFT-11). Discharges the
-- formationFundamental premise shape of BFT-6: given a BoundExceeds budget, every HasTypeDesc formation derivation
-- satisfies FundamentalConclusionAtBoundedSucc. Proved by BoundExceeds.rec (induction on the BUDGET, not the
-- derivation) so the universeFormation arm receives belowBound NAMED — sidestepping the opaque-outputType-index
-- inversion that blocks a match on the budget. IsFormationTelescopeReducibleAtBoundedSucc is the DescTelescope
-- motive_2 wrapper (BFT-10).
#assert_no_axioms FX1Poly.Typed.IsFormationTelescopeReducibleAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.fundamentalAtBoundedSucc

-- The UNCONDITIONAL (up to budget) grown FT (BoundedGrownFundamental.lean, BFT-12c). Given a BoundExceedsPi budget,
-- every HasTypeDescPi derivation satisfies FundamentalConclusionAtBoundedSucc. Via BoundExceedsPi.rec: the
-- ofFormation arm feeds the carried embedded BoundExceeds into HasTypeDesc.fundamentalAtBoundedSucc (BFT-11),
-- discharging BFT-6's formationFundamental premise inline; every other arm mirrors BFT-6 (budgets unused). With
-- BoundExceedsPi.existsBound (BFT-12b) this is one closed-corollary step (BFT-13) from SN-043.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.fundamentalAtBoundedSucc

-- The closed-term bounded-reducibility corollary (ClosedBoundedReducibleMember.lean, BFT-13). Composes
-- BoundExceedsPi.existsBound (BFT-12b) → HasTypeDescPi.fundamentalAtBoundedSucc (BFT-12c) → the empty-context env
-- witness, instantiated at the unique closing substitution Fin.elim0 : RawTermSubst 0 1. Turns the
-- budget-conditional grown FT into an UNCONDITIONAL closed-reducibility fact; feeds the member→SN bridge (BFT-14).
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedBoundedReducibleMember

-- TYTAB-4 step 3 (BoundedUnionFundamental.lean): the NATIVE union fundamental theorem, conditional on the three
-- table-arm FTs. The BoundExceedsUnion.rec dispatch (induction on the budget, mirroring the grown
-- BoundExceedsPi.rec): the four STRUCTURAL arms discharged inline (ofGrown→the grown master above; conv→the
-- verbatim grown conv block; var/universeFormation→the shipped leaf FTs fed the budget's belowBound gate), the
-- three TABLE arms (formationRule/intro/elim) taken as explicit FT premises — exactly as the grown
-- fundamentalAtBoundedSuccFromFormation took its single formationFundamental premise. Step 4 discharges the three
-- premises at the kernel bundle (the FTGEN-bounded construction); step 5 reflects the closed instance to native SN.
#assert_no_axioms FX1Poly.Typed.HasTypeUnionOver.fundamentalAtBoundedSuccFromTableArms

-- TYTAB-4 step 5 (ClosedNativeStronglyNormalizing.lean): the NATIVE closed-term SN reflection, conditional on the
-- three table-arm FTs (threaded ∀ env bound-polymorphic). The native twin of HasTypeDescPi.closedStronglyNormalizing:
-- BoundExceedsUnion.existsBound → fundamentalAtBoundedSuccFromTableArms at the unique closing substitution Fin.elim0
-- (empty-context env witness ReducibleEnvAtBounded.empty) → scope+1 bounded CR1 (stronglyNormalizing_of_member-
-- AtBoundedSucc) → SN-reflection through the weakening (StepStar.stronglyNormalizing_of_subst). Supplies gate 1
-- (nativeStronglyNormalizing) of native consistency (#1697); unconditional once step 4's three premises land.
#assert_no_axioms FX1Poly.Typed.HasTypeUnionOver.closedStronglyNormalizingFromTableArms

-- TYTAB-4 step 4 (BaseTypeFormationEmptyMember.lean): the FIRST discharged case of the native formationFundamental
-- premise — the baseType sub-family's emptyCode case. The substantive empty type emptyTypeCell is a bound-reducible
-- member of Type@0 under any closing substitution, given 0 < bound (from the formation level gate). Nullary base
-- code: empty obligations + empty children sidestep the telescope/foldChildren/binder apparatus entirely;
-- universeMembershipIntroAtBounded over (denote_lzero bound + noStep-SN via Step.no_step_from_emptyCode +
-- ReducibleTypeStepBounded.dataEmpty). The formation FT obligation for the very type whose uninhabitedness is the
-- consistency keystone of #1697.
#assert_no_axioms FX1Poly.Typed.fundamentalBaseTypeEmptyCodeAtBoundedSucc

-- TYTAB-4 step 4 / FTGEN-6 (BaseTypeFormationNeutralMembers.lean): the OTHER four discharged base-type cases —
-- Bool / Nat / Unit / Interval. Each is a closed nullary type-former leaf (mkGen gen_XCode () childNil), reducible
-- AS A TYPE via the neutral arm with the SN Tait candidate (NOT flat — isFlatDataCode is false for these); the
-- five neutral gates close by rfl/nomatch. The generic helper fundamentalNeutralBaseCodeAtBoundedSucc carries the
-- work once over a scope-polymorphic cell family; the four instances are thin instantiations. Together with the
-- emptyCode case, all five base-type formation members are discharged (the dispatching base-type arm is next).
#assert_no_axioms FX1Poly.Typed.fundamentalNeutralBaseCodeAtBoundedSucc
-- Bool moved off `neutral`: gen_boolCode is now a canonical data code (isFlatDataCode = true), so its
-- type-reducibility is the canonical-forms candidate `dataTaitCandidate boolIsValue` via the `dataFlat` arm
-- (the candidate the dependent boolElim decomposes), through `fundamentalFlatDataBaseCodeAtBoundedSucc`.
-- Bool AND Nat now ride `dataFlat` (DEP-NAT-MODEL added `gen_natCode` to `isFlatDataCode` carrying the
-- RECURSIVE `IsNatStructured` predicate); Unit/Interval remain on the neutral SN candidate.
#assert_no_axioms FX1Poly.Typed.fundamentalFlatDataBaseCodeAtBoundedSucc
-- The DEP-MODEL scrutinee bridge: a bounded member of boolTypeCell is a member of `dataTaitCandidate
-- boolIsValue` (the candidate the dependent boolElim Core member consumes), by `dataFlat` + determinism.
#assert_no_axioms FX1Poly.Typed.boolMemberAtBounded_dataTaitCandidate
-- DEP-NAT-MODEL: the nat analogue — a bounded member of natTypeCell is a member of `dataTaitCandidate
-- IsNatStructured` (the recursive candidate the dependent natElim/natRec Core members consume), by the same
-- `dataFlat` + determinism transfer.  The scrutinee bridge feeding the DEP-NAT-WIRE bounded engine.
#assert_no_axioms FX1Poly.Typed.natMemberAtBounded_dataTaitCandidate
-- DEP-BOOL-BRIDGE: the bounded DEPENDENT boolElim FT engine (boolElim analogue of fundamentalPiElimAtBoundedSucc).
-- The core-bounded member arm + the +1-closing FT arm: result-type reducibility from the motive's universe
-- membership at the scrutinee-extended env (A2 + subst_cons_eq_subst0_lift), branches transferred along the
-- dependent codomain's lockstep reduction (StepStar.subst0Argument + memberConvAtBounded).
#assert_no_axioms FX1Poly.Typed.boolElimMemberAtBounded
-- The generic dependent-eliminator result-type recovery (shared motive-side plumbing every dependent data
-- eliminator bridge reuses; extracted from the inlined bool steps, relocates to the neutral generic-bridge file).
#assert_no_axioms FX1Poly.Typed.dependentMotiveResultTypeReducibleAtBounded
-- The generic per-branch transfer along the scrutinee's reduction to a constructor value (subst0Argument +
-- memberConvAtBounded); reused by every dependent data-eliminator value handler.
#assert_no_axioms FX1Poly.Typed.branchMemberTransferAlongScrutineeReduction
-- The generic dependent-eliminator motive under-binder SN (the one ROW premise not on a sub-conclusion: fill
-- the scrutinee binder with its reducible member, reshape, reflect open-body SN); reused by every elim row.
#assert_no_axioms FX1Poly.Typed.dependentMotiveUnderBinderStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.fundamentalBoolElimAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBaseTypeBoolCodeAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBaseTypeNatCodeAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBaseTypeUnitCodeAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBaseTypeIntervalCodeAtBoundedSucc

-- TYTAB-4 step 4 / FTGEN-6 (BaseTypeFormationArm.lean): the base-type sub-family ARM — dispatch a base-type table
-- hit (baseTypeRuleDescOf generator = some baseRule) to its per-code member. baseTypeRuleTableHitIsNullaryBaseCode
-- pins the generator (5-way, no 200-way cases Generator); baseTypeRuleTableOutputIsType0 collapses the output to
-- Type@0; each branch subst+cases children, the payload eta-unifies to (), and the matching member closes. The
-- substantive base-type sub-family of the native formationFundamental premise (modulo the trivial formationRuleOf
-- bundle bridge left for the assembly brick).
#assert_no_axioms FX1Poly.Typed.fundamentalBaseTypeRowAtBoundedSucc

-- OB-1 (BoundedNeutralMember.lean): a variable is a bound-reducible member of any bound-reducible type. The
-- candidate is an unconditional reducibility candidate (ReducibleTypeAtBounded.isReducibilityCandidate) and a
-- variable joins it by CR3 (neutralExpansion) with a vacuous reduct premise (noStep_var). The member-side leaf the
-- neutral/identity closing environment (reducibleEnvOfWfContext, OB-3) cons-feeds at every context position — the
-- first brick discharging the OpenStronglyNormalizing residual toward UNCONDITIONAL open SN-043 (#546).
#assert_no_axioms FX1Poly.Typed.IsReducibleMemberAtBounded.ofVariable

-- CAN-6 / FLAT-CANON (#936) PAYOFF (FlatCodeCanonicalForms): the SECOND §5 candidate-bridge pin harvested.
-- Non-vacuity (every flat-rooted cell is bounded-reducible via the dataFlat arm); the flat candidate bridge
-- (family determinism pins ANY candidate to dataTaitCandidate (flatCodeValuePredicate root) — before the
-- edit the neutral arm collapsed it onto the whole SN set); the member identity; and per-code CLOSED
-- canonicity: a closed candidate member of a product cell reduces to a PAIR, of an either cell to an
-- inl/inr injection, and the sum lane (no intro generators — empty value predicate, honest) has NO closed
-- member. MODEL-level (sconing leg): connecting ENGINE-typed members is future work, stated, not absorbed.
#assert_no_axioms FX1Poly.Typed.flatCode_isReducibleTypeAtBounded

-- TYTAB-4 step 4 (CumulativeBinderFormationMember.lean): the binder-crossing telescope bridge + the Π/Σ cumulative
-- formation FT members — the genuinely dependent cases of the native formationFundamental premise. The bridge
-- twoChildFormationTelescopeAtBoundedSucc re-assembles the two flat obligation IHs (domain at context, codomain at
-- context.cons domain) into the TelescopeReducibleAtBounded the shipped from-telescope arms consume; the Π/Σ
-- circularity (lifting the telescope's argument from argLevel to bound needs the codomain bound, which needs the
-- cons-environment, which needs the lift) is broken with a variable-0 inhabitant at bound (domainLevel ≤ bound only)
-- that fires the codomain IH to read off codomainBelowBound, then levelMax_lt gives argLevel < bound. The two member
-- lemmas compose the bridge with fundamentalGenFormation{Pi,Sigma}FromTelescopeAtBoundedSucc, proving the bridge is
-- consumed and giving the dependent former's formation FT at output lmaxAll [domainLevel, codomainLevel].
#assert_no_axioms FX1Poly.Typed.twoChildFormationTelescopeAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativePiMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativeSigmaMemberAtBoundedSucc

-- TYTAB-4 step 4 (BoundedUniverseMemberCumulativity.lean): member-level universe cumulativity — a bound-reducible
-- member of Type@lowerLevel is a member of Type@higherLevel when denote lowerLevel env <= denote higherLevel env <
-- bound. The decoupler for the free-levels formation discharge: the cumulative Π/Σ formation members are built at
-- the component obligation levels, and the native formationFundamental premise's output universe Type@(lmaxAll
-- levels) carries an arbitrary (>= the obligation levels) levels list — this lemma lifts the member the rest of the
-- way. SN transfers unchanged (level-independent); only the reducible-as-type leg moves, by free bounded
-- cumulativity, exactly as the type-level universe cumulativity does.
#assert_no_axioms FX1Poly.Typed.universeMemberCumulativeAtBounded

-- TYTAB-4 step 4 (CumulativeFreeLevelsSupport.lean): the free-levels arithmetic + classifier-lift wrapper. The
-- native formationFundamental premise quantifies the level list FREELY, so the cumulative output universe
-- Type@(lmaxAll levels) carries an arbitrary levels list while the obligations sit at the first one/two levels (or
-- forced Type@0). denote_le_lmaxFold (the fold is monotone in its accumulator) + denote_lmaxFold_lt (the fold stays
-- below the bound) supply the lift's two premises; fundamentalConclusion_universeCumulative is the per-substitution
-- application of universeMemberCumulativeAtBounded that raises an obligation-level member to the free output universe.
#assert_no_axioms FX1Poly.Typed.denote_le_lmaxFold
#assert_no_axioms FX1Poly.Typed.denote_lmaxFold_lt
#assert_no_axioms FX1Poly.Typed.fundamentalConclusion_universeCumulative

-- TYTAB-4 step 4 (CumulativeFormationRows.lean): the Π / Σ cumulative formation FT rows over the native
-- obligation-list form + FREE levels — the cumulative sub-family's binder-crossing half of the native
-- formationFundamental premise. The subject is the generic mkGen generator payload children (children the Π/Σ binder
-- spine); the obligation IHs come as the single ∀ obligation ∈ cumulativeFormationObligations list; the level list is
-- free, so the output is Type@(lmaxAll levels). Three-way levels dispatch (real / forced-lzero-short / forced-lzero-
-- empty) lands fundamentalCumulative{Pi,Sigma}MemberAtBoundedSucc at the obligation levels and lifts to the free
-- output universe. The genuinely dependent cumulative formers' formation FT, ready to feed the .cumulative slice of
-- the formationFundamental assembly.
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativePiRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativeSigmaRowAtBoundedSucc

-- TYTAB-4 step 4 (CumulativeElementFormationRows.lean): the List / Option cumulative formation FT rows — the
-- NON-binder-crossing half of the cumulative sub-family. Single-child spine [0]: the element sits at the ambient
-- scope, so the telescope bridge (oneChildFormationTelescopeAtBoundedSucc) is the trivial cons-over-nil (no
-- variable-0 inhabitant, no argument lift). The members feed it to the shipped List/Option from-telescope arms; the
-- rows lift to the native obligation-list form + FREE levels (two-way dispatch: real element level / forced-lzero
-- empty), landing fundamentalCumulative{List,Option}MemberAtBoundedSucc and lifting to Type@(lmaxAll levels).
-- Together with the Π/Σ rows, all four non-nullary cumulative formers' formation FT is discharged.
#assert_no_axioms FX1Poly.Typed.oneChildFormationTelescopeAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativeListMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativeOptionMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativeListRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativeOptionRowAtBoundedSucc

-- TYTAB-4 step 4 (DenoteKeyedBoundedCarrierAwareArm.lean): the bound-carrying carrier-aware reducibility-from-
-- components builder — the IsReducibleTypeAtBounded-level wrapper over the inductive arm dataFlatCarrierAware, the
-- carrier-aware twin of piReducibleAtLevelFromComponentsBounded (the missing builder the bounded flat formation FT
-- needs; the denote-layer ofDataFlatCarrierAware already ships). Two obtains + one dataFlatCarrierAware constructor;
-- both component existentials share the denoteBelowFamilyBounded env level below-family so they compose directly.
#assert_no_axioms FX1Poly.Typed.carrierAwareReducibleAtLevelFromComponentsBounded

-- TYTAB-4 step 4 (CarrierAwareFlatFormationMember.lean): the generic carrier-aware flat formation FT member —
-- product / either / equiv in ONE theorem over the 3-tag CarrierCombinator (the bounded twin of the denote-layer
-- carrierAwareFormerFundamentalFromCarriers). NON-dependent (no binder crossing), so built directly through
-- universeMembershipIntroAtBounded: each component's reducible-as-type at its OWN level is lifted to the JOIN level
-- by free bounded cumulativity, assembled by the carrier-aware builder, SN by cell_isStronglyNormalizing_of_carriers.
#assert_no_axioms FX1Poly.Typed.fundamentalCarrierAwareFlatMemberAtBoundedSucc

-- TYTAB-4 step 4 (CarrierAwareFlatFormationRows.lean): the product / either / equiv carrier-aware flat formation FT
-- rows over the native obligation-list form + FREE levels — the carrier-aware half of the flat formationFundamental
-- premise. levelMax_zero_right (the right-zero collapse, two rfl clauses) handles the POSITIONAL single-level case
-- (flatFormationObligations zips children with levels, forcing only the SECOND child to lzero — unlike the cumulative
-- rows which forced both). The generic spine row factors the three-way levels dispatch once; the three per-generator
-- wrappers match the two-child spine and pin the combinator, the subject collapsing definitionally to combinator.cell.
#assert_no_axioms FX1Poly.Typed.levelMax_zero_right
#assert_no_axioms FX1Poly.Typed.fundamentalCarrierAwareFlatSpineRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalProductFormationRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalEitherFormationRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalEquivFormationRowAtBoundedSucc

-- TYTAB-4 step 4 (ContentFreeFlatFormationRows.lean): the arrow / sum content-free flat formation FT rows — the
-- content-free half of the flat formationFundamental premise (carrierCombinator? = none, isFlatDataCode = true).
-- Reducibility-as-type is content-free (flatCode_isReducibleTypeAtBounded ignores the carriers), so only the cell's
-- SN feeds the membership intro; PER-FORMER (concrete gen_arrowCode/gen_sumCode) because subst rides defeq only on a
-- concrete head, matching arrowCode/sumCode_isStronglyNormalizing_of_* and flatCode_isReducibleTypeAtBounded _ rfl
-- rfl. The generic fundamentalTwoChildFlatRowAtBoundedSucc factors the free-levels three-way dispatch over an opaque
-- subject + memberBuilder (subsumes the carrier-aware spine row's role); the two wrappers feed the per-former member.
#assert_no_axioms FX1Poly.Typed.fundamentalArrowFlatMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalSumFlatMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalTwoChildFlatRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalArrowFormationRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalSumFormationRowAtBoundedSucc

-- TYTAB-4 step 4 (FlatFormerStrongNormalization.lean): the FLAT-table twins of the cascade-free former
-- step-inversion + SN driver + weak-head-normality (the flatTypingRuleDescOf analogues of
-- formerCellStepIsChildCongruence / formerCellStronglyNormalizingOfChildren / formationGenerator_noWeakHeadStep).
-- legacyElimHead_hasNoFlatFormationRule is the one cross-table fact (every iota row's elim head carries no flat
-- formation rule); the inversion routes through the generic Step.childCongruenceOfElimHeadsExcluded, the SN
-- driver through formerCell_isStronglyNormalizing_of_accChildren — both cascade-free, so a new flat row is
-- absorbed zero-touch. The reusable infrastructure for the cohesion-modality neutral-arm members below.
#assert_no_axioms FX1Poly.Typed.legacyElimHead_hasNoFlatFormationRule
#assert_no_axioms FX1Poly.Typed.flatFormerStepInversion
#assert_no_axioms FX1Poly.Typed.flatFormerCellStronglyNormalizingOfChildren
#assert_no_axioms FX1Poly.Typed.flatFormationGenerator_noWeakHeadStep

-- TYTAB-4 step 4 (ModalityFlatFormationRows.lean): the cohesion-modality (ʃ / ♭ / ♯) flat formation FT members
-- + rows — the LAST flat formationFundamental piece (isFlatDataCode = false, carrierCombinator? = none, so the
-- neutral arm, not a data candidate). The modal type formers are level-preserving ONE-child formers whose only
-- semantic content is SN (modal intro/elim awaits the lock-extended modal context, the context-4 frontier). The
-- members are PER-FORMER (subst rides defeq on the concrete generator), feeding the flat-table SN driver + the
-- neutral arm (no-weak-step twin + decide ≠ gates + isFlatDataCode = false rfl). The generic
-- fundamentalOneChildFlatRowAtBoundedSucc factors the free-levels two-way positional dispatch once.
#assert_no_axioms FX1Poly.Typed.fundamentalShapeModalityMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalFlatModalityMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalSharpModalityMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalOneChildFlatRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalShapeModalityFormationRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalFlatModalityFormationRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalSharpModalityFormationRowAtBoundedSucc

-- TYTAB-4 step 4 (TermIndexedFormerStrongNormalization.lean): the TERM-INDEXED-table twins of the cascade-free
-- former step-inversion + SN driver + weak-head-normality (the termIndexedFormerDescOf analogues). Third
-- instantiation of the cascade-free pattern (after typingRuleDescOf and flatTypingRuleDescOf):
-- legacyElimHead_hasNoTermIndexedFormationRule is the cross-table fact, the inversion routes through the generic
-- Step.childCongruenceOfElimHeadsExcluded, the SN driver through formerCell_isStronglyNormalizing_of_accChildren.
#assert_no_axioms FX1Poly.Typed.legacyElimHead_hasNoTermIndexedFormationRule
#assert_no_axioms FX1Poly.Typed.termIndexedFormerStepInversion
#assert_no_axioms FX1Poly.Typed.termIndexedFormerCellStronglyNormalizingOfChildren
#assert_no_axioms FX1Poly.Typed.termIndexedFormationGenerator_noWeakHeadStep

-- TYTAB-4 step 4 (TermIndexedFormationRows.lean): the term-indexed (Id / Bridge) formation FT members + rows —
-- the LAST formationFundamental sub-family. The obligation list is HETEROGENEOUS: the carrier (head child) is a
-- universe member (SN off stronglyNormalizing_of_universeMemberAtBounded), the endpoints are members of the
-- carrier (SN off the bounded CR1 in member form stronglyNormalizing_of_memberAtBoundedSucc, which closes at
-- targetScope + 1). Output is the carrier-level universe Type@level; the cell's reducibility-as-type is the
-- neutral arm (gen_idCode / gen_bridgeCode are not data / Π / universe / empty codes). The rows match the arity-3
-- spine and read the three obligation IHs off the .termIndexed obligation list via List.Mem.
#assert_no_axioms FX1Poly.Typed.fundamentalIdFormationMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBridgeFormationMemberAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalIdFormationRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBridgeFormationRowAtBoundedSucc
-- The term-indexed family-arm dispatcher (the .termIndexed arm of the eventual cases-FormationRule assembly):
-- keyed on termIndexedFormerDescOf, routes gen_bridgeCode / gen_idCode to their rows, none-case impossible.
-- The analogue of fundamentalBaseTypeRowAtBoundedSucc for the carrier-plus-endpoints family.
#assert_no_axioms FX1Poly.Typed.fundamentalTermIndexedFormationRowAtBoundedSucc

-- The flat family-arm dispatcher (the .flat arm of the eventual cases-FormationRule assembly): keyed on
-- flatTypingRuleDescOf, an eight-way by_cases over the data codes (product/sum/either/arrow/equiv) + cohesion
-- modalities (shape/flat/sharp), routing each to its uniform-interface row, none-case impossible.
#assert_no_axioms FX1Poly.Typed.fundamentalFlatFormationRowAtBoundedSucc

-- The cumulative family-arm dispatcher (the .cumulative arm of the eventual cases-FormationRule assembly):
-- keyed on typingRuleDescOf + the gen_unitCode exclusion (isNotNullary), a four-way by_cases over the
-- dependent formers (pi/sigma binder-shape, list/option element-shape) routing each to its uniform-interface
-- row, none-case via the if-chain cascade (including the nullary branch via isNotNullary) + contradiction.
#assert_no_axioms FX1Poly.Typed.fundamentalCumulativeFormationRowAtBoundedSucc

-- The native formationFundamental premise (TYTAB-4 step 4): the top-level four-family `cases FormationRule`
-- assembly composing the baseType / flat / termIndexed / cumulative arms.  Every generator carrying a
-- formationRuleOf rule makes mkGen a bound-reducible member of the rule's output universe under the per-level
-- bounds + child obligation IHs.  Discharges the first of the three table-arm FT premises of
-- HasTypeUnionOver.fundamentalAtBoundedSuccFromTableArms.
#assert_no_axioms FX1Poly.Typed.fundamentalFormationRowAtBoundedSucc

-- The intro side (TYTAB-4 step 4, the value half of the Tait FT): the six NULLARY data-constructor intro rows.
-- Each nullary constructor (boolTrue/boolFalse/unit/interval0/interval1/natZero) is a bound-reducible member of
-- its neutral base type via the SN candidate (the value-side twin of the base-type formation neutral members):
-- the constructor cell is a closed normal-form leaf, hence SN, hence in the type's `neutral`-arm candidate.
#assert_no_axioms FX1Poly.Typed.fundamentalNullaryIntroAtBoundedSucc
-- boolTrue/boolFalse moved off the SN candidate: they now land in `dataTaitCandidate boolIsValue` (the value IS a
-- canonical form, via `dataTaitCandidate.memberOfValue`) through `fundamentalFlatDataNullaryIntroAtBoundedSucc`,
-- matching Bool's type candidate so the dependent eliminator's scrutinee decomposes.
#assert_no_axioms FX1Poly.Typed.fundamentalFlatDataNullaryIntroAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBoolTrueIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalBoolFalseIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalUnitIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalInterval0IntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalInterval1IntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalNatZeroIntroRowAtBoundedSucc

-- The intro-constructor SN engine (the fourth cascade-free instantiation, keyed on introRuleOf): an introducer
-- cell is SN once its children are (it heads no root redex; Step carries no eta). Universe-robust route via the
-- table-free Step.weakHeadOrChildCong + the introducer weak-head-rigidity (IntroRule lives a universe above the
-- generic childCongruenceOfElimHeadsExcluded's tableValue). The value-SN engine for the SN-neutral intro rows.
#assert_no_axioms FX1Poly.Typed.introConstructorNoWeakHeadStep
#assert_no_axioms FX1Poly.Typed.introConstructorStepInversion
#assert_no_axioms FX1Poly.Typed.introConstructorCellStronglyNormalizingOfChildren

-- The SN-neutral recursive-constructor intro FT rows (the value-side twin of the term-indexed formation members):
-- a non-nullary introducer whose output type is SN-neutral (Σ / list / option / Id / bridge / nat) is a
-- bound-reducible member of that type — the output type is reducible-as-type via the `neutral` arm (candidate
-- `IsStronglyNormalizing`), and the constructed cell lies in it because it is SN, supplied by the intro-constructor
-- SN engine from the children's SN (read off the obligation IHs). `natSucc` (nullary-base output) and `refl`
-- (term-indexed output) — the two output-type shapes that need no cumulative-table machinery.
#assert_no_axioms FX1Poly.Typed.fundamentalNatSuccIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalReflIntroRowAtBoundedSucc

-- The cumulative-output SN-neutral intro FT rows: list/option constructors are bound-reducible members of their
-- cumulative-former output types (List(A) / option(A)), whose neutral candidate IsStronglyNormalizing is gated
-- by the table-generic cumulative weak-head-rigidity formationGenerator_noWeakHeadStep (keyed on
-- typingRuleDescOf_listCode / typingRuleDescOf_optionCode). listCons/optionSome read child SN off the obligation
-- IHs; listNil/optionNone are closed nullary normal-form leaves (formedness-only, no member obligation consumed).
#assert_no_axioms FX1Poly.Typed.fundamentalListConsIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalOptionSomeIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalListNilIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalOptionNoneIntroRowAtBoundedSucc

-- The carrier-aware (content-bearing flat) intro FT rows: product/either constructors are bound-reducible
-- members of their carrier-aware-candidate output types. The SAME component candidates from the obligation IHs
-- feed both the formation arm (dataFlatCarrierAware, storing combinator.assemble = carrierAware…Candidate) and
-- the Core general data-intro member (memberOfReducibleComponents) — no determinism alignment needed. `pair`
-- takes both carriers from its value obligations.
#assert_no_axioms FX1Poly.Typed.fundamentalPairIntroRowAtBoundedSucc
-- eitherInl/eitherInr: the injected carrier from the value obligation, the free carrier from the formedness
-- obligation via the universe-member bridge (reducibleTypeAtBoundFromUniverseMemberBounded, belowBound read off
-- the universe code's reducibility); cell via memberOfReducibleInl/Inr.
#assert_no_axioms FX1Poly.Typed.fundamentalEitherInlIntroRowAtBoundedSucc
#assert_no_axioms FX1Poly.Typed.fundamentalEitherInrIntroRowAtBoundedSucc

-- The graded-binder (Tier-3) intro FT row: `lam` is a bound-reducible member of its `piTyCodeCell` output via
-- the shipped binder-crux engine `fundamentalPiIntroAtBoundedSucc`, fed its three closing-substitution premises
-- from the two universe-membership obligation IHs (the A2 bridge + the SN-from-member CR1) and the body
-- obligation IH — the union-table restatement of the grown-engine piIntro recursor arm.
#assert_no_axioms FX1Poly.Typed.fundamentalLamIntroRowAtBoundedSucc
-- pathLam (the affine path binder, SN-neutral bridge output): body SN reflected from an interval-filled
-- member via codomainOpenStronglyNormalizing_ofBoundedFilledMember (no binder-lift / renaming-stability), then
-- the intro-constructor SN engine lifts it to the cell; the bridge type takes the SN-neutral term-indexed arm.
#assert_no_axioms FX1Poly.Typed.fundamentalPathLamIntroRowAtBoundedSucc

-- The flat introFundamental glue: the seventeen-row `introRuleOf_cases` dispatcher assembling all intro rows
-- into the single `introFundamental` premise of `fundamentalAtBoundedSuccFromTableArms` (keyed on
-- `introRuleOf generator = some rule`, the fxTypingBundle intro table). The native analogue of the grown intro
-- arms; a future introducer row adds one disjunct with no change to the existing arms.
#assert_no_axioms FX1Poly.Typed.fundamentalIntroRowAtBoundedSucc

-- The elim side (TYTAB-4 step 4, elimFundamental). app: the general (non-data) eliminator via the shipped
-- fundamentalPiElimAtBoundedSucc Pi-elimination engine — the union-table restatement of the grown piElim arm.
#assert_no_axioms FX1Poly.Typed.fundamentalAppElimRowAtBoundedSucc
-- The dependent data-eliminator rows (DEP-BOOL-ROW …): boolElim via the shipped
-- fundamentalBoolElimAtBoundedSucc dependent engine, the under-binder motive SN reflected from the motive IH.
#assert_no_axioms FX1Poly.Typed.fundamentalBoolElimRowAtBoundedSucc

-- The bounded member weak-head expansion keystone: every bound-reducible candidate absorbs a member redex under
-- any WeakHeadStep (the arrow arm closed by the general weak-head SN spine).  Behind the data-eliminator FT rows.
#assert_no_axioms FX1Poly.Typed.ReducibleTypeAtBounded.memberWeakHeadExpansion
