import FX1PolyAudit.DependencyAudit
import FX1Poly.Core.Metatheory.Reducibility.Core.DataReducibilityCoverage
import FX1Poly.Core.Metatheory.Reducibility.Candidates.DataTaitCandidate
import FX1Poly.Core.Metatheory.Reducibility.Candidates.FlatCodeTaitCandidate
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FlatCodeCanonicalForms
import FX1Poly.Typed.Ledger.MilestoneASpineValueLayer
import FX1Poly.Typed.Ledger.MilestoneAEliminatorLayerSpine
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimComputingCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicityTyped
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchGeneralBranchCanonicity
import FX1Poly.Typed.Ledger.MetatheoryParityLedger
import FX1Poly.Typed.Engine.Classifier.TypingContext
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeShape
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeConversion
import FX1Poly.Typed.Engine.Formation.SigmaCodeShape
import FX1Poly.Typed.Engine.Formation.ListCodeShape
import FX1Poly.Typed.Engine.Formation.ListFormationSmoke
import FX1Poly.Typed.Engine.Formation.OptionCodeShape
import FX1Poly.Typed.Engine.Formation.OptionCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.OptionFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationOptionFromTelescope
import FX1Poly.Typed.Engine.Formation.OptionFormationSmoke
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDesc
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescDecidable
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElim
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescValidity
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescClosedForms
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFormerTelescopeInversion
import FX1Poly.Typed.Engine.Formation.DataFormerInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescUniqueness
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPi
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaCoherence
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionGrown
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionComputes
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiWeakening
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiSubstitution
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiValidity
import FX1Poly.Typed.Ledger.Misc.ConvCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvBoolCodeRigidity
import FX1Poly.Typed.Engine.Formation.ConvFormationFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvCrossTableFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvDataCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.EmptyTypeCodeConvRigidity
import FX1Poly.Typed.Ledger.Inversion.EmptyTypeValueInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FormationCanonicalForms
import FX1Poly.Typed.Ledger.Inversion.PiTypeFunctionInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalForms
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafety
import FX1Poly.Typed.Engine.Formation.FormationTypeSafety
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsNonVacuity
import FX1Poly.Typed.Corpus.Smoke.GrownBetaRedexInAction
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgress
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownOpenCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafetyUnconditional
import FX1Poly.Typed.Engine.Formation.FormerStepInversionGeneric
import FX1Poly.Typed.Metatheory.SubjectReduction.SubjectReductionAtFormerGeneric
import FX1Poly.Typed.Engine.WfContext.WfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescValidity
import FX1Poly.Typed.Engine.WfContext.WfContextDescUniqueness
import FX1Poly.Typed.Engine.WfContext.WfContextDescPi
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiFromWfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiClassifierValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiFunctionComponentValidity
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionDescPi
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionMutual
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnv
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAt
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvTypeVariable
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprFT
import FX1Poly.Typed.Metatheory.Reducibility.Pi.AbstractionNonDependentUnderSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprReducibleLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermFundamentalLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInversionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprClosureLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermRenameLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1Poly.Typed.Metatheory.SimplyTyped.MilestoneA0SimplyTypedFloor
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1Poly.Tier0.FxRenamingCategory
import FX1Poly.Tier0.FxBaseRenamingCategory
import FX1Poly.Tier0.FxBaseRenamingVecCategory
import FX1Poly.Tier0.FxBaseRenamingVecIsomorphism
import FX1Poly.Tier0.FxBaseRenamingVecTabulate
import FX1Poly.Tier0.FxBaseRenamingVecPreimage
import FX1Poly.Tier0.FxBaseRenamingVecTryTabulate
import FX1Poly.Tier0.FxBaseRenamingVecRMC
import FX1Poly.Tier0.FxBaseRenamingVecGlobalSections
import FX1Poly.Tier0.FxBaseRenamingVecSconingPreservation
import FX1Poly.Tier0.FxBaseSubstVec
import FX1Poly.Tier0.FxBaseSubstCategory
import FX1Poly.Tier0.FxBaseSubstWeakening
import FX1Poly.Tier0.FxBaseSubstComprehension
import FX1Poly.Tier0.FxBaseSubstSingleton
import FX1Poly.Tier0.FxBaseSubstGlobalSections
import FX1Poly.Tier0.FxBaseSubstScone
import FX1Poly.Tier0.FxBaseSubstWitnessScone
import FX1Poly.Tier0.FxBaseSubstConcreteScone
import FX1Poly.Tier0.IsomorphismCategorical
import FX1Poly.Tier0.FxThinScopeRMC
import FX1Poly.Tier0.FxThinScopeGlobalSections
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1Poly.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1Poly.Core.Rewriting.Reduction.Head.RootStepDispatch
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnce
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1Poly.Core.Rewriting.Normalize.Normalize
import FX1Poly.Core.Rewriting.Normalize.NormalizeSteps
import FX1Poly.Core.Rewriting.Conversion.ConvDecisionSteps
import FX1Poly.Core.Rewriting.Normalize.NormalizeMeta
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsWeakHeadExpansion
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.BoolElimCanonicalComputation
import FX1Poly.Core.Eliminators.Bool.BoolElimClosedMembership
import FX1Poly.Core.Eliminators.Core.DataEliminatorMembershipSmoke
import FX1Poly.Core.Metatheory.Canonicity.SigmaProjectionCanonicalComputation
import FX1Poly.Core.Metatheory.Canonicity.IdentityEliminatorCanonicalComputation
import FX1Poly.Core.Eliminators.Identity.IdEliminatorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.OptionEitherMatchCanonicalComputation
import FX1Poly.Core.Eliminators.Match.MatchClosedMembership
import FX1Poly.Core.Eliminators.Sigma.SigmaProjectionClosedMembership
import FX1Poly.Core.Eliminators.Recursor.RecursorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.RecursiveEliminatorBaseComputation
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.DataCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.ModalCanonicityViaSconing
import FX1Poly.Core.Metatheory.Sconing.DataMetatheoryViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1Poly.Core.Metatheory.Sconing.ConsistencyViaSconing
import FX1Poly.Core.Eliminators.Core.DataEliminatorProgressViaSconing
import FX1Poly.Core.Eliminators.Recursor.RecursiveEliminatorProgressViaSconing
import FX1Poly.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.UnitCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EmptyCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingSubst
import FX1Poly.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1Poly.Core.Metatheory.Normalization.Core.WeakNormalization
import FX1Poly.Core.Rewriting.Normalize.NormalFormUnique
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevels
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllFormerChildren
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPiIntro
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Pi.NeutralFuelStability
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiTypeSaturationReassembly
import FX1Poly.Typed.Metatheory.Reducibility.Pi.StrongNormalizingAllLevelPiComponents
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescopePositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllCanonicalCandidate
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllVectorPremises
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllNonDependentBinders
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtUniformVectorPremises
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFundamentalVectorFromFormation
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFundamentalAtAllFromGenFormation
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClosedLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.TypeFundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LeveledContext
import FX1Poly.Typed.Corpus.Smoke.ClosedSNSmoke
import FX1Poly.Typed.Corpus.Smoke.UntypedOmegaNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.StepNonDeterministic
import FX1Poly.Typed.Ledger.Misc.ConvValueDiscrimination
import FX1Poly.Typed.Corpus.Smoke.TypedLambdaDerivations
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleans
import FX1Poly.Typed.Corpus.Church.Core.TypedChurchNegation
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumerals
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIteration
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralDiscrimination
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralThree
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralTyping
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralInhabitants
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralComputeGeneral
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralAddition
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralMultiplication
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralSemiringLaws
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIsZero
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleanOperations
import FX1Poly.Typed.Corpus.Smoke.TypedFragmentAcyclicity
import FX1Poly.Typed.Corpus.Smoke.UnboundedGrowthNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointDivergence
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointCombinator
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryLogic
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryCompleteness
import FX1Poly.Typed.Corpus.Church.Combinators.SymbolicSCombinatorRule
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairs
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairsInjective
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSums
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsDisjoint
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsGeneral
import FX1Poly.Typed.Corpus.Church.Lists.ChurchLists
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListIsEmpty
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAny
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAll
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBooleanComplementLaws
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBoolXor
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListFirstOr
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSucc
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSuccApplies
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListLength
import FX1Poly.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1Poly.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1Poly.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseNoTop
import FX1Poly.Typed.Metatheory.Universe.TypedUniversePredicative
import FX1Poly.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1Poly.Typed.Corpus.Progress.ClosedNormalForm
import FX1Poly.Typed.Metatheory.Normalizer.ClosedNonConvertibility
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTyping
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiStronglyNormalizingFromFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVecTypeVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConsistency
import FX1Poly.Typed.Engine.Formation.HasTypeFormationNoLambdaApplication
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleSemanticRules
import FX1Poly.Typed.Engine.Formation.ListCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.ListFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberFormation
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeInversion
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeReach
import FX1Poly.Typed.Engine.RuleTables.FlatDescTelescope
import FX1Poly.Typed.Metatheory.Canonicity.Core.StandaloneEngineCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.CombinedBoolCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedBoolCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicitySyntacticRoute
import FX1Poly.Typed.Metatheory.Canonicity.Core.GrownRigidityCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedNatCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimValueCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.NatElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulArithmetic
import FX1Poly.Typed.Metatheory.Reducibility.Core.ClosedNumeralSubstInvariant
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulMul
import FX1Poly.Typed.Corpus.Faithfulness.ValueElimHostFold
import FX1Poly.Typed.Corpus.Faithfulness.RecursorHostFold
import FX1Poly.Typed.Metatheory.Canonicity.Core.ListElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.ListElimFaithfulLength
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicity
import FX1Poly.Typed.Corpus.Progress.GrownClosedNormalClassifierShape
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ClosedNormalEmptyConsistency
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ProductEitherCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.OptionCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ListCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.IdCanonicalForms
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiFormerMembership
import FX1Poly.Typed.Engine.Formation.FormerChildrenReducible
import FX1Poly.Typed.Metatheory.Reducibility.Telescope.TelescopeReducible
import FX1Poly.Typed.Metatheory.Universe.UniverseDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsInduction
import FX1Poly.Typed.Metatheory.Reducibility.Pi.ReducibleTypeAtAllLevelsPiNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsWhnfDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsPiDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsPiMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsHeadExpand
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsConv
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Strengthening.RouteAObstruction
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelDiagnosis
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelMeasure
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibility
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibilitySmoke
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPi
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedLevelIrrelevance
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseFormationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCanonicalMemberCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationFromExistence
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGeneralDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSingleLevelPi
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiAboveThreshold
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormerAtLevel
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleTypeLevelLift
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiArmDischarge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedApplicationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedConvMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberForwardClosed
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMemberBetaExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberWeakHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedAbstractionMember
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAbstractionUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiElim
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalConv
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAmbientLevelBridge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrow
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiIntro
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedClosedMember
import FX1Poly.Typed.Metatheory.Denote.Telescope.DenoteKeyedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedUniformReducible
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMembershipIntro
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFormation
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFromChildMembers
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationSigmaArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedCumulativityObstruction
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibility
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedConvArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiElimArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiIntroArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedFormerEngine
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiDischarge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedAssemblyBridge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeProjection
import FX1Poly.Typed.Engine.Formation.FormerOutputLevelBounds
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedCodomainOpenSN
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDomainInhabitant
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationPiFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationSigmaFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationListFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedTelescopeConsSucc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGrownDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDesc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPi
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPiDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedGrownFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ClosedBoundedReducibleMember
import FX1Poly.Typed.Corpus.Smoke.ClosedStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedNeutralMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseInversion
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBindingTypeReducible
import FX1Poly.Typed.Engine.WfContext.ReducibleEnvOfWfContext
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizingUnconditional
import FX1Poly.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1Poly.Typed.Corpus.Smoke.OpenSNSmoke
import FX1Poly.Typed.Corpus.Progress.ContextValidityFails
import FX1Poly.Typed.Equality.UnitEta.UnitEtaJudgmentalEquality
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruenceGap
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruentEquality
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapse
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseIncompleteness
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeep
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseNeutralBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitNeutralSpineDetection
import FX1Poly.Typed.Equality.UnitEta.UnitSpineDetectionBoundary
import FX1Poly.Typed.Equality.UnitEta.TypeDirectedUnitReadback
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackArgumentBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackFormerChildBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackDeepSpineBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackAnnotationBoundary
import FX1Poly.Typed.Engine.Formation.FormationClassifierRigidity
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeConvDecision
import FX1Poly.Typed.Ledger.Misc.LiftedChildNormalizationFromClosure
import FX1Poly.Typed.Engine.RuleTables.TelescopeSubstitutedChildrenNormalization
import FX1Poly.Typed.Ledger.CascadeFreedomLedger
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyTargetSignature
import FX1Poly.Typed.Ledger.Bridge.CandidateBridgeEditViability
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicityTargetSignature
import FX1Poly.Typed.Metatheory.Universe.NullaryFormerFormation
import FX1Poly.Typed.Metatheory.Universe.GrownUniverseFormationStrictness
import FX1Poly.Typed.Engine.Formation.GrownFormerFormationStrictness
import FX1Poly.Typed.Engine.Classifier.GrownTypingNotUnique
import FX1Poly.Typed.Engine.Classifier.GrownEngineHonesty
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.GrownUniverseConsistency
import FX1Poly.Typed.Engine.Classifier.GrownVariableHonesty
import FX1Poly.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiLamInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiAppInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVarInversion
import FX1Poly.Typed.Metatheory.ContextConversion.VarHeadedAppContextConversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiBetaSR
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiCongruence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerCongruence
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionConditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimReduction
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionValidityReduction
import FX1Poly.Typed.Corpus.Progress.GrownMutualMetatheoryFromPiValidity
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimEquivalence
import FX1Poly.Typed.Engine.HasTypeDescPi.ContextConversion.HasTypeDescPiContextStepConversion
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionUnconditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionFlexibleUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormationFragment
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormerStep
import FX1Poly.Typed.Metatheory.ContextConversion.GenFormerValidityContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPiValidityModelNeutral
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveled
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransport
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransportUnderWf
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledCompleteness
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValid
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRename
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValidLookup
import FX1Poly.Typed.Ledger.Misc.PiElimClassifierConvResidual
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiFormerInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiDataHeadUntyped
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiRootGeneric
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedUniverseBoundedCumulativity
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedClosedTypeCodeSN
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiMemberSN
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrowMemberSN
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCodomainMemberWiring
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelSpike
import FX1Poly.Typed.Ledger.SNStrategy
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.LogRelSpec
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LevelingBridge
import FX1Poly.Typed.Metatheory.Canonicity.Core.ConsistentStratification
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingLevelFlexible
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingRefinedMotive
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingConvArm
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingPiArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingFormerArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingVariableLevelPinned
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalReduction
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalAssembly
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.SimplyTyped.HigherOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiOverNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiNeutralCodomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentlyTypedNeutralDomainFragment
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedSubsumption
import FX1Poly.Typed.Metatheory.Universe.UniverseCumulativity
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermReducibility
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiTypingNonUnique
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckOfInferred
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVariableInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiUniverseCodeInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckUniverseCode
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplicationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckFormation
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationCodomainReTyping
import FX1Poly.Typed.Engine.RuleTables.IntroRuleDesc
import FX1Poly.Typed.Engine.RuleTables.ElimRuleDesc
import FX1Poly.Typed.Engine.RuleTables.GenElimIotaComputation
import FX1Poly.Typed.Engine.Classifier.TypingRoleClassifier
import FX1Poly.Typed.Engine.Classifier.TypingRoleEngineBridge
import FX1Poly.Typed.Engine.Classifier.TypingRoleCoverage
import FX1Poly.Typed.Engine.Classifier.UntypableHeadDecision
import FX1Poly.Typed.Engine.Classifier.TypingHeadKindClassifier
import FX1Poly.Typed.Engine.Classifier.TypedBySomeEngine
import FX1Poly.Typed.Engine.Classifier.GeneratorSemanticTier
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyOverview
import FX1Poly.Typed.Engine.Classifier.StaticTypingSoundness
import FX1Poly.Typed.Engine.Classifier.SemanticTierSoundness
import FX1Poly.Typed.Engine.Classifier.ClassifierRefinement
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyLedger
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionTermination
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerStepDomainFormationCodomain
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionFormerArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionInlineArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionConvOfFormationArms
import FX1Poly.Typed.Metatheory.SubjectReduction.ConsistencyConditionalOnSubjectReduction
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencySyntactic
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyOfPiElimArm
import FX1Poly.Typed.Ledger.Misc.PiElimUpToClassifierConv
import FX1Poly.Typed.Engine.Classifier.ClassifierRespectsConvRefuted
import FX1Poly.Typed.Dimensions.AxisObligation.TypedCertificationStackingRefuted
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencyUnconditional
import FX1Poly.Typed.Engine.Formation.FormationNormalSmoke
import FX1Poly.Typed.Engine.Formation.BoolTypeCodeSubstrate
import FX1Poly.Typed.Engine.Formation.NatTypeCodeSubstrate
import FX1Poly.Typed.Corpus.Progress.GrownNoTypeInType
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescRigidity
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidable
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1Poly.Typed.Ledger.KnownUnsoundnessCorpus
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationAcyclic
import FX1Poly.Modal.SecurityNoninterferenceGeneral
import FX1Poly.Modal.GradedApplicationFlow
import FX1Poly.Typed.Ledger.MetatheoryFuzz
import FX1Poly.Typed.Ledger.FuzzCorpusConvertibility
import FX1Poly.Typed.Ledger.FuzzCorpusNormalizes
import FX1Poly.Typed.Ledger.LambdaValueFuzzFamily
import FX1Poly.Typed.Ledger.MechanizedProofCrossReference
import FX1Poly.Typed.Ledger.FormalReviewGate
import FX1Poly.Typed.Ledger.SelfVerifiedMetatheory
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengthening
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheck
import FX1Poly.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1Poly.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiImageComponents
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiRenameImage
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionContext
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiIntro
import FX1Poly.Typed.Engine.Formation.FormationPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.GrownPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimCore
import FX1Poly.Typed.Corpus.Smoke.GrownWfOpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimDispatcher
import FX1Poly.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1Poly.Typed.Metatheory.Strengthening.GuardedPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PlateauPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.NeutralReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionLamClassifierResidual
import FX1Poly.Typed.Metatheory.Strengthening.FlagCoherentReflectionCondition
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationUnique
import FX1Poly.Typed.Ledger.Misc.NeutralClassifierUnique
import FX1Poly.Typed.Ledger.Misc.NormalAppNeutral
import FX1Poly.Typed.Engine.RuleTables.TelescopeUniverseDeterminism
import FX1Poly.Typed.Engine.RuleTables.GenericFormerTelescopeInversion
import FX1Poly.Typed.Metatheory.Universe.NormalUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.ConvUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Strengthening.RenameAlongFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.PinSelectsCallerPair
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.LamReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherentMaster

/-! # FX1PolyAudit/AuditTypedCanonicalForms — typed-layer zero-axiom gates: canonical forms, canonicity, consistency, progress, and type safety
   (semantic shard of the typed audit; gates classified by declaration topic, appended
   clusters kept together; full import block retained for namespace-sweep coverage) -/


/-! ### Closed-form consequences for the description formation engine: closed subjects are intrinsic
    description types, have universe/Pi/Sigma type-former shape, and have classifiers convertible to
    universe codes.  All three — `closedSubjectIsTypeDesc` (via the scope-generalised
    `closedSubjectIsTypeDescGeneral` workhorse), the STRUCTURAL `closedSubjectIsTypeFormer` (native
    `closedSubjectHeadIsFormerOrUniverse` + the `eq_*Cell_of_headGenerator` head-to-children
    reconstructions), and `closedClassifierConvUniverseCode` (native uniqueness) — are proved directly on the
    native formation recursion. -/
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedSubjectIsTypeDescGeneral
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedSubjectIsTypeDesc
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedSubjectIsTypeFormer
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedSubjectHeadIsFormerOrUniverse
-- FORMATION-ENGINE CONSISTENCY: no closed formation-engine term inhabits the empty type
-- (HasTypeDesc .empty t emptyTypeCell → False). Every classifier a closed formation derivation reaches has
-- head gen_universeCode (universeFormation / genFormation outputs) or — for a conv reclassifier — a Π/Σ/universe
-- head (subjectIsVariableOrFormerHead, variable disjunct killed by closedness); none is gen_emptyCode. The
-- FORMATION half of SN-050; no reconstruction, no value-inversion. Zero-axiom (recursor + Generator.noConfusion).
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.noClosedFormationTermAtEmptyType
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedNormalSubjectHead
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtEmptyType
-- CANONICAL FORMS PER TYPE (GrownCanonicalFormsByClassifier.lean): the classifier-sharp refinement of
-- closedNormalSubjectHead. closedNormalFunctionIsLambda = a closed normal FUNCTION-typed term (Π classifier) is a
-- λ with body extracted (the three type-former heads refuted by the *NotTypedAtPiType inversions). closedNormalTypeIsFormer
-- = a closed normal TYPE (universe classifier) is a type FORMER head piTy/sigmaTy/univ, never λ (lam refuted by
-- lam_notTypedAtUniverseCode). #672-independent, no SR — pure inversion over the closed-canonical-forms recursor.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedNormalFunctionIsLambda
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedNormalTypeIsFormer
-- CANONICAL-FORMS NON-VACUITY (GrownCanonicalFormsNonVacuity.lean): concrete closed witnesses showing the
-- canonical-forms-per-type theorems FIRE. closedUniverseCodeTyping = Type@s : Type@(s+1) (universeFormation);
-- closedIdentityLambdaTyping = λ(x:Type@s).x : Π(Type@s).Type@s (piIntro + var) — the first NAMED concrete closed
-- POSITIVE typing derivations (complement to the GrownEngineHonesty 0-FP corpus). The two *_nonVacuous theorems
-- feed Type@0 / the identity lambda through closedNormalTypeIsFormer / closedNormalFunctionIsLambda.
#assert_no_axioms FX1Poly.Typed.closedUniverseCodeTyping
#assert_no_axioms FX1Poly.Typed.closedIdentityLambdaTyping
#assert_no_axioms FX1Poly.Typed.closedNormalTypeIsFormer_nonVacuous
#assert_no_axioms FX1Poly.Typed.closedNormalFunctionIsLambda_nonVacuous
-- TYPE SAFETY IN ACTION (GrownBetaRedexInAction.lean): a concrete closed REDUCING term threaded through the
-- safety pipeline. closedIdentityAppRedexTyping = (λ(x:Type@1).x)(Type@0) : Type@1 (piElim). betaStep = it
-- Step.beta's to Type@0. safety = the reduct Type@0 is STILL typed at Type@1 (betaSubjectReduction PRESERVATION)
-- AND is a canonical value (closedNormalTypeIsFormer) — progress + preservation + canonical forms on one
-- reducing closed term, the concrete instantiation of "a well-typed term steps to a well-typed value".
#assert_no_axioms FX1Poly.Typed.closedIdentityAppRedexTyping
-- That SR-along-↝* residual is now DISCHARGED: HasTypeDescPi.subjectReductionStar is unconditional (SR-U4),
-- so emptyTypeConsistencySyntactic instantiates it at the empty context (WfContextDescPi.emptyIsWellFormed)
-- and EmptyType classifier — the UNCONDITIONAL syntactic-route empty consistency, the twin of the
-- candidate-route emptyTypeConsistency that survives into the substantive-Empty regime.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.emptyTypeConsistencySyntactic
-- GROWN TYPE SAFETY (GrownTypeSafety.lean, five-layer-defense L4 §27.3): the named preservation/progress safety
-- statements over the grown engine. closedProgress = PROGRESS unconditional (a closed grown-typed term is a
-- canonical value — canonical head + normal — or it steps; no stuck closed terms; typing is load-bearing in the
-- normal case via closedNormalSubjectHead). closedTypeSafetyOfSubjectReductionStar = TYPE SAFETY conditional on
-- SR-along-↝* (every closed grown-typed term evaluates to a canonical value: OB-5 SN + weak normalization + the
-- preservation hypothesis + canonical forms), the lone gate being the SN-055 master dispatcher, exactly as the
-- consistency route.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedProgress
-- FORMATION TYPE SAFETY (FormationTypeSafety.lean, five-layer-defense L4 §27.3): the UNCONDITIONAL half of the
-- preservation/progress parity.  The formation engine HasTypeDesc types only normal forms (subjectAdmitsNoStep),
-- so closedFormationProgress is a canonical value with NO "or it steps" disjunct, and closedFormationTypeSafety
-- evaluates to the term ITSELF (StepStar.refl) with NO subjectReductionStar hypothesis — the SR gate the grown
-- closedTypeSafetyOfSubjectReductionStar carries is ELIMINATED here.
#assert_no_axioms FX1Poly.Typed.RawTerm.IsFormationCanonicalHead
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedFormationSubjectIsNormal
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedFormationProgress
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedFormationTypeSafety
-- OPEN PROGRESS (GrownOpenProgress.lean, five-layer-defense L4 §27.3): the OPEN generalization of closedProgress
-- off the empty context. openNormalSubjectCanonicalOrNeutral = OPEN CANONICAL FORMS — a grown-typed NORMAL term in
-- ANY well-formed context is a canonical head (IsGrownCanonicalHead) or a Core.IsNeutral term; the recursor mirrors
-- closedNormalSubjectHead but drops the (Fin scope → False) premise, rerouting the two leaves closedness eliminated
-- (var → IsNeutral.var, neutral-function app → IsNeutral.app, where variableCell/appCell are definitionally the
-- mkGen gen_var/gen_app cells the constructors expect). openProgress = OPEN PROGRESS unconditional — a grown-typed
-- term in any context is a normal canonical-value-or-neutral or it steps (by_cases on decidable normality), no
-- stuck terms in ANY context. #672-independent — pure inversion, no SR, no SN.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.openNormalSubjectCanonicalOrNeutral
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.openProgress
-- UNCONDITIONAL GROWN TYPE SAFETY (GrownTypeSafetyUnconditional.lean, HARVEST-TS): discharge the SR-along-↝*
-- hypothesis of the four conditional capstones above via SR-U4 (subjectReductionStar, now unconditional under the
-- benign WfContextDescPi presupposition).  closedTypeSafety / closedTypeSafetyUnique feed the empty-context witness
-- (WfContextDescPi.emptyIsWellFormed); openTypeSafety / openTypeSafetyUnique lift the WfContextDesc presupposition
-- to the grown WfContextDescPi via WfContextDescPi.ofWfContextDesc.  Progress + preservation (+ confluence) with NO
-- hypothesis: every closed/open grown-typed term EVALUATES TO ITS (unique) canonical[-or-neutral] value.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedTypeSafety
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedTypeSafetyUnique
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.openTypeSafety
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.openTypeSafetyUnique
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.consistencyOfPiElimArm
-- ★ SN-050 UNCONDITIONAL (EmptyTypeConsistencyUnconditional.lean): emptyTypeConsistency DROPS the piElim/SR
-- conditionality above. Once emptyTypeCellHasNoTyping (the data-head boundary, last commit) existed, grown
-- VALIDITY (classifierIsTypeDescPi, WFG-3) closes consistency in two lines: t : emptyTypeCell forces
-- emptyTypeCell : universe (validity), refuted by emptyTypeCellHasNoTyping. Honest scope: the current engine,
-- where emptyTypeCell is not yet a substantive type (typingRuleDescOf gen_emptyCode = none); the
-- canonicity-grounded consistency for a formation-row Empty (CON-A3) is independent + future.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.emptyTypeConsistency
-- EXTRACTION twin of the decision lane: from the FT-derived closed SN, the normalizer EXTRACTS the canonical
-- normal form (closedNormalFormFromLevelIndexed) with its metatheory — converts to it, it is normal, and NF
-- equality is a COMPLETE conversion invariant (closedConv_iff_normalForm_eq). The cherries are PROVEN (not
-- just decidable): the closed β-redex normalizes to its reduct Type@e; the closed identity is its own NF.
#assert_no_axioms FX1Poly.Typed.closedNormalFormFromLevelIndexed
#assert_no_axioms FX1Poly.Typed.closedNormalForm_conv
#assert_no_axioms FX1Poly.Typed.closedNormalForm_isStepNormalForm
-- NEGATIVE non-vacuity capstone: closed normal terms convert IFF syntactically equal
-- (closedNormalConv_iff_syntacticEq, the isStepNormalForm-stated rigidity), so distinct head generators are
-- PROVABLY non-convertible. Complements betaRedexConvertsToReduct (positive) — the decidable-Conv lane
-- decides both convertible AND non-convertible closed pairs. Unconditional (no FT/SN — just normality).
#assert_no_axioms FX1Poly.Typed.closedNormalConv_iff_syntacticEq
#assert_no_axioms FX1Poly.Typed.lamWithNonAppBody_blocksTableEta
#assert_no_axioms FX1Poly.Typed.normalizeFirstCanonicalizer_isIncomplete
-- STANDALONE-ENGINE CANONICITY (StandaloneEngineCanonicity, CANON-1 increment): combined closed-canonical-forms
-- over the two NON-grown engines (data-intro values + base-type codes). ★ standaloneBoolCanonicalForms = a
-- subject typed at boolTypeCell by EITHER engine is boolTrue/boolFalse (data-intro gives it; base-type is ruled
-- out since its classifier is Type@0 != boolCode, via classifierIsType0 + headGenerator/Generator.noConfusion).
-- standaloneEmptyUninhabited = nothing typed at emptyTypeCell by either engine (standalone half of SN-050).
-- dataIntroAndBaseTypeSubjectsDisjoint = the value layer and type layer never type the same term (disjoint heads).
-- The grown disjunct (HasTypeDescPi at boolCode via conv/piElim) is the remaining CANON-1 residual. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.standaloneBoolCanonicalForms
#assert_no_axioms FX1Poly.Typed.standaloneEmptyUninhabited
-- INTERVAL NATIVE-ENGINE CANONICITY (NATIVE-10, the interval twin of standaloneBoolCanonicalForms): a subject
-- typed at intervalTypeCell by EITHER standalone engine is interval0/interval1 — the two bridge-dimension
-- endpoints. The 4th/5th coordinated data-intro rows give the endpoint directly; the bool/unit rows and the
-- base-type disjunct (Type@0 != intervalCode) are ruled out by classifier-head Generator.noConfusion.
-- ★ intervalEndpointsDistinct = interval0 != interval1 (head-generator mismatch); the faithfulness companion.
-- ★ standaloneIntervalCanonicalFormsExactlyTwo = canonicity + distinctness bundled (exactly two distinct closed
-- canonical inhabitants, the interval analogue of bool's {true,false} two-element canonicity). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.standaloneIntervalCanonicalForms
#assert_no_axioms FX1Poly.Typed.intervalEndpointsDistinct
#assert_no_axioms FX1Poly.Typed.standaloneIntervalCanonicalFormsExactlyTwo
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtBoolType
#assert_no_axioms FX1Poly.Typed.closedNormalBoolCanonicalForms
#assert_no_axioms FX1Poly.Typed.closedBoolCanonicalForms
-- SYNTACTIC-ROUTE CANONICITY TARGET SIGNATURE (CanonicitySyntacticRoute, the candidate-bridge-free twin of
-- CanonicityTargetSignature.dataCanonicityFromCandidateBridge). ★ dataCanonicityFromSyntacticRoute = generic
-- SN-047/048/049 signature: standalone-engine canonicity (value engines) + grown vacuity ⟹ 3-engine canonicity,
-- with NO §5 candidate bridge (the grown vacuity is grown SN + SR-U4 + closed-normal forms, all shipped). Nat
-- (SN-048) / data (SN-049) instantiate it once their standalone canonicity + grown vacuity land.
-- boolCanonicityViaSyntacticRoute = the first instance, witnessing non-vacuity (= closedBoolCanonicalForms).
-- Eliminator-computing canonicity (4th engine HasTypeDescDataElim) is the follow-on, off this signature. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.dataCanonicityFromSyntacticRoute
#assert_no_axioms FX1Poly.Typed.boolCanonicityViaSyntacticRoute
-- ★ MILESTONE-A ELIMINATOR-LAYER SPINE: discharges the eliminator-layer frontier the VALUE-layer spine deferred.
-- Five fields, one per data eliminator, each a shipped unconditional computing-canonicity theorem: bool
-- (boolElimValueCanonicity, value-branch engine, one ι-step), nat (natElimCopyComputesToNumeral, RECURSIVE
-- IH-threaded copy fold), list (listElimLengthComputesToNumeral, RECURSIVE length fold), option/either
-- (closedOption/EitherMatchIntoBoolComputes, firing-64 typed match-into-bool). Every closed well-formed
-- eliminator instance reduces to a canonical value; zero-axiom. Honest scope: this is the per-eliminator
-- computing layer, NOT a unified eliminator:dataType judgment (the combined intro/elim table-residency, whose
-- formation/grown half GTL-18/20 is shipped, data-elim half open). Advances #556/#1138.
#assert_no_axioms FX1Poly.Typed.eliminatorLayerCanonicitySpineHolds
#assert_no_axioms FX1Poly.Typed.dataCanonicityFromGrownRigidity
#assert_no_axioms FX1Poly.Typed.boolCanonicityViaGrownRigidity
-- ★ SN-049: CLOSED DATA CANONICITY for Option/List/Product(Σ)/Either(Sum) (ClosedDataCanonicity, the bulk of the
-- closed-data-canonicity family after bool SN-047 + nat SN-048). Each is the SAME per-type instantiation of the
-- generic grown-rigidity packaging (dataCanonicityFromGrownRigidity): the standalone arm is the shipped
-- subjectIs<Type>Constructor inversion (the data-intro term IS a constructor, so StepStar.refl), and the two
-- Conv-rigidities are the shipped <code>_not_piTyCode / _not_universeCode from the closed-NORMAL companions
-- (OptionCanonicalForms / ListCanonicalForms / ProductEitherCanonicalForms). Product/Either use piTyCode_not_conv
-- flipped (.sym) since they are FLAT-table formers. The grown-vacuity disjunct is derived inside. ★ the four
-- closed<X>CanonicalForms = SN-049: a closed term at the data type code (intro OR grown engine) reduces to a
-- constructor. The .smoke witnesses (optionNone / nil / pair / eitherInl of universe codes) prove non-vacuity.
-- Unit deferred (its type-code rule-out not yet landed; reducibility-route candidate shipped #720). The recursive
-- eliminator-computing canonicity (#1138) is the follow-on. Zero-axiom.
-- ELIMINATOR-ENGINE CLOSED-NORMAL VACUITY: retired by NATIVE-43 — the per-engine vacuity statements
-- (BoolElimClosedNormalForms / BoolElimArbitrarySubjectCanonicity / MatchClosedNormalForms) named the
-- bespoke elim judgments; their content (a closed eliminator on a closed value scrutinee always
-- ι-fires) is carried by the union lane master's eliminator arms (every elim arm refutes normality
-- through the scrutinee IH) and the per-lane closed-normal corollaries over the ONE judgment.
#assert_no_axioms FX1Poly.Typed.boolElimValueCanonicity
-- GROWN CLOSED-NORMAL CLASSIFIER SHAPE (GrownClosedNormalClassifierShape, CANON-1 generalization): the POSITIVE
-- characterization behind every data-classifier rule-out. ★ closedNormalClassifierIsFunctionOrType = a closed
-- normal grown-typed term's classifier is Conv a Π-code OR Conv a universe code (the grown engine inhabits only
-- FUNCTION types via λ + UNIVERSES via formers, nothing else — dual of closedNormalFunctionIsLambda/TypeIsFormer).
-- noClosedNormalTermAtDataClassifier = the rule-out corollary (classifier Conv neither → no closed-normal grown
-- inhabitant), the reusable engine subsuming boolType/emptyType. ★ noClosedNormalTermAtSigmaType = NEW Σ instance
-- (grown has Σ-formation, no Σ-introduction). closedNormalSigmaTypeUninhabited = combined 3-engine: no engine
-- inhabits a Σ-type yet (honest current state until DI-2 Σ-intro). Unconditional (classifier read at normal subject).
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedNormalClassifierIsFunctionOrType
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtDataClassifier
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtSigmaType
#assert_no_axioms FX1Poly.Typed.closedNormalSigmaTypeUninhabited
-- EMPTY-TYPE COMBINED CONSISTENCY (ClosedNormalEmptyConsistency, CANON-1c instance): the consistency-type twin of
-- closedNormalSigmaTypeUninhabited. noClosedNormalTermAtEmptyTypeViaGeneric = the grown empty rule-out re-derived
-- via the CANON-1c corollary noClosedNormalTermAtDataClassifier (emptyTypeCell Conv neither Π nor universe code,
-- via Conv.piTyCode_not_emptyTypeCode/.universeCode_not_emptyTypeCode + .sym) — demonstrates the abstraction
-- subsumes the concrete noClosedNormalTermAtEmptyType. ★ closedNormalEmptyTypeUninhabited = combined 3-engine: NO
-- engine (data-intro/base-type/grown) inhabits Empty for closed-normal subjects → the new standalone engines
-- PRESERVE consistency. Unconditional (classifier read at normal subject). Full closed consistency = SN-050/CON-A5.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtEmptyTypeViaGeneric
#assert_no_axioms FX1Poly.Typed.closedNormalEmptyTypeUninhabited
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtProductType
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtEitherType
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtOptionType

-- CAN-4/CAN-5 RETIRED by NATIVE-42: the TypedByValueEngine zoo mini-union and its
-- closedNormalSubjectHeadCombined / closedNormalNatCanonicalFormsCombined assemblies are
-- superseded by the ONE-judgment NATIVE-38 union lane master and its per-lane corollaries
-- (HasTypeUnion.closedNormalLaneCanonicalForms + closedNormalNatCanonicalForms etc.,
-- gated in AuditHasTypeUnionCanonicalForms and re-verified in CapstoneSignoff).

#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtListType
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.noClosedNormalTermAtIdType
-- DATA-CANONICITY FOUNDATION: CanonicalFormsPredicate isValue = SN ∧ (neutral ∨ reduces-to-value), the sharper
-- canonicity-bearing candidate (vs the bare SN candidate the model gives data leaves). Generic over the value
-- predicate (bool→true/false, Empty→empty pred, nat→zero/succ). CR1 (stronglyNormalizing) = first conjunct; CR3
-- (neutralExpansion) = Acc.intro over reducts' SN + Or.inl (shipped SN-candidate CR3 pattern); containsVariable
-- via vacuous CR3. CR2 DEFERRED (needs IsNeutral-closed-under-Step + per-term confluence) — so this is the
-- honest 2-of-3 foundation, NOT yet a full IsReducibilityCandidate. #672-free. Toward SN-063/047.
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.neutralExpansion
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.containsVariable
-- CR2 NOW DISCHARGED (was deferred last tick): closedUnderStep — a member's reduct stays a member, the disjunct
-- preserved by neutralClosedUnderStep (neutral case) or per-term confluence + value rigidity (reduces-to-value
-- case: value is an NF, confluence_of_localJoin_and_accessible joins the reduct with the value-chain,
-- eq_of_noStep collapses the apex onto the value). isReducibilityCandidate = the FULL CR1+CR2+CR3 bundle: the
-- canonical-forms predicate IS a Girard reducibility candidate given the two data facts (IsNeutral closed under
-- Step + data values are normal). Per-term confluence only (no global-confluence assumption). #672-free; the
-- honest unconditional foundation for data canonicity (SN-063 bool reducibility / SN-047 bool canonicity).
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.closedUnderStep
-- CANONICITY EXTRACTION (#672-free): a CLOSED candidate member cannot be neutral (IsNeutral.noClosed), so it
-- reduces to a designated value. Generic closedReducesToValue + bool specialization (closed bool member
-- reduces to true/false). The structural core of SN-047/049 canonicity; only the membership half (closed
-- well-typed term is a member) awaits the typed reducibility fundamental theorem.
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.closedReducesToValue
#assert_no_axioms FX1Poly.Core.boolClosedReducesToTrueOrFalse
-- WEAK-HEAD EXPANSION (backward closure) for the data candidate, in the regime where it HOLDS: a redex into
-- a value-reaching contractum, itself SN, is a member (r ↝ contractum ↝* value gives r ↝* value). The data
-- candidate is NOT weak-head-expansion-closed for a NEUTRAL contractum (a fired redex is non-neutral yet
-- reduces to the stuck neutral, satisfying neither disjunct) — that boundary is the honest scope, documented
-- in the file. weakHeadExpansionOfMemberNotNeutral is the directly-usable member form (ι contractum is a
-- non-neutral closed branch member). The closed-canonicity recursor-assembly step; #672-independent.
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.weakHeadExpansionOfValueReaching
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.ofStepStarReachingValue
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.weakHeadExpansionOfMemberNotNeutral
#assert_no_axioms FX1Poly.Core.boolElimCanonicalScrutineeReducesToBranch
-- ELIMINATION MEMBERSHIP (#672-free, SN-063 eliminator half): a closed boolElim on a canonical bool scrutinee
-- with member branches is ITSELF a member of the result candidate. The cell is SN (boolElim SN from the
-- members' CR1 witnesses), reduces to the selected branch (boolElimCanonicalScrutineeReducesToBranch), and that
-- closed branch member reaches a value (closedReducesToValue) — value-reaching weak-head expansion
-- (ofStepStarReachingValue, #735) lifts membership back to the cell. The recursor lands in the candidate, not
-- merely normalizes — closed-layer assembly, no fundamental theorem.
#assert_no_axioms FX1Poly.Core.boolElimClosedIsMember
-- Concrete eliminator-membership regression (DataEliminatorMembershipSmoke, SN-149 corpus seed): a CONCRETE
-- closed boolElim on canonical bool members is itself a bool-candidate member — boolElimClosedIsMember fed the
-- shipped concrete value-members compose into an actual closed inhabitant (not an alias). The data-eliminator
-- membership layer (bool/Σ/option/either/idJ/idStrictRec/refl + recursive nat/list) is complete; this exercises it.
#assert_no_axioms FX1Poly.Core.boolElimClosedMembershipSmoke
-- Concrete idJ / idStrictRec membership regression (DataEliminatorMembershipSmoke, SN-149 corpus): the closed
-- idJ / idStrictRec cells with base case boolTrue and witness (refl boolTrue) are themselves bool-candidate
-- members via idJClosedIsMember / idStrictRecClosedIsMember fed the refl member (witness inner term step-normal
-- by decide) and boolTrueCell_isMember — extending the concrete eliminator-membership corpus past boolElim.
#assert_no_axioms FX1Poly.Core.idJClosedMembershipSmoke
#assert_no_axioms FX1Poly.Core.idStrictRecClosedMembershipSmoke
-- Concrete fst / snd PROJECTION membership regression (DataEliminatorMembershipSmoke, SN-149 corpus): the closed
-- fst / snd cells over the canonical pair (boolTrue, boolFalse) are bool-candidate members via fstClosedIsMember /
-- sndClosedIsMember. The component obligation (∀ first second, scrutinee ↝* pairCell _ _ → member) is discharged by
-- inversion: the pair is a structural normal form (isStepNormalForm_blocks_step on `by decide`), so eq_of_noStep
-- forces the reach reflexive and the mkGen/childCons injection (scope/shift/restShifts/childHead/childTail, five
-- outputs) pins the component to the canonical bool value. The value-PROJECTING half of the corpus, concrete.
#assert_no_axioms FX1Poly.Core.fstClosedMembershipSmoke
#assert_no_axioms FX1Poly.Core.sndClosedMembershipSmoke
-- Concrete optionMatch / eitherMatch BRANCH-APPLYING membership regression (DataEliminatorMembershipSmoke,
-- SN-149 corpus): the closed optionMatch (on none) / eitherMatch (on inl boolTrue) over the constant branch
-- λ_. boolTrue are bool-candidate members via optionMatchClosedIsMember / eitherMatchClosedIsMember. The
-- branch-respect-SN obligation (branch applied to an arbitrary SN argument lands in the candidate) is
-- discharged by constLamBoolTrue_respectsSN: app (λ_. boolTrue) value β-reduces (WeakHeadStep.beta.toStep,
-- subst0 boolTrue value = boolTrue definitional) to the bool value boolTrue, SN by appLamBoolTrue..., lifted by
-- ofStepStarReachingValue. The "constant-branch weak-head expansion" — completes the non-recursive eliminator
-- smoke corpus (only recursive natElim/natRec/listElim remain deferred).
#assert_no_axioms FX1Poly.Core.constLamBoolTrue_app_stepStar
#assert_no_axioms FX1Poly.Core.constLamBoolTrue_respectsSN
#assert_no_axioms FX1Poly.Core.optionMatchClosedMembershipSmoke
#assert_no_axioms FX1Poly.Core.eitherMatchClosedMembershipSmoke
-- Concrete recursive-eliminator BASE-CASE membership regression (DataEliminatorMembershipSmoke, SN-149 corpus):
-- natElim/natRec on natZero and listElim on listNil fire root-ι to the base branch with NO recursion, so the
-- cell is SN by the branch-SN-only helper (natElimZero_isStronglyNormalizing_of_branches and twins — no
-- per-predecessor recursor-SN obligation), and ofStepStarReachingValue lifts the base-branch member. The SN-061/
-- 062/064 base half at concrete witnesses; the IH-carrying succ/cons case remains the lone deferral.
#assert_no_axioms FX1Poly.Core.natElimZeroClosedMembershipSmoke
#assert_no_axioms FX1Poly.Core.natRecZeroClosedMembershipSmoke
#assert_no_axioms FX1Poly.Core.listElimNilClosedMembershipSmoke
#assert_no_axioms FX1Poly.Core.pairCanonicalScrutineeProjectsToComponents
#assert_no_axioms FX1Poly.Core.idJCanonicalWitnessReducesToBase
#assert_no_axioms FX1Poly.Core.idStrictRecCanonicalWitnessReducesToBase
-- IDENTITY-ELIMINATOR MEMBERSHIP (#672-free, the SN-068/069 elimination half, closed-layer): a closed idJ/
-- idStrictRec whose witness is a canonical identity member and whose base case is a member of a result candidate
-- is ITSELF a member of that candidate. The exact clean analogue of boolElimClosedIsMember — idJ/idStrictRec are
-- the non-growing (passive-base) eliminators whose single iota selects the base case DIRECTLY from the witness
-- position (no payload app, no recursion). The cell is SN (idJ/idStrictRec_isStronglyNormalizing_of_strongly_
-- normalizing_base, the SN-base strengthening, on the members' CR1 SN), reduces to the base case (idJ/
-- idStrictRecCanonicalWitnessReducesToBase), and that closed base-case member reaches a value (closedReducesTo-
-- Value) — value-reaching weak-head expansion (ofStepStarReachingValue, #735) lifts membership to the cell. The
-- recursor lands in the candidate, not merely normalizes; no fundamental theorem used.
#assert_no_axioms FX1Poly.Core.idJClosedIsMember
#assert_no_axioms FX1Poly.Core.idStrictRecClosedIsMember
#assert_no_axioms FX1Poly.Core.optionMatchCanonicalScrutineeReduces
#assert_no_axioms FX1Poly.Core.eitherMatchCanonicalScrutineeReduces
-- APPLIED-BRANCH eliminator MEMBERSHIP (#672-free, the SN-065/066 elimination half, closed-layer): a closed
-- optionMatch/eitherMatch whose scrutinee is a canonical member and whose branches RESPECT SN arguments (map SN
-- args to result-candidate members) is ITSELF a member. The applied-branch twin of boolElim/idJ closed
-- membership — the some/inl/inr ι applies the branch to the wrapped payload, so the cell-SN ingredient is the
-- SN-from-SN-branches matcher lemma (someContractumTerminates from branchRespectsSN's CR1), and the contractum
-- app branch payload reaches a value because the payload is SN (canonical scrutinee subterm via descendStepStar
-- + value-subterm) and branchRespectsSN payload is a member. ofStepStarReachingValue (#735) lifts to the cell.
#assert_no_axioms FX1Poly.Core.optionMatchClosedIsMember
#assert_no_axioms FX1Poly.Core.eitherMatchClosedIsMember
-- PROJECTION eliminator MEMBERSHIP (#672-free, the SN-058 elimination half, closed-layer): a closed fst/snd on
-- a canonical pair scrutinee whose projected component is a result-candidate member is ITSELF a member. The
-- projection twin of the branch-eliminator membership, completing the closed-membership track for ALL
-- non-recursive eliminators. Cell SN is the shipped fst/snd_isStronglyNormalizing_of_argument (contractum is a
-- subterm, no respect-hypothesis); pairCanonicalScrutineeProjectsToComponents reduces the cell to the component;
-- firstComponentMember/secondComponentMember (conditional on the witnessed scrutinee ->* pairCell) is a member,
-- so reaches a value; ofStepStarReachingValue (#735) lifts to the cell.
#assert_no_axioms FX1Poly.Core.fstClosedIsMember
#assert_no_axioms FX1Poly.Core.sndClosedIsMember
-- RECURSIVE eliminator MEMBERSHIP (#672-free, the deferred half of SN-061, closed-layer): a closed natElim/
-- natRec on a member Nat scrutinee with a reducible (function-space) succ branch is ITSELF a member. The
-- recursive twin of the eliminator-membership track — instantiates natElim/natRecValueReducibility (#732) at the
-- closed data candidate (headExpand from weakHeadExpansionOfMemberNotNeutral + WeakHeadStep.toStep + IsNeutral.
-- noClosed), discharges redexStronglyNormalizing + cell SN via the natElim/natRec SN-from-SN-branches recursors
-- (prior tick), lifts the numeral-case membership through the scrutinee congruence by ofStepStarReachingValue
-- (#735). succContractumTerminates is the honest recursor-SN IH-premise (the same conditional-arm discipline
-- #732 uses for redexStronglyNormalizing).
#assert_no_axioms FX1Poly.Core.natElimClosedIsMember
#assert_no_axioms FX1Poly.Core.natRecClosedIsMember
-- The list twin (deferred half of SN-064, closed-layer): a closed listElim on a member List scrutinee with a
-- reducible (3-argument function-space) cons branch is ITSELF a member. Instantiates listElimValueReducibility
-- (#733) at the closed data candidate; consBranchApplication takes the head in isStepNormalForm form (not SN)
-- and the tail as IsListValue; consContractumTerminates is the honest recursor-SN IH-premise.
#assert_no_axioms FX1Poly.Core.listElimClosedIsMember
-- SCONING LEG (Path C, the INDEPENDENT canonicity route; SN-092/100): the FIRST concrete data-type sconing
-- witness. boolCanonicityScone instantiates the generic BKS SconingWitness for bool with the SHARP canonical-form
-- notion (reduces to true/false): computable = bool candidate, EXTRACTION discharged #672-free by
-- boolClosedReducesToTrueOrFalse, fundamental (well-typed bool -> candidate member = the FT) the explicit sole
-- obligation. boolCanonicityViaSconing = SconingWitness.canonicity applied: given fundamental, closed well-typed
-- bool reduces to true/false. Shows the sconing route reaches the SAME bool canonicity as Tait, modulo the SAME
-- #672 fundamental — extraction is free, so Path C adds no obligation beyond Path A's. No fundamental proven here.
#assert_no_axioms FX1Poly.Core.boolCanonicityScone
#assert_no_axioms FX1Poly.Core.boolCanonicityViaSconing
-- GENERIC data-canonicity sconing witness (SN-048/049/093): generalizes the bool witness above (a SPECIAL CASE).
-- EVERY data candidate shares ONE uniform #672-free extraction (CanonicalFormsPredicate.closedReducesToValue,
-- generic in the value predicate), so dataCanonicityScone is parametric in isValue: computable = data candidate,
-- extraction = the uniform closedReducesToValue, fundamental (well-typed -> candidate member) the explicit sole
-- obligation. dataCanonicityViaSconing = canonicity applied generically. nat/list/option/either/pair instances
-- are one-line specializations at the concrete value predicates — the "one functor => canonicity for all data"
-- realization (toward SN-110), each the §3.12 canonicity headline per type via Path C. No fundamental proven here.
#assert_no_axioms FX1Poly.Core.dataCanonicityScone
#assert_no_axioms FX1Poly.Core.dataCanonicityViaSconing
#assert_no_axioms FX1Poly.Core.natCanonicityViaSconing
#assert_no_axioms FX1Poly.Core.listCanonicityViaSconing
#assert_no_axioms FX1Poly.Core.optionCanonicityViaSconing
#assert_no_axioms FX1Poly.Core.eitherCanonicityViaSconing
#assert_no_axioms FX1Poly.Core.pairCanonicityViaSconing
#assert_no_axioms FX1Poly.Core.identityCanonicityViaSconing
-- modIntro (modal box) canonicity via sconing (SN-073): the modal-box former joins the generic sconing witness
-- (isModIntroValue), completing canonicity-via-sconing coverage to ALL formers with a canonical-forms candidate
-- (data + modal box). #672-free extraction, conditional only on the per-type fundamental, so genuinely unblocked.
#assert_no_axioms FX1Poly.Core.modIntroCanonicityViaSconing
-- BKS BUNDLING CAPSTONE for the data axis (SN-096/110): one fundamental obligation => BOTH metatheorems.
-- DataMetatheory bundles normalization (every well-typed term is SN) + canonicity (reduces to a constructor).
-- dataMetatheoryViaSconing: from the single fundamental (well-typed -> candidate member), normalization is the
-- candidate's CR1 first conjunct (stronglyNormalizing), canonicity is the closed extraction
-- (closedReducesToValue = dataCanonicityViaSconing). The data-axis realization of "one functor => many
-- metatheorems" (BKS sconing-is-enough). Both halves #672-free; the shared fundamental is the sole #672 gate.
-- Does NOT flip the Tier-0 ln.hasBKSMetatheoryPackage flag (that tracks the categorical glued-model package).
#assert_no_axioms FX1Poly.Core.DataMetatheory
#assert_no_axioms FX1Poly.Core.dataMetatheoryViaSconing
-- CONSISTENCY via the sconing leg (SN-050/053): the third corner of the sconing-leg triad (normalization +
-- canonicity + consistency). consistencyScone is the sconing witness at the empty type — computable = the empty
-- candidate, canonical-form notion the DEGENERATE fun _ => False (the empty type has no canonical forms),
-- EXTRACTION the #672-free emptyHasNoClosedMember (no closed term inhabits the empty candidate, as a closed
-- member would reduce to a value but an empty value is False). consistencyViaSconing = canonicity applied:
-- given the fundamental, every closed well-typed empty term yields False. Consistency IS canonicity at the
-- empty type. The fundamental (closed well-typed empty -> member) is the explicit sole #672 obligation.
#assert_no_axioms FX1Poly.Core.consistencyScone
#assert_no_axioms FX1Poly.Core.consistencyViaSconing
-- PROGRESS via the sconing fundamental (SN-058/063): the operational complement to canonicity. Where
-- canonicity says what value a closed well-typed data term reduces to, progress says a closed well-typed
-- eliminator is never STUCK. Composes the sconing fundamental (well-typed scrutinee -> candidate member,
-- the explicit #672 obligation) with the #672-free eliminator computation. Restricted to the NON-RECURSIVE
-- eliminators (boolElim branch selection, fst/snd projection) whose iota fires once with no recursive
-- sub-term; the recursive natElim/natRec/listElim only progress #672-free on their base constructor.
#assert_no_axioms FX1Poly.Core.boolElimProgressViaSconing
#assert_no_axioms FX1Poly.Core.pairProjectionProgressViaSconing
-- Progress completion for the REMAINING non-recursive eliminators (option/either case selection, idJ/idStrictRec
-- base selection): same composition pattern (fundamental + #672-free eliminator computation). With boolElim +
-- fst/snd above, this closes the progress track for EVERY non-recursive data eliminator — never stuck on
-- well-typed input, modulo the one shared #672 fundamental.
#assert_no_axioms FX1Poly.Core.optionMatchProgressViaSconing
#assert_no_axioms FX1Poly.Core.eitherMatchProgressViaSconing
#assert_no_axioms FX1Poly.Core.idJProgressViaSconing
#assert_no_axioms FX1Poly.Core.idStrictRecProgressViaSconing
-- Progress for the RECURSIVE data eliminators (RecursiveEliminatorProgressViaSconing.lean, SN-061/SN-064): lifts
-- the exclusion noted above. The recursive succ/cons ι re-invokes the eliminator, which the prior progress file
-- said "needs Tait" — that Tait piece is RecursorClosedMembership (natElim/natRec/listElimClosedIsMember, the
-- #672-free scrutinee-reduction half, fed the honest recursor-SN IH-premise). Threads the sconing fundamental
-- (well-typed Nat/List scrutinee -> data-candidate member) into the scrutinee position and reads off
-- closedReducesToValue: a well-typed recursor with a reducible branch interface REDUCES TO A VALUE. The SN-061/
-- SN-064 canonicity payoff via the sconing leg, closing the recursive corner of the eliminator-progress track.
#assert_no_axioms FX1Poly.Core.natElimProgressViaSconing
#assert_no_axioms FX1Poly.Core.natRecProgressViaSconing
#assert_no_axioms FX1Poly.Core.listElimProgressViaSconing
-- A normal value is a member of its candidate (the generic constructor-reducibility helper).
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.memberOfValue
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.canonicalSplit
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.closedNormalIsLambda
#assert_no_axioms FX1Poly.Tier0.witnessScone_semanticIsCanonical
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectRootGeneratorGeneric

-- RAW NON-SN — the honest NEGATIVE counterpart to SN-043 (five-layer-defense L1, §27.3). SN-043 proves
-- WELL-TYPED terms are strongly normalizing; this proves the RAW Step relation is NOT (Ω = (λx.x x)(λx.x x)
-- β-steps to itself, so it is not Acc StepSuccessor), confirming the typing restriction is load-bearing and
-- that global raw SN (HasStrongNormalization) is FALSE, not merely unproved. The first non-SN witness in the
-- kernel. notAccessibleOfSelfLoop is the general Acc self-loop fact; divergentOmega_stepsToSelf is Step.beta
-- (the subst0 of the self-applicator into its body computes to Ω definitionally).
#assert_no_axioms FX1Poly.Typed.divergentOmega_stepsToSelf
#assert_no_axioms FX1Poly.Typed.notAccessibleOfSelfLoop
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectHeadHasRoleOrIsUniverseCode
#assert_no_axioms FX1Poly.Typed.metatheoryFuzzFamily_progress
#assert_no_axioms FX1Poly.Typed.metatheoryFuzzConstantFamily_progress
#assert_no_axioms FX1Poly.Typed.metatheoryFuzzLambdaFamily_progress
#assert_no_axioms FX1Poly.Typed.crossRef_progress
#assert_no_axioms FX1Poly.Typed.crossRef_consistency
#assert_no_axioms FX1Poly.Typed.crossRef_universePredicativity
#assert_no_axioms FX1Poly.Typed.consistency_hasClassicalPrecedent
#assert_no_axioms FX1Poly.Typed.formationMetatheory_progress
#assert_no_axioms FX1Poly.Typed.grownMetatheory_progress
#assert_no_axioms FX1Poly.Typed.grownMetatheory_preservationBeta
#assert_no_axioms FX1Poly.Typed.grownMetatheory_preservationFormerArm
#assert_no_axioms FX1Poly.Typed.incompleteMetatheory_missingProgress

-- SN-082 (DataReducibilityCoverage): the reducibility-coverage gate over the ten data-former families.
-- `hasReducibilityCandidate` is the total dependent dispatch — every family's CanonicalFormsPredicate is a
-- full Girard candidate (each arm its OWN shipped candidate, indexed by valuePredicate so no cross-family
-- discharge). A regression gate: adding a DataFormerFamily ctor without a candidate fails to compile.
-- Non-vacuity: bool's candidate is inhabited (boolTrueCell); empty's is the bottom (no closed member).
#assert_no_axioms FX1Poly.Core.DataFormerFamily.valuePredicate

/- The piElim-residual whnf DISPATCHER (PinnedReflectionPiElimDispatcher): the FULL residual
reduces to the two head-specific residuals (λ-after-whnf + neutral-reduct-after-whnf, the latter's
bare-var instance pre-discharged) via grown-wf SN → normalize → SR-star → the wf-FREE canonical
forms (copies of the shipped open canonical forms with the vestigial formation-wf premise
deleted). -/

#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.normalSubjectCanonicalOrNeutralOfTyping
#assert_no_axioms FX1Poly.Typed.cascadeAnchor_canonicalFormsBrick
#assert_no_axioms FX1Poly.Typed.canonicalForms_isBoundedBricks
#assert_no_axioms FX1Poly.Typed.cost_discriminates_dispatch_vs_canonicalForms
