import FX1PolyAudit.DependencyAudit
import FX1Poly.Core.Metatheory.Reducibility.Core.DataReducibilityCoverage
import FX1Poly.Core.Metatheory.Reducibility.Candidates.DataTaitCandidate
import FX1Poly.Core.Metatheory.Reducibility.Candidates.FlatCodeTaitCandidate
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FlatCodeCanonicalForms
import FX1Poly.Typed.Ledger.MilestoneASpineValueLayer
import FX1Poly.Typed.Ledger.MilestoneAEliminatorLayerSpine
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimComputingCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicityTyped
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchGeneralBranchCanonicity
import FX1Poly.Typed.Ledger.MetatheoryParityLedger
import FX1Poly.Typed.Engine.Classifier.TypingContext
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeShape
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeConversion
import FX1Poly.Typed.Engine.Formation.SigmaCodeShape
import FX1Poly.Typed.Engine.Formation.ListCodeShape
import FX1Poly.Typed.Engine.Formation.ListFormationSmoke
import FX1Poly.Typed.Engine.Formation.OptionCodeShape
import FX1Poly.Typed.Engine.Formation.OptionCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.OptionFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationOptionFromTelescope
import FX1Poly.Typed.Engine.Formation.OptionFormationSmoke
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDesc
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescDecidable
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElim
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescValidity
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescClosedForms
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFormerTelescopeInversion
import FX1Poly.Typed.Engine.Formation.DataFormerInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescUniqueness
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPi
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaCoherence
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionGrown
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionComputes
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiWeakening
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiSubstitution
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiValidity
import FX1Poly.Typed.Ledger.Misc.ConvCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvBoolCodeRigidity
import FX1Poly.Typed.Engine.Formation.ConvFormationFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvCrossTableFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvDataCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.EmptyTypeCodeConvRigidity
import FX1Poly.Typed.Ledger.Inversion.EmptyTypeValueInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FormationCanonicalForms
import FX1Poly.Typed.Ledger.Inversion.PiTypeFunctionInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalForms
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafety
import FX1Poly.Typed.Engine.Formation.FormationTypeSafety
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsNonVacuity
import FX1Poly.Typed.Corpus.Smoke.GrownBetaRedexInAction
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgress
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownOpenCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafetyUnconditional
import FX1Poly.Typed.Engine.Formation.FormerStepInversionGeneric
import FX1Poly.Typed.Metatheory.SubjectReduction.SubjectReductionAtFormerGeneric
import FX1Poly.Typed.Engine.WfContext.WfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescValidity
import FX1Poly.Typed.Engine.WfContext.WfContextDescUniqueness
import FX1Poly.Typed.Engine.WfContext.WfContextDescPi
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiFromWfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiClassifierValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiFunctionComponentValidity
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionDescPi
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionMutual
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnv
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAt
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvTypeVariable
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprFT
import FX1Poly.Typed.Metatheory.Reducibility.Pi.AbstractionNonDependentUnderSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprReducibleLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermFundamentalLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInversionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprClosureLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermRenameLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1Poly.Typed.Metatheory.SimplyTyped.MilestoneA0SimplyTypedFloor
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1Poly.Tier0.FxRenamingCategory
import FX1Poly.Tier0.FxBaseRenamingCategory
import FX1Poly.Tier0.FxBaseRenamingVecCategory
import FX1Poly.Tier0.FxBaseRenamingVecIsomorphism
import FX1Poly.Tier0.FxBaseRenamingVecTabulate
import FX1Poly.Tier0.FxBaseRenamingVecPreimage
import FX1Poly.Tier0.FxBaseRenamingVecTryTabulate
import FX1Poly.Tier0.FxBaseRenamingVecRMC
import FX1Poly.Tier0.FxBaseRenamingVecGlobalSections
import FX1Poly.Tier0.FxBaseRenamingVecSconingPreservation
import FX1Poly.Tier0.FxBaseSubstVec
import FX1Poly.Tier0.FxBaseSubstCategory
import FX1Poly.Tier0.FxBaseSubstWeakening
import FX1Poly.Tier0.FxBaseSubstComprehension
import FX1Poly.Tier0.FxBaseSubstSingleton
import FX1Poly.Tier0.FxBaseSubstGlobalSections
import FX1Poly.Tier0.FxBaseSubstScone
import FX1Poly.Tier0.FxBaseSubstWitnessScone
import FX1Poly.Tier0.FxBaseSubstConcreteScone
import FX1Poly.Tier0.IsomorphismCategorical
import FX1Poly.Tier0.FxThinScopeRMC
import FX1Poly.Tier0.FxThinScopeGlobalSections
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1Poly.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1Poly.Core.Rewriting.Reduction.Head.RootStepDispatch
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnce
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1Poly.Core.Rewriting.Normalize.Normalize
import FX1Poly.Core.Rewriting.Normalize.NormalizeSteps
import FX1Poly.Core.Rewriting.Conversion.ConvDecisionSteps
import FX1Poly.Core.Rewriting.Normalize.NormalizeMeta
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsWeakHeadExpansion
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.BoolElimCanonicalComputation
import FX1Poly.Core.Eliminators.Bool.BoolElimClosedMembership
import FX1Poly.Core.Eliminators.Core.DataEliminatorMembershipSmoke
import FX1Poly.Core.Metatheory.Canonicity.SigmaProjectionCanonicalComputation
import FX1Poly.Core.Metatheory.Canonicity.IdentityEliminatorCanonicalComputation
import FX1Poly.Core.Eliminators.Identity.IdEliminatorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.OptionEitherMatchCanonicalComputation
import FX1Poly.Core.Eliminators.Match.MatchClosedMembership
import FX1Poly.Core.Eliminators.Sigma.SigmaProjectionClosedMembership
import FX1Poly.Core.Eliminators.Recursor.RecursorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.RecursiveEliminatorBaseComputation
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.DataCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.ModalCanonicityViaSconing
import FX1Poly.Core.Metatheory.Sconing.DataMetatheoryViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1Poly.Core.Metatheory.Sconing.ConsistencyViaSconing
import FX1Poly.Core.Eliminators.Core.DataEliminatorProgressViaSconing
import FX1Poly.Core.Eliminators.Recursor.RecursiveEliminatorProgressViaSconing
import FX1Poly.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.UnitCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EmptyCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingSubst
import FX1Poly.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1Poly.Core.Metatheory.Normalization.Core.WeakNormalization
import FX1Poly.Core.Rewriting.Normalize.NormalFormUnique
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevels
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllFormerChildren
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPiIntro
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Pi.NeutralFuelStability
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiTypeSaturationReassembly
import FX1Poly.Typed.Metatheory.Reducibility.Pi.StrongNormalizingAllLevelPiComponents
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescopePositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllCanonicalCandidate
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllVectorPremises
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllNonDependentBinders
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtUniformVectorPremises
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFundamentalVectorFromFormation
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFundamentalAtAllFromGenFormation
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClosedLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.TypeFundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LeveledContext
import FX1Poly.Typed.Corpus.Smoke.ClosedSNSmoke
import FX1Poly.Typed.Corpus.Smoke.UntypedOmegaNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.StepNonDeterministic
import FX1Poly.Typed.Ledger.Misc.ConvValueDiscrimination
import FX1Poly.Typed.Corpus.Smoke.TypedLambdaDerivations
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleans
import FX1Poly.Typed.Corpus.Church.Core.TypedChurchNegation
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumerals
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIteration
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralDiscrimination
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralThree
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralTyping
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralInhabitants
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralComputeGeneral
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralAddition
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralMultiplication
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralSemiringLaws
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIsZero
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleanOperations
import FX1Poly.Typed.Corpus.Smoke.TypedFragmentAcyclicity
import FX1Poly.Typed.Corpus.Smoke.UnboundedGrowthNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointDivergence
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointCombinator
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryLogic
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryCompleteness
import FX1Poly.Typed.Corpus.Church.Combinators.SymbolicSCombinatorRule
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairs
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairsInjective
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSums
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsDisjoint
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsGeneral
import FX1Poly.Typed.Corpus.Church.Lists.ChurchLists
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListIsEmpty
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAny
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAll
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBooleanComplementLaws
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBoolXor
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListFirstOr
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSucc
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSuccApplies
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListLength
import FX1Poly.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1Poly.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1Poly.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseNoTop
import FX1Poly.Typed.Metatheory.Universe.TypedUniversePredicative
import FX1Poly.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1Poly.Typed.Corpus.Progress.ClosedNormalForm
import FX1Poly.Typed.Metatheory.Normalizer.ClosedNonConvertibility
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTyping
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiStronglyNormalizingFromFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVecTypeVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConsistency
import FX1Poly.Typed.Engine.Formation.HasTypeFormationNoLambdaApplication
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleSemanticRules
import FX1Poly.Typed.Engine.Formation.ListCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.ListFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberFormation
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeInversion
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeReach
import FX1Poly.Typed.Engine.RuleTables.FlatDescTelescope
import FX1Poly.Typed.Metatheory.Canonicity.Core.StandaloneEngineCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.CombinedBoolCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedBoolCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicitySyntacticRoute
import FX1Poly.Typed.Metatheory.Canonicity.Core.GrownRigidityCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedNatCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimValueCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.NatElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulArithmetic
import FX1Poly.Typed.Metatheory.Reducibility.Core.ClosedNumeralSubstInvariant
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulMul
import FX1Poly.Typed.Corpus.Faithfulness.ValueElimHostFold
import FX1Poly.Typed.Corpus.Faithfulness.RecursorHostFold
import FX1Poly.Typed.Metatheory.Canonicity.Core.ListElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.ListElimFaithfulLength
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicity
import FX1Poly.Typed.Corpus.Progress.GrownClosedNormalClassifierShape
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ClosedNormalEmptyConsistency
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ProductEitherCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.OptionCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ListCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.IdCanonicalForms
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiFormerMembership
import FX1Poly.Typed.Engine.Formation.FormerChildrenReducible
import FX1Poly.Typed.Metatheory.Reducibility.Telescope.TelescopeReducible
import FX1Poly.Typed.Metatheory.Universe.UniverseDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsInduction
import FX1Poly.Typed.Metatheory.Reducibility.Pi.ReducibleTypeAtAllLevelsPiNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsWhnfDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsPiDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsPiMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsHeadExpand
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsConv
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Strengthening.RouteAObstruction
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelDiagnosis
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelMeasure
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibility
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibilitySmoke
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPi
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedLevelIrrelevance
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseFormationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCanonicalMemberCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationFromExistence
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGeneralDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSingleLevelPi
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiAboveThreshold
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormerAtLevel
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleTypeLevelLift
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiArmDischarge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedApplicationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedConvMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberForwardClosed
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMemberBetaExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberWeakHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedAbstractionMember
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAbstractionUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiElim
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalConv
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAmbientLevelBridge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrow
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiIntro
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedClosedMember
import FX1Poly.Typed.Metatheory.Denote.Telescope.DenoteKeyedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedUniformReducible
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMembershipIntro
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFormation
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFromChildMembers
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationSigmaArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedCumulativityObstruction
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibility
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedConvArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiElimArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiIntroArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedFormerEngine
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiDischarge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedAssemblyBridge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeProjection
import FX1Poly.Typed.Engine.Formation.FormerOutputLevelBounds
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedCodomainOpenSN
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDomainInhabitant
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationPiFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationSigmaFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationListFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedTelescopeConsSucc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGrownDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDesc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPi
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPiDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedGrownFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ClosedBoundedReducibleMember
import FX1Poly.Typed.Corpus.Smoke.ClosedStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedNeutralMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseInversion
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBindingTypeReducible
import FX1Poly.Typed.Engine.WfContext.ReducibleEnvOfWfContext
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizingUnconditional
import FX1Poly.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1Poly.Typed.Corpus.Smoke.OpenSNSmoke
import FX1Poly.Typed.Corpus.Progress.ContextValidityFails
import FX1Poly.Typed.Equality.UnitEta.UnitEtaJudgmentalEquality
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruenceGap
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruentEquality
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapse
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseIncompleteness
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeep
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseNeutralBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitNeutralSpineDetection
import FX1Poly.Typed.Equality.UnitEta.UnitSpineDetectionBoundary
import FX1Poly.Typed.Equality.UnitEta.TypeDirectedUnitReadback
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackArgumentBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackFormerChildBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackDeepSpineBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackAnnotationBoundary
import FX1Poly.Typed.Engine.Formation.FormationClassifierRigidity
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeConvDecision
import FX1Poly.Typed.Ledger.Misc.LiftedChildNormalizationFromClosure
import FX1Poly.Typed.Engine.RuleTables.TelescopeSubstitutedChildrenNormalization
import FX1Poly.Typed.Ledger.CascadeFreedomLedger
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyTargetSignature
import FX1Poly.Typed.Ledger.Bridge.CandidateBridgeEditViability
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicityTargetSignature
import FX1Poly.Typed.Metatheory.Universe.NullaryFormerFormation
import FX1Poly.Typed.Metatheory.Universe.GrownUniverseFormationStrictness
import FX1Poly.Typed.Engine.Formation.GrownFormerFormationStrictness
import FX1Poly.Typed.Engine.Classifier.GrownTypingNotUnique
import FX1Poly.Typed.Engine.Classifier.GrownEngineHonesty
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.GrownUniverseConsistency
import FX1Poly.Typed.Engine.Classifier.GrownVariableHonesty
import FX1Poly.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiLamInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiAppInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVarInversion
import FX1Poly.Typed.Metatheory.ContextConversion.VarHeadedAppContextConversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiBetaSR
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiCongruence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerCongruence
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionConditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimReduction
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionValidityReduction
import FX1Poly.Typed.Corpus.Progress.GrownMutualMetatheoryFromPiValidity
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimEquivalence
import FX1Poly.Typed.Engine.HasTypeDescPi.ContextConversion.HasTypeDescPiContextStepConversion
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionUnconditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionFlexibleUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormationFragment
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormerStep
import FX1Poly.Typed.Metatheory.ContextConversion.GenFormerValidityContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPiValidityModelNeutral
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveled
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransport
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransportUnderWf
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledCompleteness
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValid
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRename
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValidLookup
import FX1Poly.Typed.Ledger.Misc.PiElimClassifierConvResidual
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiFormerInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiDataHeadUntyped
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiRootGeneric
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedUniverseBoundedCumulativity
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedClosedTypeCodeSN
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiMemberSN
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrowMemberSN
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCodomainMemberWiring
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelSpike
import FX1Poly.Typed.Ledger.SNStrategy
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.LogRelSpec
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LevelingBridge
import FX1Poly.Typed.Metatheory.Canonicity.Core.ConsistentStratification
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingLevelFlexible
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingRefinedMotive
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingConvArm
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingPiArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingFormerArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingVariableLevelPinned
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalReduction
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalAssembly
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.SimplyTyped.HigherOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiOverNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiNeutralCodomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentlyTypedNeutralDomainFragment
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedSubsumption
import FX1Poly.Typed.Metatheory.Universe.UniverseCumulativity
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermReducibility
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiTypingNonUnique
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckOfInferred
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVariableInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiUniverseCodeInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckUniverseCode
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplicationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckFormation
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationCodomainReTyping
import FX1Poly.Typed.Engine.RuleTables.IntroRuleDesc
import FX1Poly.Typed.Engine.RuleTables.ElimRuleDesc
import FX1Poly.Typed.Engine.RuleTables.GenElimIotaComputation
import FX1Poly.Typed.Engine.Classifier.TypingRoleClassifier
import FX1Poly.Typed.Engine.Classifier.TypingRoleEngineBridge
import FX1Poly.Typed.Engine.Classifier.TypingRoleCoverage
import FX1Poly.Typed.Engine.Classifier.UntypableHeadDecision
import FX1Poly.Typed.Engine.Classifier.TypingHeadKindClassifier
import FX1Poly.Typed.Engine.Classifier.TypedBySomeEngine
import FX1Poly.Typed.Engine.Classifier.GeneratorSemanticTier
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyOverview
import FX1Poly.Typed.Engine.Classifier.StaticTypingSoundness
import FX1Poly.Typed.Engine.Classifier.SemanticTierSoundness
import FX1Poly.Typed.Engine.Classifier.ClassifierRefinement
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyLedger
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionTermination
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerStepDomainFormationCodomain
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionFormerArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionInlineArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionConvOfFormationArms
import FX1Poly.Typed.Metatheory.SubjectReduction.ConsistencyConditionalOnSubjectReduction
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencySyntactic
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyOfPiElimArm
import FX1Poly.Typed.Ledger.Misc.PiElimUpToClassifierConv
import FX1Poly.Typed.Engine.Classifier.ClassifierRespectsConvRefuted
import FX1Poly.Typed.Dimensions.AxisObligation.TypedCertificationStackingRefuted
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencyUnconditional
import FX1Poly.Typed.Engine.Formation.FormationNormalSmoke
import FX1Poly.Typed.Engine.Formation.BoolTypeCodeSubstrate
import FX1Poly.Typed.Engine.Formation.NatTypeCodeSubstrate
import FX1Poly.Typed.Corpus.Progress.GrownNoTypeInType
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescRigidity
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidable
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1Poly.Typed.Ledger.KnownUnsoundnessCorpus
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationAcyclic
import FX1Poly.Modal.SecurityNoninterferenceGeneral
import FX1Poly.Modal.GradedApplicationFlow
import FX1Poly.Typed.Ledger.MetatheoryFuzz
import FX1Poly.Typed.Ledger.FuzzCorpusConvertibility
import FX1Poly.Typed.Ledger.FuzzCorpusNormalizes
import FX1Poly.Typed.Ledger.LambdaValueFuzzFamily
import FX1Poly.Typed.Ledger.MechanizedProofCrossReference
import FX1Poly.Typed.Ledger.FormalReviewGate
import FX1Poly.Typed.Ledger.SelfVerifiedMetatheory
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengthening
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheck
import FX1Poly.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1Poly.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiImageComponents
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiRenameImage
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionContext
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiIntro
import FX1Poly.Typed.Engine.Formation.FormationPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.GrownPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimCore
import FX1Poly.Typed.Corpus.Smoke.GrownWfOpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimDispatcher
import FX1Poly.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1Poly.Typed.Metatheory.Strengthening.GuardedPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PlateauPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.NeutralReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionLamClassifierResidual
import FX1Poly.Typed.Metatheory.Strengthening.FlagCoherentReflectionCondition
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationUnique
import FX1Poly.Typed.Ledger.Misc.NeutralClassifierUnique
import FX1Poly.Typed.Ledger.Misc.NormalAppNeutral
import FX1Poly.Typed.Engine.RuleTables.TelescopeUniverseDeterminism
import FX1Poly.Typed.Engine.RuleTables.GenericFormerTelescopeInversion
import FX1Poly.Typed.Metatheory.Universe.NormalUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.ConvUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Strengthening.RenameAlongFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.PinSelectsCallerPair
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.LamReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherentMaster

/-! # FX1PolyAudit/AuditTypedStrongNormalization — typed-layer zero-axiom gates: strong normalization and the accessibility assemblies
   (semantic shard of the typed audit; gates classified by declaration topic, appended
   clusters kept together; full import block retained for namespace-sweep coverage) -/


/-! ### Strong normalization and typed conversion for the description formation engine.
    Native: subject SN (`subjectStronglyNormalizing`, the public `isStronglyNormalizing` delegating to it),
    type SN (`IsTypeDesc.isStronglyNormalizing` — the `IsTypeDesc` witness's subject IS the classifier), and
    typed-middle transitivity (`Conv.trans_of_hasTypeDescMiddle` — the unconditional raw `Conv.trans`, its
    `IsTypeDesc` premise vacuous).  The `WfContext`-validity-bound classifier-SN package
    (`classifierStronglyNormalizing` / `subjectAndClassifier*`) is scoped to the formation engine; no grown
    reducibility claim.  Cascade-free: `formerCellStronglyNormalizingOfChildren` routes through the generic
    `former_step_inv` + the N-child accessibility substrate (`StepChildrenSuccessor` /
    `accStepChildrenSuccessor_cons` / `accStepChildrenSuccessor_of_allStronglyNormalizing` /
    `formerCell_isStronglyNormalizing_of_accChildren`) rather than a per-former `by_cases isPi/isSigma` — so a new
    ≥1-child formation row extends it with no change, mirroring the cascade-free formation `subjectReduction`. -/
#assert_no_axioms FX1Poly.Core.RawTermChildren.allStronglyNormalizing
#assert_no_axioms FX1Poly.Core.accStepChildrenSuccessor_of_allStronglyNormalizing
#assert_no_axioms FX1Poly.Core.formerCell_isStronglyNormalizing_of_accChildren
#assert_no_axioms FX1Poly.Typed.formerCellStronglyNormalizingOfChildren
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.subjectStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.isStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.IsTypeDesc.isStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.classifierStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.subjectAndClassifierStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.closedSubjectAndClassifierStronglyNormalizing
-- FORMATION CLASSIFIER-SN over WfContextDesc (HasTypeDescStronglyNormalizing.lean): the classifier of a
-- HasTypeDesc-typed cell is strongly normalizing, routed through classifierIsTypeDesc then
-- IsTypeDesc.isStronglyNormalizing. A consumer of the native validity target.
-- SN-026 (cross-check route status, documented-as-deferred per its DONE): the Kripke / all-levels route
-- (HasTypeDescPiAllLevelFundamentalTheorem = HasTypeDescPi → FundamentalConclusionAtAll, the ∀-level
-- ReducibleEnvAtAllLevels shape) is the SECOND route to the unconditional FT, parallel to the SN-022/023
-- ValidTyping bridge. Its machinery is shipped + gated: the interface + its corollaries (gated below), the
-- CONDITIONAL all-levels FT fundamentalAtAllFromFormation (gated here) + allLevelFundamentalTheoremFromFormationVector
-- (gated below), and the all-levels leaf arms (FundamentalAtAllLeafArms: var/conv/piIntro). Both routes bottom out
-- at the SAME formation-FT obstruction (the var + ∀-aboveLevel former-domain content of SN-022..025); an
-- UNCONDITIONAL HasTypeDescPiAllLevelFundamentalTheorem value therefore awaits that shared discharge. Per SN-005
-- the ValidTyping bridge is PRIMARY, so this Kripke route is kept as the CROSS-CHECK and its unconditional value
-- is completed together with the primary assembly (SN-027) — not independently duplicated here.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.subjectStronglyNormalizingFromFormation
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.classifierStronglyNormalizingFromFormation
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectSubstStronglyNormalizingFromFormation
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedClassifierSubstStronglyNormalizingFromFormation
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectStronglyNormalizingFromFormation
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedClassifierStronglyNormalizingFromFormation

-- ALL-LEVEL FORMATION FT, var/conv/universeFormation discharged, genFormation factored (#496 progress).
-- The downstream SN chain (the FromFormation block above) is conditional on the formation engine HasTypeDesc
-- satisfying the FT.  This peels the three NON-former formation arms off that obligation: over the all-level
-- environment, var is off-by-one-free (fundamentalVarAtAll), conv/universeFormation dispatch to their AtAll
-- arms; the genFormation former arm (whose telescope binder obligation = the recursive
-- codomain-under-argument premise) is the sole explicit hypothesis.  Reduces the formation FT to the
-- genFormation former arm alone — the formation-engine analog of fundamentalVectorFromFormation.
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.fundamentalAtAllFromGenFormation
-- FIRST UNCONDITIONAL SN results via the level-indexed FT: concrete closed terms whose FT conclusion is built
-- directly from the shipped arms at the empty context (no recursor), discharged to plain IsStronglyNormalizing
-- by the closed-SN handoff. End-to-end validation that the arms + handoff compose into hypothesis-free SN.
#assert_no_axioms FX1Poly.Typed.universeCode_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.closedPiBetweenUniverses_stronglyNormalizing
-- The closed identity λx.x : Π Type@e. Type@e is unconditionally SN — first such result with a LAMBDA +
-- BOUND VARIABLE, composing piIntro + var arms end-to-end (the heart of the FT). Fin-1 index via ⟨0,_⟩.
#assert_no_axioms FX1Poly.Typed.closedIdentityOnUniverse_stronglyNormalizing
-- The closed β-redex (λx.x) Type@e is unconditionally SN — first such result with an APPLICATION, composing
-- piElim over (piIntro + var) and universeFormation; exercises the subst0 in piElim's conclusion end-to-end.
#assert_no_axioms FX1Poly.Typed.closedIdentityApplication_stronglyNormalizing
-- Corpus extension: the Σ-formation arm end-to-end (first unconditional SN exercising fundamentalSigma-
-- FormationLevelIndexed — the Σ twin of closedPiBetweenUniverses, non-vacuous + hypothesis-free), plus the
-- argument-DISCARDING β path: the constant λx.Type@0 (var-free piIntro body) and its erasing application
-- (λx.Type@0) Type@e (piElim where subst0 discards the argument) — the complement of the substituting identity.
#assert_no_axioms FX1Poly.Typed.closedSigmaBetweenUniverses_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.closedConstantLambda_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.closedConstantApplication_stronglyNormalizing
-- NESTED formers: a former whose CHILD is itself a former — the Π/Σ formation arms COMPOSE end-to-end into
-- hypothesis-free SN (the inner arm supplies the outer arm's binder-extended codomain premise). Π-over-Σ,
-- Σ-over-Π (the dual), and Π-over-Π (the binary function type, deepest nesting).
#assert_no_axioms FX1Poly.Typed.closedNestedPiOverSigma_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.closedNestedSigmaOverPi_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.closedNestedPiOverPi_stronglyNormalizing
-- The SN-043 TYPING HYPOTHESIS IS ESSENTIAL (UntypedOmegaNotStronglyNormalizing): the closed smokes above
-- show every well-typed closed term is SN; this is the converse witness that typing is doing real work. The
-- raw Ω = (λx.x x)(λx.x x) is a closed RAW term that β-steps to itself (omegaCombinator_betaSelfStep), hence
-- is NOT SN (omegaCombinator_notStronglyNormalizing, via accessibleElementNotSelfRelated: a self-looping
-- element cannot be Acc). Ω is untypable, so SN-043 rightly excludes it. The headline records the sharper
-- non-closure fact: λx.x x IS SN (selfApplicationLambda_stronglyNormalizing — a closed normal form) yet its
-- self-application is not, so SN is NOT preserved under application — the β-redex side condition discharged by
-- the reducibility argument is load-bearing, not decoration.
#assert_no_axioms FX1Poly.Typed.accessibleElementNotSelfRelated
#assert_no_axioms FX1Poly.Typed.selfApplicationLambda_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.applicationOfStronglyNormalizingNotAlwaysStronglyNormalizing
-- WEAK ≠ STRONG normalization in the raw calculus (WeaklyNormalizingNotStronglyNormalizing): sharper than Ω
-- above (Ω has NO normalizing path; this term DOES). The Barendregt separating example (λx.Type@0) Ω has a
-- terminating β-path to the normal form Type@0 (betaReachesBody — subst0 is identity on the nullary universe-
-- code body by computation, no cancellation lemma) AND a divergent path looping in the discarded Ω argument
-- (argumentSelfLoop, the uniform Step.cong rule stepping the second app child via StepChildren.there, fed the
-- Step Ω Ω self-step). So weakly-normalizing does NOT imply strongly-normalizing — the headline. This is WHY
-- SN-043 proves STRONG normalization: weak normalization alone permits the adversarial "reduce the discarded
-- argument forever" strategy, which typing must (and does) rule out.
#assert_no_axioms FX1Poly.Typed.discardingApplicationOnOmega_betaReachesBody
#assert_no_axioms FX1Poly.Typed.discardingApplicationOnOmega_notStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.weaklyNormalizingDoesNotImplyStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.identityOnUniverse_stronglyNormalizing
-- The ELIMINATION (application) form + concrete subject reduction (TypedLambdaDerivations, extending the
-- piIntro derivations above): identityApplicationOnUniverseCode applies the identity at Type@(e+1) to the
-- universe code Type@e (which inhabits Type@(e+1) by universeFormation — no data-code machinery), typed by
-- piElim; the result-type subst0 Type@(e+1) Type@e is defeq Type@(e+1) (constant codomain ignores the arg).
-- identityApplication_subjectReduction: the redex β-reduces to its argument Type@e and BOTH redex and reduct
-- type at the SAME Type@(e+1) — concrete subject reduction on an honest piElim derivation.
#assert_no_axioms FX1Poly.Typed.identityApplicationOnUniverseCode_hasTypeDescPi
#assert_no_axioms FX1Poly.Typed.identityApplicationOnUniverseCode_betaReducesToArgument
#assert_no_axioms FX1Poly.Typed.polymorphicIdentity_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.polymorphicIdentityInstantiation_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.polymorphicIdentityTwoArg_stronglyNormalizing
-- Σ-FORMATION in the typing engine: the generic genFormationPi arm types a dependent PAIR type, not
-- only Π. The reducibility layer already had Σ formation (fundamentalSigmaFormationLevelIndexed); these
-- are the first in the TYPING judgment (HasTypeDescPi). genFormationPiTypesBothPiAndSigmaFormers bundles
-- Π and Σ at one identical context+classifier — the conjuncts differ only in the head former, i.e. only
-- in the Generator argument to the same arm: the cascade-free typing thesis, a former is a table row.
#assert_no_axioms FX1Poly.Typed.dependentPairTypeOverTypeVariable_hasTypeDescPi
#assert_no_axioms FX1Poly.Typed.closedDependentPairType_hasTypeDescPi
#assert_no_axioms FX1Poly.Typed.closedDependentPairType_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.identityApplicationViaRuleTables_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.ValidTyping.fundamental
-- SN-022 (LevelingBridge.lean): the leveling bridge HasTypeDescPi → ∃ contextLevels subjectLevel, ValidTyping …
-- — var/conv/universeFormation arms. var + universeFormation are UNCONDITIONAL leaves (direct ValidTyping ctor
-- applications; var concludes at subjectLevel := contextLevels index, the SN-024 off-by-one dodge); conv is the
-- coordinated-input wrapper (cross-sub-derivation level coordination is the inductive assembly's job, SN-027).
-- Composed with the PROVEN ValidTyping.fundamental ⟹ unconditional dependent reducibility/SN. Binder/former
-- arms = SN-023.
#assert_no_axioms FX1Poly.Typed.validTypingBridgeVar
-- SN-043 endgame reframe (LevelingBridge.lean): hasTypeDescPiStronglyNormalizingFromTotalBridge — the SN twin of
-- hasTypeDescPiReducibleFromTotalBridge, composing the total bridge with the UNCONDITIONAL
-- ValidTyping.substStronglyNormalizing. Operationalizes the finding that ValidTyping.fundamental is unconditional
-- (composite-domain Π handled by its env-extension codomain IH), so SN-043's ONLY residual is the leveling bridge
-- (totalBridge / #662) — NOT the fuel gate HasPositiveMemberExtension… (#672), which is OFF this path.
#assert_no_axioms FX1Poly.Typed.hasTypeDescPiStronglyNormalizingFromTotalBridge
-- SN-043 headline (LevelingBridge.lean): hasTypeDescPiClosedStronglyNormalizingFromEmptyBridge — the LITERAL
-- closed SN-043 shape HasTypeDescPi .empty t T → SN t, modulo the empty-context leveling bridge. Composes with
-- the unconditional ValidTyping.closedStronglyNormalizing; uses the empty bridge (producing emptyLevelVector
-- directly) to stay coercion-free (no funext over Fin 0). The closed plain-SN specialization of the open form.
#assert_no_axioms FX1Poly.Typed.hasTypeDescPiClosedStronglyNormalizingFromEmptyBridge
-- SN-027 piElim diagnosis (read-validated against fundamentalPiElimLevelIndexed + applicationUnderSubst): the
-- piElim arm runs at a UNIFORM subjectLevel — function (: Π), argument (: domain), and result are ALL at one
-- level (applicationUnderSubst closes at any COMMON level). The per-arm block validTypingBridgePiElim (SN-023)
-- already discharges it given function+argument at a common level, so piElim needs NO further per-arm lemma; the
-- residual is purely the induction's LEVEL-ALIGNMENT of function vs argument. That alignment is clean for
-- universe-code-classified members (type codes: membership in Type@e is L-independent in its decoded-at-denote-e
-- part) but case-dependent for Π-classified function TERMS (Π-membership depends on the level). So the remaining
-- SN-027 work is the single ASSEMBLY theorem: the HasTypeDescPi induction threading contextLevels with the refined
-- motive (∀-level type-code subjects, single-level terms) + the member-level alignment for piElim + the
-- ofFormation/HasTypeDesc inversion — all per-arm ingredients (conv, type-code flexibility, piElim block) now in hand.
-- SN-027 update (infra located, prior pessimism CORRECTED): the term arms' member-level alignment is NOT
-- blocked on missing math — the reducibility layer already has a rich, gated IsReducibleMemberAtAllPositiveLevels
-- framework (.atLevel / .headExpand / .universeCode_iff / .ofUniverseMember{NonPiNonUniverse,UniverseCode,
-- PiNeutralDomain}Argument / .ofNeutralClassifier / .piTypeMemberExtension / .castAlongConvOfAllLevels +
-- IsReducibleMemberAt.extendsToAllPositiveAtUniverseCodeOfLowerTypeExtendsToAllLevels). ValidTyping itself has NO
-- syntactic level subsumption (var pins its level), so the assembly routes the TERM arms (piElim/piIntro) through
-- this all-levels MEMBER machinery (reducibility layer) rather than through syntactic ValidTyping re-leveling.
-- NET: the unconditional assembly is tractable WIRING (refined-motive HasTypeDescPi induction over existing infra),
-- not infra-blocked — the focused remaining work of SN-027.
#assert_no_axioms FX1Poly.Typed.ValidTyping.closedStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.validTyping_universeCode_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.validTyping_identity_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.validTyping_piBetweenUniverses_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.validTyping_sigmaBetweenUniverses_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.ValidTyping.substStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.validTyping_openVariable_substStronglyNormalizing
-- PER-ARM RECURSOR NON-VACUITY CORPUS (ValidTyping.lean): completing piElim + conv. betaRedex = a closed
-- β-redex (λx.x)(Type@e) SN through the piElim arm (genuinely reducing); convRefl = a universe code re-typed
-- through the conv arm (reflexive conversion — closed ValidTyping terms never have a redex type, so the arm's
-- level coordination subjectLevel/subjectLevel+1 + tarskiDecode + castAlongConv is exercised but the conversion
-- is refl). All 7 recursor arms now have a non-vacuity SN witness.
#assert_no_axioms FX1Poly.Typed.validTyping_betaRedex_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.validTyping_convRefl_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiSubstitutedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiClosedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.subjectStronglyNormalizingFromFundamentalAtAll
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectSubstStronglyNormalizingFromFundamentalAtAll
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectStronglyNormalizingFromFundamentalAtAll
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiPositiveCandidateSubstitutedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueCandidateSubstitutedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueReducibilityAndStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueReducibilityAndStrongNormalizationTheorem.fundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueReducibilityAndStrongNormalizationTheorem.substitutedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueReducibilityAndStrongNormalizationTheorem.closedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.subjectStronglyNormalizingFromPositiveCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.classifierStronglyNormalizingFromPositiveCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.subjectStronglyNormalizingFromTypeValueCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.classifierStronglyNormalizingFromTypeValueCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectSubstStronglyNormalizingFromPositiveCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedClassifierSubstStronglyNormalizingFromPositiveCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectStronglyNormalizingFromPositiveCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedClassifierStronglyNormalizingFromPositiveCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectSubstStronglyNormalizingFromTypeValueCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedClassifierSubstStronglyNormalizingFromTypeValueCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedSubjectStronglyNormalizingFromTypeValueCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedClassifierStronglyNormalizingFromTypeValueCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiPositiveCandidateFundamentalTheorem.toSubstitutedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueCandidateFundamentalTheorem.toSubstitutedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueCandidateFundamentalTheorem.toReducibilityAndStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.hasTypeDescPiTypeValueReducibilityAndStrongNormalizationTheorem_iff_typeValueCandidateFundamentalTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.typeValueReducibilityAndStrongNormalizationTheoremFromFormationVectorAndAllReducibleTypesHaveTypeValueCandidates
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.typeValueReducibilityAndStrongNormalizationTheoremFromFormationVectorAndPositiveMemberExtension
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiPositiveCandidateFundamentalTheorem.toClosedStrongNormalizationTheorem
#assert_no_axioms FX1Poly.Typed.HasTypeDescPiTypeValueCandidateFundamentalTheorem.toClosedStrongNormalizationTheorem
-- FLAT-ENGINE STRONG NORMALIZATION (#935, next increment): the flat twin of
-- HasTypeDesc.subjectStronglyNormalizing. flatFormerCellStronglyNormalizingOfChildren reuses the GENERIC
-- Core accessibility substrate (formerCell_isStronglyNormalizing_of_accChildren) with the firing-45 congruence-
-- only inversion swapped in; FlatDescTelescope.childrenStronglyNormalizing is a plain (non-mutual) structural
-- recursion calling HasTypeDesc.subjectStronglyNormalizing on each head; HasTypeDescFlat.subjectStronglyNormalizing
-- is the headline; the five closed witnesses show each flat former TYPES and is SN.

-- SN-006 (contingency spec, fallback-only): the Adjedj derivation-indexed LogRel.  Key finding: `HasTypeDescPi`
-- is Prop-valued, so a Nat derivation-size is BLOCKED (no large elim from Prop); the fallback is Prop-motive
-- structural recursion on the derivation (same scheme as ValidTyping.fundamental, impredicativity-robust).
-- The marker is the fallback's deferred TARGET statement (= the primary SN goal), a checked Prop, no obligation.
#assert_no_axioms FX1Poly.Typed.DerivationIndexedStrongNormalizationFallback
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.stronglyNormalizing
-- The full CR3 neutral leaf (generalizes containsVariable past the vacuous variable case): a STRONGLY-
-- NORMALIZING NEUTRAL term is a member of every canonical-forms candidate, by well-founded recursion on its SN
-- accessibility (reducts stay neutral via closedUnderStep, are SN-smaller, hence members by IH; neutralExpansion
-- lifts). The reducibility leaf any neutral-eliminator (stuck app/fst/boolElim over a neutral head) member
-- argument consumes; isValue-agnostic.
#assert_no_axioms FX1Poly.Core.CanonicalFormsPredicate.memberOfStronglyNormalizingNeutral
-- The GENERIC head-expansion-closed data Tait candidate (dataTaitCandidate isValue), generalizing
-- emptyTaitCandidate from the empty value set to ANY data value predicate ("SN AND every reachable normal
-- form is a value or neutral").  It is a reducibility candidate (CR1/CR2/CR3) and head-expansion-closed
-- (so it serves as a Π codomain candidate across the fundamental theorem) for every isValue; a CLOSED
-- member reduces to a VALUE (closedReducesToValue) — the candidate-bridge-ready data-canonicity payload
-- each data type code (bool/nat/…) instantiates exactly as emptyTypeCell instantiates emptyTaitCandidate.
#assert_no_axioms FX1Poly.Core.dataTaitCandidate.stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.polymorphicIdentityRedexStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.stronglyNormalizingUnderSubst
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.stronglyNormalizingClosed

-- CHURCH-ROSSER + NORMAL-FORM UNIQUENESS for simply-typed terms: the SN result fed the per-term Newman bridge
-- (`confluence_of_localJoin_and_accessible`) gives confluence (`reductsJoinUnderSubst`), and `eq_of_noStep`
-- gives normal-form uniqueness (`normalFormUnique{UnderSubst,Closed}`) — the foundation for deciding conversion
-- on the simply-typed fragment.
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.reductsJoinUnderSubst
#assert_no_axioms FX1Poly.Typed.identityStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.arrowIdentityIsSimplyTyped
#assert_no_axioms FX1Poly.Typed.arrowIdentityStronglyNormalizing
#assert_no_axioms FX1Poly.Core.Conv.decidableOfStronglyNormalizing
-- Conv.iff_normalize_eq_of_isStronglyNormalizing: the SEMANTIC NbE soundness+completeness iff — two SN terms
-- convert IFF RawTerm.normalize maps them to the SAME term (the explicit biconditional decidableOfStronglyNorm-
-- alizing is decidable_of_iff over). Sharper than iff_normalForms_eq (NFs as opaque args): RHS is a literal
-- RawTerm equality via the actual normalizer.
#assert_no_axioms FX1Poly.Core.Conv.iff_normalize_eq_of_isStronglyNormalizing

-- SN REFLECTED BY SUBSTITUTION: SN of `subst σ term` ⇒ SN of bare `term` (Acc reflected along `subst σ` via
-- Step.subst + Subrelation.accessible ∘ InvImage.accessible).  This pulls the FT's SN-of-substituted back to
-- SN-of-bare, removing the closing-substitution wart: decidableOfSimplyTypedBareClosed decides conversion of
-- the BARE closed terms themselves — the cleanest "simply-typed fragment has decidable conversion".
#assert_no_axioms FX1Poly.Core.StepStar.stronglyNormalizing_of_subst
#assert_no_axioms FX1Poly.Typed.emptyClosingSubst

-- simplyTypedBareClosedStronglyNormalizing (Milestone A0 simply-typed floor, SN half): the standalone reusable
-- form of "a closed simply-typed term is strongly normalizing". The simply-typed FT's stronglyNormalizingClosed
-- reflected to the bare term
-- via stronglyNormalizing_of_subst. With decidableOfSimplyTypedBareClosed (the decidable-Conv half) this names
-- the UNCONDITIONAL defensible-kernel floor: the simply-typed fragment has SN PROVEN (not assumed), so typing
-- alone decides conversion. Honest qualifier boundary: simply-typed fragment ONLY; broader fragments need SN-043.
#assert_no_axioms FX1Poly.Typed.simplyTypedBareClosedStronglyNormalizing
-- simplyTypedDefensibleKernel (Milestone A0 bundle witness, #666/#557): the named SimplyTypedDefensibleKernel
-- structure (SN proven + Conv decidable) witnessed by the shipped unconditional theorems
-- (simplyTypedBareClosedStronglyNormalizing + Conv.decidableOfSimplyTypedBareClosed). The formal declaration of
-- Milestone A0 over the simply-typed fragment, NOT gated on SN-043 (no SN hypothesis carried). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.simplyTypedDefensibleKernel

-- CANONICAL NORMAL FORM for closed simply-typed terms — the NORMALIZE companion to the bare-closed DECIDE.
-- stronglyNormalizingBare: bare SN (the sole use site of stronglyNormalizing_of_subst); normalForm: the
-- computable RawTerm 0; conv_normalForm / normalForm_isStepNormalForm: term ↝* its NF and NF is normal;
-- normalForm_eq_self_of_isStepNormalForm: no spurious rewriting on a normal input; conv_iff_normalForm_eq:
-- two terms convert IFF their NFs coincide (the canonical NF is a complete conversion invariant — the
-- explicit characterization behind decidableOfSimplyTypedBareClosed).
#assert_no_axioms FX1Poly.Typed.SimplyTypedTermLF.stronglyNormalizingBare

-- WEAK NORMALIZATION: a strongly-normalizing term reaches a structural normal form, with the reduction
-- chain produced by descending the `Acc StepSuccessor` witness and extracting a real Step at every
-- non-normal node.  The StepStar-existence half of normalization (uniqueness comes from confluence) —
-- the strongly-normalizing-fragment door to decidable Conv (#267) and the WHNF normalizer (#374).
#assert_no_axioms FX1Poly.Core.exists_normalForm_of_isStronglyNormalizing
#assert_no_axioms FX1Poly.Core.exists_unique_normalForm_of_isStronglyNormalizing

-- SN-FRAGMENT DECIDABLE CONV: Conv = normal-form equality on the strongly-normalizing fragment, with the
-- global StepStar.HasConfluence hypothesis of PolygraphConvergentDecision DISCHARGED per-term from the SN
-- witnesses (confluence_of_localJoin_and_accessible).  The honest raw-layer decider modulo the normalizer
-- function (#261/#480) that supplies the normal-form witnesses.
#assert_no_axioms FX1Poly.Core.Conv.iff_normalForms_eq_of_isStronglyNormalizing
#assert_no_axioms FX1Poly.Core.Conv.decidableOfNormalForms_of_isStronglyNormalizing

-- GIRARD CR BUNDLE (per-decl gates on the load-bearing reducibility-candidate primitives): the
-- IsReducibilityCandidate triple CR1/CR2/CR3 (structure fields), the base SN-is-a-candidate witness,
-- candidate-congruence under PointwiseIff, and candidate variable-membership.
#assert_no_axioms FX1Poly.Core.isStronglyNormalizing_isReducibilityCandidate
#assert_no_axioms FX1Poly.Typed.universeDomainPiMemberStronglyNormalizing
-- Member-SN companion to the shipped type-level non-dependent universe-domain arrow (universeDomainNonDependent
-- Arrow): the MEMBER half of the unconditional slice of #752 (DenoteKeyedNonDependentArrowMemberSN.lean). A
-- non-dependent arrow Type@e -> codomainBase has its codomain cross the binder as a pure weakening, so the
-- weaken-cancellation (RawTerm.weaken_subst_singleton) collapses SN-D7's per-argument codomain obligation to a
-- constant -- the domain candidate's per-level DRIFT (the #752 obstruction) is never consumed. universeDomainNon
-- DependentArrowMemberStronglyNormalizing: the general member-companion (codomainBase reducible-at-level with a CR
-- => members of Type@e -> codomainBase are SN). universeToUniverseArrowMemberStronglyNormalizing: the fully-
-- UNCONDITIONAL concrete witness -- a reducible member of Type@e -> Type@e' (function between two universes) is SN
-- at any level above both decoded levels, NO codomain hypotheses. First unconditional universe-domain function-
-- type member-SN in the denote model; completes the unconditional #752 slice (type + member). Only the genuinely
-- DEPENDENT composite-domain Pi stays gated on #752/#753. Both zero-axiom.
#assert_no_axioms FX1Poly.Typed.universeDomainNonDependentArrowMemberStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.universeToUniverseArrowMemberStronglyNormalizing
#assert_no_axioms FX1Poly.Core.reducibilityNormalizationScone
#assert_no_axioms FX1Poly.Core.normalizationViaSconing
#assert_no_axioms FX1Poly.Tier0.boolValueScone_semanticIsStronglyNormalizing

-- SN-for-well-typed, CLOSED case (ClosedStronglyNormalizing.lean, BFT-14 = SN-043-closed). Every closed grown
-- derivation has a strongly-normalizing subject, unconditionally. Composes closedBoundedReducibleMember (BFT-13) →
-- stronglyNormalizing_of_memberAtBoundedSucc (scope+1 bounded CR1) → StepStar.stronglyNormalizing_of_subst (SN
-- reflects through the closing substitution). Capstone of the bounded reducibility route (BFT-1..14) for closed
-- terms; what closed-term canonicity (SN-047/048/049) and consistency (SN-050) consume. Arbitrary-context SN-043
-- (#546) additionally needs the neutral-variable open-term closing env — tracked separately.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.closedStronglyNormalizing

-- SN-for-well-typed, OPEN form / the SN-043 wiring (OpenStronglyNormalizing.lean). Any grown derivation in an
-- arbitrary context is SN GIVEN a BoundExceedsPi budget + a bound-reducible closing environment. Same
-- member→SN→reflect composition as BFT-14, parameterized over an arbitrary closing env (closed = the .empty
-- instance). Reduces fully-unconditional #546 to ONE residual: reducibleEnvOfWfContext (the identity closing subst
-- is bound-reducible over a well-formed context — the classical reducible-substitution lemma).
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.stronglyNormalizingOfReducibleEnv

-- ★ SN-043 OPEN (OpenStronglyNormalizingUnconditional.lean, OB-5): every well-typed grown term in a WELL-FORMED
-- context is strongly normalizing, UNCONDITIONALLY. WfContextDesc Γ → HasTypeDescPi Γ subject classifier →
-- IsStronglyNormalizing subject. The open generalization of closedStronglyNormalizing (BFT-14) from .empty to
-- arbitrary Γ. Composes existsBound (budget) + reducibleEnvOfWfContextDesc (OB-3, the reducible closing env over
-- the native WfContextDesc.headIsTypeDesc + HasTypeDesc.toHasTypeDescPi) at a common SUM bound, fed to
-- stronglyNormalizingOfReducibleEnv (reflects SN internally). The OB-1..OB-5 capstone — reached with NO #672, NO
-- KB merged candidate, NO renaming closure. The wf-hypothesis stays external (since HasTypeDescPi → WfContext
-- provably FAILS, ContextValidityFails). Closes #546.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.stronglyNormalizingOfWfContextDesc

-- OSN-2 (OpenSNSmoke.lean): open-context SN regression corpus via open SN-043 (OB-5). Four concrete terms in the
-- non-empty well-formed context Γ = (.empty).cons (Type@e) — a universe code (ofFormation), the context
-- variable var 0 (var rule), the identity lambda (piIntro binder), and the β-redex (λx.x) Type@s (piElim)
-- — each discharged to IsStronglyNormalizing by HasTypeDescPi.stronglyNormalizingOfWfContextDesc (OB-5 over the
-- native IsTypeDesc-based WfContextDesc + wfContextDesc_universeBinding). The β-redex entry is the
-- NON-VACUOUS one: a term that actually reduces, whose termination OB-5 certifies. The open analogue of
-- ClosedSNSmoke (SN-044).
#assert_no_axioms FX1Poly.Typed.openUniverseCode_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.openContextVariable_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.openIdentityLambda_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.openBetaRedex_stronglyNormalizing

-- OSN-1 (OpenStronglyNormalizingBetaEta.lean): the βη leg. Well-typed open terms are β-SN (OB-5) AND η-SN
-- (unconditional, since η shrinks RawTerm.size) separately. The UNION βη-SN is NOT their conjunction (β/η
-- interleave), but the SN-of-union assembly is the Geser criterion accUnionBetaEta; the η-postponement crux
-- EtaQuasiCommutesOverBeta is discharged (etaQuasiCommutesOverBeta, the per-η-ctor critical-pair assembly over
-- all 5 η constructors). No sorry/placeholder. (The WfContextDesc open βη-SN twins are gated below.)
-- The WfContextDesc twins (the βη leg): the conditional + headline open βη-SN
-- (OpenStronglyNormalizingBetaEta.lean) and the Geuvers βη-CR + unique-βη-NF (WfContextBetaEtaConfluence.lean),
-- all routed through the bridge-free stronglyNormalizingOfWfContextDesc — the η-SN component + the Geser union
-- criterion + the βη-Newman bridge are context-predicate-agnostic, so NO HasType on the path.
#assert_no_axioms FX1Poly.Typed.divergentOmega_notStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.rawStep_notStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.metatheoryFuzzFamily_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.metatheoryFuzzConstantFamily_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.metatheoryFuzzLambdaFamily_stronglyNormalizing

-- §27.3 Layer-3 defense: every core metatheory rule cross-referenced to a PUBLISHED MECHANIZED proof and
-- ANCHORED to the real kernel theorem that realizes it.  The `crossRef_*` anchors (`def := @kernelTheorem`)
-- verify each cited rule EXISTS and — via these gates — RE-CERTIFY each classical rule's kernel proof is
-- zero-axiom.  `KernelMetatheoryRule` + `mechanizedSource`/`hasClassicalPrecedent`/`kernelAnchor` is the
-- machine-checked catalog; the `…_hasClassicalPrecedent`/`…_isFxOriginal` rfl-facts pin the honest
-- classical-vs-FX-original split (9 classical anchored + 2 FX-original).
#assert_no_axioms FX1Poly.Typed.KernelMetatheoryRule
#assert_no_axioms FX1Poly.Typed.KernelMetatheoryRule.mechanizedSource
#assert_no_axioms FX1Poly.Typed.KernelMetatheoryRule.hasClassicalPrecedent
#assert_no_axioms FX1Poly.Typed.KernelMetatheoryRule.kernelAnchor
#assert_no_axioms FX1Poly.Typed.crossRef_correctedLam
#assert_no_axioms FX1Poly.Typed.crossRef_strongNormalization
#assert_no_axioms FX1Poly.Typed.strongNormalization_hasClassicalPrecedent
#assert_no_axioms FX1Poly.Typed.parityAnchor_strongNormalization_formation
#assert_no_axioms FX1Poly.Typed.parityAnchor_strongNormalization_grown
#assert_no_axioms FX1Poly.Typed.strongNormalization_grownNeedsWfContext
#assert_no_axioms FX1Poly.Typed.notStronglyNormalizing_of_infiniteReduction
#assert_no_axioms FX1Poly.Typed.growingReductionSequence_steps
#assert_no_axioms FX1Poly.Typed.growingDivergentTerm_notStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.growingFirstReduct_ne_source
#assert_no_axioms FX1Poly.Typed.nonSelfLoopingDivergenceExists
#assert_no_axioms FX1Poly.Typed.idTower_stronglyNormalizing
#assert_no_axioms FX1Poly.Typed.idTower_reducesToValue
#assert_no_axioms FX1Poly.Typed.idTowerUniformlyTypedReducesToValue
#assert_no_axioms FX1Poly.Typed.curryOmega_notStronglyNormalizing
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.stronglyNormalizingOfWfContextDescPi

/-! ### ConvDecisionSteps — the SN-fragment Conv decider's exact cost witness (M19)

The decider's reducer cost = the sum of the two operands' exact normalizer counters
(`decideStronglyNormalizingSteps`), tied to the verdict + the two counted chains in ONE object
(`costAccounting`), zero exactly on the normal fragment, EXACT (= m + n) on tower pairs, and
unbounded.  HONEST M19 closure: `DecisionComplexity` is deliberately NOT instantiated for raw
`Conv` (two β-normalization runs admit no truthful size-polynomial — Statman 1979,
literature-cited); the §11.8.7 "decidable but EXP-tower" loophole is closed by exact DISCLOSURE,
with the polynomial witness reserved for deciders where it is true (the LevelExpr instance). -/

#assert_no_axioms FX1Poly.Core.Conv.decideStronglyNormalizingSteps
#assert_no_axioms FX1Poly.Core.Conv.decideStronglyNormalizing_costAccounting
#assert_no_axioms FX1Poly.Core.Conv.decideStronglyNormalizingSteps_eq_zero_iff_normalForms

/-! ### LiftedChildNormalizationFromClosure — the GTL-06 kernel's brick 1 (#820)

The reusable fresh-variable instantiation, extracted from the Π/Σ former-membership interiors
and strictly generalized (abstract domain term, ARBITRARY child classifier): a cons-closure at
a one-level-up-reducible domain yields strong normalization of the LIFTED-open substituted
binder-child.  This is the one genuinely new piece the table-generic dispatch arm needs at
shift-1 children; depth-0 children are CR1, shift ≥ 2 is a named non-blocker (no current
formation row).  The module docstring records the GO verdict + the remaining #820 assembly. -/

#assert_no_axioms FX1Poly.Typed.IsStronglyNormalizing.liftedSubstOfConsClosureAtFreshVariable
#assert_no_axioms FX1Poly.Typed.cascadeAnchor_strongNormalization
#assert_no_axioms FX1Poly.Typed.strongNormalization_isZeroArm
