import FX1PolyAudit.DependencyAudit
import FX1Poly.Core.Metatheory.Reducibility.Core.DataReducibilityCoverage
import FX1Poly.Core.Metatheory.Reducibility.Candidates.DataTaitCandidate
import FX1Poly.Core.Metatheory.Reducibility.Candidates.FlatCodeTaitCandidate
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FlatCodeCanonicalForms
import FX1PolyAudit.MilestoneASpineValueLayer
import FX1PolyAudit.MilestoneAEliminatorLayerSpine
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimComputingCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicityTyped
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchGeneralBranchCanonicity
import FX1PolyAudit.MetatheoryParityLedger
import FX1Poly.Typed.Engine.Classifier.TypingContext
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeShape
import FX1Poly.Typed.Metatheory.Universe.UniverseCodeConversion
import FX1Poly.Typed.Engine.Formation.SigmaCodeShape
import FX1Poly.Typed.Engine.Formation.ListCodeShape
import FX1Poly.Typed.Engine.Formation.ListFormationSmoke
import FX1Poly.Typed.Engine.Formation.OptionCodeShape
import FX1Poly.Typed.Engine.Formation.OptionCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.OptionFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationOptionFromTelescope
import FX1Poly.Typed.Engine.Formation.OptionFormationSmoke
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDesc
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescDecidable
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElim
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescValidity
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescClosedForms
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFormerTelescopeInversion
import FX1Poly.Typed.Engine.Formation.DataFormerInversion
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescUniqueness
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimWeakening
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescElimSubstitution
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPi
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaCoherence
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionGrown
import FX1Poly.Typed.Engine.HasTypeDescPi.Eta.HasTypeDescPiEtaExpansionComputes
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiWeakening
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiSubstitution
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiValidity
import FX1Poly.Typed.Ledger.Misc.ConvCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvBoolCodeRigidity
import FX1Poly.Typed.Engine.Formation.ConvFormationFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvCrossTableFormerRigidity
import FX1Poly.Typed.Engine.Formation.ConvFlatCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.ConvDataCodeInjectivity
import FX1Poly.Typed.Ledger.Misc.EmptyTypeCodeConvRigidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.EmptyTypeValueInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.FormationCanonicalForms
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.PiTypeFunctionInversion
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalForms
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafety
import FX1Poly.Typed.Engine.Formation.FormationTypeSafety
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownClosedProgressByClassifier
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownCanonicalFormsNonVacuity
import FX1Poly.Typed.Corpus.Smoke.GrownBetaRedexInAction
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgress
import FX1Poly.Typed.Metatheory.Canonicity.Forms.GrownOpenCanonicalFormsByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenProgressByClassifier
import FX1Poly.Typed.Corpus.Progress.GrownOpenTypeSafety
import FX1Poly.Typed.Corpus.Progress.GrownTypeSafetyUnconditional
import FX1Poly.Typed.Engine.Formation.FormerStepInversionGeneric
import FX1Poly.Typed.Metatheory.SubjectReduction.SubjectReductionAtFormerGeneric
import FX1Poly.Typed.Engine.WfContext.WfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescValidity
import FX1Poly.Typed.Engine.WfContext.WfContextDescUniqueness
import FX1Poly.Typed.Engine.WfContext.WfContextDescPi
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiFromWfContextDesc
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiLookup
import FX1Poly.Typed.Engine.WfContext.WfContextDescPiValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiClassifierValidity
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiFunctionComponentValidity
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionDescPi
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionMutual
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnv
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAt
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvTypeVariable
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprFT
import FX1Poly.Typed.Metatheory.Reducibility.Pi.AbstractionNonDependentUnderSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprReducibleLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermFundamentalLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConfluenceLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInhabitationLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermInversionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTypeExprClosureLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermRenameLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubstLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermSubjectReductionLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermCanonicityLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermConsistencyLevelFree
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvDecision
import FX1Poly.Typed.Metatheory.SimplyTyped.MilestoneA0SimplyTypedFloor
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedMetatheoryViaSconing
import FX1Poly.Tier0.Context.Instances.Renaming.FxRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecCategory
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecIsomorphism
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecPreimage
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecTryTabulate
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecRMC
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecGlobalSections
import FX1Poly.Tier0.Context.Instances.Renaming.FxBaseRenamingVecSconingPreservation
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstVec
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstCategory
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWeakening
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstComprehension
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstSingleton
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstGlobalSections
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstWitnessScone
import FX1Poly.Tier0.Context.Instances.Subst.FxBaseSubstConcreteScone
import FX1Poly.Tier0.Context.IsomorphismCategorical
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeRMC
import FX1Poly.Tier0.Context.Instances.ThinScope.FxThinScopeGlobalSections
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedConvEquivalence
import FX1Poly.Typed.Corpus.Smoke.ReduceSmokeCorpus
import FX1Poly.Core.Rewriting.Reduction.Head.RootStepDispatch
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnce
import FX1Poly.Core.Rewriting.Reduction.Step.ReduceOnceComplete
import FX1Poly.Core.Rewriting.Normalize.Normalize
import FX1Poly.Core.Rewriting.Normalize.NormalizeSteps
import FX1Poly.Core.Rewriting.Conversion.ConvDecisionSteps
import FX1Poly.Core.Rewriting.Normalize.NormalizeMeta
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.CanonicalFormsWeakHeadExpansion
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.BoolElimCanonicalComputation
import FX1Poly.Core.Eliminators.Bool.BoolElimClosedMembership
import FX1Poly.Core.Eliminators.Core.DataEliminatorMembershipSmoke
import FX1Poly.Core.Metatheory.Canonicity.SigmaProjectionCanonicalComputation
import FX1Poly.Core.Metatheory.Canonicity.IdentityEliminatorCanonicalComputation
import FX1Poly.Core.Eliminators.Identity.IdEliminatorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.OptionEitherMatchCanonicalComputation
import FX1Poly.Core.Eliminators.Match.MatchClosedMembership
import FX1Poly.Core.Eliminators.Sigma.SigmaProjectionClosedMembership
import FX1Poly.Core.Eliminators.Recursor.RecursorClosedMembership
import FX1Poly.Core.Metatheory.Canonicity.RecursiveEliminatorBaseComputation
import FX1Poly.Core.Metatheory.Canonicity.BoolCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.DataCanonicityViaSconing
import FX1Poly.Core.Metatheory.Canonicity.ModalCanonicityViaSconing
import FX1Poly.Core.Metatheory.Sconing.DataMetatheoryViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityNormalizationViaSconing
import FX1Poly.Core.Metatheory.Sconing.ReducibilityConversionViaSconing
import FX1Poly.Core.Metatheory.Sconing.ConsistencyViaSconing
import FX1Poly.Core.Eliminators.Core.DataEliminatorProgressViaSconing
import FX1Poly.Core.Eliminators.Recursor.RecursiveEliminatorProgressViaSconing
import FX1Poly.Core.Metatheory.Canonicity.NatCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.PairCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.UnitCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ModIntroCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EmptyCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ListCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.OptionCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.EitherCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Canonicity.ReflCanonicalFormsCandidate
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingSubst
import FX1Poly.Core.Rewriting.Normalize.ExistsStepOfNotNormal
import FX1Poly.Core.Metatheory.Normalization.Core.WeakNormalization
import FX1Poly.Core.Rewriting.Normalize.NormalFormUnique
import FX1Poly.Core.Metatheory.Normalization.Core.StronglyNormalizingConvDecision
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevels
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvAtAllLevelsWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithPositiveTypeCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalWithTypeValueCandidates
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllFormerChildren
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPiIntro
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Pi.NeutralFuelStability
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiTypeSaturationReassembly
import FX1Poly.Typed.Metatheory.Reducibility.Pi.StrongNormalizingAllLevelPiComponents
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllTelescopePositiveArguments
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllPositiveMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllCanonicalCandidate
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllVectorPremises
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtAllNonDependentBinders
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalAtUniformVectorPremises
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFundamentalVectorFromFormation
import FX1Poly.Typed.Engine.HasTypeDesc.HasTypeDescFundamentalAtAllFromGenFormation
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClosedLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.TypeFundamentalLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LeveledContext
import FX1Poly.Typed.Corpus.Smoke.ClosedSNSmoke
import FX1Poly.Typed.Corpus.Smoke.UntypedOmegaNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.WeaklyNormalizingNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.StepNonDeterministic
import FX1Poly.Typed.Ledger.Misc.ConvValueDiscrimination
import FX1Poly.Typed.Corpus.Smoke.TypedLambdaDerivations
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleans
import FX1Poly.Typed.Corpus.Church.Core.TypedChurchNegation
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumerals
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIteration
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralDiscrimination
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralThree
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralFaithful
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralTyping
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralInhabitants
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralComputeGeneral
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralAddition
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralMultiplication
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralSemiringLaws
import FX1Poly.Typed.Corpus.Church.Numerals.TypedChurchNumeralIsZero
import FX1Poly.Typed.Corpus.Church.Booleans.TypedChurchBooleanOperations
import FX1Poly.Typed.Corpus.Smoke.TypedFragmentAcyclicity
import FX1Poly.Typed.Corpus.Smoke.UnboundedGrowthNotStronglyNormalizing
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointDivergence
import FX1Poly.Typed.Corpus.Church.Combinators.CurryFixpointCombinator
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryLogic
import FX1Poly.Typed.Corpus.Church.Combinators.CombinatoryCompleteness
import FX1Poly.Typed.Corpus.Church.Combinators.SymbolicSCombinatorRule
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairs
import FX1Poly.Typed.Corpus.Church.Pairs.ChurchPairsInjective
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSums
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsDisjoint
import FX1Poly.Typed.Corpus.Church.Sums.ChurchSumsGeneral
import FX1Poly.Typed.Corpus.Church.Lists.ChurchLists
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListIsEmpty
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAny
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListAll
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBooleanComplementLaws
import FX1Poly.Typed.Corpus.Church.Booleans.ChurchBoolXor
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListFirstOr
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSucc
import FX1Poly.Typed.Corpus.Church.Numerals.ChurchSuccApplies
import FX1Poly.Typed.Corpus.Church.Lists.ChurchListLength
import FX1Poly.Typed.Metatheory.Normalizer.TypedNormalizer
import FX1Poly.Typed.Corpus.Smoke.IdentityTowerFamily
import FX1Poly.Typed.Metatheory.Normalizer.NormalizeStepsTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseTower
import FX1Poly.Typed.Metatheory.Universe.TypedUniverseNoTop
import FX1Poly.Typed.Metatheory.Universe.TypedUniversePredicative
import FX1Poly.Typed.Metatheory.Normalizer.ClosedConvDecision
import FX1Poly.Typed.Corpus.Progress.ClosedNormalForm
import FX1Poly.Typed.Metatheory.Normalizer.ClosedNonConvertibility
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTyping
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiStronglyNormalizingFromFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVec
import FX1Poly.Typed.Metatheory.Reducibility.Env.ReducibleEnvVecTypeVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConsistency
import FX1Poly.Typed.Engine.Formation.HasTypeFormationNoLambdaApplication
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleSemanticRules
import FX1Poly.Typed.Engine.Formation.ListCodeFormationUnderSubst
import FX1Poly.Typed.Engine.Formation.ListFormerMemberLevelIndexed
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberFormation
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeInversion
import FX1Poly.Typed.Engine.RuleTables.DescTelescopeReach
import FX1Poly.Typed.Engine.RuleTables.FlatDescTelescope
import FX1Poly.Typed.Metatheory.Canonicity.Core.StandaloneEngineCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Forms.CombinedBoolCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedBoolCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicitySyntacticRoute
import FX1Poly.Typed.Metatheory.Canonicity.Core.GrownRigidityCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.ClosedNatCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.BoolElimValueCanonicity
import FX1Poly.Typed.Metatheory.Canonicity.Core.NatElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulArithmetic
import FX1Poly.Typed.Metatheory.Reducibility.Core.ClosedNumeralSubstInvariant
import FX1Poly.Typed.Corpus.Faithfulness.NatElimFaithfulMul
import FX1Poly.Typed.Corpus.Faithfulness.ValueElimHostFold
import FX1Poly.Typed.Corpus.Faithfulness.RecursorHostFold
import FX1Poly.Typed.Metatheory.Canonicity.Core.ListElimComputingCanonicity
import FX1Poly.Typed.Corpus.Faithfulness.ListElimFaithfulLength
import FX1Poly.Typed.Metatheory.Canonicity.Core.MatchElimComputingCanonicity
import FX1Poly.Typed.Corpus.Progress.GrownClosedNormalClassifierShape
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ClosedNormalEmptyConsistency
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ProductEitherCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.OptionCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.ListCanonicalForms
import FX1Poly.Typed.Metatheory.Canonicity.Forms.IdCanonicalForms
import FX1Poly.Typed.Metatheory.Reducibility.Pi.PiFormerMembership
import FX1Poly.Typed.Engine.Formation.FormerChildrenReducible
import FX1Poly.Typed.Metatheory.Reducibility.Telescope.TelescopeReducible
import FX1Poly.Typed.Metatheory.Universe.UniverseDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsInduction
import FX1Poly.Typed.Metatheory.Reducibility.Pi.ReducibleTypeAtAllLevelsPiNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsLeaves
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FundamentalTelescopeConsWhnfDomain
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsPiDomainMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsPiMemberExtension
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsHeadExpand
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsConv
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleMemberAtAllPositiveLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Reducibility.Member.ReducibleTypeAtAllLevelsNonDependentArrow
import FX1Poly.Typed.Metatheory.Strengthening.RouteAObstruction
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelDiagnosis
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelMeasure
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibility
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibilitySmoke
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPi
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedLevelIrrelevance
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseFormationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCanonicalMemberCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationFromExistence
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGeneralDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSingleLevelPi
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiCandidate
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedUniformPiAboveThreshold
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormerAtLevel
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedReducibleTypeLevelLift
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiArmDischarge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedPiFormationUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedApplicationMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedConvMember
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberForwardClosed
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMemberBetaExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedMemberWeakHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedHeadExpansion
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedAbstractionMember
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAbstractionUnderSubst
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiElim
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalConv
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedAmbientLevelBridge
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrow
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedFundamentalPiIntro
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedClosedMember
import FX1Poly.Typed.Metatheory.Denote.Telescope.DenoteKeyedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedUniformReducible
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseMembershipIntro
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFormation
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedSigmaFromChildMembers
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationSigmaArm
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedCumulativityObstruction
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibility
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedReducibleEnv
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedFundamentalMotive
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedConvArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiElimArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedPiIntroArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedFormerEngine
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiArm
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedGenFormationPiDischarge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedAssemblyBridge
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeReducible
import FX1Poly.Typed.Metatheory.Denote.Fundamental.DenoteKeyedBoundedTelescopeFundamental
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedBoundedTelescopeProjection
import FX1Poly.Typed.Engine.Formation.FormerOutputLevelBounds
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedCodomainOpenSN
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedDomainInhabitant
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationPiFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationSigmaFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGenFormationListFromTelescope
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedTelescopeConsSucc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedGrownDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationLeafArms
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDesc
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedFormationDispatch
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPi
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundExceedsPiDischarge
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.BoundedGrownFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.ClosedBoundedReducibleMember
import FX1Poly.Typed.Corpus.Smoke.ClosedStronglyNormalizing
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedNeutralMember
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedUniverseInversion
import FX1Poly.Typed.Metatheory.Reducibility.Bounded.BoundedBindingTypeReducible
import FX1Poly.Typed.Engine.WfContext.ReducibleEnvOfWfContext
import FX1Poly.Typed.Corpus.Smoke.OpenStronglyNormalizingUnconditional
import FX1Poly.Typed.Metatheory.Normalizer.WfContextDecidableConv
import FX1Poly.Typed.Corpus.Smoke.OpenSNSmoke
import FX1Poly.Typed.Corpus.Progress.ContextValidityFails
import FX1Poly.Typed.Equality.UnitEta.UnitEtaJudgmentalEquality
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruenceGap
import FX1Poly.Typed.Equality.UnitEta.UnitEtaCongruentEquality
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapse
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseIncompleteness
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseBinderFence
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeep
import FX1Poly.Typed.Equality.UnitEta.UnitVariableCollapseDeepSound
import FX1Poly.Typed.Equality.UnitEta.UnitCollapseNeutralBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitNeutralSpineDetection
import FX1Poly.Typed.Equality.UnitEta.UnitSpineDetectionBoundary
import FX1Poly.Typed.Equality.UnitEta.TypeDirectedUnitReadback
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackArgumentBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackFormerChildBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackDeepSpineBoundary
import FX1Poly.Typed.Equality.UnitEta.UnitReadbackAnnotationBoundary
import FX1Poly.Typed.Engine.Formation.FormationClassifierRigidity
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeNormalizer
import FX1Poly.Typed.Metatheory.Normalizer.TypedNbeConvDecision
import FX1Poly.Typed.Ledger.Misc.LiftedChildNormalizationFromClosure
import FX1Poly.Typed.Engine.RuleTables.TelescopeSubstitutedChildrenNormalization
import FX1PolyAudit.CascadeFreedomLedger
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyTargetSignature
import FX1PolyAudit.CandidateBridgeEditViability
import FX1Poly.Typed.Metatheory.Canonicity.Core.CanonicityTargetSignature
import FX1Poly.Typed.Metatheory.Universe.NullaryFormerFormation
import FX1Poly.Typed.Metatheory.Universe.GrownUniverseFormationStrictness
import FX1Poly.Typed.Engine.Formation.GrownFormerFormationStrictness
import FX1Poly.Typed.Engine.Classifier.GrownTypingNotUnique
import FX1Poly.Typed.Engine.Classifier.GrownEngineHonesty
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.GrownUniverseConsistency
import FX1Poly.Typed.Engine.Classifier.GrownVariableHonesty
import FX1Poly.Typed.Corpus.Smoke.RawStepNotStronglyNormalizing
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiLamInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiAppInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVarInversion
import FX1Poly.Typed.Metatheory.ContextConversion.VarHeadedAppContextConversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiBetaSR
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiCongruence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerCongruence
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionConditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimReduction
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionValidityReduction
import FX1Poly.Typed.Corpus.Progress.GrownMutualMetatheoryFromPiValidity
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimEquivalence
import FX1Poly.Typed.Engine.HasTypeDescPi.ContextConversion.HasTypeDescPiContextStepConversion
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionUnconditional
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionPiElimUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.HasTypeDescPiContextConversionFlexibleUnderWf
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormationFragment
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPreservesPiValidityFormerStep
import FX1Poly.Typed.Metatheory.ContextConversion.GenFormerValidityContextConversion
import FX1Poly.Typed.Metatheory.ContextConversion.ConvContextPiValidityModelNeutral
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRelation
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveled
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransport
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledTransportUnderWf
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityLeveledCompleteness
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValid
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.TypedTypeValidityBoxedRename
import FX1Poly.Typed.Engine.WfContext.WfContextTypedLrValidLookup
import FX1Poly.Typed.Ledger.Misc.PiElimClassifierConvResidual
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiFormerInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiDataHeadUntyped
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiRootGeneric
import FX1Poly.Typed.Metatheory.Denote.Bounded.DenoteKeyedUniverseBoundedCumulativity
import FX1Poly.Typed.Metatheory.Denote.Core.DenoteKeyedClosedTypeCodeSN
import FX1Poly.Typed.Metatheory.Denote.Universe.DenoteKeyedUniverseDomainPiMemberSN
import FX1Poly.Typed.Metatheory.Denote.Pi.DenoteKeyedNonDependentArrowMemberSN
import FX1Poly.Typed.Metatheory.Denote.Member.DenoteKeyedCodomainMemberWiring
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.ClassifierLevelSpike
import FX1PolyAudit.SNStrategy
import FX1Poly.Typed.Metatheory.Reducibility.LogRel.LogRelSpec
import FX1Poly.Typed.Metatheory.Reducibility.Leveled.LevelingBridge
import FX1Poly.Typed.Metatheory.Canonicity.Core.ConsistentStratification
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingLevelFlexible
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingRefinedMotive
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingConvArm
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingPiArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingFormerArms
import FX1Poly.Typed.Metatheory.Reducibility.Valid.ValidTypingVariableLevelPinned
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalReduction
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamental
import FX1Poly.Typed.Metatheory.Reducibility.Fundamental.FormationEngineFundamentalAssembly
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiConditionalConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiUniqueNormalForm
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.SimplyTyped.HigherOrderSimplyTypedReducibility
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiOverNeutralDomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentPiNeutralCodomain
import FX1Poly.Typed.Metatheory.Reducibility.Pi.DependentlyTypedNeutralDomainFragment
import FX1Poly.Typed.Metatheory.SimplyTyped.FirstOrderSimplyTypedSubsumption
import FX1Poly.Typed.Metatheory.Universe.UniverseCumulativity
import FX1Poly.Typed.Metatheory.SimplyTyped.SimplyTypedTermReducibility
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiTypingNonUnique
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckOfInferred
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiVariableInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckVariable
import FX1Poly.Typed.Engine.HasTypeDescPi.Inversion.HasTypeDescPiUniverseCodeInversion
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckUniverseCode
import FX1Poly.Typed.Engine.HasTypeDescPi.Core.HasTypeDescPiApplicationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckApplication
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationUniqueness
import FX1Poly.Typed.Engine.HasTypeDescPi.Check.HasTypeDescPiCheckFormation
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormationCodomainReTyping
import FX1Poly.Typed.Engine.RuleTables.IntroRuleDesc
import FX1Poly.Typed.Engine.RuleTables.ElimRuleDesc
import FX1Poly.Typed.Engine.RuleTables.GenElimIotaComputation
import FX1Poly.Typed.Engine.Classifier.TypingRoleClassifier
import FX1Poly.Typed.Engine.Classifier.TypingRoleEngineBridge
import FX1Poly.Typed.Engine.Classifier.TypingRoleCoverage
import FX1Poly.Typed.Engine.Classifier.UntypableHeadDecision
import FX1Poly.Typed.Engine.Classifier.TypingHeadKindClassifier
import FX1Poly.Typed.Engine.Classifier.TypedBySomeEngine
import FX1Poly.Typed.Engine.Classifier.GeneratorSemanticTier
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyOverview
import FX1Poly.Typed.Engine.Classifier.StaticTypingSoundness
import FX1Poly.Typed.Engine.Classifier.SemanticTierSoundness
import FX1Poly.Typed.Engine.Classifier.ClassifierRefinement
import FX1Poly.Typed.Engine.Classifier.GeneratorHonestyLedger
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionTermination
import FX1Poly.Typed.Ledger.Misc.CertifiedWordReductionConfluence
import FX1Poly.Typed.Engine.HasTypeDescPi.Formation.HasTypeDescPiFormerStepDomainFormationCodomain
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionFormerArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionInlineArms
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescSubjectReduction
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeDescPiSubjectReductionConvOfFormationArms
import FX1Poly.Typed.Metatheory.SubjectReduction.ConsistencyConditionalOnSubjectReduction
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencySyntactic
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.ConsistencyOfPiElimArm
import FX1Poly.Typed.Ledger.Misc.PiElimUpToClassifierConv
import FX1Poly.Typed.Engine.Classifier.ClassifierRespectsConvRefuted
import FX1Poly.Typed.Dimensions.AxisObligation.TypedCertificationStackingRefuted
import FX1Poly.Typed.Metatheory.Canonicity.Consistency.EmptyTypeConsistencyUnconditional
import FX1Poly.Typed.Engine.Formation.FormationNormalSmoke
import FX1Poly.Typed.Engine.Formation.BoolTypeCodeSubstrate
import FX1Poly.Typed.Engine.Formation.NatTypeCodeSubstrate
import FX1Poly.Typed.Corpus.Progress.GrownNoTypeInType
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescRigidity
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidable
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescDecidableGeneric
import FX1Poly.Typed.Engine.IsTypeDesc.IsTypeDescGenericSmoke
import FX1PolyAudit.KnownUnsoundnessCorpus
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationAcyclic
import FX1Poly.Dimensions.Security.SecurityNoninterferenceGeneral
import FX1Poly.Dimensions.Graded.GradedApplicationFlow
import FX1PolyAudit.MetatheoryFuzz
import FX1PolyAudit.FuzzCorpusConvertibility
import FX1PolyAudit.FuzzCorpusNormalizes
import FX1PolyAudit.LambdaValueFuzzFamily
import FX1PolyAudit.MechanizedProofCrossReference
import FX1PolyAudit.FormalReviewGate
import FX1PolyAudit.SelfVerifiedMetatheory
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengthening
import FX1Poly.Typed.Metatheory.Strengthening.GrownStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheck
import FX1Poly.Typed.Metatheory.ContextConversion.GrownCheckContextConversion
import FX1Poly.Typed.Metatheory.Strengthening.GrownCheckSoundnessRefutation
import FX1Poly.Typed.Metatheory.Strengthening.ConvExistentialStrengtheningRefutation
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiImageComponents
import FX1Poly.Typed.Metatheory.Strengthening.PinnedPiRenameImage
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionContext
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiIntro
import FX1Poly.Typed.Engine.Formation.FormationPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.GrownPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimCore
import FX1Poly.Typed.Corpus.Smoke.GrownWfOpenStronglyNormalizing
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionPiElimDispatcher
import FX1Poly.Typed.Metatheory.Strengthening.PlateauDescentSubstrate
import FX1Poly.Typed.Metatheory.Strengthening.GuardedPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.PlateauPinnedReflection
import FX1Poly.Typed.Metatheory.Strengthening.NeutralReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionLamClassifierResidual
import FX1Poly.Typed.Metatheory.Strengthening.FlagCoherentReflectionCondition
import FX1Poly.Typed.Metatheory.Universe.UniverseClassificationUnique
import FX1Poly.Typed.Ledger.Misc.NeutralClassifierUnique
import FX1Poly.Typed.Ledger.Misc.NormalAppNeutral
import FX1Poly.Typed.Engine.RuleTables.TelescopeUniverseDeterminism
import FX1Poly.Typed.Engine.RuleTables.GenericFormerTelescopeInversion
import FX1Poly.Typed.Metatheory.Universe.NormalUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Universe.ConvUniverseClassificationUnique
import FX1Poly.Typed.Metatheory.Strengthening.RenameAlongFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.PinSelectsCallerPair
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherent
import FX1Poly.Typed.Metatheory.Strengthening.LamReductResidualDischarge
import FX1Poly.Typed.Metatheory.Strengthening.PinnedReflectionFlagCoherentMaster

/-! # FX1PolyAudit/AuditTypedContextConversion — typed-layer zero-axiom gates: context conversion and Pi-validity transport
   (semantic shard of the typed audit; gates classified by declaration topic, appended
   clusters kept together; full import block retained for namespace-sweep coverage) -/

#assert_no_axioms FX1Poly.Typed.renameContextCondition_cons
#assert_no_axioms FX1Poly.Typed.substContextCondition_cons
#assert_no_axioms FX1Poly.Typed.convContextCondition_consStep
#assert_no_axioms FX1Poly.Typed.convContextCondition_cons
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.convContext
#assert_no_axioms FX1Poly.Typed.DescTelescope.convTelescope
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.convContextOfFormation
-- GROWN context-conversion mutual pair, conditional on the lone piElim arm (HasTypeDescPiContextConversion
-- Conditional.lean, GrownCtxConv-1/2/3/4/6): the SRD-1 conditional-package discipline (#664) applied to GrownCtxConv. ALL five
-- non-piElim arms discharged — ofFormation (convContextOfFormation), conv (recurse+compose), piIntro
-- VALIDITY-FREE (components conv-backed to universe codes; body via the recursively-obtained codomain re-typing),
-- genFormationPi (mutual convTelescope), telescope nil/cons. The piElim arm (type-Conv-closure, circular with SR
-- = the mutual fundamental-metatheory bundle GrownCtxConv-5) is the LONE explicit hypothesis. convTelescopeOfPiElimArm =
-- the grown telescope context-conversion (GrownCtxConv-3) the grown telescope SR consumes ⟹ SRD-2 ⟹ unconditional SN-055.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.convContextOfPiElimArm
#assert_no_axioms FX1Poly.Typed.DescTelescopePi.convTelescopeOfPiElimArm
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.piElimArmFromPiValidityTransfer

-- GrownCtxConv-5 WfContext-threaded context-conversion conditional on the MINIMAL residual (HasTypeDescPiContextConversion
-- Wf.lean, GrownCtxConv-5-WFTHREAD, toward #842). convContextWfOfPiValidity / convTelescopeWfOfPiValidity: a
-- WfContextDescPi-threaded grown context-conversion mutual pair conditional on ConvContextPreservesPiValidity (the
-- minimal type-formation residual from #1092) INSTEAD of the opaque full piElimArm. The piElim arm is INLINED via
-- piElimArmFromPiValidityTransfer (threaded wfSrc → classifierIsTypeDescPi/WFG-3 source Pi-validity → residual
-- transfers it → reassembly) using the recursive convContext IH on the function/argument children. WfContextDescPi
-- (a structural def) is extended at each binder from the SOURCE-side domain/head typing via WfContextDescPi.cons --
-- every recursive call's well-formedness is discharged from premises already present. Strictly improves on
-- convContextOfPiElimArm: residual is now the minimal Pi-type-code-validity-is-context-conversion-stable fact,
-- WfContext is threaded (the SR consumers have it), the piElim arm is demonstrably inlinable. Leaves
-- ConvContextPreservesPiValidity as the single open obligation (GTL-20 bundle / semantic-reflection). The telescope
-- theorem orders (telescope)(wf) so the baseScope/currentDepth split is pinned before the sum-only wf. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.convContextWfOfPiValidity
#assert_no_axioms FX1Poly.Typed.DescTelescopePi.convTelescopeWfOfPiValidity

-- GTL-20 (#1098): the grown mutual fundamental-metatheory bundle, conditional on the SINGLE residual
-- (GrownMutualMetatheoryFromPiValidity.lean, toward #834). PROVES that ConvContextPreservesPiValidity discharges BOTH
-- open grown-metatheory release blockers: grown context-conversion (GrownCtxConv-5/#842) AND the grown master subject
-- reduction (SRD-2/#845/SN-055/#558). grownContextConversionFromPiValidity = the clean top-level GrownCtxConv-5 closure (wraps
-- #1093). masterSubjectReductionFromPiValidity ⋈ DescTelescopePi.subjectReductionFromPiValidity = the Wf-THREADING
-- master SR re-statement: the shipped subjectReductionOfPiElimArm is conditional on the WHOLE grown context-conversion
-- piElim arm as a WfContextDescPi-FREE hypothesis, which CANNOT be discharged from the residual (the route needs
-- WfContextDescPi to expose the function's Π-classifier validity, and HasTypeDescPi → WfContextDesc is REFUTED by
-- ContextValidityFails — the var rule types in ill-formed contexts — so Wf can't be recovered inside the arm). The
-- shipped master SR consumes its piElim arm in EXACTLY ONE place (the telescope here arm's convTelescopeOfPiElimArm);
-- replacing that ONE call with #1093's Wf-threading convTelescopeWfOfPiValidity (source Wf from WfContextDescPi.cons)
-- re-bases the whole mutual block on the residual, every other arm unchanged — a mechanical re-statement, not a new
-- proof. grownMutualMetatheoryFromPiValidity = the explicit unification: ONE residual ⟹ BOTH. So GrownCtxConv-5 and SRD-2
-- provably share a single obligation; discharging it (syntactic GTL-21 OR the semantic/reducibility route) closes
-- both. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.grownContextConversionFromPiValidity
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.grownMutualMetatheoryFromPiValidity

-- HasTypeDescPiContextConversionPiElimEquivalence: the REVERSE direction `piElimArm → residual`, completing the
-- equivalence `ConvContextPreservesPiValidity ⟺ piElimArm`. piElimArmFromPiValidityTransfer (#1092) gives the forward
-- (residual + source Wf ⟹ piElimArm — the conv rule re-types the function at the literal Π-code, needing IsTypeDescPi
-- tgt (Π D C)). piValidityFromPiElimArm gives the reverse with NO Wf premise: convContextOfPiElimArm transports the
-- Π-CODE's universe typing, and the conv-back to the literal universe code is FREE (the conv rule's reclassifierTyped
-- obligation is here the universe code's OWN validity via ofFormation∘universeFormation, not a Π-code's — so the
-- circularity that blocks the application case does NOT arise for the type-code case). Together: GrownCtxConv-5's entire
-- remaining content IS the single piElim arm. masterSubjectReductionFromPiElimArm = the capstone: piElimArm alone yields
-- master SR (chaining the reverse through GTL-20's masterSubjectReductionFromPiValidity); combined with
-- convContextOfPiElimArm (grown context conversion from piElimArm, no extra premise) this exhibits piElimArm as the
-- single lynchpin of the grown metatheory. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.piValidityFromPiElimArm

-- HasTypeDescPiContextStepConversion (SR-U1, the unconditional DIRECTED context-conversion route toward #842/#845/#558):
-- ConvContextWithOldValid Γ Γ' := ∀ i, Conv (Γ.lookup i) (Γ'.lookup i) ∧ IsTypeDescPi Γ' (Γ.lookup i) — old entries Conv
-- to new AND valid in new (FREE for a directed step / unchanged prefix; FAILS for arbitrary Conv = the residual).
-- convContextExactToGrown: a FORMATION subject re-types EXACTLY into the GROWN engine under the enriched condition. var
-- conv's back to the EXACT old classifier via the enriched validity (the linchpin that arbitrary-Conv convContext can't
-- make — its docstring names "type the OLD entry under the NEW context" as the sinking circularity); universe/conv/
-- genFormation are universe-classified/free (genFormation via the shipped exact DescTelescope.convTelescope on the .1
-- projection). This is the ofFormation leaf of the grown directed context conversion (SR-U2 next). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.convContextExactToGrown

-- ConvContextWithOldValid.cons (SR-U2 infra): the enriched condition LIFTS under a shared binder — the binder-crossing
-- closure the grown directed context conversion needs at its piIntro / genFormationPi arms. index 0: both sides look up
-- the weakened binder (Conv.refl) + its validity from weakening bindingValid (weakenUnderBinding + rename_universeCodeCell,
-- the universe classifier is closed so weakening fixes it); index k+1: the weakened old condition. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.ConvContextWithOldValid.cons

-- SR-U3 (the directed-step instance): ConvContextWithOldValid.ofHeadStep builds the enriched condition FREE for a head
-- domain step (domain ↝ domainReduct, prefix UNCHANGED): index 0 = Conv (weaken domain) (weaken domainReduct) from the
-- step + domain's prefix-validity (headIsType) weakened; index k+1 = refl (prefix entries unchanged) + lookupIsType
-- weakened. ★ HasTypeDescPi.codomainReTypingStep = contextConversionExact ∘ ofHeadStep: a codomain re-types across a
-- stepped domain binder at the SAME classifier, UNCONDITIONALLY — the grown twin of the shipped FORMATION
-- codomainReTypingOfFormationStep (#1096), discharging the grown codomainReTyping that gated master SR (SRD-1/#844 →
-- SRD-2/#845 → SN-055/#558). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.ConvContextWithOldValid.ofHeadStep
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.codomainReTypingStep

-- ★ convContextUnderWf ⋈ convTelescopeUnderWf — the GROWN context conversion, UNCONDITIONAL under target
-- well-formedness: the structural closure of GrownCtxConv-5/#842 (the piElim context-conversion arm that resisted
-- 40+ firings).  A faithful transform of the conditional convContextOfPiElimArm ⋈ convTelescopeOfPiElimArm with the
-- piElimArm hypothesis DROPPED: the piElim arm uses piElimArmUnderWfTarget (functionFlexible derived from
-- functionConverted via classifierIsTypeDescPi), the var-style leaves are wf-FREE (the var rule types
-- unconditionally), and target wf is threaded + extended at piIntro/telescope-cons via WfContextDescPi.cons.  The
-- wf-FREE arbitrary-Conv version is genuinely LR-bound (the source→target wf bridge is circular with the theorem,
-- and classifierRespectsConv is refuted #1058); carrying TARGET wf cuts the knot, reading every needed target
-- validity off lookupIsType/classifierIsTypeDescPi.  So this is the MAXIMAL structural closure — unconditional
-- modulo a presupposition of exactly SN-043's benign character (HasTypeDescPi → WfContextDesc is itself refuted).
-- Master SR does NOT consume this (SR-U4 routed through the EXACT directed conversion); this is the standalone
-- GrownCtxConv-5 result.  Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.convContextUnderWf
#assert_no_axioms FX1Poly.Typed.DescTelescopePi.convTelescopeUnderWf

-- GrownCtxConv-5-FORMFRAG (#1099): the residual ConvContextPreservesPiValidity is UNCONDITIONALLY free for FORMATION-valid
-- Π-codes (ConvContextPreservesPiValidityFormationFragment.lean). convContextPreservesPiValidityForFormationCode:
-- a piTyCodeCell D C that is a FORMATION type (IsTypeDesc, no type-level computation) context-converts to a grown
-- type (IsTypeDescPi) under any pointwise-Conv-related target, via the shipped unconditional formation
-- context-conversion convContextOfFormation (HasTypeDesc.convContext re-embedded through ofFormation) +
-- convBackToUniverseCode — NO semantic input. Together with #1095 (the validity-respects-reduction twin is likewise
-- free for the formation fragment), this LOCALIZED the residual's then-open core precisely to the
-- GENUINELY-GROWN Π-codes: NEUTRAL type-level applications ((var f)(var a) at a universe) / type-level λ, typed
-- via piElim/piIntro at the type level, NOT via ofFormation/genFormationPi-from-formation. That neutral case WAS
-- GrownCtxConv-5 itself (context-converting a neutral type-level application is the piElim context-conversion); no
-- further syntactic fragment was left to peel. STATUS: the core has since been closed UNCONDITIONALLY via the SR-U
-- enriched-condition route (SR-U4/SR-U5), and the neutral-reconstruction hypothesis is separately discharged under
-- target wf (TypedTypeValidityLeveledTransportUnderWf). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.convContextPreservesPiValidityForFormationCode
-- GrownCtxConv-5-GENFORMERSTEP (#1122): the TABLE-GENERIC genFormationPi former step
-- (GenFormerValidityContextConversion.lean) — ONE theorem covering EVERY genFormationPi type-code former (Π, Σ,
-- list, option, id, equiv, and any future typingRuleDescOf row), the cascade-free consolidation of the per-former
-- Π (#1120) and Σ (#1121) steps. convTelescopeFromChildIH: the reusable telescope-validity transport — a grown
-- premise telescope transports across a pointwise-Conv context conversion GIVEN a scope-polymorphic,
-- universe-code-PRESERVING per-child IH (each head re-types via the IH, each tail recurses under the cons-lifted
-- convContextCondition_cons); the validity-rebuild analogue of convTelescopeOfPiElimArm gated on the recursive
-- type-code IH rather than the general piElimArm. genFormerValidityContextConversion: re-form a genFormationPi
-- former under the converted target by transporting its premise telescope and re-firing genFormationPi (same
-- rule.outputType). FRAME-2 cascade-freedom: a new type-code former needs ZERO new context-conversion arms.
-- Zero-axiom.
#assert_no_axioms FX1Poly.Typed.DescTelescopePi.convTelescopeFromChildIH
-- neutralRecon DISCHARGED under target wf (TypedTypeValidityLeveledTransportUnderWf.lean) — the leveled
-- transport's lone conditional arm closed by composing convContextUnderWf (#1133, post-dates the transport)
-- with convBackToUniverseCode: a subject typed at an EXACT universe code survives pointwise-Conv context
-- conversion at that SAME code given WfContextDescPi target (IsNeutral not even needed).
-- universeClassifiedConvContextUnderWf is the discharge; transportUnderWf re-runs the leveled-LR transport
-- with the neutral arm closed (wf extended at the piType binder via the transported domain's exact universe
-- typing), PRESERVING the candidate box — the LR structure transports, not just the typing;
-- transportValidityUnderWf is the GrownCtxConv-5-residual-shaped payoff. Converts the #1168
-- grown-strengthening chain's neutralRecon link from an open LR research hypothesis into the same benign
-- WfContextDescPi presupposition SN-043/OSN-1 carry. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.universeClassifiedConvContextUnderWf

-- GrownCtxConv-5 SECOND piElim-arm reduction, to TypeCodeValidityRespectsReduction (HasTypeDescPiContextConversionValidity
-- Reduction.lean, GrownCtxConv-5-VALRED, toward #842). The FLEXIBLE route, twin of #1092's exact route. The fine-grained
-- obstruction: a context-conversion bundle's piElim arm must re-type the function under tgt at SOME Π-code. EXACT
-- motive (re-type at the original Π D C) closes piElim (#1092 reassembly) but var needs IsType-respects-Conv
-- (FALSE #1058); FLEXIBLE motive (any Conv-equal Π-code) closes var (WfContextDescPi.lookupIsType gives the tgt
-- binding's validity) but piElim needs validity-survives-reduction. Both bridges = the same SR-grade fact, routing
-- through the logical relation. TypeCodeValidityRespectsReduction = the flexible residual (IsTypeDescPi ctx S →
-- StepStar S T → IsTypeDescPi ctx T, single-context "subject reduction for type codes"). reassembleApplication
-- FromConvEqualPiValidity generalizes #1092's reassembly to a Conv-equal Π reductD reductC (via Conv.piTyCode_cong
-- + Conv.subst0). piElimArmFromValidityRespectsReduction: from the function's flexible classifier-transfer IH +
-- reducesToPiTyCode (PC' ⤳* Π reductD reductC) + the residual + the generalized reassembly. Triangulates the GrownCtxConv-5
-- residual with #1092/#1093 (exact ConvContextPreservesPiValidity vs flexible TypeCodeValidityRespectsReduction,
-- inter-derivable, both logical-relation-discharged). Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDescPi.reassembleApplicationFromConvEqualPiValidity

-- GrownCtxConv-5 formation/grown BOUNDARY, named (same file, GrownCtxConv-5-FORMBOUND, toward #842). HasTypeDesc.codomainReTyping
-- OfFormationStep: codomain re-typing under a stepped domain binder is UNCONDITIONAL for FORMATION codomains -- the
-- single domain Step gives Conv domain domainReduct (Conv.fromStepStar), hence the pointwise context-conversion
-- condition (convContextCondition_consStep), and the UNCONDITIONAL formation HasTypeDesc.convContext re-types the
-- codomain (conv-backed to the same universe code). This is the formation analogue of the grown codomainReTyping
-- (GrownCtxConv-6 #843) but UNCONDITIONAL where the grown one is gated on GrownCtxConv-5. It IS exactly the move the grown engine
-- cannot make for genuinely-grown codomains -- that single asymmetry (formation context-conversion unconditional,
-- grown not) is the ENTIRE content of why GrownCtxConv-5 / master-SR genFormationPi / TypeCodeValidityRespectsReduction
-- remain open and need the FX logical relation. Zero-axiom.
#assert_no_axioms FX1Poly.Typed.HasTypeDesc.codomainReTypingOfFormationStep

/- GrownCheck structural helpers (GrownCheckContextConversion): EXACT-target context conversion under
pointwise-Conv contexts (raw relation → no wf needed, contrast convContextUnderWf) + the Conv-related-binders
cons condition + the binder-swap corollary (the reflection's swap-the-floating-binder ingredient) + the
target-side Π exposure (reducesToPiTyCode ∘ subjectReductionStar ∘ invertPiTyCode, wf-conditional) + the
lam/app soundness reassembly shapes consumed by the STR-5 soundness induction. -/

#assert_no_axioms FX1Poly.Typed.convContextCondition_consConv
#assert_no_axioms FX1Poly.Typed.GrownCheck.convContext
#assert_no_axioms FX1Poly.Typed.GrownCheckTelescope.convContext
