import LeanFX2.HoTT.HIT.Eliminator

/-! # HoTT/HIT/PropTrunc

Propositional truncation as an explicit setoid presentation.

The carrier is the source type and the path relation is generated by
the named squash constructor `PropTruncRel.merge`: any two
representatives are related.  This does not make the representatives
definitionally equal in Lean; every eliminator must carry a proof that
it respects the squash relation.

This is the first concrete HIT specialization over the generic
`HITSetoid` / `HITRecursor` foundation.  It deliberately avoids
Lean's quotient machinery and therefore avoids `Quot.sound`.
-/

namespace LeanFX2
namespace HoTT
namespace HIT

universe sourceLevel resultLevel

/-- The path relation generated by propositional truncation's squash
constructor.  A witness of `merge left right` is the setoid-level path
identifying any two representatives. -/
inductive PropTruncRel (sourceType : Type sourceLevel) :
    sourceType → sourceType → Prop where
  | merge (leftValue rightValue : sourceType) :
      PropTruncRel sourceType leftValue rightValue

namespace PropTruncRel

/-- Reflexivity for the squash-generated relation. -/
theorem relation_refl {sourceType : Type sourceLevel}
    (sourceValue : sourceType) :
    PropTruncRel sourceType sourceValue sourceValue :=
  PropTruncRel.merge sourceValue sourceValue

/-- Symmetry for the squash-generated relation. -/
theorem relation_symm {sourceType : Type sourceLevel}
    {leftValue rightValue : sourceType}
    (_relationWitness : PropTruncRel sourceType leftValue rightValue) :
    PropTruncRel sourceType rightValue leftValue :=
  PropTruncRel.merge rightValue leftValue

/-- Transitivity for the squash-generated relation. -/
theorem relation_trans {sourceType : Type sourceLevel}
    {leftValue middleValue rightValue : sourceType}
    (_firstWitness : PropTruncRel sourceType leftValue middleValue)
    (_secondWitness : PropTruncRel sourceType middleValue rightValue) :
    PropTruncRel sourceType leftValue rightValue :=
  PropTruncRel.merge leftValue rightValue

end PropTruncRel

/-- Propositional truncation presentation for a source type.

The current zero-axiom encoding exposes the setoid presentation rather
than a quotient carrier.  Consumers eliminate through `PropTrunc.rec`,
which requires a proof that all outputs are equal. -/
def PropTrunc (sourceType : Type sourceLevel) : HITSetoid.{sourceLevel} :=
  HITSetoid.fromEquivalence
    sourceType
    (PropTruncRel sourceType)
    PropTruncRel.relation_refl
    PropTruncRel.relation_symm
    PropTruncRel.relation_trans

namespace PropTrunc

/-- Introduce a representative into the propositional truncation
presentation. -/
def intro {sourceType : Type sourceLevel}
    (sourceValue : sourceType) :
    (PropTrunc sourceType).carrier :=
  sourceValue

/-- Any two representatives are related by the squash path. -/
theorem squash {sourceType : Type sourceLevel}
    (leftValue rightValue : (PropTrunc sourceType).carrier) :
    (PropTrunc sourceType).relation leftValue rightValue :=
  PropTruncRel.merge leftValue rightValue

/-- Non-dependent recursion out of propositional truncation.

The caller must prove that the output does not depend on which witness
of the source type was chosen. -/
def rec {sourceType : Type sourceLevel}
    (resultType : Sort resultLevel)
    (introCase : sourceType → resultType)
    (squashRespects :
      ∀ leftValue rightValue : sourceType,
        introCase leftValue = introCase rightValue) :
    HITRecursor (PropTrunc sourceType) resultType where
  apply := introCase
  respectsRelation := fun {leftValue} {rightValue} _relationWitness =>
    squashRespects leftValue rightValue

/-- Recursion computes on introduced representatives by reflexive
reduction. -/
theorem rec_intro {sourceType : Type sourceLevel}
    (resultType : Sort resultLevel)
    (introCase : sourceType → resultType)
    (squashRespects :
      ∀ leftValue rightValue : sourceType,
        introCase leftValue = introCase rightValue)
    (sourceValue : sourceType) :
    (PropTrunc.rec resultType introCase squashRespects).run
      (PropTrunc.intro sourceValue) =
      introCase sourceValue :=
  rfl

/-- A recursor maps squash-related representatives to equal outputs. -/
theorem rec_squash {sourceType : Type sourceLevel}
    (resultType : Sort resultLevel)
    (introCase : sourceType → resultType)
    (squashRespects :
      ∀ leftValue rightValue : sourceType,
        introCase leftValue = introCase rightValue)
    (leftValue rightValue : sourceType) :
    (PropTrunc.rec resultType introCase squashRespects).run
      (PropTrunc.intro leftValue) =
      (PropTrunc.rec resultType introCase squashRespects).run
        (PropTrunc.intro rightValue) :=
  HITRecursor.run_respects
    (PropTrunc.rec resultType introCase squashRespects)
    (PropTrunc.squash leftValue rightValue)

/-- Dependent induction out of propositional truncation.

The caller supplies a motive over representatives, an intro case for
each source value, and a proof that those motive witnesses are
heterogeneously equal across the squash relation. -/
def dependentInductor {sourceType : Type sourceLevel}
    (motive : (PropTrunc sourceType).carrier → Sort resultLevel)
    (introCase :
      ∀ sourceValue : sourceType,
        motive (PropTrunc.intro sourceValue))
    (squashRespects :
      ∀ leftValue rightValue : sourceType,
        HEq (introCase leftValue) (introCase rightValue)) :
    HITInductor (PropTrunc sourceType) motive where
  apply := introCase
  respectsRelation := fun {leftValue} {rightValue} _relationWitness =>
    squashRespects leftValue rightValue

/-- Dependent induction computes on introduced representatives by
reflexive reduction. -/
theorem dependentInductor_intro {sourceType : Type sourceLevel}
    (motive : (PropTrunc sourceType).carrier → Sort resultLevel)
    (introCase :
      ∀ sourceValue : sourceType,
        motive (PropTrunc.intro sourceValue))
    (squashRespects :
      ∀ leftValue rightValue : sourceType,
        HEq (introCase leftValue) (introCase rightValue))
    (sourceValue : sourceType) :
    (PropTrunc.dependentInductor motive introCase squashRespects).run
      (PropTrunc.intro sourceValue) =
      introCase sourceValue :=
  rfl

/-- Dependent induction respects the propositional-truncation squash
relation. -/
theorem dependentInductor_squash {sourceType : Type sourceLevel}
    (motive : (PropTrunc sourceType).carrier → Sort resultLevel)
    (introCase :
      ∀ sourceValue : sourceType,
        motive (PropTrunc.intro sourceValue))
    (squashRespects :
      ∀ leftValue rightValue : sourceType,
        HEq (introCase leftValue) (introCase rightValue))
    (leftValue rightValue : sourceType) :
    HEq
      ((PropTrunc.dependentInductor motive introCase squashRespects).run
        (PropTrunc.intro leftValue))
      ((PropTrunc.dependentInductor motive introCase squashRespects).run
        (PropTrunc.intro rightValue)) :=
  HITInductor.run_respects
    (PropTrunc.dependentInductor motive introCase squashRespects)
    (PropTrunc.squash leftValue rightValue)

/-- Constant recursion out of propositional truncation. -/
def recConstant {sourceType : Type sourceLevel}
    (resultType : Sort resultLevel)
    (resultValue : resultType) :
    HITRecursor (PropTrunc sourceType) resultType :=
  HITRecursor.constant resultType resultValue

/-- Constant recursion computes by reflexive reduction. -/
theorem recConstant_intro {sourceType : Type sourceLevel}
    (resultType : Sort resultLevel)
    (resultValue : resultType)
    (sourceValue : sourceType) :
    (PropTrunc.recConstant
      (sourceType := sourceType) resultType resultValue).run
      (PropTrunc.intro sourceValue) =
      resultValue :=
  rfl

end PropTrunc

end HIT
end HoTT
end LeanFX2
