import LeanFX2.HoTT.HIT.Spec

/-! # HoTT/HIT/Setoid — setoid encoding of HITs

Encode a HIT presentation as `(Carrier, Relation)` where:
* `Carrier` is a regular type with point representatives
* `Relation` is an equivalence relation generated by path constructors
  and congruence

Usage in lean-fx-2:

```lean
def EncodedHIT (spec : HITSpec) : HITSetoid := ...
```

Maps out of the presentation carry manual relation-preservation
proofs.  The current foundation does not take a Lean quotient.

## Why setoid encoding

Lean 4 has native `Quot.mk`/`Quot.lift` but they leak `Quot.sound`.
For zero-axiom HITs we need *manual* respect proofs that avoid
`Quot.sound`.

The setoid approach: track the underlying value + an equivalence
relation, prove operations preserve the relation explicitly.  No
propext.

## Trade-offs

* Pro: zero axioms
* Con: each operation needs a `respect`-preservation proof
* Con: not as ergonomic as native HITs

## Dependencies

* `HoTT/HIT/Spec.lean`

## Downstream consumers

* `HoTT/HIT/Eliminator.lean`
* `HoTT/HIT/Examples.lean`

## Diff from lean-fx

lean-fx had this on the roadmap (#950).  lean-fx-2 now ships the
first load-bearing setoid foundation; concrete HIT modules still need
their own relations, recursors, and computation smokes.
-/

namespace LeanFX2
namespace HoTT
namespace HIT

universe carrierLevel resultLevel

/-- An explicit setoid presentation used as the zero-axiom carrier for
HIT approximations.  This is intentionally a structure, not Lean's
`Quot`, so no eliminator can smuggle in `Quot.sound`. -/
structure HITSetoid where
  /-- Underlying point carrier. -/
  carrier : Type carrierLevel
  /-- Relation generated by the HIT path constructors. -/
  relation : carrier → carrier → Prop
  /-- The relation is reflexive. -/
  isRefl : ∀ someValue : carrier, relation someValue someValue
  /-- The relation is symmetric. -/
  isSymm :
    ∀ {leftValue rightValue : carrier},
      relation leftValue rightValue →
      relation rightValue leftValue
  /-- The relation is transitive. -/
  isTrans :
    ∀ {leftValue middleValue rightValue : carrier},
      relation leftValue middleValue →
      relation middleValue rightValue →
      relation leftValue rightValue

namespace HITSetoid

/-- Relation-preservation predicate for ordinary functions out of a
setoid presentation. -/
def preservesRelation (encodedHit : HITSetoid.{carrierLevel})
    {resultType : Sort resultLevel}
    (someMap : encodedHit.carrier → resultType) : Prop :=
  ∀ {leftValue rightValue : encodedHit.carrier},
    encodedHit.relation leftValue rightValue →
    someMap leftValue = someMap rightValue

/-- The discrete setoid over a carrier: only definitionally equal points
are related. -/
def discrete (carrier : Type carrierLevel) : HITSetoid where
  carrier := carrier
  relation := Eq
  isRefl := fun someValue => Eq.refl someValue
  isSymm := fun relationWitness => Eq.symm relationWitness
  isTrans := fun firstWitness secondWitness =>
    Eq.trans firstWitness secondWitness

/-- The indiscrete setoid over a carrier: every two points are related.
This is the setoid presentation behind propositional truncation. -/
def indiscrete (carrier : Type carrierLevel) : HITSetoid where
  carrier := carrier
  relation := fun _ _ => True
  isRefl := fun _ => True.intro
  isSymm := fun _ => True.intro
  isTrans := fun _ _ => True.intro

/-- Pack an already-proven equivalence relation as a HIT setoid
presentation. -/
def fromEquivalence
    (carrier : Type carrierLevel)
    (relation : carrier → carrier → Prop)
    (isRefl : ∀ someValue : carrier, relation someValue someValue)
    (isSymm :
      ∀ {leftValue rightValue : carrier},
        relation leftValue rightValue →
        relation rightValue leftValue)
    (isTrans :
      ∀ {leftValue middleValue rightValue : carrier},
        relation leftValue middleValue →
        relation middleValue rightValue →
        relation leftValue rightValue) :
    HITSetoid :=
  { carrier := carrier,
    relation := relation,
    isRefl := isRefl,
    isSymm := isSymm,
    isTrans := isTrans }

/-- Relation reflexivity, exposed as a theorem for audit gates and
downstream code. -/
theorem relation_refl (encodedHit : HITSetoid.{carrierLevel})
    (someValue : encodedHit.carrier) :
    encodedHit.relation someValue someValue :=
  encodedHit.isRefl someValue

/-- Relation symmetry, exposed as a theorem for audit gates and
downstream code. -/
theorem relation_symm (encodedHit : HITSetoid.{carrierLevel})
    {leftValue rightValue : encodedHit.carrier}
    (relationWitness : encodedHit.relation leftValue rightValue) :
    encodedHit.relation rightValue leftValue :=
  encodedHit.isSymm relationWitness

/-- Relation transitivity, exposed as a theorem for audit gates and
downstream code. -/
theorem relation_trans (encodedHit : HITSetoid.{carrierLevel})
    {leftValue middleValue rightValue : encodedHit.carrier}
    (firstWitness : encodedHit.relation leftValue middleValue)
    (secondWitness : encodedHit.relation middleValue rightValue) :
    encodedHit.relation leftValue rightValue :=
  encodedHit.isTrans firstWitness secondWitness

end HITSetoid

end HIT
end HoTT
end LeanFX2
