import FX1Poly.Core.StepWordRewriteSoundness
import FX1Poly.Core.StepEta

/-! # FX1Poly/Core/BetaEtaWordSystem
    — the certified β/ι/η word-rewrite system (SN-130, #633)

SN-126's `fxStepSystem` is generated by `Step` = β + ι (+ cong) only; the η rules live in the SIBLING relation
`Step.eta`, so the word bridge of SN-127..129 covered β/ι but NOT η.  This file enumerates the FULL certified
rule system — `fxBetaEtaStepSystem`, generated by every `Step.betaEta` (= `Step ∨ Step.eta`, `StepEta.lean`)
reduction — so β, ι, AND η are all certified word-rewrite rules of one system, and proves the β/ι system embeds
in it.

`FxWordRewritesOneStep` / `FxWordRewritesMany` (SN-127) are generic over the rule system, so this file reuses
them directly at `fxBetaEtaStepSystem` — no new word-rewrite relation is needed.

## What is proved

* `fxBetaEtaStepSystem` — the certified β/ι/η rule system: a rule is in it iff it is some `Step.betaEta`
  reduction's term-code pair.
* `Step.betaEta.inducedRewriteRule` + `_mem_fxBetaEtaStepSystem` — the rule each β/ι/η reduction induces, and its
  membership (generic, mirroring SN-126).
* `Step.betaEta.toWordRewrite` — single-step soundness into the unified system (the `fire` lift).
* `fxStepSystem_imp_fxBetaEtaStepSystem` — the β/ι system (over `Step`) EMBEDS in the β/ι/η system (over
  `Step.betaEta`), via the `Or.inl` inclusion `Step ⟶ Step.betaEta`.
* `Step.toBetaEtaWordRewrite` / `Step.eta.toBetaEtaWordRewrite` — β/ι rules (via `Or.inl`) AND η rules (via
  `Or.inr`) are both word rewrites of the unified system.  The η half is the NEW capability the earlier
  `fxStepSystem` lacked.
* `Step.betaEtaStar.toWordRewrites` — many-step (η-inclusive) soundness, by induction over the β/ι/η reduction
  chain.

This is the rule enumeration SN-134's `WordReducer` / `decidableConvertibleModulo_ofConvergent` will range over
once the FX word system's termination (SN-131, typed-SN-gated) and confluence (SN-132/133) land.

## Zero-axiom verification

`fxBetaEtaStepSystem` is a plain `∃`; the rule map is a record literal; membership is an existential intro with
`rfl` witnesses; `toWordRewrite` is the `fire` constructor; the embedding and the `Or.inl`/`Or.inr` inclusions are
`obtain` + anonymous-constructor with the disjunction injection (defeq into the `Step.betaEta` def); the many-step
soundness is a structural induction over `Step.betaEtaStar`.  No `axiom`, `sorry`, `propext`, `Quot.sound`,
`Classical`, `native_decide`, `omega`.  Per-declaration gated in `FX1PolyAudit/AuditCore.lean`.
-/

namespace FX1Poly.Core

/-- **The certified β/ι/η rule system**: a rule belongs to it iff it is the term-code pair of some `Step.betaEta`
(= β/ι via `Step`, or η via `Step.eta`) reduction. -/
def fxBetaEtaStepSystem (rule : FxTermRewriteRule) : Prop :=
  ∃ (scope : Nat) (redex reduct : RawTerm scope),
    Step.betaEta redex reduct
      ∧ rule.leftHandSide = redex.toCode
      ∧ rule.rightHandSide = reduct.toCode

/-- The rewrite rule a β/ι/η reduction induces: its redex's and reduct's term codes. -/
def Step.betaEta.inducedRewriteRule {scope : Nat} {redex reduct : RawTerm scope}
    (_step : Step.betaEta redex reduct) : FxTermRewriteRule where
  leftHandSide := redex.toCode
  rightHandSide := reduct.toCode

/-- Every β/ι/η reduction's induced rule is a rule of the unified system (membership by construction). -/
theorem Step.betaEta.inducedRewriteRule_mem_fxBetaEtaStepSystem {scope : Nat}
    {redex reduct : RawTerm scope} (step : Step.betaEta redex reduct) :
    fxBetaEtaStepSystem (Step.betaEta.inducedRewriteRule step) :=
  ⟨scope, redex, reduct, step, rfl, rfl⟩

/-- **Single-step soundness** into the unified system: every β/ι/η reduction is a one-step word rewrite under
`fxBetaEtaStepSystem` (the `fire` of its system rule). -/
theorem Step.betaEta.toWordRewrite {scope : Nat} {redex reduct : RawTerm scope}
    (step : Step.betaEta redex reduct) :
    FxWordRewritesOneStep fxBetaEtaStepSystem redex.toCode reduct.toCode :=
  FxWordRewritesOneStep.fire (Step.betaEta.inducedRewriteRule step)
    (Step.betaEta.inducedRewriteRule_mem_fxBetaEtaStepSystem step)

/-- **The β/ι system embeds in the β/ι/η system**: every `fxStepSystem` rule is an `fxBetaEtaStepSystem` rule,
via the `Or.inl` inclusion `Step ⟶ Step.betaEta`. -/
theorem fxStepSystem_imp_fxBetaEtaStepSystem {rule : FxTermRewriteRule}
    (mem : fxStepSystem rule) : fxBetaEtaStepSystem rule := by
  obtain ⟨scope, redex, reduct, step, lhsEq, rhsEq⟩ := mem
  exact ⟨scope, redex, reduct, Or.inl step, lhsEq, rhsEq⟩

/-- A β/ι reduction (a `Step`) is a word rewrite of the unified system (via `Or.inl`). -/
theorem Step.toBetaEtaWordRewrite {scope : Nat} {redex reduct : RawTerm scope}
    (step : Step redex reduct) :
    FxWordRewritesOneStep fxBetaEtaStepSystem redex.toCode reduct.toCode :=
  Step.betaEta.toWordRewrite (Or.inl step)

/-- An η reduction (a `Step.eta`) is a word rewrite of the unified system (via `Or.inr`) — the capability the
β/ι-only `fxStepSystem` lacked. -/
theorem Step.eta.toBetaEtaWordRewrite {scope : Nat} {redex reduct : RawTerm scope}
    (etaStep : Step.eta redex reduct) :
    FxWordRewritesOneStep fxBetaEtaStepSystem redex.toCode reduct.toCode :=
  Step.betaEta.toWordRewrite (Or.inr etaStep)

/-- **Many-step (η-inclusive) soundness**: every β/ι/η reduction sequence is a word-rewrite sequence under the
unified system, by induction over the `Step.betaEtaStar` chain. -/
theorem Step.betaEtaStar.toWordRewrites {scope : Nat} {startTerm finalTerm : RawTerm scope}
    (steps : Step.betaEtaStar startTerm finalTerm) :
    FxWordRewritesMany fxBetaEtaStepSystem startTerm.toCode finalTerm.toCode := by
  induction steps with
  | refl term => exact FxWordRewritesMany.refl term.toCode
  | trans headStep _tailStar tailIH =>
      exact FxWordRewritesMany.step headStep.toWordRewrite tailIH

end FX1Poly.Core
