import FX1Poly.Core.CellSort

/-! # Foundation/PolyCell/Core/RuleSpec — dim-1 generating-rule admission

This file ships the v2 generating-rule metadata + admission layer for
dim-1 cells (rewrite rules).  Parallel to:

* `GeneratorAdmission` — admits dim-0 generators (term-formers)
* `GenPayloadEvidence` — admits generator payloads (Type-Unit
  trivially under fxProfile)

Per `polycell.md` §4, the certified `PolyCell.generatingCell`
constructor takes BOTH a `RuleSpec` parameter (the rule's metadata)
AND a `SupportedRuleSpec rule` parameter (the per-rule admission
witness).  This file ships the v2 counterparts.

## Architectural distinction — closed enum vs open set

`SupportedGenerator` is parameterized over `Generator`, a CLOSED
enum with 194 named constructors.  That makes the total form
`supportedGenerator : (g : Generator) -> SupportedGenerator g`
well-defined — exhaustive by `cases g`.

`SupportedRuleSpec` is parameterized over `RuleSpec`, a STRUCTURE
whose `ruleId : Nat` field admits infinitely many distinct rule
values.  No total admission witness exists — most `RuleSpec` values
are not admitted by any current profile.  Hence only the
Option-valued lookup `supportedRuleSpec?` ships here, never a total
form.

## Three pieces

1. `RuleSpec` structure — rule metadata (ruleId, cellSort,
   endpointDimension).  Auto-derives `DecidableEq` from its `Nat` +
   `CellSort` components (both zero-axiom).

2. `termStepRuleSpec : RuleSpec` constant — the seed rule.
   ruleId 0, cellSort `.term`, endpointDimension 0.  Mirrors v1's
   `termStepRuleSpec`.  Marked `@[reducible]` so downstream
   DecidableEq comparisons can reduce through the abstraction.

3. `SupportedRuleSpec : RuleSpec -> Type` inductive — the
   admission ledger.  Currently one arm: `.termStep` admits
   `termStepRuleSpec`.  Future arms = future rule kinds (cubical
   beta rules, modal cross-rules, observational equality rules).

## Two lookup interfaces

* `lookupRuleSpec? : Nat -> Option RuleSpec` — ruleId-keyed
  lookup.  The certifier extracts a `ruleId` from a raw
  `generatingCell ruleId source target` payload and uses this lookup
  to retrieve the admitted rule's metadata.

* `supportedRuleSpec? : (rule : RuleSpec) -> Option (...)` —
  dependent admission-witness lookup.  Returns the typed admission
  witness if the rule is admitted, else none.  Used at the certified
  layer to produce the `SupportedRuleSpec rule` parameter the
  `generatingCell` ctor demands.

## Why two distinct lookups

Either alone is insufficient:

* `lookupRuleSpec?` returns the RuleSpec but NOT the admission
  witness.  Useful when the certifier wants to know "what rule does
  ruleId 0 refer to?" before checking admission.

* `supportedRuleSpec?` returns the admission witness for a
  SPECIFIC RuleSpec.  Useful when the certifier already has a
  RuleSpec in hand and wants the typed admission witness.

Composed: `match lookupRuleSpec? ruleId with | some rule =>
match supportedRuleSpec? rule with | some witness => ...`.  Both
return `none` for unrecognized inputs; the certifier reports
`.unsupportedRule` in the `none` case.

## Why no `deriving DecidableEq` on `SupportedRuleSpec`

Same reason as `SupportedGenerator`: autogenerated DecEq for
indexed inductives can pull `propext` via `noConfusion` over the
index mismatch cases.  The admission witness type carries trivial
DecEq anyway (one inhabitant per admitted rule, by index pinning).
If a downstream consumer needs DecEq, it's provided by hand via
case-on-rule.

## The `▸` transport in `supportedRuleSpec?`

When `h : rule = termStepRuleSpec`, transport
`SupportedRuleSpec.termStep : SupportedRuleSpec termStepRuleSpec`
to `SupportedRuleSpec rule` via `h.symm ▸ .termStep`.  This is the
SPIKE-1-style value-level transport, propext-clean because the
equation comes from `Nat.decEq` / `CellSort` DecEq (both zero-axiom),
not from equation-compiler reasoning on a type index.

## Zero-axiom verification

Every shipped declaration audited via `#assert_no_axioms` in
`Tools/AuditAll/AuditPolyCell.lean`.
-/

namespace FX1Poly.Core

/-- Metadata for a dim-1 generating-rule.  Three fields:

* `ruleId : Nat` — stable identifier for ruleId-keyed dispatch
* `cellSort : CellSort` — the sort at which the rule operates
* `endpointDimension : Nat` — the dimension of source/target
  endpoints

Used as a parameter to the certified `PolyCell.generatingCell`
ctor.  DecidableEq derives from `Nat` + `CellSort` component DecEqs
(both zero-axiom). -/
structure RuleSpec where
  ruleId : Nat
  cellSort : CellSort
  endpointDimension : Nat
  deriving DecidableEq

/-- The seed dim-1 term-step rule.  ruleId 0, cellSort `.term`,
endpointDimension 0.

`@[reducible]` so that downstream comparisons of `termStepRuleSpec`
against itself reduce through the abstraction — required for `rfl`-
closing of `supportedRuleSpec?_termStep`. -/
@[reducible] def termStepRuleSpec : RuleSpec where
  ruleId := 0
  cellSort := .term
  endpointDimension := 0

/-- Admission ledger for dim-1 generating rules.  Currently one arm:

* `.termStep` admits `termStepRuleSpec` — the generic term-step
  rewrite rule.

Adding a rule kind = adding ONE new arm here (plus a new
`*RuleSpec : RuleSpec` constant).  Future arms = future rule
kinds (cubical β rules, modal cross-rules, observational equality
rules).

No `deriving DecidableEq`: autogenerated DecEq for indexed inductives
can pull propext via noConfusion.  The witness type carries trivial
DecEq anyway (one inhabitant per admitted rule). -/
inductive SupportedRuleSpec : RuleSpec → Type where
  | termStep : SupportedRuleSpec termStepRuleSpec

/-- ruleId-keyed lookup.  Returns the admitted RuleSpec if matched.

Currently only `ruleId = 0` returns `some termStepRuleSpec`; all
other ruleIds return `none`.  Future rules add new arms.

`@[reducible]` so downstream `rfl`-based proofs can unfold this.

Pattern matches on Nat's two constructors directly (`0` and `_ + 1`)
to avoid the wildcard-pattern propext-leak class catalogued in
`feedback_lean_match_propext_recipe.md`. -/
@[reducible] def lookupRuleSpec? : Nat → Option RuleSpec
  | 0 => some termStepRuleSpec
  | _ + 1 => none

/-- Dependent admission-witness lookup.  Returns the typed admission
witness `SupportedRuleSpec rule` if `rule` is admitted, else
`none`.

Implementation: dispatches on `rule = termStepRuleSpec` via the
auto-derived `DecidableEq`.  When the equation holds, transports
`SupportedRuleSpec.termStep` from index `termStepRuleSpec` to
index `rule` via value-level `▸` (the SPIKE-1 transport).

The `▸` transport is propext-clean because the equation comes from
`Nat.decEq` + `CellSort` decEq (both zero-axiom) on the struct's
fields, not from equation-compiler reasoning on a type index.

`@[reducible]` for downstream unfolding. -/
@[reducible] def supportedRuleSpec? (rule : RuleSpec) :
    Option (SupportedRuleSpec rule) :=
  if equation : rule = termStepRuleSpec then
    some (equation.symm ▸ SupportedRuleSpec.termStep)
  else
    none

/-- Discipline: `lookupRuleSpec?` returns `termStepRuleSpec` for
ruleId 0.  Closes by `rfl` since `lookupRuleSpec?` is `@[reducible]`
and the `0` arm is a literal match. -/
theorem lookupRuleSpec?_zero :
    lookupRuleSpec? 0 = some termStepRuleSpec :=
  rfl

/-- Discipline: `supportedRuleSpec?` returns `some .termStep` for
`termStepRuleSpec`.

Closes by `rfl` if the auto-derived `DecidableEq` on `RuleSpec`
reduces correctly on `termStepRuleSpec = termStepRuleSpec` —
which it does since all three fields (Nat, CellSort, Nat) admit
`rfl` proofs of self-equality and the struct's auto-derived
comparison reduces through them. -/
theorem supportedRuleSpec?_termStep :
    supportedRuleSpec? termStepRuleSpec = some .termStep :=
  rfl

end FX1Poly.Core
