/-! # mode-0 — the Tier0 mode ω-category, design-lock: the mode polygraph data model

`mode-0` is the DESIGN-LOCK of the MODE axis — the second of the four Tier0 ω-categories (context · mode ·
term · type) that meet at `Core/` through the fibration (`fib-*`) tasks.  It fixes the DATA MODEL the whole
mode ladder (`mode-1` … `mode-21`) builds on.

A multimodal type theory (Gratzer–Kavvos–Nuyts–Birkedal, "Multimodal Dependent Type Theory", LMCS 2021) is
parameterised by a MODE THEORY — a (strict, eventually weak) 2-category whose objects are MODES, morphisms are
MODALITIES, and 2-cells are transformations between modalities.  FX presents that mode theory as a POLYGRAPH
(a computad, after Burroni / Street / Batanin): a signature of GENERATING cells per dimension.

## What is locked here (the data model), and what is deferred

mode-0 ships the GENERATING DATA — the 2-polygraph signature (the dimensions a 2-category mode theory needs) —
in full and zero-axiom; it does NOT build the freely-generated category or prove its laws (that is `mode-1`,
the "strict 2-category core").

  * **`ModeGraph`** — the 0- and 1-cell generators: a quiver of `Mode`s (0-cells) and typed `Modality`
    generators (1-cells `Modality a b`).
  * **`ModalityPath`** — the free 1-cells: finite composable sequences of modality generators (the free
    category on the quiver).  `identityPath` (the empty path) and `composePath` (concatenation) are the 1-cell
    identity and composition; `length` measures the 1-cell.  Their CATEGORY LAWS (associativity, right
    identity) are deferred to `mode-1`; only the definitional left identity ships here as a smoke.
  * **`ModeSignature`** — the 2-polygraph: a `ModeGraph` plus a family `twoCell` of generating 2-cells between
    PARALLEL `ModalityPath`s.  (This is exactly why the free 1-cells must already exist: a 2-cell's boundary is
    a parallel pair of 1-cells.)
  * **`ModeAxisData` / `fxModeAxis`** — the FX mode-axis datum (the chosen signature); it grows in `mode-1`+.
  * the canonical NON-DEGENERATE witness `adjunctionModeSignature` — the two-mode adjunction / cohesion seed:
    two distinct modes, a modality each way, and unit/counit 2-cell GENERATORS between non-trivial parallel
    paths — exercising every dimension of the data model.  `trivialModeSignature` is the degenerate base (one
    mode, no non-identity generators = ordinary MTT = ordinary type theory).

DEFERRED (recorded by `= false` markers):
  * the FREE STRICT 2-CATEGORY generated by the signature (path-category laws + free 2-cells with
    vertical/horizontal composition + interchange) and the semantic `FXModeTheory` round-trip —
    `hasStrictTwoCategoryCore = false` (`mode-1`);
  * DECIDABLE 2-CELL EQUALITY via a convergent 3-polygraph (Gratzer's coherence hurdle) —
    `hasDecidableTwoCellEquality = false` (`mode-3`);
  * the higher (dimension > 2) generators + the Gray / semistrict / WEAK ω-category structure (the data model
    here is the 2-truncation, the base of the ω-polygraph) — `hasWeakOmegaStructure = false`
    (`mode-5` / `mode-6` / `mode-21`);
  * the kernel FIBRED over the mode theory (the MTT "everything ⊣ mode") — `hasModeFibration = false`
    (cross-axis, `fib-3`).

## Coherence with the PolyCell cell substrate

This file is the mode theory's POLYGRAPH PRESENTATION — one of THREE complementary layers; keeping them distinct
is the coherence point (it is NOT a duplicate of the existing categorical/cell substrates):

  * **(a) presentation** — `ModeSignature` here: the generating modes/modalities/2-cells.  This is, for the
    mode axis, the analog of the TERM axis's 205-constructor `Generator` enum — a signature, not yet a
    category.  Built standalone (Init only), as each Tier0 axis builds its own generating structures.
  * **(b) presented 2-category** — `mode-1` builds the free strict 2-category on this signature and round-trips
    it against the §3.13 mode theory (`fxModeTheory`: modes / oneCells / twoCells / decidable 1-cell
    equality); its underlying free 1-category packages as a `RawCategory` (the shared categorical substrate the
    CONTEXT axis also plugs into).  So the mode axis joins that substrate at `mode-1`, NOT here — exactly as
    the term axis's `Generator` enum is one level below its `RawCell` cells.
  * **(c) fibered `.mode` cells** — `CellSort.mode` + the `gen_mod*` formers in the Core `Generator` table: the
    modal SYNTAX (`⟨μ | A⟩`, locks) fibred OVER the mode theory.  A modality is a dim-1 `.mode` cell in the one
    PolyCell cell world, whereas `ModeSignature` is the doctrine it is fibred over — a DIFFERENT object.  The
    two meet at `fib-3` (`hasModeFibration = false`).  (`CellSort.mode` is presently unpopulated; the modal
    formers currently sit at sort `.term` pending that migration.)

The 2-cell boundary here (`twoCell : ModalityPath a b → ModalityPath a b → Type`, a 2-cell between a PARALLEL
pair of 1-cells) is the SAME paradigm as the Core `CellBoundary` ("a dim-(n+1) cell carries a source/target
pair of dim-n cells").  And `mode-0` follows the substrate's "COMPUTE the dimension, do not type-index by it"
discipline — paths are indexed by modes, not by a `Nat` dimension — the choice the `RawCell` layer makes to
stay propext-clean, and the one `mode-21` will inherit when the weak ω-structure adds the higher cells.

Zero external dependencies.  Raw Lean 4 + Init only.
-/

namespace FX1Poly.Tier0

/-! ## The 0- and 1-cell generators: the mode quiver -/

/-- A **mode quiver** — the 0- and 1-cell generators of a mode theory: `Mode`s (the 0-cells) and typed
`Modality` generators (the 1-cells, `Modality sourceMode targetMode`).  This is the underlying directed graph
(1-computad) the free 1-category is built on. -/
structure ModeGraph where
  /-- The modes (0-cells). -/
  Mode : Type
  /-- The generating modalities (1-cell generators), typed by source and target mode. -/
  Modality : Mode → Mode → Type

/-! ## The free 1-cells: paths of modalities -/

/-- A **modality path** — a free 1-cell: a finite composable sequence of modality generators from
`sourceMode` to `targetMode`.  `nil` is the identity 1-cell; `cons` prepends a generator.  These are the
1-cells of the free category on the quiver. -/
inductive ModalityPath (graph : ModeGraph) : graph.Mode → graph.Mode → Type where
  /-- The empty path — the identity 1-cell at a mode. -/
  | nil : (mode : graph.Mode) → ModalityPath graph mode mode
  /-- Prepend a modality generator to a path. -/
  | cons : {sourceMode middleMode targetMode : graph.Mode} →
      graph.Modality sourceMode middleMode →
      ModalityPath graph middleMode targetMode →
      ModalityPath graph sourceMode targetMode

/-- The length of a modality path (the number of generators composed) — the 1-cell's word length. -/
def ModalityPath.length {graph : ModeGraph} {sourceMode targetMode : graph.Mode}
    (path : ModalityPath graph sourceMode targetMode) : Nat :=
  match path with
  | .nil _ => 0
  | .cons _ rest => rest.length + 1

/-- The identity 1-cell at a mode (the empty path). -/
def identityPath {graph : ModeGraph} (mode : graph.Mode) : ModalityPath graph mode mode :=
  ModalityPath.nil mode

/-- 1-cell composition — concatenation of modality paths (recursion on the first path).  Its associativity
and right identity (making this a category) are deferred to `mode-1`. -/
def composePath {graph : ModeGraph} {sourceMode middleMode targetMode : graph.Mode}
    (first : ModalityPath graph sourceMode middleMode)
    (second : ModalityPath graph middleMode targetMode) : ModalityPath graph sourceMode targetMode :=
  match first with
  | .nil _ => second
  | .cons modality rest => .cons modality (composePath rest second)

/-- Smoke: the left identity law holds DEFINITIONALLY (`composePath` recurses on the first path, so the empty
path on the left is erased on the nose).  The right identity and associativity are `mode-1`. -/
theorem composePath_identityPath_left {graph : ModeGraph} {sourceMode targetMode : graph.Mode}
    (path : ModalityPath graph sourceMode targetMode) : composePath (identityPath sourceMode) path = path :=
  rfl

/-! ## The 2-polygraph signature -/

/-- A **mode signature** — the 2-polygraph presenting a mode theory: a `ModeGraph` (0- and 1-cell generators)
plus a family `twoCell` of generating 2-cells between PARALLEL 1-cells (modality paths sharing source and
target).  The freely-generated strict 2-category (with the laws) is `mode-1`. -/
structure ModeSignature where
  /-- The underlying quiver of modes and modality generators. -/
  graph : ModeGraph
  /-- The generating 2-cells, indexed by a parallel pair of modality paths (their boundary). -/
  twoCell : {sourceMode targetMode : graph.Mode} →
    ModalityPath graph sourceMode targetMode → ModalityPath graph sourceMode targetMode → Type

/-- The FX mode-axis datum — the chosen signature.  Minimal at the design-lock stage; `mode-1`+ extend it with
the presented 2-category and the `FXModeTheory` round-trip. -/
structure ModeAxisData where
  /-- The mode theory's polygraph signature. -/
  signature : ModeSignature

/-! ## The degenerate base -/

/-- The trivial mode quiver: one mode, no modality generators. -/
def trivialModeGraph : ModeGraph where
  Mode := Unit
  Modality := fun _ _ => Empty

/-- The **trivial (degenerate) mode signature** — one mode, no non-identity modality generators, no 2-cell
generators.  Its free category is the terminal category; MTT over it is ordinary (single-mode) type theory.
The base instance, mirroring `context-0`'s `trivialMode`. -/
def trivialModeSignature : ModeSignature where
  graph := trivialModeGraph
  twoCell := fun _ _ => Empty

/-- The trivial signature is genuinely degenerate: it has NO modality generators (every hom is `Empty`). -/
theorem trivialModeSignature_modality_isEmpty
    (modeOne modeTwo : trivialModeSignature.graph.Mode) :
    trivialModeSignature.graph.Modality modeOne modeTwo = Empty :=
  rfl

/-! ## The canonical non-degenerate witness: the two-mode adjunction / cohesion seed -/

/-- The two modes of the adjunction seed. -/
inductive AdjunctionMode where
  /-- The source mode. -/
  | base
  /-- The target mode. -/
  | tip

/-- The modality generators of the adjunction seed: one in each direction. -/
inductive AdjunctionModality : AdjunctionMode → AdjunctionMode → Type where
  /-- The left modality `base ⟶ tip`. -/
  | left : AdjunctionModality AdjunctionMode.base AdjunctionMode.tip
  /-- The right modality `tip ⟶ base`. -/
  | right : AdjunctionModality AdjunctionMode.tip AdjunctionMode.base

/-- The adjunction-seed quiver: two modes, a modality each way. -/
def adjunctionGraph : ModeGraph where
  Mode := AdjunctionMode
  Modality := AdjunctionModality

/-- The composite 1-cell `base ⟶ tip ⟶ base` (left then right) — a non-trivial endo-path at `base`. -/
def adjunctionLeftThenRight : ModalityPath adjunctionGraph AdjunctionMode.base AdjunctionMode.base :=
  ModalityPath.cons AdjunctionModality.left
    (ModalityPath.cons AdjunctionModality.right
      (ModalityPath.nil (graph := adjunctionGraph) AdjunctionMode.base))

/-- The composite 1-cell `tip ⟶ base ⟶ tip` (right then left) — a non-trivial endo-path at `tip`. -/
def adjunctionRightThenLeft : ModalityPath adjunctionGraph AdjunctionMode.tip AdjunctionMode.tip :=
  ModalityPath.cons AdjunctionModality.right
    (ModalityPath.cons AdjunctionModality.left
      (ModalityPath.nil (graph := adjunctionGraph) AdjunctionMode.tip))

/-- The generating 2-cells of the adjunction seed — the unit and counit, between non-trivial parallel paths.
These are the GENERATORS only; the triangle laws relating them are deferred (`mode-3` / `mode-4`). -/
inductive AdjunctionTwoCell :
    {sourceMode targetMode : AdjunctionMode} →
    ModalityPath adjunctionGraph sourceMode targetMode →
    ModalityPath adjunctionGraph sourceMode targetMode → Type where
  /-- The unit `id_base ⟹ (left then right)`. -/
  | unit : AdjunctionTwoCell (ModalityPath.nil (graph := adjunctionGraph) AdjunctionMode.base)
      adjunctionLeftThenRight
  /-- The counit `(right then left) ⟹ id_tip`. -/
  | counit : AdjunctionTwoCell adjunctionRightThenLeft
      (ModalityPath.nil (graph := adjunctionGraph) AdjunctionMode.tip)

/-- ★ The **adjunction / cohesion mode signature** — the canonical NON-DEGENERATE witness: two distinct modes,
a modality each way, and unit/counit 2-cell generators between non-trivial parallel paths.  It exercises every
dimension of the data model (modes, typed modalities, composite paths, 2-cells between distinct parallel
paths). -/
def adjunctionModeSignature : ModeSignature where
  graph := adjunctionGraph
  twoCell := fun firstPath secondPath => AdjunctionTwoCell firstPath secondPath

/-- ★ The FX mode-axis datum at the design-lock stage carries the non-degenerate adjunction seed (NOT the
trivial signature). -/
def fxModeAxis : ModeAxisData where
  signature := adjunctionModeSignature

/-! ## Non-degeneracy witnesses -/

/-- The adjunction seed has two genuinely distinct modes (the data model is not single-sorted). -/
theorem adjunctionHasTwoDistinctModes : AdjunctionMode.base ≠ AdjunctionMode.tip :=
  fun modesEqual => AdjunctionMode.noConfusion modesEqual

/-- The adjunction seed has a modality with genuinely distinct source and target (a directed 1-cell). -/
def adjunctionHasDirectedModality : AdjunctionModality AdjunctionMode.base AdjunctionMode.tip :=
  AdjunctionModality.left

/-- The unit 2-cell goes between genuinely distinct parallel paths — its source is the identity path and its
target is a length-2 composite, so the 2-cell layer is non-trivial (not merely endo-2-cells on identities). -/
theorem adjunctionUnitBoundariesDistinct :
    ModalityPath.nil (graph := adjunctionGraph) AdjunctionMode.base ≠ adjunctionLeftThenRight := by
  intro boundariesEqual
  exact absurd (congrArg ModalityPath.length boundariesEqual) (by decide)

/-- The FX mode-axis datum is the non-degenerate witness, pinned definitionally. -/
theorem fxModeAxis_signature_isAdjunction : fxModeAxis.signature = adjunctionModeSignature :=
  rfl

/-! ## Honesty markers -/

/-- **Honesty marker.**  The FREE STRICT 2-CATEGORY generated by the signature (path-category laws + free
2-cells with vertical/horizontal composition + interchange) and the semantic `FXModeTheory` round-trip are
`mode-1`, deferred.  `= false`. -/
def fxMode_hasStrictTwoCategoryCore : Bool := false

/-- **Honesty marker.**  DECIDABLE 2-CELL EQUALITY via a convergent 3-polygraph (Gratzer's coherence hurdle)
is `mode-3`, deferred.  `= false`. -/
def fxMode_hasDecidableTwoCellEquality : Bool := false

/-- **Honesty marker.**  The higher (dimension > 2) generators + the Gray / semistrict / WEAK ω-category
structure (the data model here is the 2-truncation) are `mode-5` / `mode-6` / `mode-21`, deferred.  `= false`. -/
def fxMode_hasWeakOmegaStructure : Bool := false

/-- **ESTABLISHED (fib-3).**  The kernel is FIBRED over the (affine) mode theory — the MTT "everything ⊣ mode",
realized at `Core/Fib/ModeFibration` (`affineModeFibrationRealized`): the dimension lock pinned to the mode-12
unpointable multiplier, the modal index faithfully a `ModalityPath`, the discipline derived from unpointedness,
and modality (1-cell) equality decidable.  `= true`.  (The cross-axis assembly lives at `Core/Fib`; this Tier0
marker reflects that landing.  The GENERAL multi-mode `fxMode_hasDecidableTwoCellEquality` stays `false`.) -/
def fxMode_hasModeFibration : Bool := true

end FX1Poly.Tier0
