import FX1Poly.Polygraph.Homology.CrossedModuleIdentityInvariant
import FX1Poly.ComputerAlgebra.Number.IntCancellation

/-! # FX1Poly/Polygraph/Homology/CrossedModuleRelationModule — the relation-module characterization of
    the free crossed module of `⟨s | s³⟩`: the kernel landing `ker(N) = {aug = 0}`, the exponent-sum
    bridge `∂x = [] ⟹ aug(image x) = 0`, the realization family surjecting onto `ker N`, and the honest
    surjection / injectivity-wall adjudication (WP-2GROUP r3, #2199)

r2 (`Homology/CrossedModuleIdentityInvariant`) shipped the separating `ZZ[ZZ/3] ≅ ZZ³` invariant
`crossedModuleImage : E → ZZ[ZZ/3]`, its Peiffer-invariance, and the element-level `π₂ ≠ 0`
(`ζ ↦ (−1, 1, 0) ≠ 0`).  This module characterizes the IMAGE lattice: the norm element `N = 1 + s + s²`
has kernel `ker(N) = {(a, b, c) : a + b + c = 0}`, exactly the augmentation-zero ideal generated by
`s − 1`; every identity (element of `ker ∂`) lands there; and the invariant surjects onto it.

## B1 — the kernel landing (this file's first brick)

Two independent halves:

  * **The finite `ZZ³` half** — `groupRingNormElement v = v + s·v + s²·v` (the multiplication-by-`N`
    map) has `groupRingNormElement v = 0 ↔ groupRingAugmentation v = 0` (`normKernelIffAugmentationZero`),
    naming the target lattice `ker(N) = {a + b + c = 0}`.  Pure `Int` arithmetic through the propext-clean
    kit; a full-enum `Iff`.
  * **The exponent-sum bridge** — the `Int` exponent-sum `exponentSum : F(s) → ZZ` is a free-reduction-
    blind `++`-homomorphism, so `exponentSum(∂x) = groupRingAugmentation(crossedModuleImage x) · 3`
    for well-formed identities (all generators `relationIndex = 0`,
    `AllRelatorIndexZero`).  From `∂x = []` the left side is `0`, and `3 · aug = 0` forces `aug = 0`
    (`intEqZeroOfMulOfNatSuccEqZero`).  This is `identityLandsAugmentationZero`.

★ **The `relationIndex = 0` guard is load-bearing (not cosmetic).**  `conjugatedRelatorImage` ignores
`relationIndex` and `relatorWord (n+1) = []`, so `⟨[], 1, true⟩` is an identity by the `∂ = []` test yet
images to `(1, 0, 0)` with augmentation `1 ≠ 0`.  Without the `AllRelatorIndexZero` guard the kernel-
landing theorem is FALSE; every deliverable that concludes `aug = 0` carries it.

## Zero-axiom design decisions

  * All `Int` arithmetic through the shipped propext-clean kit (`intAddComm`/`intAddAssoc`/
    `intAddRightNeg`/`intAddLeftNeg`/`intZeroAdd`/`intAddZero`/`intNegAdd`/`intNegNeg`/`intRightDistrib`/
    `intMulOne`/`intMulZero`/`intZeroMul`/`intMulNeg`/`intNegMul`), never Init's propext-dirty forms.
  * The divisibility close is the shipped `intEqZeroOfMulOfNatSuccEqZero` (`3 = Int.ofNat (1 + 2)`).
  * Every match on `SignedLetter` / `Bool` / `ConjugatedRelator` is FULLY enumerated — no `_ =>` wildcard.
  * Group-ring inequality (never used here for `=`) would go through `congrArg` on a single projection,
    never `mk.injEq`.
  * The exponent bridge recurses structurally on the `AllRelatorIndexZero` proof, mirroring r2's
    `crossedModuleImageRespectsPeiffer`; the magnitude realizer recurses structurally on the `Nat`
    payload after an `Int`-constructor match, never `WellFounded.fix`.

`Init`-only (over `Homology/CrossedModuleIdentityInvariant` and `ComputerAlgebra.Number.IntCancellation`),
structural, zero axioms.  No `axiom`, `sorry`, `propext`, `Quot.sound`, `Classical`, `native_decide`, or
`omega`.  Per-declaration gated in `FX1PolyAudit/Polygraph/Homology/CrossedModuleRelationModule.lean`. -/

namespace FX1Poly.Polygraph.Homology

open FX1Poly.ComputerAlgebra

/-! ## B1a — the augmentation, the `s`-action, and the norm element `N = 1 + s + s²` -/

/-- **The augmentation `ε : ZZ[ZZ/3] → ZZ`** — the coefficient sum `a + b + c`.  Under `ZZ[G] ≅ ZZ³`
this is the ring map sending every group element to `1`; its kernel is the augmentation ideal. -/
def groupRingAugmentation (value : GroupRingZmod3) : Int :=
  value.coeffOne + value.coeffT + value.coeffTsq

/-- **The `s`-action on `ZZ[ZZ/3]`** — multiplication by `t` rotates the basis `e₀ ↦ e₁ ↦ e₂ ↦ e₀`, i.e.
`(a, b, c) ↦ (c, a, b)`. -/
def groupRingSAction (value : GroupRingZmod3) : GroupRingZmod3 :=
  ⟨value.coeffTsq, value.coeffOne, value.coeffT⟩

/-- **The norm element action `v ↦ N·v = v + s·v + s²·v`** — multiplication by `N = 1 + s + s²`.  On
`(a, b, c)` it returns `(σ, σ, σ)` with `σ = a + b + c`, so its image is the diagonal and its kernel is
the augmentation-zero ideal. -/
def groupRingNormElement (value : GroupRingZmod3) : GroupRingZmod3 :=
  groupRingAdd value (groupRingAdd (groupRingSAction value) (groupRingSAction (groupRingSAction value)))

/-- The four-summand interchange `(a + b) + (c + d) = (a + c) + (b + d)` — the abelian regrouping the
augmentation-additivity needs.  Built from `intAddAssoc`/`intAddComm` only. -/
theorem intAddAddComm (first second third fourth : Int) :
    (first + second) + (third + fourth) = (first + third) + (second + fourth) :=
  (intAddAssoc first second (third + fourth)).trans
    ((congrArg (fun summand => first + summand)
        (((intAddAssoc second third fourth).symm).trans
          ((congrArg (fun summand => summand + fourth) (intAddComm second third)).trans
            (intAddAssoc third second fourth)))).trans
      (intAddAssoc first third (second + fourth)).symm)

/-- The augmentation negates through group-ring negation: `ε(−v) = −ε(v)`. -/
theorem groupRingAugmentationNeg (value : GroupRingZmod3) :
    groupRingAugmentation (groupRingNeg value) = -(groupRingAugmentation value) :=
  ((intNegAdd (value.coeffOne + value.coeffT) value.coeffTsq).trans
      (congrArg (fun summand => summand + -value.coeffTsq)
        (intNegAdd value.coeffOne value.coeffT))).symm

/-- ★ **The augmentation is additive**: `ε(v + w) = ε(v) + ε(w)` — two four-summand interchanges. -/
theorem groupRingAugmentationAdd (left right : GroupRingZmod3) :
    groupRingAugmentation (groupRingAdd left right)
      = groupRingAugmentation left + groupRingAugmentation right :=
  (congrArg (fun summand => summand + (left.coeffTsq + right.coeffTsq))
      (intAddAddComm left.coeffOne right.coeffOne left.coeffT right.coeffT)).trans
    (intAddAddComm (left.coeffOne + left.coeffT) (right.coeffOne + right.coeffT)
      left.coeffTsq right.coeffTsq)

/-- Each basis vector has augmentation `1` (it is a single `±1` coefficient). -/
theorem groupRingAugmentationOfPowerOfT : ∀ residue : ZmodThree,
    groupRingAugmentation (powerOfT residue) = 1
  | .residue0 => rfl
  | .residue1 => rfl
  | .residue2 => rfl

/-! ### B1a probes — evaluate the finite ops on literals FIRST -/

/-- Probe — the norm element of `e₀` is the diagonal `(1, 1, 1)` (= `N·1`). -/
theorem groupRingNormElementProbe :
    groupRingNormElement (GroupRingZmod3.mk 1 0 0) = GroupRingZmod3.mk 1 1 1 := rfl

/-- Probe — the augmentation of that diagonal is `3` (= `ε(N)`). -/
theorem groupRingAugmentationDiagonalProbe :
    groupRingAugmentation (GroupRingZmod3.mk 1 1 1) = 3 := rfl

/-- Probe — the `s`-action rotates `e₀ ↦ e₁`: `(1, 0, 0) ↦ (0, 1, 0)`. -/
theorem groupRingSActionProbe :
    groupRingSAction (GroupRingZmod3.mk 1 0 0) = GroupRingZmod3.mk 0 1 0 := rfl

/-! ## B1b — the target lattice `ker(N) = {a + b + c = 0}` -/

/-- ★★ **The kernel of the norm equals the augmentation ideal**: `N·v = 0 ↔ ε(v) = 0`.  Forward projects
the `coeffOne` slot (`a + (c + b) = 0`) and reassociates to `(a + b) + c = 0`; backward rebuilds all three
diagonal coordinates from `(a + b) + c = 0`.  This NAMES the target lattice `ker(N)` the invariant
surjects onto — the `ZZ[G]`-ideal generated by `s − 1`. -/
theorem normKernelIffAugmentationZero (value : GroupRingZmod3) :
    groupRingNormElement value = groupRingZero ↔ groupRingAugmentation value = 0 :=
  Iff.intro
    (fun normIsZero =>
      let coeffOneZero :
          value.coeffOne + (value.coeffTsq + value.coeffT) = 0 :=
        congrArg GroupRingZmod3.coeffOne normIsZero
      (intAddAssoc value.coeffOne value.coeffT value.coeffTsq).trans
        ((congrArg (fun summand => value.coeffOne + summand)
            (intAddComm value.coeffT value.coeffTsq)).trans coeffOneZero))
    (fun augZero =>
      groupRingEq
        ((congrArg (fun summand => value.coeffOne + summand)
            (intAddComm value.coeffTsq value.coeffT)).trans
          ((intAddAssoc value.coeffOne value.coeffT value.coeffTsq).symm.trans augZero))
        ((intAddAssoc value.coeffT value.coeffOne value.coeffTsq).symm.trans
          ((congrArg (fun summand => summand + value.coeffTsq)
              (intAddComm value.coeffT value.coeffOne)).trans augZero))
        ((intAddComm value.coeffTsq (value.coeffT + value.coeffOne)).trans
          ((congrArg (fun summand => summand + value.coeffTsq)
              (intAddComm value.coeffT value.coeffOne)).trans augZero)))

/-! ## B1c — the exponent-sum bridge `exponentSum(∂x) = ε(image x) · 3`

`exponentSum : F(s) → ZZ` (r1 `Homology/CrossedModuleCyclicThree`) is the trivial-coefficient shadow.
It is a free-reduction-blind `++`-homomorphism, so it survives `reduceWord` and factors through append.
Under the `relationIndex = 0` well-formedness guard each `∂gen` has `exponentSum = ±3 = 3·(sign)`, and the
image's augmentation is exactly the same `sign`; so the whole boundary's exponent sum is `3·ε(image x)`. -/

/-- The `Int` exponent of a single signed letter — `pos ↦ +1`, `neg ↦ −1`.  The per-letter increment
`exponentSum` folds. -/
def letterExp : SignedLetter → Int
  | .pos _ => 1
  | .neg _ => -1

/-- `exponentSum` peels one letter as `letterExp` — the cons law, full enum on the sign. -/
theorem exponentSumCons : ∀ (letter : SignedLetter) (rest : List SignedLetter),
    exponentSum (letter :: rest) = letterExp letter + exponentSum rest
  | .pos _, _ => rfl
  | .neg _, _ => rfl

/-- ★ **`exponentSum` is a `++`-homomorphism** — the append law by induction on the left word. -/
theorem exponentSumAppend : ∀ (leftWord rightWord : List SignedLetter),
    exponentSum (leftWord ++ rightWord) = exponentSum leftWord + exponentSum rightWord
  | [], rightWord => (intZeroAdd (exponentSum rightWord)).symm
  | letter :: rest, rightWord =>
      (exponentSumCons letter (rest ++ rightWord)).trans
        ((congrArg (fun summand => letterExp letter + summand) (exponentSumAppend rest rightWord)).trans
          ((intAddAssoc (letterExp letter) (exponentSum rest) (exponentSum rightWord)).symm.trans
            (congrArg (fun summand => summand + exponentSum rightWord)
              (exponentSumCons letter rest).symm)))

/-- Two mutually-inverse letters have opposite exponents summing to `0` — the residue of a cancelling
pair.  Full enum on the four sign combinations (`Bool.noConfusion` kills the same-sign impossibilities). -/
theorem letterExpInverseSumZero : ∀ (letter top : SignedLetter),
    areInverse letter top = true → letterExp letter + letterExp top = 0
  | .pos _, .neg _, _ => intAddRightNeg 1
  | .neg _, .pos _, _ => intAddLeftNeg 1
  | .pos _, .pos _, cancels => Bool.noConfusion cancels
  | .neg _, .neg _, cancels => Bool.noConfusion cancels

/-- The letter inverse negates the exponent: `letterExp (letter⁻¹) = −(letterExp letter)`. -/
theorem letterExpInverse : ∀ letter : SignedLetter,
    letterExp (inverseLetter letter) = -(letterExp letter)
  | .pos _ => rfl
  | .neg _ => (intNegNeg 1).symm

/-- `List.map inverseLetter` negates the exponent sum (each letter flips). -/
theorem exponentSumMapInverse : ∀ word : List SignedLetter,
    exponentSum (List.map inverseLetter word) = -(exponentSum word)
  | [] => rfl
  | letter :: rest =>
      (exponentSumCons (inverseLetter letter) (List.map inverseLetter rest)).trans
        ((congrArg (fun summand => summand + exponentSum (List.map inverseLetter rest))
            (letterExpInverse letter)).trans
          ((congrArg (fun summand => -(letterExp letter) + summand) (exponentSumMapInverse rest)).trans
            ((intNegAdd (letterExp letter) (exponentSum rest)).symm.trans
              (congrArg (fun summand => -summand) (exponentSumCons letter rest).symm))))

/-- Reversal preserves the exponent sum — accumulator-general form (`ZZ` is abelian). -/
theorem exponentSumReverseAux : ∀ (word accumulator : List SignedLetter),
    exponentSum (List.reverseAux word accumulator)
      = exponentSum accumulator + exponentSum word
  | [], accumulator => (intAddZero (exponentSum accumulator)).symm
  | frontLetter :: remaining, accumulator =>
      (exponentSumReverseAux remaining (frontLetter :: accumulator)).trans
        ((congrArg (fun summand => summand + exponentSum remaining)
            (exponentSumCons frontLetter accumulator)).trans
          (((congrArg (fun summand => summand + exponentSum remaining)
                (intAddComm (letterExp frontLetter) (exponentSum accumulator))).trans
              (intAddAssoc (exponentSum accumulator) (letterExp frontLetter)
                (exponentSum remaining))).trans
            (congrArg (fun summand => exponentSum accumulator + summand)
              (exponentSumCons frontLetter remaining).symm)))

/-- Reversal preserves the exponent sum. -/
theorem exponentSumReverse (word : List SignedLetter) :
    exponentSum (List.reverse word) = exponentSum word :=
  (exponentSumReverseAux word []).trans (intZeroAdd (exponentSum word))

/-- ★ **`invWord` negates the exponent sum**: `exponentSum (w⁻¹) = −(exponentSum w)`. -/
theorem exponentSumInvWord (word : List SignedLetter) :
    exponentSum (invWord word) = -(exponentSum word) :=
  (exponentSumReverse (List.map inverseLetter word)).trans (exponentSumMapInverse word)

/-- ★ **`consReduced` preserves the exponent sum** — the free-cancellation guard drops both letters
(their exponents summing to `0`) or extends (adds the letter's exponent).  Mirror of r2's
`consReducedResidue` into `Int`. -/
theorem exponentSumConsReduced : ∀ (letter : SignedLetter) (word : List SignedLetter),
    exponentSum (consReduced letter word) = letterExp letter + exponentSum word
  | letter, [] => exponentSumCons letter []
  | letter, top :: rest =>
      match hCancel : areInverse letter top with
      | true =>
          (congrArg exponentSum (consReducedCancel letter top rest hCancel)).trans
            (((congrArg (fun summand => letterExp letter + summand) (exponentSumCons top rest)).trans
                (((intAddAssoc (letterExp letter) (letterExp top) (exponentSum rest)).symm).trans
                  ((congrArg (fun summand => summand + exponentSum rest)
                      (letterExpInverseSumZero letter top hCancel)).trans
                    (intZeroAdd (exponentSum rest))))).symm)
      | false =>
          (congrArg exponentSum (consReducedExtend letter top rest hCancel)).trans
            (exponentSumCons letter (top :: rest))

/-- ★★ **`reduceWord` preserves the exponent sum** — free reduction is exponent-blind.  Structural
induction folding `exponentSumConsReduced`. -/
theorem exponentSumReduceInvariant : ∀ word : List SignedLetter,
    exponentSum (reduceWord word) = exponentSum word
  | [] => rfl
  | letter :: rest =>
      (exponentSumConsReduced letter (reduceWord rest)).trans
        ((congrArg (fun summand => letterExp letter + summand)
            (exponentSumReduceInvariant rest)).trans (exponentSumCons letter rest).symm)

/-- The outer cancellation `(outer + inner) + (−outer) = inner` — the conjugator's exponent cancels. -/
theorem intCancelOuter (outer inner : Int) : (outer + inner) + -outer = inner :=
  (congrArg (fun summand => summand + -outer) (intAddComm outer inner)).trans
    ((intAddAssoc inner outer (-outer)).trans
      ((congrArg (fun summand => inner + summand) (intAddRightNeg outer)).trans (intAddZero inner)))

/-- A conjugated body's exponent sum is the body's own: `exponentSum (w · body · w⁻¹) = exponentSum body`
(the flanking `w`/`w⁻¹` exponents cancel).  Mirror of r2's `conjugationResidueZero`, but returning the
body's exponent rather than `0`. -/
theorem exponentSumConjugation (conjugatorWord relatorBody : List SignedLetter) :
    exponentSum (reduceWord (conjugatorWord ++ relatorBody ++ invWord conjugatorWord))
      = exponentSum relatorBody :=
  (exponentSumReduceInvariant (conjugatorWord ++ relatorBody ++ invWord conjugatorWord)).trans
    ((exponentSumAppend (conjugatorWord ++ relatorBody) (invWord conjugatorWord)).trans
      ((congrArg (fun summand => summand + exponentSum (invWord conjugatorWord))
          (exponentSumAppend conjugatorWord relatorBody)).trans
        ((congrArg
            (fun summand => (exponentSum conjugatorWord + exponentSum relatorBody) + summand)
            (exponentSumInvWord conjugatorWord)).trans
          (intCancelOuter (exponentSum conjugatorWord) (exponentSum relatorBody)))))

/-- The `Int` sign of a `Bool` — `true ↦ +1`, `false ↦ −1`.  The augmentation of `±eₖ`. -/
def signInt : Bool → Int
  | true => 1
  | false => -1

/-- ★ **A well-formed conjugated relator's boundary has exponent sum `sign · 3`** — under
`relationIndex = 0` the relator is `s³` (exponent `3`); the sign case sends `∂` to `s³`/`s⁻³` with
exponent `+3`/`−3`.  `exponentSumConjugation` cancels the conjugator; the relator's exponent is `±3`. -/
theorem conjugatedRelatorBoundaryExponentIndexZero : ∀ (gen : ConjugatedRelator),
    gen.relationIndex = 0 →
    exponentSum (conjugatedRelatorBoundary gen) = signInt gen.isPositive * 3
  | ⟨conjugatorWord, relatorIndex, true⟩, indexIsZero =>
      (exponentSumConjugation conjugatorWord (relatorWord relatorIndex)).trans
        ((congrArg (fun index => exponentSum (relatorWord index)) indexIsZero).trans rfl)
  | ⟨conjugatorWord, relatorIndex, false⟩, indexIsZero =>
      (exponentSumConjugation conjugatorWord (invWord (relatorWord relatorIndex))).trans
        ((exponentSumInvWord (relatorWord relatorIndex)).trans
          ((congrArg (fun index => -(exponentSum (relatorWord index))) indexIsZero).trans rfl))

/-- The image augmentation of a single conjugated relator is its sign: `ε(image (w, r, sign)) = sign`
(the image is `±eₖ`, augmentation `±1`).  Full enum on the sign. -/
theorem augmentationOfConjugatedRelatorImage : ∀ gen : ConjugatedRelator,
    groupRingAugmentation (conjugatedRelatorImage gen) = signInt gen.isPositive
  | ⟨conjugatorWord, _, true⟩ => groupRingAugmentationOfPowerOfT (wordResidue conjugatorWord)
  | ⟨conjugatorWord, _, false⟩ =>
      (groupRingAugmentationNeg (powerOfT (wordResidue conjugatorWord))).trans
        (congrArg (fun summand => -summand)
          (groupRingAugmentationOfPowerOfT (wordResidue conjugatorWord)))

/-- The well-formedness guard: every generator conjugates the ONLY genuine relator (`relationIndex = 0`).
Without it a phantom `⟨[], n+1, true⟩` (empty relator, `∂ = []`) images to `(1, 0, 0)` with augmentation
`1` — refuting the kernel landing.  A `Prop`-inductive, structurally recursed by the bridge. -/
inductive AllRelatorIndexZero : PreCrossedElement → Prop where
  /-- The empty element is well-formed. -/
  | nil : AllRelatorIndexZero []
  /-- A cons is well-formed when its head conjugates relator `0` and its tail is well-formed. -/
  | cons (gen : ConjugatedRelator) (rest : PreCrossedElement)
      (indexIsZero : gen.relationIndex = 0) (restAllZero : AllRelatorIndexZero rest) :
      AllRelatorIndexZero (gen :: rest)

/-- ★★★ **THE EXPONENT-SUM BRIDGE** — for a well-formed element, `exponentSum(∂x) = ε(image x) · 3`.
Structural recursion on the `AllRelatorIndexZero` proof (mirroring r2's
`crossedModuleImageRespectsPeiffer`): the empty element is `0 = 0 · 3`; the cons folds
`exponentSumReduceInvariant`, `exponentSumAppend`, the per-generator `sign · 3`
(`conjugatedRelatorBoundaryExponentIndexZero`), the tail bridge, and `intRightDistrib` against the
augmentation split (`groupRingAugmentationAdd` + `augmentationOfConjugatedRelatorImage`). -/
theorem exponentSumBoundaryIsThreeAugmentation :
    ∀ {element : PreCrossedElement}, AllRelatorIndexZero element →
      exponentSum (partialBoundary element)
        = groupRingAugmentation (crossedModuleImage element) * 3
  | _, .nil => rfl
  | _, .cons gen rest indexIsZero restAllZero =>
      let stepBoundary :
          exponentSum (conjugatedRelatorBoundary gen) = signInt gen.isPositive * 3 :=
        conjugatedRelatorBoundaryExponentIndexZero gen indexIsZero
      let tailBridge :
          exponentSum (partialBoundary rest)
            = groupRingAugmentation (crossedModuleImage rest) * 3 :=
        exponentSumBoundaryIsThreeAugmentation restAllZero
      let augSplit :
          groupRingAugmentation (crossedModuleImage (gen :: rest))
            = signInt gen.isPositive + groupRingAugmentation (crossedModuleImage rest) :=
        (groupRingAugmentationAdd (conjugatedRelatorImage gen) (crossedModuleImage rest)).trans
          (congrArg (fun summand => summand + groupRingAugmentation (crossedModuleImage rest))
            (augmentationOfConjugatedRelatorImage gen))
      (exponentSumReduceInvariant (conjugatedRelatorBoundary gen ++ partialBoundary rest)).trans
        ((exponentSumAppend (conjugatedRelatorBoundary gen) (partialBoundary rest)).trans
          (((congrArg (fun summand => summand + exponentSum (partialBoundary rest)) stepBoundary).trans
              (congrArg (fun summand => signInt gen.isPositive * 3 + summand) tailBridge)).trans
            (((intRightDistrib (signInt gen.isPositive)
                  (groupRingAugmentation (crossedModuleImage rest)) 3).symm).trans
              (congrArg (fun summand => summand * 3) augSplit.symm))))

/-- ★★★ **THE KERNEL LANDING** — a well-formed identity (`AllRelatorIndexZero` + `∂x = []`) has
`ε(image x) = 0`, i.e. `image x ∈ ker(N)`.  The bridge gives `ε(image x) · 3 = exponentSum [] = 0`, and
`3` is a positive-successor factor, so `intEqZeroOfMulOfNatSuccEqZero` cancels it. -/
theorem identityLandsAugmentationZero {element : PreCrossedElement}
    (indexGuard : AllRelatorIndexZero element)
    (isIdentity : partialBoundary element = oneWord) :
    groupRingAugmentation (crossedModuleImage element) = 0 :=
  let augTimesThreeZero :
      groupRingAugmentation (crossedModuleImage element) * 3 = 0 :=
    (exponentSumBoundaryIsThreeAugmentation indexGuard).symm.trans
      (congrArg exponentSum isIdentity)
  intEqZeroOfMulOfNatSuccEqZero (groupRingAugmentation (crossedModuleImage element)) 2
    augTimesThreeZero

/-! ### B1c probes — the r2 `ζ` and a fresh doubly-conjugated identity land in `ker(N)` -/

/-- ★ Probe — the r2 rotation identity `ζ` has augmentation `0` (its image `(−1, 1, 0)` sums to `0`), so
`image ζ ∈ ker(N)`: the FIRST identity witnessed inside the target lattice. -/
theorem rotationIdentityAugmentationIsZero :
    groupRingAugmentation (crossedModuleImage rotationIdentityWitness) = 0 := rfl

/-- ★ Probe — a FRESH doubly-conjugated cancelling pair `[(s², ρ), (s², ρ)⁻¹]` (untouched by r1/r2):
`∂ = s³·s⁻³ = []` is an identity, and its image `e₂ + (−e₂) = 0` has augmentation `0`.  A genuine
identity landing at the origin of `ker(N)`. -/
theorem doublyConjugatedIdentityBoundaryVanishes :
    partialBoundary [⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩,
        invGen ⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩] = oneWord := rfl

/-- Probe — that doubly-conjugated identity images to `0`, hence augmentation `0` (in `ker(N)`). -/
theorem doublyConjugatedIdentityAugmentationIsZero :
    groupRingAugmentation (crossedModuleImage [⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩,
        invGen ⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩]) = 0 := rfl

end FX1Poly.Polygraph.Homology
