import FX1Poly.Polygraph.Homology.CrossedModuleIdentityInvariant
import FX1Poly.ComputerAlgebra.Number.IntCancellation

/-! # FX1Poly/Polygraph/Homology/CrossedModuleRelationModule — the relation-module characterization of
    the free crossed module of `⟨s | s³⟩`: the kernel landing `ker(N) = {aug = 0}`, the exponent-sum
    bridge `∂x = [] ⟹ aug(image x) = 0`, the realization family surjecting onto `ker N`, and the honest
    surjection / injectivity-wall adjudication (WP-2GROUP r3, #2199)

r2 (`Homology/CrossedModuleIdentityInvariant`) shipped the separating `ZZ[ZZ/3] ≅ ZZ³` invariant
`crossedModuleImage : E → ZZ[ZZ/3]`, its Peiffer-invariance, and the element-level `π₂ ≠ 0`
(`ζ ↦ (−1, 1, 0) ≠ 0`).  This module characterizes the IMAGE lattice: the norm element `N = 1 + s + s²`
has kernel `ker(N) = {(a, b, c) : a + b + c = 0}`, exactly the augmentation-zero ideal generated by
`s − 1`; every identity (element of `ker ∂`) lands there; and the invariant surjects onto it.

## B1 — the kernel landing (this file's first brick)

Two independent halves:

  * **The finite `ZZ³` half** — `groupRingNormElement v = v + s·v + s²·v` (the multiplication-by-`N`
    map) has `groupRingNormElement v = 0 ↔ groupRingAugmentation v = 0` (`normKernelIffAugmentationZero`),
    naming the target lattice `ker(N) = {a + b + c = 0}`.  Pure `Int` arithmetic through the propext-clean
    kit; a full-enum `Iff`.
  * **The exponent-sum bridge** — the `Int` exponent-sum `exponentSum : F(s) → ZZ` is a free-reduction-
    blind `++`-homomorphism, so `exponentSum(∂x) = groupRingAugmentation(crossedModuleImage x) · 3`
    for well-formed identities (all generators `relationIndex = 0`,
    `AllRelatorIndexZero`).  From `∂x = []` the left side is `0`, and `3 · aug = 0` forces `aug = 0`
    (`intEqZeroOfMulOfNatSuccEqZero`).  This is `identityLandsAugmentationZero`.

★ **The `relationIndex = 0` guard is load-bearing (not cosmetic).**  `conjugatedRelatorImage` ignores
`relationIndex` and `relatorWord (n+1) = []`, so `⟨[], 1, true⟩` is an identity by the `∂ = []` test yet
images to `(1, 0, 0)` with augmentation `1 ≠ 0`.  Without the `AllRelatorIndexZero` guard the kernel-
landing theorem is FALSE; every deliverable that concludes `aug = 0` carries it.

## Zero-axiom design decisions

  * All `Int` arithmetic through the shipped propext-clean kit (`intAddComm`/`intAddAssoc`/
    `intAddRightNeg`/`intAddLeftNeg`/`intZeroAdd`/`intAddZero`/`intNegAdd`/`intNegNeg`/`intRightDistrib`/
    `intMulOne`/`intMulZero`/`intZeroMul`/`intMulNeg`/`intNegMul`), never Init's propext-dirty forms.
  * The divisibility close is the shipped `intEqZeroOfMulOfNatSuccEqZero` (`3 = Int.ofNat (1 + 2)`).
  * Every match on `SignedLetter` / `Bool` / `ConjugatedRelator` is FULLY enumerated — no `_ =>` wildcard.
  * Group-ring inequality (never used here for `=`) would go through `congrArg` on a single projection,
    never `mk.injEq`.
  * The exponent bridge recurses structurally on the `AllRelatorIndexZero` proof, mirroring r2's
    `crossedModuleImageRespectsPeiffer`; the magnitude realizer recurses structurally on the `Nat`
    payload after an `Int`-constructor match, never `WellFounded.fix`.

`Init`-only (over `Homology/CrossedModuleIdentityInvariant` and `ComputerAlgebra.Number.IntCancellation`),
structural, zero axioms.  No `axiom`, `sorry`, `propext`, `Quot.sound`, `Classical`, `native_decide`, or
`omega`.  Per-declaration gated in `FX1PolyAudit/Polygraph/Homology/CrossedModuleRelationModule.lean`. -/

namespace FX1Poly.Polygraph.Homology

open FX1Poly.ComputerAlgebra

/-! ## B1a — the augmentation, the `s`-action, and the norm element `N = 1 + s + s²` -/

/-- **The augmentation `ε : ZZ[ZZ/3] → ZZ`** — the coefficient sum `a + b + c`.  Under `ZZ[G] ≅ ZZ³`
this is the ring map sending every group element to `1`; its kernel is the augmentation ideal. -/
def groupRingAugmentation (value : GroupRingZmod3) : Int :=
  value.coeffOne + value.coeffT + value.coeffTsq

/-- **The `s`-action on `ZZ[ZZ/3]`** — multiplication by `t` rotates the basis `e₀ ↦ e₁ ↦ e₂ ↦ e₀`, i.e.
`(a, b, c) ↦ (c, a, b)`. -/
def groupRingSAction (value : GroupRingZmod3) : GroupRingZmod3 :=
  ⟨value.coeffTsq, value.coeffOne, value.coeffT⟩

/-- **The norm element action `v ↦ N·v = v + s·v + s²·v`** — multiplication by `N = 1 + s + s²`.  On
`(a, b, c)` it returns `(σ, σ, σ)` with `σ = a + b + c`, so its image is the diagonal and its kernel is
the augmentation-zero ideal. -/
def groupRingNormElement (value : GroupRingZmod3) : GroupRingZmod3 :=
  groupRingAdd value (groupRingAdd (groupRingSAction value) (groupRingSAction (groupRingSAction value)))

/-- The four-summand interchange `(a + b) + (c + d) = (a + c) + (b + d)` — the abelian regrouping the
augmentation-additivity needs.  Built from `intAddAssoc`/`intAddComm` only. -/
theorem intAddAddComm (first second third fourth : Int) :
    (first + second) + (third + fourth) = (first + third) + (second + fourth) :=
  (intAddAssoc first second (third + fourth)).trans
    ((congrArg (fun summand => first + summand)
        (((intAddAssoc second third fourth).symm).trans
          ((congrArg (fun summand => summand + fourth) (intAddComm second third)).trans
            (intAddAssoc third second fourth)))).trans
      (intAddAssoc first third (second + fourth)).symm)

/-- The augmentation negates through group-ring negation: `ε(−v) = −ε(v)`. -/
theorem groupRingAugmentationNeg (value : GroupRingZmod3) :
    groupRingAugmentation (groupRingNeg value) = -(groupRingAugmentation value) :=
  ((intNegAdd (value.coeffOne + value.coeffT) value.coeffTsq).trans
      (congrArg (fun summand => summand + -value.coeffTsq)
        (intNegAdd value.coeffOne value.coeffT))).symm

/-- ★ **The augmentation is additive**: `ε(v + w) = ε(v) + ε(w)` — two four-summand interchanges. -/
theorem groupRingAugmentationAdd (left right : GroupRingZmod3) :
    groupRingAugmentation (groupRingAdd left right)
      = groupRingAugmentation left + groupRingAugmentation right :=
  (congrArg (fun summand => summand + (left.coeffTsq + right.coeffTsq))
      (intAddAddComm left.coeffOne right.coeffOne left.coeffT right.coeffT)).trans
    (intAddAddComm (left.coeffOne + left.coeffT) (right.coeffOne + right.coeffT)
      left.coeffTsq right.coeffTsq)

/-- Each basis vector has augmentation `1` (it is a single `±1` coefficient). -/
theorem groupRingAugmentationOfPowerOfT : ∀ residue : ZmodThree,
    groupRingAugmentation (powerOfT residue) = 1
  | .residue0 => rfl
  | .residue1 => rfl
  | .residue2 => rfl

/-! ### B1a probes — evaluate the finite ops on literals FIRST -/

/-- Probe — the norm element of `e₀` is the diagonal `(1, 1, 1)` (= `N·1`). -/
theorem groupRingNormElementProbe :
    groupRingNormElement (GroupRingZmod3.mk 1 0 0) = GroupRingZmod3.mk 1 1 1 := rfl

/-- Probe — the augmentation of that diagonal is `3` (= `ε(N)`). -/
theorem groupRingAugmentationDiagonalProbe :
    groupRingAugmentation (GroupRingZmod3.mk 1 1 1) = 3 := rfl

/-- Probe — the `s`-action rotates `e₀ ↦ e₁`: `(1, 0, 0) ↦ (0, 1, 0)`. -/
theorem groupRingSActionProbe :
    groupRingSAction (GroupRingZmod3.mk 1 0 0) = GroupRingZmod3.mk 0 1 0 := rfl

/-! ## B1b — the target lattice `ker(N) = {a + b + c = 0}` -/

/-- ★★ **The kernel of the norm equals the augmentation ideal**: `N·v = 0 ↔ ε(v) = 0`.  Forward projects
the `coeffOne` slot (`a + (c + b) = 0`) and reassociates to `(a + b) + c = 0`; backward rebuilds all three
diagonal coordinates from `(a + b) + c = 0`.  This NAMES the target lattice `ker(N)` the invariant
surjects onto — the `ZZ[G]`-ideal generated by `s − 1`. -/
theorem normKernelIffAugmentationZero (value : GroupRingZmod3) :
    groupRingNormElement value = groupRingZero ↔ groupRingAugmentation value = 0 :=
  Iff.intro
    (fun normIsZero =>
      let coeffOneZero :
          value.coeffOne + (value.coeffTsq + value.coeffT) = 0 :=
        congrArg GroupRingZmod3.coeffOne normIsZero
      (intAddAssoc value.coeffOne value.coeffT value.coeffTsq).trans
        ((congrArg (fun summand => value.coeffOne + summand)
            (intAddComm value.coeffT value.coeffTsq)).trans coeffOneZero))
    (fun augZero =>
      groupRingEq
        ((congrArg (fun summand => value.coeffOne + summand)
            (intAddComm value.coeffTsq value.coeffT)).trans
          ((intAddAssoc value.coeffOne value.coeffT value.coeffTsq).symm.trans augZero))
        ((intAddAssoc value.coeffT value.coeffOne value.coeffTsq).symm.trans
          ((congrArg (fun summand => summand + value.coeffTsq)
              (intAddComm value.coeffT value.coeffOne)).trans augZero))
        ((intAddComm value.coeffTsq (value.coeffT + value.coeffOne)).trans
          ((congrArg (fun summand => summand + value.coeffTsq)
              (intAddComm value.coeffT value.coeffOne)).trans augZero)))

/-! ## B1c — the exponent-sum bridge `exponentSum(∂x) = ε(image x) · 3`

`exponentSum : F(s) → ZZ` (r1 `Homology/CrossedModuleCyclicThree`) is the trivial-coefficient shadow.
It is a free-reduction-blind `++`-homomorphism, so it survives `reduceWord` and factors through append.
Under the `relationIndex = 0` well-formedness guard each `∂gen` has `exponentSum = ±3 = 3·(sign)`, and the
image's augmentation is exactly the same `sign`; so the whole boundary's exponent sum is `3·ε(image x)`. -/

/-- The `Int` exponent of a single signed letter — `pos ↦ +1`, `neg ↦ −1`.  The per-letter increment
`exponentSum` folds. -/
def letterExp : SignedLetter → Int
  | .pos _ => 1
  | .neg _ => -1

/-- `exponentSum` peels one letter as `letterExp` — the cons law, full enum on the sign. -/
theorem exponentSumCons : ∀ (letter : SignedLetter) (rest : List SignedLetter),
    exponentSum (letter :: rest) = letterExp letter + exponentSum rest
  | .pos _, _ => rfl
  | .neg _, _ => rfl

/-- ★ **`exponentSum` is a `++`-homomorphism** — the append law by induction on the left word. -/
theorem exponentSumAppend : ∀ (leftWord rightWord : List SignedLetter),
    exponentSum (leftWord ++ rightWord) = exponentSum leftWord + exponentSum rightWord
  | [], rightWord => (intZeroAdd (exponentSum rightWord)).symm
  | letter :: rest, rightWord =>
      (exponentSumCons letter (rest ++ rightWord)).trans
        ((congrArg (fun summand => letterExp letter + summand) (exponentSumAppend rest rightWord)).trans
          ((intAddAssoc (letterExp letter) (exponentSum rest) (exponentSum rightWord)).symm.trans
            (congrArg (fun summand => summand + exponentSum rightWord)
              (exponentSumCons letter rest).symm)))

/-- Two mutually-inverse letters have opposite exponents summing to `0` — the residue of a cancelling
pair.  Full enum on the four sign combinations (`Bool.noConfusion` kills the same-sign impossibilities). -/
theorem letterExpInverseSumZero : ∀ (letter top : SignedLetter),
    areInverse letter top = true → letterExp letter + letterExp top = 0
  | .pos _, .neg _, _ => intAddRightNeg 1
  | .neg _, .pos _, _ => intAddLeftNeg 1
  | .pos _, .pos _, cancels => Bool.noConfusion cancels
  | .neg _, .neg _, cancels => Bool.noConfusion cancels

/-- The letter inverse negates the exponent: `letterExp (letter⁻¹) = −(letterExp letter)`. -/
theorem letterExpInverse : ∀ letter : SignedLetter,
    letterExp (inverseLetter letter) = -(letterExp letter)
  | .pos _ => rfl
  | .neg _ => (intNegNeg 1).symm

/-- `List.map inverseLetter` negates the exponent sum (each letter flips). -/
theorem exponentSumMapInverse : ∀ word : List SignedLetter,
    exponentSum (List.map inverseLetter word) = -(exponentSum word)
  | [] => rfl
  | letter :: rest =>
      (exponentSumCons (inverseLetter letter) (List.map inverseLetter rest)).trans
        ((congrArg (fun summand => summand + exponentSum (List.map inverseLetter rest))
            (letterExpInverse letter)).trans
          ((congrArg (fun summand => -(letterExp letter) + summand) (exponentSumMapInverse rest)).trans
            ((intNegAdd (letterExp letter) (exponentSum rest)).symm.trans
              (congrArg (fun summand => -summand) (exponentSumCons letter rest).symm))))

/-- Reversal preserves the exponent sum — accumulator-general form (`ZZ` is abelian). -/
theorem exponentSumReverseAux : ∀ (word accumulator : List SignedLetter),
    exponentSum (List.reverseAux word accumulator)
      = exponentSum accumulator + exponentSum word
  | [], accumulator => (intAddZero (exponentSum accumulator)).symm
  | frontLetter :: remaining, accumulator =>
      (exponentSumReverseAux remaining (frontLetter :: accumulator)).trans
        ((congrArg (fun summand => summand + exponentSum remaining)
            (exponentSumCons frontLetter accumulator)).trans
          (((congrArg (fun summand => summand + exponentSum remaining)
                (intAddComm (letterExp frontLetter) (exponentSum accumulator))).trans
              (intAddAssoc (exponentSum accumulator) (letterExp frontLetter)
                (exponentSum remaining))).trans
            (congrArg (fun summand => exponentSum accumulator + summand)
              (exponentSumCons frontLetter remaining).symm)))

/-- Reversal preserves the exponent sum. -/
theorem exponentSumReverse (word : List SignedLetter) :
    exponentSum (List.reverse word) = exponentSum word :=
  (exponentSumReverseAux word []).trans (intZeroAdd (exponentSum word))

/-- ★ **`invWord` negates the exponent sum**: `exponentSum (w⁻¹) = −(exponentSum w)`. -/
theorem exponentSumInvWord (word : List SignedLetter) :
    exponentSum (invWord word) = -(exponentSum word) :=
  (exponentSumReverse (List.map inverseLetter word)).trans (exponentSumMapInverse word)

/-- ★ **`consReduced` preserves the exponent sum** — the free-cancellation guard drops both letters
(their exponents summing to `0`) or extends (adds the letter's exponent).  Mirror of r2's
`consReducedResidue` into `Int`. -/
theorem exponentSumConsReduced : ∀ (letter : SignedLetter) (word : List SignedLetter),
    exponentSum (consReduced letter word) = letterExp letter + exponentSum word
  | letter, [] => exponentSumCons letter []
  | letter, top :: rest =>
      match hCancel : areInverse letter top with
      | true =>
          (congrArg exponentSum (consReducedCancel letter top rest hCancel)).trans
            (((congrArg (fun summand => letterExp letter + summand) (exponentSumCons top rest)).trans
                (((intAddAssoc (letterExp letter) (letterExp top) (exponentSum rest)).symm).trans
                  ((congrArg (fun summand => summand + exponentSum rest)
                      (letterExpInverseSumZero letter top hCancel)).trans
                    (intZeroAdd (exponentSum rest))))).symm)
      | false =>
          (congrArg exponentSum (consReducedExtend letter top rest hCancel)).trans
            (exponentSumCons letter (top :: rest))

/-- ★★ **`reduceWord` preserves the exponent sum** — free reduction is exponent-blind.  Structural
induction folding `exponentSumConsReduced`. -/
theorem exponentSumReduceInvariant : ∀ word : List SignedLetter,
    exponentSum (reduceWord word) = exponentSum word
  | [] => rfl
  | letter :: rest =>
      (exponentSumConsReduced letter (reduceWord rest)).trans
        ((congrArg (fun summand => letterExp letter + summand)
            (exponentSumReduceInvariant rest)).trans (exponentSumCons letter rest).symm)

/-- The outer cancellation `(outer + inner) + (−outer) = inner` — the conjugator's exponent cancels. -/
theorem intCancelOuter (outer inner : Int) : (outer + inner) + -outer = inner :=
  (congrArg (fun summand => summand + -outer) (intAddComm outer inner)).trans
    ((intAddAssoc inner outer (-outer)).trans
      ((congrArg (fun summand => inner + summand) (intAddRightNeg outer)).trans (intAddZero inner)))

/-- A conjugated body's exponent sum is the body's own: `exponentSum (w · body · w⁻¹) = exponentSum body`
(the flanking `w`/`w⁻¹` exponents cancel).  Mirror of r2's `conjugationResidueZero`, but returning the
body's exponent rather than `0`. -/
theorem exponentSumConjugation (conjugatorWord relatorBody : List SignedLetter) :
    exponentSum (reduceWord (conjugatorWord ++ relatorBody ++ invWord conjugatorWord))
      = exponentSum relatorBody :=
  (exponentSumReduceInvariant (conjugatorWord ++ relatorBody ++ invWord conjugatorWord)).trans
    ((exponentSumAppend (conjugatorWord ++ relatorBody) (invWord conjugatorWord)).trans
      ((congrArg (fun summand => summand + exponentSum (invWord conjugatorWord))
          (exponentSumAppend conjugatorWord relatorBody)).trans
        ((congrArg
            (fun summand => (exponentSum conjugatorWord + exponentSum relatorBody) + summand)
            (exponentSumInvWord conjugatorWord)).trans
          (intCancelOuter (exponentSum conjugatorWord) (exponentSum relatorBody)))))

/-- The `Int` sign of a `Bool` — `true ↦ +1`, `false ↦ −1`.  The augmentation of `±eₖ`. -/
def signInt : Bool → Int
  | true => 1
  | false => -1

/-- ★ **A well-formed conjugated relator's boundary has exponent sum `sign · 3`** — under
`relationIndex = 0` the relator is `s³` (exponent `3`); the sign case sends `∂` to `s³`/`s⁻³` with
exponent `+3`/`−3`.  `exponentSumConjugation` cancels the conjugator; the relator's exponent is `±3`. -/
theorem conjugatedRelatorBoundaryExponentIndexZero : ∀ (gen : ConjugatedRelator),
    gen.relationIndex = 0 →
    exponentSum (conjugatedRelatorBoundary gen) = signInt gen.isPositive * 3
  | ⟨conjugatorWord, relatorIndex, true⟩, indexIsZero =>
      (exponentSumConjugation conjugatorWord (relatorWord relatorIndex)).trans
        ((congrArg (fun index => exponentSum (relatorWord index)) indexIsZero).trans rfl)
  | ⟨conjugatorWord, relatorIndex, false⟩, indexIsZero =>
      (exponentSumConjugation conjugatorWord (invWord (relatorWord relatorIndex))).trans
        ((exponentSumInvWord (relatorWord relatorIndex)).trans
          ((congrArg (fun index => -(exponentSum (relatorWord index))) indexIsZero).trans rfl))

/-- The image augmentation of a single conjugated relator is its sign: `ε(image (w, r, sign)) = sign`
(the image is `±eₖ`, augmentation `±1`).  Full enum on the sign. -/
theorem augmentationOfConjugatedRelatorImage : ∀ gen : ConjugatedRelator,
    groupRingAugmentation (conjugatedRelatorImage gen) = signInt gen.isPositive
  | ⟨conjugatorWord, _, true⟩ => groupRingAugmentationOfPowerOfT (wordResidue conjugatorWord)
  | ⟨conjugatorWord, _, false⟩ =>
      (groupRingAugmentationNeg (powerOfT (wordResidue conjugatorWord))).trans
        (congrArg (fun summand => -summand)
          (groupRingAugmentationOfPowerOfT (wordResidue conjugatorWord)))

/-- The well-formedness guard: every generator conjugates the ONLY genuine relator (`relationIndex = 0`).
Without it a phantom `⟨[], n+1, true⟩` (empty relator, `∂ = []`) images to `(1, 0, 0)` with augmentation
`1` — refuting the kernel landing.  A `Prop`-inductive, structurally recursed by the bridge. -/
inductive AllRelatorIndexZero : PreCrossedElement → Prop where
  /-- The empty element is well-formed. -/
  | nil : AllRelatorIndexZero []
  /-- A cons is well-formed when its head conjugates relator `0` and its tail is well-formed. -/
  | cons (gen : ConjugatedRelator) (rest : PreCrossedElement)
      (indexIsZero : gen.relationIndex = 0) (restAllZero : AllRelatorIndexZero rest) :
      AllRelatorIndexZero (gen :: rest)

/-- ★★★ **THE EXPONENT-SUM BRIDGE** — for a well-formed element, `exponentSum(∂x) = ε(image x) · 3`.
Structural recursion on the `AllRelatorIndexZero` proof (mirroring r2's
`crossedModuleImageRespectsPeiffer`): the empty element is `0 = 0 · 3`; the cons folds
`exponentSumReduceInvariant`, `exponentSumAppend`, the per-generator `sign · 3`
(`conjugatedRelatorBoundaryExponentIndexZero`), the tail bridge, and `intRightDistrib` against the
augmentation split (`groupRingAugmentationAdd` + `augmentationOfConjugatedRelatorImage`). -/
theorem exponentSumBoundaryIsThreeAugmentation :
    ∀ {element : PreCrossedElement}, AllRelatorIndexZero element →
      exponentSum (partialBoundary element)
        = groupRingAugmentation (crossedModuleImage element) * 3
  | _, .nil => rfl
  | _, .cons gen rest indexIsZero restAllZero =>
      let stepBoundary :
          exponentSum (conjugatedRelatorBoundary gen) = signInt gen.isPositive * 3 :=
        conjugatedRelatorBoundaryExponentIndexZero gen indexIsZero
      let tailBridge :
          exponentSum (partialBoundary rest)
            = groupRingAugmentation (crossedModuleImage rest) * 3 :=
        exponentSumBoundaryIsThreeAugmentation restAllZero
      let augSplit :
          groupRingAugmentation (crossedModuleImage (gen :: rest))
            = signInt gen.isPositive + groupRingAugmentation (crossedModuleImage rest) :=
        (groupRingAugmentationAdd (conjugatedRelatorImage gen) (crossedModuleImage rest)).trans
          (congrArg (fun summand => summand + groupRingAugmentation (crossedModuleImage rest))
            (augmentationOfConjugatedRelatorImage gen))
      (exponentSumReduceInvariant (conjugatedRelatorBoundary gen ++ partialBoundary rest)).trans
        ((exponentSumAppend (conjugatedRelatorBoundary gen) (partialBoundary rest)).trans
          (((congrArg (fun summand => summand + exponentSum (partialBoundary rest)) stepBoundary).trans
              (congrArg (fun summand => signInt gen.isPositive * 3 + summand) tailBridge)).trans
            (((intRightDistrib (signInt gen.isPositive)
                  (groupRingAugmentation (crossedModuleImage rest)) 3).symm).trans
              (congrArg (fun summand => summand * 3) augSplit.symm))))

/-- ★★★ **THE KERNEL LANDING** — a well-formed identity (`AllRelatorIndexZero` + `∂x = []`) has
`ε(image x) = 0`, i.e. `image x ∈ ker(N)`.  The bridge gives `ε(image x) · 3 = exponentSum [] = 0`, and
`3` is a positive-successor factor, so `intEqZeroOfMulOfNatSuccEqZero` cancels it. -/
theorem identityLandsAugmentationZero {element : PreCrossedElement}
    (indexGuard : AllRelatorIndexZero element)
    (isIdentity : partialBoundary element = oneWord) :
    groupRingAugmentation (crossedModuleImage element) = 0 :=
  let augTimesThreeZero :
      groupRingAugmentation (crossedModuleImage element) * 3 = 0 :=
    (exponentSumBoundaryIsThreeAugmentation indexGuard).symm.trans
      (congrArg exponentSum isIdentity)
  intEqZeroOfMulOfNatSuccEqZero (groupRingAugmentation (crossedModuleImage element)) 2
    augTimesThreeZero

/-! ### B1c probes — the r2 `ζ` and a fresh doubly-conjugated identity land in `ker(N)` -/

/-- ★ Probe — the r2 rotation identity `ζ` has augmentation `0` (its image `(−1, 1, 0)` sums to `0`), so
`image ζ ∈ ker(N)`: the FIRST identity witnessed inside the target lattice. -/
theorem rotationIdentityAugmentationIsZero :
    groupRingAugmentation (crossedModuleImage rotationIdentityWitness) = 0 := rfl

/-- ★ Probe — a FRESH doubly-conjugated cancelling pair `[(s², ρ), (s², ρ)⁻¹]` (untouched by r1/r2):
`∂ = s³·s⁻³ = []` is an identity, and its image `e₂ + (−e₂) = 0` has augmentation `0`.  A genuine
identity landing at the origin of `ker(N)`. -/
theorem doublyConjugatedIdentityBoundaryVanishes :
    partialBoundary [⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩,
        invGen ⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩] = oneWord := rfl

/-- Probe — that doubly-conjugated identity images to `0`, hence augmentation `0` (in `ker(N)`). -/
theorem doublyConjugatedIdentityAugmentationIsZero :
    groupRingAugmentation (crossedModuleImage [⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩,
        invGen ⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩]) = 0 := rfl

/-! ## B2 — the realization family: `crossedModuleImage` surjects onto `ZZ[ZZ/3]` (hence onto `ker N`)

Single generators image to `±eₖ`, so scaling a generator by an integer and concatenating the three
basis columns realizes any `(a, b, c)` as an image.  This makes `crossedModuleImage : E → ZZ[ZZ/3]` a
SURJECTION onto the whole group ring — in particular onto `ker(N)`.

★ **Honest scope.**  This exhibits, for every target, a PREIMAGE in the pre-crossed carrier `E`.  It does
NOT claim the preimage is itself an identity (`∂ = []`); the arbitrary realizer's identity-hood telescopes
`mulWord`-associativity + `mulWord a (invWord a) = []`, the r1 named residual R1 (deferred).  The genuine
`ker(N)`-generators that ARE identities are the rotation orbit `ζ`, `s·ζ`, `s²·ζ` below. -/

/-- Integer scaling of a group-ring element — coefficientwise `Int` multiplication. -/
def groupRingZScale (scale : Int) (value : GroupRingZmod3) : GroupRingZmod3 :=
  ⟨scale * value.coeffOne, scale * value.coeffT, scale * value.coeffTsq⟩

/-- The `e₀` basis generator `(1, ρ)` — images to `(1, 0, 0)`. -/
def genE0 : ConjugatedRelator := ⟨[], 0, true⟩

/-- The `e₁` basis generator `(s, ρ)` — images to `(0, 1, 0)`. -/
def genE1 : ConjugatedRelator := ⟨[SignedLetter.pos 0], 0, true⟩

/-- The `e₂` basis generator `(s², ρ)` — images to `(0, 0, 1)`. -/
def genE2 : ConjugatedRelator := ⟨[SignedLetter.pos 0, SignedLetter.pos 0], 0, true⟩

/-- `count` copies of a generator — structural on the `Nat`. -/
def repeatGenPos : Nat → ConjugatedRelator → PreCrossedElement
  | 0, _ => []
  | count + 1, gen => gen :: repeatGenPos count gen

/-- `scale` signed copies of a generator: `ofNat k` copies of `gen`, `negSucc k` = `k + 1` copies of its
inverse.  Structural on the `Nat` payload after an `Int`-constructor match (no well-founded recursion). -/
def repeatGen : Int → ConjugatedRelator → PreCrossedElement
  | Int.ofNat count, gen => repeatGenPos count gen
  | Int.negSucc predecessor, gen => repeatGenPos (predecessor + 1) (invGen gen)

/-- The successor-scaling law `x + n·x = (n+1)·x` — `intRightDistrib` against the unit. -/
theorem intSuccScale (count : Nat) (value : Int) :
    value + Int.ofNat count * value = Int.ofNat (count + 1) * value :=
  (intAddComm value (Int.ofNat count * value)).trans
    ((congrArg (fun summand => Int.ofNat count * value + summand) (intOneMul value).symm).trans
      (intRightDistrib (Int.ofNat count) 1 value).symm)

/-- The image of `count` copies of a generator is `count`-scaled. -/
theorem imageRepeatGenPos : ∀ (count : Nat) (gen : ConjugatedRelator),
    crossedModuleImage (repeatGenPos count gen)
      = groupRingZScale (Int.ofNat count) (conjugatedRelatorImage gen)
  | 0, gen =>
      groupRingEq (intZeroMul (conjugatedRelatorImage gen).coeffOne).symm
        (intZeroMul (conjugatedRelatorImage gen).coeffT).symm
        (intZeroMul (conjugatedRelatorImage gen).coeffTsq).symm
  | count + 1, gen =>
      (congrArg (fun tailImage => groupRingAdd (conjugatedRelatorImage gen) tailImage)
          (imageRepeatGenPos count gen)).trans
        (groupRingEq (intSuccScale count (conjugatedRelatorImage gen).coeffOne)
          (intSuccScale count (conjugatedRelatorImage gen).coeffT)
          (intSuccScale count (conjugatedRelatorImage gen).coeffTsq))

/-- The `negSucc`-scaling of a negated value is the plain `negSucc`-scaling: `(k+1)·(−x) = negSucc k · x`
(both `−((k+1)·x)`). -/
theorem negSuccScaleNeg (predecessor : Nat) (value : Int) :
    Int.ofNat (predecessor + 1) * -value = Int.negSucc predecessor * value :=
  (intMulNeg (Int.ofNat (predecessor + 1)) value).trans
    (intNegMul (Int.ofNat (predecessor + 1)) value).symm

/-- ★ **The image of `scale` signed copies of a generator is `scale`-scaled** — `ofNat` folds
`imageRepeatGenPos`; `negSucc` folds it on the inverse (`conjugatedRelatorImageInvGen`) and rebalances
the sign (`negSuccScaleNeg`). -/
theorem imageRepeatGen : ∀ (scale : Int) (gen : ConjugatedRelator),
    crossedModuleImage (repeatGen scale gen)
      = groupRingZScale scale (conjugatedRelatorImage gen)
  | Int.ofNat count, gen => imageRepeatGenPos count gen
  | Int.negSucc predecessor, gen =>
      (imageRepeatGenPos (predecessor + 1) (invGen gen)).trans
        ((congrArg (fun negatedImage => groupRingZScale (Int.ofNat (predecessor + 1)) negatedImage)
            (conjugatedRelatorImageInvGen gen)).trans
          (groupRingEq (negSuccScaleNeg predecessor (conjugatedRelatorImage gen).coeffOne)
            (negSuccScaleNeg predecessor (conjugatedRelatorImage gen).coeffT)
            (negSuccScaleNeg predecessor (conjugatedRelatorImage gen).coeffTsq)))

/-- Scaling the `e₀` basis vector: `scale · (1, 0, 0) = (scale, 0, 0)`. -/
theorem groupRingZScaleE0 (scale : Int) :
    groupRingZScale scale (GroupRingZmod3.mk 1 0 0) = GroupRingZmod3.mk scale 0 0 :=
  groupRingEq (intMulOne scale) (intMulZero scale) (intMulZero scale)

/-- Scaling the `e₁` basis vector: `scale · (0, 1, 0) = (0, scale, 0)`. -/
theorem groupRingZScaleE1 (scale : Int) :
    groupRingZScale scale (GroupRingZmod3.mk 0 1 0) = GroupRingZmod3.mk 0 scale 0 :=
  groupRingEq (intMulZero scale) (intMulOne scale) (intMulZero scale)

/-- Scaling the `e₂` basis vector: `scale · (0, 0, 1) = (0, 0, scale)`. -/
theorem groupRingZScaleE2 (scale : Int) :
    groupRingZScale scale (GroupRingZmod3.mk 0 0 1) = GroupRingZmod3.mk 0 0 scale :=
  groupRingEq (intMulZero scale) (intMulZero scale) (intMulOne scale)

/-- The `e₀`-column image: `scale` copies of `genE0` image to `(scale, 0, 0)`. -/
theorem imageRepeatGenE0 (scale : Int) :
    crossedModuleImage (repeatGen scale genE0) = GroupRingZmod3.mk scale 0 0 :=
  (imageRepeatGen scale genE0).trans (groupRingZScaleE0 scale)

/-- The `e₁`-column image: `scale` copies of `genE1` image to `(0, scale, 0)`. -/
theorem imageRepeatGenE1 (scale : Int) :
    crossedModuleImage (repeatGen scale genE1) = GroupRingZmod3.mk 0 scale 0 :=
  (imageRepeatGen scale genE1).trans (groupRingZScaleE1 scale)

/-- The `e₂`-column image: `scale` copies of `genE2` image to `(0, 0, scale)`. -/
theorem imageRepeatGenE2 (scale : Int) :
    crossedModuleImage (repeatGen scale genE2) = GroupRingZmod3.mk 0 0 scale :=
  (imageRepeatGen scale genE2).trans (groupRingZScaleE2 scale)

/-- ★ **The realizer** — `(a, b, c)` as a pre-crossed element: `a` copies of `genE0`, `b` of `genE1`, `c`
of `genE2` (signed), concatenated.  Its image is exactly `(a, b, c)` (`realizeRoundTrip`). -/
def realizeAugmentationZeroIdentity (targetOne targetT targetTsq : Int) : PreCrossedElement :=
  repeatGen targetOne genE0 ++ repeatGen targetT genE1 ++ repeatGen targetTsq genE2

/-- ★★ **THE ROUND TRIP** — `image (realize a b c) = (a, b, c)` for ARBITRARY targets.  Two
`crossedModuleImageAppend`s split the three columns; `imageRepeatGenE0/E1/E2` give each column its basis
value; the coordinatewise `0`-cleanup assembles `(a, b, c)`. -/
theorem realizeRoundTrip (targetOne targetT targetTsq : Int) :
    crossedModuleImage (realizeAugmentationZeroIdentity targetOne targetT targetTsq)
      = GroupRingZmod3.mk targetOne targetT targetTsq :=
  (crossedModuleImageAppend (repeatGen targetOne genE0 ++ repeatGen targetT genE1)
      (repeatGen targetTsq genE2)).trans
    ((congrArg
        (fun leftImage => groupRingAdd leftImage (crossedModuleImage (repeatGen targetTsq genE2)))
        (crossedModuleImageAppend (repeatGen targetOne genE0) (repeatGen targetT genE1))).trans
      ((congrArg
          (fun columnZero => groupRingAdd (groupRingAdd columnZero
              (crossedModuleImage (repeatGen targetT genE1)))
            (crossedModuleImage (repeatGen targetTsq genE2)))
          (imageRepeatGenE0 targetOne)).trans
        ((congrArg
            (fun columnOne => groupRingAdd (groupRingAdd (GroupRingZmod3.mk targetOne 0 0) columnOne)
              (crossedModuleImage (repeatGen targetTsq genE2)))
            (imageRepeatGenE1 targetT)).trans
          ((congrArg
              (fun columnTwo => groupRingAdd
                (groupRingAdd (GroupRingZmod3.mk targetOne 0 0) (GroupRingZmod3.mk 0 targetT 0))
                columnTwo)
              (imageRepeatGenE2 targetTsq)).trans
            (groupRingEq ((intAddZero (targetOne + 0)).trans (intAddZero targetOne))
              ((intAddZero (0 + targetT)).trans (intZeroAdd targetT))
              ((congrArg (fun summand => summand + targetTsq) (intAddZero (0 : Int))).trans
                (intZeroAdd targetTsq)))))))

/-- ★ **`crossedModuleImage` surjects onto the group ring** — every `v : ZZ[ZZ/3]` is `image (realize …)`.
In particular it surjects onto `ker(N)` (which the identities land in, `identityLandsAugmentationZero`),
completing the realization half of the characterization. -/
theorem crossedModuleImageSurjectsOntoGroupRing (value : GroupRingZmod3) :
    crossedModuleImage
        (realizeAugmentationZeroIdentity value.coeffOne value.coeffT value.coeffTsq) = value :=
  realizeRoundTrip value.coeffOne value.coeffT value.coeffTsq

/-! ### B2 probes — evaluate the realizer on the tasked targets -/

/-- ★ Probe (eval) — `realize 2 (−1) (−1)` reduces to the concrete list `[e₀, e₀, e₁⁻¹, e₂⁻¹]`. -/
theorem realizeProbeListTwoNegOneNegOne :
    realizeAugmentationZeroIdentity 2 (-1) (-1)
      = [genE0, genE0, invGen genE1, invGen genE2] := rfl

/-- ★ Probe — the target `(2, −1, −1)` (augmentation `0`) is realized: `image = (2, −1, −1)`. -/
theorem realizeProbeImageTwoNegOneNegOne :
    crossedModuleImage (realizeAugmentationZeroIdentity 2 (-1) (-1))
      = GroupRingZmod3.mk 2 (-1) (-1) :=
  realizeRoundTrip 2 (-1) (-1)

/-- ★ Probe — the target `(0, 3, −3)` (augmentation `0`) is realized: `image = (0, 3, −3)`. -/
theorem realizeProbeImageZeroThreeNegThree :
    crossedModuleImage (realizeAugmentationZeroIdentity 0 3 (-3))
      = GroupRingZmod3.mk 0 3 (-3) :=
  realizeRoundTrip 0 3 (-3)

/-! ## B2b — the genuine `ker(N)`-generators: the rotation orbit `ζ`, `s·ζ`, `s²·ζ`

Unlike the arbitrary realizer, the rotation orbit consists of GENUINE identities (`∂ = []`).  The
`s`-action `sActOnGen` (prepend `s` to the conjugator) is image-equivariant
(`crossedModuleImageSActOnGen`: `image ∘ map sActOnGen = s · image`), so the orbit of `ζ` images to the
`s`-orbit of `(−1, 1, 0)`: `(0, −1, 1)` and `(1, 0, −1)`.  Their sum is `N · image ζ`
(`rotationOrbitSumsToNormElement`), an aug-zero diagonal — the norm relation made explicit. -/

/-- The `s`-action on a generator — prepend `s` to its conjugator (through the free-cancellation guard). -/
def sActOnGen (gen : ConjugatedRelator) : ConjugatedRelator :=
  { gen with conjugator := consReduced (SignedLetter.pos 0) gen.conjugator }

/-- The `s`-action rotates the basis: `s · eₖ = e_{k+1}`. -/
theorem groupRingSActionPowerOfT : ∀ residue : ZmodThree,
    groupRingSAction (powerOfT residue) = powerOfT (shiftUp residue)
  | .residue0 => rfl
  | .residue1 => rfl
  | .residue2 => rfl

/-- The `s`-action commutes with sign scaling. -/
theorem groupRingSActionSignScale : ∀ (sign : Bool) (value : GroupRingZmod3),
    groupRingSAction (signScale sign value) = signScale sign (groupRingSAction value)
  | true, _ => rfl
  | false, _ => rfl

/-- The `s`-action is additive. -/
theorem groupRingSActionAdd (left right : GroupRingZmod3) :
    groupRingSAction (groupRingAdd left right)
      = groupRingAdd (groupRingSAction left) (groupRingSAction right) := rfl

/-- ★ **The `s`-action is image-equivariant on a single generator**: `image (s · gen) = s · image gen`
(via `consReducedResidue` rotating the residue and `groupRingSActionPowerOfT`). -/
theorem conjugatedRelatorImageSActOnGen (gen : ConjugatedRelator) :
    conjugatedRelatorImage (sActOnGen gen)
      = groupRingSAction (conjugatedRelatorImage gen) :=
  (congrArg (fun residue => signScale gen.isPositive (powerOfT residue))
      (consReducedResidue (SignedLetter.pos 0) gen.conjugator)).trans
    ((congrArg (fun rotated => signScale gen.isPositive rotated)
        (groupRingSActionPowerOfT (wordResidue gen.conjugator)).symm).trans
      (groupRingSActionSignScale gen.isPositive (powerOfT (wordResidue gen.conjugator))).symm)

/-- ★★ **The `s`-action is image-equivariant**: `image (map sActOnGen x) = s · image x`. -/
theorem crossedModuleImageSActOnGen : ∀ element : PreCrossedElement,
    crossedModuleImage (List.map sActOnGen element)
      = groupRingSAction (crossedModuleImage element)
  | [] => rfl
  | gen :: rest =>
      (groupRingAddCongr (conjugatedRelatorImageSActOnGen gen)
          (crossedModuleImageSActOnGen rest)).trans
        (groupRingSActionAdd (conjugatedRelatorImage gen) (crossedModuleImage rest)).symm

/-- The second rotation identity `s · ζ` — the `s`-action image of `ζ`. -/
def rotationIdentityWitnessSecond : PreCrossedElement := List.map sActOnGen rotationIdentityWitness

/-- The third rotation identity `s² · ζ`. -/
def rotationIdentityWitnessThird : PreCrossedElement := List.map sActOnGen rotationIdentityWitnessSecond

/-- ★ `s · ζ` images to `(0, −1, 1) = s² − s` (the `s`-rotate of `(−1, 1, 0)`). -/
theorem rotationIdentityWitnessSecondImage :
    crossedModuleImage rotationIdentityWitnessSecond = GroupRingZmod3.mk 0 (-1) 1 :=
  (crossedModuleImageSActOnGen rotationIdentityWitness).trans
    (congrArg groupRingSAction rotationIdentityImageIsSeparating)

/-- ★ `s² · ζ` images to `(1, 0, −1) = 1 − s²`. -/
theorem rotationIdentityWitnessThirdImage :
    crossedModuleImage rotationIdentityWitnessThird = GroupRingZmod3.mk 1 0 (-1) :=
  (crossedModuleImageSActOnGen rotationIdentityWitnessSecond).trans
    (congrArg groupRingSAction rotationIdentityWitnessSecondImage)

/-- ★ `s · ζ` is a genuine identity (`∂ = []`) — `∂` still telescopes `s³·s⁻³ = 1`.  `rfl`. -/
theorem rotationIdentityWitnessSecondBoundaryVanishes :
    partialBoundary rotationIdentityWitnessSecond = oneWord := rfl

/-- ★ `s² · ζ` is a genuine identity (`∂ = []`).  `rfl`. -/
theorem rotationIdentityWitnessThirdBoundaryVanishes :
    partialBoundary rotationIdentityWitnessThird = oneWord := rfl

/-- ★★ **The rotation orbit sums to `N · image ζ`** — `image ζ + image (s·ζ) + image (s²·ζ)
= (1 + s + s²) · image ζ`, an aug-zero diagonal.  The norm relation among the three genuine identities,
machine-checked. -/
theorem rotationOrbitSumsToNormElement :
    groupRingAdd (crossedModuleImage rotationIdentityWitness)
        (groupRingAdd (crossedModuleImage rotationIdentityWitnessSecond)
          (crossedModuleImage rotationIdentityWitnessThird))
      = groupRingNormElement (crossedModuleImage rotationIdentityWitness) :=
  groupRingAddCongr rfl
    (groupRingAddCongr rotationIdentityWitnessSecondImage rotationIdentityWitnessThirdImage)

/-- ★★ **`ker(N)` is Z-spanned by the rotation generators** — any aug-zero `(a, b, c)` decomposes as
`(a, −a, 0) + (0, −c, c)`, integer multiples of `1 − s = (1, −1, 0)` and `s² − s = (0, −1, 1)`.  The
middle coordinate `b = −a − c` is forced by `a + b + c = 0`.  Pure `Int` arithmetic; no multiplication. -/
theorem augmentationZeroSpannedByRotations (targetOne targetT targetTsq : Int)
    (augZero : (targetOne + targetT) + targetTsq = 0) :
    GroupRingZmod3.mk targetOne targetT targetTsq
      = groupRingAdd (GroupRingZmod3.mk targetOne (-targetOne) 0)
          (GroupRingZmod3.mk 0 (-targetTsq) targetTsq) :=
  let sumEqualsNegThird : targetOne + targetT = -targetTsq :=
    (intAddZero (targetOne + targetT)).symm.trans
      ((congrArg (fun summand => (targetOne + targetT) + summand) (intAddRightNeg targetTsq).symm).trans
        ((intAddAssoc (targetOne + targetT) targetTsq (-targetTsq)).symm.trans
          ((congrArg (fun summand => summand + -targetTsq) augZero).trans (intZeroAdd (-targetTsq)))))
  groupRingEq (intAddZero targetOne).symm
    ((intZeroAdd targetT).symm.trans
      ((congrArg (fun summand => summand + targetT) (intAddLeftNeg targetOne).symm).trans
        ((intAddAssoc (-targetOne) targetOne targetT).trans
          (congrArg (fun summand => -targetOne + summand) sumEqualsNegThird))))
    (intZeroAdd targetTsq).symm

end FX1Poly.Polygraph.Homology
