import FX1Poly.Polygraph.Homology.Type2CompletionCyclicThreeInstance
import FX1Poly.Polygraph.Homology.SquierNoGoInterface

/-! # FX1Poly/Polygraph/Homology/SquierNoGoRestingFrontier -- the honest resting adjudication for the
    Squier no-go program (H2-SQUIER-NOGO, #2139)

The r1-r7 arc delivered, zero-axiom and lane-clean, the PRESENTED-scope program:

  * r1 (`SquierNoGoInterface`) -- the finite `HomologyInvariant` read-off, the contrapositive no-go SCHEMA
    `squierNoGoSchema` (gated on an explicit `HomologyPresentationInvariance` hypothesis field -- the
    invariance gap lives in the TYPE), the op-duality sign-invariance witness, and the `S_1` witness ledger
    with obligation-3's structural wall PROVED (`carrierDegreeThreeChainIsAlwaysFinite`).
  * r3 (`FreshGeneratorTietzeExpansionInvariance`) -- the GENERIC fresh-generator Tietze block constructor
    and the generic degree-1 / degree-2 homology-PRESERVATION THEOREMS (fresh-unit rank successor + torsion
    stability), fed through three regressions.
  * r5/r6 (`BlockDiagonalCertificateLifting`, `FreshGeneratorTietzeExpansionInvariance`) -- the cert-free
    block-lifting induction, the non-square (m<n) class closure, the type-2 H1 theorem (generic
    column-in-span clearing), and the permanent H2 wall (`type2CyclicThreeH2PreservationHasNoTheorem`,
    with `type2NaiveH2FreeRankIsOne` recording that the naive move gives a spurious H2 = ZZ).
  * r7 (`Type2CompletionCyclicThreeInstance`) -- the completed UNSIMPLIFIED convergent two-rule system
    `{sss => e, ssss => s}` (11 critical pairs, all joining), its well-formedness `d2 . d3 = 0`, and the
    read-off `H2 = 0` RESTORED by the covering critical pair `ssss = (sss)s` (column `[1, -1]`,
    `rank(d3) = 1`) -- ONE worked type-2 H2 instance, additive evidence for the r6 wall, NOT a general
    theorem.

r8 finds the round-sized rung list EMPTY: every remaining node is a named research frontier or a structural
wall.  Following the WP-2GROUP r10 resting precedent (`CrossedModuleAsphericityRestingFrontier`) and the
TOWER-ANICK r16 rest, THIS module records the rest.  It ships NO marker flip -- the three r7 delivery
markers, the r6 general-H2 wall, and the r1 honesty marker all stay byte-identical, pinned here by `rfl` --
and names the three legs of the frontier with their classical citations and the concrete reason each is
non-round-sized.

## THE FRONTIER TABLE (three research-frontier / structurally-walled legs)

1. **General presentation-invariance / Squier-Pride homotopy leg** -- the general type-2 H2-preservation
     statement: any two finite convergent presentations of the same monoid have isomorphic integral
     homology (equivalently, finite derivation type is a Tietze invariant of finite presentations).  Walled
     by `type2CyclicThreeH2PreservationHasNoTheorem` (r6, byte-intact); the shipped down-payments are the
     r3 generic fresh-generator preservation theorem and the r7 single worked type-2 H2 instance.  Classical:
     Squier-Otto-Kobayashi, Theorem 4.3 (finite derivation type is invariant under change of finite
     presentation), and Squier, Theorem 5.2 (every family of generating confluences is a homotopy basis);
     as reprinted in Guiraud-Malbos, "Polygraphs of finite derivation type," MSCS 28 (2018), 4.2.3 /
     4.3.2-4.3.3, whose printed proof runs through the homotopy-basis transfer (Lemma 4.2.1: a functorial
     section-retraction `(F, G, sigma, tau)` between the free (2,1)-categories; Theorem 4.2.2: the transfer;
     Proposition 4.2.4: finiteness descends).  NON-round-sized: needs a `PresentsMonoid` relation (does not
     exist in-lane) plus the functorial-transfer bookkeeping (or, alternatively, the four elementary Tietze
     transformations preserving a finite homotopy basis).  Mechanized in NO proof assistant -- mathlib4
     stops at abstract `groupCohomology.H2` cocycles; no relation module and no `pi_2`-of-presentation exist
     anywhere.  CITED, never claimed.

2. **The `S_1` homological witness leg (H3 not finitely generated)** -- the deepest no-go content: exhibit a
     finitely-presented monoid with decidable word problem whose degree-3 integral homology is NOT finitely
     generated, hence which admits no finite convergent presentation.  Walled by
     `carrierDegreeThreeChainIsAlwaysFinite`: the shipped chain complex truncates at
     `C_3 = criticalPairs.length` (a finite `Nat`) with no critical-TRIPLE / `C_4` machinery, so `H_3` is a
     subquotient of a finitely-generated free module -- ALWAYS finitely generated by construction; the
     carrier cannot even STATE non-finiteness.  Classical: Squier, Theorem 4.1 (a monoid with a finite
     convergent presentation is of homological type left-FP_3), together with the family `S_k` (for
     `k >= 2`) that is finitely generated with decidable word problem yet NOT left-FP_3 (Squier, JPAA 49
     (1987), 201-217); the left-FP_infinity strengthening via the n-fold critical branchings of Kobayashi
     (1990) and the Anick chains (Anick, 1986).  NON-round-sized: witnessing non-finiteness needs a NEW
     infinite-basis / non-truncated substrate.  The TOWER-ANICK and TOWER-PERIODIC walkers build such
     substrates but explicitly keep `S_1` walled.  CITED, never claimed.

3. **The no-go corollary's live-antecedent leg** -- firing the assembled contrapositive.  `squierNoGoSchema`
     is shipped as an honest INTERFACE, conditional on the load-bearing `HomologyPresentationInvariance`
     field (whose `isInvariant` component IS the missing monoid-level invariance of leg 1); over the finite
     `List` carrier its `not-finitely-generated` antecedent is unsatisfiable
     (`squierNoGoAntecedentUnsatisfiableOverThisCarrier`).  Pulling the trigger needs leg 2's live non-f.g.
     witness AND leg 1's real monoid-level invariance.  Recorded honestly by `squierNoGoOpenedButNotClosed`:
     r1 OPENS the no-go, it does not CLOSE it.  Non-round-sized: a strict superset of legs 1 and 2.

## THE OBSTRUCTION LANDSCAPE (why two witness families, not one)

Finite convergent presentation ==> finite derivation type ==> homological type left-FP_3 (the forward chain;
the FDT ==> left-FP_3 step is due to Cremanns-Otto, Pride, Lafont).  Contrapositively there are two
obstruction strengths: `not left-FP_3` (the `S_k`, k >= 2 -- HOMOLOGICAL, what the shipped H2-of-decided-
walkers machinery detects) is stronger evidence but rarer, while `not FDT` (the monoid `S_1` -- HOMOTOPICAL,
left-FP_3 yet not FDT) catches cases the homological net misses.  The shipped `H2`-of-decided-walkers is the
left-FP_3 detector; FDT is the finer net, unbuilt.

## PRIOR ART (this layer is unclaimed territory)

No machine-checked proof of Squier's homological theorem (the left-FP_3 direction), nor of the FDT
Tietze-invariance theorem, exists in any proof assistant.  The closest formalizations -- the freealgstr
Lean/Agda HoTT rewriting-coherence development, and the single-set cubical omega-categories in Isabelle/HOL
underpinning the cubical Squier coherence theorem -- formalize the HOMOTOPICAL coherence substrate, not the
finiteness obstruction.  A kernel-checked polygraphic chain complex to degree 3 with `d . d = 0`, `H2` of
decided presentations, `ZZ/n` periodic resolutions, and the no-go INTERFACE with its invariance gap in the
type is, to the honest reach of this survey, a genuine first for the homological / no-go layer.

Read the meaning from THIS docstring and the pinned `rfl` facts, never from a name.  An honest rest beats a
padded round: the presented layer is complete; legs 1 and 2 are the research frontier, leg 3 their union. -/

namespace FX1Poly.Polygraph.Homology

/-- The kind of wall standing in front of a Squier-no-go resting leg -- each leg has a DIFFERENT reason it
is non-round-sized, so the three constructors name the three distinct wall-kinds honestly. -/
inductive SquierNoGoFrontierStatus where
  /-- A classical theorem CITED, unmechanized in any proof assistant (Squier-Otto-Kobayashi FDT-invariance /
  Squier-Pride homotopy; no `PresentsMonoid` relation, no `pi_2`-of-presentation formalization exists). -/
  | classicalCitedResearchFrontier
  /-- Structurally walled: the shipped complex truncates at `C_3 = criticalPairs.length` with no critical-
  triple / `C_4` layer, so `H_3` is always finitely generated -- witnessing `S_1`'s non-finiteness needs a
  new infinite-basis substrate (`carrierDegreeThreeChainIsAlwaysFinite`). -/
  | carrierStructuralFinitenessWall
  /-- The assembled contrapositive's antecedent is unsatisfiable over the finite carrier; firing it is a
  strict superset of the other two legs, not an in-lane build (`squierNoGoOpenedButNotClosed`). -/
  | noGoCorollaryLiveAntecedentResidual

/-- The r8 resting frontier -- the three legs that remain after the presented-scope program is complete,
each classified by its honest wall-kind.  No leg is a bounded `rfl`-sized rung. -/
structure SquierNoGoRestingFrontier where
  /-- The general type-2 / presentation-invariance theorem (Squier-Otto-Kobayashi FDT-invariance, Squier
  Pride homotopy). -/
  presentationInvarianceLeg : SquierNoGoFrontierStatus
  /-- The `S_1` homological witness: `H_3` not finitely generated (Squier Theorem 4.1 + the `S_k` family). -/
  witnessNonFinitenessLeg : SquierNoGoFrontierStatus
  /-- Firing the assembled `squierNoGoSchema` contrapositive (a strict superset of the other two legs). -/
  noGoCorollaryTriggerLeg : SquierNoGoFrontierStatus

/-- The resting frontier, filled.  Presentation-invariance = classical research frontier (unmechanized);
the `S_1` witness = the carrier structural-finiteness wall; the no-go corollary trigger = the live-antecedent
residual (a superset of the first two).  Each field is a literal enum constructor. -/
def squierNoGoRestingFrontier : SquierNoGoRestingFrontier :=
  { presentationInvarianceLeg := SquierNoGoFrontierStatus.classicalCitedResearchFrontier
  , witnessNonFinitenessLeg := SquierNoGoFrontierStatus.carrierStructuralFinitenessWall
  , noGoCorollaryTriggerLeg := SquierNoGoFrontierStatus.noGoCorollaryLiveAntecedentResidual }

/-- No flip (r7 delivery, 1/3).  The r7 instance-level marker
`type2CompletedCyclicThreeH2VindicatedAtInstance` stays `true`: the completed unsimplified `ZZ/3` system
preserved `H2 = 0` at the one worked instance -- delivered, unchanged at rest.  `rfl`. -/
theorem squierNoGoRestPinsType2H2VindicatedAtInstance :
    type2CompletedCyclicThreeH2VindicatedAtInstance = true := rfl

/-- No flip (r7 delivery, 2/3).  The r7 tautological-collapse note `type2CompletionTautologicalCollapseNote`
stays `true`: Knuth-Bendix interreduction deletes the derivable rule `R2`, collapsing the completed system
to cyclic `<s | sss>` -- recorded as a note, not the content.  `rfl`. -/
theorem squierNoGoRestPinsTautologicalCollapseNote :
    type2CompletionTautologicalCollapseNote = true := rfl

/-- No flip (r7 delivery, 3/3).  The r7 residual marker `type2CompletedCyclicThreeLedgerResidual` stays
`true`: the general type-2 H2 invariance remains the R1 research wall, paid down by one instance only.
`rfl`. -/
theorem squierNoGoRestPinsLedgerResidual :
    type2CompletedCyclicThreeLedgerResidual = true := rfl

/-- No flip (leg 1 wall stands).  The r6 general-H2 wall `type2CyclicThreeH2PreservationHasNoTheorem` stays
`true`: NO general type-2 H2-preservation theorem is shipped, the r7 instance notwithstanding.  Flipping it
would fabricate the presentation-invariance claim; this `rfl` pins the honest value so any accidental future
edit breaks THIS build.  `rfl`. -/
theorem squierNoGoRestPinsGeneralH2WallStands :
    type2CyclicThreeH2PreservationHasNoTheorem = true := rfl

/-- No flip (leg 2 wall stands, at the r7 head itself).  The carrier's degree-3 chain count is
`criticalPairs.length` -- a finite `Nat` -- for the completed presentation (`C_3 = 11`), the exact
structural finiteness that walls the `S_1` `H_3`-non-finiteness witness.  Proved by applying the shipped
generic `carrierDegreeThreeChainIsAlwaysFinite` at the r7 completed presentation; no new axiom surface. -/
theorem squierNoGoRestPinsCarrierFinitenessAtCompletedHead :
    type2CompletedCyclicThreePresentation.computeBasisCount 3
      = type2CompletedCyclicThreePresentation.criticalPairs.length :=
  carrierDegreeThreeChainIsAlwaysFinite type2CompletedCyclicThreePresentation

/-- No flip (leg 3 honesty).  The r1 honesty marker `squierNoGoOpenedButNotClosed` stays `true`: the no-go
is OPENED (interface + down-payments), never CLOSED.  `rfl`. -/
theorem squierNoGoRestPinsOpenedButNotClosed :
    squierNoGoOpenedButNotClosed = true := rfl

/-- The r8 resting marker.  The walker RESTS at its honest frontier: the round-sized rung list is empty; the
presented-scope program (the no-go interface with its invariance gap in the type, the generic fresh-generator
Tietze preservation theorems, the type-2 H1 theorem, and the one worked type-2 H2 instance) is complete
zero-axiom, and the three remaining legs (general presentation-invariance / Squier-Pride homotopy, the `S_1`
`H_3`-non-finiteness witness, and the assembled contrapositive's live antecedent) are the research frontier
-- CITED in the module docstring's frontier table, never claimed.  No marker flip (pinned by the six `rfl` /
generic-application facts above).  An honest rest beats a padded round. -/
def squierNoGoWalkerRestsAtHonestFrontier : Bool := true

end FX1Poly.Polygraph.Homology
