import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Omega.RelProp.BooleanRelationProp

/-! # FX1PolyAudit.Polygraph.Omega.RelProp.BooleanRelationProp — zero-axiom gate (WP-REL)

Per-declaration zero-axiom gate for the Boolean OR-AND matrix decision of the Carboni-Walters
cartesian bicategory of relations: the fresh Boolean matrix kit, the seven-generator `RelDiagram`
carrier with its Boolean-matrix denotation, per-row soundness (including the rig-flipped SPECIAL
FROBENIUS law `copy;merge = id`), the full congruence-closure soundness lift, the decision procedure
with its negative direction, the walled Carboni-Walters completeness owner marker, and the ground
fires.

Must be free of `propext`, `Quot.sound`, `Classical`, `sorry`, `native_decide`, `omega`,
`WellFounded.fix`.  All recursion is structural on `Nat` bounds; all fires are kernel `rfl`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.BoolMatrixEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.falseEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.identityBoolEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.composeBoolEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.directSumBoolEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeGenEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.createGenEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyGenEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardGenEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapGenEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.capGenEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.cupGenEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.areBoolsEqual
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.doBoolEntriesAgreeOnRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.doBoolEntriesAgreeOnRows
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.doBoolEntriesAgreeUpTo
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapComposeSwapIsIdentity
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyThenMergeIsIdentityEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyThenMergeAgreesWithIdentity
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.falseOr
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.andFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.falseAnd
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.andTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.trueAnd
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.andAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.andOrDistribLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.andOrDistribRight
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orFourExchange
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.areBoolsEqualSelf
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.eqOfAreBoolsEqual
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.beqSelfIsTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.eqOfBeqIsTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.beqIsFalseOfNe
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.bleIsTrueOfLe
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.leOfBleIsTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.bltIsTrueOfLt
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.ltOfBltIsTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.bltIsFalseOfGe
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.noLtOfEq
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.noLtOfGe
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.ltOrEqOfLtSucc
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.succSubSucc
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.addSubCancelLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.bleFalseGivesReverseLt
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.leOfBltIsFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.leGivesAddSubCancel
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.decomposeIndexAgainstBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.leOfAddLeAddLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.ltOfAddLtAddLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.beqAddLeftCancel
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowRespectsPointwise
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowOfAllFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowOfSingleSupport
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowSplitsAtBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowOfPointwiseOr
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowAndLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowAndRight
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.orBelowExchange
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.identityBoolOnDiagonal
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.identityBoolOffDiagonal
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.directSumBoolInTopBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.directSumBoolInBottomBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.directSumBoolInTopRightBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.directSumBoolInBottomLeftBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.leftIsTrueOfAndTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.rightIsTrueOfAndTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.agreeOnRowOfPointwise
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.pointwiseOfAgreeOnRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.agreeOnRowsOfPointwise
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.pointwiseOfAgreeOnRows
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.agreeUpToOfPointwise
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.pointwiseOfAgreeUpTo
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.singleWire
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.denoteBoolEntries
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyDenotesColumnOfOnes
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeDenotesRowOfOnes
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.capDenotesEmptyRectangle
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapDenotesTransposition
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapBesideWire
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.wireBesideSwap
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeBesideWire
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.wireBesideMerge
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyBesideWire
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.wireBesideCopy
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardBesideWire
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.wireBesideDiscard
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.createBesideWire
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.wireBesideCreate
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyPairStage
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.innerSwapWindowStage
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergePairStage
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeAssocLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeAssocRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeAssocRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeLeftUnitLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeLeftUnitRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeLeftUnitRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeRightUnitLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeRightUnitRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeRightUnitRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeCommLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeCommRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.mergeCommRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyCoassocLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyCoassocRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyCoassocRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyLeftCounitLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyLeftCounitRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyLeftCounitRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyRightCounitLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyRightCounitRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyRightCounitRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyCocommLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyCocommRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyCocommRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyAfterMergeLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyAfterMergeRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyAfterMergeRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyAfterCreateLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyAfterCreateRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyAfterCreateRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardAfterMergeLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardAfterMergeRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardAfterMergeRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardAfterCreateLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardAfterCreateRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardAfterCreateRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapInvolutionLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapInvolutionRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapInvolutionRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapYangBaxterLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapYangBaxterRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapYangBaxterRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapPastMergeLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapPastMergeRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapPastMergeRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapPastCreateLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapPastCreateRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.swapPastCreateRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyPastSwapLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyPastSwapRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.copyPastSwapRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardPastSwapLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardPastSwapRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.discardPastSwapRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.specialFrobeniusLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.specialFrobeniusRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.specialFrobeniusRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.capDefinitionLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.capDefinitionRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.capDefinitionRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.cupDefinitionLeftSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.cupDefinitionRightSide
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.cupDefinitionRowIsSound
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.convertibleRelDiagramsDenoteEqualBoolMatrices
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.decideRelConvBool
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.decisionIsImpliedByRelConv
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.notRelConvOfDistinctBoolMatrices
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.carboniWaltersCompletenessStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.rcwHasCarboniWaltersCompleteness
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.fireCopyBoolMatrix
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.fireCapBoolMatrixAndDefinition
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.fireSpecialFrobeniusDecidesTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.fireIdentityVersusSwapDecidesFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.fireIdentityNotConvertibleToSwap
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.identityWires
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.composeSequential
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.tensorParallel
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.mergeGen
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.createGen
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.copyGen
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.discardGen
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.swapGen
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.capGen
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelDiagram.cupGen
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromReflexivity
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromSymmetry
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromTransitivity
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.underComposeSequential
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.underTensorParallel
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.composeIdentitySource
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.composeIdentityTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.composeReassociate
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.tensorIdentityFusion
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.middleFourInterchange
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromMergeAssocRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromMergeLeftUnitRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromMergeRightUnitRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromMergeCommRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCopyCoassocRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCopyLeftCounitRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCopyRightCounitRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCopyCocommRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCopyAfterMergeRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCopyAfterCreateRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromDiscardAfterMergeRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromDiscardAfterCreateRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromSwapInvolutionRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromSwapYangBaxterRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromSwapPastMergeRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromSwapPastCreateRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCopyPastSwapRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromDiscardPastSwapRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromSpecialFrobeniusRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCapDefinitionRow
#assert_no_axioms FX1Poly.Polygraph.Omega.RelProp.RelConv.fromCupDefinitionRow

end FX1PolyAudit
