import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Homology.AmalgamBimonoidBialgebraObstruction

/-! # FX1PolyAudit/Polygraph/Homology/AmalgamBimonoidBialgebraObstruction — zero-axiom gate (the
    bimonoid amalgamation obstruction in the PROP grading: the without-law complex, the with-law
    complex + two-complex comparison, and the probe-decided degree-1 class)

Per-declaration zero-axiom gate for TOWER-MV r3 (the bimonoid round): the arity boundary and its
re-grading pin; the without-law relation boundary and its chain-complex proof; the with-law relation
boundary + bialgebra column + comparison; the Smith normal forms, ranks, degree-1 homology free ranks,
and no-torsion facts; the degree-1 class, the relative cocycle, the escape-without / boundary-with
theorems, the part-alone `H1 = 0` facts, the killer theorem, and the two round-3 markers.

Every declaration must be free of `propext`, `Quot.sound`, `Classical.choice`, `sorry`,
`native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidArityBoundary
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidArityBoundaryIsR1Regrade
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidRelationBoundaryWithoutLaw
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawIsChainComplex
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidBialgebraLawColumn
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidRelationBoundaryWithLaw
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidBialgebraColumnIsLastWithLawColumn
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawIsChainComplex
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidArityBoundarySmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidAritySmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidArityCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidArityBoundaryReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidArityRank
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawRank
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawRank
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawDegreeOneHomologyFreeRank
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawDegreeOneHomologyFreeRankIsOne
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawDegreeOneHomologyFreeRank
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawDegreeOneHomologyFreeRankIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithoutLawHasNoTorsion
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidWithLawHasNoTorsion
#assert_no_axioms FX1Poly.Polygraph.Homology.BimonoidTwoComplexComparisonStatement
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidTwoComplexComparison
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidClassMuPlusDelta
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidClassIsCycle
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidRelativeCocycle
#assert_no_axioms FX1Poly.Polygraph.Homology.withoutLawBoundaryCombinationCoordinate
#assert_no_axioms FX1Poly.Polygraph.Homology.cocycleVanishesOnWithoutLawBoundaries
#assert_no_axioms FX1Poly.Polygraph.Homology.cocycleAnnihilatesEveryWithoutLawCombination
#assert_no_axioms FX1Poly.Polygraph.Homology.cocycleDetectsClass
#assert_no_axioms FX1Poly.Polygraph.Homology.classEscapesWithoutLawBoundarySpan
#assert_no_axioms FX1Poly.Polygraph.Homology.withLawBoundaryCombinationCoordinate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidBialgebraKillingCoefficients
#assert_no_axioms FX1Poly.Polygraph.Homology.classIsWithLawBoundary
#assert_no_axioms FX1Poly.Polygraph.Homology.classDiesWithLaw
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartArityBoundary
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartRelationBoundary
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartArityBoundary
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartRelationBoundary
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartAritySmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartAritySmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartArityProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartArityReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartRelationSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartRelationSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartRelationProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartRelationReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartAritySmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartAritySmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartArityProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartArityReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartRelationSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartRelationSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartRelationProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartRelationReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartDegreeOneHomologyFreeRank
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidMonoidPartDegreeOneHomologyIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartDegreeOneHomologyFreeRank
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidComonoidPartDegreeOneHomologyIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.BimonoidBialgebraObstructionStatement
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidBialgebraObstruction
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidBialgebraLawKillsH1ClassIsLive
#assert_no_axioms FX1Poly.Polygraph.Homology.bimonoidPropRegradingIsHonest

end FX1PolyAudit
