import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Homology.FreshGeneratorTietzeExpansionInvariance

/-! # FX1PolyAudit/Polygraph/Homology/FreshGeneratorTietzeExpansionInvariance — zero-axiom gate (the
    generic fresh-generator Tietze-expansion theorem: the block constructor, the no-new-critical-pair
    fact, the generic degree-1/degree-2 homology-preservation theorems, and the three instances fed
    through them)

Per-declaration zero-axiom gate for H2-SQUIER-NOGO r3 bricks B1..B5.  Every declaration must be free of
`propext`, `Quot.sound`, `Classical.choice`, `sorry`, `native_decide`, `omega`. -/

namespace FX1PolyAudit

-- B1: the generic block constructor + the no-new-critical-pair fact + the hand probe
#assert_no_axioms FX1Poly.Polygraph.Homology.expandWalkerPresentationWithFreshGenerator
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionAddsNoCriticalPairs
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionKeepsDegreeThreeChain
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionBumpsGeneratorCount
#assert_no_axioms FX1Poly.Polygraph.Homology.listAppendSingletonLength
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionBumpsRuleCount
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzePresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeComputesExpandedBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzeBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedBoundaryReducesToSmithNormalForm

-- B2 (r4): the structurally-t-free entry point + the bridging lemma
#assert_no_axioms FX1Poly.Polygraph.Homology.embedBaseWord
#assert_no_axioms FX1Poly.Polygraph.Homology.embeddedBaseWordFreshCountIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.expandWalkerPresentationWithBaseWord
#assert_no_axioms FX1Poly.Polygraph.Homology.expandWalkerPresentationWithBaseWordIsFreshFree

-- B2: the certificate-extension engine + the GENERIC well-formedness of the expansion
#assert_no_axioms FX1Poly.Polygraph.Homology.natZeroAddEqSelf
#assert_no_axioms FX1Poly.Polygraph.Homology.natSuccAddEqAddSucc
#assert_no_axioms FX1Poly.Polygraph.Homology.natZeroLtSucc
#assert_no_axioms FX1Poly.Polygraph.Homology.natSuccLeSucc
#assert_no_axioms FX1Poly.Polygraph.Homology.natLtSuccCases
#assert_no_axioms FX1Poly.Polygraph.Homology.walkerPresentationDimOneRowsGet
#assert_no_axioms FX1Poly.Polygraph.Homology.walkerPresentationDimTwoRowsGet
#assert_no_axioms FX1Poly.Polygraph.Homology.walkerPresentationDimOneRowAppendDistrib
#assert_no_axioms FX1Poly.Polygraph.Homology.listGetWithDefaultAppendLeft
#assert_no_axioms FX1Poly.Polygraph.Homology.sumOverIndicesCongrBelow
#assert_no_axioms FX1Poly.Polygraph.Homology.sumOverIndicesZeroBelow
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionOldColumnD2Agrees
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionOldRowD3Agrees
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionNewGeneratorRowVanishes
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionNewRuleRowVanishes
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionIsWellFormedOfBase
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionChainComplex
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeZmodThreeBaseFreshGeneratorRowIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeZmodThreeBaseFreshRuleRowIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzePresentationIsWellFormed
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzeChainComplex

-- B3: the reader-level diagonal inductions + the generic degree-1/degree-2 preservation theorems
#assert_no_axioms FX1Poly.Polygraph.Homology.natSuccSubSuccEqSub
#assert_no_axioms FX1Poly.Polygraph.Homology.homologyInvariantEq
#assert_no_axioms FX1Poly.Polygraph.Homology.smithRankWithinTopNonzeroIsSuccessor
#assert_no_axioms FX1Poly.Polygraph.Homology.nonUnitInvariantFactorsUnitConsIsStable
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeExpansionPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeExpansionPreservesDegreeTwoInvariant

-- B4: regression 1 (cyclic ZZ/3, t => s)
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreePresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeBoundaryOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeComputesBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeSmithNormalFormOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeBoundaryOfDimOneReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.cyclicThreeFreshExpansionPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeDegreeOneHomologyIsZmodThree
-- B4: regression 2 (r2 Tietze ZZ/3, u => st)
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorPresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorComputesBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorSmithNormalFormOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimOneReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorDegreeOneHomologyIsZmodThree
-- B4: regression 3 (walking involution ZZ/2, t => s) — the FRESH third instance
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionPresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionBoundaryOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionComputesBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionSmithNormalFormOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionBoundaryOfDimOneReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.involutionFreshExpansionPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionDegreeOneHomologyIsZmodTwo
-- B4: the degree-2 preservation instance (r2 Tietze H2 = 0 through the generic degree-2 theorem)
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimTwo
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorComputesBoundaryDimTwo
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorSmithNormalFormOfDimTwo
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorCertificateProducesSmithNormalFormOfDimTwo
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimTwoReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorDegreeTwoSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorPreservesDegreeTwoInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorDegreeTwoHomologyIsZero

-- r4 engine: the fresh-column pivot, the reader congruences, the append-right helper
#assert_no_axioms FX1Poly.Polygraph.Homology.listGetWithDefaultAppendRightStart
#assert_no_axioms FX1Poly.Polygraph.Homology.freshColumnPivotIsUnitOfFreshFree
#assert_no_axioms FX1Poly.Polygraph.Homology.smithRankWithinCongrBelow
#assert_no_axioms FX1Poly.Polygraph.Homology.smithInvariantFactorsWithinCongrBelow
#assert_no_axioms FX1Poly.Polygraph.Homology.smithRankWithinAllZeroDiagonalIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.smithRankWithinTopZeroIsStable
#assert_no_axioms FX1Poly.Polygraph.Homology.smithInvariantFactorsWithinTopZeroIsStable

-- B4 (r4): the END-TO-END homology-preservation theorems (no per-instance reader rfl gate)
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionPreservesDegreeOneHomologyOfBase
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionPreservesDegreeTwoHomologyOfBase

-- B4 (r4): regression 1 re-fed — cyclic ZZ/3, unit last
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeUnitLastSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeRecipeCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeRecipeProducesUnitLast
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeUnitLastDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.cyclicThreeEndToEndDegreeOne
#assert_no_axioms FX1Poly.Polygraph.Homology.cyclicThreeEndToEndDegreeOneIsZmodThree

-- B4 (r4): regression 3 re-fed — walking involution ZZ/2, unit last
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionUnitLastSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionRecipeCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionRecipeProducesUnitLast
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionUnitLastDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.involutionEndToEndDegreeOne

-- B4 (r4): regression 2 re-fed — r2 Tietze ZZ/3, unit last (m<n one generic swap), degree 1 and 2
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorUnitLastSmithNormalFormOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorRecipeCertificateOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorRecipeProducesUnitLastOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorUnitLastDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeThirdGeneratorEndToEndDegreeOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorUnitLastDegreeTwoSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeThirdGeneratorEndToEndDegreeTwo

-- B4 (r4): the FRESH instance — involution t => ss through the structural entry point
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionBaseWord
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionExpansion
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionExpansionComputesBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionWordIsStructurallyFreshFree
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionUnitLastSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionRecipeCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionRecipeProducesUnitLast
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionUnitLastDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionEndToEndDegreeOne
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionEndToEndIsZmodTwo

-- B5: the ledger
#assert_no_axioms FX1Poly.Polygraph.Homology.walkersWithFreshGeneratorExpansionInvarianceCount
#assert_no_axioms FX1Poly.Polygraph.Homology.walkersWithFreshGeneratorExpansionInvarianceCountValue
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorTietzeExpansionLedgerIsComplete
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionEnrichesButNoWallMoved
#assert_no_axioms FX1Poly.Polygraph.Homology.endToEndHomologyPreservationInstanceCount
#assert_no_axioms FX1Poly.Polygraph.Homology.endToEndHomologyPreservationInstanceCountValue
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionEndToEndButConnectionRflRemains

-- B2 (r5): the generic recipe reduction via block-lifting + 4 re-feeds
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorRecipeReducesViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeRecipeViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionRecipeViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionRecipeViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorRecipeViaBlockLifting

-- B3 (r5): the square homology assembly via block-lifting + 3 square re-feeds
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorSquareExpansionPreservesDegreeOneHomologyViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.cyclicThreeEndToEndDegreeOneViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.involutionEndToEndDegreeOneViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.freshInvolutionEndToEndDegreeOneViaBlockLifting

-- B4 (r5): the type-2 spike — H1 preserved (column-in-span), naive H2 REFUTED
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeExpandedBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeReductionCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeNewColumnInSpan
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeReducesToRankOne
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeRankIsOne
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeTorsionIsThree
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeH1FreeRankIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.type2NaiveH2FreeRank
#assert_no_axioms FX1Poly.Polygraph.Homology.type2NaiveH2FreeRankIsOne

-- B5 (r5): the ledger
#assert_no_axioms FX1Poly.Polygraph.Homology.recipeViaBlockLiftingInstanceCount
#assert_no_axioms FX1Poly.Polygraph.Homology.recipeViaBlockLiftingInstanceCountValue
#assert_no_axioms FX1Poly.Polygraph.Homology.homologyViaBlockLiftingSquareInstanceCount
#assert_no_axioms FX1Poly.Polygraph.Homology.homologyViaBlockLiftingSquareInstanceCountValue
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionBlockLiftingWallPaid
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionBlockLiftingResidual

-- B3 (r6): the NON-SQUARE presentation-to-homology assembly (m < n) + r2 Tietze deg-1/2 re-feeds
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorNonSquareExpansionPreservesDegreeOneHomologyViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorNonSquareExpansionPreservesDegreeTwoHomologyViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeThirdGeneratorEndToEndDegreeOneViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeThirdGeneratorEndToEndDegreeTwoViaBlockLifting

-- B4 (r6): the type-2 H1 theorem (generic column-in-span clearing) + the permanent H2 wall
#assert_no_axioms FX1Poly.Polygraph.Homology.appendScalarMultipleColumn
#assert_no_axioms FX1Poly.Polygraph.Homology.mapAllRowsFuseUnderWidth
#assert_no_axioms FX1Poly.Polygraph.Homology.listModifyAtAppendSingletonEnd
#assert_no_axioms FX1Poly.Polygraph.Homology.appendThenClearRowIsExtend
#assert_no_axioms FX1Poly.Polygraph.Homology.appendedScalarMultipleColumnClearsToZeroColumn
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeIsAppendScalarMultiple
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeInSpanColumnClearsGeneric
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeExpandedBoundaryReducesToFromHigher
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeDegreeOneHomologyPreserved
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeDegreeOneHomologyIsZmodThree
#assert_no_axioms FX1Poly.Polygraph.Homology.type2CyclicThreeH2PreservationHasNoTheorem

-- B1 (r6): the generic clearing wrapper — builder + truth probe + generic action lemma
#assert_no_axioms FX1Poly.Polygraph.Homology.freshPivotRow
#assert_no_axioms FX1Poly.Polygraph.Homology.attachFreshColumnEntries
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedWithFreshColumn
#assert_no_axioms FX1Poly.Polygraph.Homology.buildFreshColumnClearing
#assert_no_axioms FX1Poly.Polygraph.Homology.r2TietzeConcreteClearingLandsBlockDiag
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorIsFreshColumnForm
#assert_no_axioms FX1Poly.Polygraph.Homology.replicateZeroRowLength
#assert_no_axioms FX1Poly.Polygraph.Homology.freshPivotRowLength
#assert_no_axioms FX1Poly.Polygraph.Homology.appendConsAssoc
#assert_no_axioms FX1Poly.Polygraph.Homology.listModifyAtAppendAtLeftLength
#assert_no_axioms FX1Poly.Polygraph.Homology.addScaledEntriesReplicateZeroInert
#assert_no_axioms FX1Poly.Polygraph.Homology.addScaledEntriesFreshPivotClears
#assert_no_axioms FX1Poly.Polygraph.Homology.attachFreshColumnEntriesLength
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedFreshColumnSingleClear
#assert_no_axioms FX1Poly.Polygraph.Homology.listAppendLength
#assert_no_axioms FX1Poly.Polygraph.Homology.natLtAddSucc
#assert_no_axioms FX1Poly.Polygraph.Homology.listModifyAtReplicateAppendEnd
#assert_no_axioms FX1Poly.Polygraph.Homology.headClearLemma
#assert_no_axioms FX1Poly.Polygraph.Homology.clearFreshColumnFrom
#assert_no_axioms FX1Poly.Polygraph.Homology.negateColumnExtendRowInert
#assert_no_axioms FX1Poly.Polygraph.Homology.negateColumnFreshPivotIsUnit
#assert_no_axioms FX1Poly.Polygraph.Homology.freshColumnClearingReducesToBlockDiag
#assert_no_axioms FX1Poly.Polygraph.Homology.r2TietzeClearingViaGenericLemma

-- B5 (r6): the ledger — fresh-generator move class CLOSED, clearing action generic, type-2 H1 closed
#assert_no_axioms FX1Poly.Polygraph.Homology.nonSquareHomologyViaBlockSwapInstanceCount
#assert_no_axioms FX1Poly.Polygraph.Homology.nonSquareHomologyViaBlockSwapInstanceCountValue
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorTietzeMoveClassIsComplete
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorClearingActionIsGeneric
#assert_no_axioms FX1Poly.Polygraph.Homology.type2MoveH1ClosedH2Walled
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionR6LedgerResidual

-- B1 (r7): the mechanicals — the SQUARE degree-2 assembly + the recipe with clearingBridge dissolved
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorSquareExpansionPreservesDegreeTwoHomologyViaBlockLifting
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorRecipeReducesGenerically
#assert_no_axioms FX1Poly.Polygraph.Homology.r2TietzeRecipeGenericallyReducesToBlockDiag
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionR7MechanicalsComplete

end FX1PolyAudit
