import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Homology.FreshGeneratorTietzeExpansionInvariance

/-! # FX1PolyAudit/Polygraph/Homology/FreshGeneratorTietzeExpansionInvariance — zero-axiom gate (the
    generic fresh-generator Tietze-expansion theorem: the block constructor, the no-new-critical-pair
    fact, the generic degree-1/degree-2 homology-preservation theorems, and the three instances fed
    through them)

Per-declaration zero-axiom gate for H2-SQUIER-NOGO r3 bricks B1..B5.  Every declaration must be free of
`propext`, `Quot.sound`, `Classical.choice`, `sorry`, `native_decide`, `omega`. -/

namespace FX1PolyAudit

-- B1: the generic block constructor + the no-new-critical-pair fact + the hand probe
#assert_no_axioms FX1Poly.Polygraph.Homology.expandWalkerPresentationWithFreshGenerator
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionAddsNoCriticalPairs
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionKeepsDegreeThreeChain
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionBumpsGeneratorCount
#assert_no_axioms FX1Poly.Polygraph.Homology.listAppendSingletonLength
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionBumpsRuleCount
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzePresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeComputesExpandedBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzeBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedBoundaryReducesToSmithNormalForm

-- B2: the certificate-extension engine + the GENERIC well-formedness of the expansion
#assert_no_axioms FX1Poly.Polygraph.Homology.natZeroAddEqSelf
#assert_no_axioms FX1Poly.Polygraph.Homology.natSuccAddEqAddSucc
#assert_no_axioms FX1Poly.Polygraph.Homology.natZeroLtSucc
#assert_no_axioms FX1Poly.Polygraph.Homology.natSuccLeSucc
#assert_no_axioms FX1Poly.Polygraph.Homology.natLtSuccCases
#assert_no_axioms FX1Poly.Polygraph.Homology.walkerPresentationDimOneRowsGet
#assert_no_axioms FX1Poly.Polygraph.Homology.walkerPresentationDimTwoRowsGet
#assert_no_axioms FX1Poly.Polygraph.Homology.walkerPresentationDimOneRowAppendDistrib
#assert_no_axioms FX1Poly.Polygraph.Homology.listGetWithDefaultAppendLeft
#assert_no_axioms FX1Poly.Polygraph.Homology.sumOverIndicesCongrBelow
#assert_no_axioms FX1Poly.Polygraph.Homology.sumOverIndicesZeroBelow
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionOldColumnD2Agrees
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionOldRowD3Agrees
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionNewGeneratorRowVanishes
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionNewRuleRowVanishes
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionIsWellFormedOfBase
#assert_no_axioms FX1Poly.Polygraph.Homology.freshGeneratorExpansionChainComplex
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeZmodThreeBaseFreshGeneratorRowIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeZmodThreeBaseFreshRuleRowIsZero
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzePresentationIsWellFormed
#assert_no_axioms FX1Poly.Polygraph.Homology.handProbeExpandedTietzeChainComplex

-- B3: the reader-level diagonal inductions + the generic degree-1/degree-2 preservation theorems
#assert_no_axioms FX1Poly.Polygraph.Homology.natSuccSubSuccEqSub
#assert_no_axioms FX1Poly.Polygraph.Homology.homologyInvariantEq
#assert_no_axioms FX1Poly.Polygraph.Homology.smithRankWithinTopNonzeroIsSuccessor
#assert_no_axioms FX1Poly.Polygraph.Homology.nonUnitInvariantFactorsUnitConsIsStable
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeExpansionPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.tietzeExpansionPreservesDegreeTwoInvariant

-- B4: regression 1 (cyclic ZZ/3, t => s)
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreePresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeBoundaryOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeComputesBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeSmithNormalFormOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeBoundaryOfDimOneReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.cyclicThreeFreshExpansionPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedCyclicThreeDegreeOneHomologyIsZmodThree
-- B4: regression 2 (r2 Tietze ZZ/3, u => st)
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorPresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorComputesBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorSmithNormalFormOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorBoundaryOfDimOneReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedTietzeThirdGeneratorDegreeOneHomologyIsZmodThree
-- B4: regression 3 (walking involution ZZ/2, t => s) — the FRESH third instance
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionPresentation
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionBoundaryOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionComputesBoundaryDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionSmithNormalFormOfDimOne
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionBoundaryOfDimOneSmithCertificate
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionCertificateProducesSmithNormalForm
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionBoundaryOfDimOneReducesToSmith
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionDegreeOneSmithData
#assert_no_axioms FX1Poly.Polygraph.Homology.involutionFreshExpansionPreservesDegreeOneInvariant
#assert_no_axioms FX1Poly.Polygraph.Homology.expandedInvolutionDegreeOneHomologyIsZmodTwo

end FX1PolyAudit
