import FX1PolyAudit.DependencyAudit
import FX1Poly.ComputerAlgebra.Analysis.RealIntegral

/-! # FX1PolyAudit/ComputerAlgebra/Analysis/RealIntegral — zero-axiom gate
    (ANALYSIS-INTEGRAL-1)

Per-declaration zero-axiom gate for the Riemann-sum functional layer: the
constant-real homomorphisms, the natural-scaling law, the rational mesh and
sample points, the cell-count/mesh telescope, the Riemann-sum functional, and
its exact linearity + constant laws.

Every declaration must be free of `propext`, `Quot.sound`,
`Classical.choice`, `sorry`, `native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.ComputerAlgebra.constantRealAddExact
#assert_no_axioms FX1Poly.ComputerAlgebra.constantRealMulExact
#assert_no_axioms FX1Poly.ComputerAlgebra.natRational
#assert_no_axioms FX1Poly.ComputerAlgebra.natRationalSuccDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.replicateRealEqScale
#assert_no_axioms FX1Poly.ComputerAlgebra.isMagnitudeWithinSelfOfNonNegative
#assert_no_axioms FX1Poly.ComputerAlgebra.mulExactRespectsIsWithinBoundConstantLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.natRationalZeroDenotesZero
#assert_no_axioms FX1Poly.ComputerAlgebra.natScaleRationalDenotesScale
#assert_no_axioms FX1Poly.ComputerAlgebra.scalarMulRealExactBoundOfNonNegative
#assert_no_axioms FX1Poly.ComputerAlgebra.sumRealRespectsIsWithinRealBoundOnRange
#assert_no_axioms FX1Poly.ComputerAlgebra.refinedCellCountPredecessor
#assert_no_axioms FX1Poly.ComputerAlgebra.natRationalMul
#assert_no_axioms FX1Poly.ComputerAlgebra.reciprocalBlockCancels
#assert_no_axioms FX1Poly.ComputerAlgebra.meshWidthRefinesByBlock
#assert_no_axioms FX1Poly.ComputerAlgebra.samplePointBaseRefines
#assert_no_axioms FX1Poly.ComputerAlgebra.natRationalAddDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.subExactSelfAddRightDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.samplePointOffsetShift
#assert_no_axioms FX1Poly.ComputerAlgebra.samplePointGapWithinMesh
#assert_no_axioms FX1Poly.ComputerAlgebra.constantRealIsWithinRealBoundOfIsWithinBound
#assert_no_axioms FX1Poly.ComputerAlgebra.refinementEstimate
#assert_no_axioms FX1Poly.ComputerAlgebra.meshWidth
#assert_no_axioms FX1Poly.ComputerAlgebra.samplePoint
#assert_no_axioms FX1Poly.ComputerAlgebra.cellCountMeshWidthDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.riemannSum
#assert_no_axioms FX1Poly.ComputerAlgebra.riemannSumAddReal
#assert_no_axioms FX1Poly.ComputerAlgebra.riemannSumScalarMulReal
#assert_no_axioms FX1Poly.ComputerAlgebra.riemannSumConstant
#assert_no_axioms FX1Poly.ComputerAlgebra.meshLessEqualReciprocalOfCellBound
#assert_no_axioms FX1Poly.ComputerAlgebra.refinedCellCountPredecessorAssoc
#assert_no_axioms FX1Poly.ComputerAlgebra.denotesSameRealOfEq
#assert_no_axioms FX1Poly.ComputerAlgebra.scheduleBlockPredecessor
#assert_no_axioms FX1Poly.ComputerAlgebra.scheduleCellCountPredecessor
#assert_no_axioms FX1Poly.ComputerAlgebra.integralSchedulePredecessor
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOutputPrecisionPredecessor
#assert_no_axioms FX1Poly.ComputerAlgebra.scheduleCellCountSelfGeStepFactor
#assert_no_axioms FX1Poly.ComputerAlgebra.integralScheduleMeshCondition
#assert_no_axioms FX1Poly.ComputerAlgebra.scheduleRefinementFromGap
#assert_no_axioms FX1Poly.ComputerAlgebra.scheduleRefinementBetween
#assert_no_axioms FX1Poly.ComputerAlgebra.scheduleRiemannLegBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.reciprocalLeAddReciprocalLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.reciprocalLeAddReciprocalRight
#assert_no_axioms FX1Poly.ComputerAlgebra.scheduleRiemannSumIsCauchy
#assert_no_axioms FX1Poly.ComputerAlgebra.riemannSumScheduleSequence
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOfUC
#assert_no_axioms FX1Poly.ComputerAlgebra.isUniformlyContinuousConstantReal
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOfUCConstant
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOfUCAddReal
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOfUCScalarMul
#assert_no_axioms FX1Poly.ComputerAlgebra.riemannSumRespectsDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOfUCRespectsDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.riemannSumNegReal
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOfUCNegReal
#assert_no_axioms FX1Poly.ComputerAlgebra.integralOfUCSubReal

end FX1PolyAudit
