import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.TwoCategory.WalkingMonad.MonadSaturatedDeltaReps

/-! # FX1PolyAudit.Polygraph.TwoCategory.WalkingMonad.MonadSaturatedDeltaReps — zero-axiom gate (the deep bridge)

Per-declaration zero-axiom gate for the bespoke-free DEEP saturated-Δ representatives bridge: the unit /
multiplication free 2-cells and the three law composites, and the retuned monotone-map fold with its generator
smokes, structural-fragment soundness leg, and three monad-law fold-soundness theorems, relocated VERBATIM from the
pure-bespoke Δ chain so the survivor lane can consume the walking-monad skeleton conv-decoupled.  Must be free of
`propext`, `Quot.sound`, `Classical`, `sorry`, `native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Polygraph.monadUnitTwoCell
#assert_no_axioms FX1Poly.Polygraph.monadMulTwoCell
#assert_no_axioms FX1Poly.Polygraph.monadLeftUnitCell
#assert_no_axioms FX1Poly.Polygraph.monadRightUnitCell
#assert_no_axioms FX1Poly.Polygraph.monadAssocLeftCell
#assert_no_axioms FX1Poly.Polygraph.monadAssocRightCell
#assert_no_axioms FX1Poly.Polygraph.monadIdTCell
#assert_no_axioms FX1Poly.Polygraph.monadMonoStepAtom
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_unit
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_mul
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_congr_of_spine_eq
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_eq_of_interchangeFreeStep
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_leftUnit_eq_id
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_rightUnit_eq_id
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_assoc_eq
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredLeftUnit_via_simplicialIdentity
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredIdT_eq
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredLeftUnit
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_rightUnit_via_succSimplicialIdentity
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_assoc_via_degenCommute

#assert_no_axioms FX1Poly.Polygraph.monadMonoProcessSpine
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell
#assert_no_axioms FX1Poly.Polygraph.monadMonoProcessSpine_spineDiff
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_vcomp
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_whiskerLeft
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_whiskerRight
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_rightContext_irrelevant
#assert_no_axioms FX1Poly.Polygraph.monadEtaWidthShift
#assert_no_axioms FX1Poly.Polygraph.monadMuWidthShift
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_width_gen
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_width
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_eq_runMonoCell
#assert_no_axioms FX1Poly.Polygraph.monadWhiskerT_length
#assert_no_axioms FX1Poly.Polygraph.monadWhiskerTTT_length
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredLeftUnit_atContext
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredIdT_atContext
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredLeftUnit_sound
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredRightUnit_atContext
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredRightUnit_sound
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskeredAssoc_sound
#assert_no_axioms FX1Poly.Polygraph.monadMergeThenUnitRight
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_idTThenT
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_mergeThenUnitRight
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_separates_idTThenT_mergeThenUnitRight
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_identifies_leftUnit_idT
#assert_no_axioms FX1Poly.Polygraph.fxMonad_hasMonotoneMapEngineAndLawsAtContext
#assert_no_axioms FX1Poly.Polygraph.fxMonad_hasFullMapEqOfConvAndCompleteness

#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_mapsInto_gen
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_mapsInto
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_map_length
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_mapFactor_gen
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_mapFactor
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_vcomp_map
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_vcomp
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_vcompCongrLeft
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_vcompCongrRight
#assert_no_axioms FX1Poly.Polygraph.fxMonad_hasMapFactorizationAndVcompCongruence

#assert_no_axioms FX1Poly.Polygraph.embedLocalMap_idMap
#assert_no_axioms FX1Poly.Polygraph.faceMap_eq_embedLocalMap
#assert_no_axioms FX1Poly.Polygraph.degenMap_eq_embedLocalMap
#assert_no_axioms FX1Poly.Polygraph.embedLocalMap_composeMap
#assert_no_axioms FX1Poly.Polygraph.embedLocalMap_nest
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_length
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_mapsInto
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_localEmbed_gen
#assert_no_axioms FX1Poly.Polygraph.monadRunMonoCell_localEmbed
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskerLeft
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskerRight
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskerLeftCongr
#assert_no_axioms FX1Poly.Polygraph.monadMonotoneMapOf_whiskerRightCongr
#assert_no_axioms FX1Poly.Polygraph.fxMonad_hasWhiskerEmbeddingAndCongruence
end FX1PolyAudit
