import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.TwoCategory.WalkingAdjunction.AdjunctionTriangleObstruction

/-! # FX1PolyAudit.Polygraph.TwoCategory.WalkingAdjunction.AdjunctionTriangleObstruction — zero-axiom gate (the fib-3 dim-2 obstruction)

Per-declaration zero-axiom gate for the rigorous adjunction-triangle obstruction: the two snakes, their generator
counts, the identity count, the two non-convertibility obstruction theorems, the termination-direction fact, and
the confluence-direction structural-normality of the snakes (the triangle is their sole redex).
Must be free of `propext`, `Quot.sound`, `Classical`, `sorry`, `native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake_generatorCount
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake_generatorCount
#assert_no_axioms FX1Poly.Polygraph.leftIdentityCell_generatorCount
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake_not_conv_id
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake_not_conv_id
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake_classGeneratorCount
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake_classGeneratorCount
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedTriangleReductionDecreasesCount
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightTriangleReductionDecreasesCount
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake_isInterchangeNormal
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake_isInterchangeNormal
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake_no_structuralStep
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake_no_structuralStep
#assert_no_axioms FX1Poly.Polygraph.AdjunctionLeftSaturatedStep
#assert_no_axioms FX1Poly.Polygraph.AdjunctionLeftSaturatedReduces
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake_vcompContinuation_reducesToContinuation
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedLeftSnake_assocCriticalPair_joins
#assert_no_axioms FX1Poly.Polygraph.AdjunctionRightSaturatedStep
#assert_no_axioms FX1Poly.Polygraph.AdjunctionRightSaturatedReduces
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake_vcompContinuation_reducesToContinuation
#assert_no_axioms FX1Poly.Polygraph.adjunctionSeedRightSnake_assocCriticalPair_joins
#assert_no_axioms FX1Poly.Polygraph.AdjunctionLeftSaturatedStep.generatorCount_le
#assert_no_axioms FX1Poly.Polygraph.AdjunctionLeftSaturatedReduces.generatorCount_le
#assert_no_axioms FX1Poly.Polygraph.AdjunctionRightSaturatedStep.generatorCount_le
#assert_no_axioms FX1Poly.Polygraph.AdjunctionRightSaturatedReduces.generatorCount_le

end FX1PolyAudit
