import LeanFX2.Foundation.Ty
import LeanFX2.Foundation.Subst
import LeanFX2.Foundation.SubstActsOnTy

/-! # Foundation/TyActBridge — Zero-axiom bridge equivalence theorems for `Ty.act`.

## Mission summary (relaunch)

Tier 3 / MEGA-Z2.B was originally chartered to redirect the bodies of
`Ty.rename`, `Ty.subst`, and `Ty.weaken` to one-line invocations of
`Ty.act`.  The literal redirect was investigated during this
relaunch; the conclusion is that an in-place body redefinition
cascades through ~250+ `simp only [Ty.rename]` / `simp only [Ty.subst]`
sites in `Foundation/{Ty,Subst,SubstHet}.lean` plus three downstream
files (`Term/Subst.lean`, `Term/Rename.lean`, `Term/SubstHet.lean`).
Each site relies on the per-ctor equation lemmas generated by the
existing pattern-match bodies; redirecting to `Ty.act` replaces those
with a single equation `Ty.rename t rho = Ty.act t rho`, breaking
every reduction-by-simp.

That cascade is *exactly* the work captured by MEGA-Z3 (drop
propositional commute lemmas — WSC/WSHC/WRC + BHKM ladder).  Z3's
charter assumes Z2.B has shipped a SEMANTIC bridge between `Ty.act`
and the three legacy operations; Z3 then DELETES the legacy
operations and their commute ladder, replacing every consumer with
direct `Ty.act` calls.

This file is therefore the Z2.B deliverable as a SEMANTIC bridge:
zero-axiom theorems witnessing `Ty.act ≡ Ty.{rename,subst,weaken}`
pointwise on every Ty constructor.  Once shipped, Z3 has the
algebraic license to perform the literal redirect across the whole
project.

## Theorems shipped

* `Ty.act_eq_rename` — `Ty.act t rho = Ty.rename t rho` for every
  `t : Ty level scope`, every `rho : RawRenaming scope targetScope`,
  every `level`.  Proved by structural induction on `t` over all 25
  Ty constructors.
* `Ty.act_eq_subst`  — `Ty.act t sigma = Ty.subst t sigma` for every
  `t : Ty level scope`, every `sigma : Subst level scope targetScope`.
* `Ty.act_eq_weaken` — `Ty.act t RawRenaming.weaken = Ty.weaken t` for
  every `t : Ty level scope`.  Corollary of `Ty.act_eq_rename` with
  `rho = RawRenaming.weaken` after unfolding `Ty.weaken`.

Per the strict zero-axiom commitment in `CLAUDE.md`, every shipped
declaration must report "does not depend on any axioms".  The
matching smoke gates live in `Smoke/AuditMegaZ2B.lean`; this
production file carries only the load-bearing theorem definitions.

## Why these theorems are zero-axiom

Each constructor arm is either `rfl` (leaf ctors: `unit`, `bool`,
`nat`, `empty`, `interval`, `universe`) or a structural rewrite using
the inductive hypothesis.  No propext, no Quot.sound, no Classical
appeal.  The matching arm shapes mirror `Ty.rename` and `Ty.subst`'s
pattern-match exactly, and `Ty.act`'s shape — guaranteeing
`simp only [Ty.act, Ty.rename]` (or the corresponding `subst` pair)
reduces both sides to the same constructor application.

The `tyVar` arm is the load-bearing one: `Ty.act` looks up via
`ActsOnTyVar.varToTy`, which for `RawRenaming` reduces to
`Ty.tyVar (rho position)` (the `instActsOnRawTermRawRenaming` /
`ActsOnTyVarOfRawRenaming` instances) — definitionally identical to
`Ty.rename`'s `tyVar` arm.  For `Subst level`, `varToTy` reduces to
`sigma.forTy position` — definitionally identical to `Ty.subst`'s
`tyVar` arm.

Binder arms (`piTy`, `sigmaTy`, `refine`) require the IH to be
applied at the lifted action.  For `RawRenaming`, `Action.liftForTy`
is `rho.lift` — definitionally identical to the existing
`Ty.rename`'s `rho.lift` recursive call.  For `Subst level`,
`Action.liftForTy` is `sigma.lift` — definitionally identical.  No
extensionality needed; the IHs apply directly.

## Bridge for Ty.weaken

`Ty.weaken t = t.rename RawRenaming.weaken` by definition.
Therefore `Ty.act_eq_weaken` is `Ty.act_eq_rename` specialised at
`rho = RawRenaming.weaken`.  Ships as a one-line corollary.
-/

namespace LeanFX2

-- ============================================================
-- Section 1: Bridge — Ty.act over RawRenaming equals Ty.rename
-- ============================================================

/-- Bridge theorem: applying `Ty.act` over a `RawRenaming` Container
produces the same result as applying `Ty.rename` directly.  Proved by
structural induction on the type over all 25 Ty constructors.

Per the docstring above, every arm reduces by `rfl` (leaves) or by
the inductive hypothesis (recursive ctors).  Binder arms use the
fact that `Action.liftForTy rho` and `Action.liftForRaw rho` for the
`RawRenaming` Action instance are both definitionally `rho.lift`. -/
theorem Ty.act_eq_rename {level : Nat} :
    ∀ {scope targetScope : Nat}
      (someTy : Ty level scope) (someRenaming : RawRenaming scope targetScope),
      Ty.act someTy someRenaming = Ty.rename someTy someRenaming := by
  intro scope targetScope someTy
  induction someTy generalizing targetScope with
  | unit => intro _; rfl
  | bool => intro _; rfl
  | nat  => intro _; rfl
  | arrow domainType codomainType domainIH codomainIH =>
      intro someRenaming
      show Ty.arrow (domainType.act someRenaming) (codomainType.act someRenaming) =
           Ty.arrow (domainType.rename someRenaming) (codomainType.rename someRenaming)
      rw [domainIH someRenaming, codomainIH someRenaming]
  | piTy domainType codomainType domainIH codomainIH =>
      intro someRenaming
      show Ty.piTy (domainType.act someRenaming)
                   (codomainType.act (Action.liftForTy someRenaming)) =
           Ty.piTy (domainType.rename someRenaming)
                   (codomainType.rename someRenaming.lift)
      rw [domainIH someRenaming, codomainIH (Action.liftForTy someRenaming)]
      rfl
  | sigmaTy firstType secondType firstIH secondIH =>
      intro someRenaming
      show Ty.sigmaTy (firstType.act someRenaming)
                      (secondType.act (Action.liftForTy someRenaming)) =
           Ty.sigmaTy (firstType.rename someRenaming)
                      (secondType.rename someRenaming.lift)
      rw [firstIH someRenaming, secondIH (Action.liftForTy someRenaming)]
      rfl
  | tyVar position => intro _; rfl
  | id carrier leftEndpoint rightEndpoint carrierIH =>
      intro someRenaming
      show Ty.id (carrier.act someRenaming)
                 (RawTerm.act leftEndpoint someRenaming)
                 (RawTerm.act rightEndpoint someRenaming) =
           Ty.id (carrier.rename someRenaming)
                 (leftEndpoint.rename someRenaming)
                 (rightEndpoint.rename someRenaming)
      rw [carrierIH someRenaming,
          RawTerm.act_eq_rename leftEndpoint someRenaming,
          RawTerm.act_eq_rename rightEndpoint someRenaming]
  | listType elementType elementIH =>
      intro someRenaming
      show Ty.listType (elementType.act someRenaming) =
           Ty.listType (elementType.rename someRenaming)
      rw [elementIH someRenaming]
  | optionType elementType elementIH =>
      intro someRenaming
      show Ty.optionType (elementType.act someRenaming) =
           Ty.optionType (elementType.rename someRenaming)
      rw [elementIH someRenaming]
  | eitherType leftType rightType leftIH rightIH =>
      intro someRenaming
      show Ty.eitherType (leftType.act someRenaming) (rightType.act someRenaming) =
           Ty.eitherType (leftType.rename someRenaming) (rightType.rename someRenaming)
      rw [leftIH someRenaming, rightIH someRenaming]
  | «universe» universeLevel levelLe => intro _; rfl
  | empty => intro _; rfl
  | interval => intro _; rfl
  | path carrier leftEndpoint rightEndpoint carrierIH =>
      intro someRenaming
      show Ty.path (carrier.act someRenaming)
                   (RawTerm.act leftEndpoint someRenaming)
                   (RawTerm.act rightEndpoint someRenaming) =
           Ty.path (carrier.rename someRenaming)
                   (leftEndpoint.rename someRenaming)
                   (rightEndpoint.rename someRenaming)
      rw [carrierIH someRenaming,
          RawTerm.act_eq_rename leftEndpoint someRenaming,
          RawTerm.act_eq_rename rightEndpoint someRenaming]
  | glue baseType boundaryWitness baseIH =>
      intro someRenaming
      show Ty.glue (baseType.act someRenaming)
                   (RawTerm.act boundaryWitness someRenaming) =
           Ty.glue (baseType.rename someRenaming)
                   (boundaryWitness.rename someRenaming)
      rw [baseIH someRenaming,
          RawTerm.act_eq_rename boundaryWitness someRenaming]
  | oeq carrier leftEndpoint rightEndpoint carrierIH =>
      intro someRenaming
      show Ty.oeq (carrier.act someRenaming)
                  (RawTerm.act leftEndpoint someRenaming)
                  (RawTerm.act rightEndpoint someRenaming) =
           Ty.oeq (carrier.rename someRenaming)
                  (leftEndpoint.rename someRenaming)
                  (rightEndpoint.rename someRenaming)
      rw [carrierIH someRenaming,
          RawTerm.act_eq_rename leftEndpoint someRenaming,
          RawTerm.act_eq_rename rightEndpoint someRenaming]
  | idStrict carrier leftEndpoint rightEndpoint carrierIH =>
      intro someRenaming
      show Ty.idStrict (carrier.act someRenaming)
                       (RawTerm.act leftEndpoint someRenaming)
                       (RawTerm.act rightEndpoint someRenaming) =
           Ty.idStrict (carrier.rename someRenaming)
                       (leftEndpoint.rename someRenaming)
                       (rightEndpoint.rename someRenaming)
      rw [carrierIH someRenaming,
          RawTerm.act_eq_rename leftEndpoint someRenaming,
          RawTerm.act_eq_rename rightEndpoint someRenaming]
  | equiv domainType codomainType domainIH codomainIH =>
      intro someRenaming
      show Ty.equiv (domainType.act someRenaming) (codomainType.act someRenaming) =
           Ty.equiv (domainType.rename someRenaming) (codomainType.rename someRenaming)
      rw [domainIH someRenaming, codomainIH someRenaming]
  | refine baseType predicate baseIH =>
      intro someRenaming
      show Ty.refine (baseType.act someRenaming)
                     (RawTerm.act predicate (Action.liftForRaw someRenaming)) =
           Ty.refine (baseType.rename someRenaming)
                     (predicate.rename someRenaming.lift)
      rw [baseIH someRenaming,
          RawTerm.act_eq_rename predicate (Action.liftForRaw someRenaming)]
      rfl
  | record singleFieldType singleFieldIH =>
      intro someRenaming
      show Ty.record (singleFieldType.act someRenaming) =
           Ty.record (singleFieldType.rename someRenaming)
      rw [singleFieldIH someRenaming]
  | codata stateType outputType stateIH outputIH =>
      intro someRenaming
      show Ty.codata (stateType.act someRenaming) (outputType.act someRenaming) =
           Ty.codata (stateType.rename someRenaming) (outputType.rename someRenaming)
      rw [stateIH someRenaming, outputIH someRenaming]
  | session protocolStep =>
      intro someRenaming
      show Ty.session (RawTerm.act protocolStep someRenaming) =
           Ty.session (protocolStep.rename someRenaming)
      rw [RawTerm.act_eq_rename protocolStep someRenaming]
  | effect carrierType effectTag carrierIH =>
      intro someRenaming
      show Ty.effect (carrierType.act someRenaming)
                     (RawTerm.act effectTag someRenaming) =
           Ty.effect (carrierType.rename someRenaming)
                     (effectTag.rename someRenaming)
      rw [carrierIH someRenaming,
          RawTerm.act_eq_rename effectTag someRenaming]
  | modal modalityTag carrierType carrierIH =>
      intro someRenaming
      show Ty.modal modalityTag (carrierType.act someRenaming) =
           Ty.modal modalityTag (carrierType.rename someRenaming)
      rw [carrierIH someRenaming]

-- ============================================================
-- Section 2: Bridge — Ty.act over Subst equals Ty.subst
-- ============================================================

/-- Bridge theorem: applying `Ty.act` over a `Subst level` Container
produces the same result as applying `Ty.subst` directly.  Proved by
structural induction over all 25 Ty constructors.

The `tyVar` arm reduces by `rfl` because `ActsOnTyVarOfSubst.varToTy
sigma position = sigma.forTy position` definitionally — same as
`Ty.subst`'s `tyVar` arm.

The raw-payload arms (`id`, `path`, `glue`, `oeq`, `idStrict`,
`session`, `effect`) use `ActsOnRawTermOfSubst.actOnRawTerm sigma raw
= raw.subst sigma.forRaw` definitionally — same as `Ty.subst`'s
arms for those ctors.

Binder arms (`piTy`, `sigmaTy`, `refine`) use `Action.liftForTy sigma
= sigma.lift` and `Action.liftForRaw sigma = sigma.lift`
definitionally — same as `Ty.subst`'s recursive calls. -/
theorem Ty.act_eq_subst {level : Nat} :
    ∀ {scope targetScope : Nat}
      (someTy : Ty level scope) (someSubst : Subst level scope targetScope),
      Ty.act someTy someSubst = Ty.subst someTy someSubst := by
  intro scope targetScope someTy
  induction someTy generalizing targetScope with
  | unit => intro _; rfl
  | bool => intro _; rfl
  | nat  => intro _; rfl
  | arrow domainType codomainType domainIH codomainIH =>
      intro someSubst
      show Ty.arrow (domainType.act someSubst) (codomainType.act someSubst) =
           Ty.arrow (domainType.subst someSubst) (codomainType.subst someSubst)
      rw [domainIH someSubst, codomainIH someSubst]
  | piTy domainType codomainType domainIH codomainIH =>
      intro someSubst
      show Ty.piTy (domainType.act someSubst)
                   (codomainType.act (Action.liftForTy someSubst)) =
           Ty.piTy (domainType.subst someSubst)
                   (codomainType.subst someSubst.lift)
      rw [domainIH someSubst, codomainIH (Action.liftForTy someSubst)]
      rfl
  | sigmaTy firstType secondType firstIH secondIH =>
      intro someSubst
      show Ty.sigmaTy (firstType.act someSubst)
                      (secondType.act (Action.liftForTy someSubst)) =
           Ty.sigmaTy (firstType.subst someSubst)
                      (secondType.subst someSubst.lift)
      rw [firstIH someSubst, secondIH (Action.liftForTy someSubst)]
      rfl
  | tyVar position => intro _; rfl
  | id carrier leftEndpoint rightEndpoint carrierIH =>
      intro someSubst
      show Ty.id (carrier.act someSubst)
                 (RawTerm.act leftEndpoint someSubst)
                 (RawTerm.act rightEndpoint someSubst) =
           Ty.id (carrier.subst someSubst)
                 (leftEndpoint.subst someSubst.forRaw)
                 (rightEndpoint.subst someSubst.forRaw)
      rw [carrierIH someSubst,
          RawTerm.act_eq_subst_forRaw leftEndpoint someSubst,
          RawTerm.act_eq_subst_forRaw rightEndpoint someSubst]
  | listType elementType elementIH =>
      intro someSubst
      show Ty.listType (elementType.act someSubst) =
           Ty.listType (elementType.subst someSubst)
      rw [elementIH someSubst]
  | optionType elementType elementIH =>
      intro someSubst
      show Ty.optionType (elementType.act someSubst) =
           Ty.optionType (elementType.subst someSubst)
      rw [elementIH someSubst]
  | eitherType leftType rightType leftIH rightIH =>
      intro someSubst
      show Ty.eitherType (leftType.act someSubst) (rightType.act someSubst) =
           Ty.eitherType (leftType.subst someSubst) (rightType.subst someSubst)
      rw [leftIH someSubst, rightIH someSubst]
  | «universe» universeLevel levelLe => intro _; rfl
  | empty => intro _; rfl
  | interval => intro _; rfl
  | path carrier leftEndpoint rightEndpoint carrierIH =>
      intro someSubst
      show Ty.path (carrier.act someSubst)
                   (RawTerm.act leftEndpoint someSubst)
                   (RawTerm.act rightEndpoint someSubst) =
           Ty.path (carrier.subst someSubst)
                   (leftEndpoint.subst someSubst.forRaw)
                   (rightEndpoint.subst someSubst.forRaw)
      rw [carrierIH someSubst,
          RawTerm.act_eq_subst_forRaw leftEndpoint someSubst,
          RawTerm.act_eq_subst_forRaw rightEndpoint someSubst]
  | glue baseType boundaryWitness baseIH =>
      intro someSubst
      show Ty.glue (baseType.act someSubst)
                   (RawTerm.act boundaryWitness someSubst) =
           Ty.glue (baseType.subst someSubst)
                   (boundaryWitness.subst someSubst.forRaw)
      rw [baseIH someSubst,
          RawTerm.act_eq_subst_forRaw boundaryWitness someSubst]
  | oeq carrier leftEndpoint rightEndpoint carrierIH =>
      intro someSubst
      show Ty.oeq (carrier.act someSubst)
                  (RawTerm.act leftEndpoint someSubst)
                  (RawTerm.act rightEndpoint someSubst) =
           Ty.oeq (carrier.subst someSubst)
                  (leftEndpoint.subst someSubst.forRaw)
                  (rightEndpoint.subst someSubst.forRaw)
      rw [carrierIH someSubst,
          RawTerm.act_eq_subst_forRaw leftEndpoint someSubst,
          RawTerm.act_eq_subst_forRaw rightEndpoint someSubst]
  | idStrict carrier leftEndpoint rightEndpoint carrierIH =>
      intro someSubst
      show Ty.idStrict (carrier.act someSubst)
                       (RawTerm.act leftEndpoint someSubst)
                       (RawTerm.act rightEndpoint someSubst) =
           Ty.idStrict (carrier.subst someSubst)
                       (leftEndpoint.subst someSubst.forRaw)
                       (rightEndpoint.subst someSubst.forRaw)
      rw [carrierIH someSubst,
          RawTerm.act_eq_subst_forRaw leftEndpoint someSubst,
          RawTerm.act_eq_subst_forRaw rightEndpoint someSubst]
  | equiv domainType codomainType domainIH codomainIH =>
      intro someSubst
      show Ty.equiv (domainType.act someSubst) (codomainType.act someSubst) =
           Ty.equiv (domainType.subst someSubst) (codomainType.subst someSubst)
      rw [domainIH someSubst, codomainIH someSubst]
  | refine baseType predicate baseIH =>
      intro someSubst
      show Ty.refine (baseType.act someSubst)
                     (RawTerm.act predicate (Action.liftForRaw someSubst)) =
           Ty.refine (baseType.subst someSubst)
                     (predicate.subst someSubst.forRaw.lift)
      rw [baseIH someSubst,
          RawTerm.act_eq_subst_forRaw predicate (Action.liftForRaw someSubst)]
      rfl
  | record singleFieldType singleFieldIH =>
      intro someSubst
      show Ty.record (singleFieldType.act someSubst) =
           Ty.record (singleFieldType.subst someSubst)
      rw [singleFieldIH someSubst]
  | codata stateType outputType stateIH outputIH =>
      intro someSubst
      show Ty.codata (stateType.act someSubst) (outputType.act someSubst) =
           Ty.codata (stateType.subst someSubst) (outputType.subst someSubst)
      rw [stateIH someSubst, outputIH someSubst]
  | session protocolStep =>
      intro someSubst
      show Ty.session (RawTerm.act protocolStep someSubst) =
           Ty.session (protocolStep.subst someSubst.forRaw)
      rw [RawTerm.act_eq_subst_forRaw protocolStep someSubst]
  | effect carrierType effectTag carrierIH =>
      intro someSubst
      show Ty.effect (carrierType.act someSubst)
                     (RawTerm.act effectTag someSubst) =
           Ty.effect (carrierType.subst someSubst)
                     (effectTag.subst someSubst.forRaw)
      rw [carrierIH someSubst,
          RawTerm.act_eq_subst_forRaw effectTag someSubst]
  | modal modalityTag carrierType carrierIH =>
      intro someSubst
      show Ty.modal modalityTag (carrierType.act someSubst) =
           Ty.modal modalityTag (carrierType.subst someSubst)
      rw [carrierIH someSubst]

-- ============================================================
-- Section 3: Bridge — Ty.act over RawRenaming.weaken equals Ty.weaken
-- ============================================================

/-- Bridge theorem: applying `Ty.act` over the canonical
shift-by-one renaming (`RawRenaming.weaken`) produces the same result
as `Ty.weaken`.  One-line corollary of `Ty.act_eq_rename` after
unfolding the `@[reducible]` definition `Ty.weaken t = t.rename
RawRenaming.weaken`. -/
theorem Ty.act_eq_weaken {level scope : Nat} (someTy : Ty level scope) :
    Ty.act someTy (RawRenaming.weaken : RawRenaming scope (scope + 1)) =
      Ty.weaken someTy :=
  Ty.act_eq_rename someTy RawRenaming.weaken

-- ============================================================
-- Section 4: Per-ctor specialisations on Subst (5 representative ctors)
-- ============================================================
-- These are the per-ctor smokes the brief calls for: definitional
-- equality of Ty.act and Ty.subst on representative constructors.
-- Each is `rfl` because Ty.act and Ty.subst share the same recursive
-- call shape — only the variable arm and binder lifts differ, both
-- of which are definitionally equal under the Subst Action instance.

theorem Ty.act_subst_unit_def {level scope targetScope : Nat}
    (someSubst : Subst level scope targetScope) :
    (Ty.unit : Ty level scope).act someSubst = Ty.unit.subst someSubst := rfl

theorem Ty.act_subst_arrow_def {level scope targetScope : Nat}
    (someSubst : Subst level scope targetScope)
    (domainType codomainType : Ty level scope) :
    (Ty.arrow domainType codomainType).act someSubst =
      Ty.arrow (domainType.act someSubst) (codomainType.act someSubst) := rfl

theorem Ty.act_subst_piTy_def {level scope targetScope : Nat}
    (someSubst : Subst level scope targetScope)
    (domainType : Ty level scope)
    (codomainType : Ty level (scope + 1)) :
    (Ty.piTy domainType codomainType).act someSubst =
      Ty.piTy (domainType.act someSubst)
              (codomainType.act (Action.liftForTy someSubst)) := rfl

theorem Ty.act_subst_id_def {level scope targetScope : Nat}
    (someSubst : Subst level scope targetScope)
    (carrier : Ty level scope)
    (leftEndpoint rightEndpoint : RawTerm scope) :
    (Ty.id carrier leftEndpoint rightEndpoint).act someSubst =
      Ty.id (carrier.act someSubst)
            (ActsOnRawTerm.actOnRawTerm someSubst leftEndpoint)
            (ActsOnRawTerm.actOnRawTerm someSubst rightEndpoint) := rfl

theorem Ty.act_subst_universe_def {level scope targetScope : Nat}
    (someSubst : Subst level scope targetScope)
    (universeLevel : UniverseLevel)
    (levelLe : universeLevel.toNat + 1 ≤ level) :
    (Ty.universe (scope := scope) universeLevel levelLe).act someSubst =
      Ty.universe universeLevel levelLe := rfl

end LeanFX2
