import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Omega.WalkingBunchedBimonoidPresentation

/-! # FX1PolyAudit.Polygraph.Omega.WalkingBunchedBimonoidPresentationAudit — zero-axiom gate for the walking
bunched bimonoid twenty-two-critical-pair Squier presentation (WP-BI r1, #2188).

Per-declaration `#assert_no_axioms` on the nine-label bunched signature, the two 1-generators and seven 2-cell
generators, the four bialgebra rows (incl. the tamed B1 4-strand delta-of-product with the middle swap), the
two (co)commutativity rows and the sigma-involution row (B1); the fifteen transported monoid-`m` / monoid-`a` /
comonoid-`a` legs, the twenty-two critical-pair rows, the base relation, the assembled per-pair resolutions and
the coherent-presentation bundle, the least-congruence UP and the twenty-two-row census (B2); the decision
ledger (multiplicative Delta-transport / additive Mat(N) r2 / mixed alternating-block clean) and the named
walls (B3); the Frobenius-distinction self-attack — the four-count is UNSOUND over the bialgebra congruence,
`BI != Frobenius` — and the grade-algebra / matrix-PROP tie-in markers (B4).

Independent `#print axioms` (NOT fuel-based, MEMORY: mandatory) on the coherent-presentation bundle and both
Frobenius-distinction witnesses closes the `#assert_no_axioms` gate. -/

namespace FX1PolyAudit


#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBIGenLabel
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidLabelTag
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidLabelBeq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidOmegaComputad
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidOmegaModeBeq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidOmegaGenBeq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidPoint
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAdditiveGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidIdOne
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAaWord
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMmWord
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMuGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddEtaGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddDeltaGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddEpsGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddSigmaGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMuGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultEtaGen
#assert_no_axioms FX1Poly.Polygraph.Omega.allBunchedBimonoidGenLabels
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidGeneratorLabelCountIsNine
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidDeltaTensorDelta
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMiddleSwap
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMuTensorMu
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductRightLeg_boundarySource
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductRightLeg_boundaryTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductLeftLeg_boundarySource
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductLeftLeg_boundaryTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraCounitLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraCounitRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraCounitLeftLeg_boundaryTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraCounitRightLeg_boundaryTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraUnitLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraUnitRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraUnitLeftLeg_boundaryTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraUnitRightLeg_boundaryTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraBoneLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraBoneRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraBoneLeftLeg_boundaryTarget
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCommutativityLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCommutativityRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCocommutativityLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCocommutativityRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidSigmaInvolutionLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidSigmaInvolutionRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraCounitLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraUnitLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraBoneLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCommutativityLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCocommutativityLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidSigmaInvolutionLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidSwapGen_notIdentity
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidColours_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_bialgebraRowsTypeCheckOnConcreteWords
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_swapSymmetryLawProbed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadUnitUnitLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadUnitUnitRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadLeftUnitAssocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadLeftUnitAssocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadRightUnitAssocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadRightUnitAssocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadPentagonLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadPentagonRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadRootUnitAssocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadRootUnitAssocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadUnitUnitLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadUnitUnitRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadLeftUnitAssocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadLeftUnitAssocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadRightUnitAssocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadRightUnitAssocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadPentagonLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadPentagonRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadRootUnitAssocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadRootUnitAssocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidCounitCounitLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidCounitCounitRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidLeftCounitCoassocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidLeftCounitCoassocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidRightCounitCoassocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidRightCounitCoassocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidCopentagonLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidCopentagonRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidRootCounitCoassocLeftLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidRootCounitCoassocRightLeg
#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBimonoidCriticalRow
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidOmegaBaseRel
#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBimonoidCriticalPairResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidResolveRow
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadUnitUnitResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadLeftUnitAssocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadRightUnitAssocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadPentagonResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadRootUnitAssocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadUnitUnitResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadLeftUnitAssocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadRightUnitAssocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadPentagonResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAddMonadRootUnitAssocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidCounitCounitResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidLeftCounitCoassocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidRightCounitCoassocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidCopentagonResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidRootCounitCoassocResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraCounitResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraUnitResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraBoneResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCommutativityResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCocommutativityResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidSigmaInvolutionResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBimonoidWalkerCoherentPresentationStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidWalkerCoherentPresentation
#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBimonoidSevenNewRowsResolvedStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidSevenNewRowsResolved
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCriticalPairsIdentifiedInEveryModel
#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBimonoidCriticalPairLabel
#assert_no_axioms FX1Poly.Polygraph.Omega.allBunchedBimonoidCriticalPairs
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidCriticalPairCountIsTwentyTwo
#assert_no_axioms FX1Poly.Polygraph.Omega.allBunchedBimonoidNewRows
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidNewRowCountIsSeven
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidMultMonadUnitUnitLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidComonoidCopentagonLegs_distinct
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_twentyTwoCriticalPairsShipped
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_bialgebraMiddleSwapRowIsTheStar
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_multiplicativeDecisionIsMonotoneMapsDelta
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_additiveDecisionIsMatNat
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_additiveConvergentNormalizerReached
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_mixedDecisionIsAlternatingBlockAmalgam
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_oneCellDecisionIsFreeMonoidLiteralEquality
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_yangBaxterHexagonReached
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_sigmaNaturalityRowsShipped
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_fullHomotopyBasisReached
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidFourAdd
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidLabelFourTag
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidGeneratorFourCount
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductLeftLeg_fourCount
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBialgebraProductRightLeg_fourCount
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedFourCountUnsoundForBialgebra
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidFrobeniusFourCountBreaksOnBialgebra
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_frobeniusFourCountUnsoundHere
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_biNotEqualFrobenius
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_gradeAlgebraTieInNamed
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_matrixPropCorrespondenceNamedForTable

-- Independent confirmation (not fuel-based): the load-bearing bundle + the B4 self-attack are axiom-free.
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidWalkerCoherentPresentation
#print axioms FX1Poly.Polygraph.Omega.bunchedFourCountUnsoundForBialgebra
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidFrobeniusFourCountBreaksOnBialgebra

end FX1PolyAudit
