import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Omega.WalkingBunchedBimonoidBracketMagmaSemantics

/-! # FX1PolyAudit.Polygraph.Omega.WalkingBunchedBimonoidBracketMagmaSemanticsAudit — zero-axiom gate for the bracket-magma (free commutative unital magma) semantics: the canonical tree carrier, the association-order separation, the shape invariant, and the composability-gated absorber of the FULL unital star scope. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBimonoidBracketTree
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketNatCompare
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketOrderingFlip
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTreeCompare
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketNatCompareFlip
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketNatCompareEqExtract
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTreeCompareFlip
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTreeCompareEqExtract
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketOrderedPair
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketMul
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketMulUnitRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketOrderedPairComm
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketMulComm
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGet
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTruncPad
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTruncPadLength
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketNatEqOfBeq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketNilOfLengthZero
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketAppendNil
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketAppendAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTakeAppendDrop
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTakeAppendLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketDropAppendLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTakeNil
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketDropNil
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketLengthAppend
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTakeLengthAdd
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketDropLengthAdd
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTakeAddSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketDropAddSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.BunchedBimonoidBracketCarrier
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketWordWidthAt
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGenRaw
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGenEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketIdEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketVcompEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketWhiskerLeftEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketWhiskerRightEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidLeftAssocCell
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidRightAssocCell
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketThreeVars
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidLeftAssocBracketValue
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidRightAssocBracketValue
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketShapeStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketShape
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketTakeAppendOfLength
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketDropAppendOfLength
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketCleanVcompSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketCleanVcompJoin
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketAgree
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedEq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketAgreeRefl
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketAgreeSymm
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketAgreeTrans
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketCleanVcompIffLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketCleanVcompIffRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedVcompAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedVcompUnitLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedVcompUnitRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerLeftUnit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerRightUnit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerLeftFunctorial
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerRightFunctorial
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedInterchange
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerAssocLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerAssocRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerLeftRightCommute
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedVcompCongrLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedVcompCongrRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerLeftCongr
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerRightCongr
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedIdCongr
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerLeftWhiskerCongr
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedWhiskerRightWhiskerCongr
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedAbsorbsUnitalScope
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedEqOfUnitalConv
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_bracketMagmaAbsorberShipped

-- Independent (non-fuel) axiom prints on the spine.
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketMulComm
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketEval
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketShape
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidLeftAssocBracketValue
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidRightAssocBracketValue
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedAbsorbsUnitalScope
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidBracketGatedEqOfUnitalConv

end FX1PolyAudit
