import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Omega.WalkingBunchedBimonoidAffineOffsetSemantics

/-! # FX1PolyAudit.Polygraph.Omega.WalkingBunchedBimonoidAffineOffsetSemanticsAudit — zero-axiom gate for the affine-offset (unit-path-augmented) matrix semantics, its structural invariants (shape, boundary dims, headedness), the pointed-tensor algebra (bridges, identity, multiplicativity, associativity), and the composability-gated absorber over the FULL star scope (WP-PROP r30). -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBeqZeroLeftFalseOfPos
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBeqZeroRightFalseOfPos
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugNatListGetBeyond
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugRowListGetBeyond
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugCanonicalWellFormed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugCanonicalEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugEntryBeyondRow
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugEntryBeyondCol
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugAddRightCancel
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugAddLeftCancel
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugLeOfAddLeAddLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugShiftedDeltaCollapseHit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugShiftedDeltaCollapseMissLow
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugShiftedDeltaCollapseMissHigh
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGenSeed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugTruncPad
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRightEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugGen
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugId
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugVcomp
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugWhiskerLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugWhiskerRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugCell
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugWordWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugAddMuGenValue
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugUnitIntoMuValue
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugIdentityCellValue
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftEntryHeader
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftEntryWire
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftEntryBlockOffset
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftEntryBlockWireCol
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftEntryBlockBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRightEntryBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRightEntryBlockPad
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRightEntryWire
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugTruncPadEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftRead
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRightRead
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugAndSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugAndJoin
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugComposableBool
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugCleanCell
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugCleanLowStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugCleanLow
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugCleanOneCell
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugMatMulWellFormed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugIdentityMatWellFormed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugTruncPadWellFormed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftWellFormed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRightWellFormed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugShapedStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugCellShaped
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugWellFormedEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBoundaryDimsStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBoundaryDims
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugRowsEq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugColsEq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugRowsPos
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugColsPos
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugHeadedMat
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugHeadedStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGenSeedHeaded
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugCellHeaded
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugHeadedEval
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugMatEqOfPointwise
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugDeltaEqOne
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugDeltaNeZero
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBeqShiftCancelRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBeqShiftCancelLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedIndexSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugIndexSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedContractionSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugSumRangeZero
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBeqSymm
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugSuccPredOfPos
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugIdentityHeaded
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensor
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorWellFormed
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorRead
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorEntryTop
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorEntryTopPad
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorEntryBottomOffset
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorEntryBottomZero
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorEntryBottomBlock
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugBlockLocalSub
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftAsTensor
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedRightAsTensor
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorIdentity
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugSuccLtOfLtPred
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugSuccAddShuffle
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugWireBlockIndex
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugHeadPeelShape
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorMulTopEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorMulBottomEntry
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorMul
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugShiftSubOne
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugCleanGate
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedEq
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedVcompAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedVcompUnitLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedVcompUnitRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedWhiskerLeftUnit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedWhiskerRightUnit
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedWhiskerLeftFunctorial
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedWhiskerRightFunctorial
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedInterchange
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedWhiskerAssocLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedWhiskerAssocRight
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedWhiskerLeftRightCommute
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedAbsorbsStarScope
#assert_no_axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedEqOfStarConv
#assert_no_axioms FX1Poly.Polygraph.Omega.fxBunchedBimonoid_affineOffsetAbsorberShipped

-- Independent (non-fuel) axiom prints on the spine.
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidEvalAugCell
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedAbsorbsStarScope
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugGatedEqOfStarConv
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorMul
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedTensorAssoc
#print axioms FX1Poly.Polygraph.Omega.bunchedBimonoidAugPointedLeftAsTensor

end FX1PolyAudit
