import FX1PolyAudit.DependencyAudit
import FX1Poly.Typed.Engine.Union.HasTypeUnionSubstitution

/-! # FX1PolyAudit.Typed.Engine.Union.HasTypeUnionSubstitution — zero-axiom gate (mirror shard, region-D restructure) -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Typed.gradedBinderChecks_subst_lift
#assert_no_axioms FX1Poly.Typed.subjectUsabilityPreservedUnderSubst
#assert_no_axioms FX1Poly.Typed.HasTypeUnion.substRespectingContext
#assert_no_axioms FX1Poly.Typed.HasTypeUnion.substPairUnderTwoBindings
#assert_no_axioms FX1Poly.Typed.HasTypeUnion.substPairNonDependent
#assert_no_axioms FX1Poly.Typed.natElimRecursiveCallUnionTyped
#assert_no_axioms FX1Poly.Typed.natRecRecursiveCallUnionTyped
#assert_no_axioms FX1Poly.Typed.natElimSuccIotaComputesTypedInUnion
#assert_no_axioms FX1Poly.Typed.natRecSuccIotaComputesTypedInUnion
#assert_no_axioms FX1Poly.Typed.NativeUnionSubstitutionCoverage
#assert_no_axioms FX1Poly.Typed.nativeUnionSubstitutionCoverageWitness
#assert_no_axioms FX1Poly.Typed.substRespectsModalityUnderConsLift
#assert_no_axioms FX1Poly.Typed.substRespectsModalityUnderLockConsLift
#assert_no_axioms FX1Poly.Typed.subjectUsabilityPreservedUnderSubstConsLift
#assert_no_axioms FX1Poly.Typed.subjectUsabilityPreservedUnderSubstLockConsLift
#assert_no_axioms FX1Poly.Typed.IntroRule.obligationsUsable_pushSubst
-- ★ A1-CONJUNCT-WIRE (#1829): the elim / formation use-site usability substitution pushes + the consTwice lift.
#assert_no_axioms FX1Poly.Typed.subjectUsabilityPreservedUnderSubstConsTwiceLift
#assert_no_axioms FX1Poly.Typed.ElimRule.obligationsUsable_pushSubst
#assert_no_axioms FX1Poly.Typed.flatFormationObligations_usable_pushSubst
#assert_no_axioms FX1Poly.Typed.termIndexedEndpointObligations_usable_pushSubst
#assert_no_axioms FX1Poly.Typed.cumulativeFormationObligations_usable_pushSubst
#assert_no_axioms FX1Poly.Typed.FormationRule.obligationsUsable_pushSubst

end FX1PolyAudit
