import LeanFX2.Tools.DependencyAudit

/-! # Tools/AuditGen — namespace-level fail-fast audit command

`#audit_namespace LeanFX2.Graded` walks declarations currently loaded
under that namespace and applies the same check as `#assert_no_axioms`
to each auditable constant.  It is a command-time gate, not a text
generator; use it in temporary audit files or during local development
to find leaking declarations quickly.
-/

namespace LeanFX2.Tools

open Lean Elab Command

/-- Is `candidateName` inside `namespaceName` or equal to it? -/
def Name.isWithinNamespace (namespaceName candidateName : Name) : Bool :=
  namespaceName == candidateName || namespaceName.isPrefixOf candidateName

/-- Constants generated by the compiler or audit tooling are not kernel
targets for namespace sweeps. -/
def isGeneratedOrToolingName (candidateName : Name) : Bool :=
  let renderedName := candidateName.toString
  candidateName.isInternal ||
  (`LeanFX2.Tools).isPrefixOf candidateName ||
  (`LeanFX2.Smoke).isPrefixOf candidateName ||
  renderedName.endsWith ".injEq" ||
  renderedName.endsWith ".noConfusion" ||
  renderedName.endsWith ".noConfusionType" ||
  renderedName.endsWith ".sizeOf_spec" ||
  renderedName.endsWith ".repr" ||
  renderedName.contains ".instRepr"

/-- Only declarations with user-facing dependency bodies are audited by
namespace sweeps.  Constructors and recursors are reached through their
own inductive declarations. -/
def isNamespaceAuditTarget (constantInfo : ConstantInfo) : Bool :=
  match constantInfo with
  | .axiomInfo _ => true
  | .thmInfo _ => true
  | .defnInfo _ => true
  | .inductInfo _ => true
  | .opaqueInfo _ => true
  | .ctorInfo _ => false
  | .recInfo _ => false
  | .quotInfo _ => true

/-- Names in the current environment that should be checked for a
namespace-level audit. -/
def namespaceAuditTargets
    (environment : Environment)
    (namespaceName : Name) :
    Array Name :=
  environment.constants.toList.foldl
    (init := #[])
    (fun targetNames (constantName, constantInfo) =>
      if Name.isWithinNamespace namespaceName constantName &&
          !isGeneratedOrToolingName constantName &&
          isNamespaceAuditTarget constantInfo then
        targetNames.push constantName
      else
        targetNames)

/-- Audit every loaded declaration under a namespace, failing at the
first axiom leak. -/
elab "#audit_namespace " namespaceSyntax:ident : command => do
  let environment ← getEnv
  let namespaceName := namespaceSyntax.getId
  let targetNames := namespaceAuditTargets environment namespaceName
  for targetName in targetNames do
    let stats := computeStats environment targetName (includeStdlib := true)
    if !stats.axiomNames.isEmpty then
      throwError
        "namespace axiom audit failed for {targetName}: {stats.axiomNames.size} axiom(s): {formatNameList stats.axiomNames}"
  logInfo m!"namespace axiom audit ok: {namespaceName} ({targetNames.size} declarations)"

/-- Compatibility spelling for the planned generator command. -/
elab "#auditgen " namespaceSyntax:ident : command => do
  let environment ← getEnv
  let namespaceName := namespaceSyntax.getId
  let targetNames := namespaceAuditTargets environment namespaceName
  for targetName in targetNames do
    let stats := computeStats environment targetName (includeStdlib := true)
    if !stats.axiomNames.isEmpty then
      throwError
        "namespace axiom audit failed for {targetName}: {stats.axiomNames.size} axiom(s): {formatNameList stats.axiomNames}"
  logInfo m!"namespace axiom audit ok: {namespaceName} ({targetNames.size} declarations)"

end LeanFX2.Tools
