import FX1PolyAudit.DependencyAudit
import FX1Poly.Typed.Metatheory.SubjectReduction.HasTypeUnionTermIndexedFormationCongruence

/-! # FX1PolyAudit.Typed.Metatheory.SubjectReduction.HasTypeUnionTermIndexedFormationCongruence — zero-axiom gate (mirror shard, region-D restructure) -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Typed.termIndexedEndpointObligationsHoldAfter
#assert_no_axioms FX1Poly.Typed.termIndexedEndpointObligationsHoldUnderCarrierConv
#assert_no_axioms FX1Poly.Typed.termIndexedFormationPremisesHoldAfter
#assert_no_axioms FX1Poly.Typed.termIndexedEndpointObligationsHoldAfterWf
#assert_no_axioms FX1Poly.Typed.termIndexedFormationPremisesHoldAfterWf

end FX1PolyAudit
