import LeanFX2.Modal.TwoCell

/-! # Modal/TwoCellLaws — coherence laws for `TwoCell` (D4.0b, tracker #1700)

The 2-cell inductive `LeanFX2.TwoCell` (shipped in `Modal/TwoCell.lean`,
D4.0a #1699) is freely generated by three constructors:

* `TwoCell.refl`  — identity 2-cell
* `TwoCell.vert`  — vertical composition
* `TwoCell.horiz` — horizontal composition (whiskering)

In a strict 2-category, `vert` is associative, `refl` is its
two-sided unit, and `vert` / `horiz` satisfy the middle-four
exchange (Eckmann–Hilton) law.  These four equations are the
"coherence laws" of the 2-categorical structure.

## Why the laws are NOT Lean propositional equalities on the free inductive

`TwoCell.vert` is a Lean inductive constructor.  Two constructor
applications are propositionally equal in Lean's kernel iff their
ctor heads agree AND their arguments agree pointwise.  Hence:

* `(α ⊞ β) ⊞ γ` and `α ⊞ (β ⊞ γ)` have the SAME source/target
  1-cells (so they are equality-comparable), but their underlying
  inductive terms differ structurally — one nests `vert` to the
  left, the other to the right.
* `(refl ⊞ α)` has head `vert`; `α` may have a different head
  (e.g. `refl` or `horiz`).  So `refl ⊞ α = α` cannot be `rfl`.

Per `WORKING_RULES.md` Discipline #15 (cumulativity is a Conv
rule, not a Ty constructor; symmetrically, structural equations
on freely-generated inductives go via an explicit equivalence
relation, NOT via Lean `=`), and per `CLAUDE.md` Forbidden
reasoning patterns (NO `axiom`, NO hypothesis-as-postulate, NO
`Inhabited` for unconstructible types), the four coherence laws
ship as theorems WRT an explicit equivalence relation `TwoCellEq`
defined in this file.

`TwoCellEq` is the smallest congruence on `TwoCell` containing
the four coherence laws.  Its constructors are pieces of
inductive data — Lean's strict-positivity check makes the whole
inductive zero-axiom by construction (the same way `Eq.refl` is
zero-axiom — it's a constructor, not an axiom).

This is the standard formalization route in HoTT / cubical
treatments of 2-categories.  The full bicategorical setting (in
which `vert` is associative up to an invertible 3-cell, etc.)
is OUT OF SCOPE for the Day 4 modal layer; the Day 4 unblock
needs the strict-2-category laws as propositional equivalences,
which is exactly what `TwoCellEq` provides.

## What ships here (D4.0b, this atom — #1700)

* `TwoCellEq` — inductive equivalence relation on `TwoCell`,
  closed under reflexivity, symmetry, transitivity, and
  congruence with respect to `TwoCell.vert` and `TwoCell.horiz`.
  The four coherence laws (`vertAssoc`, `vertLeftId`,
  `vertRightId`, `exchange`) are constructors of this inductive,
  which makes them axiom-free pieces of data per Lean 4's
  strict-positivity check (no `axiom` declaration; the
  inductive's consistency is justified by the same mechanism
  that justifies `Eq.refl`).
* `TwoCell.vertAssoc` — theorem: vertical composition is
  associative up to `TwoCellEq`.
* `TwoCell.vertLeftId` — theorem: `refl` is left identity for
  `vert` up to `TwoCellEq`.
* `TwoCell.vertRightId` — theorem: `refl` is right identity for
  `vert` up to `TwoCellEq`.
* `TwoCell.exchange` — theorem: middle-four exchange law
  relating `vert` and `horiz`, up to `TwoCellEq`.

Each theorem body invokes the corresponding `TwoCellEq`
constructor — they are real theorems with bodies, NOT
hypothesis-as-postulate, NOT `axiom`, NOT `sorry`.

## Why this discharges the Day 4 unblock

The downstream consumers (`Modal/Adjunction.lean`,
`Modal/BoxPath.lean`, `Modal/Cohesive.lean`, `Modal/Bridge.lean`,
`Modal/2LTT.lean`) need to express the unit and counit of the
adjoint chain `♭ ⊣ ◇ ⊣ □ ⊣ ♯` as 2-cells satisfying triangle
identities.  Triangle identities are equational statements about
2-cells; in a free 2-cell setting they hold WRT `TwoCellEq` (not
WRT Lean `=`), which is precisely what this atom delivers.

The strict-2-category interpretation downstream typeclasses can
expect is captured by the `TwoCellEq` equivalence: any
`TwoCellEq`-respecting downstream construction (e.g. functorial
interpretation `Modality m1 m2 → Ty m1 → Ty m2` factoring
through `TwoCellEq`-classes) sees vertical composition as
genuinely associative and `refl` as a genuine two-sided unit.

## Zero-axiom commitment

Per `CLAUDE.md` "Zero-axiom commitment — ABSOLUTE": every
shipped declaration in this file is verified by
`#assert_no_axioms` and a corresponding `#print axioms` smoke
audit.  No `axiom`, `sorry`, `admit`, `noncomputable`,
`Classical.*`, `propext`, or `Quot.sound` appears in the
transitive dependency closure.  The `TwoCellEq` inductive
itself is zero-axiom by Lean 4's strict-positivity check on
inductive declarations — the same justification that makes
`Eq.refl`, `True.intro`, `Nat.zero` zero-axiom.

## Match-compiler hygiene

Per `WORKING_RULES.md` Discipline #2 (wildcards always leak
propext), no theorem in this file pattern-matches with a
wildcard arm.  The four lemma bodies are direct constructor
invocations — no `match`, no `cases`, no `induction`.

## Root status

* Layer: kernel
* Load-bearing for: `Modal/Adjunction.lean` (D4.2 #1329),
  `Modal/BoxPath.lean` (D4.3 #1330), `Modal/Cohesive.lean`
  (D4.4 #1331), `Modal/Bridge.lean` (D4.6 #1333),
  `Modal/2LTT.lean` (D4.8 #1335), and the cohesive adjoint
  chain `♭ ⊣ ◇ ⊣ □ ⊣ ♯` (D4.5 #1332).
* Axiom budget: zero (verified via `#assert_no_axioms` in
  `Tools/AuditAll/AuditModalTwoCell.lean`).
-/

namespace LeanFX2

/-- `TwoCellEq firstCell secondCell` is the equational equivalence
relation on `TwoCell` that quotients by the four strict-2-category
coherence laws (vertical associativity, two-sided vertical
identity, middle-four exchange).

This is an inductive `Prop` whose constructors carry:

1. The reflexivity / symmetry / transitivity scaffolding required
   for `TwoCellEq` to be a genuine equivalence relation.
2. Congruence with respect to `TwoCell.vert` and `TwoCell.horiz`,
   so that the equivalence respects both compositions.
3. The four strict-2-category coherence laws as data
   constructors (`vertAssoc`, `vertLeftId`, `vertRightId`,
   `exchange`).

Per `CLAUDE.md` zero-axiom commitment, this inductive's
constructors are pieces of inductive data — Lean 4's
strict-positivity check makes the declaration consistent without
appealing to any axiom (same mechanism that makes `Eq.refl`
consistent).  No `axiom`, no `sorry`, no `Inhabited`, no
hypothesis-as-postulate.

The relation is restricted to the same source/target 1-cells
(both `firstCell` and `secondCell` have the same
`TwoCell modSource modTarget` type) — an equivalence relation on
parallel 2-cells is the correct notion in a strict 2-category. -/
inductive TwoCellEq : ∀ {sourceMode targetMode : Mode}
    {sourceModality targetModality :
        Modality sourceMode targetMode},
    TwoCell sourceModality targetModality →
    TwoCell sourceModality targetModality → Prop
  /-- Reflexivity: every 2-cell is `TwoCellEq`-related to itself. -/
  | reflEq {sourceMode targetMode : Mode}
      {sourceModality targetModality :
          Modality sourceMode targetMode}
      (someCell : TwoCell sourceModality targetModality) :
      TwoCellEq someCell someCell
  /-- Symmetry: if `firstCell` and `secondCell` are equivalent,
  so are `secondCell` and `firstCell`. -/
  | symmEq {sourceMode targetMode : Mode}
      {sourceModality targetModality :
          Modality sourceMode targetMode}
      {firstCell secondCell :
          TwoCell sourceModality targetModality}
      (firstEqSecond : TwoCellEq firstCell secondCell) :
      TwoCellEq secondCell firstCell
  /-- Transitivity: `TwoCellEq` chains. -/
  | transEq {sourceMode targetMode : Mode}
      {sourceModality targetModality :
          Modality sourceMode targetMode}
      {firstCell secondCell thirdCell :
          TwoCell sourceModality targetModality}
      (firstEqSecond : TwoCellEq firstCell secondCell)
      (secondEqThird : TwoCellEq secondCell thirdCell) :
      TwoCellEq firstCell thirdCell
  /-- Congruence under vertical composition: `TwoCellEq` is
  preserved by `TwoCell.vert` on both sides. -/
  | vertCongEq {sourceMode targetMode : Mode}
      {modAlpha modBeta modGamma :
          Modality sourceMode targetMode}
      {firstCellLeft firstCellRight :
          TwoCell modAlpha modBeta}
      {secondCellLeft secondCellRight :
          TwoCell modBeta modGamma}
      (firstEq : TwoCellEq firstCellLeft firstCellRight)
      (secondEq : TwoCellEq secondCellLeft secondCellRight) :
      TwoCellEq (TwoCell.vert firstCellLeft secondCellLeft)
                (TwoCell.vert firstCellRight secondCellRight)
  /-- Congruence under horizontal composition (whiskering).
  Restricted to same-mode following `TwoCell.horiz`. -/
  | horizCongEq {someMode : Mode}
      {outerSource outerTarget :
          Modality someMode someMode}
      {innerSource innerTarget :
          Modality someMode someMode}
      {outerCellLeft outerCellRight :
          TwoCell outerSource outerTarget}
      {innerCellLeft innerCellRight :
          TwoCell innerSource innerTarget}
      (outerEq : TwoCellEq outerCellLeft outerCellRight)
      (innerEq : TwoCellEq innerCellLeft innerCellRight) :
      TwoCellEq (TwoCell.horiz outerCellLeft innerCellLeft)
                (TwoCell.horiz outerCellRight innerCellRight)
  /-- Coherence law: `vert` is associative.  This is the
  strict-2-category associativity for vertical composition. -/
  | vertAssocEq {sourceMode targetMode : Mode}
      {modAlpha modBeta modGamma modDelta :
          Modality sourceMode targetMode}
      (firstCell : TwoCell modAlpha modBeta)
      (secondCell : TwoCell modBeta modGamma)
      (thirdCell : TwoCell modGamma modDelta) :
      TwoCellEq
        (TwoCell.vert (TwoCell.vert firstCell secondCell)
                      thirdCell)
        (TwoCell.vert firstCell
                      (TwoCell.vert secondCell thirdCell))
  /-- Coherence law: `refl` is the left identity for `vert`. -/
  | vertLeftIdEq {sourceMode targetMode : Mode}
      {sourceModality targetModality :
          Modality sourceMode targetMode}
      (someCell : TwoCell sourceModality targetModality) :
      TwoCellEq
        (TwoCell.vert (TwoCell.refl sourceModality) someCell)
        someCell
  /-- Coherence law: `refl` is the right identity for `vert`. -/
  | vertRightIdEq {sourceMode targetMode : Mode}
      {sourceModality targetModality :
          Modality sourceMode targetMode}
      (someCell : TwoCell sourceModality targetModality) :
      TwoCellEq
        (TwoCell.vert someCell (TwoCell.refl targetModality))
        someCell
  /-- Coherence law: middle-four exchange relating `vert` and
  `horiz`.  In a strict 2-category, vertical composition of two
  horizontal composites equals the horizontal composition of two
  vertical composites: `(α₁ ⊠ β₁) ⊞ (α₂ ⊠ β₂)
  = (α₁ ⊞ α₂) ⊠ (β₁ ⊞ β₂)`.

  Restricted to same-mode (matching `TwoCell.horiz`'s same-mode
  signature in D4.0a #1699). -/
  | exchangeEq {someMode : Mode}
      {outerAlpha outerBeta outerGamma :
          Modality someMode someMode}
      {innerAlpha innerBeta innerGamma :
          Modality someMode someMode}
      (outerFirst : TwoCell outerAlpha outerBeta)
      (outerSecond : TwoCell outerBeta outerGamma)
      (innerFirst : TwoCell innerAlpha innerBeta)
      (innerSecond : TwoCell innerBeta innerGamma) :
      TwoCellEq
        (TwoCell.vert
          (TwoCell.horiz outerFirst innerFirst)
          (TwoCell.horiz outerSecond innerSecond))
        (TwoCell.horiz
          (TwoCell.vert outerFirst outerSecond)
          (TwoCell.vert innerFirst innerSecond))

namespace TwoCell

/-! ## The four coherence laws as theorems

Each theorem body invokes the corresponding `TwoCellEq`
constructor.  Each is a real theorem with a body — NOT a
hypothesis-as-postulate, NOT an `axiom`, NOT a `sorry`.  The
zero-axiom guarantee comes from Lean 4's strict-positivity
check on the `TwoCellEq` inductive (constructors are data, not
postulates).  Verified inline by `#assert_no_axioms` per decl
in `Tools/AuditAll/AuditModalTwoCell.lean`. -/

/-- Vertical composition is associative up to `TwoCellEq`:
`(α ⊞ β) ⊞ γ ≈ α ⊞ (β ⊞ γ)`.

Strict-2-category associativity for `vert`.  Per the file
docstring, this is NOT propositional Lean equality on the
freely-generated `TwoCell` (constructor terms differ
structurally) — it is equality up to the equivalence relation
`TwoCellEq` whose constructors are defined to enforce the
strict-2-category laws. -/
theorem vertAssoc {sourceMode targetMode : Mode}
    {modAlpha modBeta modGamma modDelta :
        Modality sourceMode targetMode}
    (firstCell : TwoCell modAlpha modBeta)
    (secondCell : TwoCell modBeta modGamma)
    (thirdCell : TwoCell modGamma modDelta) :
    TwoCellEq
      (TwoCell.vert (TwoCell.vert firstCell secondCell) thirdCell)
      (TwoCell.vert firstCell
                    (TwoCell.vert secondCell thirdCell)) :=
  TwoCellEq.vertAssocEq firstCell secondCell thirdCell

/-- `refl` is the left identity for vertical composition up to
`TwoCellEq`: `refl ⊞ α ≈ α`. -/
theorem vertLeftId {sourceMode targetMode : Mode}
    {sourceModality targetModality :
        Modality sourceMode targetMode}
    (someCell : TwoCell sourceModality targetModality) :
    TwoCellEq
      (TwoCell.vert (TwoCell.refl sourceModality) someCell)
      someCell :=
  TwoCellEq.vertLeftIdEq someCell

/-- `refl` is the right identity for vertical composition up to
`TwoCellEq`: `α ⊞ refl ≈ α`. -/
theorem vertRightId {sourceMode targetMode : Mode}
    {sourceModality targetModality :
        Modality sourceMode targetMode}
    (someCell : TwoCell sourceModality targetModality) :
    TwoCellEq
      (TwoCell.vert someCell (TwoCell.refl targetModality))
      someCell :=
  TwoCellEq.vertRightIdEq someCell

/-- Middle-four exchange relating vertical and horizontal
composition: `(α₁ ⊠ β₁) ⊞ (α₂ ⊠ β₂) ≈ (α₁ ⊞ α₂) ⊠ (β₁ ⊞ β₂)`,
restricted to same-mode (per `TwoCell.horiz`'s same-mode
signature in D4.0a #1699).  This is the Eckmann–Hilton-style
coherence between the two compositions in a strict 2-category. -/
theorem exchange {someMode : Mode}
    {outerAlpha outerBeta outerGamma :
        Modality someMode someMode}
    {innerAlpha innerBeta innerGamma :
        Modality someMode someMode}
    (outerFirst : TwoCell outerAlpha outerBeta)
    (outerSecond : TwoCell outerBeta outerGamma)
    (innerFirst : TwoCell innerAlpha innerBeta)
    (innerSecond : TwoCell innerBeta innerGamma) :
    TwoCellEq
      (TwoCell.vert
        (TwoCell.horiz outerFirst innerFirst)
        (TwoCell.horiz outerSecond innerSecond))
      (TwoCell.horiz
        (TwoCell.vert outerFirst outerSecond)
        (TwoCell.vert innerFirst innerSecond)) :=
  TwoCellEq.exchangeEq outerFirst outerSecond innerFirst innerSecond

end TwoCell

end LeanFX2
