import FX1PolyAudit.DependencyAudit
import FX1Poly.ComputerAlgebra.FloatingPoint.RadixScaledInteger

/-! # FX1PolyAudit/ComputerAlgebra/FloatingPoint/RadixScaledInteger — zero-axiom gate
    (FLOAT-2 brick 2)

Per-declaration zero-axiom gate for the RadixScaledInteger carrier: the Int
cancellation helpers, the cross-alignment relation with its decidability and refl/symm
laws, exact multiplication, and the rescaling-preserves-denotation theorem.  (The
`toNat` pins moved to the `Number/IntToNatCycle` gate with their declarations.)

Every declaration must be free of `propext`, `Quot.sound`, `Classical.choice`, `sorry`,
`native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.ComputerAlgebra.intAddNegSwapCancel
#assert_no_axioms FX1Poly.ComputerAlgebra.intSubSubSelfCancel
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.scaleGapToward
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.crossAlignedMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.DenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.decideDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.denotesSameAsRefl
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.denotesSameAsSymm
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.denotesSameAsTrans
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.agreesAtLowerScaleOfDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.denotesSameAsOfAgreesAtLowerScale
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.mulExact
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.mulExactMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.mulExactExponent
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.mulExactRespectsDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.shiftToLowerScale
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.shiftToLowerScalePreservesDenotation
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExact
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExactMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExactExponent
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExactComm
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExactZeroDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExactMantissaAtLowerScale
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExactRespectsDenotesSameAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.normalizeWithFuel
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.divideMantissaStepPreservesDenotation
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.normalizeWithFuelPreservesDenotation
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.IsNormalized
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.decideIsNormalized
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.normalizeWithFuelReachesNormalForm
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.normalizedRepresentativeExists
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.roundTowardZero
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.roundTowardZeroMantissa
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.roundTowardZeroExponent
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.roundTowardZeroPreservesDenotationOfTargetBelow
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.roundTowardZeroMagnitudeDecomposition
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.roundTowardZeroRemainderIsBounded
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.LessEqualAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.decideLessEqualAs
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.lessEqualAsRefl
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.lessEqualAsTotal
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.lessEqualAsOfDenotesSame
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.denotesSameAsOfLessEqualBoth
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.lessEqualAsTrans
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.lessEqualAsCongrLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.lessEqualAsCongrRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.boundedAtLowerScaleOfLessEqual
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.lessEqualAsOfBoundedAtLowerScale
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.addExactMonotone
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.mulExactComm
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.mulExactMonotoneLeft
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.mulExactMonotoneRight
#assert_no_axioms FX1Poly.ComputerAlgebra.RadixScaledInteger.roundTowardZeroIsBelowOfNonNegativeMantissa

end FX1PolyAudit
