import FX1Poly.Polygraph.TwoCategory.WalkingAdjunction.MonotoneMap
import FX1Poly.ComputerAlgebra.Semigroup.CommWordProblem

/-! # FX1Poly/Polygraph/Directed/SimplexWordProblem — the simplex-category (Δ) word problem

The simplex category **Δ** (equivalently, augmented Δ₊) is the category of monotone maps between finite
ordinals.  Its arrows are generated by the **face** injections `δ_i` and the **degeneracy** surjections `σ_i`,
subject to the five **simplicial identities**.  A *word* in these generators is an abstract composite; two words
denote the same monotone map iff their evaluated value-tables coincide.

This file ships that 1-categorical word problem END-TO-END, zero-axiom, reusing the already-verified Δ₊
value-list model in `WalkingAdjunction/MonotoneMap.lean` (`composeMap` / `faceMap` / `degenMap` / `idMap` and the
five `composeMap_*` simplicial-identity table equalities) and the `csw` order/list-equality kit in
`ComputerAlgebra/Semigroup/CommWordProblem.lean` (`cswLe` for the non-decreasing check, `cswListNatBeq` /
`cswListNatBeqEq` for the table decision).

## What is DECIDED (zero-axiom)

* **T1 — model + generators + words.**  A non-dependent `MonoMap` (domain/codomain dims + a `List Nat` value
  table); a Boolean `sdwWellFormed` (length, entry bound via `sdwEntriesBelow`, non-decreasing via a structural
  pairwise-`cswLe` fold `sdwNonDecreasing`); `sdwSimplexId` / `sdwSimplexCompose`; the face/degeneracy generator
  maps; a `SimplexWord` inductive (`idW` / `faceW` / `degenW` / `compW`) and `sdwEvaluate : SimplexWord → MonoMap`.
  `sdwEvaluateTableLength` proves table-length preservation for every word (the length half of well-formedness
  preservation, general over all words).

* **T2 — simplicial-identity soundness.**  A congruence `SimplexConv` closed under reflexivity/symmetry/
  transitivity/congruence, the category associativity + unit laws (with their `mapsInto` side-conditions), and the
  five simplicial identities (`σδ = id` at the same and the successor face, face-face, degeneracy-degeneracy, and
  the mixed lower commutation).  `sdwConvSound : SimplexConv w1 w2 → (sdwEvaluate w1).table = (sdwEvaluate w2).table`
  discharges every generating relation by the corresponding `composeMap_*` table equality.

* **T3 — the decision.**  `decideSimplexEq w1 w2 := cswListNatBeq (sdwEvaluate w1).table (sdwEvaluate w2).table`.
  `decideSimplexEq_ofSimplexConv` (convertible ⟹ decides `true`) and `sdwNotConv_ofDecideFalse` (distinct tables ⟹
  NOT convertible) are both zero-axiom, via `sdwConvSound` + `cswListNatBeqRefl` / `cswListNatBeqEq`.

## What is WALLED

* Eilenberg–Zilber **completeness** of the word problem (equal table ⟹ `SimplexConv`) — the unique
  surjection-then-injection factorization must be recovered from the arbitrary table and lifted back to a `Conv`
  path.  The existence half is shipped upstream (`composeMap_rankList_imageList`); the uniqueness/lift is the
  residual.  Marker `sdwHasEilenbergZilberCompleteness = false`.

* The deep ∞-categorical extension — **directed univalence / Segal–Rezk completeness** (Riehl–Shulman synthetic
  ∞-category theory).  `sdwHasDirectedUnivalence = false`, `sdwHasSegalCompleteness = false`.

Every declaration is free of `propext`, `Quot.sound`, `Classical.choice`, `sorry`, `native_decide`, `funext`,
`WellFounded.fix`, `omega`.  All `Nat` order facts route through the calibrated-clean `cswLe`; all list equality
routes through `cswListNatBeq`; all monotone-map algebra reuses the audited `MonotoneMap` value-list lemmas. -/

set_option autoImplicit false
set_option relaxedAutoImplicit false

open FX1Poly.ComputerAlgebra

namespace FX1Poly.Polygraph.Directed

/-! ## T1 — the model: `MonoMap`, well-formedness, generators, words -/

/-- A monotone map between finite ordinals as a NON-dependent record: the domain/codomain widths together with the
value table.  (The dependent, invariant-carrying `MonotoneMap` lives upstream; this bare record is what
`sdwEvaluate` targets so composition can thread the widths structurally.) -/
structure MonoMap where
  domainDim   : Nat
  codomainDim : Nat
  table       : List Nat

/-- Structural length of a value table (own recursion; no `List.length` order lemmas needed downstream). -/
def sdwLength : List Nat → Nat
  | []      => 0
  | _ :: rest => sdwLength rest + 1

/-- Every entry of the table is `< bound` (structural; reuses `cswLe` as `entry + 1 ≤ bound`, i.e. `entry < bound`
via the successor comparator). -/
def sdwEntriesBelow : List Nat → Nat → Bool
  | [],        _     => true
  | entry :: rest, bound => cswLe (entry + 1) bound && sdwEntriesBelow rest bound

/-- The table is non-decreasing: each adjacent pair satisfies `cswLe`.  This is the pairwise-`cswLe` fold the
directive prescribes — the monotone predicate, reusing the calibrated-clean `cswLe`, never a leaky order lemma. -/
def sdwNonDecreasing : List Nat → Bool
  | []            => true
  | _ :: []        => true
  | first :: second :: rest => cswLe first second && sdwNonDecreasing (second :: rest)

/-- A `MonoMap` is well-formed when its table has the declared length, lands in `[codomainDim]`, and is weakly
increasing. -/
def sdwWellFormed (mono : MonoMap) : Bool :=
  Nat.beq (sdwLength mono.table) mono.domainDim
    && sdwEntriesBelow mono.table mono.codomainDim
    && sdwNonDecreasing mono.table

/-- The identity monotone map on `[n]`. -/
def sdwSimplexId (n : Nat) : MonoMap := ⟨n, n, idMap n⟩

/-- Composition of monotone maps: `sdwSimplexCompose second first` is `second ∘ first` (apply `first` then
`second`), its table computed by the audited index-through `composeMap`. -/
def sdwSimplexCompose (second first : MonoMap) : MonoMap :=
  ⟨first.domainDim, second.codomainDim, composeMap first.table second.table⟩

/-- The face generator `δ_i : [n] → [n+1]` as a `MonoMap`. -/
def sdwFace (i n : Nat) : MonoMap := ⟨n, n + 1, faceMap i n⟩

/-- The degeneracy generator `σ_i : [n+1] → [n]` as a `MonoMap`. -/
def sdwDegen (i n : Nat) : MonoMap := ⟨n + 1, n, degenMap i n⟩

/-- Abstract words in the face/degeneracy generators. -/
inductive SimplexWord where
  | idW    (n : Nat)                     : SimplexWord
  | faceW  (i n : Nat)                   : SimplexWord
  | degenW (i n : Nat)                   : SimplexWord
  | compW  (second first : SimplexWord)  : SimplexWord

/-- Evaluate a word to its concrete monotone map. -/
def sdwEvaluate : SimplexWord → MonoMap
  | .idW n        => sdwSimplexId n
  | .faceW i n    => sdwFace i n
  | .degenW i n   => sdwDegen i n
  | .compW second first => sdwSimplexCompose (sdwEvaluate second) (sdwEvaluate first)

/-- ★ **Well-formedness preservation (length half), general over all words.**  Every evaluated word's table has
exactly `domainDim` entries — the length invariant threaded through `idMap` / `faceMap` / `degenMap` /
`composeMap`. -/
theorem sdwEvaluateTableLength : (word : SimplexWord) →
    (sdwEvaluate word).table.length = (sdwEvaluate word).domainDim
  | .idW n => by
      show (idMap n).length = n
      exact ascendingFrom_length 0 n
  | .faceW i n => faceMap_length i n
  | .degenW i n => degenMap_length i n
  | .compW second first => by
      show (composeMap (sdwEvaluate first).table (sdwEvaluate second).table).length
            = (sdwEvaluate first).domainDim
      rw [composeMap_length]
      exact sdwEvaluateTableLength first

/-! ## T2 — the congruence `SimplexConv` and its soundness -/

/-- The simplicial congruence on words: an equivalence closed under composition, the category associativity and
unit laws (with the `mapsInto` side-conditions the value-list model needs), and the five simplicial identities.
Each generating relation is a genuine equality of the evaluated value tables (`sdwConvSound`). -/
inductive SimplexConv : SimplexWord → SimplexWord → Prop where
  | refl (word : SimplexWord) : SimplexConv word word
  | symm {left right : SimplexWord} :
      SimplexConv left right → SimplexConv right left
  | trans {left middle right : SimplexWord} :
      SimplexConv left middle → SimplexConv middle right → SimplexConv left right
  | congComp {secondLeft secondRight firstLeft firstRight : SimplexWord} :
      SimplexConv secondLeft secondRight → SimplexConv firstLeft firstRight →
      SimplexConv (.compW secondLeft firstLeft) (.compW secondRight firstRight)
  | assocConv (outer middle inner : SimplexWord)
      (hrange : mapsInto (sdwEvaluate inner).table (sdwEvaluate middle).table.length) :
      SimplexConv (.compW (.compW outer middle) inner) (.compW outer (.compW middle inner))
  | idLeftConv (n : Nat) (word : SimplexWord)
      (hrange : mapsInto (sdwEvaluate word).table n) :
      SimplexConv (.compW (.idW n) word) word
  | idRightConv (n : Nat) (word : SimplexWord)
      (hlen : (sdwEvaluate word).table.length = n) :
      SimplexConv (.compW word (.idW n)) word
  | faceDegenSame (i n : Nat) :
      SimplexConv (.compW (.degenW i n) (.faceW i n)) (.idW n)
  | faceDegenSucc (i n : Nat) :
      SimplexConv (.compW (.degenW i n) (.faceW (i + 1) n)) (.idW n)
  | faceFace (i j n : Nat) (hij : i ≤ j) :
      SimplexConv (.compW (.faceW (j + 1) (n + 1)) (.faceW i n))
                  (.compW (.faceW i (n + 1)) (.faceW j n))
  | degenDegen (i j n : Nat) (hij : i ≤ j) (hjn : j < n) :
      SimplexConv (.compW (.degenW j n) (.degenW i (n + 1)))
                  (.compW (.degenW i n) (.degenW (j + 1) (n + 1)))
  | faceDegenLower (i j n : Nat) (hij : i ≤ j) (hjn : j < n) :
      SimplexConv (.compW (.degenW (j + 1) (n + 1)) (.faceW i (n + 1)))
                  (.compW (.faceW i n) (.degenW j n))

/-- ★ **Soundness of the simplicial congruence.**  Convertible words evaluate to the SAME monotone value table.
Each simplicial constructor is discharged by the matching audited `composeMap_*` identity. -/
theorem sdwConvSound : {left right : SimplexWord} →
    SimplexConv left right → (sdwEvaluate left).table = (sdwEvaluate right).table
  | _, _, .refl _ => rfl
  | _, _, .symm hConv => (sdwConvSound hConv).symm
  | _, _, .trans hLeft hRight => (sdwConvSound hLeft).trans (sdwConvSound hRight)
  | _, _, .congComp hSecond hFirst => by
      show composeMap (sdwEvaluate _).table (sdwEvaluate _).table
            = composeMap (sdwEvaluate _).table (sdwEvaluate _).table
      rw [sdwConvSound hFirst, sdwConvSound hSecond]
  | _, _, .assocConv outer middle inner hrange => by
      show composeMap (sdwEvaluate inner).table
              (composeMap (sdwEvaluate middle).table (sdwEvaluate outer).table)
            = composeMap (composeMap (sdwEvaluate inner).table (sdwEvaluate middle).table)
              (sdwEvaluate outer).table
      exact (composeMap_assoc (sdwEvaluate inner).table (sdwEvaluate middle).table
              (sdwEvaluate outer).table hrange).symm
  | _, _, .idLeftConv n word hrange => by
      show composeMap (sdwEvaluate word).table (idMap n) = (sdwEvaluate word).table
      exact composeMap_idMap_right (sdwEvaluate word).table n hrange
  | _, _, .idRightConv n word hlen => by
      show composeMap (idMap n) (sdwEvaluate word).table = (sdwEvaluate word).table
      rw [← hlen]
      exact composeMap_idMap_eq (sdwEvaluate word).table
  | _, _, .faceDegenSame i n => composeMap_faceMap_degenMap i n
  | _, _, .faceDegenSucc i n => composeMap_faceMap_succ_degenMap i n
  | _, _, .faceFace i j n hij => composeMap_faceMap_faceMap_commute i j n hij
  | _, _, .degenDegen i j n hij hjn => composeMap_degenMap_degenMap_commute i j n hij hjn
  | _, _, .faceDegenLower i j n hij hjn => composeMap_faceMap_degenMap_lowerCommute i j n hij hjn

/-! ## T3 — the decision -/

/-- The word-problem decision: two words are declared equal exactly when their evaluated tables are `cswListNatBeq`.
Computes; propext-free. -/
def decideSimplexEq (left right : SimplexWord) : Bool :=
  cswListNatBeq (sdwEvaluate left).table (sdwEvaluate right).table

/-- ★ **Positive half.**  Convertible words decide `true`. -/
theorem decideSimplexEq_ofSimplexConv {left right : SimplexWord} :
    SimplexConv left right → decideSimplexEq left right = true := by
  intro hConv
  show cswListNatBeq (sdwEvaluate left).table (sdwEvaluate right).table = true
  rw [sdwConvSound hConv]
  exact cswListNatBeqRefl (sdwEvaluate right).table

/-- ★ **Refutation half.**  Words whose tables differ (`decideSimplexEq = false`) are NOT convertible — the
soundness contrapositive.  This is the genuine separating power: distinct monotone maps can never be equated by any
simplicial rewrite path. -/
theorem sdwNotConv_ofDecideFalse {left right : SimplexWord} :
    decideSimplexEq left right = false → ¬ SimplexConv left right := by
  intro hFalse hConv
  have hTablesEq : (sdwEvaluate left).table = (sdwEvaluate right).table := sdwConvSound hConv
  have hTrue : cswListNatBeq (sdwEvaluate left).table (sdwEvaluate right).table = true := by
    rw [hTablesEq]; exact cswListNatBeqRefl (sdwEvaluate right).table
  rw [decideSimplexEq, hTrue] at hFalse
  exact Bool.noConfusion hFalse

/-! ## Walls -/

/-- **Eilenberg–Zilber completeness wall.**  The converse of `decideSimplexEq_ofSimplexConv` — equal evaluated
table ⟹ `SimplexConv` — is NOT shipped.

Obstruction: completeness requires the EZ factorization to be RECOVERED from an arbitrary value table and lifted
back to a `SimplexConv` path.  Concretely, `w1` and `w2` with the same table must each be shown convertible to the
canonical surjection-then-injection normal form of that table, and that NF-reconstruction must be a `SimplexConv`
derivation (not merely a table equality).

Burned attack A — *reuse existence directly*: the upstream `composeMap_rankList_imageList` gives the table's
factorization as `composeMap (rankList t) (imageList t) = t`, but `rankList`/`imageList` are VALUE-list
operations, not generator WORDS; turning them into a `SimplexConv` path needs a per-table induction expressing the
epi as a `degenW`-composite and the mono as a `faceW`-composite, together with a UNIQUENESS argument that any two
words with the same table reduce to the SAME such composite.  That uniqueness is exactly the EZ lemma, absent here.

Burned attack B — *induct on word structure*: attempting `sdwConvComplete` by induction on `w1` (or on table
length) stalls at `compW`: from `(sdwEvaluate (compW s f)).table = (sdwEvaluate w2).table` one cannot peel a
generator off `w2` without already knowing `w2`'s canonical form, so the induction has no decreasing measure that
survives an arbitrary right-hand word.  A `WellFounded.fix` over a table-complexity measure would close it — banned
in this Init-only regime. -/
def sdwHasEilenbergZilberCompleteness : Bool := false

/-- **Directed-univalence wall.**  The deep extension beyond the 1-categorical Δ word problem is the synthetic
∞-category theory of Riehl–Shulman: directed univalence `Hom_U(A, B) ≃ Fun(A, B)` at a proof-relevant universe,
with the Segal (composition) and Rezk (completeness) conditions.

Obstruction: full Segal/Rezk directed univalence entails directed ∞-fillers and homotopy-coherent composition whose
coherences are equalities BETWEEN proofs — i.e. they require `funext` / `Quot.sound` to identify parallel
higher cells — which is outside the zero-axiom Init-only regime.  The 1-categorical `decideSimplexEq` lives strictly
BELOW this wall (it decides a set-level table equality, no higher coherence).

Burned attack A — *decidable Hom at a discrete object*: the tower's precedent
(`fxContextDirectedUnivalence_homReducesToFun`) only obtains the equivalence at a DISCRETE universe object where
`Hom` degenerates to a decidable table; extending to a proof-relevant object reintroduces the coherence quotient.

Burned attack B — *bounded Segal filler by unrolling*: a finite Δ²-horn filler decides at each fixed dimension, but
the Rezk completeness condition quantifies over an unbounded tower of degeneracies whose identification is a
`Quot.sound`-gated equality of the universe's path space. -/
def sdwHasDirectedUnivalence : Bool := false

/-- **Segal–Rezk completeness wall** (companion marker to `sdwHasDirectedUnivalence`): homotopy-coherent Segal
composition plus Rezk completeness of the simplicial universe.  Same obstruction — higher coherences need
`funext` / `Quot.sound`. -/
def sdwHasSegalCompleteness : Bool := false

/-- Capability marker: the 1-categorical Δ word problem IS decided (below the walls). -/
def sdwHasSimplexWordDecision : Bool := true

/-! ## T5 — ground fires -/

/-- The cosimplicial (face-face) identity `δ_2 ∘ δ_0 = δ_0 ∘ δ_1` at `n = 1` decides `true`: both sides evaluate to
the same monotone table. -/
theorem sdwFire_faceFaceDecides :
    decideSimplexEq (.compW (.faceW 2 2) (.faceW 0 1)) (.compW (.faceW 0 2) (.faceW 1 1)) = true := rfl

/-- The same face-face identity via the CONGRUENCE constructor (`faceFace 0 1 1`) is sound and hence decides
`true`. -/
theorem sdwFire_faceFaceConvDecides :
    decideSimplexEq (.compW (.faceW 2 2) (.faceW 0 1)) (.compW (.faceW 0 2) (.faceW 1 1)) = true :=
  decideSimplexEq_ofSimplexConv (SimplexConv.faceFace 0 1 1 (Nat.le_of_lt (Nat.lt_succ_self 0)))

/-- The triangle identity `σ_0 ∘ δ_0 = id` at `n = 2` decides `true`. -/
theorem sdwFire_triangleDecides :
    decideSimplexEq (.compW (.degenW 0 2) (.faceW 0 2)) (.idW 2) = true := rfl

/-- Right-identity composition `f ∘ id = f` decides `true` for the concrete face `δ_0 : [2] → [3]`: the inner
identity is on `[2]` (the domain), so `compW (faceW 0 2) (idW 2)` evaluates to the face table itself. -/
theorem sdwFire_idComposeDecides :
    decideSimplexEq (.compW (.faceW 0 2) (.idW 2)) (.faceW 0 2) = true := rfl

/-- Two distinct faces `δ_0, δ_1 : [2] → [3]` have different tables and decide `false`. -/
theorem sdwFire_distinctDecidesFalse :
    decideSimplexEq (.faceW 0 2) (.faceW 1 2) = false := rfl

/-- The concrete face `δ_1 : [3] → [4]` has the expected value table `[0, 2, 3]` (it SKIPS the value `1`). -/
theorem sdwFire_faceSkipTable : (sdwEvaluate (.faceW 1 3)).table = [0, 2, 3] := rfl

/-- The concrete degeneracy `σ_1 : [3] → [2]` has the expected value table `[0, 1, 1]` (it REPEATS the value `1`). -/
theorem sdwFire_degenRepeatTable : (sdwEvaluate (.degenW 1 2)).table = [0, 1, 1] := rfl

/-- A concrete evaluated word is well-formed (length + entry bound + non-decreasing all pass). -/
theorem sdwFire_wellFormedFace : sdwWellFormed (sdwEvaluate (.faceW 1 3)) = true := rfl

/-- A concrete composite is well-formed too. -/
theorem sdwFire_wellFormedComposite :
    sdwWellFormed (sdwEvaluate (.compW (.degenW 0 2) (.faceW 0 2))) = true := rfl

end FX1Poly.Polygraph.Directed
