-- FX — library root for leanx (the Lean 4 reference interpreter).
--
-- Role: stable, single-import entry point for downstream consumers
-- (the `fxi` binary, the conformance tests, editor tooling).  This
-- file intentionally contains NO declarations of its own; it only
-- re-exports the curated module list in `FX/Core.lean`, which in
-- turn gates imports by phase.  Keep it a one-liner — any logic
-- belongs in `FX.Core` so the phase gating stays in exactly one
-- place.
--
-- See `FX/Core.lean` for the layering, `SPEC.md` §3 for the trust
-- story, and `fx_design.md` §24 for how `fxi` surfaces this to
-- agents.
import FX.Core
