import LeanFX2.Tools.DependencyAudit
import LeanFX2.FX1Bridge.Pi

namespace LeanFX2.Tools

/-! ## AuditFX1Bridge_UnitTypeForm — 16 `#assert_no_axioms` checks. -/

#assert_no_axioms LeanFX2.FX1Bridge.unitPiIdentityRaw
#assert_no_axioms LeanFX2.FX1Bridge.unitPiIdentityType
#assert_no_axioms LeanFX2.FX1Bridge.unitPiIdentityTerm
#assert_no_axioms LeanFX2.FX1Bridge.encodeTy_unitPiIdentity
#assert_no_axioms LeanFX2.FX1Bridge.encodeRawTerm_unitPiIdentity
#assert_no_axioms LeanFX2.FX1Bridge.encodedUnitPiIdentityType_has_sort
#assert_no_axioms LeanFX2.FX1Bridge.encodedUnitPiIdentity_has_type
#assert_no_axioms LeanFX2.FX1Bridge.encodeTermSound_unitPiIdentity
#assert_no_axioms LeanFX2.FX1Bridge.encodeTermSound_unitPiIdentity_roundTrip
#assert_no_axioms LeanFX2.FX1Bridge.unitPiIdentityAppRaw
#assert_no_axioms LeanFX2.FX1Bridge.unitPiIdentityAppTerm
#assert_no_axioms LeanFX2.FX1Bridge.encodeRawTerm_unitPiIdentityApp
#assert_no_axioms LeanFX2.FX1Bridge.encodedUnitPiIdentityApp_has_type
#assert_no_axioms LeanFX2.FX1Bridge.encodedUnitPiIdentityApp_betaStep
#assert_no_axioms LeanFX2.FX1Bridge.encodeTermSound_unitPiIdentityApp
#assert_no_axioms LeanFX2.FX1Bridge.encodeTermSound_unitPiIdentityApp_roundTrip

end LeanFX2.Tools
