import LeanFX2.Tools.DependencyAudit
import LeanFX2.Tools.AuditGen
import LeanFX2.Tools.StrictHarness
import LeanFX2
import LeanFX2.FX1.LeanKernel.Name
import LeanFX2.FX1.LeanKernel.Level
import LeanFX2.FX1.LeanKernel.Expr
import LeanFX2.FX1.LeanKernel.Substitution
import LeanFX2.FX1.LeanKernel.Reduction
import LeanFX2.FX1.LeanKernel.Inductive
import LeanFX2.FX1.LeanKernel.HasType
import LeanFX2.FX1.LeanKernel.Check
import LeanFX2.FX1.LeanKernel.Soundness
import LeanFX2.FX1.LeanKernel.Audit
import LeanFX2.FX1
import LeanFX2.FX1Bridge

namespace LeanFX2.Tools

/-! ## Audit chunk 10 (lines 1042-1153 of original AuditAll). -/

#assert_no_axioms LeanFX2.FX1.Level.checkerBeq
#assert_no_axioms LeanFX2.FX1.Level.checkerBeq_sound
#assert_no_axioms LeanFX2.FX1.Expr.checkerBeq
#assert_no_axioms LeanFX2.FX1.Expr.checkerBeq_sound
#assert_no_axioms LeanFX2.FX1.Environment.LookupDeclarationResult
#assert_no_axioms LeanFX2.FX1.Environment.LookupDeclarationResult.declaration
#assert_no_axioms LeanFX2.FX1.Environment.LookupDeclarationResult.declarationMember
#assert_no_axioms LeanFX2.FX1.Environment.LookupDeclarationResult.rewriteQueryName
#assert_no_axioms LeanFX2.FX1.Environment.FindTypeByNameSoundResult
#assert_no_axioms LeanFX2.FX1.Environment.FindTypeByNameSoundResult.declaration
#assert_no_axioms LeanFX2.FX1.Environment.FindTypeByNameSoundResult.declarationMember
#assert_no_axioms LeanFX2.FX1.Environment.FindTypeByNameSoundResult.typeEquality
#assert_no_axioms LeanFX2.FX1.Environment.findByNameResultInDeclarations?
#assert_no_axioms LeanFX2.FX1.Environment.findByNameResult?
#assert_no_axioms LeanFX2.FX1.Environment.findTypeByNameFromResult?
#assert_no_axioms LeanFX2.FX1.Environment.findTypeByName?
#assert_no_axioms LeanFX2.FX1.Environment.findTypeByName_sound
#assert_no_axioms LeanFX2.FX1.Environment.TransparentLookupResult
#assert_no_axioms LeanFX2.FX1.Environment.TransparentLookupResult.typeExpr
#assert_no_axioms LeanFX2.FX1.Environment.TransparentLookupResult.valueExpr
#assert_no_axioms LeanFX2.FX1.Environment.TransparentLookupResult.transparentDefinition
#assert_no_axioms LeanFX2.FX1.Environment.TransparentLookupResult.rewriteQueryName
#assert_no_axioms LeanFX2.FX1.Environment.FindTransparentValueSoundResult
#assert_no_axioms LeanFX2.FX1.Environment.FindTransparentValueSoundResult.typeExpr
#assert_no_axioms LeanFX2.FX1.Environment.FindTransparentValueSoundResult.transparentDefinition
#assert_no_axioms LeanFX2.FX1.Environment.TransparentLookupResult.weakenOlder
#assert_no_axioms LeanFX2.FX1.Environment.findTransparentDefinitionResultInDeclarations?
#assert_no_axioms LeanFX2.FX1.Environment.findTransparentDefinitionResult?
#assert_no_axioms LeanFX2.FX1.Environment.findTransparentValueFromResult?
#assert_no_axioms LeanFX2.FX1.Environment.findTransparentValue?
#assert_no_axioms LeanFX2.FX1.Environment.findTransparentValue_sound
#assert_no_axioms LeanFX2.FX1.Context.LookupTypeResult
#assert_no_axioms LeanFX2.FX1.Context.LookupTypeResult.typeExpr
#assert_no_axioms LeanFX2.FX1.Context.LookupTypeResult.typeAtIndex
#assert_no_axioms LeanFX2.FX1.Context.lookupTypeResultInEntries?
#assert_no_axioms LeanFX2.FX1.Context.lookupTypeFromResult?
#assert_no_axioms LeanFX2.FX1.Context.lookupTypeInEntries?
#assert_no_axioms LeanFX2.FX1.Context.lookupType?
#assert_no_axioms LeanFX2.FX1.Context.lookupTypeResult?
#assert_no_axioms LeanFX2.FX1.Context.lookupType_sound
#assert_no_axioms LeanFX2.FX1.Expr.HeadStepResult
#assert_no_axioms LeanFX2.FX1.Expr.HeadStepResult.targetExpr
#assert_no_axioms LeanFX2.FX1.Expr.HeadStepResult.reductionStep
#assert_no_axioms LeanFX2.FX1.Expr.headStepResult?
#assert_no_axioms LeanFX2.FX1.Expr.headStepFromResult?
#assert_no_axioms LeanFX2.FX1.Expr.headStep?
#assert_no_axioms LeanFX2.FX1.Expr.headStep?_sound
#assert_no_axioms LeanFX2.FX1.Expr.WhnfResult
#assert_no_axioms LeanFX2.FX1.Expr.WhnfResult.targetExpr
#assert_no_axioms LeanFX2.FX1.Expr.WhnfResult.reductions
#assert_no_axioms LeanFX2.FX1.Expr.whnfResultWithFuel
#assert_no_axioms LeanFX2.FX1.Expr.whnfFromResult
#assert_no_axioms LeanFX2.FX1.Expr.whnfWithFuel
#assert_no_axioms LeanFX2.FX1.Expr.weakHeadFuel
#assert_no_axioms LeanFX2.FX1.Expr.whnf
#assert_no_axioms LeanFX2.FX1.Expr.whnfWithFuel_sound
#assert_no_axioms LeanFX2.FX1.Expr.whnf_sound
#assert_no_axioms LeanFX2.FX1.Expr.DefEqResult
#assert_no_axioms LeanFX2.FX1.Expr.DefEqResult.commonExpr
#assert_no_axioms LeanFX2.FX1.Expr.DefEqResult.leftReductions
#assert_no_axioms LeanFX2.FX1.Expr.DefEqResult.rightReductions
#assert_no_axioms LeanFX2.FX1.Expr.DefEqResult.toDefEq
#assert_no_axioms LeanFX2.FX1.Expr.weakHeadFuelAdd
#assert_no_axioms LeanFX2.FX1.Expr.defEqFuel
#assert_no_axioms LeanFX2.FX1.Expr.defEqResultWithFuel?
#assert_no_axioms LeanFX2.FX1.Expr.isDefEqWithFuel
#assert_no_axioms LeanFX2.FX1.Expr.isDefEq
#assert_no_axioms LeanFX2.FX1.Expr.isDefEqWithFuel_sound
#assert_no_axioms LeanFX2.FX1.Expr.isDefEq_sound
#assert_no_axioms LeanFX2.FX1.Expr.isDefEqWithFuel_sound_defEq
#assert_no_axioms LeanFX2.FX1.Expr.isDefEq_sound_defEq
#assert_no_axioms LeanFX2.FX1.Expr.InferResult
#assert_no_axioms LeanFX2.FX1.Expr.InferResult.typeExpr
#assert_no_axioms LeanFX2.FX1.Expr.InferResult.typeDerivation
#assert_no_axioms LeanFX2.FX1.Expr.inferTypeFromResult?
#assert_no_axioms LeanFX2.FX1.Expr.checkBoolFromResult?
#assert_no_axioms LeanFX2.FX1.Expr.checkBoolFromCoreType?
#assert_no_axioms LeanFX2.FX1.Expr.inferCore?
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_bvar_sound
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_sort_sound
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_const_sound
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_pi_from_branch_sound
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_lam_from_branch_sound
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_app_from_branch_sound
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_none_absurd
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_sound
#assert_no_axioms LeanFX2.FX1.Expr.checkCore?
#assert_no_axioms LeanFX2.FX1.Expr.checkCore_of_inferCore_sound
#assert_no_axioms LeanFX2.FX1.Expr.checkCore_sound
#assert_no_axioms LeanFX2.FX1.Expr.checkCore_bvar_sound
#assert_no_axioms LeanFX2.FX1.Expr.checkCore_sort_sound
#assert_no_axioms LeanFX2.FX1.Expr.inferResult?
#assert_no_axioms LeanFX2.FX1.Expr.infer?
#assert_no_axioms LeanFX2.FX1.Expr.infer?_sound
#assert_no_axioms LeanFX2.FX1.Expr.check?
#assert_no_axioms LeanFX2.FX1.Expr.check?_sound
#assert_no_axioms LeanFX2.FX1.Expr.betaConvertibleSortZeroType
#assert_no_axioms LeanFX2.FX1.Expr.betaConvertibleArgumentContext
#assert_no_axioms LeanFX2.FX1.Expr.betaConvertibleIdentityApp
#assert_no_axioms LeanFX2.FX1.Expr.isDefEq_betaConvertibleSortZeroType
#assert_no_axioms LeanFX2.FX1.Expr.inferCore_accepts_betaConvertibleArgumentDomain
#assert_no_axioms LeanFX2.FX1.Expr.checkCore_accepts_betaConvertibleExpectedType
#assert_no_axioms LeanFX2.FX1.Expr.infer_accepts_betaConvertibleArgumentDomain
#assert_no_axioms LeanFX2.FX1.Expr.check_accepts_betaConvertibleExpectedType
#assert_no_axioms LeanFX2.FX1.check_sound
#assert_no_axioms LeanFX2.FX1.checkCore_sound

-- FX1Bridge staged rich-to-FX1 unit fragment.  These proofs make only a
-- Bridge-status claim: the staged FX1 environment contains object-level
-- axiom declarations, so this is not Root-FX1 release evidence.
#assert_no_axioms LeanFX2.FX1Bridge.unitTypeAtomId
#assert_no_axioms LeanFX2.FX1Bridge.unitValueAtomId

end LeanFX2.Tools
