import LeanFX2.Tools.DependencyAudit
import LeanFX2.Tools.AuditGen
import LeanFX2.Tools.StrictHarness
import LeanFX2
import LeanFX2.FX1.LeanKernel.Name
import LeanFX2.FX1.LeanKernel.Level
import LeanFX2.FX1.LeanKernel.Expr
import LeanFX2.FX1.LeanKernel.Substitution
import LeanFX2.FX1.LeanKernel.Reduction
import LeanFX2.FX1.LeanKernel.Inductive
import LeanFX2.FX1.LeanKernel.HasType
import LeanFX2.FX1.LeanKernel.Check
import LeanFX2.FX1.LeanKernel.Soundness
import LeanFX2.FX1.LeanKernel.Audit
import LeanFX2.FX1
import LeanFX2.FX1Bridge

namespace LeanFX2.Tools

/-! ## Audit chunk 08 (lines 818-929 of original AuditAll). -/

#assert_no_axioms LeanFX2.Graded.structuralDimensionEntries21_length
#assert_no_axioms LeanFX2.Graded.semiringDimensions21_length
#assert_no_axioms LeanFX2.Graded.semiringDimensionSlots21_length
#assert_no_axioms LeanFX2.Graded.joinDimensions21_length
#assert_no_axioms LeanFX2.Graded.joinDimensionSlots21_length
#assert_no_axioms LeanFX2.Graded.structuralDimensionSlots21_length
#assert_no_axioms LeanFX2.Graded.semiringDimensions21_slots_length_match
#assert_no_axioms LeanFX2.Graded.joinDimensions21_slots_length_match
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.bottom
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.one
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.compose
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.le_refl
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.le_trans
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.joinGrades_bottom_le
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.compose_semiring_one_left
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.compose_semiring_one_right
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.compose_join_left_le
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.compose_join_right_le
#assert_no_axioms LeanFX2.Graded.JoinGradeVector.join_mono
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.join_mono
#assert_no_axioms LeanFX2.Graded.FXGradeVector21.compose_mono

-- FX1/Core minimal syntax and M1 environment scaffold
#assert_no_axioms LeanFX2.FX1.Boolean.and_true_left
#assert_no_axioms LeanFX2.FX1.Boolean.and_true_right
#assert_no_axioms LeanFX2.FX1.EqualityResult
#assert_no_axioms LeanFX2.FX1.EqualityResult.equal
#assert_no_axioms LeanFX2.FX1.EqualityResult.notEqual
#assert_no_axioms LeanFX2.FX1.NaturalNumber.beq
#assert_no_axioms LeanFX2.FX1.NaturalNumber.beq_sound
#assert_no_axioms LeanFX2.FX1.NaturalNumber.eqResult
#assert_no_axioms LeanFX2.FX1.Name
#assert_no_axioms LeanFX2.FX1.Name.appendAtom
#assert_no_axioms LeanFX2.FX1.Name.appendNumber
#assert_no_axioms LeanFX2.FX1.Name.isAnonymous
#assert_no_axioms LeanFX2.FX1.Name.beq
#assert_no_axioms LeanFX2.FX1.Name.nodeCount
#assert_no_axioms LeanFX2.FX1.Name.beq_sound
#assert_no_axioms LeanFX2.FX1.Name.eqResult
#assert_no_axioms LeanFX2.FX1.Level
#assert_no_axioms LeanFX2.FX1.Level.beq
#assert_no_axioms LeanFX2.FX1.Level.nodeCount
#assert_no_axioms LeanFX2.FX1.Expr
#assert_no_axioms LeanFX2.FX1.Expr.beq
#assert_no_axioms LeanFX2.FX1.Expr.nodeCount
#assert_no_axioms LeanFX2.FX1.Declaration
#assert_no_axioms LeanFX2.FX1.Declaration.name
#assert_no_axioms LeanFX2.FX1.Declaration.typeExpr
#assert_no_axioms LeanFX2.FX1.Declaration.valueExpr?
#assert_no_axioms LeanFX2.FX1.Declaration.hasValue
#assert_no_axioms LeanFX2.FX1.Declaration.isAxiomDeclaration
#assert_no_axioms LeanFX2.FX1.Declaration.hasName
#assert_no_axioms LeanFX2.FX1.Environment
#assert_no_axioms LeanFX2.FX1.Environment.empty
#assert_no_axioms LeanFX2.FX1.Environment.extend
#assert_no_axioms LeanFX2.FX1.Environment.declarationCountInList
#assert_no_axioms LeanFX2.FX1.Environment.declarationCount
#assert_no_axioms LeanFX2.FX1.Environment.findInDeclarations?
#assert_no_axioms LeanFX2.FX1.Environment.findWhere?
#assert_no_axioms LeanFX2.FX1.Environment.hasDeclarationWhere
#assert_no_axioms LeanFX2.FX1.Environment.findByName?
#assert_no_axioms LeanFX2.FX1.Environment.hasName
#assert_no_axioms LeanFX2.FX1.Environment.hasAxiomDeclaration
#assert_no_axioms LeanFX2.FX1.Context
#assert_no_axioms LeanFX2.FX1.Context.empty
#assert_no_axioms LeanFX2.FX1.Context.extend
#assert_no_axioms LeanFX2.FX1.Context.lengthInEntries
#assert_no_axioms LeanFX2.FX1.Context.length
#assert_no_axioms LeanFX2.FX1.Context.lookupInEntries?
#assert_no_axioms LeanFX2.FX1.Context.lookup?
#assert_no_axioms LeanFX2.FX1.Context.hasIndex
#assert_no_axioms LeanFX2.FX1.Expr.isScopedIn
#assert_no_axioms LeanFX2.FX1.Renaming
#assert_no_axioms LeanFX2.FX1.Renaming.identity
#assert_no_axioms LeanFX2.FX1.Renaming.shift
#assert_no_axioms LeanFX2.FX1.Renaming.compose
#assert_no_axioms LeanFX2.FX1.Renaming.lift
#assert_no_axioms LeanFX2.FX1.Renaming.lift_ext
#assert_no_axioms LeanFX2.FX1.Renaming.lift_identity_apply
#assert_no_axioms LeanFX2.FX1.Renaming.compose_identity_left_apply
#assert_no_axioms LeanFX2.FX1.Renaming.compose_identity_right_apply
#assert_no_axioms LeanFX2.FX1.Renaming.compose_lift_apply
#assert_no_axioms LeanFX2.FX1.Renaming.compose_shift_lift_apply
#assert_no_axioms LeanFX2.FX1.Expr.rename
#assert_no_axioms LeanFX2.FX1.Expr.weaken
#assert_no_axioms LeanFX2.FX1.Expr.pi_congr
#assert_no_axioms LeanFX2.FX1.Expr.lam_congr
#assert_no_axioms LeanFX2.FX1.Expr.app_congr
#assert_no_axioms LeanFX2.FX1.Expr.rename_ext
#assert_no_axioms LeanFX2.FX1.Expr.rename_identity
#assert_no_axioms LeanFX2.FX1.Expr.rename_compose
#assert_no_axioms LeanFX2.FX1.Expr.rename_shift_lift_commute
#assert_no_axioms LeanFX2.FX1.Substitution
#assert_no_axioms LeanFX2.FX1.Substitution.identity
#assert_no_axioms LeanFX2.FX1.Substitution.ofRenaming
#assert_no_axioms LeanFX2.FX1.Substitution.renameOutput
#assert_no_axioms LeanFX2.FX1.Substitution.renameInput
#assert_no_axioms LeanFX2.FX1.Substitution.compose
#assert_no_axioms LeanFX2.FX1.Substitution.lift
#assert_no_axioms LeanFX2.FX1.Substitution.singleton
#assert_no_axioms LeanFX2.FX1.Substitution.lift_ext
#assert_no_axioms LeanFX2.FX1.Substitution.lift_identity_apply
#assert_no_axioms LeanFX2.FX1.Substitution.ofRenaming_identity_apply
#assert_no_axioms LeanFX2.FX1.Substitution.lift_ofRenaming_apply
#assert_no_axioms LeanFX2.FX1.Substitution.lift_renameOutput_apply
#assert_no_axioms LeanFX2.FX1.Substitution.lift_renameInput_apply
#assert_no_axioms LeanFX2.FX1.Substitution.renameInput_lift_shift_apply
#assert_no_axioms LeanFX2.FX1.Substitution.lift_compose_apply
#assert_no_axioms LeanFX2.FX1.Substitution.compose_identity_left_apply
#assert_no_axioms LeanFX2.FX1.Substitution.compose_identity_right_apply
#assert_no_axioms LeanFX2.FX1.Substitution.singleton_newest
#assert_no_axioms LeanFX2.FX1.Substitution.singleton_older

end LeanFX2.Tools
