import LeanFX2.Tools.DependencyAudit
import LeanFX2.Tools.AuditGen
import LeanFX2.Tools.StrictHarness
import LeanFX2
import LeanFX2.FX1.LeanKernel.Name
import LeanFX2.FX1.LeanKernel.Level
import LeanFX2.FX1.LeanKernel.Expr
import LeanFX2.FX1.LeanKernel.Substitution
import LeanFX2.FX1.LeanKernel.Reduction
import LeanFX2.FX1.LeanKernel.Inductive
import LeanFX2.FX1.LeanKernel.HasType
import LeanFX2.FX1.LeanKernel.Check
import LeanFX2.FX1.LeanKernel.Soundness
import LeanFX2.FX1.LeanKernel.Audit
import LeanFX2.FX1
import LeanFX2.FX1Bridge

namespace LeanFX2.Tools

/-! ## Audit chunk 06 (lines 594-705 of original AuditAll). -/

#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.rec
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.rec_intro
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.rec_sound
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.dependentInductor
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.dependentInductor_intro
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.dependentInductor_sound
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.recConstant
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.recConstant_intro
#assert_no_axioms LeanFX2.HoTT.HIT.S1PointLabel
#assert_no_axioms LeanFX2.HoTT.HIT.S1PathLabel
#assert_no_axioms LeanFX2.HoTT.HIT.S1Spec
#assert_no_axioms LeanFX2.HoTT.HIT.S1.S1Loop
#assert_no_axioms LeanFX2.HoTT.HIT.S1.S1Loop.relation
#assert_no_axioms LeanFX2.HoTT.HIT.S1.S1Loop.relation_refl
#assert_no_axioms LeanFX2.HoTT.HIT.S1.S1Loop.relation_symm
#assert_no_axioms LeanFX2.HoTT.HIT.S1.S1Loop.relation_trans
#assert_no_axioms LeanFX2.HoTT.HIT.S1.loopSpec
#assert_no_axioms LeanFX2.HoTT.HIT.S1.setoid
#assert_no_axioms LeanFX2.HoTT.HIT.S1.base
#assert_no_axioms LeanFX2.HoTT.HIT.S1.forwardLoop
#assert_no_axioms LeanFX2.HoTT.HIT.S1.backwardLoop
#assert_no_axioms LeanFX2.HoTT.HIT.S1.loop
#assert_no_axioms LeanFX2.HoTT.HIT.S1.loopForward
#assert_no_axioms LeanFX2.HoTT.HIT.S1.loopBackward
#assert_no_axioms LeanFX2.HoTT.HIT.S1.loopBetween
#assert_no_axioms LeanFX2.HoTT.HIT.S1.rec
#assert_no_axioms LeanFX2.HoTT.HIT.S1.recFromWinding
#assert_no_axioms LeanFX2.HoTT.HIT.S1.rec_base
#assert_no_axioms LeanFX2.HoTT.HIT.S1.rec_loop
#assert_no_axioms LeanFX2.HoTT.HIT.S1.recFromWinding_base
#assert_no_axioms LeanFX2.HoTT.HIT.S1.recFromWinding_loopBetween
#assert_no_axioms LeanFX2.HoTT.HIT.S1.dependentInductor
#assert_no_axioms LeanFX2.HoTT.HIT.S1.dependentInductor_base
#assert_no_axioms LeanFX2.HoTT.HIT.S1.dependentInductor_loop
#assert_no_axioms LeanFX2.HoTT.HIT.S1.dependentInductor_loopBetween
#assert_no_axioms LeanFX2.HoTT.HIT.SuspensionPoint
#assert_no_axioms LeanFX2.HoTT.HIT.SuspensionRel
#assert_no_axioms LeanFX2.HoTT.HIT.SuspensionRel.relation_refl
#assert_no_axioms LeanFX2.HoTT.HIT.SuspensionRel.relation_symm
#assert_no_axioms LeanFX2.HoTT.HIT.SuspensionRel.relation_trans
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.relation
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.relation_refl
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.relation_symm
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.relation_trans
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.setoid
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.north
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.south
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.meridian
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.rec
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.rec_north
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.rec_south
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.rec_meridian
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.dependentInductor
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.dependentInductor_north
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.dependentInductor_south
#assert_no_axioms LeanFX2.HoTT.HIT.Suspension.dependentInductor_meridian
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutCarrier
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.evaluate
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.dependentEvaluate
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.left
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.right
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.glue
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.rec
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.rec_left
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.rec_right
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.rec_glue
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.dependentInductor
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.dependentInductor_left
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.dependentInductor_right
#assert_no_axioms LeanFX2.HoTT.HIT.PushoutHIT.dependentInductor_glue
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.point
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.equalize
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.rec
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.rec_point
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.rec_equalize
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.dependentInductor
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.dependentInductor_point
#assert_no_axioms LeanFX2.HoTT.HIT.CoequalizerHIT.dependentInductor_equalize
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.quotientUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.propTruncUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.setTruncUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.s1BaseUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.suspensionNorthUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.pushoutUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.pushoutLeftUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.coequalizerUnit
#assert_no_axioms LeanFX2.HoTT.HIT.Examples.coequalizerPointUnit

-- Codata stream structural layer
#assert_no_axioms LeanFX2.Codata.Stream
#assert_no_axioms LeanFX2.Codata.Stream.head
#assert_no_axioms LeanFX2.Codata.Stream.tail
#assert_no_axioms LeanFX2.Codata.Stream.iterateState
#assert_no_axioms LeanFX2.Codata.Stream.unfold
#assert_no_axioms LeanFX2.Codata.Stream.Bisim
#assert_no_axioms LeanFX2.Codata.Stream.bisim_refl
#assert_no_axioms LeanFX2.Codata.Stream.bisim_symm
#assert_no_axioms LeanFX2.Codata.Stream.bisim_trans
#assert_no_axioms LeanFX2.Codata.Stream.head_unfold
#assert_no_axioms LeanFX2.Codata.Stream.tail_unfold
#assert_no_axioms LeanFX2.Codata.Stream.bisim_head
#assert_no_axioms LeanFX2.Codata.Stream.bisim_tail
#assert_no_axioms LeanFX2.Codata.Stream.productive
#assert_no_axioms LeanFX2.Codata.constantZero
#assert_no_axioms LeanFX2.Codata.naturals
#assert_no_axioms LeanFX2.Codata.Stream.Destructor
#assert_no_axioms LeanFX2.Codata.Stream.Destructor.Result
#assert_no_axioms LeanFX2.Codata.Stream.Step
#assert_no_axioms LeanFX2.Codata.Stream.Step.head_deterministic
#assert_no_axioms LeanFX2.Codata.Stream.Step.tail_deterministic

end LeanFX2.Tools
