import LeanFX2.Tools.DependencyAudit
import LeanFX2.Tools.AuditGen
import LeanFX2.Tools.StrictHarness
import LeanFX2
import LeanFX2.FX1.LeanKernel.Name
import LeanFX2.FX1.LeanKernel.Level
import LeanFX2.FX1.LeanKernel.Expr
import LeanFX2.FX1.LeanKernel.Substitution
import LeanFX2.FX1.LeanKernel.Reduction
import LeanFX2.FX1.LeanKernel.Inductive
import LeanFX2.FX1.LeanKernel.HasType
import LeanFX2.FX1.LeanKernel.Check
import LeanFX2.FX1.LeanKernel.Soundness
import LeanFX2.FX1.LeanKernel.Audit
import LeanFX2.FX1
import LeanFX2.FX1Bridge

namespace LeanFX2.Tools

/-! ## Audit chunk 03 (lines 258-369 of original AuditAll). -/

#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.findInductive?_empty
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.HasConstantInList
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.HasConstantInList.newest
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.HasConstantInList.older
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.HasConstant
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.HasConstantInList.weaken
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.empty
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.extend
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.weakenEntries
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.weaken
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.extendForBinder
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.HasTypeAt
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.HasTypeAt.newest
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.HasTypeAt.older
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.HasTypeAt.weaken
#assert_no_axioms LeanFX2.FX1.LeanKernel.HasType
#assert_no_axioms LeanFX2.FX1.LeanKernel.HasType.sort
#assert_no_axioms LeanFX2.FX1.LeanKernel.HasType.bvar
#assert_no_axioms LeanFX2.FX1.LeanKernel.HasType.const
#assert_no_axioms LeanFX2.FX1.LeanKernel.HasType.forallE
#assert_no_axioms LeanFX2.FX1.LeanKernel.HasType.lam
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.ConstantLookupResult
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.findConstantResultInList?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Environment.findConstantResult?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.LookupTypeResult
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.lookupTypeResultInEntries?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Context.lookupTypeResult?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.InferResult
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.inferTypeFromResult?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.inferResult?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.infer?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.inferTypeFromResult?_sound
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.infer?_sound
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.check?
#assert_no_axioms LeanFX2.FX1.LeanKernel.Expr.check?_sound
#assert_no_axioms LeanFX2.FX1.LeanKernel.check
#assert_no_axioms LeanFX2.FX1.LeanKernel.check_sound
#assert_no_axioms LeanFX2.Cubical.glueIntroduction
#assert_no_axioms LeanFX2.Cubical.glueIntroduction_toRaw
#assert_no_axioms LeanFX2.Cubical.glueElimination
#assert_no_axioms LeanFX2.Cubical.glueElimination_toRaw
#assert_no_axioms LeanFX2.Cubical.glueIntroduction_parCong
#assert_no_axioms LeanFX2.Cubical.glueElimination_parCong
#assert_no_axioms LeanFX2.Cubical.glueIntroduction_convCumul
#assert_no_axioms LeanFX2.Cubical.glueElimination_convCumul
#assert_no_axioms LeanFX2.Cubical.glueElimIntro_parBeta
#assert_no_axioms LeanFX2.Cubical.glueElimIntro_convCumulBeta
#assert_no_axioms LeanFX2.Cubical.homogeneousComposition
#assert_no_axioms LeanFX2.Cubical.homogeneousComposition_toRaw
#assert_no_axioms LeanFX2.Cubical.homogeneousComposition_parCong
#assert_no_axioms LeanFX2.Cubical.homogeneousComposition_convCumul
#assert_no_axioms LeanFX2.Cubical.degenerateHomogeneousComposition
#assert_no_axioms LeanFX2.Cubical.degenerateHomogeneousComposition_toRaw
#assert_no_axioms LeanFX2.Cubical.degenerateHomogeneousComposition_parCong
#assert_no_axioms LeanFX2.Cubical.degenerateHomogeneousComposition_convCumul
#assert_no_axioms LeanFX2.Cubical.constantTypeTransport
#assert_no_axioms LeanFX2.Cubical.constantTypeTransport_toRaw
#assert_no_axioms LeanFX2.Cubical.constantTypeTransport_typeLineRecognized
#assert_no_axioms LeanFX2.Cubical.constantTypeTransport_sourceCong
#assert_no_axioms LeanFX2.Cubical.constantTypeTransport_sourceCong_toRawBridge
#assert_no_axioms LeanFX2.Cubical.constantTypeTransport_sourceConvCumul
#assert_no_axioms LeanFX2.Cubical.constantTypeTransport_betaConvCumul
#assert_no_axioms LeanFX2.Step.par.pathLam
#assert_no_axioms LeanFX2.Step.par.pathLamCong
#assert_no_axioms LeanFX2.Step.par.pathApp
#assert_no_axioms LeanFX2.Step.par.pathAppCong
#assert_no_axioms LeanFX2.Step.betaModElimIntro
#assert_no_axioms LeanFX2.Step.par.betaModElimIntro
#assert_no_axioms LeanFX2.Step.par.betaModElimIntroDeep
#assert_no_axioms LeanFX2.ConvCumul.betaModElimIntroCumul
#assert_no_axioms LeanFX2.ConvCumul.betaModElimIntroCumul_toConv
#assert_no_axioms LeanFX2.Step.toConvCumul
#assert_no_axioms LeanFX2.RawStep.par.iotaIdStrictRecRefl
#assert_no_axioms LeanFX2.RawStep.par.iotaIdStrictRecReflDeep
#assert_no_axioms LeanFX2.Step.intervalOppInner
#assert_no_axioms LeanFX2.Step.intervalMeetLeft
#assert_no_axioms LeanFX2.Step.intervalMeetRight
#assert_no_axioms LeanFX2.Step.intervalJoinLeft
#assert_no_axioms LeanFX2.Step.intervalJoinRight
#assert_no_axioms LeanFX2.Step.par.intervalOppCong
#assert_no_axioms LeanFX2.Step.par.intervalMeetCong
#assert_no_axioms LeanFX2.Step.par.intervalJoinCong
#assert_no_axioms LeanFX2.ConvCumul.intervalOppCong
#assert_no_axioms LeanFX2.ConvCumul.intervalMeetCong
#assert_no_axioms LeanFX2.ConvCumul.intervalJoinCong
#assert_no_axioms LeanFX2.ConvCumul.subst_compatible_intervalOpp_allais
#assert_no_axioms LeanFX2.ConvCumul.subst_compatible_intervalMeet_allais
#assert_no_axioms LeanFX2.ConvCumul.subst_compatible_intervalJoin_allais
#assert_no_axioms LeanFX2.Step.par.betaPathApp
#assert_no_axioms LeanFX2.Step.par.betaPathAppDeep
#assert_no_axioms LeanFX2.Step.par.toRawBridge
#assert_no_axioms LeanFX2.Step.par.rename_toRawBridge
#assert_no_axioms LeanFX2.Step.par.subst_toRawBridge
#assert_no_axioms LeanFX2.RawStep.par.rename_compatible
#assert_no_axioms LeanFX2.RawStep.par.subst_compatible
#assert_no_axioms LeanFX2.RawStep.par.subst_compatible_same

-- Typed D2.5 Glue-elimination parity
#assert_no_axioms LeanFX2.Term.toRaw_glueIntro
#assert_no_axioms LeanFX2.Term.toRaw_glueElim
#assert_no_axioms LeanFX2.Step.par.glueIntro
#assert_no_axioms LeanFX2.Step.par.glueIntroCong
#assert_no_axioms LeanFX2.Step.par.glueElim
#assert_no_axioms LeanFX2.Step.par.glueElimCong
#assert_no_axioms LeanFX2.Step.par.transpCong
#assert_no_axioms LeanFX2.Step.par.hcompCong
#assert_no_axioms LeanFX2.Step.par.betaGlueElimIntro
#assert_no_axioms LeanFX2.Step.par.betaGlueElimIntroDeep
#assert_no_axioms LeanFX2.ConvCumul.glueIntroCong
#assert_no_axioms LeanFX2.ConvCumul.glueElimCong
#assert_no_axioms LeanFX2.ConvCumul.subst_compatible_glueIntro_allais

end LeanFX2.Tools
