import LeanFX2.Tools.DependencyAudit
import LeanFX2.Tools.AuditGen
import LeanFX2.Tools.StrictHarness
import LeanFX2
import LeanFX2.FX1.LeanKernel.Name
import LeanFX2.FX1.LeanKernel.Level
import LeanFX2.FX1.LeanKernel.Expr
import LeanFX2.FX1.LeanKernel.Substitution
import LeanFX2.FX1.LeanKernel.Reduction
import LeanFX2.FX1.LeanKernel.Inductive
import LeanFX2.FX1.LeanKernel.HasType
import LeanFX2.FX1.LeanKernel.Check
import LeanFX2.FX1.LeanKernel.Soundness
import LeanFX2.FX1.LeanKernel.Audit
import LeanFX2.FX1
import LeanFX2.FX1Bridge

namespace LeanFX2.Tools

/-! ## Audit chunk 05 (lines 482-593 of original AuditAll). -/

#assert_no_axioms LeanFX2.Step.sessionSendPayload
#assert_no_axioms LeanFX2.Step.sessionRecvChannel
#assert_no_axioms LeanFX2.Step.effectPerformOperation
#assert_no_axioms LeanFX2.Step.effectPerformArguments
#assert_no_axioms LeanFX2.Step.par.sessionSendCong
#assert_no_axioms LeanFX2.Step.par.sessionRecvCong
#assert_no_axioms LeanFX2.Step.par.effectPerformCong
#assert_no_axioms LeanFX2.ConvCumul.sessionSendCong
#assert_no_axioms LeanFX2.ConvCumul.sessionRecvCong
#assert_no_axioms LeanFX2.ConvCumul.effectPerformCong
#assert_no_axioms LeanFX2.ConvCumul.subst_compatible_sessionSend_allais
#assert_no_axioms LeanFX2.ConvCumul.subst_compatible_sessionRecv_allais
#assert_no_axioms LeanFX2.ConvCumul.subst_compatible_effectPerform_allais

-- Conv core
#assert_no_axioms LeanFX2.Conv.refl
#assert_no_axioms LeanFX2.Conv.fromStep
#assert_no_axioms LeanFX2.Conv.toRawJoin
#assert_no_axioms LeanFX2.Conv.canonicalRaw
#assert_no_axioms LeanFX2.Conv.transRaw

-- Day 3 HoTT equivalence, univalence, funext, and path algebra.
#assert_no_axioms LeanFX2.Equiv.refl
#assert_no_axioms LeanFX2.Equiv.symm
#assert_no_axioms LeanFX2.Equiv.trans
#assert_no_axioms LeanFX2.Equiv.trans_refl_left_toFun
#assert_no_axioms LeanFX2.Equiv.trans_refl_right_toFun
#assert_no_axioms LeanFX2.IsContr.unit
#assert_no_axioms LeanFX2.IsEquiv.identity
#assert_no_axioms LeanFX2.Univalence
#assert_no_axioms LeanFX2.UnivalenceHet
#assert_no_axioms LeanFX2.Univalence.idToEquivMeta
#assert_no_axioms LeanFX2.Univalence.idToEquivMeta_isEquiv_toFun
#assert_no_axioms LeanFX2.Univalence.idToEquivMeta_isEquiv_invFun
#assert_no_axioms LeanFX2.Univalence.ua_beta_meta
#assert_no_axioms LeanFX2.Univalence.ua_beta_toFun_pointwise
#assert_no_axioms LeanFX2.Univalence.ua_beta_invFun_pointwise
#assert_no_axioms LeanFX2.funext
#assert_no_axioms LeanFX2.FunextHet
#assert_no_axioms LeanFX2.Funext.fnEqToPointwiseMeta
#assert_no_axioms LeanFX2.Funext.pointwiseMetaToFnEqAtRefl
#assert_no_axioms LeanFX2.Funext.kernelMetaCorrespondence_atRefl
#assert_no_axioms LeanFX2.Path.trans
#assert_no_axioms LeanFX2.Path.symm
#assert_no_axioms LeanFX2.Path.trans_assoc
#assert_no_axioms LeanFX2.Path.trans_refl_left
#assert_no_axioms LeanFX2.Path.trans_refl_right
#assert_no_axioms LeanFX2.Path.symm_symm
#assert_no_axioms LeanFX2.Path.trans_symm_left
#assert_no_axioms LeanFX2.Path.trans_symm_right
#assert_no_axioms LeanFX2.Path.symm_trans
#assert_no_axioms LeanFX2.PathGroupoidLaws
#assert_no_axioms LeanFX2.PathGroupoidLaws.instance
#assert_no_axioms LeanFX2.Path.trans_left_cancel
#assert_no_axioms LeanFX2.Path.trans_right_cancel

-- HoTT HIT setoid foundation
#assert_no_axioms LeanFX2.HoTT.HIT.EmptyPathLabel
#assert_no_axioms LeanFX2.HoTT.HIT.HITSpec
#assert_no_axioms LeanFX2.HoTT.HIT.HITSpec.hasPathBetween
#assert_no_axioms LeanFX2.HoTT.HIT.HITSpec.discrete
#assert_no_axioms LeanFX2.HoTT.HIT.HITSpec.discrete_hasNoPath
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid.preservesRelation
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid.discrete
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid.indiscrete
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid.fromEquivalence
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid.relation_refl
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid.relation_symm
#assert_no_axioms LeanFX2.HoTT.HIT.HITSetoid.relation_trans
#assert_no_axioms LeanFX2.HoTT.HIT.HITRecursor
#assert_no_axioms LeanFX2.HoTT.HIT.HITRecursor.run
#assert_no_axioms LeanFX2.HoTT.HIT.HITRecursor.run_respects
#assert_no_axioms LeanFX2.HoTT.HIT.HITRecursor.constant
#assert_no_axioms LeanFX2.HoTT.HIT.HITRecursor.constant_run
#assert_no_axioms LeanFX2.HoTT.HIT.HITInductor
#assert_no_axioms LeanFX2.HoTT.HIT.HITInductor.run
#assert_no_axioms LeanFX2.HoTT.HIT.HITInductor.run_respects
#assert_no_axioms LeanFX2.HoTT.HIT.HITInductor.constant
#assert_no_axioms LeanFX2.HoTT.HIT.HITInductor.constant_run
#assert_no_axioms LeanFX2.HoTT.HIT.PropTruncRel
#assert_no_axioms LeanFX2.HoTT.HIT.PropTruncRel.relation_refl
#assert_no_axioms LeanFX2.HoTT.HIT.PropTruncRel.relation_symm
#assert_no_axioms LeanFX2.HoTT.HIT.PropTruncRel.relation_trans
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.intro
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.squash
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.rec
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.rec_intro
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.rec_squash
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.dependentInductor
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.dependentInductor_intro
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.dependentInductor_squash
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.recConstant
#assert_no_axioms LeanFX2.HoTT.HIT.PropTrunc.recConstant_intro
#assert_no_axioms LeanFX2.HoTT.HIT.SetTruncRel
#assert_no_axioms LeanFX2.HoTT.HIT.SetTruncRel.relation_refl
#assert_no_axioms LeanFX2.HoTT.HIT.SetTruncRel.relation_symm
#assert_no_axioms LeanFX2.HoTT.HIT.SetTruncRel.relation_trans
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.intro
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.path
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.rec
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.rec_intro
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.rec_path
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.dependentInductor
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.dependentInductor_intro
#assert_no_axioms LeanFX2.HoTT.HIT.SetTrunc.dependentInductor_path
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.equality
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.intro
#assert_no_axioms LeanFX2.HoTT.HIT.QuotientHIT.sound

end LeanFX2.Tools
