import FX1PolyAudit.DependencyAudit
import FX1Poly.ComputerAlgebra.LinearAlgebra.EndomorphismSimilarity

/-! # FX1PolyAudit/ComputerAlgebra/LinearAlgebra/EndomorphismSimilarity — zero-axiom gate

Per-declaration zero-axiom gate for the walking-endomorphism linear model: the windowed-equality
substrate, the scaled-pair witness structure, and the substrate truth-probe.

Confirms the `decide`-discharged window checks are free of `propext`, `Quot.sound`,
`Classical.choice`, `sorry`, `native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.ComputerAlgebra.agreeOnWindow
#assert_no_axioms FX1Poly.ComputerAlgebra.EndomorphismSimilarityWitness
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismScaledInverseWindowProbe
#assert_no_axioms FX1Poly.ComputerAlgebra.EndomorphismSimilarityWitness.WitnessesSimilarity
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismSingularBasisWitness
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismSingularBasisRejected
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismDegenerateScaleWitness
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismDegenerateScaleRejected
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismCharPolyCoefficients
#assert_no_axioms FX1Poly.ComputerAlgebra.EndomorphismDissimilarByCharPoly
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismCharPolyTwoByTwoExample
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismCharPolyThreeByThreeExample
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismRank2
#assert_no_axioms FX1Poly.ComputerAlgebra.EndomorphismDissimilarByRank
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismRankZeroExample
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismRankOneExample
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismRankTwoExample
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismNilpotentConjugacyWitness
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismNilpotentConjugacyIsWitnessed
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismRationalConjugacyWitness
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismRationalConjugacyIsWitnessed
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismDistinctTraceDissimilar
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismZeroVersusJordanDissimilar
#assert_no_axioms FX1Poly.ComputerAlgebra.endomorphismZeroVersusJordanShareCharPoly
#assert_no_axioms FX1Poly.ComputerAlgebra.WalkingEndomorphismClassification
#assert_no_axioms FX1Poly.ComputerAlgebra.WalkingEndomorphismCensusEntry
#assert_no_axioms FX1Poly.ComputerAlgebra.walkingEndomorphismCensusEntry
#assert_no_axioms FX1Poly.ComputerAlgebra.walkingEndomorphismCensusGrounded
#assert_no_axioms FX1Poly.ComputerAlgebra.fxEndo_hasSeparatorSuite

end FX1PolyAudit
