import FX1PolyAudit.DependencyAudit
import FX1Poly.ComputerAlgebra.LinearAlgebra.SmithNormalForm

/-! # FX1PolyAudit/ComputerAlgebra/LinearAlgebra/SmithNormalForm — zero-axiom gate (H2-SMITH r1)

Per-declaration zero-axiom gate for the ZZ Smith driver + certificates: the certified-gcd
interface and its integer instance, the operation-inverse kit, the elimination driver, and the
non-vacuity theorems (driver-produced and diagonal SNF certificates, including the `Z/2`
homology-with-torsion seed).

Every declaration must be free of `propext`, `Quot.sound`, `Classical.choice`, `sorry`,
`native_decide`, `omega`. -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.ComputerAlgebra.CertifiedGcd
#assert_no_axioms FX1Poly.ComputerAlgebra.intCertifiedGcd
#assert_no_axioms FX1Poly.ComputerAlgebra.inverseRowOperation
#assert_no_axioms FX1Poly.ComputerAlgebra.inverseColumnOperation
#assert_no_axioms FX1Poly.ComputerAlgebra.inverseOperation
#assert_no_axioms FX1Poly.ComputerAlgebra.reverseOperationWord
#assert_no_axioms FX1Poly.ComputerAlgebra.listMapNegNeg
#assert_no_axioms FX1Poly.ComputerAlgebra.listModifyAtNegNeg
#assert_no_axioms FX1Poly.ComputerAlgebra.negateRowInvolutive
#assert_no_axioms FX1Poly.ComputerAlgebra.addScaledEntriesCancel
#assert_no_axioms FX1Poly.ComputerAlgebra.intPivotQuotient
#assert_no_axioms FX1Poly.ComputerAlgebra.smithClearRowRightSteps
#assert_no_axioms FX1Poly.ComputerAlgebra.smithClearColumnBelowSteps
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReduceSweep
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReduce
#assert_no_axioms FX1Poly.ComputerAlgebra.smithExampleTorsionDiagonal
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedUpperTriangular
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedDenseTwo
#assert_no_axioms FX1Poly.ComputerAlgebra.smithExampleChainThree
#assert_no_axioms FX1Poly.ComputerAlgebra.smithExampleCyclicTwo
#assert_no_axioms FX1Poly.ComputerAlgebra.smithRotationDecreasesPivotSize
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedEuclideanRow
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedSignedDiagonal
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedRankDeficient
#assert_no_axioms FX1Poly.ComputerAlgebra.listReplaceAtPreservesLength
#assert_no_axioms FX1Poly.ComputerAlgebra.listModifyAtPreservesLength
#assert_no_axioms FX1Poly.ComputerAlgebra.mapAllRowsPreservesLength
#assert_no_axioms FX1Poly.ComputerAlgebra.listMapPreservesLength
#assert_no_axioms FX1Poly.ComputerAlgebra.addScaledEntriesPreservesLength
#assert_no_axioms FX1Poly.ComputerAlgebra.swapEntriesWithinRowPreservesLength
#assert_no_axioms FX1Poly.ComputerAlgebra.addScaledEntryWithinRowPreservesLength
#assert_no_axioms FX1Poly.ComputerAlgebra.listModifyAtPreservesRowsWidth
#assert_no_axioms FX1Poly.ComputerAlgebra.listReplaceAtPreservesRowsWidth
#assert_no_axioms FX1Poly.ComputerAlgebra.mapAllRowsPreservesRowsWidth
#assert_no_axioms FX1Poly.ComputerAlgebra.listGetWithDefaultHasWidth
#assert_no_axioms FX1Poly.ComputerAlgebra.applyRowOperationPreservesRectangular
#assert_no_axioms FX1Poly.ComputerAlgebra.applyColumnOperationPreservesRectangular
#assert_no_axioms FX1Poly.ComputerAlgebra.applyOperationPreservesRectangular
#assert_no_axioms FX1Poly.ComputerAlgebra.applyOperationsPreservesRectangular
#assert_no_axioms FX1Poly.ComputerAlgebra.SmithReduceTotalStatement
#assert_no_axioms FX1Poly.ComputerAlgebra.smithExampleBoundaryMap
#assert_no_axioms FX1Poly.ComputerAlgebra.smithScanRowMinAbs
#assert_no_axioms FX1Poly.ComputerAlgebra.smithScanMinorMinAbs
#assert_no_axioms FX1Poly.ComputerAlgebra.smithFindMinAbsInMinor
#assert_no_axioms FX1Poly.ComputerAlgebra.smithMoveToPivotOps
#assert_no_axioms FX1Poly.ComputerAlgebra.smithSignNormalizeOps
#assert_no_axioms FX1Poly.ComputerAlgebra.smithRowSegmentAllZero
#assert_no_axioms FX1Poly.ComputerAlgebra.smithColSegmentAllZero
#assert_no_axioms FX1Poly.ComputerAlgebra.smithCrossIsClear
#assert_no_axioms FX1Poly.ComputerAlgebra.smithRowAbsSum
#assert_no_axioms FX1Poly.ComputerAlgebra.smithMinorAbsSumRows
#assert_no_axioms FX1Poly.ComputerAlgebra.smithMinorAbsSum
#assert_no_axioms FX1Poly.ComputerAlgebra.smithCascadeSweep
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReduceTotalSweep
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReduceTotal
#assert_no_axioms FX1Poly.ComputerAlgebra.smithExampleWideTwoByThree
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedEuclideanRowByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedRankDeficientByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedSignedDiagonalByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedBoundaryMapByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedWideTwoByThreeByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReduceIsNotTotal
#assert_no_axioms FX1Poly.ComputerAlgebra.SmithReduceTotalDriverStatement
#assert_no_axioms FX1Poly.ComputerAlgebra.smithPivotDividesEntry
#assert_no_axioms FX1Poly.ComputerAlgebra.smithFindNonDividingLaterDiagonal
#assert_no_axioms FX1Poly.ComputerAlgebra.smithRepairPositionSweep
#assert_no_axioms FX1Poly.ComputerAlgebra.smithDivisibilityRepairSweep
#assert_no_axioms FX1Poly.ComputerAlgebra.smithDiagonalSignSweep
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReduceFull
#assert_no_axioms FX1Poly.ComputerAlgebra.listGetWithDefaultModifyAtNe
#assert_no_axioms FX1Poly.ComputerAlgebra.addRowMultiplePreservesEntryOffTargetRow
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReduceTotalIsNotFullyReducing
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedCoprimeTwoThreeByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedCoprimeSixTenByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedCoprimeFourSixByDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedCoprimeChainByFullDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedAlreadyDivisibleByFullDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedEuclideanRowByFullDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedWideByFullDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.smithReducedSignedByFullDriver
#assert_no_axioms FX1Poly.ComputerAlgebra.SmithReduceFullDriverStatement
#assert_no_axioms FX1Poly.ComputerAlgebra.applyOperationsAppend
#assert_no_axioms FX1Poly.ComputerAlgebra.natGcdLtLeftOfNotDivides
#assert_no_axioms FX1Poly.ComputerAlgebra.smithRepairDecreasesPivotSize
#assert_no_axioms FX1Poly.ComputerAlgebra.IsWindowDiagonal
#assert_no_axioms FX1Poly.ComputerAlgebra.SmithChainPrefix
#assert_no_axioms FX1Poly.ComputerAlgebra.listGetWithDefaultModifyAtEq
#assert_no_axioms FX1Poly.ComputerAlgebra.listGetWithDefaultAddScaledEntries
#assert_no_axioms FX1Poly.ComputerAlgebra.addRowMultipleEntryOnTargetRow
#assert_no_axioms FX1Poly.ComputerAlgebra.foldPreservesSettledColumnZero

end FX1PolyAudit
