import FX1PolyAudit.DependencyAudit
import FX1Poly.Polygraph.Omega.ZXPhaseFree.SpiderRelationSeed

/-! # FX1PolyAudit.Polygraph.Omega.ZXPhaseFree.SpiderRelationSeed — zero-axiom gate
(WP-ZX seed: phase-free ZX diagrams with the F2 linear-relations semantics)

Per-declaration zero-axiom gate for the WP-ZX seed: the fresh Bool-xor/structural-Nat
kits, the F2 row kit (cons-only dense rows), inductive spans with the xor-closure algebra
(constructors asserted individually), echelonization + reduction + the mutual-reduction
span decision `zxpSpanEqB` with BOTH soundness and completeness, `zxpRref` with
`zxpRrefSpansSame`, relations as generator matrices with the composition pullback
characterization `zxpComposeSpec` / tensor characterization `zxpTensorSpec` / identity
`zxpIdSpec` and the categorical laws (congruences, associativity, units,
`zxpTensorComposeInterchange`), the strict-layer diagram carrier (cells, layers,
whiskering, the pad combinator with its denote decomposition), THE PUBLISHED ROW SET
(33 `ZxpRowTag` constructors asserted individually; per-row soundness kernel-decided in
`zxpRowBundle`), the layer-split move with the exchange derivation
(`zxpSplitLayerBundle`), the boundary-indexed congruence `ZxpConv` with SOUNDNESS
`zxpConvSound` and the refutation bridge `zxpConvSpanEqB`, the fires (Hopf, bialgebra
square, both fusions, the two FALSE-case span separations with their non-convertibility
theorems, the scalar collapse), and the three stage markers
(`fxWpZx_hasRelationSemantics` true, `fxWpZx_hasRowSoundness` true,
`fxWpZx_hasCompleteness` FALSE — completeness owner-false with the invariant-first gate
requirement recorded on `zxpCompletenessStatement`).

Must be free of `propext`, `Quot.sound`, `Classical`, `sorry`, `native_decide`, `omega`,
`WellFounded.fix`, `funext`.  Built by the FX1PolyAudit lib glob; AuditAll registration
is a later round's bookkeeping (AuditAll untouched per this round's commission). -/

namespace FX1PolyAudit

#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXorB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXorBComm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXorBAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXorBFalseLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXorBFalseRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXorBSelf
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpOrder
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpOrder.isLt
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpOrder.isEq
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpOrder.isGt
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatCompare
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatLe
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatCompareRefl
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatCompareEqImpliesEq
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatLeRefl
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatLeZeroLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatLeTrans
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatLeSuccRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatLeSuccOfCompareLt
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatCompareLtOfLeSucc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatLeOfCompareLt
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZeroRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllOnesRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCat
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTakeN
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDropN
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpGetBit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLead
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZeroRowLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllOnesRowLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTakeNCatExact
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDropNCatExact
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatTakeDrop
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTakeNLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDropNLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorComm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorSelf
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorZeroLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorZeroRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorCancelLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpGetBitZeroRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpGetBitXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllFalseZeroRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllFalseToZeroRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllFalseXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllFalseGetBit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllFalseTakeN
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatNilRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatZeroZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatInj
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorCat
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTakeNXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDropNXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTakeNZeroRowExact
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDropNZeroRowExact
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLeadFalseConsSome
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLeadFalseConsNone
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLeadBitTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLeadBitBelowFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLeadNoneAllFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLeadXorRaises
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTakeNotAllFalseLead
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllFalseTakeGetBit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowXorEqZeroImpliesEq
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowMem
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowMem.head
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowMem.tail
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpAllWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpAllWidth.nil
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpAllWidth.cons
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpMemSpan
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpMemSpan.zero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpMemSpan.pick
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllWidthRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanWeaken
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanElem
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanXorClosed
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanSub
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanNilInv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanConsInv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanBitFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanTakeAllFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpEchelonFrom
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpEchelonFrom.nil
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpEchelonFrom.cons
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonFromMono
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonFromRowLead
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonRowsBitFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowNilNone
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowNilSome
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowConsVecNone
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowConsHeadNone
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowConsLt
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowConsEq
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowConsGt
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonize
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLeadNoneToZeroRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonizeWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatCompareGtFlip
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowEchelonFrom
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonizeEchelon
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowRowsCovered
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpInsertRowSpanCovers
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonizeSpanSub1
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpEchelonizeSpanSub2
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainst
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainstConsNone
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainstConsTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainstConsFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainstWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainstSound
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainstMember
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpReduceAgainstComplete
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllRowsReduceToZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllRowsReduceToZeroConsTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllRowsReduceToZeroConsFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllRowsReduceToZeroSpec1
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllRowsReduceToZeroSpec2
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanLeB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanEqB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanEqBOfLe
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanEqBOfNotLe
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanLeBSound
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanLeBComplete
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanEqBSound
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanEqBComplete
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpBackReduce
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpBackReduceWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpBackReduceSpanSub1
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpBackReduceSpanSub2
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRref
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRrefSpansSame
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRrefWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRrefUniquenessStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRrefUniquenessIsProven
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMapRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRowsMemSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRowsMemLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRowsMemRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRowsSpanLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRowsSpanRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatRowsSpanSplitFwd
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMapRowsMemInv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMapRowsMemIntro
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMapRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMapRowsSpanFwd
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMapRowsSpanBwd
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpPairMem
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpMemSpanCast
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpAllWidthCast
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedFirst
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedSecond
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseConsTrue
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseConsFalse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseMemSub
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseMemTake
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseSpanSub
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseSpanTake
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpFilterHeadFalseSpanComplete
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedFirstLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedFirstZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedFirstXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedSecondLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedSecondZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedSecondXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeEmbedXorBlocks
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeStackFwd
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeStackBwd
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeSpec
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedFirst
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedSecond
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedFirstLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedFirstZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedFirstXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedSecondLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedSecondZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedSecondXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorEmbedXorBlocks
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorSpec
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLengthZeroNil
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadPairRow
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpIdRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadPairRowLength
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadPairRowZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadPairRowXor
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpIdRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpIdSpec
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSwapRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSwapRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRelEquiv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRelEquivRefl
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRelEquivSymm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRelEquivTrans
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRelEquivOfSpanIff
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanIffOfRelEquiv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRelEquivOfSpanEqB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpanEqBOfRelEquiv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeRowsCong
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeRowsAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeIdLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpComposeIdRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPairMemCast
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorRowsCong
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorIdSum
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorUnitLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorUnitRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorRowsAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpTensorComposeInterchange
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpCell
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpCell.zSpider
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpCell.xSpider
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpCell.wire
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpCell.crossing
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCellDomArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCellCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpiderCopyRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpParityRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSpiderCopyRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpParityRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCellRows
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCellRowsWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatCells
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayerDomArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayerCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayerDenote
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayerDenoteWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatCellsDomArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatCellsCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWireCells
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWireCellsDomArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWireCellsCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRelEquivCast
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWireCellsDenoteId
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayerDenoteCatSplit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatLayers
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpLayersWF
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpLayersWF.nil
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpLayersWF.cons
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersDenote
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersDenoteWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersCodArityCat
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersWFCat
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersDenoteCat
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayer
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayers
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayerDomArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayerCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayersCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayersWF
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayerDenote
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayersDenote
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpDiagram.mk
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpDiagram.sourceArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpDiagram.layers
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDiagramCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpDiagramWF
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDiagramDenote
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDiagramDenoteWidth
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatEqB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpNatEqBSound
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersWFB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpLayersWFOfB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDiagramWFB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpDiagramWFOfB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadDiagramWF
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadDiagramCodArity
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadDiagramDenoteDecomp
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpConvBundle
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpConvBundleSymm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpConvBundleTrans
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpConvBundleOfChecks
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.xMonoidAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.xMonoidComm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.xMonoidUnit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.zComonoidCoassoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.zComonoidCocomm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.zComonoidCounit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.zMonoidAssoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.zMonoidComm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.zMonoidUnit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.xComonoidCoassoc
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.xComonoidCocomm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.xComonoidCounit
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgCopyMult
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgSquare
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgUnitCopy
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgBone
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgCopyMultDual
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgSquareDual
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgUnitCopyDual
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.bialgBoneDual
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.hopf
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.boneX
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.boneZ
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.frobeniusXLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.frobeniusXRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.frobeniusZLeft
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.frobeniusZRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.specialZ
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.specialX
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.cupCoincide
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.capCoincide
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.zIdentitySpider
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpRowTag.xIdentitySpider
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowLhs
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowRhs
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowBundle
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatCellsNilRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCatLayersNilRight
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWhiskerLayersZero
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpPadDiagramIdentityAt
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpWindowMove
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpWindowMove.row
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpWindowMove.splitLayer
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpSplitLayerBundle
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpWindowMoveBundle
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpStep
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpStep.pad
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpStepBundle
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpConv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpConv.step
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpConv.refl
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpConv.symm
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.ZxpConv.trans
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpConvSound
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpConvSpanEqB
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpRowConv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpHopfFire
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpHopfConv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpBialgebraSquareFire
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZChainedPairDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZFusedTripleDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXChainedPairDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXFusedTripleDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZFusionFire
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXFusionFire
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZUnitDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpXUnitDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZUnitXUnitSpanDistinct
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpZUnitXUnitNotConv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCrossingDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpParallelWiresDiagram
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCrossingWiresSpanDistinct
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCrossingWiresNotConv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpScalarCollapse
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpScalarCollapseFire
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpClosedBonesConv
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpIllFormedDetected
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.fxWpZx_hasRelationSemantics
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.fxWpZx_hasRowSoundness
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.zxpCompletenessStatement
#assert_no_axioms FX1Poly.Polygraph.Omega.ZXPhaseFree.fxWpZx_hasCompleteness

end FX1PolyAudit
